### ISSUE TITLE
[ALM Accelerator - BUG]: Error when executing "coe alm install -f quickstart.json" in step "Pipeline repository pipeline import"

### ISSUE THREAD

**Issue by Reinhard-S** [microsoft/coe-starter-kit#3469] opened 2022-08-17 09:55 UTC
### Describe the issue

The current version of coe-cli does not execute file ./src/powershell/importpipelinerepo.ps1 as intended and throws an exception instead.

I was able to do a quick fix locally on my machine as described in my comment:
https://github.com/microsoft/coe-starter-kit/commit/8b1da3870383570e2285195ea8ec483310248df6#r81397040

Could you please implement a fix which takes care of the issue? Thank you.

Best Regards,
Reinhard

### Expected Behavior

Contents should be available within the repository after that step instead of the exception.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2022

### Steps To Reproduce

1. Prepare an empty DevOps project and repository without any contents
2. Use a config referring to that project / repository
3. Run "coe alm install -f quickstart.json"

**Comment by piyushpaliwal** [comment] 2022-08-17 11:29
I faced the same situation and the workaround that I took was to run my coe install command from within the `coe-cli` folder. Went through like a charm.

**Comment by Reinhard-S** [comment] 2022-08-17 13:02
> I faced the same situation and the workaround that I took was to run my coe install command from within the `coe-cli` folder. Went through like a charm.

That's also a good idea but I wanted to keep the actual CoE-CLI application files separated from the operations I perform. 
I executed the installation for one of our customers therefore I'd like to save that configuration json as well as all other resources generated within separated directories.

**Comment by mikefactorial** [comment] 2022-08-18 01:29
This is a documentation related issue. While we could add some configuration to assist the cli ultimately running the install from the correct location is the root cause of this issue. @Reinhard-S if you have a suggestion on a better solution let us know. Closing this out for now as we've included @piyushpaliwal original issue in [#3437](https://github.com/microsoft/coe-starter-kit/issues/3437)

**Closed** 2022-08-18 01:30 UTC
Labels: bug, alm-accelerator

**Comment by Reinhard-S** [comment] 2022-08-18 07:00
> This is a documentation related issue.

I provided a possible solution in comment https://github.com/microsoft/coe-starter-kit/commit/8b1da3870383570e2285195ea8ec483310248df6#r81397040 which worked for me.
