### ISSUE TITLE
[CoE Starter Kit - BUG] Get Parent Bot ID in Admin | Sync Template v3 (PVA) fails

### ISSUE THREAD

**Issue by GoerdesM** [microsoft/coe-starter-kit#2501] opened 2022-04-19 06:36 UTC
### Describe the issue

The flow Admin | Sync Template v3 (PVA) fails with an error message "InvalidTemplate. Unable to process template language expressions in action 'GetBotID' inputs at line '0' and column '0': 'The template language expression 'first(body('List_bot_for_a_botcomponent')?['value'])['botid']' cannot be evaluated because property 'botid' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'"

![image](https://user-images.githubusercontent.com/103028386/163940505-03b31189-a63d-426c-a861-2074c83de9f1.png)

The flow fails for the default environment as well as for a Test environment. 

![image](https://user-images.githubusercontent.com/103028386/163940582-8058aca4-ae55-4acb-aad2-1c451f876ad9.png)

### Expected Behavior

Flow should work without any errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18 for Teams

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

Just start the corresponding flow

**Comment by xmihux** [comment] 2022-04-20 08:30
Hi, this has already been raised e.g. here: https://github.com/microsoft/coe-starter-kit/issues/2402

A quick fix before the CoE is updated seems to be this:

The current GetBotID action is:
`first(body('List_bot_for_a_botcomponent')?['value'])['botid']`

And a question mark before ['botid'] solves the problem and we get a null rather than an error:
`first(body('List_bot_for_a_botcomponent')?['value'])?['botid']`

**Comment by Jenefer-Monroe** [comment] 2022-04-20 09:29
Thanks for adding this comment! Closing as Duplicate of #2402

**Closed by Jenefer-Monroe** 2022-04-20 09:29 UTC
Labels: bug, coe-starter-kit

**Comment by medicineshow** [comment] 2022-04-25 11:45
we just added a comment to #2402 . Are you able to respond please

**Comment by GoerdesM** [comment] 2022-04-26 12:01
Hi, I will wait for the May release to check this again.You can close this ticket as duplicate. Thanks
