### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI "Introduction" page buttons setting incorrect query strings for page navigation

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#1531] opened 2021-11-24 07:47 UTC
### Describe the issue

I am trying to compare data from Power Platform analytics and CoE Dashboard and its seems that data is not matched exactly 

CoE Power BI Dashboard:

![CoEAppReport](https://user-images.githubusercontent.com/30046543/143200022-bd87c6ea-e28c-4f06-83e7-e3f914f2c1ca.png)

Power Platform Analytics:  

![image](https://user-images.githubusercontent.com/30046543/144976619-619a4860-4f7d-4794-b00b-1bdb5c9af205.png)

### Expected Behavior

Data should be matched in both environment (Power Platform analytics and CoE Power BI report)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Power BI Report

### Steps To Reproduce

Open Power Platform analytics and CoE Power BI report and match the Apps/Flow/Cloud Flow count

**Comment by manuelap-msft** [comment] 2021-11-24 08:21
This is expected behaviour! 

On the first one, this looks correct to me: Both the Admin Center and CoE display 1 Group and 2 Users as shared with. The number you highlighted is Unique Users - we get this information from the Audit Log based on Launches, this information is not available in the Admin Center analytics and it shows you the number of unique users that have launched the app. As the 1 Group your app is shared with could consist of hundres of users, this number seems ok to me. For comparision, you would want to compare with Users Shared not Unique Users. 

We have a limitation on what custom connectors can be gathered in the CoE starter kit: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#missing-custom-connectors - but I'm not quite sure what discrepancy you found in your data, could you elaborate what's missing?

Manuela

**Comment by sharmajitendralal** [comment] 2021-11-24 10:16
Query: Custom connector count and display name is not matched exactly when i was extracting data from PowerShell 

CoE Dasboard reported : 43 + 5 custom connector
Using PowerShell reported : 40 custom connector

CoE Screen shot: Seems that regular connector name in shared power apps grid not custom connector 

![image](https://user-images.githubusercontent.com/30046543/143219162-acc07d43-4a43-4311-aea9-4c3f044e0a49.png)

PowerShell report: This is actual custom connector display name
![image](https://user-images.githubusercontent.com/30046543/143218918-4d0abc4b-f7c8-4627-a386-de1cbfdb4d07.png)

**Comment by manuelap-msft** [comment] 2021-11-24 12:19
Hello,

the PowerShell cmdlet does not return custom connectors that are in solutions - the CoE Starter Kit also includes custom connectors that are in solutions. Due to the way the different mechanisms work, slight discrepancies like that are expected. 

Manuela

**Comment by sharmajitendralal** [comment] 2021-11-25 03:57
OK, Thanks for update...
but if I can forget the count for the time being still custom connector name is completely not matched with PowerShell report the old CoE Power BI report, Here is screen shot from 

CoE Power BI Dashboard - October release: 

![image](https://user-images.githubusercontent.com/30046543/143376843-9e9462f4-4d8b-4f35-a322-2cc28f60d6ab.png)

 CoE Power BI Dashboard - March release: 

![image](https://user-images.githubusercontent.com/30046543/143376974-a068e815-10ee-4b9b-80c2-09fca611ff58.png)

Power Shell Report: 

![image](https://user-images.githubusercontent.com/30046543/143377019-6deeb17b-05b6-4657-bb47-378557e080da.png)


Its seems that in October release Power Apps Custom connector report is not correct because listed connector in grid is not custom connector

**Comment by sharmajitendralal** [comment] 2021-11-25 05:38
Hello Manuela,

One more conflict display in Environments report 
here you can see count is same for Total Env, Trial Env, Developer Env

![image](https://user-images.githubusercontent.com/30046543/143385656-f94fec16-f2d7-41e9-b06a-28f8955cfa70.png)

**Comment by sharmajitendralal** [comment] 2021-11-25 06:39
Hello Manuela,

Sorry I am facing another issue..

In Cloud Flow section : Filter available for limited Environment, here you can see in screen shot

![image](https://user-images.githubusercontent.com/30046543/143391631-541a5e20-25f4-4c58-9f84-9f1cc5144053.png)

I want ensure you there is no filter apply on this page

**Comment by sharmajitendralal** [comment] 2021-11-29 05:44
Hello Manuela,

Please suggest..
How should I move further ?

Jitendra

**Comment by sharmajitendralal** [comment] 2021-12-01 05:00
Yes, PBI also upgraded as per 3.13 version

We are facing this gap in new version 3.13, if you are looking back to my previous shared screen shot 
then you can see environment count is Correct in "Overview Power Automate" section but  for " Overview PowerApps" its not correct 

**What about custom connector count ?** Its completely different to actual value and count 
We have only 43 custom connector but its showing 633 and value is also not matched completely

Please help me to resolve the all gap or let me know if required to upgrade it with newer version

**Comment by Jenefer-Monroe** [comment] 2021-12-01 05:25
You have a lot of issues at play in this bug so I'm having trouble tracking.

I do not repro this:

> ![image](https://user-images.githubusercontent.com/30046543/143385887-6c698ad2-0382-44d7-a34b-a55508e452e3.png)

Nor do I repro this, both these cards have the exact same data in them so they are the same number for us:

> ![image](https://user-images.githubusercontent.com/89584709/144176666-09ab084a-5018-40f1-b145-5041357b094f.png)

At this point I suggest you just try with a fresh copy of our dashboard. 
Here is our December version: https://github.com/microsoft/coe-starter-kit/tree/coe-december/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

**Comment by sharmajitendralal** [comment] 2021-12-01 10:35
Same Issue with new version December one: 

Still custom connector count wrongly appear in "Overview PowerApps section" but fortunately Env count seems consistent in both interface 

Overview PowerApps
![image](https://user-images.githubusercontent.com/30046543/144218123-fcd5a5b1-782e-4768-a38c-a04a9a4c30df.png)

Overview PowerAutomate

![image](https://user-images.githubusercontent.com/30046543/144218377-80af1c66-e78e-4202-9b19-9722cc7d868b.png)

**Comment by sharmajitendralal** [comment] 2021-12-06 03:21
Hello Jenefer-Monroe,

Please help me to understand, What's the cause behind this conflict 

Regards,
Jitendra

**Comment by sharmajitendralal** [comment] 2021-12-07 05:34
Hello Team,

I am looking for your help to resolve the issue

As you can see in the shared screen shot custom connector count is not consistent and Same environment  appearing two times 

![image](https://user-images.githubusercontent.com/30046543/144972348-9c175389-35b5-44d6-a6b5-6c1955a8f79e.png)
  

Regards,
Jitendra

**Comment by sharmajitendralal** [comment] 2021-12-09 06:04
Hello Team,

I am still looking for solutions

**Comment by manuelap-msft** [comment] 2021-12-09 08:16
Hello,

please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support 

We do not have a support team that can help resolve issues, and support is provided on best endevaours without SLA via GitHub. We will look into your issue, but at the moment can not provide a timeline.

Thank you for your patience,
Manuela

**Comment by sharmajitendralal** [comment] 2021-12-14 08:28
Hello,

In this case, Please help me to know that how will I get notified once the issue resolved

secondly, let me know that the same issue is replicated on your side or not Or any log is required from my side ?

**Comment by manuelap-msft** [comment] 2021-12-16 08:50
You are experiencing a lot of issues that we have not seen before and that we do not repo.

I suggest running a full inventory to make sure your inventory in the CoE tables is up to date - please follow these steps exactly and note that it may take a while to complete:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#incomplete-inventory

For the Power BI Count, this visual on the Overview Power Apps page has the highlighted filter set to only show connectors where isCustomAPI is true. The entire group at the top is the same across all Overview pages, and pulls information from the same tables so it's simply not possible that the count is different. You may have accidently removed the filter as you made changes to the dashboard. I can confirm that our latest released version (December), which Jenefer pointed to earlier, has this filter set. You can add this filter manually yourself by looking for the isCustomApi field and setting the filter value to true.
![image](https://user-images.githubusercontent.com/55705669/146338428-0791dca7-2bb5-4789-8b96-fdda4a221fb9.png)

**Comment by sharmajitendralal** [comment] 2021-12-21 05:34
Thanks for your help on filter part..

Now connector count seems ok after applied the suggested filter, please help on other count issue 

"Created this month" section showing wrong count in both page "Overview-PowerApps and Overview-Power Automate and other section" I did not do any changes in default template seems that default setting not correct  

Working on to run the full inventory....will update you once completed

**Comment by sharmajitendralal** [comment] 2021-12-21 10:55
I have updated the full inventory as suggested but still getting the same issue ..

Its seems that there is issue in introduction page, This page carry query string and update the target page accordingly

 Step to reproduce the issue

1. Click on Introduction page and select the Overview Power Apps 

![CoEIntro](https://user-images.githubusercontent.com/30046543/146918029-5487d972-519d-4ee6-b8af-1c772a387382.PNG)

2. On the Overview Power Apps page focus on custom connector count 

![CoEPowerAppReset](https://user-images.githubusercontent.com/30046543/146918327-a31f40d1-bd5f-468a-a21f-39e1bc05d084.PNG)

3. After Reset the page custom connector count appear correctly

![CoEPowerApp](https://user-images.githubusercontent.com/30046543/146918425-c3843fb1-05d0-4b0f-b1fe-4628985d64fc.PNG)

**Comment by manuelap-msft** [comment] 2021-12-22 11:14
Hello,

you're right - there was an issue with the navigation from the Introduction page to the sub-pages that caused the filters for custom connectors and created this month to disappear.

You can fix this yourself by selecting the button on the Introduction page, and in the Format Button pane changing the Action from Bookmark to Page Navigation > Overview Power Apps for the Power Apps button and Page Navigation > Overview Power Automate for the Power Automate button. 
![image](https://user-images.githubusercontent.com/55705669/147084338-e729a380-1850-4a17-a2d9-71833d4c1bae.png)

I am also fixing this locally and it will be part of our next release mid-January.

**Comment by manuelap-msft** [comment] 2021-12-22 11:15
> 
> Now connector count seems ok after applied the suggested filter, please help on other count issue
> 

I am afraid I don't follow, what "other count issue" do you still need help with?

**Comment by sharmajitendralal** [comment] 2021-12-23 05:53
Thanks ..

But I am still not able to find out the root cause, Why environment name appearing two times with different app count in Overview Power Apps section

**Comment by manuelap-msft** [comment] 2021-12-23 09:23
Have you done a full refresh of the Power BI data after you ran the Full Inventory? Can you open the Power Platform Admin View (model driven app part of the Core components solution) and check the Environments page there - are the environments showing up double there as well?

**Comment by Jenefer-Monroe** [comment] 2021-12-23 13:03
Hi there. Pulling all our asks into one place. 

Can you please do the following? 

1) As Manuela has asked, have you refreshed the data in the PBI since you ran the full inventory? 

1) As Manuela has asked, please see if these show up twice in the product admin pages: https://admin.powerplatform.microsoft.com/

1) Ensure all the flows in the Core solution that begin with the word **_CLEANUP -_** are turned on, running, and passing, and that they dont have any unmanaged layers.
![image](https://user-images.githubusercontent.com/89584709/147242513-4365c13b-844b-4d05-b264-686bb1ce7230.png)

1) Export the data from the Environments table (note you cannot do this from the solution itself, see picture below), find a pair of the duplicate records (ex **_Architecture Tests_** and **_Architecture Tests (org8xxxxx2)_** and return with an obfuscated list of the following fields: admin_environmentid, admin_environmentcdsinstanceurl, admin_environmentcreatedon, admin_environmentdeleted, admin_environmentmakerdisplayname, admin_environmentsku, admin_environmentname

1) For clarity, and in case its obfuscated away, do they have the same values for admin_environmentid? for admin_environmentname? 


**How to Export the table**
![image](https://user-images.githubusercontent.com/89584709/147242961-45d84de3-4b91-4a09-b0f2-3d6c2e697ffc.png)

**Comment by sharmajitendralal** [comment] 2021-12-24 10:05
Thanks both of you..

After refreshed the data now duplicate issue resolved :)

But I can see some Power automate without environment name

![image](https://user-images.githubusercontent.com/30046543/147343217-c5bb46f3-dd03-434b-8031-fb69bba77456.png)

**Comment by Jenefer-Monroe** [comment] 2021-12-27 13:36
Please ensure all the flows in the Core solution that begin with the word **_CLEANUP -_** are turned on, running, and passing, and that they dont have any unmanaged layers.
![image](https://user-images.githubusercontent.com/89584709/147242513-4365c13b-844b-4d05-b264-686bb1ce7230.png)

**Comment by sharmajitendralal** [comment] 2022-01-03 05:34
Hello, Thanks for your suggestion 

I have verified and found all CLEANUP - are turned on and there is no unmanaged layers

![CleanUPFlow](https://user-images.githubusercontent.com/30046543/147901971-68daef74-3b0f-4e9c-b371-759a67da369a.JPG)

**Comment by Jenefer-Monroe** [comment] 2022-01-03 14:42
This issue is tracking way too many things. And it is now marked as fixed for January for the issue of the link from the home page. 
Please post one issue per issue, we cannot continue to track mega threads like this as it does not allow search or tracking.

**Comment by sharmajitendralal** [comment] 2022-01-04 08:37
Ok got it, I will keep in mind in future

**Comment by mikefactorial** [comment] 2022-01-06 21:19
@sharmajitendralal This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by mikefactorial** 2022-01-06 21:19 UTC
Labels: coe-starter-kit, vnext
