### ISSUE TITLE
BYODL dataflow error "We found extra characters at the end of the JSON input" 

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#6725] opened 2023-09-27 06:57 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The dataflow refresh had been working since setting it up earlier this month, then it started failing on September 21st.

The CoE BYODL Makers dataflow is failing with error :
Error Code: Mashup Exception Data Format Error, Error Details: Couldn't refresh the entity because of an issue with the mashup document MashupException.Error: DataFormat.Error: We found extra characters at the end of the JSON input. Details: Value = ,;Position = 10053

### Expected Behavior

Dataflow refresh should complete succesfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE BYODL Makers dataflow

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

<img width="701" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/b5b840c4-0e96-486d-84d8-d32f6dcb8d0a">

**Comment by manuelap-msft** [comment] 2023-09-27 07:31
Closing as duplicate of: https://github.com/microsoft/coe-starter-kit/issues/6723

**Closed by manuelap-msft** 2023-09-27 07:31 UTC
Labels: bug, coe-starter-kit
