### ISSUE TITLE
Unable to Install CoE Starterkit Core Solution 4.17 Nov 2023

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#7077] opened 2023-11-10 23:12 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Importing the core solution 4.17 from Nov 2023 release throws an error in Power Apps interface

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/467aece3-88be-4108-88cb-59bc9a85a704)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/0965ed2a-9e5c-475c-8257-e9b107351122)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/63a2ee73-9782-4466-8b8b-5c0ba4ce2d9e)

### Expected Behavior

Installation should allow proper import of solution

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Core Solution Import

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Navigate to make.powerapps.com
2. Import the solution 4.17 (Nov 2023 release)
3. Import process throws error

AB#819

**Comment by Jenefer-Monroe** [comment] 2023-11-11 00:10
Hello, this is a dupe of https://github.com/microsoft/coe-starter-kit/issues/7050 which is a product bug that impacts some subset of people. 
Product support was able to find a workaround which is explained here: Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240
I'll go ahead and close out as a dupe.

**Closed by Jenefer-Monroe** 2023-11-11 00:10 UTC
Labels: bug, coe-starter-kit
