### ISSUE TITLE
[ALM Accelerator - BUG]: Import unmanaged to dev environment fails

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#4050] opened 2022-10-26 22:06 UTC
### Describe the issue

We had a repo that had an older application that had not been upgraded to the new folder structure for App Modules vs App Actions. 

The import failed with the following in the log:

Cannot add a Root Component <AppNameRemoved> of type 80 because it is not in the target system

The full log is attached.
[log.txt](https://github.com/microsoft/coe-starter-kit/files/9874010/log.txt)

### Expected Behavior

If we didn't have the app imported into an existing environment where we could commit changes again, we wouldn't have been able to get imported.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

October 2022 - HF1

**Comment by mikefactorial** [comment] 2022-10-26 22:15
Hey @rfarris2000 mind sharing a screenshot of the solution's repo structure. We've gotten similar feedback from others who have upgraded from older versions. We may have missed an upgrade scenario here.

**Comment by rfarris2000** [comment] 2022-10-26 22:17
![image](https://user-images.githubusercontent.com/1624416/198149096-c9bdb628-7a36-423b-ac39-a10d4ee793f7.png)

**Comment by rfarris2000** [comment] 2022-10-26 22:19
New version after recommiting:

![image](https://user-images.githubusercontent.com/1624416/198149318-249070d0-89d1-4023-95ab-6950bbf4dbdb.png)

**Comment by Ballzer0** [comment] 2022-10-28 11:58
This issue is related to the one im experiencing here.
https://github.com/microsoft/coe-starter-kit/issues/4029

We have found a manual workaround for this. Im currently manually editing each solution to reflect the new folder structure.

how i fix a solution manually
1. add **src** folder into SolutionPackage
2. move everything into src
3. add {solutionName}.cdsproj file to solution package (just copy from a working solution and rename it)
4. Restructure config folder to follow new structure with Validation/Test/Prod folder
5. push the changes to a new branch in git called "restructured-{solutionName}"
6. import changes to solution into my own dev environment
7. configure deployment settings
8. immediately push commit solution throgh the ALM-Accelerator app 

its quite the list, but it seems to do the trick, have fixed 4 solutions by going through this process

**Comment by Ballzer0** [comment] 2022-10-28 12:20
another way to get the import the solution is to the last production pipeline that ran.

open the artifacts
![image](https://user-images.githubusercontent.com/28560729/198585300-9f2ebe56-48b1-44ea-9425-af270105f2a8.png)

download the unmanaged solution and manually import it to your dev environment.
![image](https://user-images.githubusercontent.com/28560729/198585531-f25baea8-e219-408a-90c6-bb686d257c18.png)

this only works if you still have your pipeline history.

**Comment by RajeevPentyala** [comment] 2022-11-07 10:39
@Ballzer0 Can you please confirm whether your solution has Model Driven Applications (MDA)? I am curious to know the manual work around you shared worked for a solution, which has MDA component.

**Comment by RajeevPentyala** [comment] 2022-11-28 13:17
@rfarris2000  "Cannot add a Root Component of type 80 because it is not in the target system" issue is caused by "App Module" component part of your solution. Possible reason for this issue could be either due to the corruption of committed solution files or something has been modified on target environment.
From your last comment, I believe you've committed solution again which restructured the folders. Please confirm if you able to Import the Solution with the restructured folders.

**Comment by rfarris2000** [comment] 2022-11-29 17:49
I was able to recommit and this restructured all of the files.  However, if we hadn't had the app imported into an environment already there would not have been a way to rehydrate it from source.

**Comment by mikefactorial** [comment] 2022-12-07 16:39
@rfarris2000 closing this out for now as a duplicate of #4029. Will continue to track against #4029 to see if there's anything we can do to resolve this.

**Closed by mikefactorial** 2022-12-07 16:39 UTC
Labels: bug, alm-accelerator
