### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connection Identities) Flow Errors

### ISSUE THREAD

**Issue by JeromieSkypoint** [microsoft/coe-starter-kit#4305] opened 2022-11-29 23:55 UTC
### Describe the issue

Admin | Sync Template v3 (Connection Identities) in the CoE Starter Kit fails 1 or of every 20 or so runs

![image](https://user-images.githubusercontent.com/117628477/204674077-8d893b1e-d952-455a-9b86-fec2e21c7b34.png)

### Expected Behavior

Flow succeeds/ 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

**Comment by JeromieSkypoint** [comment] 2022-11-30 19:32
Errors starting occurring after implementing CoE update

**Comment by Jenefer-Monroe** [comment] 2022-11-30 23:56
Thank you for posting, looks to be a duplicate of https://github.com/microsoft/coe-starter-kit/issues/4086. Will investigate with that bug.

**Comment by Jenefer-Monroe** [comment] 2022-11-30 23:56
Duplicate of #4086

**Closed** 2022-12-01 01:50 UTC
Labels: bug, coe-starter-kit
