### ISSUE TITLE
[CoE Starter Kit - BUG] Not able to see all the Environments list in Set Flow Permissions Admin app.

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7042] opened 2023-11-08 06:24 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We were not able to see the flows list from few of the Environments present in our Tenant in both Flow table and as well as Set Flow Permissions App, we have checked the dataflows and all the dataflows runs are successful.

could you please assist us on this issue.

<img width="414" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/e49ec99d-8374-4bea-8c02-a02798275f3c">

<img width="209" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/35e16ab9-0a4c-4ba7-b415-333dd9556ba4">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Flow

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

We were not able to see the flows list from few of the Environments present in our Tenant in both Flow table and as well as Set Flow Permissions App, we have checked the dataflows and all the dataflows runs are successful.

could you please assist us on this issue.

<img width="414" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/e49ec99d-8374-4bea-8c02-a02798275f3c">

<img width="209" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/35e16ab9-0a4c-4ba7-b415-333dd9556ba4">

AB#751

**Comment by Jenefer-Monroe** [comment] 2023-11-08 13:37
Lets see if they are in the storage account from the Data Export
Go to your storage account and use the storage browser so that you can sort/filter.
Go to the flows folder and search by the GUID of the environment for which you are not seeing data. The file name is based on the envt GUID.
Do you find it? When does it say it was last modified? And if you download it, do you see expected flows in there?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b1036ef0-7ec7-4b43-8abe-9cd3ac634bc9)

**Comment by ALSPowerPlatform** [comment] 2023-11-09 06:15
We can see all those environment GUIDS in storage account, with modified date as 11/8/2023, 4:14:34 PM. and can search flows in the downloaded file, but not able to see the flows or environments in Flows table and set flow permissions app.

<img width="521" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/cafec438-e8c4-4ffc-b5ff-43d492884dab">

**Comment by Jenefer-Monroe** [comment] 2023-11-10 12:58
Next please check to make sure your Dataflows are all running each day and passing
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/189d035f-cf14-4ec4-9613-5fb2f4c43bc0)

**Comment by ALSPowerPlatform** [comment] 2023-11-13 16:25
<img width="781" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/042421d0-7712-4c58-89fb-0f32a1462a20">

Observed that Flow: CoE BYODL - When Maker dataflow refresh is complete is failing with below error, Could you please assist on the issue.
<img width="569" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/1d4ccb6f-8c08-49c8-a311-02bff6b89ee8">

**Comment by Jenefer-Monroe** [comment] 2023-11-13 18:34
Can you please tell me, were these flows on and running? That will help us understand the original issue you posted, then we can also look at this individual failure.

**Comment by Jenefer-Monroe** [comment] 2023-11-13 18:38
Can you please share what was returned from this call?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3e3f16c0-8e2b-49d1-9cfc-2904a4b3edb3)

**Comment by ALSPowerPlatform** [comment] 2023-11-14 04:53
<img width="327" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/d0ef7008-dea8-4b38-897f-0ac415e85b8b">

returning output in this way
<img width="899" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/30096446-18fa-4e2e-bbd0-925ab0304703">

**Comment by Jenefer-Monroe** [comment] 2023-11-14 10:22
Thank you, and what is returned from this call for the failures?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/071799f4-fe26-4bae-870a-f714761a1f46)

**Comment by ALSPowerPlatform** [comment] 2023-11-15 05:46
Here is the screenshot

<img width="955" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/889b6a95-5a80-46bf-97d7-11b47552b0e8">

**Comment by Jenefer-Monroe** [comment] 2023-11-15 20:36
Its a little hard for me to see that output but it loks like its missing the Display Name. 
Can you please go to that table and look for the GUID to see if the user is present and if so if its missing its Display Name
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/216ba8d6-8794-4f43-8791-fe218ebe399a)

**Comment by ALSPowerPlatform** [comment] 2023-11-16 04:29
We see that the display name is coming blank in the table

<img width="540" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/856c4bdb-d298-403c-a599-5607a35665b0">

**Comment by Jenefer-Monroe** [comment] 2023-11-16 11:35
Do you have this flow turned on and running? 
CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

It cleans up this table as well when it runs


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2b6eb74e-d9a0-4cd7-b4d2-675983b45ff0)

**Comment by Jenefer-Monroe** [comment] 2023-11-16 11:42
And if that flow is on and running, can you please look up these users with blank information in the Maker table (by the GUID) and see if they are marked as Service Principles? 

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3aa8072f-494a-44f3-a307-6990ccea30ed)

**Comment by Jenefer-Monroe** [comment] 2023-11-16 12:42
If these are service principles then I think the issue is now understood and fixed for Dec. 
You can see the fix here https://github.com/microsoft/coe-starter-kit/issues/7136#issuecomment-1814364745

**Comment by ALSPowerPlatform** [comment] 2023-11-17 04:36
This flow is on and running
<img width="514" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/da957dc9-6b20-4c94-a00b-54883d69a5d5">

<img width="810" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/c7781220-eeb1-400d-a8f8-2375816b0cbf">

We are seeing Makers table as Makers(2) and not able to find the UserisServicePrinciple field.

<img width="581" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/34caf83d-054e-4f6d-b9c1-a4e9ecdf7bf4">

**Comment by Jenefer-Monroe** [comment] 2023-11-17 13:32
Can you apply this fix locally to the **_CoE BYODL - When Maker dataflow refresh is complete_** flow and see if it resolves the issue?
https://github.com/microsoft/coe-starter-kit/issues/7136#issuecomment-1814364745

**Comment by Jenefer-Monroe** [comment] 2023-11-26 14:58
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-11-26 14:58 UTC
Labels: bug, coe-starter-kit

**Comment by ALSPowerPlatform** [comment] 2023-11-28 11:09
@Jenefer-Monroe even after applying the above solution, still we are not able to see many of our environments in both the tables and set flow permissions app. Could you please help us on this, please find the screenshots below with difference.

<img width="707" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/1ee65f6a-85e1-46b9-bb9f-a4c8ef5323f1">

<img width="182" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/3a6e1222-a23e-4dd5-9db5-527593df1430">

**Comment by ALSPowerPlatform** [comment] 2023-12-12 05:05
could you please update us on this issue.
