### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to upgrade the Center of Excellence - Core Components Solution 

### ISSUE THREAD

**Issue by ortizh** [microsoft/coe-starter-kit#8515] opened 2024-06-19 17:08 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am unable to upgrade the "Center of Excellence - Core Components "  version June 2024. I am getting the following error :

![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/14ba98c6-01b6-407a-9e92-21cf43f3663a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3635

**Comment by Jenefer-Monroe** [comment] 2024-06-19 17:34
Unfortunately it looks like you've hit a product bug around upgrade. A few other people have hit this too. Please see https://github.com/microsoft/coe-starter-kit/issues/8466. 
### The connection
This is likely the legacy Dataverse connection that is at play, why it wont tell you the name I don’t know. 
But this is a connection that we have removed from the kit and that is causing issues in the product’s upgrade code.
### The likely issue
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 
### Find impacted flows
Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8186341-cf26-4710-aa3c-8b3e3bb9f2ea)
### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.
And another user has succeeded with this workaround. See https://github.com/microsoft/coe-starter-kit/issues/8466

**Comment by Jenefer-Monroe** [comment] 2024-06-25 13:13
Closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-06-25 13:13 UTC
Labels: duplicate, question, coe-starter-kit

**Comment by ortizh** [comment] 2024-06-28 17:32
@Jenefer-Monroe thank you!! 
Would I need to follow the steps above for all of these? 
![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/f57f6ec2-13cb-49e1-9856-4c763456d5d9)
