### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to start flows due to connection references missing connections

### ISSUE THREAD

**Issue by SheraHintzen** [microsoft/coe-starter-kit#6761] opened 2023-09-29 22:04 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I downloaded the COE Starter Kit and set up my connectors. When I try to start the child flows I get an error. 
First Error: Unable to start flow due to connection references missing connections. Set the connections on the connection references before starting.

I see that this error is mentioned in the setup documentation, so I tried the recommend work around and edit the run-only users. Then I get another error (see screenshot).  This is hit or miss. 

I could turn on several flows by editing the flow, reestablishing the connection, saving the flow, republishing it and then turning it on. This is a work around I shouldn't have to do.

I opened a MS ticket TrackingID#2309270010002483 and the support engineer determined this is an issue with the COE. I can create a new flow with the dataverse connectors and it worked just fine. 

![start error](https://github.com/microsoft/coe-starter-kit/assets/146489937/6580d843-e112-4587-8504-973fd82a9279)
![run only error](https://github.com/microsoft/coe-starter-kit/assets/146489937/191165ae-3259-4ccc-98b8-91ff1c44e0fc)

### Expected Behavior

I should be able to turn the flows on without connector errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

All flows

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Download the COE Starter Kit
2. Add connectors
3. Follow directions and turn on child flows. 
4. Start with Helper- Add User to Security Role flow, click turn On
5. I get the first error
6. Then I try to edit the run users and get the second error.

**Comment by Jenefer-Monroe** [comment] 2023-09-30 16:22
Did you install the kit as a different identity than you are now using the kit? 
Go to the default environment > Connection References. Make sure they are all attributed to you.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f2cdff2c-a270-4bd7-b015-07281cf9a2a0)

**Comment by SheraHintzen** [comment] 2023-10-03 14:56
All the connections are associated with the COE service account. And my connection reference isn't in the same area yours is. Not sure if that makes a difference.


***@***.***
***@***.***
Shera H.

**Comment by Jenefer-Monroe** [comment] 2023-10-09 16:35
I'm afraid we are just using a product feature here, and it works for most people so the issue is in some configuration in your tenant. 
We have seen this issue before and it always had to do with the health of the connection. Some people simply deleted and recreated those connections to resolve.

**Comment by Jenefer-Monroe** [comment] 2023-10-11 15:48
If that's something you can do then yes I would suggest just starting from scratch. 
Note also that its highly recommended that you use the **CoE Setup and Upgrade Wizard** to install or upgrade the kit. It allows you to not worry about the order of turning flows on / new environment variables etc. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7901e1e-4c2a-442a-ba27-dfbeb62332bb)

**Comment by SheraHintzen** [comment] 2023-10-11 21:16
Jenefer,

I uninstalled the COE Core Components solution and removed all connectors.

I followed the starter kit documentation and added in all 15 connectors prior to installing the core components solution. When I import the solution I get an error message and it wants to me readd all those connectors. The connectors have already been added, why is it not recognizing it here?

***@***.***
***@***.***
***@***.***



Shera H.

**Comment by Jenefer-Monroe** [comment] 2023-10-12 11:42
My guess is that you are logged in as a different user than you created the connections for, or that there is something else wrong with the identity you are using. 
I'm afraid you are hitting things we cannot really assist with remotely, you may need to contact product support or hire out an expert in CoE to assist.

**Comment by Jenefer-Monroe** [comment] 2023-10-13 12:28
I just had one more thought, if you go to the Default environment > Connection References 
Select each of the managed connection references and make sure its resolved
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9fb8a5d6-6d43-4f60-bb45-ffc69cb2bacc)

**Comment by Jenefer-Monroe** [comment] 2023-10-19 12:46
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-10-19 12:46 UTC
Labels: question, coe-starter-kit
