### ISSUE TITLE
[CoE Starter Kit - BUG] Issue upgrading to CoE Core 4.24 from 4.3

### ISSUE THREAD

**Issue by tripdes** [microsoft/coe-starter-kit#7832] opened 2024-03-13 14:22 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

First off I'd like to start by saying thank you for such an excellent initiative you're delivering here, it's allowing our organisation to make great strides in the world of low and no-code!

We are currently experiencing a problem during the upgrade process of the Center of Excellence (CoE) toolkit from version 4.3 to v4.24. Despite successfully importing the 'CenterofExcellenceCoreComponents_4.24_managed' package and resolving initial issues related to legacy references to the Office 365 Management API custom connector, we are unable to proceed past the 'Run setup flows' step within the 'Center of Excellence Upgrade Wizard'.

Specifically, the 'Admin | Sync Template v3 Configure Emails' flow is not being recognized as complete within the upgrade wizard, despite multiple successful executions. This issue is preventing us from completing the upgrade process and leveraging the new features and improvements within the CoE toolkit v4.24.

We acknowledge the importance of staying up-to-date with the current release of the CoE toolkit and commit to adopting this as our strategy moving forward. However, we need to resolve the current issue to ensure a successful upgrade process.
We are seeking assistance to identify and resolve the underlying cause of this issue, enabling us to continue with the upgrade and stay current with future CoE toolkit releases.

![Screenshot 2024-03-13 122639](https://github.com/microsoft/coe-starter-kit/assets/1639769/e5dfe527-8711-40c8-91d1-8127472b83ee)
![Screenshot 2024-03-13 122553](https://github.com/microsoft/coe-starter-kit/assets/1639769/d834545b-0844-4a8b-a2da-7c1be41b0538)

### Expected Behavior

We should be able to progress all the way through the wizard and complete the upgrade.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3 Configure Emails

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2548

**Comment by Jenefer-Monroe** [comment] 2024-03-13 14:40
Well done getting past the upgrade hurdle! Glad to have you in the current build! 

### Flow passing?
This issue can happen sometimes when connections expire. 
Can you please go see if the flow completed? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6a46aeee-352f-44ff-baa7-2bec468f56fd)

### Fix Connections
You will want to go make sure all your connections are up to date. 
Please log in as the user who’s identity installs and browse to the connections in the envt. 
If there are any broken connections please repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2198fb17-1107-4851-a744-f3b34e89d11d)

### Trick it
If ensuring the flow passes does not fix it, a trick you can do here is to manually flag the flow as having completed. 
Go to the CoE Solution Metadata table, configure it to show the columns below, filter to this flow and set its LastRun to tomorrow and LastRunPassed to Yes
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/afdb43ab-7e2c-48c5-aa75-a0dcd3dcf0a6)

Then once you are done with install be sure to run the **_Admin | Sync Template v3 (Call Updates)_** flow to be sure you got all your emails configured.

**Comment by Jenefer-Monroe** [comment] 2024-03-13 16:29
Looks like your run-only-users setting have gotten messed up. 
Can you please go make sure you dont have any unmanaged layers on that flow? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fa9f04c1-3e04-443c-b9f7-a04abf5c62c0)

**Comment by tripdes** [comment] 2024-03-13 16:35
Funnily enough I was looking at another issue earlier where that was the solution - I can't see any unmanaged layers on those flows. Any idea how we rectify the run-only-users setting @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment] 2024-03-13 20:05
As the identity running the flow, browse to the **_Admin | Sync Template v3 Configure Emails_** flow details page. 
Make sure the **_Connection References_** all show as green checks. And then hit the **_Run only users_** link
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/feed276b-5f2d-433e-9166-685fea564d96)

Select the identity running the flow from the drop down for "Use this connection"
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6e28ee0a-09ee-4c63-9dd5-1c7ed6123abb)

**Comment by Jenefer-Monroe** [comment] 2024-03-14 13:24
I can really only do one issue per GitHub instance so lets please keep this one talking about the configure email issue, and you can post other issues for the other ones you mention above. 

The configure emails flow used to have a schedule trigger but now has a manual as we needed to be able to call from apps as well.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cc8b240a-30b8-4e6e-b18e-bf62b6117598)

So it appears the issue is that upgrade didnt actually upgrade this flow for you. 
What happens if you try to turn it on?

**Comment by tripdes** [comment] 2024-03-14 14:41
Sure thing @Jenefer-Monroe - apologies 😄 if I try and enable it then I get the error message which is included in the following screenshot:

![Screenshot 2024-03-14 114444](https://github.com/microsoft/coe-starter-kit/assets/1639769/a2b583b2-c604-426f-9290-a508af71fe30)

You're right that it appears not to have upgraded this flow as it's still set to 'schedule' despite the import of the new solution appearing to have been successful.

What can we do about this?

**Comment by Jenefer-Monroe** [comment] 2024-03-14 14:56
Its the configure email flow I'm hoping you'll try to turn on for me. And if its already on can you turn it off and back on?

**Comment by tripdes** [comment] 2024-03-14 15:04
Ahh I understand now @Jenefer-Monroe, though unfortunately turning it off and then back on again doesn't appear to have done the trick as it's still retaining the 'scheduled' state:

![Screenshot 2024-03-14 150108](https://github.com/microsoft/coe-starter-kit/assets/1639769/17d0d2af-54e4-498d-a5be-07c041361c0d)

**Comment by Jenefer-Monroe** [comment] 2024-03-14 15:09
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by tripdes** [comment] 2024-03-14 15:12
@Jenefer-Monroe I think it might be the "Center of Excellence - Core Components for Teams" solution. Is this still relevant, or has it been deprecated?

**Comment by Jenefer-Monroe** [comment] 2024-03-14 20:04
Yes that was deprecated. Bummer! I'm not sure how to get you out of that state. I think you might have to uninstall Core and start from scratch

**Comment by tripdes** [comment] 2024-03-14 21:28
Ahh darn @Jenefer-Monroe, that's unfortunate! Is there a way we can uninstall/reinstall whilst preserving historic data, do you know?

Thanks for all your help on this - and I felt we were so close too!

**Comment by Jenefer-Monroe** [comment] 2024-03-14 22:38
What features of the kit are you using? That would help understand what historic data you are trying to preserve.

**Comment by tripdes** [comment] 2024-03-20 09:41
@Jenefer-Monroe apologies for the delay! Could I not just delete the Teams core components solution and avoid the need to completely reinstall? Regarding historic data - on closer inspection I don't think we need to keep anything 🙂

**Comment by Jenefer-Monroe** [comment] 2024-03-26 13:21
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-03-26 13:21 UTC
Labels: bug, coe-starter-kit
