### ISSUE TITLE
[CoE Starter Kit - BUG] Setup wizard errors in GCC - List flows as Admin (v2) not returning all records there

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#6074] opened 2023-07-14 15:11 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have a test CoE environment. Going from core 4.4.2 to 4.11. 

When installing core 4.11, getting banner about tenant ID (happens multiple times through set up wizard)
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/256bc321-f230-4db4-bed6-de1161c3bf4c)

Also getting error loading control on requirements page
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/272f4328-8b3a-4b86-b8db-6a1e5d5c63b6)

was able to continue

When waiting for the flows to run. I waited a bit. Then hit refresh, and 2 of them disappeared. 
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/428a99e4-10ff-4c57-a0e9-e482cb3ea4db)

was able to continue.

### Expected Behavior

Run through set up wizard with no errors. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment] 2023-07-14 15:36
Did you follow the Government cloud specific steps outlined here?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/f7c814ce-517c-44ea-a061-81c71deeda7f)

**Comment by pnoot7** [comment] 2023-07-14 16:45
Yes, left blank during import.

**Comment by Jenefer-Monroe** [comment] 2023-07-14 17:17
Can you confirm, this is an upgrade then not a clean install correct? 
If so, plesae go to the command center > Environment variables > graph url. 
Is it correct for your cloud type?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b1bf3e8-33ac-445d-bcb9-65d527f56abf)

If so, please go turn off and back on these flows. Sometimes env vars get cached and a flow needs reset to see them. 
SetupWizard>CreateGroup
SetupWizard>GetCurrentEnvironment
SetupWizard>GetTenantID
SetupWizard>GetUserDetails

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0ca55af9-8ddf-4db3-a064-e8d96aa9c447)

**Comment by pnoot7** [comment] 2023-07-14 17:42
Correct, going from core 4.4.2 to 4.11. Stated above. 
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/4ea73bc1-d487-4995-a960-f346bf6ea5c0)

The article states that the graph endpoint is the same as commercial. Mine is set to "https://graph.microsoft.com/"

After toggling the flows. Going back into the setup wizard did not give issues on tenant ID and did load the requirements page. Not sure if already completing it did anything either.

**Comment by Jenefer-Monroe** [comment] 2023-07-14 17:53
Wonderful news. It seems like an env var just got cached by flow then.

**Comment by pnoot7** [comment] 2023-07-14 17:56
Would this be recommended to turn these flows on/off when upgrading a production environment? Or any other suggestions to avoid these issues?

Also it let me continue, but I mentioned that some of the set up flows disappeared during the setup wizard. Not sure if that needs to be looked at or not. Can't replicate currently as they are already done.

**Comment by Jenefer-Monroe** [comment] 2023-07-14 18:11
the env var doesnt change so you wont need to ensure that cache goes away again. now that its set and in the flow you are ok. 
but if you see this issue in other envts thats just something you can try.

**Comment by Jenefer-Monroe** [comment] 2023-07-14 18:12
I'm not sure what you mean by the flows disappeared, or what screen you were on. 
During setup there is a screen where the flows are removed as they get toggled on. That might be what you are referencing?

**Comment by pnoot7** [comment] 2023-07-14 18:15
The run set up flows. Third image in original post. It has the three flows that need to run, and it starts showing all three with the moving progress bar. I hit refresh and two disappeared completely, and only one remained with a check mark.

**Comment by Jenefer-Monroe** [comment] 2023-07-14 18:18
ok. feel free to continue with setup now then. I've not seen that happen but can include it in the GCC test pass for the internal team.

**Comment by bwieland86** [comment] 2023-07-14 20:09
I'd like to follow-up on this, as I'm also having issues with doing a clean install (in a new environment) of CoE for initial testing before upgrading. The Setup app hangs on the "Run setup flows" screen and hitting "refresh" never loads anything. 

![image](https://github.com/microsoft/coe-starter-kit/assets/13457692/fdac1c24-28ec-4688-b8bb-153aa08ebe42)

I suspect it may be the result of this:

![image](https://github.com/microsoft/coe-starter-kit/assets/13457692/92b9de9f-6f48-4226-b8db-46f083cb14eb)

**Comment by TigerJ** [comment] 2023-07-18 19:50
> I'd like to follow-up on this, as I'm also having issues with doing a clean install (in a new environment) of CoE into a GCC tenant for initial testing before upgrading and had the same issue regarding the "tenantId" not sticking. I even tried to update it in the Default solution in the environment to get it to hold the value.
> 
> As a result, the Setup app hangs on the "Run setup flows" screen and hitting "refresh" never loads anything.
> 
> ![image](https://user-images.githubusercontent.com/13457692/253672081-fdac1c24-28ec-4688-b8bb-153aa08ebe42.png).
> 
> I did check manually and the SetupWizard -> RunInitialFlows workflow ran successfully, as did the child Admin | Sync Template v3 (Connectors) and Admin | Sync Template v3 (Configure Emails) that the workflow calls. However, the app is "hung" at the "Run setup flows" screen, nothing populates, and I'm unable to continue installation.

I ran through this similar pattern of issues listed here, resolved most of them similar ways and am at the same spot as you [bwieland86](https://github.com/bwieland86) I'll update here if I figure anything out or find anything.

**Comment by TigerJ** [comment] 2023-07-19 20:44
@bwieland86 I have a hunch the issue might be somewhere in here, this is the code called from the canvas app in the step I believe we are moving into. My thought is something is going wrong here, and the refresh button is not operating as expected. The refresh code is below this code block separately.

`//now that environment variables are set, turn on sync flows
Set(
    loadSyncFlowWait,
    true
);
Patch(
    [@'Environment Variable Values'],
    Defaults([@'Environment Variable Values']),
    {
        'Environment Variable Definition': LookUp(
            [@'Environment Variable Definitions'],
            'Schema Name' = "admin_InventoryandTelemetryinAzureDataStorageaccount"
        ),
        'Schema Name': "admin_InventoryandTelemetryinAzureDataStorageaccount",
        Value: If(
            myDataSource.isBYODL,
            "yes",
            "no"
        )
    }
);
//'Admin|SyncTemplatev3CoESolutionMetadata'.Run();
    If(
        myDataSource.isBYODL,
        ClearCollect(
            myFlowstoTurnOn,
            SortByColumns(
                Filter(
                    'CoE Solution Metadata',
                    And(
                        CoESolutionArea = "Inventory",
                        UsedForByodlCoe = 'UsedForByodlCoe (CoE Solution Metadata)'.Yes,
                        !("CoE BYODL" in ObjectName)
                    )
                ), "admin_installorder"
            )
        ),
        ClearCollect(
            myFlowstoTurnOn,
             SortByColumns(
                Filter(
                    'CoE Solution Metadata',
                    And(
                        CoESolutionArea = "Inventory",
                        UsedForSyncFlowCoe = 'UsedForSyncFlowCoe (CoE Solution Metadata)'.Yes,
                        !("CoE BYODL" in ObjectName)
                    )
                ),
               "admin_installorder"
            )
        )
    );
    ForAll(
        myFlowstoTurnOn,
        If(
            LookUp(
                Processes,
               'Process Name' = ObjectName
            ).Status = 'Status (Processes)'.Draft,
            IfError(Patch(
                Processes,
                LookUp(
                    Processes,
                    'Process Name' = ObjectName
                ),
                {Status: 'Status (Processes)'.Activated}
            ), IfError(Patch(
                Processes,
                LookUp(
                    Processes,
                    'Process Name' = ObjectName
                ),
                {Status: 'Status (Processes)'.Activated}
            ), IfError(Patch(
                Processes,
                LookUp(
                    Processes,
                    'Process Name' = ObjectName
                ),
                {Status: 'Status (Processes)'.Activated}
            ), Blank())))
        ));
     /*   ForAll(
        myFlowstoTurnOn,
        If(
            LookUp(
                Processes,
                'Process Name' = ObjectName
            ).Status = 'Status (Processes)'.Draft,
            IfError(Patch(
                Processes,
                LookUp(
                    Processes,
                   'Process Name' = ObjectName
                ),
                {Status: 'Status (Processes)'.Activated}
            ), IfError(Patch(
                Processes,
                LookUp(
                    Processes,
                    'Process Name' = ObjectName
                ),
                {Status: 'Status (Processes)'.Activated}
            ), Patch(
                Processes,
                LookUp(
                    Processes,
                   'Process Name' = ObjectName
                ),
                {Status: 'Status (Processes)'.Activated}
            )))
        )
    )*/

/*
//'Admin|SyncTemplatev3(Connectors)'.Run();
//'Admin|SyncTemplatev3ConfigureEmails'.Run();
    IfError(
        Patch(
            Processes,
            LookUp(
                Processes,
                "CanvasAppOperations" in 'Process Name'
            ),
            {Status: 'Status (Processes)'.Activated}
        ),
        Patch(
            Processes,
            LookUp(
                Processes,
                "CanvasAppOperations" in 'Process Name'
            ),
            {Status: 'Status (Processes)'.Activated}
        )
    );
    IfError(
        Patch(
            Processes,
            LookUp(
                Processes,
                "CloudFlowOperations" in 'Process Name'
            ),
            {Status: 'Status (Processes)'.Activated}
        ),
        Patch(
            Processes,
            LookUp(
                Processes,
                "CloudFlowOperations" in 'Process Name'
            ),
            {Status: 'Status (Processes)'.Activated}
        )
    );
    ClearCollect(
        colHelperFlowsToTurnOn,
        Filter(
            Processes,
            And(
                solutionid = coeSolution,
                Or(
                    "Command Center" in 'Process Name',
                    "DLP Editor" in 'Process Name',
                    "Admin | Add Maker" in 'Process Name',
                    "Admin | Excuse" in 'Process Name',
                    "HELPER" in 'Process Name'
                ),
                Status = 'Status (Processes)'.Draft
            )
        )
    );
    UpdateIf(
        colHelperFlowsToTurnOn,
        Status = 'Status (Processes)'.Draft,
        {Status: 'Status (Processes)'.Activated}
    );
    Patch(
        Processes,
        colHelperFlowsToTurnOn
    );
    Patch(
        Processes,
        LookUp(
            Processes,
            "ObjectOperations" in 'Process Name'
        ),
        {Status: 'Status (Processes)'.Activated}
    );
    comment in here 
ForAll(colHelperFlowsToTurnOn As cPatch,
Patch(
    Processes,
    LookUp(
            Processes,
           WorkflowIdUnique = cPatch.WorkflowIdUnique
    ),
    {Status: 'Status (Processes)'.Activated}
));
Patch(
    Processes,
    First(
        Filter(
            Processes,
            "ObjectOperations" in 'Process Name'
        )
    ),
    {Status: 'Status (Processes)'.Activated}
); comment out here
Patch(
        Processes,
        LookUp(
            Processes,
            "ShareApps" in 'Process Name'
        ),
        {Status: 'Status (Processes)'.Activated}
    );
    
//now that environment variables are set, turn on sync flows
ClearCollect(
        colSyncFlowsToTurnOn,
        Filter(
            Processes,
            And(
                solutionid = coeSolution,
                "Admin | Sync Template v3 (" in 'Process Name',
                !("CLEANUP - " in 'Process Name'),
                Status = 'Status (Processes)'.Draft
            )
        )
    )
);
RemoveIf(
    colSyncFlowsToTurnOn,
    "Flow Action" in 'Process Name'
);
  If(
        myDataSource.isBYODL, 
        RemoveIf(
    colSyncFlowsToTurnOn,
    "Sync Template v3 (Apps)" in 'Process Name'
); RemoveIf(
    colSyncFlowsToTurnOn,
    "Sync Template v3 (Flows)" in 'Process Name'
); RemoveIf(
    colSyncFlowsToTurnOn,
    "Sync Template v3 (Model Driven Apps)" in 'Process Name'
));
UpdateIf(
    colSyncFlowsToTurnOn,
    Status = 'Status (Processes)'.Draft,
    {Status: 'Status (Processes)'.Activated}
);
IfError(
    Patch(
        Processes,
        colSyncFlowsToTurnOn
    ),
    Notify("Failed to turn on Admin | Sync Template flows. Please navigate to the solution and turn this flow on manually.")
);
/*ForAll(colSyncFlowsToTurnOn As cPatch,
Patch(
    Processes,
    LookUp(
            Processes,
           WorkflowIdUnique = cPatch.WorkflowIdUnique
    ),
    {Status: 'Status (Processes)'.Activated}
));*/
//'SetupWizard>UpdateInventoryTypeAppSetting'.Run();
Refresh('Setup Wizard State metadata');
Select(btnCollectFlowsWithMetadata);
Set(
    loadSyncFlowWait,
    false
);
`

Here is the refresh button code:

`Refresh('CoE Solution Metadata');
Refresh('Setup Wizard State metadata');

/*If(
    CountRows('CoE Solution Metadata') = 0,
    Patch(
        Processes,
        LookUp(
            Processes,
            "RunInitialFlows" in 'Process Name'
        ),
        {Status: 'Status (Processes)'.Activated}
    );
    Patch(
        'Setup Wizard State metadata',
        Defaults('Setup Wizard State metadata'),
        {
            Name: "Initial Setup",
            'Last Completed Step': 4,
            'Solution Name': "CenterofExcellenceCoreComponents",
            'Solution Version': coESolutionVersion
        }
    );
    Set(timerGo, true)
)*/
`

And the refresh function appears to just be refreshing the dataverse tables which are displayed in a component below. the button and hidden/white out with no data.

That's where I am at in digging, I am going to explore these tables, their dependencies in the core solution, and flows that interact with them soon. I'll send an update later as I find things.

Here is a view of the designer with the wizard open explaining how to figure out what is possibly happening:
![image](https://github.com/microsoft/coe-starter-kit/assets/1319169/212c0c12-9504-44d0-b39a-364e3d9e3ee6)

**Comment by junterpfe** [comment] 2023-07-19 21:09
Getting the same issue in my GCC tenant however what it looks like is all the flows listed in the CoE Solution Metadata table that are "Inventory" all are set to No on rerun on import so the button fails to show next so you can click through. 

![image](https://github.com/microsoft/coe-starter-kit/assets/47872678/d183a1e5-4144-4a8f-b103-b74d2551dc8f)

Happy to walk through this with someone internally if they want to see it in action.

**Comment by junterpfe** [comment] 2023-07-19 21:18
Finding 1 inventory flow in the CoE Solution Metadata table and toggling it to yes for RerunOnUpgrade let me move past the screen, however it seems like that should not be that way, I think something isn't updating that table properly.

**Comment by bwieland86** [comment] 2023-07-20 14:41
> Getting the same issue in my GCC tenant however what it looks like is all the flows listed in the CoE Solution Metadata table that are "Inventory" all are set to No on rerun on import so the button fails to show next so you can click through.
> 
> ![image](https://user-images.githubusercontent.com/47872678/254711434-d183a1e5-4144-4a8f-b103-b74d2551dc8f.png)
> 
> Happy to walk through this with someone internally if they want to see it in action.

This is what we observed as well during further troubleshooting. Looking at the underlying 'CoE Solution Metadata' table showed none of the 'RerunOnUpgrade' fields were set to "Yes", thus the DisplayMode of the "Next" button is Disabled.

We also took a look at the Gallery items itself and found that the filter conditions prevents any items from being displayed in the Gallery at that step, hence why hitting the "Refresh" button on the custom page would not display the status of any of the workflows that were meant to run during that stage, even though the workflows appeared to have run in the background.

**Comment by pnoot7** [comment] 2023-07-21 14:25
Also available for troubleshooting call/investigation if needed. I do have a test environment with 4.11 installed, so low steaks on testing in it.

**Comment by Jenefer-Monroe** [comment] 2023-07-21 15:27
Root cause ended up being an issue with the new **_List Flows as Admin (V2)_** action in GCC not returning all flows.
Pressing with dev to fix.

**Comment by craig-lund-planet** [comment] 2023-07-26 17:51
Any update on this issue? 

> Root cause ended up being an issue with the new **_List Flows as Admin (V2)_** action in GCC not returning all flows. Pressing with dev to fix.

**Comment by craig-lund-planet** [comment] 2023-07-26 20:20
Am I correct in understanding that this is an issue with the 'Power Automate Management" Connector and not with the CoE?

**Comment by Jenefer-Monroe** [comment] 2023-07-26 20:32
Thats correct, the new List flows as Admin (v2) action is not pulling back all the needed fields in non-commercial tenants.
Product team is following up.

**Comment by Yocomd** [comment] 2023-08-01 22:06
Adding myself to this thread.  I'm also in GCC and stuck at the same place, though perhaps it's slightly different?  I saw a "Network error. Patch failed" error pop up when I was moving into that step.  I can see that some of the flows that are supposed to run (e.g. Admin | Sync Template v3 Configure Emails, Admin | Sync Template v3 CoE Solution Metadata) actually do run successfully, but they fail on the step where they're supposed to update the metadata record to say "Passed" because that metadata record doesn't actually exist.

I'm guessing that the patch that is failing was supposed to put a bunch of records into the COE Solution Metadata table for all of the flows that are supposed to run and so the non-existent records cannot be updated which means I can't move on?

**Comment by Jenefer-Monroe** [comment] 2023-08-02 00:28
Unfortunately the issue is not just with the setup wizard but with the ability to gather inventory about cloud flows. 
You can move on with a manual upgrade [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) but the cloud flow inventory will not work as expected until this issue is resolved. We are pressing for a fix.

**Comment by pnoot7** [comment] 2023-08-02 14:22
What is the ETA on this? The August release just came out, and I am just assuming it will have the same issues. This will push GCC users even further behind. I understand you are pressing for a fix, but are there any details on that? Are we GCC customers able to provide any assistance? Should we have our CSAM's reach out?

**Comment by Jenefer-Monroe** [comment] 2023-08-02 14:25
If you can have your account folks post internal tickets (ICMs) that would be helpful. Have them reference the connector directly, something like this:

The new List flows as Admin (v2) action is not returning all fields for non-commerical tenants.
Then in impact you can mention that this blocks usaeg of the CoE Starter Kit and hence (describe your impact / tenant size / etc)

**Comment by craig-lund-planet** [comment] 2023-08-02 14:38
There are already ICM tickets and One It VSO work item. There has been no priority set. The more we can get folks to have ICMs created the more visibility we can get. For us we have 1 current and 3+ future projects this will affect. We are working all angles we have. Here is one of the latest comments. 

![image](https://github.com/microsoft/coe-starter-kit/assets/132308542/8d838156-b59b-4d22-9dac-ae45b309de34)

Squeaky wheels with get greased first!  Be sure to include the financial impact on you and for Microsoft.

**Comment by ChrisGarty** [comment] 2023-08-04 07:10
@Jenefer-Monroe, @manuelap-msft, @craig-lund-planet, @pnoot7, @Yocomd, @bwieland86, @junterpfe, @TigerJ, and other CoE Starter Kit fans, 
This is caused by an issue in the Azure infrastructure we use to return flow details. That Azure infrastructure has some differences in GCC and is currently being fixed/updated to match the other regions. We don't have a firm timeline yet. We are working with the Azure infrastructure team to determine the expected timeline. Thanks for your patience on this!
- Chris Garty
Product Manager, Power Automate Cloud Flows

**Comment by pnoot7** [comment] 2023-08-04 11:44
> @Jenefer-Monroe, @manuelap-msft, @craig-lund-planet, @pnoot7, @Yocomd, @bwieland86, @junterpfe, @TigerJ, and other CoE Starter Kit fans, This is caused by an issue in the Azure infrastructure we use to return flow details. That Azure infrastructure has some differences in GCC and is currently being fixed/updated to match the other regions. We don't have a firm timeline yet. We are working with the Azure infrastructure team to determine the expected timeline. Thanks for your patience on this!
> 
> * Chris Garty
>   Product Manager, Power Automate Cloud Flows

Thank you for the follow up. As this appears to be a large outage for GCC, can we please get a service advisory posted? I will follow up with my CSAM too, but I do think there is value in getting this posted for awareness.

**Comment by SOM-Scott** [comment] 2023-08-09 20:58
A service advisory for this would be great. It is a major holdup for our users.

**Comment by pnoot7** [comment] 2023-08-10 11:57
I encourage everyone to bring this up with their account manager. Our CSAM had me use the report issue to try to get an advisory posted, but it was closed almost immediately as "no issue found". Microsoft seems to be against posting advisories when things are broken, even if they admit it is broken for a large number of users. I also have a ticket open, and have not been able to get any information from them as well. I don't understand what is going on with them when they have a large scale issue, but refuse to acknowledge it. I don't think it's an unreasonable ask to get an advisory posted.

@ChrisGarty - Any update or response to getting a service advisory?

**Comment by LJVan** [comment] 2023-08-15 22:19
Is there any ETA yet for a fix from the team that owns this issue? Or any update about getting a service advisory?

**Comment by craig-lund-planet** [comment] 2023-08-16 17:12
@manuelap-msft, @Jenefer-Monroe 

Ok, after some back and forth, research, and trial and error I believe I found a fix / workaround that would be sustainable after a fix. 

Issue, as I have come to understand it, is data returned in GCC+ is different or missing. See below: top portion is "List Flows and Admin V2" bottom potion is "Get Flow as Admin", Commercial on left, GCC on the right. 

Can the CoE flow(s) (I think there was 3-4 that used the connector action) be modified to perform a null check on 'properties.creator' If null Skip adding a creator otherwise add creator. Then get the flow using "Get Flow as Admin" get the Display Name from there. 

This should allow the CoE to work, just without a creator in GCC+. When the Infrastructure fix comes through it would not affect the flow, just add the creator. 

I do not recall if any CoE Flows use the "workflowEntityId" but, as that is missing it may need a null check as well. 

Thoughts? 

![image](https://github.com/microsoft/coe-starter-kit/assets/132308542/9888f609-c995-4e96-8db4-5b4794cc72cd)

**Comment by Jenefer-Monroe** [comment] 2023-08-16 18:31
While we may be able to work around this limitation for the purposes of the setup wizard, we would not be able to get what we need for the flow inventory. The whole kit was rewritten to use this new connector action, so we just need the product team to fix this issue so that we can correctly gather the inventory. 
@ChrisGarty can hopefully comment on status. I believe we are days away from it being resolved.

**Comment by pnoot7** [comment] 2023-08-16 18:53
> While we may be able to work around this limitation for the purposes of the setup wizard, we would not be able to get what we need for the flow inventory. The whole kit was rewritten to use this new connector action, so we just need the product team to fix this issue so that we can correctly gather the inventory. @ChrisGarty can hopefully comment on status. I believe we are days away from it being resolved.

I hope this to be the case, however, it is not lining up with my support ticket. I was told that _maybe_ this week we would get a service advisory posted, let alone have the issue fixed. Unless support means they are only going to post the advisory after the issue is fixed, but I suppose that's a different battle. It would be extremely helpful to get some details on what is going on.

**Comment by awinklerawinkler** [comment] 2023-08-17 18:46
Does anyone on this thread recommend how we get a "service advisory" on this issue or escalate? My team had to delay an important scheduled project while we wait for this to be fixed. This is NOT resolved. PLEASE up the priority of this issue.  -Alexandra Winkler, Chief Information Officer, City of Boise.

**Comment by pnoot7** [comment] 2023-08-17 18:51
@awinklerawinkler, I've been pushing it with my Microsoft Customer Success Account Manager (CSAM) and a ticket with MS support. However, have not been getting much progress. If you can press Microsoft, and include a financial cost, maybe you can get some attention on it.

**Comment by pnoot7** [comment] 2023-08-18 18:44
@Jenefer-Monroe, I finally got access to the audit logs for my service account. I can manually go and do a search. Yet nothing is pulled into the CoE. I ran through all the set up docs, and it is correct. Is this issue related to not be able to get audit logs in GCC, or should I open a new issue?

The flows all run correctly, and I get a 400 subscription already started. Azure App has correct API/permissions assigned. Yet nothing is pulled into the audit log table, even after 48 hours, and I have opened/edited several apps.

**Comment by pnoot7** [comment] 2023-08-21 14:20
@Jenefer-Monroe, @ChrisGarty , @manuelap-msft , Are any of you able to share any updates? We have not been able to get any information for some time now.

**Comment by pnoot7** [comment] 2023-08-21 16:54
I was able to get some information from MS support. He directed me to this post: https://powerusers.microsoft.com/t5/Using-Connectors/Transition-to-List-Flows-as-Admin-V2-from-deprecated-List-Flows/m-p/2307573/highlight/true#M19466

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/827d54d5-b6fb-4df4-bc11-af9aa921a22a)

I however, do not see a message center post with an ID of "MC624197", and have asked support about this. So we will see what comes of this.

**Comment by Jenefer-Monroe** [comment] 2023-08-23 12:46
Thank you community for keeping each other up to date with your news. I'll return when I hear something as well.

**Comment by pnoot7** [comment] 2023-08-25 12:30
Back again to see if anyone has any updates. Still no advisory posted. Still no message center message (that one mentioned above is not in my tenant and no one can tell me why). No ETA. This whole process has been unacceptable.

**Comment by awinklerawinkler** [comment] 2023-08-25 14:02
I'm with @pnoot7. Request update. This is seriously delaying an important discovery project and is pushing us into another fiscal year.

**Comment by Jenefer-Monroe** [comment] 2023-08-25 15:53
I do apologize for how this issue had been handled with regards to keeping you all in the know. I agree it’s been insufficient for keeping great customers like yourselves engaged in the product.

I have just been told that, assuming no issues with rollout, the fix should reach GCC, GCCH and DoD customers by Tuesday, Aug 29.

**Comment by craig-lund-planet** [comment] 2023-08-28 23:47
Fix looks to be implemented. Please validate and report back here if you can. Thanks!

**Comment by bwieland86** [comment] 2023-08-29 03:10
I am using the July 2023 version and was previously stuck at the initial setup flows. I had to manually start the Configure Emails and Connectors flow, but otherwise was able to proceed as normal and complete a fresh install into a DEV environment.

I will attempt to install the August 2023 version on top of it tomorrow, due to the other hardcoded values that prevent usage in GCC, particularly with the loss of the connector actions used in the Power BI dashboard.

Preference would be for the CoE Team to stop implementing new functionality for month or two and clean through the backlog of issues and bugs while working more closely with Microsoft to ensure that this issue does not happen again. Understand that the CoE is a "sample implementation," yet each time I talk with Microsoft Support they are the first recommending its utilization while simultaneously repeating that they can only perform "best effort" and do not support it. With monthly updates and new bugs introduced in each version, many end-users do not have the staff or resources to build on top of it while also having to replace and rebuild each month. This needs to gain more official support and resources from Microsoft if they are going to promote it, hold the documentation for it, and even have MS Learn modules about it. Otherwise, it is just a defective product showcase and not a tool for supporting and maintaining Power Platform tenants.

**Comment by Jenefer-Monroe** [comment] 2023-08-30 14:06
Sorry to hear you are frustrated with the kit, we do a large amount of effort to ensure high quality releases even though we are not a supported product. Some people do implement their own tooling to monitor and govern the kit instead, and just use us as an inspiration for ideas and potential solution paths. This may be a better fit for you.

**Comment by Jenefer-Monroe** [comment] 2023-08-30 14:09
Folks on this thread, please do let us know if you are now able to use the setup wizard. We are releasing the Sept release next month and so feel free to wait for that build. 

Do note that before upgrading to August or more current, that we have cut support for the custom connector methodology of gathering audit logs. So if you are using those, please clean that up before you proceed. 

Here are some links on how to [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by Yocomd** [comment] 2023-08-30 16:53
@Jenefer-Monroe, if we completed the installation manually, is there another way that we can confirm that everything is working?

**Comment by Jenefer-Monroe** [comment] 2023-08-30 18:07
Go to a run of this flow from today: **_Admin | Sync Template v4 (Flows)_**

Look at the output of this action
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ce69e0fe-c4b7-4d09-9404-fc16126a9e40)

Does the output have all these fields? 
In particular I believe it was displayName, createdTime, lastModifiedTime which were missing. But please let me know generally if you now have all of these please.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/40a4ed3d-52f7-4cc6-92a6-8e539f992987)

**Comment by Yocomd** [comment] 2023-08-30 18:16
Thank you for those instructions!  It looks to be working for us here!  Do you think it would be a good idea to turn on a full inventory for the next sync to get everything that might have been missed over the last month?

**Comment by Jenefer-Monroe** [comment] 2023-08-30 18:32
What version of Core are you on? And how many flows do you have in your tenant? It may not be needed / worthwhile if you are current enough and your flow count is high.

**Comment by Yocomd** [comment] 2023-08-30 18:35
Core 4.13.  I don't know exactly how many flows we have in the tenant, since we rely on the CoE and I know it was previously missing some, but we currently have 4,800 flows listed.  Is there some other way I can determine the actual number of flows?

**Comment by Jenefer-Monroe** [comment] 2023-08-30 18:39
You should be ok without a full inventory. We redid the way we look for new flows in ~June so you shouldnt miss anything.

**Comment by Yocomd** [comment] 2023-08-30 18:42
Thanks!

Diane Yocom
(she/her)
Technical Lead | Applications - Digital Workflows
O: 206.684.0612 | ***@***.***
SEATTLE INFORMATION TECHNOLOGY

**Comment by pnoot7** [comment] 2023-08-31 14:19
My Test CoE environment is a sandbox, so I reset. Enabled component framework, imported Creator kit. Imported core 4.13, and created the connections, using https://graph.microsoft.com for GCC per documentation. Used that same URL for Graph URL Environment Variable during import. Launched the Setup wizard, and still get this error:
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/80ebe5d1-ed8c-49ff-a000-1a4f9db295b9)


Error Details: Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bkind%2C%20severity%2C%20errorHttpResponse%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at pb (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:213:454)
    at n (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:214:221)
    at Ac (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:271:369)
    at https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:281:190
    at N (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:291:3)
    at hi (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:307:194)
    at Qg (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:345:293)
    at Rg (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:346:168)
    at Sc (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:359:109)
    at Z (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:357:492)

Activity Id: 2a97af54-e8b7-4d83-9b4c-4c6d089e535d

Any suggestions?

**Comment by pnoot7** [comment] 2023-08-31 14:23
Tried to continue, still get:
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/79f22879-e5d7-4917-8427-c8385eff3ba0)

Do I need to completely delete this environment and start fresh?

**Comment by Jenefer-Monroe** [comment] 2023-08-31 14:25
Please do the below quickly if you have runs, to make sure you're tenant is fixed up. 
Then if it is, yes I suggest starting from scratch. Resetting envts does not actually reset it all the way and sometimes leaves flows in a strange state.

> Go to a run of this flow from today: **_Admin | Sync Template v4 (Flows)_**
> 
> Look at the output of this action ![image](https://user-images.githubusercontent.com/89584709/264432117-ce69e0fe-c4b7-4d09-9404-fc16126a9e40.png)
> 
> Does the output have all these fields? In particular I believe it was displayName, createdTime, lastModifiedTime which were missing. But please let me know generally if you now have all of these please.
> 
> ![image](https://user-images.githubusercontent.com/89584709/264433651-40a4ed3d-52f7-4cc6-92a6-8e539f992987.png)

**Comment by Jenefer-Monroe** [comment] 2023-08-31 14:42
No it sounds like you're tenant might still be broken so lets check that before we do anything else. 

Please create a new blank flow and just add two calls to this action
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a0aff3cc-be07-46c2-9e43-a29f02ecc6b1)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/52955499-2df0-431a-a096-5b86b01fca74)

For one of the calls select your default envt and for the other your CoE
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c34aaf5-7dd9-4c14-b606-6df12ebfe601)

Run it and look at the output of each

1. Do they both return flows?
2. Do the results contain information like this?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/40a4ed3d-52f7-4cc6-92a6-8e539f992987)

**Comment by pnoot7** [comment] 2023-08-31 14:47
Both are returning a long list with sections like the one you posted.

**Comment by Jenefer-Monroe** [comment] 2023-08-31 14:53
Wonderful. Then the issue this bug was tracking, the product bug, is resolved for you. 
Yes I woudl suggest you start with a new envt then.

**Comment by bwieland86** [comment] 2023-09-01 17:51
> No it sounds like you're tenant might still be broken so lets check that before we do anything else.
> 
> Please create a new blank flow and just add two calls to this action ![image](https://user-images.githubusercontent.com/89584709/264681182-a0aff3cc-be07-46c2-9e43-a29f02ecc6b1.png) ![image](https://user-images.githubusercontent.com/89584709/264681397-52955499-2df0-431a-a096-5b86b01fca74.png)
> 
> For one of the calls select your default envt and for the other your CoE ![image](https://user-images.githubusercontent.com/89584709/264681672-0c34aaf5-7dd9-4c14-b606-6df12ebfe601.png)
> 
> Run it and look at the output of each
> 
> 1. Do they both return flows?
> 2. Do the results contain information like this?
>    ![image](https://user-images.githubusercontent.com/89584709/264433651-40a4ed3d-52f7-4cc6-92a6-8e539f992987.png)

Thank you so much for including these steps. I was able to follow them and get the correct properties from the new List Flows as Admin V2 action, and then was able to install the August update on top of the July update into our DEV environment.

**Comment by Jenefer-Monroe** [comment] 2023-09-06 11:32
closing out now as resolved.

**Closed by Jenefer-Monroe** 2023-09-06 11:32 UTC
Labels: question, coe-starter-kit, product-gap
