### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by ArunimaTalukdar** [microsoft/coe-starter-kit#797] opened 2021-07-08 17:55 UTC
### Describe the issue

Not able to see owner names in "Apps" page in Power BI report, we only see owners represented as for the Default environment "SYSTEM".

### Expected Behavior

"Owners" field should show usernames instead of "SYSTEM"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

None

**Comment by JeneferM-MSFT** [comment] 2021-07-08 17:57
looks to be the same issue as #784 
Can you confirm?

**Comment by JeneferM-MSFT** [comment] 2021-07-08 22:36
#
Duplicate of #784

**Closed by JeneferM-MSFT** 2021-07-08 22:36 UTC
Labels: coe-starter-kit
