### ISSUE TITLE
[CoE Starter Kit - BUG] The number of flows returned for System Account in Default tenant is not way off

### ISSUE THREAD

**Issue by umananan** [microsoft/coe-starter-kit#2033] opened 2022-02-11 06:37 UTC
### Describe the issue

Wanted to know if there is any limitation on the "**Admin | Sync Template v3 (Flows)**" which uses the "List Flows as Admin".
The reason being, the flows captured by the run in the Dataverse in thus in the Power BI and and the Power Platform Admin View App is way off for the Default Environment.

The total flows in the Environments (most of it are created using Standard templates)  is shown as 18 but in actual it has 380+ flows. 
The PowerShell "Get-AdminFlow" gives the correct information. Do I need to change any parameter of setting to have all the information being captured by the Sync flows or it is a bug ?

Please let me know if any more details is needed.  

Packaged used : CenterofExcellenceCoreComponents_3_20_6_managed.zip

### Expected Behavior

The count should of flows and list of flows should match , to what is actually there and what is being reported by the report (Sync flow)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment] 2022-02-11 12:42
Hello, you need to do a full inventory run. We had a bug which made first inventories not find all apps/flows. 
Please see https://github.com/microsoft/coe-starter-kit/issues/1810

Please see [running a full inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)

**Comment by Jenefer-Monroe** [comment] 2022-02-11 12:42
Duplicate of #1810

**Comment by umananan** [comment] 2022-02-11 23:17
Thanks for the quick response. That did solve it. 
Another query wanted to know was regarding the Filter condition applied - 
@or(greater(item()?['properties/createdTime'], body('Get_past_time')), greater(item()?['properties/lastModifiedTime'], body('Get_past_time')), equals(item()?['properties/lastModifiedTime'], null))
What does this filter do.

**Comment by Jenefer-Monroe** [comment] 2022-02-14 14:52
The sync flows have been optimized to only run for new or recently updated objects. This filter is a big part of that. 
Past time is configured to be either years ago (if full inventory) or one week ago.
It then filters to flows (or apps for example) that have been modified since that past time. 

This is to avoid the sync flow having to touch all the objects in the tenant each time. Instead it does this filter to only touch those flows that qualify. 

Hope that helps.

**Comment by Jenefer-Monroe** [comment] 2022-02-17 14:09
closing out as no further work for starter kit team. 
Thanks for using CoE

**Closed by Jenefer-Monroe** 2022-02-17 14:09 UTC
Labels: coe-starter-kit
