### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connection Identities) failing on some flow runs

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#3353] opened 2022-08-03 16:31 UTC
Hi, I have a flow in the starter kit that is failing on some flow runs...I am getting the following error. Is there a way around this? I have another flow that is failing, but wanted to make sure this one isn't causing that one to fail.  

![image](https://user-images.githubusercontent.com/95765970/182660955-15a787fb-b0ff-43fd-9f86-c3027d2abf84.png)

**Comment by Jenefer-Monroe** [comment] 2022-08-03 19:39
Hello, this is a product limitation tracked by https://github.com/microsoft/coe-starter-kit/issues/3293
Please create a support ticket for this so that the product team can take a look, and you can also try this workaround if you'd like which is a PowerShell command to delete the broken connections in your default environment. Hopefully that reduces the count enough to work in flow.

(Get-AdminPowerAppConnection -EnvironmentName "Default-**_yourguidhere_**") | Where { $_.statuses -like "Error"} | Remove-AdminPowerAppConnection

Closing out as a dupe of #3293 , please correspond in that bug with your findings.

**Closed by Jenefer-Monroe** 2022-08-03 19:39 UTC
