### ISSUE TITLE
[ALM Accelerator - BUG]: "Projects" tab not showing in the ALM Accelerator Administration App

### ISSUE THREAD

**Issue by billigproton** [microsoft/coe-starter-kit#5691] opened 2023-05-31 13:29 UTC
### Describe the issue

Hello,

We've been trying to deploy ALM Accelerator to a test environment, but it doesn't seem to be successful... First, we tried to set it up using the Admin App following the instructions at Microsoft Docs. After carefully checking that we have all the prerequisites and following all the instructions, we can't get through the "Set up your first Azure DevOps project for use with ALM Accelerator for Power Platform", because there simply is no "Projects" tab showing. Do you know what might be the solution to this?

Also, does this approach really do the same thing as the manual approach? In the manual approach, there seem to be a lot more steps.

Thanks in advance!

Daniel

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

### Anything else?

<img width="1051" alt="alm" src="https://github.com/microsoft/coe-starter-kit/assets/85786747/6bb8f666-2810-4682-8762-d01be1b410d1">

**Comment by mikefactorial** [comment] 2023-05-31 18:34
@billigproton looks like you have a very old version of the ALM Accelerator 1.0.20220114.1 (this is from January of 2022). We ship monthly updates the latest release is here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2023. Follow the instructions in https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks using this version. 

Was this recently installed? If so, wonder if we have a stale link somewhere that needs updated if you can provide how you came across the old version that would help.

**Comment by billigproton** [comment] 2023-05-31 19:56
Hi @mikefactorial , yes, after installing the latest version I can finally see the Projects tab. It seems like I downloaded the old version from github by accident... :) 

Also, the issue I'm experiencing now is within the Project wizard. When I click "Yes" on the popup to download the release history, nothing happens... When i want to access the Project wizard again, the popup shows up again...

Thanks!

**Comment by mikefactorial** [comment] 2023-06-01 14:12
@billigproton can you make sure that all of the Flows in the solution are activated? Particularly, the *ReleaseHistory* flows.

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/f222ae7f-8fb4-4453-a652-477833ecc7fd)

**Comment by billigproton** [comment] 2023-06-04 17:48
@mikefactorial Thanks for your continuous help! The flows were indeed off. I was able to then finish the tutorial to set up ALM accelerator. Can I then use the the canvas app? Because after defining a deployment profile, service connections to my desired environments, I wasn't able to deploy the test solution to a test prod environment. This is the error I got.

![image](https://github.com/microsoft/coe-starter-kit/assets/85786747/0a6fb5bf-1d6b-4535-8ab1-af2d449aff9d)

**Comment by billigproton** [comment] 2023-06-09 10:50
hi @mikefactorial, just making sure my issue is not forgotten about.

Thanks in advance!

Daniel

**Comment by billigproton** [comment] 2023-06-09 15:38
@mikefactorial oh, I'm sorry... here you go.

<img width="1280" alt="2023-06-09" src="https://github.com/microsoft/coe-starter-kit/assets/85786747/0a77153a-0d6d-4238-822a-70a8ed057d22">

**Comment by mikefactorial** [comment] 2023-06-09 15:47
@billigproton looks like Power Apps is truncating the error but it looks like this error (https://stackoverflow.com/questions/69097402/tf401398-the-pull-request-cannot-be-activated-because-the-source-and-or-the-tar)

This would imply that when you are deploying the source and target branches aren't being set correctly. Would need to know more about the steps you took to reproduce this issue e.g. did you export to a new branch and then deploy with the new branch as the source and the solution branch as the target? 
You might want to refer to this video to make sure you're following the correct steps for deployment. https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceALMAccelerator/WALKTHROUGHS.md#advanced-maker-experience-in-the-alm-accelerator-for-power-platform

**Comment by mikefactorial** [comment] 2023-07-05 16:55
Closing this out as there hasn't been any response in a while. Feel free to reopen with the additional information requested or if the problem was solved let us know as it may help others find an answer.

**Closed by mikefactorial** 2023-07-05 16:55 UTC
Labels: bug, alm-accelerator
