### ISSUE TITLE
 Admin | Sync Template v3 - Action 'Get_Maker' failed #1139 

### ISSUE THREAD

**Issue by maron1209** [microsoft/coe-starter-kit#2062] opened 2022-02-16 14:34 UTC
### Describe the issue

 Hi. My Admin | Sync Template v3 fails when running. Setting up the CoE, it initially ran, however, on the second run the flow failed along with the other sync templates.

### Expected Behavior

 Excepted the flow to find the maker of the app/flow and continue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Latest version. Februrary 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 and related sync flows (model-driven, canvas ...)

### Steps To Reproduce

1.     Go to core
2.     Click on Admin | Sync Template v3
3.     Scroll down to Store environments in the CDS entity > Check if legacy environment > Get maker
4.     See error below

    {
    "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585567290480689261520781454CU117'."
    }
    }

![image](https://user-images.githubusercontent.com/57493048/154286215-59c16d39-a5a6-4254-89e8-a93d5aa1c720.png)

**Comment by Jenefer-Monroe** [comment] 2022-02-16 14:50
Hello, my guess is that you have not enabled the child flows. Please note that every time you upgrade you need to go and make sure that you have all the flows turned on. 

For inventory, you can look through the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) for this. Note there are 3 spots in the instructions where you see flows listed. Ensure you turn them all on in the order shown.

**Comment by maron1209** [comment] 2022-02-16 14:57
I looked through the core components, and don't see the following flows listed:

HELPER – Send Email
HELPER – Maker Check
HELPER – CloudFlowOperations
HELPER – CanvasAppOperations
HELPER – ObjectOperations

**Comment by maron1209** [comment] 2022-02-16 15:02
Just doubled checked and all of the child flows are turned on. Would it help to turn all of the flows off and then back on in the same order?

**Comment by Jenefer-Monroe** [comment] 2022-02-16 15:18
No, I dont think that it would. 
Go to the Maker Check flow and let me know what you see there for failures.

**Comment by JasonMorrisMJMC** [comment] 2022-02-16 19:14
In case Maron1209 doesn't come back, I have the same error. Installed the COE kit on 2/3/2022 and it worked until 2/6, now I'm getting this error within the Helper - Maker Check.

I have deleted some orphaned and no longer used flows which I feel is the only activity I did.
I've tried to find any reference to country in the Environment variables but no luck.
I just disabled all flows, then turned them back on in order prescribed just in case that works and am waiting for the sync to finish.

Suggestions?

> Unable to process template language expressions in action 'Set_variable_existing_value_-_Country' inputs at line '0' and column '0': 'The template language expression 'first(outputs('See_if_maker_exists_and_updated_already_today')?['body/value'])['admin_country']' cannot be evaluated because property 'admin_country' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_makerisorphaned@OData.Community.Display.V1.FormattedValue, admin_makerisorphaned, admin_userisserviceprinciple@OData.Community.Display.V1.FormattedValue, admin_userisserviceprinciple, admin_company, admin_department, admin_displayname, admin_city, admin_makerid@odata.type, admin_makerid, admin_userprincipalname, admin_managerid'. Please see https://aka.ms/logicexpressions for usage details.'.

**Comment by Jenefer-Monroe** [comment] 2022-02-16 19:23
That is an error we expect sometimes and so should be caught, here shows a similar case where the user didnt have company (yours is country but same situation) but the flow continues. Can you share a picture of what you see? Does it not continue after the failure? 

![image](https://user-images.githubusercontent.com/89584709/154340066-e851d18a-09f0-4dba-930e-91a795577324.png)

**Comment by Jenefer-Monroe** [comment] 2022-02-16 19:26
And please also check to see if the maker has any unmanaged layers.

**Comment by JasonMorrisMJMC** [comment] 2022-02-16 22:29
Correct, the flow appears to stop after the failure. Screenshot of the Helper - Maker Check directly below.
![image](https://user-images.githubusercontent.com/99033414/154366563-893ba2ea-5390-470a-b78c-fc5f4580e65b.png)

Ultimately the Admin | Sync Template v3 fails...
![image](https://user-images.githubusercontent.com/99033414/154366700-0a26b922-e026-4b2e-a690-f479402f2545.png)
![image](https://user-images.githubusercontent.com/99033414/154367987-772bc774-a8a6-490d-b1aa-f0f941aae2d9.png)
![image](https://user-images.githubusercontent.com/99033414/154368146-13615e5b-7e47-45ed-8ccf-6c1de69674bc.png)
![image](https://user-images.githubusercontent.com/99033414/154368165-7aa86293-9888-40f8-ba3f-1d387c35477b.png)

**Comment by maron1209** [comment] 2022-02-17 07:24
Hi, just checked the maker flow and I get the same errors as @JasonMorrisMJMC. My flow however continues after first error. 

> Error details:
> Unable to process template language expressions in action 'Set_variable_existing_value_-_Company' inputs at line '0' and column '0': 'The template language expression 'first(outputs('See_if_maker_exists_and_updated_already_today')?['body/value'])['admin_company']' cannot be evaluated because property 'admin_company' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_makerisorphaned@OData.Community.Display.V1.FormattedValue, admin_makerisorphaned, admin_userisserviceprinciple@OData.Community.Display.V1.FormattedValue, admin_userisserviceprinciple, admin_department, admin_displayname, admin_country, admin_preferredlanguage, admin_makerid@odata.type, admin_makerid, admin_userprincipalname, admin_managerid'. Please see https://aka.ms/logicexpressions for usage details.'.


![image](https://user-images.githubusercontent.com/57493048/154425825-ea58a621-a4d5-4759-b4f5-1826fb20f998.png)

**Comment by Jenefer-Monroe** [comment] 2022-02-17 11:09
In @JasonMorrisMJMC's case, I dont know that it didnt continue, I didnt see a picture like the one you show here.
Thanks for posting this picture, it shows what I expected for the initial failure. It is expected and caught, so that is not what is causing the flow to fail. Please scroll down further in the run and find an uncaught failure to share with me here.

**Comment by maron1209** [comment] 2022-02-17 12:20
Is this an uncaught failure? Not quite sure what you mean.

![image](https://user-images.githubusercontent.com/57493048/154480622-995277b9-0f4c-4c23-8e78-b33f0fd365f1.png)

**Comment by Jenefer-Monroe** [comment] 2022-02-17 12:24
Yep! Thats the spot! Thanks for finding. This is a known bug fixed for March. Duplicate of #2051 
I'll close this one out, please monitor that bug to see when the fix is available.

**Closed** 2022-02-17 12:24 UTC
Labels: question, coe-starter-kit
