### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permission throws "change owner failed" issue when adding new viewer

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3174] opened 2022-07-13 06:39 UTC
### Describe the issue

Set Flow Permission App Issue

I just tried to "Add new Users" to a flow. The permisison drop down available was Viewer and Editor.
I selected Viewer and then this message throws up.

Although, i just added a user to viewr, it throws error as if i was changing the owner (which is incorrect from assignment perspective)

![image](https://user-images.githubusercontent.com/17232756/178666777-d0127335-63cf-4144-87a8-e643b7f24700.png)

### Expected Behavior

Must allow - Adding a user as a viewer to Flow

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

Open the App
Select any flow
Search for a user
Select 'Viewer' from drop down and set the assignment.

Error pops out

![image](https://user-images.githubusercontent.com/17232756/178667450-9e622103-852a-4455-a190-d6329779336e.png)

**Comment by Jenefer-Monroe** [comment] 2022-07-13 23:39
Hello, we had a regression in the helper flow for this but that is adressed in the July release via https://github.com/microsoft/coe-starter-kit/issues/3116
Please upgrade to see the fix
Thanks for using CoE
Duplicate of #3116

**Closed by Jenefer-Monroe** 2022-07-13 23:39 UTC
Labels: bug, coe-starter-kit

**Comment by girishuppal** [comment] 2022-07-14 01:58
Same Error Post upgrading to Core Components 3.4 version
![image](https://user-images.githubusercontent.com/17232756/178879910-b6e53e49-0fb0-44c2-8f11-c2adad4fe94a.png)
![image](https://user-images.githubusercontent.com/17232756/178880044-94d5ad88-4b09-49ff-a59a-e52d05cade4e.png)

**Comment by Jenefer-Monroe** [comment] 2022-07-14 02:10
Did you remove the unmanaged layers from the helper flows on upgrade? 
See our [upgrade documentation](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)

**Comment by girishuppal** [comment] 2022-07-14 04:57
Yes

**Comment by Jenefer-Monroe** [comment] 2022-07-14 13:37
I dont repro so I do believe this has been fixed and you just arent seeing it. 

Please go to the HELPER - CloudFlowOperations flow, click on the time stamp for your failure, and see what failure you find there.
![image](https://user-images.githubusercontent.com/89584709/178994986-6ce16bfe-6f51-4399-ab74-18827d8375c3.png)

Please also share a screenshot showing there being no unmanaged layers on the helper
![image](https://user-images.githubusercontent.com/89584709/178995413-10943a9f-6c89-4d5f-9a13-3a04761eccf5.png)
![image](https://user-images.githubusercontent.com/89584709/178995467-18adc0b8-9ae5-44fb-9d4d-9c75371b8e27.png)

**Comment by girishuppal** [comment] 2022-07-15 00:19
Layer All good
![image](https://user-images.githubusercontent.com/17232756/179121918-5b661c25-a854-4077-8abd-2c67178f0bad.png)

Flow Failed
![image](https://user-images.githubusercontent.com/17232756/179122039-2f975ec2-87b3-4402-8b2f-770acb05ab8e.png)

Request to Azure Resource Manager failed with error: '{"Code":"NotFound","Message":"Cannot find connection acl with name ee3d5e22-4f42-4ae1-b645-9883abe2fa66.","Target":null,"Details":[{"Message":"Cannot find connection acl with name ee3d5e22-4f42-4ae1-b645-9883abe2fa66."},{"Code":"NotFound"},{"ErrorEntity":{"ExtendedCode":"14010","MessageTemplate":"Cannot find connection acl with name {0}.","Parameters":["ee3d5e22-4f42-4ae1-b645-9883abe2fa66"],"Code":"NotFound","Message":"Cannot find connection acl with name ee3d5e22-4f42-4ae1-b645-9883abe2fa66."}}],"Innererror":null}'.

**Comment by girishuppal** [comment] 2022-07-15 00:20
![image](https://user-images.githubusercontent.com/17232756/179122215-506fa146-1965-4589-b7c6-721e93b9b29d.png)

**Comment by girishuppal** [comment] 2022-07-15 05:57
![image](https://user-images.githubusercontent.com/17232756/179160242-243e8331-b705-49c1-888c-a8439c44da31.png)
Finally suceeded. Dont know how, but it worked. Thanks team.

**Comment by Jenefer-Monroe** [comment] 2022-07-15 13:52
our fix was to add a catch as part of that second call. 
![image](https://user-images.githubusercontent.com/89584709/179236532-9b5f742f-9f35-4621-afcf-5cc66b70b488.png)


So this call should have caught. And you arent seeing the change for some reason. 
![image](https://user-images.githubusercontent.com/89584709/179236644-62845274-7b7a-4582-bae7-fe3f7085a5cf.png)

**Comment by Jenefer-Monroe** [comment] 2022-07-15 13:52
My guess is somethign went wrong with your upgrade, please look at your solution history

**Comment by girishuppal** [comment] 2022-07-19 04:38
Sure. Thanks
