### ISSUE TITLE
[CoE Starter Kit - BUG] GCC Audit log is not showing any data. The flow runs successfully everyday and JSON response is 200

### ISSUE THREAD

**Issue by yeiner899** [microsoft/coe-starter-kit#858] opened 2021-07-15 16:21 UTC
### Describe the issue

Audit logt is not showing any data. The flow runs successfully everyday and JSON response is 200.

### Expected Behavior

Be able to see the Audit logs in GCC

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.98

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

Reviewed the solutions for the Audit Logs
Power apps looks ok
Power Automate too

### Anything else?

![coe app](https://user-images.githubusercontent.com/56973905/125822482-791dd7b9-4b85-489f-9af6-22996f842376.JPG)

**Comment by JeneferM-MSFT** [comment] 2021-07-15 16:39
Hello. Have we worked together on this already? Please provide that context. 
Can you also reclarify what version you are using? We have not gotten to that number yet. 
This is supported and we have customer getting audit logs in GCC so you will need to validate that your setup is correct. But before writing all that I want to be sure we haven't already had this conversation. 
Thank you

**Comment by JeneferM-MSFT** [comment] 2021-07-15 22:43
Yes it looks like this is the same issue we worked with in email. 
In the future please share all context when posting github issues. Else we could have spent a lot of time getting to the same details we already spent hours getting to. 

Here is where we are as far as I know
- The custom connector is bringing back only teams events, not events from Power Platform. 
- We have never seen this before and do have GCC customers using the solution. 
- The suggestion was to see if they have a M365 E3 or E5 license as that is required for posting to the event log for PP. PErhaps Teams requires something different
- To my knowledge this is the only lead we havent followed as they have G3 and assume its equivalent. Perhaps it is, I dont know. But if its not that could be the cause. 

Note that the toolkit is not a supported offering. And the product team is working on natively supporting Power Apps activities now. So this customer may just need to wait for that. 
Duplicate of #473

**Closed by JeneferM-MSFT** 2021-07-15 22:43 UTC
Labels: coe-starter-kit

**Comment by yeiner899** [comment] 2021-07-16 02:26
Yes, please dismiss the github case.

I think I found the issue

Yeiner Lopez

SUPPORT ENG

Power Platform

Office: +506 (4) 1161287<tel:+50641161287>

Mobile: 72244905

***@***.******@***.***>

6 AM - 3 PM CST


________________________________

**Comment by JeneferM-MSFT** [comment] 2021-07-16 13:03
Please share your findings here.

**Comment by yeiner899** [comment] 2021-07-16 13:24
Sure, I will soon

﻿ --
Yeiner Lopez
SUPPORT ENG
Power Platform
Office: +506 (4) 1161287
Mobile: 72244905
***@***.******@***.***>
6 AM - 3 PM CST

If you have any feedback about my work, please let either me or my manager Doug Verona know at ***@***.******@***.***>
[Microsoft]
﻿"The only difference between a good day and a bad day is your attitude"​



The content of this email including its attachments (the “Content”) is confidential and provided for information purposes only. It does not under any circumstance constitute a legally binding offer or acceptance of Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. This Content shall not be construed as (i) any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate and/or (ii) supplementing or amending the terms of any existing agreement with Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. In any case, any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate must be prior stated in an agreement drafted by Microsoft and signed by the duly authorized representatives of the Microsoft affiliate concerned and your company. Furthermore you are reminded that the Content is solely based on the information provided to us at the time of this email and that it will be subject to possible change.

**Comment by yeiner899** [comment] 2021-07-20 18:42
Hello Jenefer



  *   We reviewed the custom connector and the host was incorrectly, for GCC should be manage-gcc.office.com/<https://manage-gcc.office.com/>
  *   The app ID using in the custom connector was different so we grabbed the correct from Azure > Applications > Microsoft 365 Management
  *   The same for the secret ID
  *   We started the subscription from the custom connector using the Tenant and Application ID (this information from Azure)
  *   We fixed the connection

The flow started working and you are able to see the data into the app


﻿ --
Yeiner Lopez
SUPPORT ENG
Power Platform
Office: +506 (4) 1161287
Mobile: 72244905
***@***.******@***.***>
6 AM - 3 PM CST

If you have any feedback about my work, please let either me or my manager Doug Verona know at ***@***.******@***.***>
[Microsoft]
﻿"The only difference between a good day and a bad day is your attitude"​



The content of this email including its attachments (the “Content”) is confidential and provided for information purposes only. It does not under any circumstance constitute a legally binding offer or acceptance of Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. This Content shall not be construed as (i) any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate and/or (ii) supplementing or amending the terms of any existing agreement with Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. In any case, any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate must be prior stated in an agreement drafted by Microsoft and signed by the duly authorized representatives of the Microsoft affiliate concerned and your company. Furthermore you are reminded that the Content is solely based on the information provided to us at the time of this email and that it will be subject to possible change.


From: Yeiner Lopez
Sent: Friday, July 16, 2021 7:25 AM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] GCC Audit log is not showing any data. The flow runs successfully everyday and JSON response is 200 (#858)

Sure, I will soon

﻿ --
Yeiner Lopez
SUPPORT ENG
Power Platform
Office: +506 (4) 1161287
Mobile: 72244905
***@***.******@***.***>
6 AM - 3 PM CST

If you have any feedback about my work, please let either me or my manager Doug Verona know at ***@***.******@***.***>
[Microsoft]
﻿"The only difference between a good day and a bad day is your attitude"​



The content of this email including its attachments (the “Content”) is confidential and provided for information purposes only. It does not under any circumstance constitute a legally binding offer or acceptance of Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. This Content shall not be construed as (i) any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate and/or (ii) supplementing or amending the terms of any existing agreement with Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. In any case, any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate must be prior stated in an agreement drafted by Microsoft and signed by the duly authorized representatives of the Microsoft affiliate concerned and your company. Furthermore you are reminded that the Content is solely based on the information provided to us at the time of this email and that it will be subject to possible change.
