### ISSUE TITLE
[ALM Accelerator - BUG]: Variable reference is not valid. ':' 

### ISSUE THREAD

**Issue by HymansTesting** [microsoft/coe-starter-kit#3562] opened 2022-08-31 14:40 UTC
### Describe the issue

Experiencing error:

Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to 
delimit the name. 
At D:\a\_temp\2b4abb0c-c732-4f85-84f5-321d5feaf204.ps1:6 char:6938 
+ ... UniqueName":"fdfa7fe9-1d4a-e811-80d4-001dd8b71e0b","ownerEmail":""}]'

![image](https://user-images.githubusercontent.com/109288908/187705642-8feb3060-b3ae-4051-beaf-7e79c3148ec8.png)

### Expected Behavior

The step called "Update Solution Components Ownwership" to complete without issue or error.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

### Steps To Reproduce

Deploy solution from the ALM Accelerator.

**Comment by mikefactorial** [comment] 2022-08-31 16:28
Duplicate of https://github.com/microsoft/coe-starter-kit/issues/3563

**Closed by mikefactorial** 2022-08-31 16:28 UTC
Labels: bug, alm-accelerator
