### ISSUE TITLE
[ALM Accelerator - BUG]: Export solution failed due to Power BI sign on failure

### ISSUE THREAD

**Issue by sam-barrett-synsci** [microsoft/coe-starter-kit#6167] opened 2023-07-26 12:40 UTC
### Describe the issue

I am attempting to commit my latest Power BI additions to a branch. Within the environment's solution, we have a Power BI connection reference, Power Automate that uses a Power BI action with said connection reference, Data Set, and Power BI Report. We have embedded the Power BI Report within a model-driven app. We are using ALM for the commits and deploys. 

Whenever I commit to a branch and initiate the export of the solution, I receive this error:
"The reason given was: Your solution could not be exported. Sign in to your Power BI account, then give it another go."

We added PowerBI service permissions to ALM accelerator service principal but no change.

Here is the screenshot of the pac - Clone or Sync Solution step
![image](https://github.com/microsoft/coe-starter-kit/assets/118316484/8c39d84e-12f0-4cb4-b3cd-317fea67bebb)

### Expected Behavior

To sign into PowerBI when using ALM and export solution correctly.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

0d6679d2

### Steps To Reproduce

1. In ALM, commit customizations, creating a branch

**Comment by mikefactorial** [comment] 2023-07-28 17:37
@sam-barrett-synsci thanks for reporting this. Doesn't appear to be related to the ALM Accelerator. Would recommend opening a new isssue on https://github.com/microsoft/powerplatform-build-tools. Feel free to reference this issue as well.

**Comment by sam-barrett-synsci** [comment] 2023-07-28 20:12
@mikefactorial thank you for the link to the proper area.

**Comment by sdhsynsci** [comment] 2023-08-02 18:54
@mikefactorial this is has been raised on the powerplatform-build-tools https://github.com/microsoft/powerplatform-build-tools/issues/298 that group has marked it as external, any other suggestions on how to get this resolved it is blocking a very important go live for us.

**Comment by mikefactorial** [comment] 2023-09-06 17:51
Thanks @sdhsynsci. Based on the thread this is a Power BI related ALM issue Unfortunately, there's nothing we can do at the moment until the issue is fixed by the Power BI Team. Going to close this out for now.

**Closed by mikefactorial** 2023-09-06 17:51 UTC
Labels: bug, alm-accelerator
