### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Check Deleted (Custom Connectors) and Sync Template v3 (custom connectors) failing invalid response from API 'powerappsforappmakers'

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#5616] opened 2023-05-24 10:19 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have recently started to receive the errors from the flow runs across nearly all environments for the CLEANUP HELPER - Check Deleted (Custom Connectors) and Sync Template v3 (custom connectors) flow. The issue happens at the 'Get Custom Connectors and store them in CoE CDS Entity' scope (in Admin | Sync Template v3 (Custom Connectors) flow) at the 'Get Connectors' action and at the 'Build array of custom connectors that still exist' scope (in CLEANUP HELPER - Check Deleted (Custom Connectors) flow) at the 'Get Connectors' action:

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/93/properties/connectionParameters/username/uiDefinition/constraints/clearText' to be of type 'Boolean' but is of type 'String'.'

CLEANUP HELPER - Check Deleted (Custom Connectors):

<img width="305" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/81301f1d-5a2d-444a-8c95-ebe462f39e43">

Admin | Sync Template v3 (Custom Connectors)

<img width="290" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/02a02cd8-ed3c-4b88-9506-f6a3014828d2">

### Expected Behavior

Get connectors for the environment within the filter query

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors); CLEANUP HELPER - Check Deleted (Custom Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run the Admin | Sync Template v3 (Custom Connectors) flow or CLEANUP HELPER - Check Deleted (Custom Connectors) flow
2. Error occurs at Get Connectors stage

**Comment by manuelap-msft** [comment] 2023-05-24 10:54
Duplicate of #5580.

This is a product issue (a bug with the connector) and there's nothing we can do it in the CoE kit to fix this - we are just consumers of the connector. 

We recommend creating a sample flow **outside** of the CoE kit that uses this action (see an example here: https://github.com/microsoft/coe-starter-kit/issues/5580#issuecomment-1554557152) and raising a support ticket with Microsoft support so they can look into this. 

I'll close this as duplicate, and you can add further comments to  #5580 so we can track this in one place.

**Closed by manuelap-msft** 2023-05-24 10:54 UTC
Labels: bug, coe-starter-kit

**Comment by miguelverweij** [comment] 2023-05-31 07:58
I had the same issue after updating. I created a manually triggered flow with the power apps for makers connector with the get connectors call. The first run failed, the second succeeded. after that, all the failed flow worked after resubmitting it. Just posting this as it might help those who experience the same.
