### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Inactivity notifications v2 (Start Approval for Flows)

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4069] opened 2022-10-28 14:27 UTC
### What is your question?

Turned on following flows:

Admin | Inactivity notifications v2 (Check Approval)
Admin | Inactivity notifications v2 (Clean Up and Delete)
Admin | Inactivity notifications v2 (Start Approval for Apps)
Admin | Inactivity notifications v2 (Start Approval for Flows)

We started getting dozens of emails in regard to the following -

![image](https://user-images.githubusercontent.com/24686498/198643671-953fd821-69d8-4c1b-b50a-43fcd04e6abf.png)

We are getting these in regard to flows, apps, for manager to approve a selected file etc.

I'm not sure what I'm supposed to do to resolve the error.  What permissions are the makers needing exactly?

Also, it is still sending emails out even though I stopped the flows 20 minutes ago.  Please advise how to stop them

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Oct 2022

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

**Comment by manuelap-msft** [comment] 2022-10-28 15:19
Looks like this is a duplicate of your other issue so I'll close that out!

**Closed by manuelap-msft** 2022-10-28 15:19 UTC
Labels: question, coe-starter-kit
