### ISSUE TITLE
[ALM Accelerator - BUG]: All SharePoint sites not listed in Environment variable configuration

### ISSUE THREAD

**Issue by antonydineshhenry** [microsoft/coe-starter-kit#2041] opened 2022-02-14 09:41 UTC
### Describe the issue

I am trying to set a data source environment variable to point to different SharePoint sites and lists for the Validation and Production environments. However, I find that not all the SharePoint sites in the environment are listed in the list of sites. I have tried using the global admin account as well and do not find many of the sites.
It is also not possible to just type in a site URL and then select the lists. The lists are dependent on the site selection.

Another issue related to this was that if I do configure a SharePoint site and some lists for the environment variable in Validation, the same is not applied when the solution is deployed to the Validation environment. The environment variables are still pointing to the site and lists used in the DEV (maker) environment.

### Expected Behavior

- All the SharePoint sites in the tenant to be available for selection in the Environment variable configuration and the lists to be available based on the site
- The site and lists configured in the environment variable should be applied when deployment of the solution to validation and production is done. It should not hold the values in the Dev environment

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

### Steps To Reproduce

1. Create a profile for the deployment of a solution
2. Go to Commit solution and prepare the environment variables
3. Try to select a SharePoint site and lists
4. Not all SharePoint sites are listed. 
5. If a site and lists are selected and then the solution is deployed to Validation, then it still points to the site and lists in DEV

**Comment by mikefactorial** [comment] 2022-02-14 12:36
Hey @antonydineshhenry,
Thanks for reporting this and for the detailed issue notes. This looks like a duplicate of #1460. Will close out this issue for now and add a note to #1460 linking back. Feel free to add any follow-up you have to that issue. Thanks!

**Closed by mikefactorial** 2022-02-14 12:36 UTC
Labels: bug, alm-accelerator

**Comment by dspencelink** [comment] 2025-01-22 20:11
@antonydineshhenry See my fix to the flow in #7839
