### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL_CoE_Dashboard_January2024 not prompting for URL's - setting and clearing the parameters from being stored

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#7417] opened 2024-01-09 15:47 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are trying to create the Power BI report from the BYODL_CoE_Dashboard_January2024.pbit file and when opening the file it does not ask for the environment, dataflow or workspace URL's. It immediately opens with the screen below

<img width="823" alt="CoE090124" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/d8fbfdb7-e6c1-4bc2-8558-43a6648269e0">

Is there a process to enter the URL's after the Power BI report has opened if it does not prompt for us to enter them when opening the PBIT file?

### Expected Behavior

1. Open  BYODL_CoE_Dashboard_January2024.pbit file
2. Enter the URL of your environment instance, including the https:// prefix for OrgUrl. Enter the ID to your Power BI Workspace for Power BI Workspace ID. Enter the ID to your Power BI Dataflow for Power BI Dataflow ID. If prompted, sign in to Power BI Desktop with your organization account that has access to the environment you installed the CoE Starter Kit in.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power BI Report for BYODL

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Open  BYODL_CoE_Dashboard_January2024.pbit file

At this point we are not prompted to enter the enviornment, dataflow or workspace URL

AB#1990

**Comment by Jenefer-Monroe** [comment] 2024-01-09 16:20
Hello. I dont repro this. I do see the parameters when I open like this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74242616-fccc-407f-8720-23a0d4c242f5)

Perhaps you were touching the wrong file. Here is the PBIT again (zipped up so I can share here)
[BYODL_CoEDashboard_January2024.zip](https://github.com/microsoft/coe-starter-kit/files/13876270/BYODL_CoEDashboard_January2024.zip)

Can you please try again?

**Comment by G1982C** [comment] 2024-01-09 16:29
Thanks. We were using the pbit file from the release section of the CoE Git Hub. I have tried the file that you shared and I get the exact same issue. We have also tried it on a different machine and get the same issue. 

I am confused as to what the problem might be if it works for you. I have tried an older version of the pbit and get the same issue, although it must have worked previously as it was used to create the report.

**Comment by Jenefer-Monroe** [comment] 2024-01-09 16:41
Strange. I'm not a PBI expert so I'll be guessing here but perhaps it can be resolved by clearing your data source settings? 
Open PBI without any files > File > Options and settings > Data source settings 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b56beaea-a35b-474d-b1e8-dec610889dc0)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/319a287c-e5fc-4bba-b033-8f88c7f93618)

**Comment by Jenefer-Monroe** [comment] 2024-01-09 17:36
I'm just not sure then. It seems to be attaching to some default data source. But I've never heard of anyone else hitting this. 
Lets see if anyone in the community has ideas. Do you come to office hours? Perhaps you can ask there.

**Comment by G1982C** [comment] 2024-01-09 17:38
Thanks Jenefer. I do have it in my diary, but don't always attend due to availiability. 

I have raised a support ticket with Microsoft to see if their Power BI team can assist. Do you have a technical term for the box that appears asking for the URL's? :-)

**Comment by G1982C** [comment] 2024-01-09 18:08
Just to update you, we have found a workaround in case anyone else gets this issue: 

1. Open the *.pbit file, select discard changes
2. Then select file --> Open --> select the same *.pbit file
3. On this occassion you will be prompted for the urls

I have managed to replicate this on every occassion, so seems a plausible workaround

**Comment by G1982C** [comment] 2024-01-10 08:19
Thanks Jenefer. You wouldn't believe I passed the Power BI Exam a couple of years agoi if I didn't know that :-)

**Comment by stevealldridge** [comment] 2024-01-10 10:46
I can confirm that I had exactly the same issue as noted here, and also that the workaround also worked for me too

**Comment by Jenefer-Monroe** [comment] 2024-01-10 14:41
I'm going to mark this as a thing for documentation. So will hold it open while that gets done.

**Comment by pnoot7** [comment] 2024-04-08 19:17
I can confirm I also have this issue when using the "Production_CoEDashboard_April2024.pbit". Should I open a separate issue for this (this thread seems to focus on the BYODL version)? The odd double opening does give the prompt to enter the URL and select tenant type. 

Before finding this thread, I did publish the dashboard without the URL, and found the parameters in the model in the web app, but was not sure what the accepted values for tenant type are - at the time. (for me seems to simply be GCC)

The documentation is still not updated for this issue.

**Comment by reymesEDC** [comment] 2024-04-16 14:51
Hello. I also had this issue when using the "Production_CoEDashboard_March2024.pbit" file and the same solution worked for me.
Thanks G1982C

**Comment by robertcaretta** [comment] 2024-05-15 20:23
Same issue for me with the May 2024 release. After much headache found this thread. G1982C's work-around helped.

**Comment by Jenefer-Monroe** [comment] 2024-05-20 13:40
local fixed in documentation. Thanks for debugging, I have never seen this issue so would not have been able to assist others.

**Closed** 2024-06-10 16:12 UTC
Labels: documentation, coe-starter-kit, officehourTHANKS
