### ISSUE TITLE
Unable to see any visual in Pulse Dashboard

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#6251] opened 2023-08-07 01:51 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When the Pulse Dashboard is updated with Aug 2023 release then i see no visuals appearing on the dashboard

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/32cfbbde-c378-4e0a-85e7-760a53e8b996)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/1232d38b-f988-431a-8ee0-0558a498b5e3)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/34f47f30-c5b6-4a7d-9c35-d4b627202620)

### Expected Behavior

All visuals should load correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Aug 2023 PBI

### What app or flow are you having the issue with?

Pulse Dashboard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open the pbit file for Aug 2023 setup in Power BI desktop

**Comment by manuelap-msft** [comment] 2023-08-07 13:00
We haven't updated this Power BI dashboard and the data model in a long time (not since the initial release sometime last year). Likely a change in Power BI Desktop has caused some issues here. We're investigating how to update this.

**Comment by manuelap-msft** [comment] 2023-08-07 15:06
Could you please check to see if this version works for you now:
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Pulse_CoEDashboard.pbit

Thank you!

(The issue is due to how the PBI Dataverse connector returns fields for the data mapping. It used to return the unique name of a field, e.g. pcat_admintask, and now returns the display name, e.g. Admin Task. We have updated the PBIT file to point the visuals to the new names.)

**Comment by girishuppal** [comment] 2023-08-07 22:37
The new PBIT file fixed the issue. Thanks so much for the quick turn around

**Comment by manuelap-msft** [comment] 2023-08-09 11:49
Closing out as this is now fixed, and the PBIT file has been updated in the release.

**Closed by manuelap-msft** 2023-08-09 11:49 UTC
Labels: bug, coe-starter-kit, product-gap
