### ISSUE TITLE
[CoE Starter Kit - BUG] Error for Admin | Sync Template v3 (Custom Connectors)

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3429] opened 2022-08-11 10:20 UTC
### Describe the issue

Hi ,
We are experiencing the following error when the following flow runs: It would appear that this occured when an Environment Request was approved but I am not 100% certain of that.

Admin | Sync Template v3 (Custom Connectors)
![image](https://user-images.githubusercontent.com/48433526/184113408-d9da7511-7a7d-4c84-a23c-9c256c85c4c9.png)

Other flows also failed at the same time:

![image](https://user-images.githubusercontent.com/48433526/184100602-e011acf3-6ea9-4251-a5ed-5523d9f293cf.png)

**Admin | Sync Template v3 (Apps)**
The 'inputs.parameters' of workflow operation 'Get_Custom_Connectors_as_Admin' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'environment'

![image](https://user-images.githubusercontent.com/48433526/184100847-0f102798-8cec-401a-8b4c-573fdde09dbe.png)

**Admin | Sync Template v3 (Connection Identities)**
![image](https://user-images.githubusercontent.com/48433526/184113117-21813b81-e888-465d-8829-adb2dbb30a60.png)

### Expected Behavior

Flows do not fail!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

**Comment by myatix** [comment] 2022-08-12 06:12
It would appear that the Environment is null???

{
    "host": {
        "connectionReferenceName": "shared_powerappsforadmins",
        "operationId": "Get-AdminConnectors"
    },
    "parameters": {
        **"environment": null,**
        "api-version": "2017-05-01",
        "$top": 250
    }
}

**Comment by myatix** [comment] 2022-08-12 06:17
On the Admin | Sync Template v3 (PVA) flow we are getting this error every day!

![image](https://user-images.githubusercontent.com/48433526/184295618-5c621a4f-8c24-4861-84ab-567a4e03b061.png)

**Comment by myatix** [comment] 2022-08-12 06:22
On the Admin | Sync Template v3 (Business Process Flows)

We get the following error:

**admin_Maker With Id = ABCDEF-b53a-4ef1-8bc5-123456789 Does Not Exist**

![image](https://user-images.githubusercontent.com/48433526/184296133-16f0d5b2-8cbb-431a-be0c-e17e390d1b2f.png)

**Comment by Jenefer-Monroe** [comment] 2022-08-12 11:05
We cannot have this many issues in one bug, its too hard to track. I will hide the comments above to make tracking easier. 
I believe both the PVA and BPF ones are known and fixed. The PVA one in the past (look for and remove unmanaged layers). The BPF one in Sept. Please investigate and search before posting new issues for each.

**Comment by Jenefer-Monroe** [comment] 2022-08-12 11:26
The envt there should not be null, its a property we copy directly from the product in another flow and is used all over the kit.

Let's see how broad the issue is first. 
In the Core solution go to tables > Environment > make sure the Name column is present
![image](https://user-images.githubusercontent.com/89584709/184344683-b9c8ca9d-c3c5-4058-92bf-6818250539c8.png)
And filter the Name column to Does not contain data
![image](https://user-images.githubusercontent.com/89584709/184344857-62c1d936-1f10-44a5-b8b8-061c2141e8fe.png)

How many records show up? There should be none.

**Comment by myatix** [comment] 2022-08-15 10:37
Strange! There are no environments with Null in the Name field.

![image](https://user-images.githubusercontent.com/48433526/184620943-39690903-7991-422b-a164-4682d9383fc2.png)

**Comment by Jenefer-Monroe** [comment] 2022-08-15 13:29
That is strange. OK lets get back to the flow then and see whats wrong there. 

1. Open the flow in edit mode, and make sure these two calls look like this:
![image](https://user-images.githubusercontent.com/89584709/184643616-a2bedbc2-33da-4a69-a3bf-46ef9b1d2305.png)

2. Open the failed run and expand the trigger, look for a column called admin_environmentname. It should be your envt GUID. Is it also null or is it your GUID? 
![image](https://user-images.githubusercontent.com/89584709/184644051-57ca400a-3e9b-4f1b-86d6-8abe484e95f2.png)

3. I've seen some weird caching issues lately. If you turn this flow off and back on, then Resubmit the run, does it still fail?
![image](https://user-images.githubusercontent.com/89584709/184644280-053c8b6e-d085-430d-83dc-62d60b7a6f4d.png)

**Comment by Jenefer-Monroe** [comment] 2022-08-28 18:30
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-08-28 18:30 UTC
Labels: bug, coe-starter-kit
