### ISSUE TITLE
[ALM Accelerator - BUG]: Can't able to deploy the solution into test environment instead its deploying to the validation(Dev environment).

### ISSUE THREAD

**Issue by Vaddeani** [microsoft/coe-starter-kit#2496] opened 2022-04-18 16:37 UTC
### Describe the issue

Even if I select the test environment as the target branch(AA4PP App) and click on Deploy solution, after the successful run by pipeline.
Next I approved the PR it should kick off the test build {deploy-test-(solutionName)} pipeline, but its triggering with the deploy-validation-(solutionName) pipeline.
Let me know whether am I missing with any of the configurations or please let me know the process of deploying the solution from DEV-TEST-PROD.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/103512064/163840707-007e4155-89d2-4ec9-960e-30890b901b6a.png)

### Expected Behavior

When I deploy solution and turn off Advanced settings, and select the test environment, the solution should be moved to the test environment.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220406.1

### Steps To Reproduce

1.Comit a solution to source control. After the success run by export-to-git pipeline.
2.Click on deploy solution.
3.Turn off Advanced settings and select the test environment, Click on Deploy Solution.

**Comment by mikefactorial** [comment] 2022-04-18 17:09
@Vaddeani this is the expected behavior. The deployment to test will create a Pull Request in Azure DevOps to be approved before the solution is deployed to test. Part of the approval process is a branch policy in Azure DevOps that runs the validation pipeline to validate the solution can be successfully built and deployed to provide the PR reviewer with assurance that the source code is valid for deployment. This is explained in a little more depth in the docs for the advanced maker scenario but it applies to both the maker and advanced maker scenarios. https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-advancedmaker

**Comment by mikefactorial** [comment] 2022-04-18 19:34
@Vaddeani can you tell me which branch  the PR was merged into? This may be an issue with the destination branch that is selected by default on the initial deploy.

**Comment by Vaddeani** [comment] 2022-04-19 15:33
Hi Mike,
Thanks for  the Response,
PR merged into Target branch (Almsetupcheck), which we have selected during initial deploy. Now I am able to successfully execute deploy-validation-solutionname, post that we are running the other pipelines such as Test and production ( deploy-test-solutionname, deploy-prod-solutionname) manually.

Is this  the expected behavior or the above mentioned pipelines should  get automatically trigger.
Please confirm the same, appreciate your help.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/103512064/164038334-a3c1ffa2-a2c3-4f85-98d8-9e47b4e8996a.png)

Thanks.
Anil kumar

**Comment by mikefactorial** [comment] 2022-04-20 13:47
@Vaddeani have you completed the PR that gets created when you deploy? You will need to complete/merge the PR in order for the test pipeline to run. Deployment to test and production require manual approval via the Pull Requests in order to be deployed.

Here's the basic steps for deployment

1. Commit create new working branch from main
2. Deploy to test is PR from working branch to solution branch (kicks off validation build)
3. Complete PR kicks off test build
4. Deploy to prod is PR from solution branch to main (kicks off production build)
5. Next commit create new working branch from solution branch
6. Repeat from step 2

**Comment by RoyPaarMS** [comment] 2022-04-22 17:12
@mikefactorial @jenschristianschroder @Grant-Archibald-MS Adding my findings here as they are partially in line with @Vaddeani. 

As an advanced maker (sys admin who setup the ALM accelerator using CoE CLI), I can commit to ADO and see a solution branch and working branch, both based on the main branch.  Solution branch has pipelines but no solutions files, working branch has solution package but no pipelines. When I click deploy, if I specifically leave the source branch as working branch and change the target branch to solution branch (defaults to main), then the build validation is started as soon as I grant permissions (prior to completing pull request).  **Completing the PR merges the working branch into the solution branch but does not trigger pipeline to deploy solution to test**.  If I trigger the pipeline manually in ADO it works.  I can also trigger the prod pipeline manually as well with no issue.
![image](https://user-images.githubusercontent.com/86677937/164761642-91005dd9-9d13-4a9a-b7ef-8b01a38856fc.png)


If I pretend to be a maker (sys admin who setup the ALM accelerator using CoE CLI), I can "save" to ADO and I see a solution branch and a working branch. When I deploy to test, I see no pull request (I think because I have set approval type to none in my deployment profile for this environment) and when I grant permissions, the deployment to test pipeline kicks off and fails at "Update solution XML with build number" step.  It's looking in my solution branch for my solution package, but the solution package doesn't exist there, at this point it only exists in the working branch because it hasn't been merged yet.  Maybe there is a setting somewhere I can change?
![image](https://user-images.githubusercontent.com/86677937/164761765-b0a6000f-2568-4029-860b-02460dd374f4.png)


If I open a new session as a true maker (user in AAD group with roles as per documentation, ALM canvas app in COE environment shared with AAD group, environment maker and sys customizer roles in DEV environment), then I see a variety of other issues.
	1. error when trying to choose a profile for a solution (something about git branches permissions)
![image](https://user-images.githubusercontent.com/86677937/164761834-43f32a20-33a4-4bd4-968b-a0524385cd38.png)

	2. no environments listed in prepare screens
![image](https://user-images.githubusercontent.com/86677937/164761882-caa85483-dbcf-431c-952c-0d6666aacb22.png)

	3. pipeline not valid when trying to commit
![image](https://user-images.githubusercontent.com/86677937/164761932-2a7d902e-94a9-49a2-ab3d-e0a404558dc7.png)

	4. also see discrepancy between status indicators when logged into different sessions/identities
![image](https://user-images.githubusercontent.com/86677937/164761964-3f2b52a5-0e73-42ad-bae5-55aaaba44c96.png)

**Comment by mikefactorial** [comment] 2022-04-22 17:45
@RoyPaarMS Thank you for the detailed information. 

1. We do have an existing issue related to the test and production builds not triggering that we have fixed for the May release (https://github.com/microsoft/coe-starter-kit/issues/2325 and for more reference see https://github.com/microsoft/coe-starter-kit/issues/2490#issuecomment-1099808339)
2. Changing the approval types in the profile requires additional changes to the pipelines. Unfortunately, we don't have documentation around how to use these features to customize your pipelines currently.
3. Additional Items
   - 1. This error is innocuous. However, we have a fix in the May release to handle it better so the error doesn't appear to the user.
   - 2. Will look into handling this better. However, in order for users to configure deployment settings they will need access to the target environment(s) and at least Basic User permissions.
   -  3. May need more information here. For the maker that is seeing this were they added to the project via https://github.com/microsoft/coe-starter-kit/blob/main/coe-cli/docs/help/alm/maker/add.md?
   -  4. This is expected. The indicators on the solution list are intended to show the current users latest actions against the solution. Makers can view all deployment request history by viewing the history using the > arrow on the right hand side.

**Comment by RoyPaarMS** [comment] 2022-04-22 19:43
thanks @mikefactorial for the quick response.  
1. will wait for May release
2. will reset approval types to pull request.  Can't recall initial setup - were all three set to pull request or only TEST/PROD?
![image](https://user-images.githubusercontent.com/86677937/164781444-d241d680-3989-4183-8b08-53a50a07558d.png)

3. 
i. thanks
ii. just created a new AAD security group, added my maker, added to all environments with Basic User role, still seeing the error.  
iii. did not initially use this command to add user but just ran the command and seems like user was set up correctly.  Still seeing the error on commit to repo.
![image](https://user-images.githubusercontent.com/86677937/164783197-f40d78f8-e6b7-4856-9fe9-7203e30a608f.png)

iv. thanks

**Comment by mikefactorial** [comment] 2022-05-02 14:35
@RoyPaarMS just getting back to this. Was looking at the specific error message again for the export issue and noticed this
![image](https://user-images.githubusercontent.com/42348035/166252194-58fc0d02-5a8c-4177-8deb-62860c746cf6.png)

The fact that it is showing refs/heads/$(Branch) leads me to believe that the Branch variable is not being passed into the export pipeline from the app. I wonder if you could take a look at the variables being passed into the pipeline. Specifically, there should always be a Branch variable passed into that pipeline like the following. Are you seeing variables coming into the pipeline?

![image](https://user-images.githubusercontent.com/42348035/166252564-be14275c-bc59-4b54-91f9-ff517bfd5852.png)

**Comment by RoyPaarMS** [comment] 2022-05-04 16:14
hi @mikefactorial - Sorry can't test this at the moment as I am stuck back with item 3.ii.   I am again seeing the environment filter empty when I try to navigate to the config screen as a maker.  I have run the maker add command and have added the user to my basic users ad security group team which has the basic user role.  I still have no issues when I do this as my sys admin account that I used to install the solution and setup ADO.  Here's the error again
![image](https://user-images.githubusercontent.com/86677937/166723653-9a7a4a7b-8027-4e2b-98de-9552511c7ed0.png)

**Comment by mikefactorial** [comment] 2022-05-04 16:19
@RoyPaarMS this is a permissions issue we've been working through. Pretty sure it's related to the PowerAppsForMakers connector needing access to something in Dataverse that the Basic User doesn't have access to been trying to track it down, but could be related to this https://github.com/microsoft/coe-starter-kit/issues/123

**Closed** 2022-07-01 14:49 UTC
Labels: question, alm-accelerator, follow-up, awaiting-reply
