### ISSUE TITLE
[ALM Accelerator - BUG]: Pipelines not created on first commit

### ISSUE THREAD

**Issue by LukasSchauffele** [microsoft/coe-starter-kit#5587] opened 2023-05-22 01:53 UTC
### Describe the issue

I committed a solution for the first time. The commit succeeded according to the _export-to-git_ pipeline but no deployment pipelines were created.

Log of export-to-git:

```
Pool: Azure Pipelines
Image: windows-2022
Agent: Hosted Agent
Started: Today at 10:34 am
Duration: 4m 25s

Job preparation parameters
Variables:
  AadHost: $[ variablegroups.alm-accelerator-variable-group.AadHost ]
  CdsBaseConnectionString: $[ variablegroups.alm-accelerator-variable-group.CdsBaseConnectionString ]
  clientId: $[ variablegroups.alm-accelerator-variable-group.clientId ]
  tenantId: $[ variablegroups.alm-accelerator-variable-group.tenantId ]
ContinueOnError: False
TimeoutInMinutes: 60
CancelTimeoutInMinutes: 5
Expand:
  MaxConcurrency: 0
  ########## System Pipeline Decorator(s) ##########

  Begin evaluating template 'system-pre-steps.yml'
Evaluating: eq('true', variables['system.debugContext'])
Expanded: eq('true', Null)
Result: False
Evaluating: resources['repositories']['self']
Expanded: Object
Result: True
Evaluating: not(containsValue(job['steps']['*']['task']['id'], '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Expanded: not(containsValue(Object, '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Result: False
Finished evaluating template 'system-pre-steps.yml'
********************************************************************************
Template and static variable resolution complete. Final runtime YAML document:
steps: []


  MaxConcurrency: 0
Parent pipeline used these runtime parameters
Branch : "main"
BranchToCreate : "lukask@fleetwood.com.au-EnvironmentRefresh"
BuildDefinitionId : "NA"
CommitMessage : "Initial commit"
Data : "[{\"ApprovalType\":809060000,\"BuildName\":\"deploy-validation-EnvironmentRefresh\",\"BuildTemplate\":null,\"DeploymentEnvironmentName\":\"Validation\",\"DeploymentEnvironmentUrl\":\"https://fleetwood-validation.crm6.dynamics.com/\",\"EnvironmentUrl\":\"https://fleetwood-coe.crm6.dynamics.com/\",\"ServiceConnectionName\":null,\"StepType\":null,\"UserSettings\":[{\"Name\":\"canvasshare.aadGroupId.bis_refreshenvironment_95cce\",\"Value\":\"\"},{\"Name\":\"canvasshare.roleName.bis_refreshenvironment_95cce\",\"Value\":\"CanView\"},{\"Name\":\"owner.ownerEmail.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"flow.sharing.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.order.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"1\"},{\"Name\":\"activateflow.activate.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"flow.sharing.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.order.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"2\"},{\"Name\":\"activateflow.activate.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"flow.sharing.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.order.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"3\"},{\"Name\":\"activateflow.activate.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"flow.sharing.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.order.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"4\"},{\"Name\":\"activateflow.activate.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"flow.sharing.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.order.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"5\"},{\"Name\":\"activateflow.activate.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"flow.sharing.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.order.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"6\"},{\"Name\":\"activateflow.activate.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"flow.sharing.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"activateflow.order.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"7\"},{\"Name\":\"activateflow.activate.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"true\"},{\"Name\":\"TriggerSolutionUpgrade\",\"Value\":\"false\"},{\"Name\":\"UserSettingId\",\"Value\":null}],\"VariableGroup\":null},{\"ApprovalType\":809060000,\"BuildName\":\"deploy-test-EnvironmentRefresh\",\"BuildTemplate\":null,\"DeploymentEnvironmentName\":\"Test\",\"DeploymentEnvironmentUrl\":\"https://fleetwood-uat.crm6.dynamics.com/\",\"EnvironmentUrl\":\"https://fleetwood-coe.crm6.dynamics.com/\",\"ServiceConnectionName\":null,\"StepType\":null,\"UserSettings\":[{\"Name\":\"canvasshare.aadGroupId.bis_refreshenvironment_95cce\",\"Value\":\"\"},{\"Name\":\"canvasshare.roleName.bis_refreshenvironment_95cce\",\"Value\":\"CanView\"},{\"Name\":\"owner.ownerEmail.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"flow.sharing.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.order.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"1\"},{\"Name\":\"activateflow.activate.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"flow.sharing.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.order.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"2\"},{\"Name\":\"activateflow.activate.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"flow.sharing.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.order.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"3\"},{\"Name\":\"activateflow.activate.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"flow.sharing.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.order.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"4\"},{\"Name\":\"activateflow.activate.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"flow.sharing.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.order.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"5\"},{\"Name\":\"activateflow.activate.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"flow.sharing.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.order.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"6\"},{\"Name\":\"activateflow.activate.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"flow.sharing.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"activateflow.order.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"7\"},{\"Name\":\"activateflow.activate.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"true\"},{\"Name\":\"TriggerSolutionUpgrade\",\"Value\":\"false\"},{\"Name\":\"UserSettingId\",\"Value\":null}],\"VariableGroup\":null},{\"ApprovalType\":809060000,\"BuildName\":\"deploy-prod-EnvironmentRefresh\",\"BuildTemplate\":null,\"DeploymentEnvironmentName\":\"Prod\",\"DeploymentEnvironmentUrl\":\"https://fleetwood.crm6.dynamics.com/\",\"EnvironmentUrl\":\"https://fleetwood-coe.crm6.dynamics.com/\",\"ServiceConnectionName\":null,\"StepType\":null,\"UserSettings\":[{\"Name\":\"canvasshare.aadGroupId.bis_refreshenvironment_95cce\",\"Value\":\"\"},{\"Name\":\"canvasshare.roleName.bis_refreshenvironment_95cce\",\"Value\":\"CanView\"},{\"Name\":\"owner.ownerEmail.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"flow.sharing.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.order.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"1\"},{\"Name\":\"activateflow.activate.ExecuteCurrentTask.1d73ed69-0aea-ed11-8848-00224810b565\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"flow.sharing.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.order.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"2\"},{\"Name\":\"activateflow.activate.DetermineNextTask.5b0594d9-b6eb-ed11-8849-00224893358a\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"flow.sharing.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"\"},{\"Name\":\"activateflow.order.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"3\"},{\"Name\":\"activateflow.activate.MonitorRunCommandInstance.5e4f78b1-ced8-ed11-a7c7-00224893358a\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"flow.sharing.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.order.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"4\"},{\"Name\":\"activateflow.activate.ExecuteRunCommand.15414ace-cfeb-ed11-8849-0022489336e2\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"flow.sharing.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"\"},{\"Name\":\"activateflow.order.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"5\"},{\"Name\":\"activateflow.activate.EnvironmentRefreshApproval.e8231f98-07ea-ed11-8848-00224810b565\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"flow.sharing.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"\"},{\"Name\":\"activateflow.order.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"6\"},{\"Name\":\"activateflow.activate.InitiateRefreshProcess.9e5c88f1-f5eb-ed11-8849-0022489336e2\",\"Value\":\"true\"},{\"Name\":\"owner.ownerEmail.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"flow.sharing.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"activateflow.activateas.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"\"},{\"Name\":\"activateflow.order.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"7\"},{\"Name\":\"activateflow.activate.TransferCompanyData.0872fd23-08f7-ed11-8848-00224893374f\",\"Value\":\"true\"},{\"Name\":\"TriggerSolutionUpgrade\",\"Value\":\"false\"},{\"Name\":\"UserSettingId\",\"Value\":null}],\"VariableGroup\":null}]"
Email : "lukask@fleetwood.com.au"
EnvironmentName : "NA"
ImportUnmanaged : "NA"
PipelineId : "35"
PortalSiteName : "NA"
CommitScope : "1"
PublishCustomizations : "true"
Project : "power-platform"
Repo : "power-platform"
ServiceConnectionName : "https://fleetwood-development.crm6.dynamics.com/"
ServiceConnectionUrl : "https://fleetwood-development.crm6.dynamics.com/"
SolutionName : "EnvironmentRefresh"
UserName : "Lukas Schauffele"
```

No deployment pipelines created

![CleanShot 2023-05-22 at 11 47 05](https://github.com/microsoft/coe-starter-kit/assets/7881214/93804f23-ead5-41ab-8979-65ff05cb9d9d)

Deployment settings were created:

![CleanShot 2023-05-22 at 11 49 43](https://github.com/microsoft/coe-starter-kit/assets/7881214/6a1bda1a-7a2f-44fb-8005-f86cd1e18772)

### Expected Behavior

Automatic creation of validation, test, and production deployment pipelines.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

May 2023

**Comment by LukasSchauffele** [comment] 2023-05-22 23:05
@mikefactorial - just emailed you the logs.

**Comment by mikefactorial** [comment] 2023-05-23 13:31
The only issue I'm seeing in the logs is the following
2023-05-22T00:38:35.7433618Z Error while retrieving queues.  Queue not found: Azure Pipelines
Can you take a look at what runners are available in the AzDO project? If you are using self-hosted runners this could be the problem.

**Comment by mikefactorial** [comment] 2023-05-25 12:54
@LukasSchauffele another possibility for the pipelines not being able to find the default queue (Azure Pipelines) is a permissions issue specifically check this documentation on what permissions are required https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#update-permissions-for-the-project-build-service. One of the build permissions required is "Manage build queue"

**Comment by mikefactorial** [comment] 2023-05-25 13:30
You can also verify that the queue exists under project settings
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/7d862257-adbf-4357-ace1-7532c7cf0ecf)

**Comment by LukasSchauffele** [comment] 2023-05-26 09:55
> If you are using self-hosted runners this could be the problem.

I'm not using a self-hosted runner. Just the default one.

One thing comes to mind: previously when first committing a project, I would have to manually go into each deployment pipeline and set the 'Default agent pool for YAML' to `Azure Pipelines` (been meaning to submit a bug report). 

![CleanShot 2023-05-26 at 19 52 09](https://github.com/microsoft/coe-starter-kit/assets/7881214/ca4805c4-074c-40be-ab08-d1ab95d1d191)

I've never had any issues with permissions previously, but here they are:

![CleanShot 2023-05-26 at 19 49 50](https://github.com/microsoft/coe-starter-kit/assets/7881214/692440af-14d2-4e9e-99e4-ad1ebafcb544)

![CleanShot 2023-05-26 at 19 48 11](https://github.com/microsoft/coe-starter-kit/assets/7881214/096450ea-6f11-45a4-9497-376a09573f4c)


![CleanShot 2023-05-26 at 19 45 00](https://github.com/microsoft/coe-starter-kit/assets/7881214/875f099f-d2cd-48b6-9374-eeeb450921d0)

![CleanShot 2023-05-26 at 19 46 24](https://github.com/microsoft/coe-starter-kit/assets/7881214/a28c6579-90c5-4f22-aa6f-39bbffffe60a)

**Comment by LukasSchauffele** [comment] 2023-05-26 10:35
I've created a new solution with a single flow and seeing the same behaviour. _export_solution_to_git_ completes successfully but no deployment pipelines are created.

![CleanShot 2023-05-26 at 20 29 52](https://github.com/microsoft/coe-starter-kit/assets/7881214/11b56aac-4538-48ee-af4d-4ca436623b52)

I've also tried deploying out of ALM Accelerator app but nothing is happening with the PR

![CleanShot 2023-05-26 at 20 31 12](https://github.com/microsoft/coe-starter-kit/assets/7881214/b0af8026-879d-4a77-a438-d84c89bddb28)

@mikefactorial at which step are the pipelines created?

I've double checked that both solution and templates are the latest version.

**Comment by mikefactorial** [comment] 2023-05-26 12:48
Deployment pipelines are created in the Update Deployment Settings step of the export pipeline. We recently (in May) moved away from using the coe-cli in our pipelines for generating the deployment pipelines and ported that code over to powershell in the pipeline. I can see that there was a change to the way we generate the pipelines in the may update specifically related to whether or not the default queue can be found. The change is that the pipelines won't be generated if the queue isn't found so that's more than likely the behavior you are seeing. Previously, the pipelines were created just without the default queue set which is the behavior you were seeing. However, that being said, it still does seem like a permissions issue that is causing the default queue to not be available during the pipeline generation. If we can figure out the root cause for the queue not being found then that should resolve both issues

This is from your logs
2023-05-22T00:38:35.7089951Z Retrieving default Queue
2023-05-22T00:38:35.7321234Z Found: 0 queues
2023-05-22T00:38:35.7372947Z DefaultQueue - 
2023-05-22T00:38:35.7433618Z Error while retrieving queues.  Queue not found: Azure Pipelines
2023-05-22T00:38:35.7450156Z 'Azure Pipelines' queue Not Found. You will need to set the default queue manually. Please verify the permissions for the user executing this command include access to queues.
2023-05-22T00:38:35.7462661Z Setting up branch policy start

It's possible that your export pipeline is not running as the same user that we expect e.g. the build service user in the project. You may want to try supplying the same permissions mentioned above to the Project Collection Build Service Accounts to see if that makes a difference.

**Comment by LukasSchauffele** [comment] 2023-05-27 03:12
It worked, thank you. It took a while and all the similar sounding service account names don't make it any easier. In the end, I had to give **Project Collection Build Service (org name)** the _Reader_ role to Agent Pools (Project settings - Agent pools  Security)

![CleanShot 2023-05-27 at 12 59 22@2x](https://github.com/microsoft/coe-starter-kit/assets/7881214/db41f6f1-6cd4-48c7-8938-b03db0e48815)

It looks like this account is now also the author for the _Test_ branch. Previous projects have me as the author.

Project created today with Project Collection Build Service as author:
<img width="1144" alt="CleanShot 2023-05-27 at 13 02 14@2x" src="https://github.com/microsoft/coe-starter-kit/assets/7881214/27218c86-7ae3-49d6-8d88-6a9fe77a28fb">

Project created a few months ago with my user account as author:
<img width="1136" alt="CleanShot 2023-05-27 at 13 03 56@2x" src="https://github.com/microsoft/coe-starter-kit/assets/7881214/246c4ca5-1615-4b09-a9bb-64ce77a5b22a">

We've been using and upgrading the ALM Accelerator for a while (~January 2022) so I'm not sure if some older legacy settings could have caused this.

**Comment by mikefactorial** [comment] 2023-05-28 06:13
@LukasSchauffele wondering if you were creating the deployment piplelines via the coe-cli directly previosly? Also, might depend on your setup of the ALM Accelerator pipelines that dictate the user who runs the pipelines. If you have a central repo and project for the export pipeline then they may run as a different user than if you have the pipelines in the same project as the environment in which the deployment pipelines are being created. This is a bit nuanced on the Azure DevOps side as to how the pipeline runner is decided and I'll be honest I don't understand it fully :) Glad it's working though.

**Comment by mikefactorial** [comment] 2023-05-28 06:14
There's also probably organization level policies that dictacte these permissions that again I'm not totally sure how they all work.

**Comment by mikefactorial** [comment] 2023-05-28 06:16
Closing this out for now, but feel free to open a new issue and reference this issue if you find other related issues.

**Closed by mikefactorial** 2023-05-28 06:16 UTC
Labels: bug, alm-accelerator
