### ISSUE TITLE
[CoE Starter Kit - QUESTION] Missing prerequisite for setup wizards

### ISSUE THREAD

**Issue by rarroyo111** [microsoft/coe-starter-kit#7937] opened 2024-03-25 19:59 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Each time I run a set up wizard I get prompted of **Missing prerequisite** and the following flow is triggered. Admin | Sync Template v3 CoE Solution Metadata

![image](https://github.com/microsoft/coe-starter-kit/assets/148905947/5ef94c16-bff6-4dc0-af6e-64d082f2f7c0)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2024

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2665

**Comment by Jenefer-Monroe** [comment] 2024-03-25 20:11
Hello. This is by design. 
Each time you upgrade, these need to run in order to get you the new metadata like flows, apps, and emails into the system.

**Comment by Jenefer-Monroe** [comment] 2024-03-31 15:30
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-03-31 15:30 UTC
Labels: question, coe-starter-kit
