### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE- Core Component not generating "Office 365 Management API" custom connector

### ISSUE THREAD

**Issue by JO20232425** [microsoft/coe-starter-kit#8067] opened 2024-04-15 16:56 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I need an expert advice on how to provide role based access control (RBAC) to the system administrators on the CoE Starter kit dashboard for the Power Platform . How can we define Row Level Security on CoE Dashboard.
Requirement: The system admin of an environment should be able to see only their own environment data in CoE Dashboard. How this can be implemented ? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Dashboard

### What method are you using to get inventory and telemetry?

None

AB#2904

**Comment by Jenefer-Monroe** [comment] 2024-04-15 17:15
Hello, is this a dupe of https://github.com/microsoft/coe-starter-kit/issues/8068? Or is the question just an accidental copy / paste from that?

**Comment by Jenefer-Monroe** [comment] 2024-04-22 23:32
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-04-22 23:32 UTC
Labels: question, coe-starter-kit
