### ISSUE TITLE
[PRODUCT BUG] "Error Loading Control" for Code / PCF components 

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#5815] opened 2023-06-14 07:35 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using the Manager Permissions button via the Power Platform Admin View App we recieve the following error loading the Select User control when trying to Add a new user.

![image](https://github.com/microsoft/coe-starter-kit/assets/48433526/4af894ba-730c-497d-8bc3-c7aa7a7591e6)

### Expected Behavior

Expect the Select user control to load, so we are able to select the user we want to add.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Power Platform Admin View 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open "Power Platform Admin View" App
2. Find a Flow we want to change the permissions for
3. Open the Flow in the details (Overview) view
4. Click "Manage Permissions" button
5. Click "Add"
6. Error appear immediately.

**Comment by manuelap-msft** [comment] 2023-06-14 07:50
Hello,

a product bug related to PCF components used in custom pages has rolled out - we discovered this on Friday (https://github.com/microsoft/powercat-creator-kit/issues/338) and have since then been working with the Power Apps Engineering team to triage and identify the issue. They found the root cause yesterday, and are working on a fix / rollback of the change. Unfortunately until then, there's nothing we can do as it's not a bug on our or the components side!

We'll keep this thread updated as we learn more.

Thank you
Manuela

**Comment by myatix** [comment] 2023-06-14 09:07
@manuelap-msft Thank you for the update and detailed background! 🙂

**Comment by pnoot7** [comment] 2023-06-19 13:20
Hello, checking to see if there have been any updates. I have a ticket open with Support as well, but have not been able to get any information/ETA.

**Comment by Jenefer-Monroe** [comment] 2023-06-19 13:27
Product team has created a hotfix but it sill has to go through some testing so I'm not sure when it will be rolling but we will update here once we know things should be resolved.

**Comment by Jenefer-Monroe** [comment] 2023-06-22 19:10
This was due to a product bug which has since been hotfixed.
In order to get their hotfix into your app, here is what you need to do. For any app where you are seeing these types of issues, you will need to republish the MDA for it. I have validated that this does not create an unmanaged layer so you will be good going forward as well.
1. Go to your CoE Environment > Apps
2. Edit the Model Driven App where you see this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a9d8808-b0e2-4da4-bfac-82601837c5f5)
3. Once in the MDA hit Publish and wait till publish completes
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2de49f4d-786d-4c3c-9920-7ab70c5c78b9)
4. Now reopen the Model Driven App and the issue should be resolved.

**Comment by Jenefer-Monroe** [comment] 2023-07-03 22:39
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-07-03 22:39 UTC
Labels: duplicate, coe-starter-kit, product-gap
