### ISSUE TITLE
CoE Admin Command Center -- CoE Flows Something went wrong

### ISSUE THREAD

**Issue by smohanpa** [microsoft/coe-starter-kit#6351] opened 2023-08-15 14:58 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team,
my CoE admin command center app is not showing the below. it is not running as expected. 
Something has gone wrong. Check technical details for more details.

Error Code: NetworkError
Session Id: 7b6385a0-8b7c-4b02-91e5-e24ffb2108c6
Activity Id: bca72c1a-0d06-4041-9797-a77bcf6d6fd4
Timestamp: Tue Aug 15 2023 10:49:11 GMT-0400 (Eastern Daylight Time)
The request was not sent or there was no response from the server. Check your internet connection.
UciError: The request was not sent or there was no response from the server. Check your internet connection.
![Web capture_15-8-2023_105657_mosaiccoeupdated crm dynamics com](https://github.com/microsoft/coe-starter-kit/assets/131901672/11c639d9-0224-4fac-82f4-410d2a84dfd2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by smohanpa** [comment] 2023-08-16 14:51
yes, today also same issue. I have check it just now.

**Comment by Jenefer-Monroe** [comment] 2023-08-23 10:34
I'm afraid there isnt anything we can do here the issue is in the app launching not in our app.
The issue seems specific to your envt/tenant and indicates some networking issue. You may have to reach to your IT or to Product Support.
closing out as no further action from starter kit team

**Closed by Jenefer-Monroe** 2023-08-23 10:34 UTC
Labels: question, coe-starter-kit
