### ISSUE TITLE
[ALM Accelerator - BUG]: Configuring App sharing and Component ownership is not searchable

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#1711] opened 2022-01-05 10:13 UTC
### Describe the issue

In the Configure Deployment settings pane, when sharing the app and declaring component ownership, the dropdown list is sorted alphabetically and there is no way to search for specific owners.

Furthermore, the queries max out at some point so that part of the AD cannot even be selected.
![image](https://user-images.githubusercontent.com/47601989/148199872-7cc7c517-6eca-4a20-8b15-22b5fef45926.png)

### Expected Behavior

It should be possible to search for specific users/groups to share app and declare ownership.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September release

**Comment by mikefactorial** [comment] 2022-01-05 15:14
@mdpc-nnit thanks for this. This is a duplicate of #1351 the January release addresses this via a filter option.
![image](https://user-images.githubusercontent.com/42348035/148241292-abd07231-cc1d-400e-96ed-9d6d454364dd.png)

**Closed by mikefactorial** 2022-01-05 15:14 UTC
Labels: alm-accelerator

**Comment by mdpc-nnit** [comment] 2022-01-05 16:16
Thanks, @mikefactorial Watching your demo from December, I had a feeling this might be addressed, but didn't manage to find #1351. Great that you fixed it!
