### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Custom Connectors) doesn't get all Custom Connectors

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#976] opened 2021-08-09 15:18 UTC
### Describe the issue

_Admin | Sync Template v3 (Custom Connectors)_ flow finds Custom Connectors and stores information about them in Dataverse. It uses _Get Custom Connectors as Admin_ action from _Power Apps for Admins_ connector to achieve that. This connector however returns only Custom Connectors that are directly imported into an Environment and are **not** part of a Solution. This means any Custom Connectors that are part of Solutions are not caught by this flow and are not visible in the Power BI CoE Report.
For instance, the Office 365 Management API Custom Connector which is part of CoE is not visible in the CoE report.

Custom Connectors from Solutions are present in Connector table of each Environment, so I guess they could be queried from there.

### Expected Behavior

All Custom Connectors are listed in _PowerApps Connector_ table and in Power BI CoE report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Sync Template v3 (Custom Connectors)

### Steps To Reproduce

1. Install Core Components solution
2. Import any solution with a Custom Connector
3. Run sync flows and check PowerApps Connector table and Power BI report

**Comment by JeneferM-MSFT** [comment] 2021-08-09 16:01
thank you, yes this limitation is known (though we did not document in limitations)
I will hold with your suggestion to investigate if that is possible, and if not we'll at least add it to our limitations page.

**Comment by JeneferM-MSFT** [comment] 2021-08-18 15:59
As far as I can tell, we can only get the following: 
1) custom connectors not in a solution (via **Get Custom Connectors as Admin**)
2) custom connectors to which user has access (via **Get Connectors** which returns the same custom connectors as you can get from the connectors table)

So I am going ahead and adding this second vector since I am there and have done the investigation. This will get a few more in your inventory assuming there are custom connectors in solutions to which you have access, but it will still not get all the custom connectors in the tenant. Please let me know if you have discovered a way to get all of them. 

The workaround with this fix will be to see if powershell correctly returns then and then have the identity that runs the inventory added to all custom connectors.

**Comment by xmihux** [comment] 2021-08-18 16:05
PowerShell unfortunately returns the same connectors as Get Custom
Connectors as Admin.

I believe the way to get custom connectors that are part of Solutions (not
returned by Get Custom Connectors as Admin) is to query 'Connectors' table
in Dataverse. This would need to be done for each environment. If this
process is implemented in CoE, then we would gather all custom connectors.

śr., 18 sie 2021, 17:59 użytkownik Jenefer Monroe ***@***.***>
napisał:

**Comment by JeneferM-MSFT** [comment] 2021-08-18 16:11
When I query that table, I get the same custom connectors as when I use Get Connectors. I dont get ones to which I dont have access. And I am a global admin / PPAdmin. Have you validated that you see custom connectors there to which you dont have access?

**Comment by xmihux** [comment] 2021-08-18 22:20
I tested with a Global & Power Platform administrator account and I could see custom connectors that are in solutions. Both in the UI and by querying the table with Dataverse connector. I created a couple of connectors with another account and I did not have to specifically share those custom connectors with my admin account. My understanding has been that as a Power Platform administrator I have access to all records in connectors table (even if records are not mine). The same goes for Solutions. But of course please correct me if I'm missing something here.

**Comment by JeneferM-MSFT** [comment] 2021-08-19 00:20
Can you try with this version of core to see if it resolves for you? I believe the call to Get Connections mimics looking into the connectors table in each environment (as is a more robust connector)
[CenterofExcellenceCoreComponents_2_77_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7010873/CenterofExcellenceCoreComponents_2_77_managed.zip)

**Comment by JeneferM-MSFT** [comment] 2021-08-19 16:37
OK I did a little more testing and confirmed that we cannot get access to custom connectors in solutions to which the identity running the flow does not have access. 

Avenues I have tried:
*Power Apps for Admins >> Get Custom Connectors as Admin*
-	Returns only custom connectors outside of solutions
-	Custom connectors in solutions are not returned at all
-	Does return them even if the identity that ran the flow doesn’t have access. 

*Power Apps for Admins >> Get Custom Connectors as Admin*
-	Returns custom connectors regardless of if they are in a solution or not
-	Also returns all the non-custom connectors in the environment, but filterable
-	But will only return the connectors to which the user has access

*Connectors table in each environment*
-	Returns custom connectors regardless of if they are in a solution or not
-	Its possible to have custom connectors in environments that don’t have Dataverse so this table is confusing to begin with and I don’t think we could rely on it, but including for completeness.
-	Returns only custom connectors to which the user has access


I have reached out to the product team to see if they have other ideas but as far as I can tell we are blocked. 
I have gone ahead and added the work to get custom connectors to which you have access included in inventory. So it will be a little more full, but still not complete.

**Comment by xmihux** [comment] 2021-08-20 08:34
Thanks a lot for pushing this forward. That's great.
However, I can't agree with the below:
> 
> _Connectors table in each environment_
> 
> * Returns custom connectors regardless of if they are in a solution or not
> * Its possible to have custom connectors in environments that don’t have Dataverse so this table is confusing to begin with and I don’t think we could rely on it, but including for completeness.
> * Returns only custom connectors to which the user has access
> 

My understanding is that:
- Connector table returns **only** custom connectors that come from Solutions (tested)
- It's not possible to have Solutions without a Dataverse database, so in environments without a database, we're fine with using only "Get Custom Connectors as Admin"
- Power Platform administrator can see all items in Connectors table of each environment - so the administrator can see all connecotrs coming from Solutions (please correct me if I'm wrong here)

If my statements are correct, you could just have 2 actions in the custom connectors flow and combine their results:
- Get Custom Connectors As Admin [for non-solution custom connectors]
- Get Connectors table [for custom connectors from solutions]

**Comment by JeneferM-MSFT** [comment] 2021-08-20 14:53
Good point on the solutions and dataverse. I hadnt thought of that. 
However, in my testing. I am not able to see custom connectors to which I do not have access via the connectors table or the Get Connections. So I do believe you are incorrect there. 
The Get Connections connector returns the same custom connectors as getting the information from the connector table, and avoids using the legacy Dataverse connector so its more robust. As a result, I have done the equivalent of your suggestion in the solution provided.

**Comment by xmihux** [comment] 2021-08-22 22:50
I just tested the 2.77 version you provided and it's working fine with the Get Connectors action. Thank you. A tiny detail missing in the new part of the Flow is the value in the 'Tier' column of the 'Update Custom Connector Record' action (the value is 'Custom' in the original Update Row action).

**Comment by JeneferM-MSFT** [comment] 2021-08-23 15:57
good catch! Thank you! I have fixed that for when we release this fix in September.

**Comment by mikefactorial** [comment] 2021-09-08 17:18
@xmihux This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by mikefactorial** 2021-09-08 17:18 UTC
Labels: coe-starter-kit, vnext, core-components
