### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Apps fails with Entity 'admin_app' With Id = [guid] Does Not Exist

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#6850] opened 2023-10-12 07:38 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since last week I am seeing this flow fail every day, multiple times. It always fails on the 'Upsert App record' action. A quick look into some of the flow runs tells that there are two recurring apps in all the environments that it is failing on, called 'Dataverse Actions Page' and 'Overview'.

![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/d9882493-dd63-4f0c-b56a-a3718d6b7e0b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

Might this be related to solutions recently pushed by the SYSTEM to a lot of environments, like 'Dataverse Accelerator App' and 'Power Pages Management'.. We saw these recently in a lot of envs, but they seem to be gone again now.

**Comment by Jenefer-Monroe** [comment] 2023-10-12 11:34
Yes I do believe that is the cause, we have this tracked in https://github.com/microsoft/coe-starter-kit/issues/6778 and it happened to be resolved by other work we did already in more current builds.

**Comment by Jenefer-Monroe** [comment] 2023-10-13 12:33
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-10-13 12:33 UTC
Labels: bug, duplicate, coe-starter-kit
