### ISSUE TITLE
[CoE Starter Kit - BUG] CoE BYODL Makers environment issues

### ISSUE THREAD

**Issue by accsimonwalsh** [microsoft/coe-starter-kit#6955] opened 2023-10-27 13:26 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When connecting to the Makers table for the CoE BYODL Makers dataflow the issue below occurs at the second step in the query, Merge:

<img width="619" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/d68ffc7d-8d6f-4c5c-a5ea-20a96a6c8396">

When looking at the App Makers table it seems like the Default environment apps are creating this issue. Before the same JSON issue occurs step there is one table that has an Error:

<img width="618" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/eddf53e6-ea0d-4b7e-912c-b5604179e356">

<img width="601" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/3414866b-3ca2-4ad1-847f-7ce5bc332ea0">

In the following step the issue occurs:

<img width="513" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/13022f77-ccf9-4b90-86d1-5db0e7661b8d">

When I used a filter to remove the error row, I got the same issue with only the remaining row. Removing both rows with a filter solved the issues for all tables in the dataflow:

<img width="461" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/77343d44-ca88-40e3-87ec-2d4ab175fa9f">

And made it possible to publish the dataflow:

<img width="590" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/cf27bb24-206e-4206-9604-b85843050773">

It doesn't seem like the best solution to remove any of the environments or apps to make the dataflows work. Any input on how this could be solved in a better way would be appreciated.

### Expected Behavior

The dataflow can be set up without any manual query changes. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE BYODL Makers 

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Edit dataflow "CoE BYODL Makers"
2. Connect to table "Makers"
3. The mentioned issue appears according to below:

<img width="619" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/3b4fb698-5e1c-4b18-b2c5-a63590df150e">

**Comment by Jenefer-Monroe** [comment] 2023-10-27 16:34
Hello,

this is a duplicate of https://github.com/microsoft/coe-starter-kit/issues/6688 and https://github.com/microsoft/coe-starter-kit/issues/6577. The issue is caused by new properties being made available in Data Export, some of which are made available through nested JSON in the files we consume from the storage account and the Dataflow transformations weren't robust enough to handle nested JSON. 

The fix went live with the Oct release so you will not see this anymore on upgrade. 
I'll go ahead and close this out as a duplicate but please do return if you have other questions in the future.

**Closed** 2023-10-27 16:34 UTC
Labels: duplicate, question, coe-starter-kit
