### ISSUE TITLE
[CoE Starter Kit - BUG] COE Audit Log not capturing model driven App launch

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3435] opened 2022-08-11 13:15 UTC
### Describe the issue

We have COE audit log version 2.10  and noticed that Audit log shows only  Canvas App launch records . It not showing any audit records for model driven app .

### Expected Behavior

Audit logs shows both Model driven and Canvas app launch records 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Admin Sync Audit Logs

### Steps To Reproduce

Go to Power platform Admin  view app -> Go to - Audit Logs .

**Comment by manuelap-msft** [comment] 2022-08-11 13:21
Duplicate of #3431

**Closed by manuelap-msft** 2022-08-11 13:21 UTC
Labels: bug, coe-starter-kit
