### ISSUE TITLE
Hey @mikefactorial getting the same error Error running pipeline: {"$id":"1","innerException":null,"message":

### ISSUE THREAD

**Issue by Tamy05** [microsoft/coe-starter-kit#7068] opened 2023-11-10 09:25 UTC
Hey @mikefactorial getting the same error Error running pipeline: {"$id":"1","innerException":null,"message":"An error occurred while loading the YAML build pipeline. File /Pipelines/export-solution-to-git.yml not found in repository "url"-templates branch refs/heads/main version d38309dd3b25dc5b52b32af85cdb4e858849b5ff.","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException while i click on Comit in the canvas app can you please help me with this ?

_Originally posted by @Tamy05 in https://github.com/microsoft/coe-starter-kit/issues/3314#issuecomment-1805371788_
            

AB#815

**Comment by Tamy05** [comment] 2023-11-10 09:25
"An error occurred while loading the YAML build pipeline. File /Pipelines/export-solution-to-git.yml not found in repository "url"-templates branch refs/heads/main version d38309dd3b25dc5b52b32af85cdb4e858849b5ff.","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException while i click on Comit in the canvas app can you please help me with this ?

**Comment by mikefactorial** [comment] 2023-11-13 13:44
@Tamy05 it appears that the export-solution-to-git pipeline in Azure DevOps is not configured correctly or the ALM Accelerator Templates were not successfully imported into Azure DevOps. You'll need to figure out what the issue is. Try going into Azure DevOps and selecting Edit. You should see something like this.

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/919de71b-45b8-4d09-8f9b-0cc5bdf0be4e)


The highlighted part shows where the export solution yaml file should be. You can verify if the templates exist by looking at the repo specified in the definition. 

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/33c1c10e-55c9-461f-93d1-f76c44e5bd3a)

**Comment by RajeevPentyala** [comment] 2023-11-14 10:20
@Tamy05 Closing this item as I've assisted you in resolving the issue during our call.

**Closed by RajeevPentyala** 2023-11-14 10:20 UTC
Labels: bug, alm-accelerator
