### ISSUE TITLE
[CoE Starter Kit - BUG] Setup WIzard - error when sharing apps

### ISSUE THREAD

**Issue by edarcy87** [microsoft/coe-starter-kit#4698] opened 2023-01-31 22:32 UTC
### Describe the issue

When I click to share an app, the url is not formatted correctly and is missing the make.powerapp.com prefix

![image](https://user-images.githubusercontent.com/124092704/215898403-d51cf760-8a4d-4ddd-80d1-0b5f358c1f99.png)

![image](https://user-images.githubusercontent.com/124092704/215898337-018c3218-aaac-4f51-9628-e4bcf00f9c7b.png)

### Expected Behavior

The URL should direct to the share screen:

![image](https://user-images.githubusercontent.com/124092704/215898573-5b9f6a9c-682a-4313-9620-b0d97b78ec7a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

### Steps To Reproduce

Open Setup wizard
Continue until share app screen:
![image](https://user-images.githubusercontent.com/124092704/215898680-6fdc745f-d764-4ee9-bcb0-a4ca01cfbd7b.png)
Click on the button to share
Error screen loads

**Comment by manuelap-msft** [comment] 2023-02-01 11:31
Hello,

this looks the setup wizard failed to set the environment variable that holds the prefix correctly, this would have been done in a previous step (configure mandatory settings).

Can you please 

1. Go to [Power Automate](https://make.powerautomate.com/).
2. On the left pane, select Solutions.
3. Select the Default Solution, and change the filter to show Environment Variables.
4. Check these environment variables https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values and make sure they have a Current Value configured. If they don't, look at the description in the documentation to set the value. 

We'll test this on our side as well to check why the environment variable wasn't updated from the wizard.

**Comment by manuelap-msft** [comment] 2023-02-01 13:41
Oh it looks like this is a duplicate of this issue
https://github.com/microsoft/coe-starter-kit/issues/4416

I think if you close the wizard and open it again, it will work.

**Comment by edarcy87** [comment] 2023-02-01 13:46
Thanks so much! It set the URL to just make.powerapps.com without the env ID.

**Comment by Jenefer-Monroe** [comment] 2023-02-08 19:08
Closing out as dupe for of #4416 which is now released with the Feb version

**Closed by Jenefer-Monroe** 2023-02-08 19:08 UTC
Labels: bug, coe-starter-kit
