### ISSUE TITLE
[ALM Accelerator - BUG]: Error when setting up a new Project using ALM Admin App

### ISSUE THREAD

**Issue by firozozman** [microsoft/coe-starter-kit#5531] opened 2023-05-15 15:41 UTC
### Describe the issue

I am trying to set up a new project using ALM Accelerator for Power Platform Admin app. I get the following error when I chose to download the pipeline templates. 

_CustomeAzureDevOps: CreatePipeline failed "_scrubbedSensitiveData"_

### Expected Behavior

The process succesfully completes and sets up a new project for ALM Accelerator

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

3.23033.15

### Steps To Reproduce

1. Open ALM Accelerator for the Power Platform Admin app
2. Click on Projects on the left navigation menu
3. Select the Azure DevOps Organization
4. Under Menu, select Project > New > Project Wizard
5. Select an existing project, Next
6. Check "Install into new template repository" Version: CenterofExcellenceALMAccelerator-April2023
7. Click Next, and an error appears. _CustomeAzureDevOps: CreatePipeline failed "_scrubbedSensitiveData"_

### Anything else?

![MicrosoftTeams-image (2)](https://github.com/microsoft/coe-starter-kit/assets/15437706/16492a07-7000-4a9c-99e2-d1fd960176ae)

**Comment by mikefactorial** [comment] 2023-05-15 17:35
@firozozman hard to tell specifically what the issue is without the details of the error, but it's most likely a permissions issue. May want to verify that your user has permissions to create pipelines in the project you're targeting.

**Comment by firozozman** [comment] 2023-05-17 16:55
You are right Project Creation did not create the Pipelines. It failed.

Where can I get more detailed failure information to share with you? 

I only see this: 
![image](https://github.com/microsoft/coe-starter-kit/assets/15437706/f068875f-3fc3-4da0-8ebf-765aa4b274d6)

**Comment by astriemer** [comment] 2023-06-05 19:41
We are having this same issue with version 1.0.20230405.2

**Comment by mikefactorial** [comment] 2023-06-08 16:20
This is difficult to solve without the actual error message since it's not showing. Can you try running a monitor session and reproduce the error to see if the actual error message gets logged in the monitor?
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/07caf93d-7ea5-48eb-827b-e23e203dd17b)

**Comment by mikefactorial** [comment] 2023-06-09 14:47
Unfortunately, it's difficult to diagnose this issue since the platform is masking the actual error. 

I have a hunch. Can you take a look at the project that's being created in Azure DevOps and let me know if you see a main branch under the ALM Accelerator Templates repo? Should see something like the following. 

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/7a15ca0e-2f48-4524-aa77-ed7d3e00469f)

**Comment by mikefactorial** [comment] 2023-07-07 21:45
Closing this out as there's not been any response in a month.

**Closed by mikefactorial** 2023-07-07 21:45 UTC
Labels: bug, alm-accelerator
