### ISSUE TITLE
[CoE Starter Kit - Product BUG] GCC Nurture install failing

### ISSUE THREAD

**Issue by osafomensahny** [microsoft/coe-starter-kit#888] opened 2021-07-21 22:26 UTC
### Describe the issue

Issue encountered installing Nurture components. in GCC Environment .
See Error Code below:

Exception while acquiring token: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() +0x4c    at Microsoft.Crm.Setup.Server.SolutionsUtility.TPSService.TrustedPublisherServiceProvider.SendRequestToTPS(Uri requestUri, HttpMethod httpMethod, JObject payload, String correlationId) +0xf8    at Microsoft.Crm.Setup.Server.SolutionsUtility.TPSService.TrustedPublisherServiceProvider.<>c__DisplayClass20_1.<GetAssemblyReference>b__1() +0x0    at Microsoft.Crm.Setup.Server.SolutionsUtility.ExecutionUtility.ExecuteWithRetry[TResult](String actionName, Guid orgId, Func`1 action, Int32 retryIntervalInSeconds) +0x85    at Microsoft.Crm.Setup.Server.SolutionsUtility.TPSService.TrustedPublisherServiceProvider.<>c__DisplayClass20_0.<GetAssemblyReference>b__0() +0x96    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 a... (Fault Detail is equal to Exception details:  ErrorCode: 0x80040216 Message: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() +0x4c    at Microsoft.Crm.Setup.Server.SolutionsUtility.TPSService.TrustedPublisherServiceProvider.SendRequestToTPS(Uri requestUri, HttpMethod httpMethod, JObject payload, String correlationId) +0xf8    at Microsoft.Crm.Setup.Server.SolutionsUtility.TPSService.TrustedPublisherServiceProvider.<>c__DisplayClass20_1.<GetAssemblyReference>b__1() +0x0    at Microsoft.Crm.Setup.Server.SolutionsUtility.ExecutionUtility.ExecuteWithRetry[TResult](String actionName, Guid orgId, Func`1 action, Int32 retryIntervalInSeconds) +0x85    at Microsoft.Crm.Setup.Server.SolutionsUtility.TPSService.TrustedPublisherServiceProvider.<>c__DisplayClass20_0.<GetAssemblyReference>b__0() +0x96    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger,

### Expected Behavior

Complete install of Nurture Component

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

CenterofExcellenceNurtureComponents_1.60.20210708.1_managed.zip

### What app or flow are you having the issue with?

Installation of Nurture Components 

### Steps To Reproduce

![COE-NurtureComponent Error ](https://user-images.githubusercontent.com/83729548/126567780-7e7dfb50-5a13-44c2-83ae-990d3223db84.jpg)

### Anything else?

[Center of Excellence - Nurture Components_import.xlsx](https://github.com/microsoft/coe-starter-kit/files/6859105/Center.of.Excellence.-.Nurture.Components_import.xlsx)

**Comment by JeneferM-MSFT** [comment] 2021-07-22 12:40
Please attempt an update rather than upgrade. 
Duplicate of #866

**Comment by osafomensahny** [comment] 2021-07-22 12:46
NO able to install the solution.. How am I suppose to upgrade a solution that is not installed?

**Comment by JeneferM-MSFT** [comment] 2021-07-22 12:52
Apologies, most people are referring to upgrade when they say install. As in install on top of old install.

**Comment by osafomensahny** [comment] 2021-07-22 14:11
This is a first  install .. Had no issues installing the Core and Governance Components.   Fails on the Install of the Nurture components

**Comment by JeneferM-MSFT** [comment] 2021-07-22 16:21
GCC support for Dataflows has a bug. Product team investigating

**Comment by osafomensahny** [comment] 2021-07-22 16:23
Thanks for the update… What is the ETA to resolution?

Regards,
Nana Osafo-Mensah, MBA, ITIL, CSM
Collaborative Technologies Program Manager
DHHS|NIH|NIAID|OD|OSMO|OCICB|BPIMB
5601 Fishers Lane #5A49
Rockville, MD 20852
Desk: 240-669-2731
Mobile: 240-479-1771

Visit the NIAID Community of CollaborativeTechnologies<https://nih.sharepoint.com/sites/NIAID-Portal> site for resources, guides and tips on collaboration tools and features.

“ If it's worth it, It's worth the work!” Nana Osafo-Mensah © 2019

The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by osafomensahny** [comment] 2021-08-04 13:49
Any Updates on this issue? is there an ETA/ETC?

**Comment by JeneferM-MSFT** [comment] 2021-08-04 13:54
The product fix for this is going out soon, estimate to be live end of August. 
I am going to try and get you a PR version of nurture with the August release that you can use that doesnt include this.

**Comment by osafomensahny** [comment] 2021-08-04 13:58
Awesome! This is very helpful! Much appreciated!

Regards,
Nana Osafo-Mensah, MBA, ITIL, CSM
Collaborative Technologies Program Manager
DHHS|NIH|NIAID|OD|OSMO|OCICB|BPIMB
5601 Fishers Lane #5A49
Rockville, MD 20852
Desk: 240-669-2731
Mobile: 240-479-1771

Visit the NIAID Community of CollaborativeTechnologies<https://nih.sharepoint.com/sites/NIAID-Portal> site for resources, guides and tips on collaboration tools and features.

“ If it's worth it, It's worth the work!” Nana Osafo-Mensah © 2019

The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by osafomensahny** [comment] 2021-08-23 15:10
What is the status of the  fix?

**Comment by JeneferM-MSFT** [comment] 2021-08-23 16:09
It was supposed to be live today, but there was a delay. It should be live soon and I will update here.

**Comment by osafomensahny** [comment] 2021-08-24 17:07
I see a new version of the starter kit was uploaded yesterday... Is it safe to assume that we can proceed with the solution component  upgrades?

**Comment by JeneferM-MSFT** [comment] 2021-08-24 23:59
The fix here is from the product team, and not us. So an upgrade will not help. As far as I know we did not ship a new release either so I will investigate that.

**Comment by JeneferM-MSFT** [comment] 2021-08-25 15:28
The product fix has made it into the 8/16 ship train, and should be live to you end of week. 
Please give this a try on Monday or Tuesday and let me know.

**Comment by Jenefer-Monroe** [comment] 2021-09-01 23:53
Hi folks. Can anyone please let me know if this is working for you now?

**Comment by osafomensahny** [comment] 2021-09-02 12:19
We are planning to upgrade/update our instance  on Tuesday 9/7/21// We will revert with our updates

Regards,
Nana Osafo-Mensah, MBA, ITIL, CSM
Collaborative Technologies Program Manager
DHHS|NIH|NIAID|OD|OSMO|OCICB|BPIMB
5601 Fishers Lane #5A49
Rockville, MD 20852
Desk: 240-669-2731
Mobile: 240-479-1771

Visit the NIAID Community of CollaborativeTechnologies<https://nih.sharepoint.com/sites/NIAID-Portal> site for resources, guides and tips on collaboration tools and features.

“ If it's worth it, It's worth the work!” Nana Osafo-Mensah © 2019

The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by Jenefer-Monroe** [comment] 2021-09-02 13:11
Please hold off. I have an internal team doing some testing here and I will let you know when they give the green light. 
Just dont want you all doing the same work they are :)

**Comment by osafomensahny** [comment] 2021-09-02 13:16
Thanks, Jenefer Monroe… Look forward to hearing from you.

Regards,
Nana Osafo-Mensah, MBA, ITIL, CSM
Collaborative Technologies Program Manager
DHHS|NIH|NIAID|OD|OSMO|OCICB|BPIMB
5601 Fishers Lane #5A49
Rockville, MD 20852
Desk: 240-669-2731
Mobile: 240-479-1771

Visit the NIAID Community of CollaborativeTechnologies<https://nih.sharepoint.com/sites/NIAID-Portal> site for resources, guides and tips on collaboration tools and features.

“ If it's worth it, It's worth the work!” Nana Osafo-Mensah © 2019

The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by osafomensahny** [comment] 2021-09-08 13:30
Hi @Jenefer, any updates?

**Comment by Jenefer-Monroe** [comment] 2021-09-08 17:37
our internal testing hit an issue and product team is investigating.

**Comment by osafomensahny** [comment] 2021-09-08 19:36
Thanks for the update… Look forward to hearing from you once the issue has been resolved!


Regards,
Nana Osafo-Mensah, MBA, ITIL, CSM
Collaborative Technologies Program Manager
DHHS|NIH|NIAID|OD|OSMO|OCICB|BPIMB
5601 Fishers Lane #5A49
Rockville, MD 20852
Desk: 240-669-2731
Mobile: 240-479-1771

Visit the NIAID Community of CollaborativeTechnologies<https://nih.sharepoint.com/sites/NIAID-Portal> site for resources, guides and tips on collaboration tools and features.

“ If it's worth it, It's worth the work!” Nana Osafo-Mensah © 2019

The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by Jenefer-Monroe** [comment] 2021-09-09 19:42
### Workaround solution
Hello we have created a workaround solution for you here which is Sept version of Nurture with the data flow removed. 
[CenterofExcellenceNurtureComponents_3_0_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7138428/CenterofExcellenceNurtureComponents_3_0_managed.zip)

### Maker Assessment App

The data flow was used to populate started data for the [Maker Assessment App](https://docs.microsoft.com/power-platform/guidance/coe/nurture-components#maker-assessment). 
If you would like to use that app, without having this data flow, you will need to load the sample data in another way as a result. 

Below is one technique, if it does not work for you then **_you will need to either manually insert the data or wait to use this particular app until the data flow feature works for you before you can use the app._** 

### One technique to Upload Data for Maker Assessment App
Put these 3 files locally on your machine
[assessmentcategories.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138802/assessmentcategories.xlsx)
[assessments.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138803/assessments.xlsx)
[answeroptions.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138804/answeroptions.xlsx)


**Assessment Category**
Browse to the Assessment Category table
![image](https://user-images.githubusercontent.com/89584709/132738548-a260c56a-96ea-46ce-832d-2514e9375a97.png)
Once in the table select Get data > Get data from Excel
![image](https://user-images.githubusercontent.com/89584709/132738779-f369616f-3aa1-4ebc-a013-808417bb25a7.png)
Hit **_upload_**, select assessmentcategories.xlsx, wait till mapping status says **_Mapping was successful_**
![image](https://user-images.githubusercontent.com/89584709/132739201-d5b6342b-763d-4631-84e0-185d00d90cf2.png)
Here is what the mapping should look like if you hit Map Columns
![image](https://user-images.githubusercontent.com/89584709/132750873-5a860f94-3dd8-4fde-bc7a-d4dd0d93aa95.png)
Hit import. You should see 5 items inserted
![image](https://user-images.githubusercontent.com/89584709/132751060-fefc480b-9d93-4395-8fa0-bd3405176fd5.png)

**Assessment Questions**
Do the same steps as above but point to assessments.xlsx
Here is what the mapping will look like, and you should see 22 items inserted
![image](https://user-images.githubusercontent.com/89584709/132751414-9e3fcbc9-5ed4-44c8-8b95-b5619474a2ab.png)

**Answer Options**
Do the same steps as above but point to answeroptions.xlsx
Here is what the mapping will look like, and you should see 65 items inserted
![image](https://user-images.githubusercontent.com/89584709/132752093-4348382c-f24e-4856-a90a-33e8fce84fab.png)

**Comment by Jenefer-Monroe** [comment] 2021-10-05 15:12
Here is a version for Oct without Dataflow
[CenterofExcellenceNurtureComponents_2.3_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7286983/CenterofExcellenceNurtureComponents_2.3_managed.zip)

**Comment by Jenefer-Monroe** [comment] 2021-11-03 19:47
Here is a version of Nov without Dataflow. Product is still iterating on a fix
[CenterofExcellenceNurtureComponents_2_5_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7470296/CenterofExcellenceNurtureComponents_2_5_1_managed.zip)
.

**Comment by osafomensahny** [comment] 2021-11-03 21:00
Thanks for the update.  We were not able to install the last patch….

Regards,
Nana Osafo-Mensah, MBA, ITIL, CSM
Collaborative Technologies Program Manager
DHHS|NIH|NIAID|OD|OSMO|OCICB|BPIMB
5601 Fishers Lane #5A49
Rockville, MD 20852
Desk: 240-669-2731
Mobile: 240-479-1771

Visit the NIAID Community of CollaborativeTechnologies<https://nih.sharepoint.com/sites/NIAID-Portal> site for resources, guides and tips on collaboration tools and features.

“ If it's worth it, It's worth the work!” Nana Osafo-Mensah © 2019

The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by Jenefer-Monroe** [comment] 2021-12-03 16:18
### Workaround solution
Hello we have created a workaround solution for you here which is Sept version of Nurture with the data flow removed. 
[CenterofExcellenceNurtureComponents_3_0_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7138428/CenterofExcellenceNurtureComponents_3_0_managed.zip)

### Maker Assessment App

The data flow was used to populate started data for the [Maker Assessment App](https://docs.microsoft.com/power-platform/guidance/coe/nurture-components#maker-assessment). 
If you would like to use that app, without having this data flow, you will need to load the sample data in another way as a result. 

Below is one technique, if it does not work for you then **_you will need to either manually insert the data or wait to use this particular app until the data flow feature works for you before you can use the app._** 

### One technique to Upload Data for Maker Assessment App
Put these 3 files locally on your machine
[assessmentcategories.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138802/assessmentcategories.xlsx)
[assessments.xlsx](https://github.com/microsoft/coe-starter-kit/files/7650774/assessments.xlsx)
[answeroptions.xlsx](https://github.com/microsoft/coe-starter-kit/files/7650800/answeroptions.xlsx)

**Assessment
 Category**
Browse to the Assessment Category table
![image](https://user-images.githubusercontent.com/89584709/132738548-a260c56a-96ea-46ce-832d-2514e9375a97.png)
Once in the table select Get data > Get data from Excel
![image](https://user-images.githubusercontent.com/89584709/132738779-f369616f-3aa1-4ebc-a013-808417bb25a7.png)
Hit **_upload_**, select assessmentcategories.xlsx, wait till mapping status says **_Mapping was successful_**
![image](https://user-images.githubusercontent.com/89584709/132739201-d5b6342b-763d-4631-84e0-185d00d90cf2.png)
Here is what the mapping should look like if you hit Map Columns
![image](https://user-images.githubusercontent.com/89584709/132750873-5a860f94-3dd8-4fde-bc7a-d4dd0d93aa95.png)
Hit import. You should see 5 items inserted
![image](https://user-images.githubusercontent.com/89584709/132751060-fefc480b-9d93-4395-8fa0-bd3405176fd5.png)

**Assessment Questions**
Do the same steps as above but point to assessments.xlsx
Here is what the mapping will look like, you will need to map **_Category Name_** manually. 
You should see 22 items inserted
![image](https://user-images.githubusercontent.com/89584709/144634668-b32819a0-267e-4154-a0dc-9b1836e3194a.png)

**Answer Options**
Do the same steps as above but point to answeroptions.xlsx
Here is what the mapping will look like, you will need to map **_Question (Question Name)_** manually. 
Auto-mapping gets this one wrong in a few places so please check here carefully.
You should see 65 items inserted
![image](https://user-images.githubusercontent.com/89584709/144636110-865dce8b-a045-4f81-98fe-377cafdfcbb8.png)

**Comment by Jenefer-Monroe** [comment] 2021-12-03 18:07
and here is a December 2021 version of Nurture without the dataflow
[CenterofExcellenceNurtureComponents_2_6_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7651536/CenterofExcellenceNurtureComponents_2_6_1_managed.zip)

**Closed** 2022-05-06 13:13 UTC
Labels: product-gap
