### ISSUE TITLE
[CoE Starter Kit - BUG]  Admin | Sync Template v3 (Apps) fails because of missing connector information

### ISSUE THREAD

**Issue by MSPowerPlatformDev** [microsoft/coe-starter-kit#1752] opened 2022-01-14 10:30 UTC
### Describe the issue

The filter query does not have a parameter being fetched. This most possibly is happening because Connectors table is not storing information for all the connectors using the Admin | Sync Template v3 (Connectors) flow.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/97730519/149500436-34b447a3-0042-40a3-a756-4d860d01f842.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment] 2022-01-14 14:16
You are correct, this is due to #1751. Duplicating to that bug. 
Duplicate of #1751

**Closed by Jenefer-Monroe** 2022-01-14 14:16 UTC
Labels: coe-starter-kit
