### ISSUE TITLE
[CoE Starter Kit - BUG] Entity 'admin_pva' With Id = [] Does Not Exist

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6274] opened 2023-08-09 09:23 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Running June 2023 Core. 
Seen daily failues of Admin | Sync Template v3 (PVA)

Entity 'admin_pva' With Id =   Does Not Exist

Fails at  Get PVA
![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/43f61205-989c-46c9-a1e5-4e5bb3f5e5db)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Go to sync flow errors
Appears as error. 
Go to flow
Appears at Dataverse step.

**Comment by Jenefer-Monroe** [comment] 2023-08-09 15:22
That is a caught faulure as you can see here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/96c49445-a010-4c0e-a5d6-00b9e941da78)

We use these calls to see if the object is new to the inventory, and if it is, this call to “get it” will fail. This failure is caught and the “isnew” variable is set to true. 

In order to debug you need to find the terminating failure in the flow. Here for example the call to “forced failure” failed, and was not caught, so the flow terminated here. That is the spot you need to find in your failure in order to debug. 
![image](https://user-images.githubusercontent.com/89584709/225681214-a5549790-32e9-482e-b427-0c346aa50684.png)

**Comment by uzma-fis** [comment] 2023-08-09 15:31
Excellent! The error traces back to Create Bot - this particular parameter is set up in the template itself, rather than me deep diving you do know what field this relates too? 


OpenApiOperationParameterValidationFailed. The 'inputs.parameters' of workflow operation 'Create_Bot' of type 'OpenApiConnection' is not valid. Error details: The API operation 'CreateRecord' requires the property 'item/admin_bottemplate' to be a string of maximum length '20' but is of length '23'.

**Comment by uzma-fis** [comment] 2023-08-09 15:33
Or indeed do you guys need to change this field, the text itself shows "converted-default-2.0.0" so I don't see how we are meant to amend this ourselves!

**Comment by Jenefer-Monroe** [comment] 2023-08-10 02:20
oh good news, this one is fixed then in July release with https://github.com/microsoft/coe-starter-kit/issues/5808

**Comment by Jenefer-Monroe** [comment] 2023-08-10 02:20
ill go ahead and close as a dupe of that but thank you for posting and do feel free to reach out with other issues.

**Closed by Jenefer-Monroe** 2023-08-10 02:20 UTC
Labels: question, coe-starter-kit

**Comment by uzma-fis** [comment] 2023-08-10 09:24
Ha great thanks for the update
