### ISSUE TITLE
[CoE Starter Kit - BUG] Error Updating Core Components Solution to Sept. 2022

### ISSUE THREAD

**Issue by ryanwalker726** [microsoft/coe-starter-kit#3890] opened 2022-10-07 14:12 UTC
### Describe the issue

Attempting to update from July 2022 (3.40) to Sept. 2022 (3.45) and receiving an error code with no description or explanation (80072031).  I had already checked for unmanaged layers and there weren't any.  I followed the update instructions here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup and selected "Upgrade".  After 15 minutes, the import just failed.

### Expected Behavior

Successful update to Sept. 2022 (3.45) for toolkit core components

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

N/A Failed upgrade/import of the entire solution

### Steps To Reproduce

1. In our Power Platform CoE environment
2. Upgrading the Core Components solution with the same service account that created the environment and the initial install of the CoE
3. No unmanaged layers or other customizations
4. Imported solution
5. Waited 15 minutes and got error

### Anything else?

<img width="163" alt="SolutionErrorSidePanel" src="https://user-images.githubusercontent.com/64166769/194574025-84a9eec6-8d25-4733-be6e-56ffdcfb3ecc.PNG">
<img width="487" alt="ErrorCode-NotFound" src="https://user-images.githubusercontent.com/64166769/194574030-f7ac7216-9f38-4d32-a4e4-8f9f0b06b300.PNG">
<img width="957" alt="CommandCenterError" src="https://user-images.githubusercontent.com/64166769/194574032-7c6ac046-d80c-451e-8d81-586ce10375dc.png">

**Comment by Jenefer-Monroe** [comment] 2022-10-07 14:49
A few people have hit this and we do not know the cause, but a classic overwrite fixed for them

### How to do an overwrite upgrade in the classic UX:
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by Jenefer-Monroe** [comment] 2022-10-17 12:31
closing out as no further action for coe starter kit team

**Closed by Jenefer-Monroe** 2022-10-17 12:31 UTC
Labels: bug, coe-starter-kit
