### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) failing due to time zone

### ISSUE THREAD

**Issue by BPeni** [microsoft/coe-starter-kit#4017] opened 2022-10-21 08:07 UTC
### Describe the issue

Sync Template v3 (Flow Action Details) failing due to time zone of the Admin account running the flow. Flows within the tenant are in different countries, thus the flow fails only for some cases, with the following message in the Add Action step: **System date cannot be set to a date in the future**

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

**Comment by Jenefer-Monroe** [comment] 2022-10-21 12:06
Thanks for investigating and posting. Someone else posted this bug a few days ago and its local fixed for Nov now. 
https://github.com/microsoft/coe-starter-kit/issues/3954

Will go ahead and close as a dupe of that issue.

**Closed by Jenefer-Monroe** 2022-10-21 12:06 UTC
Labels: bug, coe-starter-kit
