### ISSUE TITLE
[ALM Accelerator - Feature]: Choose the same owner/activation user on many flows

### ISSUE THREAD

**Issue by thetla** [microsoft/coe-starter-kit#4087] opened 2022-11-01 09:29 UTC
### Describe the solution you'd like

Hi

We would like that it should be able to choose the same user on all of the Owner and Activation fields. It really take a long time when doing this for 20 flows etc. It's also a little bit buggy some times with the filtering when you have many flows. We have many makers here in Equinor that would appreciate that. It would save a lot of time doing the configure deployment steps in ALM app.

**Comment by mikefactorial** [comment] 2022-11-01 14:28
I think you'll both be happy with an update we're introducing in the November release that will make this experience a little easier :). Closing this out for now as a duplicate of [#3406](https://github.com/microsoft/coe-starter-kit/issues/3406)

**Closed by mikefactorial** 2022-11-01 14:28 UTC
Labels: enhancement, alm-accelerator
