### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#6723] opened 2023-09-27 04:00 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,

From past 7 days, our COE Makers dataflow is failing, all our data verse tables related to apps and flows are blank. we have tried to upgrade with the COE September Kit and still we are facing the attached issue, Please assist us asap as this is impacting our business activities.

<img width="706" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/bbeef76e-a2b6-4e47-ada4-0387cab66a4f">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

core 4.15

### What app or flow are you having the issue with?

Makers data flow

### What method are you using to get inventory and telemetry?

Data Export

**Comment by ALSPowerPlatform** [comment] 2023-09-27 04:31
could you please assist us soon

**Comment by ALSPowerPlatform** [comment] 2023-09-27 06:22
@Jenefer-Monroe Could you please help us on this issue asap, it is impacting our business applications built on top of COE dataverse tables as well as PBI dashboards.

**Comment by manuelap-msft** [comment] 2023-09-27 07:30
Hello,

this is a duplicate of https://github.com/microsoft/coe-starter-kit/issues/6688 and https://github.com/microsoft/coe-starter-kit/issues/6577. The issue is caused by new properties being made available in Data Export, some of which are made available through nested JSON in the files we consume from the storage account and the Dataflow transformations weren't robust enough to handle nested JSON. 

We are still testing the changes required to the dataflow, but you can try making the following changes on your side and let us know how you get on:
1. Changes to the Power BI dataflow: https://github.com/microsoft/coe-starter-kit/issues/6688#issuecomment-1731598690
2. Changes to the Power Platform dataflows: https://github.com/microsoft/coe-starter-kit/issues/6688#issuecomment-1736852295

Please comment on the open issue in #6688 with your findings, as it's easier for us to track the issue in one place.

**Comment by manuelap-msft** [comment] 2023-09-27 07:31
Please also note that the CoE Starter Kit is an unsupported set of templates - although we aim to triage issues on GitHub regularly, we're a really small team and can't offer a SLA for when we're able to respond to issues.

**Comment by ALSPowerPlatform** [comment] 2023-09-27 10:29
we have updated the suggested code, still the apps are not completely updated to data verse tables. could you please let us know how much time it might take. The dataflows are successful, but data is not complete in tables.

**Comment by ALSPowerPlatform** [comment] 2023-09-27 10:47
<img width="725" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/ebe2e752-05ce-4c96-b07a-ff021e4ac091">

**Comment by ALSPowerPlatform** [comment] 2023-09-27 11:49
And our sync flows BYODL starts failing
<img width="398" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/87e5b97d-ec15-489c-a141-6284a999caea">

**Comment by Jenefer-Monroe** [comment] 2023-10-09 16:32
Please test with the Oct release and make sure you dont have unmanaged layers on the dataflows

**Closed by Jenefer-Monroe** 2023-10-09 16:32 UTC
Labels: duplicate, question, coe-starter-kit
