### ISSUE TITLE
[CoE Starter Kit - BUG] App Shares PowerBi Dashboard

### ISSUE THREAD

**Issue by lfano24** [microsoft/coe-starter-kit#4680] opened 2023-01-27 20:45 UTC
### Describe the issue

The number of shares for each app doesnt match the actual number of users an app is shared with.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### Anything else?

I looked through the flow and saw that there is no action to reset the totalusers or total groups variables after each app. I haven't seen any discussion about this issue, so I am not sure if this is only happening to me in my environment.

**Comment by Jenefer-Monroe** [comment] 2023-01-27 21:55
Hello. I believe this is a dupe of https://github.com/microsoft/coe-starter-kit/issues/4468, local fixed for Feb release.

**Comment by Jenefer-Monroe** [comment] 2023-01-30 17:31
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-01-30 17:31 UTC
Labels: bug, coe-starter-kit
