### ISSUE TITLE
[CoE Starter Kit - BUG] install from version 1.98 to latest version failed

### ISSUE THREAD

**Issue by NGseb** [microsoft/coe-starter-kit#1667] opened 2021-12-21 22:08 UTC
### Error message : 
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. 
InnerException is: 
Solution dependencies exist, cannot uninstall. 

Looking at the log the error occured during the activation of  "CLEANUP - Admin | Sync Template v3 (Check Deleted)". Details of error is below, all other tasks have not been processed.  
What has not been processed : 
- 4 security role, 
- 39 Workflow activation 
- 7 web resource
How could i manage this? I tryed to reinstall the solution, but it failed also (the solution is already installed)

**Error Code** : 
0x80040216
**Error Text** : 
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: 'BadRequest,BadRequest,BadRequest,BadRequest,BadRequest'. Please see details.","details":[{"code":"ChildFlowNeverPublished","message":"The workflow with id '2e6[xxxxxx]7d7d' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id '2e6[xxxxxx]7d7d'' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b3f[xxxxxx]c7b0' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id '9a47[xxxxx]7f74' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id 'ffd82[xxxxx]237d7d' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}]}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.98

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment] 2021-12-21 23:54
Hello I'm afraid I cannot help with upgrade from that old of a version. 
But if the issue is that you cant turn on the flows, note that there are now child flows that need turned on first. 
Please turn these on in the order shown https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by Jenefer-Monroe** [comment] 2021-12-30 17:42
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2021-12-30 17:42 UTC
Labels: coe-starter-kit
