### ISSUE TITLE
[CoE Starter Kit - BUG]: Theme Publishing

### ISSUE THREAD

**Issue by charrisonfuji** [microsoft/coe-starter-kit#553] opened 2021-06-01 14:47 UTC
**Describe the bug**
Hi, when using the theming component specifically the "PublishScreen" in the theme editor tool. The ability to upload the msapp files disappears. Also just above, the name of the selected theme disappeared. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - App or Flow: Theme editor tool app ver. 1.2

**To Reproduce**
1. Create a theme 
2. Save theme
3. Go to publish 
4. See error below

**Expected behavior**
You should be able to view the upload icons and upload phone & tablet msapp file. 

**Screenshots**

![image](https://user-images.githubusercontent.com/84843401/120343036-43c73380-c2f0-11eb-943c-857d158d78ed.png)
![image](https://user-images.githubusercontent.com/84843401/120343101-53df1300-c2f0-11eb-9bce-fa07c3672776.png)

**How I fixed it**
The error's pointed to the selectedTheme variable however this variable could not be used as it was not globally declared. Changed it to be global as the below and it worked. 
![image](https://user-images.githubusercontent.com/84843401/120343418-9b659f00-c2f0-11eb-9b47-dcb855b68d88.png)

**Comment by dtsoden** [comment] 2021-07-29 13:43
I just uploaded Theming_1.0.20210618.2_managed.zip to the environment.
I know this is not what is wanting to be heard but it needs to be known.
The app user experience has gotten worse and the same problem exists.

![2](https://user-images.githubusercontent.com/36846872/127501682-22328795-da77-4755-989b-abc69f5a43e8.png)
![3](https://user-images.githubusercontent.com/36846872/127501685-4d1bf7f4-209e-4095-a353-37b10a84b6cb.png)
![1](https://user-images.githubusercontent.com/36846872/127501687-90f33824-b186-442f-ac77-3b1cff434508.png)

The entire UI when editing a particular theme is unresponsive or locks up or loses changes made in the theme.
delete a theme requires a refresh as the modal confirmation is stuck as shown in one image. 
again I had several instances where my changes never stuck at all. 
the app still is unusable and is not ready for production use. 
more than happy to work with someone one-on-one.

I had worked with one of the Big 4 trying to get support on this feature, also a major consulting company currently, and one client in the energy sector in SO CAL is also looking at this feature, and I was going to present the option but now am going to hold off.  If this feature is keen to the team I have contacts willing and needing such a feature. Again offering to work with someone at Microsoft if this is also important to the team.

**Comment by dtsoden** [comment] 2021-07-29 13:56
I also recorded this youtube video to show the oddness of the application and how some simple time spent UAT before releasing would go a long way to adoption. If this is something that is low on the priority list - I get it, perhaps remove it till it's is ready and or stable?

Here is the video showing the user experience:
https://youtu.be/azgXiLHl3_o

**Comment by devkeydet** [comment] 2021-07-29 13:58
@dtsoden - I sense your frustration.  Sorry for the frustrating experience.  I've asked folks on the team to prioritize reviewing this issue.

**Comment by dtsoden** [comment] 2021-07-29 14:24
> @dtsoden - I sense your frustration. Sorry for the frustrating experience. I've asked folks on the team to prioritize reviewing this issue.

Thanks Marc

**Comment by carolynle27** [comment] 2021-08-02 05:22
Hi guys, I'm keen to see this issue resolved as well, it's such a massive efficiency gain if I can use the theming component as expected. Is there any other workarounds available?

**Comment by charrisonfuji** [comment] 2021-08-02 07:42
@carolynle27 , @dtsoden  does not uncommenting the the selectedTheme variable not work for you both ? As it did for me when trying to publish screens (just thinking if this could be a workaround for you both) ?

**Comment by dtsoden** [comment] 2021-08-02 11:57
@charrisonfuji, it may, I have not tried. I am not evaluating for personal use. My perspective is for Fortune x clients, the same clients Microsoft sees as important. It is not stable enough for them to use or for me to recommend to them to bother at this point. I eagerly await, as all of the CoE tools have and show great promise.

**Comment by carolynle27** [comment] 2021-08-02 23:44
@charrisonfuji Hi I've given that a try and it works as expected now. Thank you!

**Comment by charrisonfuji** [comment] 2021-08-03 07:48
@carolynle27  glad it worked

**Comment by mikefactorial** [comment] 2021-08-03 14:22
Closing this for now duplicate of #402. Will update on that issue.

**Comment by t-irani** [comment] 2021-08-03 23:03
@charrisonfuji Thanks for referring me to this ticket. I tried updating the SelectedTheme variable as described above which resolved the issue with the upload feature. However, I also found another error on this screen. 

![image](https://user-images.githubusercontent.com/87785421/128096120-52e2f5bf-790c-4c38-9bcd-4572f6a4fcba.png)

![image](https://user-images.githubusercontent.com/87785421/128095981-db9197e5-060b-4550-acac-d8657387d02d.png)

In my version of this app, the txtThemeName control didn't exist - the control it should be referring to is called txtThemeName_1. I corrected the code, and the theme name is now correctly displayed.

I thought that was all resolved. However, when I now attempt to publish the app, I get the following error.

![image](https://user-images.githubusercontent.com/87785421/128096319-1f39abb7-88b7-4894-b317-4c72e5cdb3da.png)

The full text of the error is:
The request failed with error: '{"error":{"code":"0x8004f036","message":"The dependent component CustomControl (Id=cat_RAW.ColorPicker.ColorPicker(fd140aaf-4df4-11dd-bd17-0019b9312238)) does not exist.  Failure trying to associate it with CanvasApp (Id=cecfc429-1daf-452f-8522-e2822b950de0) as a dependency. Missing dependency lookup type = EntityNameLookup."}}'. The tracking Id is '60134ad8-ef47-4bcc-bd42-e25ef9968516'.

Session ID: ae337ea8-039e-435f-9942-f9c44bca0726

Any suggestions on resolving this issue?
Thanks

**Comment by mikefactorial** [comment] 2021-08-04 12:57
@t-irani the publishing error is happening in our environment as well which is blocking an updated release of the solution with the fix. We've notified the specific engineering team of the issue and will hopefully get a resolution soon. Adding @slaouist who is working with the engineers on this issue.

**Comment by charrisonfuji** [comment] 2021-08-04 13:02
@mikefactorial , @t-irani to confirm I have encountered the dependcy error before so please keep me in the loop for updates if it all possible thanks

**Comment by t-irani** [comment] 2021-08-04 21:49
@mikefactorial Thanks, look forward to hearing of a resolution.

**Comment by charrisonfuji** [comment] 2021-08-09 13:17
@mikefactorial @t-irani  Just to add I have noticed this happening when I add a app (based from apptemplatetablet) to a solution and then edit the app in another environment. Once I re-publish the app I get the error same as @t-irani thanks

**Comment by mikefactorial** [comment] 2021-08-09 17:40
@t-irani and @charrisonfuji The engineering team was able to verify a bug that's causing the publishing error. A fix has been checked in. Waiting to hear what the timeline is for rolling out the fix to the various geos.

**Comment by t-irani** [comment] 2021-08-09 21:06
@mikefactorial @charrisonfuji Thanks for the update Mike, good to know the issue has been identified.

**Comment by charrisonfuji** [comment] 2021-08-10 07:56
@spb21 copying you in so you get updates on when the fix for the dependency error with COE theming is released. 

> @t-irani and @charrisonfuji The engineering team was able to verify a bug that's causing the publishing error. A fix has been checked in. Waiting to hear what the timeline is for rolling out the fix to the various geos.

![image](https://user-images.githubusercontent.com/84843401/128827728-4cccafc3-4001-428f-8058-df2930747449.png)

**Comment by charrisonfuji** [comment] 2021-08-10 08:52
@nihil1409 added for updates

**Comment by mikefactorial** [comment] 2021-08-11 13:58
The temporary work around to being able to publish an app with the dependent component error above is to remove the component(s) (obv. make sure to take note of all the properties beforehand), Save and Close the app. Open the app in the editor and add the component(s) back. As I mentioned a fix in the platform is on the way, but this workaround allowed us to re-publish the theme app with the fixes for the original issue and the new version will be in the August release going out in the next couple of days.

**Comment by charrisonfuji** [comment] 2021-08-11 14:34
thanks @mikefactorial for the update that sounds great. Before I try this myself I just wanted to check something. When you say remove the component do you mean to remove the component in the app itself or the component in the solution ? It seems the errors I saw were pointing towards that one component (the font loader)

**Comment by charrisonfuji** [comment] 2021-08-11 14:44
thanks @mikefactorial

**Comment by mikefactorial** [comment] 2021-08-12 14:03
@charrisonfuji This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by mikefactorial** 2021-08-12 14:03 UTC
Labels: theming

**Comment by t-irani** [comment] 2021-08-12 21:49
Thanks @mikefactorial
