### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE Admin and Maker Command Center Apps

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5109] opened 2023-03-27 20:00 UTC
### What is your question?

Hi,

Do you have any videos available about COE Admin and Maker Command Center Apps?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment] 2023-03-27 21:02
No we do not have those today. Do you have any specific questions about them that I could answer?

**Comment by lingutla123** [comment] 2023-03-28 00:53
When i opened COE Maker Command Center app getting below error.
![image](https://user-images.githubusercontent.com/126264610/228098530-cda0d6d7-ca84-4b07-acbf-ce0ad517c4b0.png)

**Comment by Jenefer-Monroe** [comment] 2023-03-28 12:39
I dont repro. Can you please see what you have configured for the Makers? 
Go to the CoE Admin Command Center > Bookmarks > Edit Bookmarks 
![image](https://user-images.githubusercontent.com/89584709/228238401-c537d94f-4ef1-41d6-820b-02aa5b8bb522.png)

Filter the Show in Maker Command Center column to Yes. 
![image](https://user-images.githubusercontent.com/89584709/228238667-9a8c17b2-f741-4a63-b3f4-b8bea1f9bb46.png)

What do you have selected?

**Comment by lingutla123** [comment] 2023-03-28 13:40
I don't see anything in Admin Command Center.

![image](https://user-images.githubusercontent.com/126264610/228256296-36eb2572-cc83-4773-9534-16b85b25f139.png)

**Comment by Jenefer-Monroe** [comment] 2023-03-28 14:55
ok you probably haven't run the flow to initialize bookmarks. 
Please run **_Command Center App > Initially Populate Bookmarks_**

**Comment by lingutla123** [comment] 2023-03-28 21:13
Ran the  Initially Populate Bookmarks and Maker Environment Request - "Show Maker Command Center"  changed from No to Yes. But still getting the same error.
![image](https://user-images.githubusercontent.com/126264610/228368319-95ba6126-689b-4171-a7aa-c41601d3d198.png)

**Comment by Jenefer-Monroe** [comment] 2023-03-28 21:17
OK i still dont repro. What version of Core are you on?

**Comment by lingutla123** [comment] 2023-03-28 21:37
Core Components- 4.3

**Comment by Jenefer-Monroe** [comment] 2023-03-28 21:44
Hmmm... can you please do the following:

Open the Model Driven App in edit mode: 
![image](https://user-images.githubusercontent.com/89584709/228372785-653e2f01-acb0-4191-9a4b-4faecf9015f2.png)

In the left you will see the pages, edit the Maker Apps one
![image](https://user-images.githubusercontent.com/89584709/228373135-e76bc1af-220e-4670-92e8-b0c2c7aa033c.png)

Click **_Open app_** on this warning
![image](https://user-images.githubusercontent.com/89584709/228373411-2adaebc4-544c-4ca8-923e-d408df722273.png)

Click **_Skip_** on this warning
![image](https://user-images.githubusercontent.com/89584709/228373456-e2959e4f-f16f-4c86-8cdd-5f2b58e5710c.png)

Now when you get the error it should show you red sqigglies where it failed.  Likely in OnStart for the App. Can you show me where its failing?

**Comment by lingutla123** [comment] 2023-03-28 21:50
When i click on Edit on COE Commander App it is giving this error.
![image](https://user-images.githubusercontent.com/126264610/228374792-ceb11a63-8aab-45fb-a143-28a6577baa9c.png)

**Comment by Jenefer-Monroe** [comment] 2023-03-28 22:03
What permissions does the user you are logged in as have in the envt?

If you dont know, go to the coe envt settings
![image](https://user-images.githubusercontent.com/89584709/228376606-471f525c-58a8-486f-8850-bb3a34340e3f.png)

USers
![image](https://user-images.githubusercontent.com/89584709/228376692-e71efb91-9cda-4491-9e39-fa90e1bb67c2.png)

Click your user > Roles
![image](https://user-images.githubusercontent.com/89584709/228376860-ef4e4754-19ce-4510-8655-f1a55a6e3c63.png)

**Comment by lingutla123** [comment] 2023-03-28 23:30
![image](https://user-images.githubusercontent.com/126264610/228389455-10da958c-d2fa-4578-97df-9d50150f47b0.png)

**Comment by Jenefer-Monroe** [comment] 2023-03-31 11:06
oh here's the reason i didnt repro. It was local fixed for us for April release 
https://github.com/microsoft/coe-starter-kit/issues/4747

YEAH! 

I'll close as a dupe of that issue. Duplicate of #4747

**Closed by Jenefer-Monroe** 2023-03-31 11:06 UTC
Labels: question, coe-starter-kit
