### ISSUE TITLE
[CoE Starter Kit - BUG] System Guid string missing Maker Table

### ISSUE THREAD

**Issue by antc11** [microsoft/coe-starter-kit#3317] opened 2022-07-31 00:24 UTC
### Describe the issue

Error when loading model for Production_CoEDashboard_August2022.
Maker
Column 'admin_recordguidasstring' in Table 'Maker' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. System user makerid contained Guid however hadn't populated the as string column. Populating the string with the makerid resolved issue and model loaded.

### Expected Behavior

'admin_recordguidasstring' should have been populated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_3.41_managed

### What app or flow are you having the issue with?

CoE Maker table

### Steps To Reproduce

Install CoE starter kit into new Dataverse environment.
Import Production_CoEDashboard_August2022 into Power BI

### Anything else?

E

**Comment by Jenefer-Monroe** [comment] 2022-07-31 02:53
Please run the following flow until you dont see these errors, the field was added to several tables and this flow will populate the field **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_**

**Comment by Jenefer-Monroe** [comment] 2022-08-02 15:10
Thanks for posting, we are re-shipping the PBI to remove this alt key. Details in #3318 
Here they are ahead of releasing them, in case you would like an early copy: [August PBITs with alt key removed.zip](https://github.com/microsoft/coe-starter-kit/files/9242700/August.PBITs.with.alt.key.removed.zip)

I'll close this as a dupe of that.

**Closed by Jenefer-Monroe** 2022-08-02 15:10 UTC
Labels: bug, coe-starter-kit

**Comment by manuelap-msft** [comment] 2022-08-03 08:40
We have re-released the PBIT files to address #3322 and #3318. They're available when you re-download https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-August2022/CoEStarterKit.zip
