### ISSUE TITLE
[ALM Accelerator - QUESTION] Solution Layering

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3276] opened 2022-07-26 18:54 UTC
### What is your question?

We have already layered our solutions based on functionality as follows 
Solution 1. Core components (Common components )
Solution 2 . Service components
Solution 3 : Sales components . 
We have 3 separate repo for each solutions in azure DevOps projects .

sometimes  it requires changes in both Core components solution and Service component solution depend on the requirement .
How can me move both solution at a time by using ALM accelerator  in order to avoid dependency issue ? 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Apr 2022

**Comment by mikefactorial** [comment] 2022-07-26 19:32
Hey @linujohn22,
Thanks for the question. Currently, we don't have any coordination of solution layering or deploying multiple solutions at once built into the ALM Accelerator. The CoE Starter Kit team uses the ALM Accelerator for releases and has similar requirements, but currently we have to ensure that core dependencies are deployed in the correct order to avoid dependency issues. We have a backlog feature request related to this here https://github.com/microsoft/coe-starter-kit/issues/786. Will add this as a related request

**Comment by mikefactorial** [comment] 2022-09-07 14:43
Closing this out as duplicate of #786

**Closed by mikefactorial** 2022-09-07 14:43 UTC
Labels: enhancement, alm-accelerator
