### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template v3 - fails to identify free developer environments

### ISSUE THREAD

**Issue by RialtoIT** [microsoft/coe-starter-kit#2409] opened 2022-04-08 07:04 UTC
### Describe the issue

Admin sync template v3 failed due to environment not present in environments table. The flow is not identifying 'Developer' environments for which there is no record within the environments table. The 'Developer' environments are created when a maker has signed up for a free developer environment. To work around this I added the following additional criteria to the 'Check if Legacy Environment' action:
OR CreationType contains Developer

Not sure if this warrants its own condition but rather just rename the 'Check for Legacy Environment' to 'Check for Legacy or Developer Environments', as I have assumend the logic that follows is the same for either condition (please verify).

### Expected Behavior

Admin Sync Template v3 runs without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Steps To Reproduce

1. In the CoE Environment
2. using version 3.36 of the Core Components. Users have registered for free developer environments, and you have developer environments listed under admin.powerplatform.com/environments
3. run the Admin - Sync Template v3
4. flow fails with an error on the Get Environments action -> error "admin_environment With ID = [GUID] Does Not Exist"

**Comment by manuelap-msft** [comment] 2022-04-08 07:09
Hello,

we released a hotfix for this issue yesterday with Core version 3.37 which you can download from here https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-April2022/CenterofExcellenceCoreComponents_3_37_managed.zip

Thank you
Manuela

Closing as duplicate of #2397

**Closed by manuelap-msft** 2022-04-08 07:09 UTC
Labels: bug, coe-starter-kit

**Comment by RialtoIT** [comment] 2022-04-08 07:12
perfect thanks maneula.

**Comment by manuelap-msft** [comment] 2022-04-08 07:13
Sorry for the inconvenience!!
