### ISSUE TITLE
[CoE Starter Kit - Enhancement] More flexibility for Governance and Nurture flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#714] opened 2021-06-30 15:11 UTC
Customers are asking for more flexibility to control at a more granular level how governance flows (like archive and compliance requests) are send to makers. Customers want to exclude certain environments from these flows.

We can add an additional field to the Environment table to indicate if this environment should be taken into consideration for governance / nurture flows - this would have to be set on every environment. We would then have to update our flows as well to check this field.

**Comment by tkudya** [comment] 2021-07-29 11:31
This feature will be useful, we have environments were Apps are created by Accounts that won't have mailboxes so they can't receive emails to Approve/Reject the approval emails.

**Comment by DiptiC-InsightRun** [comment] 2021-08-10 13:42
This could be specifically useful for the environments, for example, CoE Environments where every apps/flow probably does not require to be audited as they are all need to be there by default and by design and not require to be deleted at all. If there is a possibility to exclude similar environments would save a lot of time for CoE Admin.

**Comment by DiptiC-InsightRun** [comment] 2021-08-10 14:02
Hey @tkudya - I just had the same concern for which question has been raised here - https://github.com/microsoft/coe-starter-kit/issues/989

I believe that's something manageable within the flow by checking the "Mail" property value, however, it will be great if CoE flows/email notifications are re-adjusted accordingly. However, I agree "Excluding Environment" could be one option, but that might exclude all the resources in the environment!

> This feature will be useful, we have environments were Apps are created by Accounts that won't have mailboxes so they can't receive emails to Approve/Reject the approval emails.

**Comment by v7herman4** [comment] 2021-08-16 13:51
This would be a great feature for GCC customers!

**Comment by anton3sco** [comment] 2021-08-17 01:51
Happy to see this as a backlog item! I have a number of customers that are curious about this backlog item. A couple of customers in particular with 28k power app per user licenses and another with less. 

We have toyed with the idea of checking if it's the CoE environment or a developer environment as well. I don't think we will be immediately pursuing this but it's in our backlog.

Thank you and keep up the great work! We appreciate it!

**Comment by manuelap-msft** [comment] 2021-08-17 07:49
Hello,

our plan is:
- Add a yes/no field to the Environments table to Exclude this environment from governance and nurture flows (Question: is one flag enough, or would you like to have two flags - one to exclude from governance flows, one to exclude from nurture flows?)
- Update the Power Platform Admin View (model driven app) to allow updating of this flag 
- Update all flows to honour this flag 

We are not considering excluding entire Environment Types (e.g. all Trial / Developer environments) but it's a setting per environment - is this sufficient to meet your requirements?

We are likely not able to fit this into the September release anymore, but are targeting October for it.

Thank you
Manuela

**Comment by DiptiC-InsightRun** [comment] 2021-08-17 08:11
Hi Manuela,

Thank you for the updates, this is excellent!

I would prefer two flags - More flexibility wins if it doesn't require too much work. Would you please share - As a CoE Admin, where can we configure to exclude the specific environment?

It would be nice to have a feature to exclude environment by type, however, I don't think it's urgent.

Looking forward to seeing it's happening in October 2021, Thank you for listening and making the CoE Starter Kit robust and more optimized for all of us!

Thanks and Kind Regards,
Dipti

**Comment by anton3sco** [comment] 2021-08-20 11:38
I think having two flags would be great. 

> Hello,
> 
> our plan is:
> 
> * Add a yes/no field to the Environments table to Exclude this environment from governance and nurture flows (Question: is one flag enough, or would you like to have two flags - one to exclude from governance flows, one to exclude from nurture flows?)
> * Update the Power Platform Admin View (model driven app) to allow updating of this flag
> * Update all flows to honour this flag
> 
> We are not considering excluding entire Environment Types (e.g. all Trial / Developer environments) but it's a setting per environment - is this sufficient to meet your requirements?
> 
> We are likely not able to fit this into the September release anymore, but are targeting October for it.
> 
> Thank you
> Manuela

Having 2 flags would be great
I like the idea of this flag showing in the admin view app

Yes, this meets the needs per environment. If we want we could always write a separate flow to do a check on what type of environment it is and to update the flags based on logic.

Looking forward to this!

**Comment by Jenefer-Monroe** [comment] 2021-09-08 16:01
I have this local fixed for the October release. I added two flags to environment. One to excuse from the archival flows in Gov solution, the other to excuse from the compliance flow in Core solution. 

Field names are:
- admin_excusefromarchivalflows
- admin_excusefromcomplianceflow

And can be set in the model driven app
![image](https://user-images.githubusercontent.com/89584709/132544098-4272c8cf-1663-4155-9497-dc4cf0ea9b4c.png)

Note that the old technique of excusing default for the compliance flow will still work too. 

Please let us know if you have feedback.

**Comment by mikefactorial** [comment] 2021-10-04 12:20
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by mikefactorial** 2021-10-04 12:20 UTC
Labels: vnext, governance-components, coe-starter-kit-backlog
