### ISSUE TITLE
Admin | Sync Template v3 (PVA) flow got failed

### ISSUE THREAD

**Issue by annaserbenko** [microsoft/coe-starter-kit#2434] opened 2022-04-12 08:08 UTC
### Describe the issue

Admin | Sync Template v3 (PVA) flow got failed each time when it comes to GetBotID action.
In the scope called Update Components for Changed Bots each time when the List BotComponents action **ISN'T** empty we receive an error in the **GetBotID compose action**.
And the April update of starter kit is useless here because it checks if List BotComponents action is empty or not and each time it's not we receive this error.
On the screenshots you can see that the List BotComponents action isn't empty and the error we receive in the action after that.

### Expected Behavior

Successful run of the Get Parent Bot ID scope and actions inside it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

Actually, each time when the List BotComponents action isn't empty you can see that GetBotID compose action got failed. We didn't find any successful runs when the List BotComponents action isn't empty.

### Anything else?

![image](https://user-images.githubusercontent.com/102215719/162912125-68767505-8b3a-48d1-a1d6-05285f729849.png)
![image](https://user-images.githubusercontent.com/102215719/162912406-1dbd3b42-f956-4b7e-b487-53c072c7cb24.png)
![image](https://user-images.githubusercontent.com/102215719/162912440-4186eb1f-441a-484a-919c-9535d3c0757c.png)

**Comment by Jenefer-Monroe** [comment] 2022-04-12 14:51
Hello, this is a Duplicate of #2405 which is fixed for May. 
Thanks for using CoE.

**Closed by Jenefer-Monroe** 2022-04-12 14:51 UTC
Labels: bug, coe-starter-kit
