### ISSUE TITLE
[CoE Starter Kit - BUG] DataFormat.Error: We found extra characters at the end of the JSON input

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#6742] opened 2023-09-27 23:00 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

hi @Jenefer-Monroe ,

While editing the BYODL Dataflow, we are getting below error during the evaluation. 

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/14b76c6a-7411-40a6-8f6f-8ddb4415e264)

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/2c24c9de-77f4-44b8-a47f-e7744a3849e6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE BYODL Makers Data flow

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Edit the data flow.
2. wait for the makers evaluation to be completed.

**Comment by manuelap-msft** [comment] 2023-09-28 08:46
Hello,

this is a duplicate of https://github.com/microsoft/coe-starter-kit/issues/6688 and https://github.com/microsoft/coe-starter-kit/issues/6577. The issue is caused by new properties being made available in Data Export, some of which are made available through nested JSON in the files we consume from the storage account and the Dataflow transformations weren't robust enough to handle nested JSON. 

We are still testing the changes required to the dataflow, but you can try making the following changes on your side and let us know how you get on:
1. Changes to the Power BI dataflow: https://github.com/microsoft/coe-starter-kit/issues/6688#issuecomment-1731598690
2. Changes to the Power Platform dataflows: https://github.com/microsoft/coe-starter-kit/issues/6688#issuecomment-1736852295

Please comment on the open issue in #6688 with your findings, as it's easier for us to track the issue in one place.

I'll close this out as a duplicate.

**Closed by manuelap-msft** 2023-09-28 08:46 UTC
Labels: bug, coe-starter-kit
