### ISSUE TITLE
[CoE Starter Kit - QUESTION] Missing solutions 

### ISSUE THREAD

**Issue by Gmejia706** [microsoft/coe-starter-kit#4107] opened 2022-11-02 21:49 UTC
### What is your question?

I've successfully installed the power platform COE Starter kit. While reviewing the "Solutions" tab within the starter kit, the number of solutions presented does not reflect the number of solutions installed within the environment.  To confirm this, I've ensured that all filters have been removed from the BI report. 

While troubleshooting this issue, I've found that if you manually trigger the "Admin | Sync Template v3 (Solutions)" flow by updating a record of an environment within the PP Admin View app, the manual trigger will cause the flow to pull down all solutions to the starter kit. 

But once the scheduled flow "Admin | Sync Template v3" finishes, it then clears out any solutions that was brought down during my manual trigger. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment] 2022-11-03 02:17
Hello. I'm afraid I dont follow you here. There is no difference in the two situations you describe from the flow POV so we'll have to use a specific example. What is a solution you expect to see that you do not? We will need to walk through with it to see the repro. 

Note that we filter out all the Microsoft product solutions in order to save storage and API costs, so you will not see solutions like these that are installed by Microsoft when you setup Portals. 
![image](https://user-images.githubusercontent.com/89584709/199635891-1d609bad-bcbd-45e1-a52d-ef789275ce94.png)

Or these that you get when you setup flow approvals
![image](https://user-images.githubusercontent.com/89584709/199635966-3b2fd27b-73af-4ea9-b9c1-f963301ec434.png)

Please let me know if you have a specific case where you expect to see a non-Microsoft product solution and do not.

**Comment by Gmejia706** [comment] 2022-11-03 04:02
Hey Jenefer, 

Thanks for getting back to me. Here's a specific example of what I'm referring to. Below is a screenshot of refreshed data of the solutions tab in the COE starter kit. There are a total of 18 solutions listed here for my environment but specifically you'll see that solution for "Clickdimensions" is missing. The ClickDimensions solutions is a managed 3rd party solution that I would assume should be displayed within COE starter kit. 

![image](https://user-images.githubusercontent.com/117318292/199645274-94defb50-b8dd-4b2a-bbae-bff6a4865d8a.png)

Please note that in troubleshooting this issue, I did remove all solution query filters within the flow "Admin | Sync Template v3 (Solutions)" so it should list all default solutions. Below is a screenshot from the environment's POV of the list of all solutions. You'll notice there are a total of 61 total solutions, including the "Clickdimensions solution in question and several other that are not displayed. 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/117318292/199644719-6081cc18-99ea-47dd-81ac-adcbf544e89d.png">




> Hello. I'm afraid I dont follow you here. There is no difference in the two situations you describe from the flow POV so we'll have to use a specific example. What is a solution you expect to see that you do not? We will need to walk through with it to see the repro.
> 
> Note that we filter out all the Microsoft product solutions in order to save storage and API costs, so you will not see solutions like these that are installed by Microsoft when you setup Portals. ![image](https://user-images.githubusercontent.com/89584709/199635891-1d609bad-bcbd-45e1-a52d-ef789275ce94.png)
> 
> Or these that you get when you setup flow approvals ![image](https://user-images.githubusercontent.com/89584709/199635966-3b2fd27b-73af-4ea9-b9c1-f963301ec434.png)
> 
> Please let me know if you have a specific case where you expect to see a non-Microsoft product solution and do not.

**Comment by Gmejia706** [comment] 2022-11-03 04:02
Hey Jenefer, 

Thanks for getting back to me. Here's a specific example of what I'm referring to. Below is a screenshot of refreshed data of the solutions tab in the COE starter kit. There are a total of 18 solutions listed here for my environment but specifically you'll see that solution for "Clickdimensions" is missing. The ClickDimensions solutions is a managed 3rd party solution that I would assume should be displayed within COE starter kit. 

![image](https://user-images.githubusercontent.com/117318292/199645274-94defb50-b8dd-4b2a-bbae-bff6a4865d8a.png)

Please note that in troubleshooting this issue, I did remove all solution query filters within the flow "Admin | Sync Template v3 (Solutions)" so it should list all default solutions. Below is a screenshot from the environment's POV of the list of all solutions. You'll notice there are a total of 61 total solutions, including the "Clickdimensions solution in question and several other that are not displayed. 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/117318292/199644719-6081cc18-99ea-47dd-81ac-adcbf544e89d.png">

**Comment by Jenefer-Monroe** [comment] 2022-11-03 12:14
Please go to https://make.powerapps.com/ > chose the environment you are investigating here where you expect the ClickDimensions solution to appear > Dataverse > Tables > All > Find Solutions table and click on it
![image](https://user-images.githubusercontent.com/89584709/199716975-34793fc0-d83a-4a33-a815-c72ce55b7389.png)

Add columns until you have the following shown
![image](https://user-images.githubusercontent.com/89584709/199717269-c503da15-a242-428d-ba9a-07de96728a4b.png)
![image](https://user-images.githubusercontent.com/89584709/199717534-e3cba3a2-08d9-44da-838b-86f4073b6d00.png)

Find your ClickDimensions in the table and return with what is shown in the table.

**Comment by Gmejia706** [comment] 2022-11-03 13:50
Here's whats displayed.

![image](https://user-images.githubusercontent.com/117318292/199738280-154e75c2-c811-43c1-8eb0-6c400ee12da9.png)

Please note that the CD solution is just one of many that is not being returned in the COE starter Kit

**Comment by Jenefer-Monroe** [comment] 2022-11-03 14:36
Understood, we just have to use a single case to debug. 
1. Please [remove the unmanaged layer](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) on the flow that you created while debugging, and then trigger the run like you did by editing the envt in the Power Platform Admin View. 
Is the ClickDimensions returned here when you do that? 
![image](https://user-images.githubusercontent.com/89584709/199750212-2486ec7d-444a-4c97-8bb6-83be07cdc731.png)

2. Is this ClickDimensions solution installed in multiple environments?

**Comment by Jenefer-Monroe** [comment] 2022-11-03 15:48
The latest version is the Nov release 3.56
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2022

It looks like we forgot to update https://aka.ms/coestarterkitdownload but its updated now.

**Comment by Jenefer-Monroe** [comment] 2022-11-03 15:49
Will await your results from the run when it completes or from upgrading.

**Comment by Jenefer-Monroe** [comment] 2022-11-04 19:58
In order to share API processing calls, we dont collect the managed solutions from Microsoft (eg Dynamics 365). The point of this inventory is to see the solutions that have been installed manually by you from 3rd parties or which were created in your own tenant.

**Comment by Gmejia706** [comment] 2022-11-10 14:44
Jenefer, 

I can confirm that all COE components have been updated to the latest version. I've been monitoring 2 different environments and the number of solutions presented within the COE report flufenacets. One day it says there 31 solutions, the next day it shows there are 279 solutions.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 15:03
When you say latest version, can you please share a screenshot that shows this? 
![image](https://user-images.githubusercontent.com/89584709/201128802-d180b9af-69d4-43c2-9c11-a4a8d900eae9.png)

**Comment by Gmejia706** [comment] 2022-11-10 15:06
Here you go:

![image](https://user-images.githubusercontent.com/117318292/201130810-68136723-e9c6-4193-b254-d04c6237693f.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-10 15:24
thank you, and can you please check if you have an unmanaged layer on these flows? 

![image](https://user-images.githubusercontent.com/89584709/201135042-73fbe28d-8e94-487c-ba69-94ccd7bf0f3e.png)

- Admin | Sync Template v3 (Solutions)
- CLEANUP HELPER - Check Deleted (Solutions)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

**Comment by Gmejia706** [comment] 2022-11-10 15:40
I can confirm no unmanaged layers

![image](https://user-images.githubusercontent.com/117318292/201139424-e30c77ba-be85-48b3-bbd0-402a1f9e4cc1.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-10 17:06
ok lets debug then. 

1. Can you please identify an environment that appears to have the incorrect number of solutions, and then trigger it to run 

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. Once you have this run open see what is returned here. Is it the correct number that you expect? 
![image](https://user-images.githubusercontent.com/89584709/201160545-a34da41a-0138-4d54-b80d-878e6d9a2762.png)

**Comment by Gmejia706** [comment] 2022-11-10 17:56
yes, this manual trigger brought down the correct number for one of my environments. 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/117318292/201170944-5503d5dd-ff12-4f5a-8266-358a1436a58c.png">

**Comment by Jenefer-Monroe** [comment] 2022-11-10 17:59
Is this one of the environments that was showing incorrectly?

**Comment by Gmejia706** [comment] 2022-11-10 18:01
Correct. Yesterday it was showing 31 solutions, this morning it was showing 279 solutions.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 18:05
ok can you please go to http://flow.microsoft.com/ > your Coe envt > Find this flow > edit columns > add environment name > All runs
![image](https://user-images.githubusercontent.com/89584709/201172515-c88a695d-361e-4d3c-a7a0-392459f8a534.png)

And then find the flow for this environment from this morning / last night
We'll want to see it loading up those 279 solutions.

**Comment by Gmejia706** [comment] 2022-11-10 18:27
Here's the run for the same environment last night. As you can see it started at 12:10 and ended within 3 minutes. 

![image](https://user-images.githubusercontent.com/117318292/201175912-bfb09a93-027e-47eb-b595-7b5193215c1a.png)

It also continued to maintain 31 solutions. 

![image](https://user-images.githubusercontent.com/117318292/201176136-ec1b3a7d-f6b8-4ce2-9cf1-bbe67ebbb494.png)

I believe the 31 solutions gets overwritten when the scheduled flow "Admin | Sync Template v3" completes. If you look below the scheduled flow kicked off at 11:39AM and didn't finish until 12:17AM. indicating that changes were made after the solutions flow was ran. 

![image](https://user-images.githubusercontent.com/117318292/201176565-1e91701c-92fb-4988-b36f-5b5aa5702c65.png)

Similar to right now, the number of solutions is displaying correctly but tomorrow morning it will change once again.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 18:51
The length of time Sync Template v3 runs has to do with a delay we add for service health. It completing after this flow completes does not indicate any issues in and of itself. 

It just means that it updated this target environment (envt A) and then continued to update while this flow (solutions for envt A) quickly completed.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 18:53
I'm really at a loss here. Can I summarize what is the facts at play? 

1. You have confirmed that the identity running the flows has the Power Platform Admin role permanently assigned
2. You upgraded to Nov 2022 release last week
3. You have a target environment which shows the correct number of solutions some runs, and way too many solutions other runs
4. You cannot find any instance of the flow returning too many solutions.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 18:56
When did the following two flows last run? I wonder if it was just that the issues had not yet been cleaned up

- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Gmejia706** [comment] 2022-11-10 19:03
1. You have confirmed that the identity running the flows has the Power Platform Admin role permanently assigned
_-Confirm service account running flows has the Power Platform Admin Role_
2. You upgraded to Nov 2022 release last week
_-Confirmed I upgraded to the latest November release version 3.56_
3. You have a target environment which shows the correct number of solutions some runs, and way too many solutions other runs
_-I have a target environment that which shows the correct number of solutions some runs, and way too many solutions other runs_
4. You cannot find any instance of the flow returning too many solutions.
_-I cannot find any instance of the flow returning too many solutions._ 

CLEANUP - Admin | Sync Template v3 (Delete Bad Data) Last Run
![image](https://user-images.githubusercontent.com/117318292/201183285-772de43b-4513-4f6b-9b61-485cd3416a48.png)

CLEANUP - Admin | Sync Template v3 (Check Deleted) Last Run
![image](https://user-images.githubusercontent.com/117318292/201183592-c96abc31-430c-48ba-8ffc-29b5cabd962e.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-11 00:00
That failure in Check Delete should be investigated but its not likely the cause here.

Go to the table, add and filter the column shown to Does not contain data. Are there records like this? 
![image](https://user-images.githubusercontent.com/89584709/201231110-512e5556-867f-43ec-b9e8-b37a30f93fb5.png)
![image](https://user-images.githubusercontent.com/89584709/201231156-696e637a-4120-41e8-b41f-cf7bcea9505d.png)

**Comment by Gmejia706** [comment] 2022-11-11 15:15
Here's a screenshow of the requested table. 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/117318292/201369273-7f8ceb2c-3d6f-44a2-a15e-77a4091ba5ff.png">


I want to note that this morning the solutions are captured accurately in the COE report.

**Comment by Jenefer-Monroe** [comment] 2022-11-11 15:28
ok something went wrong with your cleanup. All those ones without anything in the table should be deleted. 
Can you please delete those from the inventory from here in this table?

**Comment by Gmejia706** [comment] 2022-11-11 15:33
Just to confirm, it says I have 954 rows that contain no data. I should delete the rows within this filtered table?

<img width="784" alt="image" src="https://user-images.githubusercontent.com/117318292/201373072-a47bceb7-fbe9-47b3-87fb-1a5a14383262.png">

**Comment by Jenefer-Monroe** [comment] 2022-11-11 15:35
Correct, there is no data loss here. All you are doing is removing these from the inventory.

**Comment by Gmejia706** [comment] 2022-11-11 16:00
All filtered data has been deleted.

**Comment by Jenefer-Monroe** [comment] 2022-11-11 16:17
ok now we'll see if this issue comes back. 
First, please quickly go validate that everything is on and without unmanaged layers in the inventory suite. This can be done in the Admin - Command Center
![image](https://user-images.githubusercontent.com/89584709/201383805-bce23c6e-18d7-46a4-a241-75f0527e4eae.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-21 17:54
any update here? has this come back?

**Comment by Gmejia706** [comment] 2022-11-21 18:28
Jenefer,

Apologies for the delayed response. I believe my issue has now been resolved.

Thanks,

Gabriel Mejia
Azure Engineer
Heico Companies - PMO
Phone: 470-249-6081
Email: ***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment] 2022-11-21 18:33
oh wonderful news. Thank you! I'll go ahead and close this out then.

**Closed by Jenefer-Monroe** 2022-11-21 18:33 UTC
Labels: question, coe-starter-kit
