### ISSUE TITLE
[CoE Starter Kit - BUG] App Sharing info and App Launching info missing

### ISSUE THREAD

**Issue by azuindow** [microsoft/coe-starter-kit#4064] opened 2022-10-28 04:01 UTC
### Describe the issue

We deployed CoE toolkit Env for Power Platform Governance,  and we are trying to use it to track Env/Apps/Flows usage. 

We created Apps in an Env, and shared them with users and users loaded the Apps, but from CoE – Power Platform Admin view, and CoE Dashboard, the sharing information and Apps launching info all missed even 2 days.

**The simple Test Case for reference**:
Create an Environment with Personal Account (Power Platform Admin) , steps as below:
1. AuditValidateEnv1, Assign the functional Account(For CoE Connections and Setup) as System Admin 
2. Create App AppAV1SharedOne, Shared to two User UserA and UserB
3. Ask UserA to launch the App
4. Create App AppAV1NotShared

**Expectation**:
1.	The Envs data includes Envs, Apps, Sharing Users, Launch Apps should populated in the 2nd day’s dashboard.

**Result**
1.	We saw only basic info for AuditValidateEnv1 with Apps, but no Sharing info also no Launching info.

### Expected Behavior

The Envs data includes Envs, Apps, Sharing Users, Launch Apps should populated in the 2nd day’s dashboard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Aug and Sep releases

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Apps)

### Steps To Reproduce

Create an Environment with Personal Account (Power Platform Admin) , steps as below:
1. AuditValidateEnv1, Assign the functional Account(For CoE Connections and Setup) as System Admin 
2. Create App AppAV1SharedOne, Shared to two User UserA and UserB
3. Ask UserA to launch the App
4. Create App AppAV1NotShared

**Comment by manuelap-msft** [comment] 2022-10-28 14:20
App Launch information is collected by the Audit Log - have you set that up and are the flows running?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

App Shared With information is collected by the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) on a regular basis (weekly) so not immediate. Check that the flow is turned on and running, you can kick it off manually to check if it's working.

Overall, everything in the CoE kit runs on a schedule so changes in the platform are never immediately / real time reflected in the CoE kit.

**Comment by azuindow** [comment] 2022-10-31 01:29
Thanks Manuela for the response.

Yes, we do have Audit Log solution deployed and flows turned on, though we found that there are lots of alert email received: "CoE Audit Logs - Missing some logs - require smaller chunks", will need to reduce the chunk from 1 Hour to 15 minutes and see how it goes.

Flow "CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)" was turned on long time for few weeks already, will need to read into the flow and understand why the data not loaded as expected.

**Comment by azuindow** [comment] 2022-10-31 12:56
Hey @manuelap-msft , I tried reduce the chunks from 1hour x 24/day to 0.25 hour x 96/day, but still got 96 alert emails (100%)  and it says 
```
You will need to use a smaller interval to gather all logs.
Current chunking size: 15 Minute
```
So few more questions:
1. Is there a way to filter out the audit logs for Microsoft Teams Env?  They are created by SYSTEM instead of our Powerr Platform Admin and most of Envs, don't think we need to audit those envs.
2. If i reduce the chunk from 1 hour to 15 minutes to even smaller such as 3 or 5 minutes, what's the impacting will be? 
3. Does an alert email means that all the data in that Child Audit Log flow actually all lost Or at least the data in the first query page is persisted?

Thanks a million anyway!

**Comment by Jenefer-Monroe** [comment] 2022-10-31 14:51
I have seen people go down to 1 minute chunks, typically that gets people most if not all of their logs. The alert means that you got some but not all logs, so its not all or nothing. 

We don't have a way to filter our the logs in a more reasonable way unfortunately via this endpoint. The real answer is going to be using the [self-service analytics](https://docs.microsoft.com/power-platform/admin/self-service-analytics) (aka Bring your own Datalake) which will write out the launches more reliably. We are working to integrate this with the CoE Starter Kit features now. 

Hope that helps/

**Comment by azuindow** [comment] 2022-11-01 09:04
Hey @manuelap-msft , your answer is a great help, really appreciate it.

I reduced the chunk window to 2 minutes (was 15) , this time I got only 2 alert emails.(was 96,  100%). 

Well, there are two more questions: 
**1. Is there a competition between Two CoE Toolkit setup ?**
Say we have two CoE Toolkit setup in two different environments, I found that in the two environments, the launching events for same app and same user and same time window, an event either shows in production or in test env, there is no same audit log showed in the two environment both. Is that expected, or maybe I need read larger data sample?
BTW, we setup the two environments with a same account, is that the root cause?


**2. If a flow run into failure or terminated manually,  will the data pulled again in next run or it will be lost forever?**
Or maybe different for Core Component flows (Inventory data) and Audit Logs Flows?
For Audit log flows, i guess that if a flow run into failure, or only grab the first page's data, then those lost data won't be touch any more next day, since audit log flow only pull last 24 hours data.
How about Inventory data flows? is there an consistency design for the data loading? 

Let me know if i need to start another thread for such kind of discussion. Thanks.

**Comment by manuelap-msft** [comment] 2022-11-01 09:48
1. It's a little hard to know what the root cause could be, however a user has certain limitations on daily executions based on their performance profile (https://learn.microsoft.com/en-us/power-automate/limits-and-config). This is based on the user, not on the flow. So this can have an impact on flows that process a lot of data (like the Audit log flows) as the user account may get throttled or run out of executions and that can cause inconsistent data to come through. Mid-term, instead of using a flow to collect Audit Log data, we are looking at integrating the CoE kit with the Data Export feature https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics - the development for this is already in progress. 

2. Correct. For Audit Logs if the flow stops or doesn't run for a time, the data is lost and not fetched. For inventory, if these flows stop for a while and then start again, they would fetch the delta of what happened - so if apps had been created or modified whilst the inventory sync flows were off, they would fetch them when they run again and get your inventory up to date.

**Comment by azuindow** [comment] 2022-11-04 11:48
Hey @Jenefer-Monroe, hope you are doing well. really appreciate your effort on this thread. the previous answers are very helpful!

There are couple of more questions (or concern): 

1. There is no audit logs for an environment if that environment is audit disabled, right? I think the answer is yes, but please help confirm. since most of our environments were created and managed by Teams, which are auidt disabled by default.

2. The total amount of audit logs will be impacted by chunk size(TimeInterval-Interval), a bigger chunk size means less Power Platform audit log loaded into CoE dataverse since only the data in first page be proceeded.  But the issue is, say we have the chunk size down to one minute, that means there are 24x60=1440 child flows for audit logs retrieving daily,  plus daily Inventory flows, that's a lot. but if we set the chunk size to 2 or 5 mintues, we got many alert emails about reducing chunk size, which means many audit logs missing.

4. About the performance Profile of the the account's license, somehow i didn't find a exactly number of daily flows running limitation, my license is "Power Apps per user plan". which is "Medium", so the daily running limitation is hundreds, or thousand a day? is there a way to check how much flows loaded today and how much left? or is there an alert say "hey, your today's flow running capacity is empty, try again next day" ?

5. The ContentDetails reteived by condition `Audit.General` bfing huge of noises (not for Power Platform audit), so most of the Child flow actually run meaningless and did't proceed any log since it's seek Operation={LaunchApp, DeleteApp, DeleteFlow, PowerAppPermissionEdited} only, they did nothing but just consume the daily capacity of flows running, other than Audit.General, is there another option to retrieve just Power Platform audit logs?

6. The Primary Column of AuditLog table is "Title" = "Power App Launch $AppName - $CreationTime", for example "Power App Launch 4490cd3e-28ea-4fc7-800f-5f696ca10ee7 - 2022-11-03T12:28:35", but if there is multiple running for the same app at that second, how that case be handled?

7. We know that Inventory -> Power Share Apps info queried for each two weeks, is there an issue in the two reports in Platform Admin View -> App View -> "APP LAUNCH EVENTS" and "APP SHARED WITH"?  There are launching events for the shared app, but there is no shared info in dataverse yet. Or those two parts are independently?

**Comment by Jenefer-Monroe** [comment] 2022-11-04 16:15
Dataverse Auditing is as separate feature, I dont believe there is an overlap at all. This is just about tracking app launches.

Generally speaking, agree that the way we get audit logs here isn't great, especially for large tenants. Large tenants also suffer from the API counts generally as they can have tens of thousands of objects to look at each day. The solution for large tenants is the https://docs.microsoft.com/power-platform/admin/self-service-analytics (aka Bring your Own Datalake), and we continue to iterate making that ready for release. 
We were not able to make that the Custom Connector more performant in the past and are no longer investing there as we are focused on BYODL where the logs are written by the product itself to the datalake.

When a user's API count gets used up flows get throttled, so what you see is the flows taking longer and longer to run. Unfortunately there isnt much we can do about that, other than work on the BYODL solution, which is the long term solution for us. 

We only consume app launches from the audit logs, we do not consume app sharing from there. Not sure if I misunderstood your question.

Hope that all helps.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 23:40
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-11-10 23:40 UTC
Labels: bug, coe-starter-kit
