### ISSUE TITLE
[CoE Starter Kit - BUG] In Capacity part of the PowerBI DashBoard I am getting blank Environment Names

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1163] opened 2021-09-14 08:29 UTC
### Describe the issue

In the Capacity Pane of the PowerBI Dashboard I am getting Blank Environment Names 
![thumbnail_blankenvironments](https://user-images.githubusercontent.com/8484048/133222997-65f8cbf0-9948-4b9e-940a-b03f08559370.jpg)

### Expected Behavior

I expect all capacities to have an environment name against them

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.70

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

observe the result of the overnight run of the CoE flows.

**Comment by NPrice99** [comment] 2021-09-14 14:19
Hi @manuelap-msft 

No change - 
![image](https://user-images.githubusercontent.com/8484048/133274925-b34514fd-5133-43f4-b6c1-c566d28877a2.png)

Regards

Nigel

**Comment by NPrice99** [comment] 2021-09-14 14:58
HI @manuelap-msft

![image](https://user-images.githubusercontent.com/8484048/133281854-89913c7e-1826-46fb-9a79-12add843ecb4.png)


Regards

Nigel

**Comment by Jenefer-Monroe** [comment] 2021-10-06 13:18
Can you please validate if these are showing in the data itself? Meaning go look at the data in the dataverse itself? 
This will let us know if the problem is with the data or the report.

**Comment by NPrice99** [comment] 2021-10-06 14:31
Hi @Jenefer-Monroe 
I can confirm the data in the column "Environment Name" is blank for about 40 rows

Regards

Nigel

**Comment by mikefactorial** [comment] 2021-11-03 14:37
@NPrice99 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by mikefactorial** 2021-11-03 14:37 UTC
Labels: coe-starter-kit, vnext, core-components
