### ISSUE TITLE
[CoE Starter Kit - BUG] Clean Up and Delete flow not working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3891] opened 2022-10-07 15:09 UTC
### Describe the issue

Cleanup and delete flow not working. We are getting a bad request error. We have verified our account to have the proper permissions to remove resources (Power Platform Admin). 

![image](https://user-images.githubusercontent.com/95443860/194586023-6b4664d0-0bce-4fbd-894f-094fff9b5117.png)

### Expected Behavior

Clean Up and Delete Flow should be deleting resources marked for deletion. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete)

### Steps To Reproduce

1. Turn on Flow
2. Error soon after it.

**Comment by Jenefer-Monroe** [comment] 2022-10-07 15:57
Are these really empty or did you hide their values for privacy?
![image](https://user-images.githubusercontent.com/89584709/194596849-1dcfbd87-1173-40be-a5e4-c1c674976a0a.png)

**Comment by Jenefer-Monroe** [comment] 2022-10-07 16:08
If really empty, then that is bad data. Please go to **_Archive Approval_** Table and see how many records you have with no environment listed. These are all bad and will need deleted.

**Comment by Jenefer-Monroe** [comment] 2022-10-07 16:11
What does it say in the output of the failure?

**Comment by nasilvae** [comment] 2022-10-07 16:16
output: 
![image](https://user-images.githubusercontent.com/95443860/194600227-3d4e6185-a565-4f95-886b-7cc397acbfd5.png)

**Comment by Jenefer-Monroe** [comment] 2022-10-07 16:26
ok yep that means that the app is referenced by something else and hence we cant delete it programatically. 
We have a feature to try and make this more easy to spot but you will need to delete once like this manually.

**Comment by Jenefer-Monroe** [comment] 2022-10-07 16:26
closing out as a dupe of that tracking item

**Closed by Jenefer-Monroe** 2022-10-07 16:26 UTC
Labels: bug, coe-starter-kit

**Comment by nasilvae** [comment] 2022-10-07 17:02
@Jenefer-Monroe do we have a solution for this bug? I am not following.
