### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question on DLP policies and Environment variables for Core Components install

### ISSUE THREAD

**Issue by Dougydoe** [microsoft/coe-starter-kit#2301] opened 2022-03-24 11:21 UTC
### Describe the issue

Hello,

I'm trying to deploy the CoE Core Component zip file into our Test tenancy but it keeps failing for whatever reason. The account I'm using has all the credentials required (Global Admin, Power Automate and Power Apps per user plans) and all the environment variables are in place as well

I'm attaching the error message here. The log file generated after the failure is in XML format which I cannot download  here.

I reached out to Microsoft as we have a support agreement with them but they said CoE issues are outside of their remit. However, the XML file is too verbose and unformatted it was a challenge to use that to troubleshoot. 

Any clues will be helpful

<img width="256" alt="CoE Failure Message" src="https://user-images.githubusercontent.com/47186116/159904886-ab98abd3-a759-43f9-bf8c-2a46fb516b8b.PNG">
 

### Expected Behavior

This literally the beginning to so was expecting to be taken to the next screen where the core component files would have been extracted into the solution

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Core Components zip file

**Comment by Jenefer-Monroe** [comment] 2022-03-24 14:38
Please go to solution history and click on the failure there. Usually there are clues in the Details + More Details. 
![image](https://user-images.githubusercontent.com/89584709/159940100-ce857111-7a84-4d6f-9685-dd6e1d623e76.png)

**Comment by Dougydoe** [comment] 2022-03-24 15:17
Hi Jenefer,

Thank you for the lead.  I think the complaint was about the Client Secret
ID variable

[image: image.png]
Where do I find that? I thought you generated this after Registering An
Application in Azure AD and creating a client secret.
This is what I used......
[image: image.png]

**Comment by manuelap-msft** [comment] 2022-03-24 15:29
Hi,

if the issue is with the **Command Center - Client Azure Secret**, this is a reference to a secret stored in Azure KeyVault, and not the secret from the App Registration. If you are using that, I would recommend leaving that empty on import and then modifying it afterwards to connect it with an Azure KeyVault. To edit afterwards

> Navigate to make.powerapps.com > Solutions
> Select the Default solution
> Filter to view only environment variables
> Update all secret values:

![image](https://user-images.githubusercontent.com/55705669/159951884-1d5da967-2b93-45c0-8393-bdac50cbf78a.png)

This should work. But it is not mandatory and you can leave it empty if you don't want to store your secret in KeyVault.

Thank you
Manuela

**Comment by Dougydoe** [comment] 2022-03-25 10:32
Hi Manuela,

Sorry to bother you again but seems to be having some issues with turning
some of the flows ON.

When turning the *CLEANUP HELPER - Power Apps User Share With flow*, I
encountered the error mentioned in the documentation so I went to the *Run
only users* section to add the connectors. I was able to turn the flow on
but it keeps going off by itself.

Also, the *Admin | Ad Maker to Group* was also producing the same
error message when attempting to turn it ON. In the details screen for this
flow, the *Run only users* section wasn't present.

In the below, I did apply the connector to all the 4 tools.

Is there something I'm doing wrong or missing here?

[image: image.png]

**Comment by manuelap-msft** [comment] 2022-03-25 11:46
Hello,

unfortunately images don't come through when you reply to GitHub issues via eMail - you will have to open the browser, go to the GitHub issue there and then attach the image here. 

We'll need to see what the error message is in order to help further! Thank you!

**Comment by Dougydoe** [comment] 2022-03-25 12:13
Hi Manuela,

Below is the error message. 

![image](https://user-images.githubusercontent.com/47186116/160118373-610dac1c-a3ef-4a66-849a-0d57ed1674b3.png)

Then I proceed to the **Run only user** section and set the connections as below; Another attempt to turn the flow on will succeed but then it will turn OFF by itself. 

![image](https://user-images.githubusercontent.com/47186116/160118074-02cfd466-30f6-41a8-86e4-2d288689ca1e.png)

Thanks

**Comment by manuelap-msft** [comment] 2022-03-25 12:34
This error message is related to a DLP policy that is applied to your CoE environment, that restricts the use of the Power Apps for Admins connector together with the Office 365 Groups connector.

You will have to update the DLP policy so that all the connectors that the CoE Starter Kit uses can be used together, see our list of connectors and guidance here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by Dougydoe** [comment] 2022-03-25 14:13
Thanks Manuela. So the DLP policy was missing one connector so it worked when I added it to the Business Group.

However, I've run into another issue. I'm at the Stage of setting up the Customer Connector and when I try to click to add a New Connection, nothing happens. It doesn't open up so I can add my account.

![image](https://user-images.githubusercontent.com/47186116/160137354-a5c1e0ee-7ddb-4c45-b9e6-2c49830357e1.png)

**Comment by manuelap-msft** [comment] 2022-03-25 14:27
Hello,

the + New Connection should open a new pop up like this where you can select Create, this will then open the usual login screen to authenticate a connection
![image](https://user-images.githubusercontent.com/55705669/160139653-89ff9c35-ab0e-482d-a0f9-3e728843b2e4.png)

If Create doesn't open a pop up for you, I would recommend closing your browser and re-opening it, checking you don't have any pop up blockers or things like that enabled. If that doesn't work, I'm afraid I don't know what could be causing this and would suggest raising a support ticket with Microsoft https://docs.microsoft.com/en-us/power-platform/admin/get-help-support 

Here on GitHub we can only help you with issues and questions specific to the CoE starter kit, but authenticating custom connectors is a platform capability where if that doesn't work for you, you'll have to raise it with support.

**Comment by Dougydoe** [comment] 2022-03-25 15:12
Thanks Manuela. I didn't have to close the browser. I just did a refresh a couple of times an it picked it up.

**Comment by manuelap-msft** [comment] 2022-03-25 15:13
Thanks for confirming, I'll close this issue now. Please raise a new issue if you experience other issues specific to the CoE Starter Kit functionality.

**Closed by manuelap-msft** 2022-03-25 15:13 UTC
Labels: question, coe-starter-kit
