### ISSUE TITLE
ALM Accelerator Test setup - PowerShell exited with code '1'

### ISSUE THREAD

**Issue by sgshameem** [microsoft/coe-starter-kit#5436] opened 2023-05-04 16:43 UTC
### Describe your bug, question or feature ask.

Hi, 

We have plan to implement ALM setup for our project and so followed the hands on lap document to test with trail CRM instances. However we are encountering a issue at the deploy solution stage with Devops job pipeline failing with below error. 

PowerShell exited with code '1'

The job is failing at the Activate Flows step. Initially when I encountered this failure, I noticed that there is a issue with activating the flows but with just warnings like below

**##[warning]Flow could not be activated. Continuing with flow activation until no more flows can be activated. If this is a result of a child flow not being activated before it's parent consider ordering your flows to avoid this message.**

However in the end the below warning with error is shown.

**##[warning]Errors occurred while activating flows. Please review the log for specific errors and verify your deployment configuration settings.
ScriptHalted
##[error]PowerShell exited with code '1'.
Finishing: Activate Flows**

So I went to CONFIGURE DEPLOYMENT SETTINGS (ALM Accelerator Sample solution) and updated the connection reference with office 365 outlook with the correct account. (admin@***.onmicrosoft.com)

After this I ran Commit and Deploy steps again, but this time it again failed with same error but this time after showing as below 

**FaultException`1 - SetState : Setting Activity State in CRM... workflow |=> Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'cat_DecimalEnvironmentVariable'."}}".**

Could you help what is the issue?

![Trail1 Fail](https://user-images.githubusercontent.com/47221026/236265097-6f0987b8-166b-4694-bbb3-04a1b9070c80.PNG)
![Setup1](https://user-images.githubusercontent.com/47221026/236265156-e0fefb7f-3ed0-40eb-94bf-75195a0dfff4.PNG)
![Setup2](https://user-images.githubusercontent.com/47221026/236265235-adab0594-a0bc-4f57-b73b-90859e18d0e2.PNG)
![Trail2 Fail](https://user-images.githubusercontent.com/47221026/236265261-b3c29508-7c20-4290-83e7-7ca557544520.PNG)
![ALMSampleVer](https://user-images.githubusercontent.com/47221026/236265725-e77a2b6e-0310-44ee-8a44-24aeec16402c.PNG)

**Comment by mikefactorial** [comment] 2023-05-04 21:21
@sgshameem this appears to be a duplicate of https://github.com/microsoft/coe-starter-kit/issues/5435. Closing this out.

**Closed by mikefactorial** 2023-05-04 21:21 UTC
Labels: alm-accelerator
