### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unmanaged solution version

### ISSUE THREAD

**Issue by mspo5** [microsoft/coe-starter-kit#7315] opened 2023-12-18 10:14 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Could you please upload the newest version of the CoreComponents for unmanaged solution - November release? 

![version difference](https://github.com/microsoft/coe-starter-kit/assets/151022094/e2f62417-7798-48e1-8bfd-42142b535dc6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2023

### What method are you using to get inventory and telemetry?

None

AB#1813

**Comment by RahulBojji** [comment] 2023-12-18 12:22
@mspo5 looks like in the release messed up the version of the unmanaged solution for the core components. We happen to identify it last week itself. We will try to fix it up for the next release

**Comment by Jenefer-Monroe** [comment] 2024-01-04 13:49
Confirmed that the unmanaged version correctly shipped this time. 
Will go ahead and close, thanks for posting
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f0d699c2-84da-4e2a-9ca0-74f7cfb307c3)

**Comment by Jenefer-Monroe** [comment] 2024-01-04 13:51
Looks like this happened again. Following up with the ALM team

**Comment by manuelap-msft** [comment] 2024-01-04 14:02
Updated with the latest version now https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-January2024/CoEStarterKit-Unmanaged.zip

**Comment by Jenefer-Monroe** [comment] 2024-01-04 14:03
Thank you Manuela! I'll resolve as fixed in Jan release then.

**Closed** 2024-01-04 14:04 UTC
Labels: bug, coe-starter-kit
