### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned objects assigned new owner outside toolkit functionality remain marked orphan?

### ISSUE THREAD

**Issue by PatriciaRAnjos** [microsoft/coe-starter-kit#2297] opened 2022-03-23 13:50 UTC
### Describe the issue

In the Power Platform Admin View app, we are going through the apps that are orphaned.

However, we see some discrepancies between Power Platform Admin View app and Power Platform admin center. 
Power Platform Admin View app defined some apps as Orphaned, but the owner is clearly defined in the Power Platform admin center and has an active account in Azure Active Directory. The No data available message is common among these discrepancy cases.

![image](https://user-images.githubusercontent.com/102228829/159713901-f166e394-f422-4aac-a32d-c6172bcd7fc6.png)

### Expected Behavior

Power Platform Admin View app to have the same owner information as Power Platform admin center and set as not Orphaned since the user account is active in Azure Active Directory. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Open Power Platform Admin View
Go to PowerApps Apps
Click on app
Click on General
Check owner name and App is Orphaned
Check is there is any data on App Shared with (List) and App Shared with graph
Check if app has an owner in Power Platform admin center
Check if owner account is active in Azure directory

**Comment by Jenefer-Monroe** [comment] 2022-03-23 15:12
It looks like we never added code to recheck an objects as orphaned and assumed that we would be the one changing ownership. 

We'll need to augment the orphan clean up flow.

**Comment by Jenefer-Monroe** [comment] 2022-03-23 16:12
Actually I mis-read your comment. I do need to do the above as well but that woudl be for when App_Owner gets updated or the app owner goes from deleted to not. 

Can you please share a screenshot of this step: **_Check if app has an owner in Power Platform admin center_**

**Comment by PatriciaRAnjos** [comment] 2022-03-24 07:44
I basically go to https://admin.powerplatform.microsoft.com/ and check owner details. 

![image](https://user-images.githubusercontent.com/102228829/159866452-4db2a48a-aa22-4225-aba6-111e189435c7.png)

**Comment by PatriciaRAnjos** [comment] 2022-03-24 14:00
I can confirm that it is running with no errors.

**Comment by Jenefer-Monroe** [comment] 2022-03-24 14:08
Well I guess it could be the original issue I mentioned (now fixed with https://github.com/microsoft/coe-starter-kit/issues/2304) 

Please do a [full inventory run](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) and validate that this fixes the issue for you.

**Comment by Jenefer-Monroe** [comment] 2022-03-29 14:09
A full inventory run should fix this. It should have no context of the app ever having been orphaned at that point. 

Questions
1) How was the new owner assigned for some / all of these apps (if you know). 
2) Did you turn the flows in core off and back on when you set the full inventory env var? Flows cache env vars and so you need to do this for them to get the value
3) Are there failures in the (Apps) sync flow that would mean the app isnt getting updated in the inventory?

**Comment by Jenefer-Monroe** [comment] 2022-03-31 14:41
Alright I'm afraid you will need to find a repro then and trace it through the (Apps) sync flow as this is not expected behavior nor a behavior that I can repro. 

Please do the following to trace your repro

1) modify an app
Take one of the repro apps that is incorrectly showing as orphan and edit it
Note that if you are still in the full inventory you can skip this step

2) trigger inventory 
To make it easier, let's just trigger for your target environment
Go to the Power Platform Admin View app > Environments > Find the environment for your target app from step 1
Audit tab > add some test text the business justification field and save 
(note you will want to remove this later) 
![image](https://user-images.githubusercontent.com/89584709/161076785-090894de-414e-404d-a83d-73336834988a.png)

3) watch the apps sync flow
Go to the Admin | Sync Template v3 (Apps) flow and hit the little refresh button until you see your triggered run. click the timestamp to open it
![image](https://user-images.githubusercontent.com/89584709/161077139-08d6f65e-2447-4015-b047-df263b992637.png)

4) find your app in the run
Find your app in the output of these steps, to ensure it got past these gates
**From load Arrays scope**
![image](https://user-images.githubusercontent.com/89584709/161078062-d35bceef-36f8-4b30-8afb-941b3223bcb9.png)
![image](https://user-images.githubusercontent.com/89584709/161078182-12ba63ad-1f34-4115-923a-f0cad2cc9594.png)

5) Find it in the Edit scope
In the apply to each editted loop, find your app. I've shown one way to find it here
![image](https://user-images.githubusercontent.com/89584709/161078887-3d1798e7-0e65-4420-be3f-18b327340b35.png)

6) See what it enters
Once you find the app, see what values it puts in Dataverse via the **_Update App record Editted_** action in the **_Update App Details Editted_** scope for the following fields
App is Orphaned
App Owner (Value)
App Owner Display Name

![image](https://user-images.githubusercontent.com/89584709/161081818-364f4eae-a85d-4fe2-bc84-89f128a2d484.png)

**Comment by Jenefer-Monroe** [comment] 2022-04-06 16:09
closing out as no further action for starter kit team

**Comment by PatriciaRAnjos** [comment] 2022-04-07 07:15
Hi,
I did as you described. I selected an app with an existing user as owner but set as orphan.

It still defined the app as orphaned on the flow. 

![image](https://user-images.githubusercontent.com/102228829/162141165-f7ac9a66-cf6c-4009-8f0e-4ce5f9a585e1.png)
![image](https://user-images.githubusercontent.com/102228829/162141569-777dc6a2-24f7-42ff-a1b3-6353d68e940b.png)

**Comment by Jenefer-Monroe** [comment] 2022-04-14 16:26
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-04-14 16:26 UTC
Labels: bug, coe-starter-kit
