### ISSUE TITLE
[CoE Starter Kit - BUG] Error Loading Control in Configured Shared Policies (Environment Request App)

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#8283] opened 2024-05-15 23:42 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Please see attached for the following error in "Configured Shared Policies" section of the Environment Request App. Please investigate. Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Environment Request App

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![error1](https://github.com/microsoft/coe-starter-kit/assets/149435271/015e3893-2fb1-4a14-b11b-de2b60b0f651)
![error1](https://github.com/microsoft/coe-starter-kit/assets/149435271/59187973-2c29-4ea5-9f53-89e1fb642631)

AB#3257

**Comment by Jenefer-Monroe** [comment] 2024-05-16 13:58
to area owner for investigation.

**Comment by gulzarudheen** [comment] 2024-06-24 11:52
Duplicate of #7403

**Closed** 2024-07-08 06:10 UTC
Labels: bug, coe-starter-kit
