### ISSUE TITLE
Audit Logs in Power Platform Admin View App does not reflect User UPN

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/coe-starter-kit#2814] opened 2022-05-23 16:45 UTC
### What is your question?

Audit logs in Power Platform Admin View App does not reflect User UPN

![image](https://user-images.githubusercontent.com/69908205/169867803-d445ff37-85c7-4dfc-92e8-8bf0c88737ba.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.34

**Comment by Jenefer-Monroe** [comment] 2022-05-23 16:52
Hello there was a change in the data source for our audit logs and so we had to shift the field we used. You will need to upgrade to the last version of the kit to get this working again.

Duplicate of #2665

**Closed by Jenefer-Monroe** 2022-05-23 16:52 UTC
Labels: question, coe-starter-kit
