### ISSUE TITLE
[ALM Accelerator - BUG]: Deployment settings are not exported

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#1818] opened 2022-01-21 13:21 UTC
### Describe the issue

Suddently, the export pipeline(s) started to throw the following warning:

```
2022-01-21T10:38:08.3590689Z ##[section]Starting: Update Deployment Settings
2022-01-21T10:38:08.3701532Z ==============================================================================
2022-01-21T10:38:08.3701851Z Task         : PowerShell
2022-01-21T10:38:08.3702132Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2022-01-21T10:38:08.3702390Z Version      : 2.194.0
2022-01-21T10:38:08.3702618Z Author       : Microsoft Corporation
2022-01-21T10:38:08.3702938Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2022-01-21T10:38:08.3703289Z ==============================================================================
2022-01-21T10:38:10.0125589Z Generating script.
2022-01-21T10:38:10.0579337Z ========================== Starting Command Output ===========================
2022-01-21T10:38:10.0816406Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\8878be59-58e2-4d7a-96e3-62416af19758.ps1'"
2022-01-21T10:38:15.5468237Z 0
2022-01-21T10:38:15.5484138Z 0
2022-01-21T10:38:15.6550684Z 1
2022-01-21T10:38:15.6551330Z 2
2022-01-21T10:38:15.6552021Z 0
2022-01-21T10:38:15.7395449Z 3
2022-01-21T10:38:15.7396321Z 4
2022-01-21T10:38:15.7396906Z 0
2022-01-21T10:38:15.9467532Z 5
2022-01-21T10:38:15.9468553Z 0
2022-01-21T10:38:15.9470008Z 6
2022-01-21T10:38:15.9470780Z 0
2022-01-21T10:38:15.9472919Z 7
2022-01-21T10:38:15.9473685Z 8
2022-01-21T10:38:15.9474418Z 0
2022-01-21T10:38:17.7143113Z ##[warning]Invalid JSON was supplied for parameter configurationData.
2022-01-21T10:38:21.7103488Z ##[section]Finishing: Update Deployment Settings
```
It started as an issue on some of the solutions and I had the idea that it was related to bad characters in the environment variables, but now all solutions.

We have both the latest and older export pipelines running, and it breaks on all of them, it seems.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

726dcade25a9ce8cecff787e86c3ed52d4dc4f8a

**Comment by mikefactorial** [comment] 2022-01-22 14:10
@mdpc-nnit Per your response in #1794 EnvironmentName should always have a value. It will be the deployment profile id for the selected solution. It seems like something is out of sync between the app and the pipeline if you're not seeing a value in the EnvironmentName. Assuming you have selected a profile for the solution in the app, could this just be an app caching issue? Maybe it's as simple as trying an in private window or Ctrl+F5 with the app open?

The code that calls the export pipeline with the EnvironmentName is here https://github.com/microsoft/coe-starter-kit/blob/78bcc9607b0c1a13699f4b9d6d278101c2f1a920/CenterofExcellenceALMAccelerator/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/Home.fx.yaml#L1963

**Comment by mikefactorial** [comment] 2022-01-24 14:01
Scratch that last part. The empty array for data would be an issue as well, but doesn't explain why neither of those values are being populated. You can see how the data variable is built in the app here https://github.com/microsoft/coe-starter-kit/blob/78bcc9607b0c1a13699f4b9d6d278101c2f1a920/CenterofExcellenceALMAccelerator/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/Home.fx.yaml#L1925

**Comment by mdpc-nnit** [comment] 2022-01-24 16:20
Hm, I think I found the error: I did not configure the deployment profile properly, and the urls where not present... it seems to work after I corrected that. Could that be the cause?

However, I still don't understand why the old app with old pipelines stopped working.

I will look a bit more into this.

**Comment by mdpc-nnit** [comment] 2022-01-24 18:16
So I am doing some digging now, and I found an export from November, where the EnvironmentName was still undefined, but the JSON warning didn't occur. Back then, the try-catch looked like this:
```
        #The configuration data will point to the records in Dataverse that store the JSON to set pipeline variables. Try/Catch for invalid json
        try
        {
            $configCriterias = ConvertFrom-Json '${{parameters.configurationData}}'
            $settingsConn = Get-CrmConnection -ConnectionString "$(CdsBaseConnectionString)$($configCriterias.EnvironmentUrl)"
            #Add the cat_usersetting records to an array
            foreach($configCriteria in $configCriterias.UserSettingId) {
                $userSetting = Get-CrmRecord -conn $settingsConn -EntityLogicalName cat_usersetting -Id $configCriteria.cat_usersettingid -Fields cat_data
                $newConfigurationData.Add($userSetting)
            }
        }
        catch
        {
            Write-Host "##vso[task.logissue type=warning]Invalid JSON was supplied for parameter configurationData."
        }
```
I don't think we ever had an issue with them not exporting before recently, even though it seems that EnvironmentName was undefined... Does this give you any clue on what is going on?

**Comment by mdpc-nnit** [comment] 2022-01-24 19:17
We have 3 scenarios:

- New pipelines, new app: seems to work after I corrected the URLs
- Old pipelines, old app: suddenly stopped working in December
- New pipelines, old app: also doesn't seem to work anymore

Maybe this can help narrow it down?

**Comment by mikefactorial** [comment] 2022-01-24 20:15
@mdpc-nnit the EnvironmentName wasn't being used in the previous releases for the export pipeline we decided to repurpose this variable for passing in the profile id on the export pipeline. May be a little confusing but was done for expedience and will likely be moved to its own variable in a future release. So, it's expected that in the previous versions that EnvironmentName was undefined.

For the specific scenarios.
1. This is good news. To my earlier question are you seeing data in EnvironmentName and Data variables populated in the export pipeline now? If so, I'll have to dig into why the environment url would have caused that. I'll try to replicate that on my end if you can confirm.
2. When you say the old pipelines / old app stopped working are you referring specifically to exporting the settings? Was there any error associated with this or it simply did not update the variables as expected?
3 and 4. A lot has changed with respect to how the pipelines and the app communicate the details of an export request. I wouldn't expect either configuration to work (i.e. new pipelines with old app or old pipelines with new app) 

Just as background the value passed into the Data variable in the export pipeline is a list of user setting records that contain the deployment configuration json. You can see those records in the admin app under Settings if you need to dig into the details

![image](https://user-images.githubusercontent.com/42348035/150857677-15b07f95-862e-471a-acdb-0fc879781759.png)

**Comment by gillesmeyer** [comment] 2022-01-26 16:12
I got the same error as the one reported by @mdpc-nnit. 

I noticed something strange when I look at queue time variables used by `export-solution-to-git` pipeline:

```
Data : [{"EnvironmentUrl":"https://xxxxx.crm4.dynamics.com/""UserSettingId":[{"cat_usersettingid":"3ef28533-ab7e-ec11-8d20-000d3ab3280c"},{"cat_usersettingid":"e4407b4c-ab7e-ec11-8d20-000d3ab3280c"},{"cat_usersettingid":"e787c368-ab7e-ec11-8d20-000d3ab3280c"}]}]
```

There seems to be a _comma missing_ between the two record fields in the JSON (EnvironmentUrl and UserSettingId).

That said, the corresponding request payload posted by the app is the following

```
value: "[{\"EnvironmentUrl\":\"https://xxxxx.crm4.dynamics.com/\",\"UserSettingId\":[{\"cat_usersettingid\":\"3ef28533-ab7e-ec11-8d20-000d3ab3280c\"},{\"cat_usersettingid\":\"e4407b4c-ab7e-ec11-8d20-000d3ab3280c\"},{\"cat_usersettingid\":\"e787c368-ab7e-ec11-8d20-000d3ab3280c\"}]}]"
```
and looks good to me.

**Comment by mikefactorial** [comment] 2022-01-26 19:13
Thanks for the details @gillesmeyer. Let me see if I can replicate this on my end. I do think I've seen what you've pointed out previously.

**Comment by mdpc-nnit** [comment] 2022-01-26 20:19
Hi mike,

1. Data and EnvironmentName are populated now.
2.  No error, simply the invalid json warning and no pipeline variables were updated. I think it was introduced in December and is probably caused by some breaking changes in preparation for the January release. We are addressing the issue by rolling forward to the January release.

**Comment by mikefactorial** [comment] 2022-01-28 13:33
@mdpc-nnit I could use some assistance with replicating this. I can see the issue that @gillesmeyer reported with the json in the data parameter looking ill-formatted, but oddly it doesn't throw the error in my pipeline and appears to parse the json and set the variables on the pipeline appropriately. 

If someone is willing to assist with a repro (e.g. a sample solution and a copy of the user settings records that can be found under the settings in the Admin app) I can try and run the same in my environment to see if I can reproduce.
![image](https://user-images.githubusercontent.com/42348035/151555700-023249c1-e480-4310-b5d9-50ffd6f9c86a.png)

**Comment by mikefactorial** [comment] 2022-01-28 16:57
Can I ask one of you to test the change I made in the update deployment settings in this branch? 
https://github.com/microsoft/coe-alm-accelerator-templates/tree/mochs-aa4pp-1818

Based on @mdpc-nnit comment that the issue was introduced in December I've removed the error handling that we added to the parsing of the configuration data. I'd like to see if that resolves this issue. As I mentioned above, I still don't see the warning although it does look like the json is malformed, but a simple powershell test locally shows that it can successfully parse the json (strange) but only throws the error because we have a try / catch around it. 

This outputs "Error"
```
try
{
$temp = '[{"EnvironmentUrl":"https://foo.crm.dynamics.com/""UserSettingId":[{"cat_usersettingid":"387f924d-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"0afb9153-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"1f6d4f61-1a6f-ec11-8943-00224827e577"}]}]'
$configCriterias = ConvertFrom-Json $temp
echo $configCriterias

} catch
{
echo "Error"

}
```

This succeeds and outputs the parsed object

```
$temp = '[{"EnvironmentUrl":"https://foo.crm.dynamics.com/""UserSettingId":[{"cat_usersettingid":"387f924d-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"0afb9153-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"1f6d4f61-1a6f-ec11-8943-00224827e577"}]}]'
$configCriterias = ConvertFrom-Json $temp
echo $configCriterias

```

I would like to get to the bottom of how the json gets into the state it's in, but as a workaround hope you can validate this change.

**Comment by mdpc-nnit** [comment] 2022-01-31 15:00
Hi @mikefactorial

Sorry, haven't had time to troubleshoot this any further, but regarding your last comment, it still throws an error, when I run your last command:
```
$temp = '[{"EnvironmentUrl":"https://foo.crm.dynamics.com/""UserSettingId":[{"cat_usersettingid":"387f924d-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"0afb9153-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"1f6d4f61-1a6f-ec11-8943-00224827e577"}]}]'
$configCriterias = ConvertFrom-Json $temp
echo $configCriterias
```
I have tried both on pwsh 7 and pwsh 5.1, and the error is fixed by adding the missing comma.

So for me, the missing comma is the problem and not the error handling.

**Comment by mikefactorial** [comment] 2022-01-31 15:58
Beginning to think the output in the queue time variables is a red herring, but still can't be sure since I'm not seeing the same behavior in the pipeline.

I can see the ill-formatted json in the queue time variables

```
Data : [{"EnvironmentUrl":"https://foo.crm.dynamics.com/""UserSettingId":[{"cat_usersettingid":"387f924d-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"0afb9153-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"1f6d4f61-1a6f-ec11-8943-00224827e577"},{"cat_usersettingid":"95fa3fa1-7f80-ec11-8d21-0022482cf654"}]}]
```

However, if I pipe out the value in the update deployment settings powershell I see it formatted correctly.
```
[{"EnvironmentUrl":"https://foo.crm.dynamics.com/","UserSettingId":[{"cat_usersettingid":"387f924d-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"0afb9153-1a6f-ec11-8943-00224825531e"},{"cat_usersettingid":"1f6d4f61-1a6f-ec11-8943-00224827e577"},{"cat_usersettingid":"95fa3fa1-7f80-ec11-8d21-0022482cf654"}]}]
```

I've added logging to the update deployment settings in https://github.com/microsoft/coe-alm-accelerator-templates/blob/mochs-aa4pp-1818/Pipelines/Templates/update-deployment-settings.yml. 

@mdpc-nnit If you have time would be great to see what you are seeing when running the export with the added logging and updated pipeline.

**Comment by gillesmeyer** [comment] 2022-02-01 07:26
Hi @mikefactorial,

Thank you for following up on this :)

I also believe the output of AzDO console is misleading here and probably not interesting.

1. Both code snippets you provided throw an error (same observation as @mdpc-nnit)
2. I tried inlining both JSON objects (ill-formatted and correct) in the build script, only the correct one succeeded
3. After I saw #1827, I reviewed permissions (all were correctly set) but also fixed deployment settings config (not all deployement steps had a valid URL because I was not using them), the pipeline went green and the warning went away.

I suspect the JSON has been fine all along but the catch block triggered because of something else related to 'GetCrm-' calls.

I would also think the try-catch block is not so helpful and could actually hide the actual root cause in this case.

**Comment by mikefactorial** [comment] 2022-02-03 21:00
@gillesmeyer agree with your points above. For number 3, I'm going to create a separate issue to investigate how to better handle this in the pipelines. There's some fragility here that I'd like to get rid of. Closing this for now. Thank you both for all the feedback and assistance in running this to ground. Feel free to open a new issue if you have any follow up.

**Closed by mikefactorial** 2022-02-03 21:00 UTC
Labels: alm-accelerator
