### ISSUE TITLE
[CoE Starter Kit - Feature]: Replace single quotes (') in Account Names

### ISSUE THREAD

**Issue by Tech-Nikal** [microsoft/coe-starter-kit#3283] opened 2022-07-27 11:37 UTC
### Is your feature request related to a problem? Please describe.

I noticed the 'Admin | Sync Template v3 (Connector Identities)' flow is failing when filtering the rows from the 'Connection Reference Identities' table due to an account name and email containing a single quote (')

### Describe the solution you'd like

Where the expressions are used to populate the account names and email addresses in the Filter Rows, wrap with a replace() expression to eliminate issues where this occurs.

![image](https://user-images.githubusercontent.com/110099187/181236501-da267bce-650d-44ca-a812-65bdac176ee7.png)

**Comment by manuelap-msft** [comment] 2022-07-27 11:52
This will be addressed in the September release, duplicate of #3201

Closing as duplicate.

**Closed by manuelap-msft** 2022-07-27 11:52 UTC
Labels: enhancement, coe-starter-kit
