### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by BUFU95** [microsoft/coe-starter-kit#934] opened 2021-07-28 20:34 UTC
### Describe the issue

Cant publish themes on themes editor 

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.51

### What app or flow are you having the issue with?

Theme editor 

### Anything else?

![image](https://user-images.githubusercontent.com/86802671/127391887-62b35cd1-e345-4437-ad4d-fec19bb271d7.png)
![image](https://user-images.githubusercontent.com/86802671/127392047-4a9ac48b-ecf8-4294-9971-17fee1773a7b.png)

**Comment by mikefactorial** [comment] 2021-08-02 14:16
@BUFU95 we're looking into this issue and will have an update out shortly. A potential workaround is mentioned here #553

**Comment by mikefactorial** [comment] 2021-08-03 14:20
Closing this duplicate of #402

**Closed by mikefactorial** 2021-08-03 14:20 UTC
Labels: theming
