### ISSUE TITLE
[CoE Starter Kit - BUG] Data Export - Deleted Apps/Flows still visible

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#7048] opened 2023-11-08 14:23 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have noticed Apps and Flows that have been deleted for a while are still appearing in the Admin view. we are using DataExport method now. 
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/bdde5e6a-28c8-48c8-8b88-ebc7728846f0)
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/3627d18e-96f8-45c7-bae8-1f74c663e21d)
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/006262e9-d659-40a3-a759-a736c5e1ed42)

the check CLEANUP HELPER - Check Deleted (Canvas Apps) has not ran for a while and looks like it exits at some point

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#759

**Comment by Jenefer-Monroe** [comment] 2023-11-08 14:42
Can you please go see what value you have for this env var? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1c19fb99-0419-4b64-9fa0-6c24668b4b85)

**Comment by tkudya** [comment] 2023-11-08 16:32
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/a67e9f20-8da7-4f2b-9b4a-efc625aae9a2)
please see attached

**Comment by Jenefer-Monroe** [comment] 2023-11-08 16:48
Please go to the most recent run of **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**
Does it go down this path?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b56e7f97-c24f-439e-8e98-ec04c11e630f)

**Comment by tkudya** [comment] 2023-11-08 16:52
yes it does
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/1ffa081e-8c16-43fc-b5e7-5616d64cb0fe)

**Comment by tkudya** [comment] 2023-11-08 16:55
meant to say the child flows are not being triggered to run, for example this has not run for last 28 days
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/a9cf9622-98fe-4e0a-81d2-00330255afd1)

**Comment by tkudya** [comment] 2023-11-08 16:56
Curious, how does it know when a flow has been deleted? is this something done by audit log or by Data Export?

**Comment by Jenefer-Monroe** [comment] 2023-11-08 16:59
Yes I think I misunderstood. I thought it was marked as deleted but not getting cleaned out.
The issue is definately that these flows arent getting triggered
Does the environment still exist? Or was it deleted?

**Comment by tkudya** [comment] 2023-11-08 17:03
the environment still exists "its the default environment" we renamed it last year but since using the Data export the name of the environment has gone back to the old one. 


They are not marked as deleted in the COE but they no longer exists.

**Comment by Jenefer-Monroe** [comment] 2023-11-08 20:17
We detect flows are deleted for data export in this flow : CoE BYODL - When Flow dataflow refresh is complete
It looks for flows that were not "queried today", meaning flows that were not found in the data export file.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b9e37e18-9958-44fb-9d65-d49fb1ac9325)

Here you can see how that is supposed to work, the flow stops being queried and then a few days later gets marked deleted by this flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/59ae28c0-1ce8-45ab-a410-38fda58efb66)

If you look at the **_Flow Queried On_** field for the flows that are supposed to be marked deleted, what do you see?

**Comment by tkudya** [comment] 2023-11-08 22:33
one example is here
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/a635e794-ebbf-4419-a4d7-72e7578d54cb)

**Comment by tkudya** [comment] 2023-11-08 23:01
App:
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/a9d658ac-5630-47e0-859f-a057743a7eb8)

**Comment by Jenefer-Monroe** [comment] 2023-11-10 12:54
### App
For your Canvas App one, it appears that may still be in the Data Export. 
Go to the storage container, find the Applications folder. 
Using the storage browser search for the GUID of the envt this app lives in.
Download the Canvas file and search for "Parts Register App"

**Comment by Jenefer-Monroe** [comment] 2023-11-10 12:56
### Flows
Please check to make sure your Dataflows are all running each day and passing
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/189d035f-cf14-4ec4-9613-5fb2f4c43bc0)

**Comment by tkudya** [comment] 2023-11-13 11:07
For Apps

I have download the JSON file its not in the JSON files anymore. I deleted another App on Friday and it's the same. Its not in the JSON but still exists
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/c16a9437-62e9-4990-867a-bf02bc5a4f91)

For Flows. 

I can see the flow but the user deleted last week and it's in the JSON file. Another one i deleted in the same period is no longer there

**Comment by Jenefer-Monroe** [comment] 2023-11-13 12:12
It looks like you have setup auto-refresh for all the dataflows, it should only be set for Makers as mine shows. 
All other dataflows are driven by power automate flows that run when Makers runs. 
Please get your Next Refresh looking like, only set up for Makers
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/189d035f-cf14-4ec4-9613-5fb2f4c43bc0)

Then go make sure all these flows are on:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/837e37e2-d0b5-40d0-8c96-8d3986a15441)

**Comment by tkudya** [comment] 2023-11-13 13:12
I will make the adjustments and let you know thanks

**Comment by Jenefer-Monroe** [comment] 2023-11-20 11:19
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-11-20 11:19 UTC
Labels: bug, coe-starter-kit
