### ISSUE TITLE
[CoE Starter Kit - just pulls only canvas and model driven apps

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#5218] opened 2023-04-07 14:18 UTC
### What is your question?

1. Dose the Set app permissions app in COE starter kit pulls only the data from Canvas and Model driven apps?
2. It doesn't show up the data of the SharePoint forms, where I can find them?
3. We have huge, orphaned list with 100+ forms, we can get the info from the PBI report but can find in the apps to manage them?
4. How to manage the Orphaned SharePoint form in COE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

**Comment by Jenefer-Monroe** [comment] 2023-04-07 14:26
Hello we do not have a mechanism for managing permissions on SP Forms, that relies on SP permissions and so the technique we used there does not work.

**Comment by Neel1KNK** [comment] 2023-04-07 14:34
Hello Jenefer
Thanks for your response.
If am an admin for both PP and SharePoint and still, I will not be able to manage the SP forms in COE?

The problem is like we are unable to manage them by changing the owners or moving them. Is there any other way in COE?

Thanks in advance.

**Comment by Jenefer-Monroe** [comment] 2023-04-07 14:39
The problem is that we just have not done the tooling, as we are not SP experts we did not know how to do it off the top of our head and then it just has not risen in priority for us to fund investigation. 
So for example, the call to get current permissions from SP, the call to edit permissions in SP, those are all calls we did not integrate with. 
So in our tooling we do not have anything like this to offer unfortunately.

**Comment by Neel1KNK** [comment] 2023-04-07 14:43
Got it Jenefer.
Thanks for the information.
Also, I have one more question which I want to try in my dev tenant, like installation of complete COE doesn't clean up or archive the quarantined/Orphaned apps right?

**Comment by Jenefer-Monroe** [comment] 2023-04-07 14:53
There is an environment variable called Production Environment which when set to no will prevent deletes/quarentines/etc from happening. And will send all mails to the admin persona instead of object owner.

![image](https://user-images.githubusercontent.com/89584709/230629254-3b24fe22-27a5-4b77-9f24-e9f6fefea844.png)

Please let me know if I've misunderstood your question.

**Comment by Neel1KNK** [comment] 2023-04-07 15:02
Ohhh nice, 

So, it applies for only production or all other like sandbox environments or how?

If yes, the app with disrespect to environment, sends mails to admin persona instead of owners >> please correct me if am wrong.

**Comment by Jenefer-Monroe** [comment] 2023-04-07 15:10
It does not matter what type of envt it is from the PP perspective. Its not a Power Platform feature, its a feature of the CoE Starter Kit. Its one of the env variables available to you here:
![image](https://user-images.githubusercontent.com/89584709/230632286-18f7e1ef-baf8-49ec-b340-103b93ff2e29.png)

**Comment by Jenefer-Monroe** [comment] 2023-04-10 14:57
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-04-10 14:57 UTC
Labels: question, coe-starter-kit
