### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Command Center - Message Center

### ISSUE THREAD

**Issue by ThomAstra11** [microsoft/coe-starter-kit#4371] opened 2022-12-07 10:57 UTC
### Describe the issue

at 9th November we did the upgrade to release 3.56 of the CoE. However, since 28th November we face issues in the Admin - Command center with getting the Message Centers information correctly. Since then we see this BadGateway Error Message on top of the Admin - Command Center as well in the corresponding Flow Command Center App > Get M365 Service Messages.

CommandCenterApp>GetM365ServiceMessages.Run failed: { "error": { "code": 502, "source": "europe-002.azure-apim.net", "clientRequestId": "0eb247ea-837d-4ade-8d60-887a4e8174db", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585311966090632676718933078CU146'." } } } }

### Expected Behavior

Usually all new Microsoft Message Center Information are shown in the Admin - Command Center - Message Center.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

**Comment by manuelap-msft** [comment] 2022-12-07 11:17
Hello,

this is a duplicate of #4312. The response of the API we are using in this call has changed and we had to adjust our parsing of the response. This has been fixed locally and will go live with the December release (expected later today).

Thank you for posting,
Manuela

**Comment by ThomAstra11** [comment] 2022-12-07 11:43
Ok. Great. Thanks for letting me know.

**Closed** 2022-12-07 16:09 UTC
Labels: bug, duplicate, coe-starter-kit
