### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture solution fails on import. Dependent workflow missing.

### ISSUE THREAD

**Issue by Pasark** [microsoft/coe-starter-kit#2744] opened 2022-05-17 12:03 UTC
### Describe the issue

Importing the Nurture solution fails with _Solution.SolutionImportProgress.KnownErrors.cannotImportSolution_. The log shows this failure:

_The dependent component Workflow (Id=8a28c32f-dd86-ec11-93b0-000d3a5b2abe) does not exist.  Failure trying to associate it with CanvasApp (Id=14cd4709-85d9-45c3-b162-bd7bc4a844c0) as a dependency. Missing dependency lookup type = PrimaryKeyLookup._

The CanvasApp Id refers to **Power Platform Training Management** in our environment.

[Nurture Solution Import Log.zip](https://github.com/microsoft/coe-starter-kit/files/8707925/Nurture.Solution.Import.Log.zip)
 

### Expected Behavior

The solution succesfully imports.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.11

### What app or flow are you having the issue with?

Power Platform Training Management

### Steps To Reproduce

1. Download solution package
2. Import Nurture solution 2.11
3. Wait

### Anything else?

Solutions already imported:

- CenterofExcellenceCoreComponents
- CenterofExcellenceAuditComponents
- Theming

**Comment by Jenefer-Monroe** [comment] 2022-05-17 12:45
Hello. It looks like the product make a change and added new checks for import. We are tracking with https://github.com/microsoft/coe-starter-kit/issues/2736

Please follow there for resolution. 

Thank you for posting! 
Duplicate of #2736

**Closed by Jenefer-Monroe** 2022-05-17 12:45 UTC
Labels: bug, coe-starter-kit

**Comment by manuelap-msft** [comment] 2022-05-18 15:31
We released a hotfix release to address this issue
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2022-HF1

Please let us know if you continue to face issues, we've done some testing on our end and don't repo anymore!
