### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Admin | Sync Template V3 (Dataverse for Teams) April version failing to grab default environment

### ISSUE THREAD

**Issue by morismm99** [microsoft/coe-starter-kit#2440] opened 2022-04-12 14:31 UTC
### What is your question?

The Admin | Sync Template v3 flow as part of the Core Components for Teams (April version) is failing to grab the default environment and all of its resources. 

Anyone else running into this issue?

It's failing on the "Check if legacy environment condition" right at the Get Environment dataverse action. Error:

  "error": {
    "code": "0x80040217",
    "message": "admin_environment With Id = c2593687-bdd2-40dc-9d37-140efdbbfed3 Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "1d4668b2-c6b5-ec11-9840-000d3a3b3045",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "8000164f-64e6-45d3-9917-edf62c7d27ad",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = c2593687-bdd2-40dc-9d37-140efdbbfed3 Does Not Exist"
  }

### What solution are you experiencing the issue with?

Core Components for Teams

### What solution version are you using?

3.17

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment] 2022-04-12 15:44
Hello. This is known and fixed in Core for Teams 3.18 which is now part of the [https://aka.ms/coestarterkitdownload](https://aka.ms/coestarterkitdownload) package. 

Duplicate of #2421 

Sorry for the inconvenience and thanks for using CoE

**Closed by Jenefer-Monroe** 2022-04-12 15:44 UTC
Labels: question, coe-starter-kit

**Comment by morismm99** [comment] 2022-04-12 16:48
Thanks @Jenefer-Monroe!
