### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Env Request - Can't  resolve GUID that start by default

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8049] opened 2024-04-11 18:49 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, this request is a duplicate. of this trhread https://github.com/microsoft/coe-starter-kit/issues/7403#event-11502428220
I think tag somenone is not working.

So when i click on shared dlp policy i have this error 
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/a3164b9d-055e-4444-a80c-b800d536c6a3)

I edited the app and it seems there is issue from the app to resolve the default environnement GUID

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/069507bd-5895-4842-9555-1a0f541139a3)

How can i fix this ?It's  important for us because actually users still use the old app.

thanks a lot

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

CoE Admin Environment Request (preview)

### What method are you using to get inventory and telemetry?

None

AB#2882

**Comment by Jenefer-Monroe** [comment] 2024-04-11 21:20
To area owner for investigation

**Comment by tocri** [comment] 2024-04-12 12:35
Thank you. I appreciate. Looking forward for updates

**Comment by tocri** [comment] 2024-05-27 19:15
@Jenefer-Monroe I have uodated to the last version. I have always the same error 
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/696a411d-46f2-448b-81ab-6d08c434e751)
 when i click on configured share policy  
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/eaeca006-aaa6-428e-bd1b-89fdebee3306)


Am i the only one with this error ? It's very annoying

**Comment by Jenefer-Monroe** [comment] 2024-05-27 19:30
@gulzarudheen can you please work with this user to understand the issue.

**Comment by tocri** [comment] 2024-06-03 19:18
@gulzarudheen  Sorry to bother you with this but it's very important. I can't resolve this issue by myself or maybe do you know how to change the id of my default environnement without breaking flows and apps that are created by users.

I must communicate on this apps very soon for my end users and i need to create a training video on how to use it

**Comment by Jenefer-Monroe** [comment] 2024-06-05 12:01
I have pinged @gulzarudheen and requested he work with you here.

**Comment by gulzarudheen** [comment] 2024-06-06 11:17
@tocri I have started investigating on it.

**Comment by gulzarudheen** [comment] 2024-06-24 11:52
Duplicate of #7403

**Closed** 2024-07-08 06:10 UTC
Labels: bug, coe-starter-kit
