### ISSUE TITLE
[Question:] What's the best way to upgrade the CoE environment to the latest version

### ISSUE THREAD

**Issue by GandhiAmit** [microsoft/coe-starter-kit#414] opened 2021-05-20 17:12 UTC
We want to upgrade the current CoE version to the latest version. Currently, we have an older version installed which does not include "CoreComponentsTeams". What's the best way to upgrade the CoE environment to the latest version?

Do we need to uninstall everything and reinstall the new CoE version from the ground up again?
Is there any other better process that does not require removing the existing CoE environment?

Currently Installed:
	CenterofExcellenceAuditComponents_1_23_managed
	CenterofExcellenceAuditLogs_1_0_0_17_managed
	CenterofExcellenceCoreComponents_1_70_2_managed
	CenterofExcellenceNurtureComponents_1_17_managed
	CenterOfExcellenceTheming_1_0_0_9_managed
	Dashboard-PowerPlatformAdminDashboard_2020-09-19

We want to upgrade to following versions:
	CenterofExcellenceAuditComponents_1_60_managed
	CenterofExcellenceAuditLogs_1_41_managed
	CenterofExcellenceCoreComponents_2_1_6_managed
	CenterofExcellenceCoreComponentsTeams_1_992_managed
	CenterofExcellenceInnovationBacklog_1_30_managed
	CenterofExcellenceNurtureComponents_1_51_managed
	Dashboard-PowerPlatformAdminDashboard-2021-04-08

**Comment by JeneferM-MSFT** [comment] 2021-05-20 18:04
Hello. You either install the Teams version **OR** the Prod version. You can find more information on chosing here: [prod v teams](https://docs.microsoft.com/power-platform/guidance/coe/setup#production-vs-dataverse-for-teams-environment)

- PROD:   CenterofExcellenceCoreComponents_****_managed
- TEAMS: CenterofExcellenceCoreComponentsTeams_****_managed

If you chose to switch to teams after reading, note that you will need to start from scratch there and follow the setup instructions for [installing in teams](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#option-2-import-the-solution-into-a-dataverse-for-teams-environment)

If you chose to stay in prod, then you will follow the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that with that old of a version you will likely have unmanaged layers on every flow to remove as the install process used to create them. 

Note also that upgrading from this old of a version may also run in to one off issues like this one https://github.com/microsoft/powerapps-tools/issues/515

Hope that helps

**Comment by manuelap-msft** [comment] 2021-05-21 14:14
Duplicate of #374

**Closed by manuelap-msft** 2021-05-21 14:14 UTC
Labels: coe-starter-kit, duplicate, question
