### ISSUE TITLE
[ALM Accelerator - BUG]: Error in commit and deployment

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#8147] opened 2024-04-25 14:48 UTC
### Describe the issue

Hello,

Please, we are implementing ALM here at the company in addition to the CoE, but in the first tests it is showing an error to comment and then an error when we try to implement it for another solution as shown in the attached images.
Can you help us with what this problem could be?

![ALM1](https://github.com/microsoft/coe-starter-kit/assets/129080740/4091d716-10ee-442b-b9b5-24021d87bc09)
![ALM3](https://github.com/microsoft/coe-starter-kit/assets/129080740/b6c71afc-d5c6-4d53-b61d-6454ac7bea10)
![ALM4](https://github.com/microsoft/coe-starter-kit/assets/129080740/c6fa4f51-eefe-44bb-9e93-d35751eaeba4)
![ALM2](https://github.com/microsoft/coe-starter-kit/assets/129080740/2e500420-b865-49f2-ba8f-b6609ec7c512)

### Expected Behavior

What would be expected would be that after committing and deploying, the status would be ok and these errors would not appear in the View Detailed Solution History.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240305.1

AB#3007

**Comment by mikefactorial** [comment] 2024-04-25 23:25
@minobrega the error messages aren't too telling apart from the Pull Request error which specifies that both a source and target are required (meaning a source branch and a target branch). However, since it doesn't look like you ever had a successful commit that would make sense since the creation of the working branch would happen during the commit. 

It would help if you included steps to reproduce in your issue and what steps you followed to get setup (i.e. a reference to the docs you are following) in order to be able to more easily deduce where the problem might be. There are some good resources in the docs that might help https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/learning-resources-catalog

**Comment by mikefactorial** [comment] 2024-04-26 11:17
@minobrega I have a suspicion about what your problem might be. Assuming you set this up using the Project Setup Wizard it looks like there's been some updates in Azure DevOps related to permissions which may be blocking your user from running pipelines. If you go to the project in Azure DevOps and look to see if there are any recent pipeline runs. Particulary, check that the sync-pipeline-repo pipeline has run and also that the template repo has been initialized. If not try running the sync-pipeline-repo pipeline manually with the following options. 

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/e949a584-272b-4608-a07b-463b8c0d9ef9)

**Comment by minobrega** [comment] 2024-04-29 13:33
Hello,

Thanks for your help, I made the change as per the instructions, but after executing it manually it shows the following error.

![ALMerro1](https://github.com/microsoft/coe-starter-kit/assets/129080740/b86b45da-445f-4cce-8267-9f7c45af3eee)

![ALM_erro](https://github.com/microsoft/coe-starter-kit/assets/129080740/89059fc9-4f80-4bb2-8289-82e8960f5fcd)

**Comment by minobrega** [comment] 2024-05-06 13:01
After filling out and receiving a response to the request form to increase free parallelism in Azure DevOps, it now displays the error message as shown in the image below

![ErroALM1](https://github.com/microsoft/coe-starter-kit/assets/129080740/35d93b3f-4513-46b8-9540-5966aa5f9062)

**Comment by mikefactorial** [comment] 2024-05-06 13:42
@minobrega looks to be an issue related to the Build Service's permissions. When you setup a project with the Project Wizard it will setup the permissions for you but if you set up the project manually you need to follow all of the the steps in this guide https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually. For permissions you can see this section https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#set-permissions-for-the-project-build-service

**Comment by minobrega** [comment] 2024-05-08 16:31
Hello,

I did the settings again in Azure DevOps, run the procedure to clone the YAML pipelines from GitHub to the Azure DevOps instance. I have already created a new pipeline, but I am trying to run it manually and the following options appear as shown in the attached image, different from what you sent. Is there any documentation to complete these options correctly?

You advised to manually perform this configuration:

![ALM executar manualmente 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/997c5683-1d8f-423c-aab9-25801c3d0ab4)

When I try to run it manually it appears like this:

![ALM executar manualmente 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/655cbfd9-a0a0-4d51-a57f-35bb7d0d74cf)
![ALM executar manualmente 3](https://github.com/microsoft/coe-starter-kit/assets/129080740/361c3f66-897a-44f1-93b3-55f5c2339fd4)
![ALM executar manualmente 4](https://github.com/microsoft/coe-starter-kit/assets/129080740/0d7c573d-ae6d-4734-86dc-f47d001cafbe)

**Comment by mikefactorial** [comment] 2024-05-09 13:49
@minobrega looks like you're confusing the sync pipeline which pulls down the pipeline templates from GitHub with the pipelines that are created for export, import, delete and deploy. The latter will run when triggered from the ALM Accelerator app. I don't advise trying to run those manually as they take in a lot of parameters that need to be configured in the ALM Accelerator app and aren't intended to be run manually. Assuming you have everything setup now have you tried using the app to export a solution and then deploy?

**Comment by minobrega** [comment] 2024-05-16 12:53
Hi Mike,

Sorry for the delay, I was selling the documentation again, I confess I was a little confused about the PIPELINES. Now I configured the project to create the PIPELINES using ALM itself in PROJECT WIZARD, it created the connections and the PEPILINES automatically, I configured the permissions according to the manual procedure, now the error has changed, when I have to do the COMMIT SOLUTION it shows the error below :

![ALM erro10](https://github.com/microsoft/coe-starter-kit/assets/129080740/9db51c8d-b2e6-444c-98e0-1438c6bae54c)


![ALM Erro11](https://github.com/microsoft/coe-starter-kit/assets/129080740/a1ff32a3-b739-418c-9176-cca9aa9eb376)

**Comment by RajeevPentyala** [comment] 2024-06-10 06:34
@minobrega Closing this issue as you logged a new ticket #8320 with publish customizations issue.

**Closed by RajeevPentyala** 2024-06-10 06:34 UTC
Labels: bug, alm-accelerator
