### ISSUE TITLE
[CoE Starter Kit - QUESTION] Solution inside Environment

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2986] opened 2022-06-13 14:22 UTC
### What is your question?

There is a way to see solution inside differente environment with Coe Toolkit?

Thanks

**Comment by manuelap-msft** [comment] 2022-06-13 14:26
Not at the moment, although this is on our backlog for investigation. Closing as duplicate of #968

**Closed as completed by manuelap-msft** 2022-06-13 14:26 UTC
Labels: duplicate, question, coe-starter-kit
