### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (PVA) - Action 'GetBotID' failed

### ISSUE THREAD

**Issue by phil0074** [microsoft/coe-starter-kit#2657] opened 2022-05-06 20:11 UTC
### Describe the issue

Receiving errors for PVA flow.
![image](https://user-images.githubusercontent.com/41122379/167209897-4cccf084-0d4d-4018-997c-754ae6b70729.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

**Comment by Jenefer-Monroe** [comment] 2022-05-06 20:14
Known and fixed in May release. 
Duplicate of #2402
Thanks for using CoE

**Closed by Jenefer-Monroe** 2022-05-06 20:14 UTC
Labels: bug, coe-starter-kit
