### ISSUE TITLE
[Power Platform Hub] "message":"The error settings already exists for the tenant.

### ISSUE THREAD

**Issue by spannaus26** [microsoft/coe-starter-kit#3897] opened 2022-10-07 21:02 UTC
### Describe your bug, question or feature ask.

![image](https://user-images.githubusercontent.com/53320957/194651881-56223a2a-d425-41d5-92e2-17be0e6b2fe5.png)

Not sure what this error is and how to fix it.

**Comment by spannaus26** [comment] 2022-10-07 21:09
I did test the template by invoking on another site.
Connect-PnPOnline -Url https://tenantname.sharepoint.com/sites/powerplatformhub -Interactive
Invoke-PnPSiteTemplate -Path template.pnp

**Comment by manuelap-msft** [comment] 2022-10-10 10:07
this is a duplicate of #3871 - the script fails if you have already set a Governance error message for your tenant. We're working on a fix which should be ready soon!

**Comment by Laskewitz** [comment] 2022-10-10 13:36
The script is now updated and will update the error settings if they already exist. Link to the script: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/PowerPlatformHub/Set-PowerPlatformHubAsDLPErrorSettings.ps1

Thanks for reporting the issue.

**Closed by Laskewitz** 2022-10-10 13:36 UTC
Labels: duplicate, powerplatformhub
