### ISSUE TITLE
[CoE Starter Kit - BUG] SLAInstanceMonitoringWarningAndExpiryFlow and other flows from default solution - orphan

### ISSUE THREAD

**Issue by larhem** [microsoft/coe-starter-kit#6665] opened 2023-09-19 10:01 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

SLAInstanceMonitoringWarningAndExpiryFlow and other flows from default solutions are now suddenly apperaring as "orphaned flows" in "Set Flow Permissons" for all our environments. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Set Flow Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

run app

**Comment by Jenefer-Monroe** [comment] 2023-09-19 13:31
I believe this would be due to this product change local fixed for Oct. Can you please take a look at the debugging steps described and see if that looks correct?
https://github.com/microsoft/coe-starter-kit/issues/6599

**Comment by larhem** [comment] 2023-09-19 16:33
Im not sure if its the same issue since our "SYNC HELPER - Cloud Flows" is running without any erros the last weeks.

**Comment by Jenefer-Monroe** [comment] 2023-09-19 17:55
Ok, please find a flow you think should not be flagged as orhpan, and run the "SYNC HELPER - Cloud Flows"  flow with it
Since its default envt you should trigger with parameters like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/30abb747-606b-4544-b846-e6d9fb2eaf3c)

**Comment by larhem** [comment] 2023-09-21 12:36
The "SYNC HELPER - Cloud Flows" runs without any problems and flow is still marked as orphaned

**Comment by Jenefer-Monroe** [comment] 2023-09-21 13:05
Please open that run you triggered and see what was returned here. Is there anything at all for Creator? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca8eea57-f6c3-4000-80e6-25febd399db9)

**Comment by larhem** [comment] 2023-09-21 14:31
For the flow SLAInstanceMonitoringWarningAndExpiryFlow there is no "creator" element beeing returned in the output for Get Flow as Admin.

**Comment by Jenefer-Monroe** [comment] 2023-09-21 14:43
thanks for confirming. we seem to have a product regression here.
Can you please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by Jenefer-Monroe** [comment] 2023-09-21 14:53
Also, are you a commercial tenant? Thats the normal type. Or something like GCC?

**Comment by larhem** [comment] 2023-09-21 16:27
Commercial tenant and its the same for both sandbox and production environements in both regions Europe and Norway.

**Comment by Jenefer-Monroe** [comment] 2023-09-22 14:31
It turns out that this was a product regression in a new feature which hadn't gotten to me yet which is why I didn't repro. 

The product team is rolling this back now.

**Comment by Jenefer-Monroe** [comment] 2023-10-09 15:37
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-10-09 15:37 UTC
Labels: bug, coe-starter-kit
