### ISSUE TITLE
[ALM Accelerator - BUG]: Publish solution throw timeout (import solution in ALM accelerator) 

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3533] opened 2022-08-26 19:03 UTC
### Describe the issue

I am getting time out error while importing solution  by using ALM accelerator. The exact step is publishing solution which throws timeout error after 10 minutes . 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Apr 2022

**Comment by devkeydet** [comment] 2022-08-31 09:57
@linujohn22 - This doesn't sound like an issue with the accelerator as much as an issue with the platform.  Unless there are more details I am missing, there's not much we can do in the accelerator to address this.  If there are more details you can provide that lead you to believe this is an accelerator issue, not a platform issue, please do let us know.  We just call the Power Platform Build Tools tasks.  The repo for those tasks is here:
https://github.com/microsoft/powerplatform-build-tools

However, you mention publishing.  We only call the publish customizations task in two scenarios.  

After an unmanaged solution import into a dev environment.
https://github.com/microsoft/coe-alm-accelerator-templates/blob/11ab120a3e76aa0dcad6f984a805cc86cc507d20/Pipelines/Templates/deploy-Solution.yml#L190

Before solution export.
https://github.com/microsoft/coe-alm-accelerator-templates/blob/f783a0e967233cd690b5428e1864e957ddff7860/Pipelines/Templates/export-Solution.yml#L103

Can you clarify in which scenario you are using it?  Because we are considering removing publish customizations from the export pipeline.
https://github.com/microsoft/coe-starter-kit/issues/3554

However, I want to reiterate that, unless can provide us more details that suggests the cause is in the accelerator, there is nothing we can do to fix the publish issue you filed.  Your next step would probably be to file an issue on the Power Platform Build Tools repo:
https://github.com/microsoft/powerplatform-build-tools

However, they might end up telling you they simply call the Dataverse API and your best bet really is to contact support.  To try to save you from jumping around, if there aren't more details you can give us to narrow down to an actual Accelerator issue or that it's an issue in the actual Build Tools task, I would suggest going here:
https://admin.powerplatform.microsoft.com/support
...and using these options:
![image](https://user-images.githubusercontent.com/4499296/187651723-f9545433-8865-4cb6-afb3-3e25508dbe2d.png)

HTH

**Comment by mikefactorial** [comment] 2022-09-01 19:26
Closing out as there's no specific issue related to the Accelerator here.

**Closed by mikefactorial** 2022-09-01 19:26 UTC
Labels: bug, alm-accelerator
