### ISSUE TITLE
[ALM Accelerator - BUG]: Issue in Solution Import with SQL Connections

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#5440] opened 2023-05-05 00:39 UTC
### Describe the issue

We are facing a strange issue with deployment for a solution having SQL Connection.

**First deployment**

Solution contains a simple canvas app with a connection reference that uses SQL Server connection.

The connection is shared with the deployment app user (as share checkbox is checked) with ‘Can Use’ in deployment settings.

Deployment is successful.

**Second Deployment.**

No changes are made in deployment settings.

The deployment fails with error as given below.

The reason given was: CanvasApp import: FAILURE: Code: ConnectionAuthorizationFailed Message: The caller with object id '311b474f-c6ed-42bd-ae15-6d609b598d20' does not have the minimum required permission to perform the requested operation on connection 'ae2f6c05ea2d4d4fabc3a8fc6111e603' under API 'shared_sql'. Client Request Id: ea220f00-db09-4a01-92cb-f5f73dc8662f. 
Microsoft PowerPlatform CLI 

![image](https://user-images.githubusercontent.com/33513504/236357371-60d29ed7-bf37-4050-a93c-d97283995e28.png)

Here the Object ID refers to the deployment app user and the specified connection is already shared with ‘Can Use’ privilege in the previous deployment.

**Deployment 3**

Manually updated the connection share to ‘Can Edit’ for the app user and deployment gets successful.
 
![image](https://user-images.githubusercontent.com/33513504/236357405-8ebf14d7-89ce-40f1-aba1-8de578596f56.png)

**Deployment 4**

The connection share is again updated to ‘Can Use’ as the share check box is checked (maybe).

This leads to deployment failure with same error unless the Share checkbox is unchecked or manually update the connection share to ‘Can Edit’ for the deployment application user.

Could you please check this.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230405.2

**Comment by mikefactorial** [comment] 2023-05-08 12:11
@tomjosbin thanks for reporting this and for the detailed notes. Will take a look at what's happening here.

**Comment by tomjosbin** [comment] 2023-05-08 13:47
Thanks @mikefactorial , additionally, even after bypassing the above errors, after deployment, the app was giving the below error.

![image](https://user-images.githubusercontent.com/33513504/236840319-f16212d5-796f-4cd1-bd6b-b805d1ad31f8.png)

Upon debugging the issue, I have found that the root cause was a preview experimental feature that was turned on in the app settings.

![image](https://user-images.githubusercontent.com/33513504/236840412-8883c06e-c03c-4ba9-86d6-b1b3db3f762f.png)

This was causing the all these issues, after turning it off, the deployment went through with out any errors.

**Comment by mikefactorial** [comment] 2023-05-08 18:55
@tomjosbin thanks for the additional details. I'm not really familiar with that preview feature. Will bring it up with the team internally and try to figure out what the issue is.

**Comment by mikefactorial** [comment] 2023-06-29 21:03
Closing this out as there's nothing more to do here. Thanks @tomjosbin for contributing back your findings!

**Closed by mikefactorial** 2023-06-29 21:03 UTC
Labels: bug, alm-accelerator
