### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance center error - ListFlowOwners fails for default environment

### ISSUE THREAD

**Issue by Harini-Parthiban** [microsoft/coe-starter-kit#4222] opened 2022-11-17 13:44 UTC
### Describe the issue

ListFlowOwner method in flow screen fails for default environment and shows access denied error
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/107025014/202459192-fadbd49b-22c1-41e0-922c-f66adc419dea.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/107025014/202461377-81505367-552b-4f24-aaf7-62a727bdef20.png)

![image](https://user-images.githubusercontent.com/107025014/202459286-312f6b3f-23ac-445d-a871-0695ab962899.png)

Instead of using Environment column, **Name** column should be used which includes the **Default prefix**

![image](https://user-images.githubusercontent.com/107025014/202459828-c355d34f-4257-48b2-bc36-b0bb3844a668.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment] 2022-11-21 15:34
Dupe of your other bug https://github.com/microsoft/coe-starter-kit/issues/4181

**Closed by Jenefer-Monroe** 2022-11-21 15:34 UTC
Labels: bug, coe-starter-kit
