### ISSUE TITLE
[CoE Starter Kit - BUG] Bug with HELPER - Maker Check

### ISSUE THREAD

**Issue by LoRosset** [microsoft/coe-starter-kit#2461] opened 2022-04-13 14:56 UTC
### Describe the issue

I am having daily failed execution for the flow "HELPER - Maker Check". It fails to "Set variable existing value - Country" and "Set variable existing value- preferredLanguage"
![image](https://user-images.githubusercontent.com/25909766/163208090-894d233f-f30c-4ddc-8bde-f7b1852abfe2.png)

Also in the same flow, the Dataverse action "Get Manager Display Name" fails: the error raise the message "admin_maker With ID = ... Does Not Exist

### Expected Behavior

No error raised by the Sync Flows, neither Helper flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

HELPER - Maker Check and Admin Sync Flows

### Steps To Reproduce

1. Activate Sync Flows with full inventory
2. Receive error related to the Admin Sync Flows
3. Investiguate further the error and find that the flow HELPER - Maker Check generate the error as it does not answer back

**Comment by Jenefer-Monroe** [comment] 2022-04-13 16:18
This is known and fixed in later versions of the starter kit. Please upgrade to see it resolved. 
https://aka.ms/coestarterkitdownload

**Comment by Jenefer-Monroe** [comment] 2022-04-13 16:23
Duplicate of #2051

**Closed by Jenefer-Monroe** 2022-04-13 16:23 UTC
Labels: bug, coe-starter-kit
