### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot Save Support Details in DCC

### ISSUE THREAD

**Issue by GregGWC** [microsoft/coe-starter-kit#8355] opened 2024-05-24 16:08 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Describe the issue

When entering details in the support section of the Developer Compliance Center (DCC), the Save and Cancel buttons do not work i.e. nothing happens when they are clicked.
This occurs for both admin accounts and Makers with the SR role.
This is similar to #7106 but there is no notice of new version available, and the form was working and no other changes have occurred. 

Monitor session shows no activity when **Save** or **Cancel** are pressed, attachments remain unsaved.

Occurs for both Makers and Admin user accounts and for Canvass Apps & Cloud Flows.

|Solution | Version | Managed | Publisher |
|:---------|:---------|:---------|:---------|
|Creator Kit |1.0.20230727.2| Yes | PowerCAT | 
|Center of Excellence - Governance Components | 3.21 | Yes | [Power Platform Admin account] |
|Center of Excellence - Core Components | 4.31 | Yes | [Power Platform Admin account] |

There are no unmanaged layers and happens on all pages.

In Power Apps, the editor for Developer Compliance Center Flows page returns an error in OnButtonSelect for panSupportDetails_1 
*Expected Record Value. panSupportDetails_1.OnButtonSelect*

![ErrorDetails](https://github.com/microsoft/coe-starter-kit/assets/170744329/e5d2aa01-2a74-4fc5-a91f-0eb62f5bdba0)

### Expected Behavior

When opening the DCC, clicking on an app and then clicking **Support Details**, users should be able to enter details and click **Save** to update them or click **Cancel** and this should close the **Support Details** window.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.21

### What app or flow are you having the issue with?

Developer Complince Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the DCC via link or Power Platform 
2. Click on **Canvass App** or **Cloud Flow**
3. Click on a flow or app
4. Click on **Support Details**
5. Enter information into any field or adjust drop downs or attach a file
6. Click **Save**
7. Nothing happens, attachment remains _unsaved_
8. Alternatively after Step 5, click **Cancel** and nothing happens.

AB#3366

**Comment by Jenefer-Monroe** [comment] 2024-05-24 16:45
Hello, this is a known issue for all dialogs and side panels in the kit due to a regression that impacted the creator kit. Please see: https://github.com/microsoft/coe-starter-kit/issues/8350

They are releasing a version of Creator Kit that fixes this early next week and then I will be repairing all the apps before we release the June version of the Starter Kit.

**Comment by Jenefer-Monroe** [comment] 2024-05-26 12:39
closing out as a duplicate.

**Closed by Jenefer-Monroe** 2024-05-26 12:39 UTC
Labels: bug, duplicate, coe-starter-kit
