### ISSUE TITLE
[CoE Starter Kit - BUG] Empty to-do sent to manager for flows with active derived owner but orphaned flow creator

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#1544] opened 2021-11-29 20:10 UTC
### Describe the issue

We're getting an issue where a manager is getting an empty card regarding an orphaned apps/flow.
![image](https://user-images.githubusercontent.com/64927104/143933959-ee6f891f-a1bb-48f6-82ff-560ab3279421.png)

We found the orphaned flow that the run catches. The flow has no owner but it has a derived owner, but the derived owner is an active user. 
![image](https://user-images.githubusercontent.com/64927104/143934803-7298ce6c-00df-4176-beaf-150f12f03716.png)

So when the Request Orphaned Objects Reassigned (Child) flow runs and filters by admin_makerisorphaned eq true. The output in empty.

![image](https://user-images.githubusercontent.com/64927104/143934414-7255b862-3b5a-41f5-9b4b-ee89db49f309.png)

Therefore it skips the whole next section which is getting the details
![image](https://user-images.githubusercontent.com/64927104/143934528-24ea1b46-03ee-4077-a996-303c6ed52053.png)

Then when composing the card, because the input from the last step is empty the card is empty.
![image](https://user-images.githubusercontent.com/64927104/143935206-cdbded35-1554-40ab-a074-018c5d1cc2e2.png)

I believe the flow needs to be modified to better handle derived owners when finding the orphaned flow owner manager.

### Expected Behavior

The card that gets sent to managers, which have derived owners, should not be empty.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

**Comment by Jenefer-Monroe** [comment] 2021-11-29 21:43
Thanks for the detailed investigation. Will explore a fix.

**Comment by Jenefer-Monroe** [comment] 2021-12-29 19:51
It actually looks like the issue is that this flow is incorrectly marked as orphaned. 
Please see in the Parent flow (**Request Orphaned Objects Reassigned (Parent)**)

![image](https://user-images.githubusercontent.com/89584709/147698424-02df45f6-f84c-430f-a355-2e9f323763b4.png)


Most likely what has happened is that when it was re-assigned via derived owner, the orphaned flag wasnt reset. 
You can do a full inventory to clear this, or just clear it manually in the Power Platform Admin View model driven app. 

I will look around to make sure we are clearning the orphan flag when we add a derived owner.

**Comment by Jenefer-Monroe** [comment] 2022-01-06 21:40
closing out as I believe this was just things not getting marked as orphan correctly.

**Closed by Jenefer-Monroe** 2022-01-06 21:40 UTC
Labels: coe-starter-kit, governance-components
