### ISSUE TITLE
AA4M: AADSTS50126: Error validating credentials due to invalid username or password.

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#222] opened 2021-04-29 18:55 UTC
Regarding ALM Accelerator i have configured it and created project as well and approval process is done as well but at the stage of deploying solution to test environment i am getting following error. if you came across similar error or issue cam you please let me know? thanks also please find error log 
[logs_1.zip](https://github.com/microsoft/coe-starter-kit/files/6397849/logs_1.zip)

 Error: AADSTS50126: Error validating credentials due to invalid username or password.
  Trace ID: 94d1d599-7f58-4d4a-99ca-3b4fec41f500
  Correlation ID: 4894d9fe-9c43-4db8-950a-a28510676818
  Timestamp: 2021-04-29 08:34:39Z
  Response status code does not indicate success: 400 (BadRequest).
  {"error":"invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: 94d1d599-7f58-4d4a-99ca-3b4fec41f500\r\nCorrelation ID: 4894d9fe-9c43-4db8-950a-a28510676818\r\nTimestamp: 2021-04-29 08:34:39Z","error_codes":[50126],"timestamp":"2021-04-29 08:34:39Z","trace_id":"94d1d599-7f58-4d4a-99ca-3b4fec41f500","correlation_id":"4894d9fe-9c43-4db8-950a-a28510676818","error_uri":"https://login.microsoftonline.com/error?code=50126"}: Unknown error
  
  
  
  Usage: create [--name] [--kind] --url [--username] [--password]
  
    --name                      The name you want to give to this authentication profile (maximum 12 characters) (alias: -n)
    --kind                      The kind of authentication profile you are creating, defaults to CDS (alias: -k)
    --url                       The resource URL to connect to (alias: -u)
    --username                  Optional: The username to authenticate with; shows AAD dialog if not specified (alias: -un)
    -*** The password to authenticate with (alias: -p)
  
  
  Error: failed: Error: Microsoft PowerApps CLI,,Version: 1.3.6+gb980aa0,,,,Error: AADSTS50126: Error validating credentials due to invalid username or password.,Trace ID: 94d1d599-7f58-4d4a-99ca-3b4fec41f500,Correlation ID: 4894d9fe-9c43-4db8-950a-a28510676818,Timestamp: 2021-04-29 08:34:39Z,Response status code does not indicate success: 400 (BadRequest).,{"error":"invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: 94d1d599-7f58-4d4a-99ca-3b4fec41f500\r\nCorrelation ID: 4894d9fe-9c43-4db8-950a-a28510676818\r\nTimestamp: 2021-04-29 08:34:39Z","error_codes":[50126],"timestamp":"2021-04-29 08:34:39Z","trace_id":"94d1d599-7f58-4d4a-99ca-3b4fec41f500","correlation_id":"4894d9fe-9c43-4db8-950a-a28510676818","error_uri":"https://login.microsoftonline.com/error?code=50126"}: Unknown error,,,,Usage: create [--name] [--kind] --url [--username] [--password],,  --name                      The name you want to give to this authentication profile (maximum 12 characters) (alias: -n),  --kind                      The kind of authentication profile you are creating, defaults to CDS (alias: -k),  --url                       The resource URL to connect to (alias: -u),  --username                  Optional: The username to authenticate with; shows AAD dialog if not specified (alias: -un),  -*** The password to authenticate with (alias: -p),,

_Originally posted by @NIhil1409 in https://github.com/microsoft/coe-starter-kit/discussions/172#discussioncomment-674191_

**Comment by devkeydet** [comment] 2021-04-29 18:59
Create for @NIhil1409 who originally put this in the following discussion: https://github.com/microsoft/coe-starter-kit/discussions/172

**Comment by mikefactorial** [comment] 2021-04-29 19:28
@NIhil1409 I assume this is related to the ALM Accelerator for Makers (formerly PowerOps) since it was also posted MicrosoftDocs/power-platform/#712. Can you verify that you've entered the correct user password into the secrets in GitHub? This would be the same password you entered during setup of the ALM Accelerator App.

**Comment by mikefactorial** [comment] 2021-04-29 19:30
NOTE: We're in the process of moving all of the CoE Starter Kit Issues to this repo so feel free to open issues here going forward for anything related to the CoE Starter Kit related in the meantime. Thanks

**Comment by NIhil1409** [comment] 2021-05-04 13:29
@mikefactorial  :- i can confirm i have entered correct user password it went fine this time and now i am getting another error while deploying from test to prod environment.  getting following error. i have raised issue with Microsoft but they came back to me saying it is out of scope from them and asked to contact Githib. if you have any idea regarding following error  please let me know . Thanks

Flow Name: DeployToStage 
Flow Run ID: 08585818225937686279580375635CU01 
Error Details: Error found in action: Check_If_Deploying_to_Test with code: ActionFailed Error: {"code":"ActionFailed","message":"An action failed. No dependent actions succeeded."}

**Comment by NIhil1409** [comment] 2021-05-14 09:28
@mikefactorial :- sorry for the late reply its working fine now. i was having issue in one of the child flow,
Thanks
Nihil

**Comment by mikefactorial** [comment] 2021-05-18 12:53
Thanks @NIhil1409. Closing this issue. Thanks for letting us know.

**Closed by mikefactorial** 2021-05-18 12:53 UTC
Labels: alm-accelerator
