### ISSUE TITLE
[CoE Starter Kit - BUG] List Bots Times out in Sync Template v3 (PVA)

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1581] opened 2021-12-08 13:49 UTC
### Describe the issue

Admin | Sync Template v3 (PVA)

The flow fails on multiple environments, runs for 2 hrs at a time because of retries also.

It is failing in the List Bots action when accessing Teams environments, (works fine for normal ones, not support).

Error Msg

The dynamic operation request to API 'commondataservice' operation 'GetTable' failed with status code 'BadGateway'. Error response: { "error": { "code": 502, "source": "europe-002.azure-apim.net", "clientRequestId": "xxxxx-xxxx-xxxx-xxxx-xxxxx", "message": "BadGateway", "innerError": { "status": 502, "message": "The 'RetrieveMetadataChanges' is only allowed to be accessed from OData endpoint in Dataverse for Teams offering. EnitytName: none", "error": { "message": "The 'RetrieveMetadataChanges' is only allowed to be accessed from OData endpoint in Dataverse for Teams offering. EnitytName: none" }, "source": "commondataservice-ne.azconn-ne.p.azurewebsites.net", "debugInfo": "clientRequestId: xxxxx-xxxx-xxxx-xxxx-xxxxx" } } }

### Expected Behavior

Collect the bots or lack of them

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

Run the flow against a Tenant with lots of Teams environments in it.

Check the flow results.

**Comment by Jenefer-Monroe** [comment] 2021-12-08 14:44
Hello, thank you for the thorough investigation. This was fixed in the Nov release via #1353 
Duplicate of #1353

**Comment by Jenefer-Monroe** [comment] 2021-12-08 20:41
closing out as dupe

**Closed by Jenefer-Monroe** 2021-12-08 20:41 UTC
Labels: coe-starter-kit
