### ISSUE TITLE
[CoE Starter Kit - QUESTION] Have starter kit record / respond to "CommonDataServiceDatabaseProvisioningState : Deleting"

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#2236] opened 2022-03-14 09:16 UTC
### What is your question?

I can see there is one environment in my Tenant which status is showing "Deleting" from long time but not deleted yet 
MS case open on this to fix that but in between I am trying to understand How we can manage this situation logically in CoE Starter kit

Other CoE Power Automate failing due to this environment 
CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) 
CLEANUP - Admin | Sync Template v3 (Check Deleted)

 
![image](https://user-images.githubusercontent.com/30046543/158141947-400faaff-7a1c-4df3-8fe7-347a74b2fe16.png)

DisplayName                                : Office365WeeklyUpdates (orgb41983c9)
CommonDataServiceDatabaseProvisioningState : Deleting
CreatedTime                                : 2021-01-27T10:15:47.8376222Z
LastModifiedTime                           : 2021-11-23T01:40:48.6606543Z

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)  CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment] 2022-03-14 13:26
Sorry I dont quite follow. I believe you are saying that you attempted to delete an environment from the tenant via the product UX at [https://admin.powerplatform.microsoft.com/environments](https://admin.powerplatform.microsoft.com/environments), and it is not deleting successfully. Is that correct? 

And your question here is how to deal with that bad state while you wait for the product team to fix up the issue?

**Comment by sharmajitendralal** [comment] 2022-03-15 07:44
Yes, Correct 

Here is little correction, Actually "Office365WeeklyUpdates" is "Microsoft Teams" Type environment  
Which should automatically delete after deletion of Teams Site but in this case Team site deleted but still environment exist

Yes, Now I am looking to handle this situation in CoE starter kit where these two flow is failing to run successfully  
and we have data mismatch issue in Power BI report 

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
CLEANUP - Admin | Sync Template v3 (Check Deleted)

Previous case reference where we are facing data mismatch issue
https://github.com/microsoft/coe-starter-kit/issues/1765

**Comment by Jenefer-Monroe** [comment] 2022-03-15 13:46
To summarize the cause:
- You had a Dataverse for Teams environment in a Team **_Office365WeeklyUpdates_**
- You deleted the team but the environment did not delete when you deleted the team. 
- When you go to look at the admin pages, it just shows the environment as deleting indefinitely. 
- This is a product issue and you already have product support looking into it. 

Correct?

**Comment by sharmajitendralal** [comment] 2022-03-16 05:21
Yes, Correct

Now I am asking to manage this situation in CoE Starter kit also so we can avoid this hurdle in future 

Also please help me to know that which Power Automate is responsible for cleaning the deleted environment or deleting one

**Comment by sharmajitendralal** [comment] 2022-03-17 04:26
Thanks for update..

Is it possible to pickup this point in future? MS engineer mentioned that this issue can be managed in PowerAutomate as well using this properties "CommonDataServiceDatabaseProvisioningState : Deleting"

**Comment by sharmajitendralal** [comment] 2022-03-21 05:48
Aahh Got it, In Deleting State its not clear either this will be delete or not 

But because of this issue CoE Power Automate start failing and we don't have any clue why its failing 
I have given much time to find out this issue so I want to avoid this situating in future

**Comment by Jenefer-Monroe** [comment] 2022-03-21 12:21
OK. We can put responding to this state in our backlog. 

Thanks for investigating.

**Comment by manuelap-msft** [comment] 2022-10-19 15:32
This has not come up as a priority with other customers, closing out.

**Closed by manuelap-msft** 2022-10-19 15:32 UTC
Labels: question, coe-starter-kit
