### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance center error - Get Connector failed

### ISSUE THREAD

**Issue by Harini-Parthiban** [microsoft/coe-starter-kit#4223] opened 2022-11-17 14:12 UTC
### Describe the issue

Getting this error while opening apps from Developer compliance center. This error is inconsistent and generally shows up after refresh.

![image](https://user-images.githubusercontent.com/107025014/202468437-bd8d618c-69a5-4a99-9252-4f5c19f972f2.png)

### Expected Behavior

Not to receive error while opening apps

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

Open any app from Developer Compliance Center

**Comment by Jenefer-Monroe** [comment] 2022-11-21 15:35
Dupe of your other bug https://github.com/microsoft/coe-starter-kit/issues/4181

**Closed by Jenefer-Monroe** 2022-11-21 15:35 UTC
Labels: bug, coe-starter-kit
