### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 - Status Failed

### ISSUE THREAD

**Issue by YvoValcon** [microsoft/coe-starter-kit#4350] opened 2022-12-06 10:04 UTC
### General information
Package: CenterofExcellenceCoreComponents_3_56_managed.zip
Child flows on: yes 

While I try to run the flow "Admin | Sync Template v3", I receive the following error message:
"Action 'Get_Environment' failed". 

More specifically, it is in the connector:
- "Check if Legacy environment"
- "Get Environment"
- "Get Maker"

### Expected Behavior

Expected to run and succesfully complete all steps in the flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 

### Steps To Reproduce

1. In the CoE Environment
2. Turn on all child flows and setup flows
3. run "Admin - Sync Template v3"

**Comment by Jenefer-Monroe** [comment] 2022-12-06 13:25
Hello, in the future screenshots will help us to answer the correct question here but I think you are saying that the flow failed on the "Get Maker" call. If not, please let me know. 

If that is the case, please go make sure **_HELPER - Maker Check_** is turned on, that is does not have any [unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows), and that its [Run only users connections](https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties) are set. 

Pictures showing all this will be helpful. 
Note that you must log in to GitHub to share pictures, replying in email will not share pictures.

**Comment by YvodeRooij** [comment] 2022-12-06 15:19
Hi Jenefer,

Thank you. I want to add pictures, however I cannot make screenshots as I am working in a Citrix environment. 
HELPER - Maker Check is turned on --> works
Run only users connections --> works
Unmanaged layers --> " This functionality relies on data that is not yet in your CoE. You need to run this flow: Admin | Sync Template v3 Then return here to use this feature." 

I cannot check for the unmanaged layers as the Admin | Sync Template v3 doesnt run... But that is the problem to start with .. kind of stuck now! What do you suggets?

**Comment by YvodeRooij** [comment] 2022-12-06 16:05
With "works" I mean that the problem is not situated there.

Where do I find the layer icon? I cannot see the icon in the Admin Command Center in the Coe...

**Comment by Jenefer-Monroe** [comment] 2022-12-06 16:14
1. What do you see for the Run only users? Can you please describe it? Do all the connections have a user selected? Are they the same user? 
2. What do you see for HELPER - Maker Check? Is it on? Are there recent runs? 
3. Access to the unmanaged layers is from the list of flows in the solution
![image](https://user-images.githubusercontent.com/89584709/205964367-27e0f3c9-bdf8-49bc-8c62-09a182ad0a16.png)

**Comment by YvodeRooij** [comment] 2022-12-06 20:14
Hi Jenefer,

Hereby the answers:

1. use this connection (myname@company.nl)
2. It is on and there are recent runs
3. there are no unmanaged layers ... here a picture made from my phone:

![CoE Maker Flow](https://user-images.githubusercontent.com/110634893/206013002-d78c4883-758b-45e1-b90e-14236f4afb4e.jpg)

**Comment by Jenefer-Monroe** [comment] 2022-12-06 22:54
what is the error message you see for the call to "Get Maker"?

**Comment by YvodeRooij** [comment] 2022-12-07 07:54
![IMG_1704](https://user-images.githubusercontent.com/110634893/206120200-e84ddd76-9336-409e-a7f9-818ded7ea077.jpg)
![IMG_1705](https://user-images.githubusercontent.com/110634893/206120214-aa480b20-c054-4e2c-9ab2-ad46660c20bd.jpg)

**Comment by Jenefer-Monroe** [comment] 2022-12-07 13:43
Let's test the **_HELPER - Maker Check_** flow directly. 

Can you please take the values from here, 
![image](https://user-images.githubusercontent.com/89584709/206194903-f7465380-be88-4f51-a528-4fdb2a57d997.png)

And run the flow with those values? 
![image](https://user-images.githubusercontent.com/89584709/205967413-65c837f8-965c-4c69-9985-a4d8b8acbcab.png)

Then click on the time stamp of the run that was triggered to open it
![image](https://user-images.githubusercontent.com/89584709/205967582-58d99a4d-b70b-47d0-9948-4e24d756d938.png)

Please share screenshots of what you see.

**Comment by YvoValcon** [comment] 2022-12-07 15:21
I used the MakerID en MakerDisplayName as suggested from the Admin | Sync Template flow and ran the Helper Maker Flow with those elements. 

It ran successfully: 

![IMG_1707](https://user-images.githubusercontent.com/97224137/206218831-97d762dc-b87d-45a9-a4cd-48db8e83a9ea.jpg)

**Comment by YvoValcon** [comment] 2022-12-08 12:10
Hi Jenefer,

Any options left? :)

**Comment by Jenefer-Monroe** [comment] 2022-12-08 13:59
The connection between the parent and child flows is broken. In the past this has always been due to either the flow being off or broken (which we have just confirmed is not the case) or something wrong with the user running the flow (insufficient permissions, run only users not set correctly, license/role via PIM, etc)

Perhaps setup didnt work correctly? 
Can you please share a screenshot of your solutions? Be sure to expand all columns so we can see all the text
![image](https://user-images.githubusercontent.com/89584709/206275474-4a642bf2-c539-4bcf-9241-2d7b5fb17b4d.png)

**Comment by YvodeRooij** [comment] 2022-12-08 15:29
![IMG_1714](https://user-images.githubusercontent.com/110634893/206486573-689e68b7-e316-42d4-8157-f5ec2c7c07be.jpg)
![IMG_1715](https://user-images.githubusercontent.com/110634893/206486584-c72a3648-70ee-413f-85b5-00d30a4b4729.jpg)
![IMG_1716](https://user-images.githubusercontent.com/110634893/206486585-c0a46c14-9671-4982-95af-21cef6af0952.jpg)
![IMG_1713](https://user-images.githubusercontent.com/110634893/206486586-24e6ebaf-8ff4-4d27-bffd-d55a6dfb25c1.jpg)

**Comment by YvodeRooij** [comment] 2022-12-12 10:26
Hi Jenefer, 

Can you please further assist?

**Comment by Jenefer-Monroe** [comment] 2022-12-14 16:53
If you edit that flow, what do you see here? (please check for unmanaged layer after you do this in case one gets added) 
![image](https://user-images.githubusercontent.com/89584709/207657718-e265b832-ed5d-4dfd-a45a-cc9b7febd8bb.png)

**Comment by YvodeRooij** [comment] 2022-12-14 19:09
![IMG_1755](https://user-images.githubusercontent.com/110634893/207690012-e7274c26-1279-438e-b676-e53e742432c7.jpg)

**Comment by Jenefer-Monroe** [comment] 2022-12-14 19:31
I'm really out of ideas. I just noticed you are on June 2022. Can you try to upgrade Core to 4.2 (Dec release)?

**Comment by YvodeRooij** [comment] 2022-12-14 20:40
The newest version is installed... that is why I could also use the setup wizard. Please see below.

Is this something that a re-install could fix?

![IMG_1756](https://user-images.githubusercontent.com/110634893/207708989-950f2dc3-be44-422e-a244-41d1ade23920.jpg)

**Comment by Jenefer-Monroe** [comment] 2022-12-14 21:19
oh yes of course, forgive me I just was looking at the original description.

**Comment by Jenefer-Monroe** [comment] 2022-12-14 21:20
Yes you could try an overwrite

### How to do an overwrite upgrade in the classic UX:
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by YvodeRooij** [comment] 2022-12-16 08:42
Hi @Jenefer-Monroe ,

Unfortunately nothing seems to work... I am now going to delete the solution and try to install it again... Ill let you know if that works!

**Comment by Jenefer-Monroe** [comment] 2023-01-06 19:35
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-01-06 19:35 UTC
Labels: bug, coe-starter-kit
