### ISSUE TITLE
admin_environmentname (Environment ID (withprefix) in table environments has blank values

### ISSUE THREAD

**Issue by KezHalls** [microsoft/coe-starter-kit#7852] opened 2024-03-14 22:44 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Cannot refresh the coe dashboard report.  There are environments that have been marked as deleted without it as well as environment that has not been deleted that doesn't have an environment Id/name.  I don't see how this could be something we have wrong.  the report is working off the CoE structure.

![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/41c301a0-4ab0-436b-83d4-2936a2bac496)

![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/76d2bb9a-a340-4950-936e-350543faca74)

### Expected Behavior

Report Data refreshes as expected

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

report CoE dashboard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open report.  put in the correct tenant url
refresh data

AB#2570

**Comment by Jenefer-Monroe** [comment] 2024-03-14 23:15
Hello. Which PBIT file are you using? 
And are you cloud flows or data export architecture?

**Comment by KezHalls** [comment] 2024-03-18 01:28
Production_CoEDashboard_October2023.pbit
we are using cloud flows.

thanks

**Comment by Jenefer-Monroe** [comment] 2024-03-18 10:20
Please do note that we recommend you match the PBIT file with the install version. So each month we ship a new PBIT and its recommended you upgrade them and overwrite your current published version with it. 

That it not likely the cause for you though it appears you have some data corruption in your Dataverse tables. 
Please go to the table in Dataverse. Add the columns shown and filter to Name - Does not contain data
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eaf06324-246e-48c3-9e65-d073a80faac1)

How many records like that do you have? 
For those records, is other information (like display name, sku, etc) provided?

**Comment by Jenefer-Monroe** [comment] 2024-03-24 14:47
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-03-24 14:47 UTC
Labels: bug, coe-starter-kit
