### ISSUE TITLE
[CoE Starter Kit - BUG] No visibility to environments created by person that left our company

### ISSUE THREAD

**Issue by jpereira2317** [microsoft/coe-starter-kit#3918] opened 2022-10-11 17:30 UTC
### Describe the issue

No visibility to environments created by person that left our company; For apps like assign flow permissions, I cannot see any of the environments because I believe the person that created it has left the company. This has had no impact on using the environment or creating/maintaining or using apps.

### Expected Behavior

To see the environments in the correct pane.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

Open Flow Permissions app, you will not see the environments or apps in those environments to pick from.

**Comment by Jenefer-Monroe** [comment] 2022-10-11 20:48
If the person left the company before you setup the CoE inventory then it will not have any information about them, there isnt really anything we can do programmatically for this unfortunately. Instead all apps/flows/environments like these will be marked as orphan but we wont be able to map them to a former employee.

But if they left after you set up the inventory it should show them and just be marked as orphaned. 
Can you clarify which of these situations you are referencing?

**Comment by jpereira2317** [comment] 2022-10-13 13:12
My problem is this person left the company:

[cid:06f46e16-1d44-4dcd-9458-943473625667]


And when I go into the Set Flow Permissions app, I do not see any environments associated with him since he created them. And also corresponding apps and flows embedded in the environments. This makes the COE toolkit not useable for my needs.

[cid:ade2348d-c39a-45e1-bab6-5eaf0795cfa7]

Prior to him leaving this absolutely worked as well as a number of things. If there is nothing you can do I understand.


Thank you,
Jeffery Pereira


________________________________
From: Jenefer Monroe ***@***.***>
Sent: Tuesday, October 11, 2022 3:48 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Pereira Jeffery ***@***.***>; Author ***@***.***>
Subject: {EXTERNAL}Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] No visibility to environments created by person that left our company (Issue #3918)


If the person left the company before you setup the CoE inventory then it will not have any information about them, there isnt really anything we can do programmatically for this unfortunately. Instead all apps/flows/environments like these will be marked as orphan but we wont be able to map them to a former employee.

But if they left after you set up the inventory it should show them and just be marked as orphaned.
Can you clarify which of these situations you are referencing?

**Comment by Jenefer-Monroe** [comment] 2022-10-13 16:24
I'm having trouble following because this is not the expected behavior, so lets walk through it a little more. 

I believe you are saying that the person, before they left the organization, were in the Maker table and showed up in inventory and in the Set Flow Permissions app correctly. 

But now that they left the organization they no longer show up. IS that accurate? 

I have just validated that this works, they should show up here still, as this orphan does
![image](https://user-images.githubusercontent.com/89584709/195651685-7f37b523-6f79-4e53-a4ec-9d0ff5b83d34.png)


### Can you please:
1. Validate if I am describing your situation correctly
In the **_Power Platform Admin View_** app, 
2. Check if they are in the Maker table still
3. Check if they still have flows to which they are the derived owner or apps to which they are the owner.

**Comment by jpereira2317** [comment] 2022-10-17 21:12
Sort of, it is more any app or flow associated with the environment (environment that was created by person that left the company) is not longer visible/you cannot successfully change or add user permissions too.


Please let me know if we are talking about the same thing just using different words and I can do the validation on my end to confirm.


Thank you,
Jeffery Pereira
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Thursday, October 13, 2022 11:24 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Pereira Jeffery ***@***.***>; Author ***@***.***>
Subject: {EXTERNAL}Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] No visibility to environments created by person that left our company (Issue #3918)


I'm having trouble following because this is not the expected behavior, so lets walk through it a little more.

I believe you are saying that the person, before they left the organization, were in the Maker table and showed up in inventory and in the Set Flow Permissions app correctly.

But now that they left the organization they no longer show up. IS that accurate?

I have just validated that this works, they should show up here still, as this orphan does
[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F195651685-7f37b523-6f79-4e53-a4ec-9d0ff5b83d34.png&data=05%7C01%7Cjpereira%40martin-brower.com%7C07dd7492c47f491681cd08daad37658d%7Cff1b190bedf8459d82370545497adf7a%7C0%7C0%7C638012750695212826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B%2FPAWf%2FZqZyn%2BeM4ZcpfzwRWW9Af5XOLqA02Y1dcw%2Bs%3D&reserved=0>

Can you please:

  1.  Validate if I am describing your situation correctly
In the Power Platform Admin View app,
  2.  Check if they are in the Maker table still
  3.  Check if they still have flows to which they are the derived owner or apps to which they are the owner.

**Comment by Jenefer-Monroe** [comment] 2022-10-19 16:49
ok i understand now, let me know if I misunderstand 

- user made an envt with apps and flows
- user left the organization
- environment no longer shows in these lists 

This also shouldn't be the case so lets step away from these apps and look at the data itself. 

Please go to the CoE environment > Tables > Environment > Edit the columns until you see the below and then filter to find the environment in question. Is it present? Is it marked orphaned? Is it deleted? 
![image](https://user-images.githubusercontent.com/89584709/196754235-c81c3a15-0c0a-4e30-871a-0cb384178ec2.png)

**Comment by Jenefer-Monroe** [comment] 2022-10-28 22:19
Closing out as no further action for starter kit team

**Comment by jpereira2317** [comment] 2022-11-04 19:22
Jenefer,

I apologize for not responding, we had some emergency issues in our organization that side tracker me here. Is there anything that can be done to open this ticket back up? I will make it my highest priority next week.


Thank you,
Jeffery Pereira
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Friday, October 28, 2022 5:19 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Pereira Jeffery ***@***.***>; Author ***@***.***>
Subject: {EXTERNAL}Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] No visibility to environments created by person that left our company (Issue #3918)


Closed #3918<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F3918&data=05%7C01%7Cjpereira%40martin-brower.com%7C14550e757df843adf9e608dab932850b%7Cff1b190bedf8459d82370545497adf7a%7C0%7C0%7C638025923915060568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MhYY5Tb1ta2T31lbev0XjffY57d0Ru4AR4AvfQRYzHo%3D&reserved=0> as completed.

**Comment by Jenefer-Monroe** [comment] 2022-11-04 20:11
Sure no problem, I've re-opened.

**Comment by jpereira2317** [comment] 2022-11-07 20:47
So I do see a few of the environments that are associated with the user that has left the company:

[cid:da3ef9d3-99b9-4056-acc6-98d3c8d030d4]

Oddly enough, it seems like the environments with orphan apps/flows are missing. Please let me know what other info can be provided.


Thank you,
Jeffery Pereira
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Wednesday, October 19, 2022 11:49 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Pereira Jeffery ***@***.***>; Author ***@***.***>
Subject: {EXTERNAL}Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] No visibility to environments created by person that left our company (Issue #3918)


ok i understand now, let me know if I misunderstand

  *   user made an envt with apps and flows
  *   user left the organization
  *   environment no longer shows in these lists

This also shouldn't be the case so lets step away from these apps and look at the data itself.

Please go to the CoE environment > Tables > Environment > Edit the columns until you see the below and then filter to find the environment in question. Is it present? Is it marked orphaned? Is it deleted?
[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F196754235-c81c3a15-0c0a-4e30-871a-0cb384178ec2.png&data=05%7C01%7Cjpereira%40martin-brower.com%7Cd6f80271d690424d8bf208dab1f1eab5%7Cff1b190bedf8459d82370545497adf7a%7C0%7C0%7C638017949827370689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3qT3wsZVK3jard8id6I3CGb9fz0wcDNZm170ob8BlYo%3D&reserved=0>

**Comment by Jenefer-Monroe** [comment] 2022-11-07 21:15
Hello. You will need to log in to GitHub to share images, so I'm not sure what you are seeing. Can you please log in and reshare the image?

**Comment by jpereira2317** [comment] 2022-11-08 14:24
Here is the image: 
![image](https://user-images.githubusercontent.com/66750779/200589884-96f628bc-99d0-409a-8d0a-833c1a322f3c.png)

**Comment by jpereira2317** [comment] 2022-11-09 21:11
{"id":"a0844033-0015-4e13-b9ae-6a6caa43240d","brandColor":"#4B53BC","connectionReferences":{"shared_teams":{"connection":{"id":"/new_sharedteams_59cf0"}}},"connectorDisplayName":"Microsoft Teams","icon":"https://connectoricons-prod.azureedge.net/releases/v1.0.1608/1.0.1608.3079/teams/icon.png","isTrigger":false,"operationName":"Post_message_in_a_chat_or_channel","operationDefinition":{"type":"OpenApiConnection","inputs":{"host":{"connectionName":"shared_teams","operationId":"PostMessageToConversation","apiId":"/providers/Microsoft.PowerApps/apis/shared_teams"},"parameters":{"poster":"Flow bot","location":"Group chat","body/recipient":"19:7db3b9f6710b414ba84b4f319c36fe24@thread.v2","body/messageBody":"<p>muting for 10 mins</p>"},"authentication":"@parameters('$authentication')"},"runAfter":{}}}

Yes they are there

**Comment by jpereira2317** [comment] 2022-11-09 21:11
Forgive me I posted the wrong thing

**Comment by jpereira2317** [comment] 2022-11-09 21:12
![image](https://user-images.githubusercontent.com/66750779/200942728-40580d5f-935c-4886-a983-ef9eebeec01c.png)
Yes they are there

**Comment by Jenefer-Monroe** [comment] 2022-11-09 21:24
Can you see what identity is running the connections in the **_Admin | Sync Template v3_** flow? Is it a different identity than you? 
![image](https://user-images.githubusercontent.com/89584709/200944715-877af34c-f6f5-49e2-b786-caa52c24428b.png)

**Comment by jpereira2317** [comment] 2022-11-09 21:27
Which solution does this template exist in? I am pretty confident it is not running as me. Nor do we have the access within our governance to change that.

**Comment by Jenefer-Monroe** [comment] 2022-11-09 21:53
You dont need to change it, we just need to make sure it has the right permissions permanently assigned.

If you go to the Core solution, this flow is part of that solution. 

Then once you know who the identity is you will need to make sure they have the Power Platform Admin Role permanently assigned.
![image](https://user-images.githubusercontent.com/89584709/200949784-5e357e98-37b2-422c-bdf8-3a053956f1d1.png)

**Comment by jpereira2317** [comment] 2022-11-09 22:01
![image](https://user-images.githubusercontent.com/66750779/200951201-2c96332b-da8f-4eaf-bba4-8d95c2556238.png)

I dont believe we will be able to verify; But this would impact more then just those environments if they werent given this role. Its only impacting a subset of environments.

**Comment by Jenefer-Monroe** [comment] 2022-11-09 22:39
I think in order to proceed you will need to be able to log in as whatever identity is running the flows

**Comment by jpereira2317** [comment] 2022-11-10 13:57
But it is only applicable to the environments associated to that user that have content in those environments. There should not need to be this level of overhead on our end to proceed forward. Have you been able to replicate the issue on your end?

**Comment by Jenefer-Monroe** [comment] 2022-11-10 14:11
No we have not seen this bug before. I suspect the issue has something to do with the identity running the flows. 

Generally speaking, in order to manage the CoE Starter Kit you will need to be able to authenticate as the user running the flows. For upgrades for example you would need this. Did someone else set up the kit for you? And do you still have access to them? 

I just looked at your version of core and it's 3.19 which is a year old. We [recommend updating at least every 3 months](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

**Comment by jpereira2317** [comment] 2022-11-10 14:16
But in your sandbox environment, have you tried creating an environment temp user1. Then creating separate flows in that same environment with a temp user2. Remove temp user1 and temp user2 and confirm if you still see the orphan flow in the Add Flow Permissions canvas app. We will not be able to proceed forward until I can have supporting evidence that there is something uniquely different in our environment other then what is called out above. Please confirm.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 14:17
And as a reminder, this CoE Starter Kit is not a supported Microsoft product. The CoE Starter Kit is an unsupported set of templates designed to assist with managing the Power Platform in your tenant. We do our best to assist people using the kit but are a very small team and so provided help with best endeavors without SLA via GitHub

Please see our [Disclaimer](https://learn.microsoft.com/en-us/power-platform/guidance/coe/overview#disclaimer)

Some customers that require a deeper level of assistance benefit from hiring a partner organization to assist in deriving your local expertise in both the kit and managing the product in the template. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

**Comment by jpereira2317** [comment] 2022-11-10 14:21
I understand, please put this in your backlog and verify. We have our own limitations as well, that is why we are not able to commit to the asks here unless we have certainty that there is something in our environment that is peculiar.

**Comment by jpereira2317** [comment] 2022-11-10 14:25
If it is an old bug, what steps can be taken to get the COE Toolkit we have to the latest and greatest?

**Comment by Jenefer-Monroe** [comment] 2022-11-10 14:29
Unfortunately upgrade from solutions that old may not be smooth, which is why we suggest upgrading every 3 months. If all you are using us for is inventory you will likely be better served starting from scratch. 

Here are our upgrade instructions: [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)
And here is where to start if you will be starting from scratch: [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup)

**Comment by jpereira2317** [comment] 2022-11-10 14:41
Thank you, I will review this with the resources this concerns. Will follow up in a week or so

**Comment by Jenefer-Monroe** [comment] 2022-12-01 01:41
Closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-12-01 01:41 UTC
Labels: bug, coe-starter-kit
