### ISSUE TITLE
[CoE Starter Kit - Feature]: Flow owners

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#2382] opened 2022-04-06 13:19 UTC
### Is your feature request related to a problem? Please describe.

The list of resource users and owners is stored in the Power Platform User Role table. This is the case e.g. for apps and then the users/owners are displayed in the main form for records in the PowerApps App table. 

There's no such feature for flows. If a flow is shared, we can't tell who are all its owners , except the main owner/creator. This can be useful especially if you want to make sure certain flows are shared and don't become orphaned.

### Describe the solution you'd like

The CoE could use the "Get Flow Owner Role as Admin" action from Power Automate For Admins connector. I know this could be quite heavy as we need to query each flow separately to get its owners but should be doable. Flow owners data could be stored in the same table - Power Platform User Role.

The action returns each user who has permissions to the flow in the "roleName" property, where:
- Owner = Owner (Creator)
- CanEdit = Owner (Co-Owner)
- CanView = Run-only user

These roles can be stored in the Role Name column like it is done for Apps.

**Comment by Niqlash** [comment] 2022-04-17 09:14
+1 here as this feature would be very useful for us too - maybe the population could be done as part of the already existing cleanup flow that gets the UserRoles for apps?

**Comment by xmihux** [comment] 2022-04-21 11:35
Hi, @Jenefer-Monroe I can see it's been added to the backlog. What does that mean exactly - is it pending review or has already been reviewed/accepted and put in the backlog for development?

**Comment by Jenefer-Monroe** [comment] 2022-04-21 11:38
Its on the backlog for development. I cant give an estimate for when the work will occur but it is something we understand and want to fund.

**Comment by xmihux** [comment] 2022-04-21 11:57
Got it. Awesome, thank you.

**Comment by suvernagithub** [comment] 2022-07-20 08:51
We are using "Get Flow Owner Role as Admin" action from Power Automate For Admins connector for our own development and we have noticed if a flow is inside solution, it returns empty result, where as same action returns list of owners and co-owners for a flow outside of a solution. What is the alternative way to find owners for solution aware flow

**Comment by manuelap-msft** [comment] 2022-10-19 15:50
Duplicate of #1083 and tracking as part of that. Closing as duplicate.

**Closed by manuelap-msft** 2022-10-19 15:50 UTC
Labels: enhancement, coe-starter-kit
