### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER Flow Errors

### ISSUE THREAD

**Issue by RheaP01** [microsoft/coe-starter-kit#7176] opened 2023-11-22 10:32 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is regarding the October release :Helper - CanvasAppOperations Failing . BadRequest error in the List Role for old owner for the Dataverse action. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

october

### What app or flow are you having the issue with?

HELPER - CanvasApp Operations

### What method are you using to get inventory and telemetry?

None

AB#1506

**Comment by shrikant-singh31** [comment] 2023-11-22 12:15
Hi @RheaP01, can you please share some more information like steps to reproduce along with the screenshots of the flow run and also the step where the flow is failing?

**Comment by RheaP01** [comment] 2023-11-22 14:00
> Hi @RheaP01, can you please share some more information like steps to reproduce along with the screenshots of the flow run and also the step where the flow is failing?

<img width="177" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/135959294/35be4781-5a36-40ca-9d3f-500ebe52adf0">
<img width="483" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/135959294/86de467e-2594-4651-8763-417930ec31db">

**Comment by shrikant-singh31** [comment] 2023-11-23 06:27
Hi @RheaP01, in the above flow run can you please check what values do we have in Filter rows in inputs of List Role for old owner action by clicking on show more button and share the screenshot of that?

**Comment by RheaP01** [comment] 2023-11-23 15:20
> Hi @RheaP01, in the above flow run can you please check what values do we have in Filter rows in inputs of List Role for old owner action by clicking on show more button and share the screenshot of that?

It just says : admin_powerplatformuserroleid

**Comment by shrikant-singh31** [comment] 2023-11-24 08:44
1. Can you go to the Admin Command Center > CoE Flows > Inventory. Validate that all HELPER - CanvasApp Operations flow is turned on and confirm that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)
2. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by RheaP01** [comment] 2023-11-24 14:52
> 1. Can you go to the Admin Command Center > CoE Flows > Inventory. Validate that all HELPER - CanvasApp Operations flow is turned on and confirm that there are no unmanaged layers as shown here.
>    ![image](https://user-images.githubusercontent.com/89584709/261634052-598b5024-2e1a-4390-a6b2-49644368c246.png)
> 2. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
>    ![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

No Unmanaged Layers and only core components :

![image](https://github.com/microsoft/coe-starter-kit/assets/135959294/b3620776-d324-4e1a-a984-a7a0a3a0b1e0)

**Comment by Jenefer-Monroe** [comment] 2023-11-26 19:15
Looks like this may be the same issue as https://github.com/microsoft/coe-starter-kit/issues/7060

**Comment by Jenefer-Monroe** [comment] 2023-11-26 19:16
Can you please confirm what the error message is that is returned?

**Comment by Jenefer-Monroe** [comment] 2023-12-05 12:14
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-12-05 12:14 UTC
Labels: duplicate, question, coe-starter-kit
