### ISSUE TITLE
[ALM Accelerator - BUG]: Bad Request error during activate flows

### ISSUE THREAD

**Issue by VaibhaviK2306** [microsoft/coe-starter-kit#5121] opened 2023-03-29 07:32 UTC
### Describe the issue

We have a solutions with some flows and apps but the deploy-test-.... pipeline fails at 'Activate Flows task' while turning on one of the flows with error, 
FaultException`1 - SetState : Setting Activity State in CRM... workflow |=> Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n  \"status\": 404,\r\n  \"message\": \"List View Not Found\\r\\nclientRequestId: a65d9080-375f-44e5-b4f8-72597c969284\\r\\nserviceRequestId: a65d9080-375f-44e5-b4f8-72597c969284\"\r\n}'."}}".
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n  \"status\": 404,\r\n  \"message\": \"List View Not Found\\r\\nclientRequestId: a65d9080-375f-44e5-b4f8-72597c969284\\r\\nserviceRequestId: a65d9080-375f-44e5-b4f8-72597c969284\"\r\n}'."}}". => Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n  \"status\": 404,\r\n  \"message\": \"List View Not Found\\r\\nclientRequestId: a65d9080-375f-44e5-b4f8-72597c969284\\r\\nserviceRequestId: a65d9080-375f-44e5-b4f8-72597c969284\"\r\n}'."}}".[TerminalFailure] Failed to Execute Command - SetState : RequestID=a6cf4f5c-1419-4d8a-b8f4-228cb396055a : Setting Activity State in CRM... workflow duration=00:00:12.9746275 ExceptionMessage = Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n  \"status\": 404,\r\n  \"message\": \"List View Not Found\\r\\nclientRequestId: a65d9080-375f-44e5-b4f8-72597c969284\\r\\nserviceRequestId: a65d9080-375f-44e5-b4f8-72597c969284\"\r\n}'."}}".
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n  \"status\": 404,\r\n  \"message\": \"List View Not Found\\r\\nclientRequestId: a65d9080-375f-44e5-b4f8-72597c969284\\r\\nserviceRequestId: a65d9080-375f-44e5-b4f8-72597c969284\"\r\n}'."}}". => Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n  \"status\": 404,\r\n  \"message\": \"List View Not Found\\r\\nclientRequestId: a65d9080-375f-44e5-b4f8-72597c969284\\r\\nserviceRequestId: a65d9080-375f-44e5-b4f8-72597c969284\"\r\n}'."}}".

There is no GetTable sharepoint step in the flow, the connections are not reflecting in the target environment for the flow

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2023

**Comment by mikefactorial** [comment] 2023-03-29 20:35
@VaibhaviK2306 thanks for reporting this. Might be a persmission issue with the service principal accessing the sharepoint list. Will need to investigate this further.

**Comment by mikefactorial** [comment] 2023-06-26 18:11
Revisiting this issue it looks as though the Sharepoint environment variable is either pointing to a non-existent list or is not specified causing the Flow Activation to fail. Closing as not reproducible since we've validated on our end that the Sharepoint environment variables are carried over correctly into downstream environments and activating the associated flows doesn't cause any errors.

**Closed by mikefactorial** 2023-06-26 18:11 UTC
Labels: bug, alm-accelerator
