### ISSUE TITLE
[AA4PP - QUESTION] How to bypass the HTTP with azure AD consent when a user opens AA4PP for the 1st time ?

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#5948] opened 2023-06-27 18:58 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When a user opens AA4PP the first time, a prompt appears and the user needs to input the url https://graph.microsoft.com/

[image
](https://user-images.githubusercontent.com/10110260/248827544-8179ae21-4d67-4733-b1f4-df2b55065bfb.png)

So i tried to bypass the consent with this helpful page https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/set-adminpowerappapistobypassconsent?view=pa-ps-latest.

But it doesn't work for this connector.

I hope you can help me with that. 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by mikefactorial** [comment] 2023-07-07 21:24
@tocri this looks like a duplicate of #6021. Please don't open multiple issues for the same request. Closing this out

**Closed by mikefactorial** 2023-07-07 21:24 UTC
Labels: question, alm-accelerator
