### ISSUE TITLE
[CoE Starter Kit - BUG] App Catalog - PowerAppsforAppMakers.GetConnectors failed

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#4762] opened 2023-02-09 11:47 UTC
### Describe the issue

After starting the **App Catalog** this error message appears:
 
```
PowerAppsforAppMakers.GetConnectors failed: { "error": { "code": "ServiceToServiceEnvironmentNotFound", "message": "The environment 'Default-' could not be found in the tenant '94d30528-464f-45a5-a95e-816428f57b90'." } }
```

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/15800069/217803801-52213205-9dd0-4b04-87ef-ef689189bbf5.png">

And yes, we have renamed the environment:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/15800069/217804473-a54d6359-4534-47d5-9dd4-d2b264dd5d67.png">

### Expected Behavior

Default environment is identified correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2023

### What app or flow are you having the issue with?

App Catalog

**Comment by manuelap-msft** [comment] 2023-02-09 12:13
Duplicate of #4745. Closing as duplicate, as we're already tracking this. We are planning to do a UX refresh of the App Catalog for March (in line with the refresh of other apps we've done with the February release) and will address the issue then. The UX refresh is tracked under #4746

**Closed by manuelap-msft** 2023-02-09 12:13 UTC
Labels: bug, coe-starter-kit
