### ISSUE TITLE
[ALM Accelerator - QUESTION]: Error installing Powershell Modules

### ISSUE THREAD

**Issue by shauryanigam-1** [microsoft/coe-starter-kit#2435] opened 2022-04-12 12:13 UTC
### Describe the issue

We are implementing ALM functionality for PowerApps using Azure Devops, at this moment we are able to migrate the solution to other environments using devops. But solution ownership gets changed and get assigned to service principal used in Job. Also we want to change ownership as per convenience by passing a parameter. 
For this we are using ALM Accelerator templates from below URL.
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/update-canvas-app-ownership.yml 
We are able to install modules but are unable to import them in pipeline as we get error msg as 
_

**The module to process
'Microsoft.PowerApps.Administration.Powershell.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest
'/home/vsts/.local/share/powershell/Modules/Microsoft.PowerApps.Administration.PowerShell/2.0.105/Microsoft.PowerApps.Administration.PowerShell.psd1' was not processed because no valid module was found in any module directory.**

_

### Expected Behavior

It should be able to import modules after successfully installing it.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Not Known

### Steps To Reproduce

The module to process
     | 'Microsoft.PowerApps.Administration.Powershell.psm1', listed
     | in field 'ModuleToProcess/RootModule' of module manifest
     | '/home/vsts/.local/share/powershell/Modules/Microsoft.PowerApps.Administration.PowerShell/2.0.105/Microsoft.PowerApps.Administration.PowerShell.psd1' was not processed because no valid module was found in any module directory.

### Anything else?

The module to process
     | 'Microsoft.PowerApps.Administration.Powershell.psm1', listed
     | in field 'ModuleToProcess/RootModule' of module manifest
     | '/home/vsts/.local/share/powershell/Modules/Microsoft.PowerApps.Administration.PowerShell/2.0.105/Microsoft.PowerApps.Administration.PowerShell.psd1' was not processed because no valid module was found in any module directory.

**Comment by mikefactorial** [comment] 2022-04-12 19:44
@shauryanigam-1 I'll try to assist here, but it sounds like you are using our templates as a reference rather than as intended in conjunction with the ALM Accelerator. As such we can only provide so much guidance since we don't know the internal workings of your pipelines. Any additional information you can provide in the way of how your pipelines operate would be helpful since I can't tell based on the description what exactly you've implemented.

You can see how and where we install the powershell modules we use in this template if it is helpful.
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/install-powershell-modules.yml

**Comment by shauryanigam-1** [comment] 2022-04-13 10:33
Hi Mike,

Thanks for responding to our issue.

We actually tried to migrate our power platform solution from Dev to Stage environment which has been successfully implemented through devops pipeline , the other thing that we are trying to achieve is making the solution owner in test environment as per our convenience for which Microsoft support team has suggested us to use ALM accelerator and few of it script which is actually not working at our end.

We are not mixing this script with some other pipeline and using this script in other pipeline from scratch. We tried Install module script that you suggested earlier but we were facing some issues so what we did we tried installing it separately, it gets installed successfully but modules are not imported so it didn’t worked.
Kindly help us on this issue.

Regards
Shaurya Nigam

**Comment by mikefactorial** [comment] 2022-04-18 16:20
@shauryanigam-1 in the powershell file I referenced previously you'll see that we are installing the powershell modules into a specific folder (https://github.com/microsoft/coe-alm-accelerator-templates/blob/05ad5e278cffd00beec71189506e38ac5bee2b01/Pipelines/Templates/install-powershell-modules.yml#L18) on the host agent (this is to handle caching of modules so they are not downloaded on each run). We then set a global variable for the other templates to use to import the modules https://github.com/microsoft/coe-alm-accelerator-templates/blob/05ad5e278cffd00beec71189506e38ac5bee2b01/Pipelines/Templates/install-powershell-modules.yml#L38 (e.g. . CoETools_Microsoft_PowerApps_Administration_PowerShell)

The above variable is used in the update-canvas-app-ownership.yml to tell the Import-Module command where to look for the installed powershell module https://github.com/microsoft/coe-alm-accelerator-templates/blob/05ad5e278cffd00beec71189506e38ac5bee2b01/Pipelines/Templates/update-canvas-app-ownership.yml#L9

My assumption is that the update-canvas-app-ownership.yml cannot find the module to import because it's not being installed in the expected location assuming based on your response that you are not using https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/install-powershell-modules.yml to install the modules. 

Let me know if this helps.

**Comment by shauryanigam-1** [comment] 2022-04-20 12:23
Hi Mike,
Thanks for your efforts on our issue.

I tried this approach, since this script https://github.com/microsoft/coe-alm-accelerator-templates/blob/05ad5e278cffd00beec71189506e38ac5bee2b01/Pipelines/Templates/install-powershell-modules.yml#L18 is having a dependency of variable   $powerPlatformToolsPath. So I combined this script with following script, https://github.com/microsoft/coe-alm-accelerator-templates/blob/05ad5e278cffd00beec71189506e38ac5bee2b01/Pipelines/Templates/set-tools-paths.yml
where this variable $powerPlatformToolsPath is already initialized, please let me know if this understanding is correct.

But while executing the combined script I got following error.

> _/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/a68c1866-40d7-42e8-b140-a884fd114bff.ps1'
> Installing PS module Microsoft.Xrm.Data.PowerShell - 2.8.12 ...
> Get-ChildItem: /home/vsts/work/_temp/a68c1866-40d7-42e8-b140-a884fd114bff.ps1:44
> Line |
>   44 |        $moduleItems = Get-ChildItem -Path $savedModulePath
>      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot find path
>      | '/home/vsts/work/1/_coe/ALM_ACC/Microsoft.Xrm.Data.PowerShell/2.8.12' because it does not exist._

I tried this approach earlier as well, at that time as well I got same error. Please let me know where we can improve. 

 Also while importing the modules we had omitted the reference to CoETools_Microsoft_PowerApps_Administration_PowerShell. And used something like below:

 Import-Module Microsoft.PowerApps.Administration.PowerShell -Force  -ArgumentList @{ NonInteractive = $true }
    Add-PowerAppsAccount -TenantID $(TenantId) -ApplicationId $(ClientId) -ClientSecret $(ClientSecret)

 Import-Module Microsoft.Xrm.Data.PowerShell -Force  -ArgumentList @{ NonInteractive = $true }

Where we had populated these variables $(TenantId), (ClientId),(ClientSecret) in Variable Group (Library).

Kindly help us on this issue.
Regards
Shaurya Nigam

**Comment by shauryanigam-1** [comment] 2022-05-04 11:04
Hi Mike,
Thanks for sparing your time to help us!
Did you got any chance to see this issue of installing modules?
Kindly let us know.
Your further support support is much appreciated.

Regards
Shaurya Nigam

**Comment by shauryanigam-1** [comment] 2022-10-11 08:34
++Chaitanya

Hi Mike,

Thanks for responding to our issue.

We actually tried to migrate our power platform solution from Dev to Stage environment which has been successfully implemented through devops pipeline , the other thing that we are trying to achieve is making the solution owner in test environment as per our convenience for which Microsoft support team has suggested us to use ALM accelerator and few of it script which is actually not working at our end.

We are not mixing this script with some other pipeline and using this script in other pipeline from scratch. We tried Install module script that you suggested earlier but we were facing some issues so what we did we tried installing it separately, it gets installed successfully but modules are not imported so it didn’t worked.
Kindly help us on this issue.

Regards
Shaurya Nigam


From: Mike Ochs ***@***.***>
Sent: 13 April 2022 01:14
To: microsoft/coe-starter-kit ***@***.***>
Cc: Nigam, Shaurya ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [ALM Accelerator - BUG]: ISSUE TITLE (Issue #2435)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


@shauryanigam-1<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shauryanigam-2D1&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=oOy2Md8JfvxWR1wgoyaKCluAhXhjEsfj_8wTygFu8QI&m=em5WRkgR7cQb2blGJ7ZqqPXYju2Tik9K8Ksckc7dydJkdt7I7Pewe_yg_Js8VTga&s=ogo__a-NAIfkk9isxwdqGO7KnoXad90jbKhm3SoQmV0&e=> I'll try to assist here, but it sounds like you are using our templates as a reference rather than as intended in conjunction with the ALM Accelerator. As such we can only provide so much guidance since we don't know the internal workings of your pipelines. Any additional information you can provide in the way of how your pipelines operate would be helpful since I can't tell based on the description what exactly you've implemented.

You can see how and where we install the powershell modules we use in this template if it is helpful.
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/install-powershell-modules.yml<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dalm-2Daccelerator-2Dtemplates_blob_main_Pipelines_Templates_install-2Dpowershell-2Dmodules.yml&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=oOy2Md8JfvxWR1wgoyaKCluAhXhjEsfj_8wTygFu8QI&m=em5WRkgR7cQb2blGJ7ZqqPXYju2Tik9K8Ksckc7dydJkdt7I7Pewe_yg_Js8VTga&s=YbbLE6dzXaM3aUvTbBGfrKTdoA7CK4TE0bdW7P75waY&e=>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_2435-23issuecomment-2D1097144179&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=oOy2Md8JfvxWR1wgoyaKCluAhXhjEsfj_8wTygFu8QI&m=em5WRkgR7cQb2blGJ7ZqqPXYju2Tik9K8Ksckc7dydJkdt7I7Pewe_yg_Js8VTga&s=0eoTsNF6_7vbmPWp-GLaY2j952vJpY6dwRYkPglfmXg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AXVYACE5H22K2CLQ5TNDBNLVEXHAVANCNFSM5THDKFKA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=oOy2Md8JfvxWR1wgoyaKCluAhXhjEsfj_8wTygFu8QI&m=em5WRkgR7cQb2blGJ7ZqqPXYju2Tik9K8Ksckc7dydJkdt7I7Pewe_yg_Js8VTga&s=ISG5M0JXrq2xWqPPosQdPw_TEcVM1028AuU-HgmXlFA&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by mikefactorial** [comment] 2022-10-17 14:42
@shauryanigam-1 the powershell modules in question are windows powershell based and not compatible with powershell core. It's difficult to diagnose your issue, however, without a specific error message so I'm answering best I can. Can you please supply a specific error message that might help?

**Comment by mikefactorial** [comment] 2022-12-07 19:44
Closing out this issue as there is no more action required

**Closed by mikefactorial** 2022-12-07 19:44 UTC
Labels: question, alm-accelerator

**Comment by shauryanigam-1** [comment] 2022-12-29 14:12
Hi Mike,
Since we were using classic template, issue was resolved by setting correct path for Powershell modules

**Comment by muhameduvais** [comment] 2024-04-23 09:37
@shauryanigam-1  I am receiving the same issue as you have listed. Can you let me know how did you resolve the issue with the module path 

_Import-Module: The module to process 'Microsoft.PowerApps.Administration.Powershell.psm1',
listed in field 'ModuleToProcess/RootModule' of module manifest
'/home/vsts/.local/share/powershell/Modules/Microsoft.PowerApps.Administration.P
owerShell/2.0.180/Microsoft.PowerApps.Administration.PowerShell.psd1' was not
processed because no valid module was found in any module directory.

##[error]PowerShell exited with code '1'._

**Comment by shauryanigam-1** [comment] 2024-05-01 05:55
Hi @muhameduvais 
After adding Install Module command, add following lines of code.
$PowerAppsModulePath=(Get-Module -ListAvailable Microsoft.PowerApps.Administration*).path
$PowerAppsModulePath2=(Get-Module -ListAvailable Microsoft.Xrm.Data*).path
$Env:PSModulePath = $Env:PSModulePath+";$PowerAppsModulePath
$Env:PSModulePath = $Env:PSModulePath+";$PowerAppsModulePath2
This issue shall be resolved this way, as this sets path for powershell modules.
