### ISSUE TITLE
[CoE Starter Kit - BUG]CoE for Teams Flow Admin - Environment Request Fails to Create Database for New Environment

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1485] opened 2021-11-16 12:11 UTC
### Describe the issue

In the flow, Env Request | Create approved environment, the flow fails at the step Create Database with the following error message:

"error": {
    "code": "AuthorizationFailed",
    "message": "A client certificate or authorization header was not provided."
  }

It creates the environment successfully though.

### Expected Behavior

App should create a new environment and provision a database once authorised.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Admin - Environment Request

### Anything else?

![image](https://user-images.githubusercontent.com/17124284/141983068-d4477d4f-c91d-46e1-967b-dd5d98bf78d2.png)

**Comment by Jenefer-Monroe** [comment] 2021-11-16 13:04
assigned to area owner

**Comment by medicineshow** [comment] 2021-11-16 17:47
I should ad that the same user account that runs the flow can provision a database directly in the Power Platform admin centre

**Comment by medicineshow** [comment] 2021-11-18 09:00
Hi, do you have any response to this issue please?

**Comment by medicineshow** [comment] 2021-12-09 12:20
Any response please?

**Comment by denisem-msft** [comment] 2021-12-21 02:30
I cannot reproduce this in our test tenant. Do you have the appropriate access level and are you using recently refreshed connections? It sounds like your organization may have some network configuration that is stripping authentication headers from your requests. Please check with your IT department and ask them to assist in excluding Flow from any rules like this they might have.

For a consistent experience, you will need to have access enabled to a number of domains as described in the following document: https://docs.microsoft.com/en-us/flow/limits-and-config

Please contact your IT department to confirm if these rules are enabled.

**Comment by medicineshow** [comment] 2021-12-21 13:55
Can you please clarify a little more. I am the IT admin with Power Platform administrator rights. What do you mean by recently refreshed connections? Surely the flow is running in the cloud and there is no network restriction?

**Comment by denisem-msft** [comment] 2021-12-22 03:02
Regarding refreshed connections, can you please confirm whether the connection for the "Power Platform for Admins" connector have been refreshed recently? If you are not sure, you can re-create a new connection then assign the connection to the connection reference in the solution portal.

Power Platform for Admins connector documentation: https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/

See this article on how to view connections: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-manage-connections#update-or-delete-a-connection

If you recreate the connection for the Power Platform for Admins connector, you can then re-assign the connection reference (the one used in the "Env Request | Create approved database" Flow) to that new connection.

Please see this article on how to update a connection reference's connection here: https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-connection-reference

**Comment by Jenefer-Monroe** [comment] 2022-01-06 21:38
closing out due to lack of resonse

**Closed by Jenefer-Monroe** 2022-01-06 21:38 UTC
Labels: coe-starter-kit, core-components
