### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by GReZ44** [microsoft/coe-starter-kit#5679] opened 2023-05-30 16:00 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to configure the Compliance Process part of CoE but am met with an error stating that I am missing prerequisites, though these have already been imported and configured.

![image](https://github.com/microsoft/coe-starter-kit/assets/91034520/762b8b59-3676-40ba-b4a9-a6386b41d204)

The solutions that have been imported:
![image](https://github.com/microsoft/coe-starter-kit/assets/91034520/3a7b2feb-0d55-4d63-b8d7-c30bf100b98c)

Below are additional features with the green highlighted features having already been configured. The red highlighted feature is the one we're trying to configure and get the error with:
![image](https://github.com/microsoft/coe-starter-kit/assets/91034520/a84120eb-bda4-4b21-83fc-57bf275a09fe)

These were configured last week so there has been plenty of time for any flows to run and I can see from the Admin Centre and PBI report that it is picking up information.

### Expected Behavior

I'm expecting to be able to configure the compliance process and not see an error stating that prerequisites are missing.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

Compliance Process

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment] 2023-05-30 16:02
A few customers raised this issue with the Compliance wizard. Whilst we look into this, you can set up those components following the manual setup instructions:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#set-up-the-developer-compliance--request-components-manually

**Comment by manuelap-msft** [comment] 2023-05-30 16:03
Duplicate of #5637, closing out. Please follow #5637 for updates related to this issue.

**Closed by manuelap-msft** 2023-05-30 16:03 UTC
Labels: bug, duplicate, coe-starter-kit
