### ISSUE TITLE
[ALM Accelerator - BUG]: ALM Activation Flow Error

### ISSUE THREAD

**Issue by ShridharDeshpande** [microsoft/coe-starter-kit#3224] opened 2022-07-18 09:54 UTC
### Describe the issue

I've recently upgraded the ALM Accelerator version to CenterofExcellenceALMAccelerator-July2022. When I'm committing the solution in getting flow activation error while running pipeline. Even though solution has no flows to activate. In the April 2022 version, this was working. Can you help me to understand if I have missed any configuration or something?

![image](https://user-images.githubusercontent.com/47315792/179485861-f40f1a4b-d3aa-4610-a51c-e48244fcd6be.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2022

### Steps To Reproduce

1. Open the ALM Canvas App.
2. Choose the deployment profile for the solution.
3. Click on "COMMIT SOLUTION" and Enter the notes and name of the new branch.
4. Click on "COMMIT"

**Comment by mikefactorial** [comment] 2022-07-19 12:02
@ShridharDeshpande doesn't look like system diagnostics is giving us anymore information. Can you try updating Pipelines/Templates/activate-flows.yml with the following to see if we can see more detailed information about the exception in the logs? Specifically try adding  
```
        Write-Host $_
```
to the catch block
```
    . "$env:POWERSHELLPATH/activate-flows.ps1"
    try {
        Invoke-ActivateFlows '$(CdsBaseConnectionString)' '${{parameters.serviceConnection}}' '$(CoETools_Microsoft_Xrm_Data_PowerShell)' '$(XrmDataPowerShellVersion)' '$(CoETools_Microsoft_PowerApps_Administration_PowerShell)' '$(PowerAppsAdminModuleVersion)' '$(TenantId)' '$(ClientId)' '$(ClientSecret)' '${{parameters.solutionName}}' $(EnvironmentId) '${{parameters.solutionComponentOwnershipConfiguration}}' '${{parameters.connectionReferences}}' '${{parameters.activateFlowConfiguration}}'
    } catch {
        Write-Host "##vso[task.logissue type=warning]Errors occurred while activating flows. Please review the log for specific errors and verify your deployment configuration settings."
        Write-Host $_
        exit 1;
    }

```

**Comment by ShridharDeshpande** [comment] 2022-07-19 13:14
@mikefactorial I'm getting this response "The property 'sortOrder' cannot be found on this object. Verify that the property exists and can be set."

![image](https://user-images.githubusercontent.com/47315792/179758674-4dc1e692-593b-407c-a430-89646332460d.png)

**Comment by ShridharDeshpande** [comment] 2022-07-22 07:44
@mikefactorial I'm still facing this issue could you please help here

**Comment by mikefactorial** [comment] 2022-07-22 12:06
@ShridharDeshpande can you share the customDeploymentSettings.json that is generated for the specific branch that this deployment is running against? Would expect to see something similar to this for a solution with no flows. Specifically, for the ActivateFlowConfiguration and FlowShareWithGroupTeamConfiguration.
![image](https://user-images.githubusercontent.com/42348035/180435811-5578a068-fab5-4c36-aae4-c3248138c370.png)

**Comment by VishChandra** [comment] 2022-07-22 19:16
I'm facing the exact same issue - 
customDeploymentSettings.json
![image](https://user-images.githubusercontent.com/25315215/180510014-8662211b-1cf0-41fa-a7d2-1d3b4fa36853.png)

**Comment by mikefactorial** [comment] 2022-07-22 19:43
I've tried to replicate this multiple times with the current released version of the pipelines and the solution and haven't had any success. I'd recommend pulling the latest pipelines from https://github.com/microsoft/coe-alm-accelerator-templates into your AzDO pipeline and installing the latest version of the solution again.

**Comment by mikefactorial** [comment] 2022-07-22 19:44
If there is anything specific about your solution that may help to share let us know.

**Comment by mikefactorial** [comment] 2022-07-22 19:45
Also, if in your case this was an upgrade. Try exporting your solution again before deploying.

**Comment by VishChandra** [comment] 2022-07-22 19:47
I updated activate-flows.yml to Fixes #2449 (#134) version with following modifications and that solved the issue for me.

![image](https://user-images.githubusercontent.com/25315215/180516467-e7c1a126-894c-4392-95a2-c249de2aabcb.png)

![image](https://user-images.githubusercontent.com/25315215/180516387-eeb751de-f40d-41f2-abb9-98bf808e7f9c.png)

![image](https://user-images.githubusercontent.com/25315215/180516533-a16c0d0b-5358-4daf-b963-caca2886b4f5.png)

**Comment by mikefactorial** [comment] 2022-07-22 21:19
Interesting. So I assume you were on an earlier version of the pipelines?  @ShridharDeshpande is this the same case for you? We release updates to the app and the pipelines on a monthly schedule. Based on this @VishChandra looks like you were still on a pre April release?

**Comment by VishChandra** [comment] 2022-07-22 23:07
@mikefactorial no, I was on latest version and had to go back to the previous version and remove a few parameters from there to make it work.

**Comment by mikefactorial** [comment] 2022-07-22 23:12
Huh. That doesn't make any sense. Are all of your pipeline files on the latest version?

**Comment by mikefactorial** [comment] 2022-07-22 23:13
I installed the latest release of the ALM accelerator pipelines into my environment and didn't see this error with a solution that had no flows and the config you have. Don't know how you got out of sync with the latest version

**Comment by mikefactorial** [comment] 2022-07-22 23:15
There should be no reason to pull a specific branch or pr. Trying to wrap my head around how this happened.

**Comment by VishChandra** [comment] 2022-07-23 19:56
I know it doesn't make any sense but everything was up to date for me and I kept getting below error with latest version of [activate-flows.yml](https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/activate-flows.yml) -

![image](https://user-images.githubusercontent.com/25315215/180620696-8f1bfc58-8e55-4a2d-9cab-ae6ab5278611.png)

Then I changed the template to [this](https://github.com/microsoft/coe-alm-accelerator-templates/blob/4b91ed674c5a689800ac670f2f83409ee3f04cb6/Pipelines/Templates/activate-flows.yml) and fixed some parameters - 
![image](https://user-images.githubusercontent.com/25315215/180620895-e55ea4d7-e2a7-40a0-a137-a33a04e6d72f.png)
![image](https://user-images.githubusercontent.com/25315215/180620899-8e1da2d8-0762-4363-9df9-4ad8a4ac6851.png)

My Activate Flows job succeeded after that.

**Comment by ShridharDeshpande** [comment] 2022-07-24 15:38
@mike if there is no flows in solution then customDeploymentSettings.json is empty as you can see in below snap.

![image](https://user-images.githubusercontent.com/47315792/180654173-f9019b80-82bd-4295-93bd-8247fbbab026.png)

I've updates the ALM to latest July-2022 version. when I made changes to activate-flows.yml as pervious version and changed some parameter same as @VishChandra. mentioned. and now activate flows is working for me as well.

**Comment by mikefactorial** [comment] 2022-07-25 17:19
Hmm still struggling to understand what's going on here. I can't tell from the screenshots above what specifically was changed in your pipelines was it rolling back to the left side? Wouldn't expect that the changes you made to the parameters would fix anything, but rather they would break the ultimate call to the powershell script that gets executed. 

Ultimately, if you reverted back then you are not passing the solutionName parameter to the powershell but instead you're passing 'Activate Flows for Component Owners' which would likely mean that the activate flows step isn't fixed it's just skipping that step because it can't find a solution named 'Activate Flows for Component Owners' 

Unfortunately, the screenshots above cut off some of the YAML so it's hard to tell how the changes you made would have affected the call to the powershell script. 

Would it be possible to share the entirety of the activate-flows.yml in your current pipelines?

Just to follow through the process active-flows.yml expects the following parameters. 

```
parameters:
- name: solutionName
  type: string
- name: serviceConnection
  type: string
- name: solutionComponentOwnershipConfiguration
  type: string
- name: connectionReferences
  type: string
- name: activateFlowConfiguration
  type: string
```

These parameters are passed in from deploy-Solution.yml here https://github.com/microsoft/coe-alm-accelerator-templates/blob/eb8e423322bb352ab7632f7b121357fc2a695e00/Pipelines/Templates/deploy-Solution.yml#L256

[Snip]
```
- template: activate-flows.yml
  parameters:
    solutionName: ${{parameters.solutionName}}
    serviceConnection: ${{parameters.serviceConnectionUrl}}
    connectionReferences: '$(outConnectionReferences)'
    solutionComponentOwnershipConfiguration: '$(outSolutionComponentOwnershipConfiguration)'
    activateFlowConfiguration: '$(outActivateFlows)'
```

activate-flow.yml uses these parameters when calling the powershell function here https://github.com/microsoft/coe-alm-accelerator-templates/blob/eb8e423322bb352ab7632f7b121357fc2a695e00/Pipelines/Templates/activate-flows.yml#L19

[Snip]
```
Invoke-ActivateFlows '$(CdsBaseConnectionString)' '${{parameters.serviceConnection}}' '$(CoETools_Microsoft_Xrm_Data_PowerShell)' '$(XrmDataPowerShellVersion)' '$(CoETools_Microsoft_PowerApps_Administration_PowerShell)' '$(PowerAppsAdminModuleVersion)' '$(TenantId)' '$(ClientId)' '$(ClientSecret)' '${{parameters.solutionName}}' $(EnvironmentId) '${{parameters.solutionComponentOwnershipConfiguration}}' '${{parameters.connectionReferences}}' '${{parameters.activateFlowConfiguration}}'
```

The powershell expects these parameters here https://github.com/microsoft/coe-alm-accelerator-templates/blob/eb8e423322bb352ab7632f7b121357fc2a695e00/PowerShell/activate-flows.ps1#L1

[Snip]
```
function Invoke-ActivateFlows($cdsBaseConnectionString, $serviceConnection, $microsoftXrmDataPowerShellModule, $xrmDataPowerShellVersion, $microsoftPowerAppsAdministrationPowerShellModule, $powerAppsAdminModuleVersion, $tenantId, $clientId, $clientSecret, $solutionName, $environmentId, $solutionComponentOwnershipConfiguration, $connectionReferences, $activateFlowConfiguration) {
```

**Comment by kimjensen90** [comment] 2022-08-02 11:27
Hi @mikefactorial

I experience the exact same thing as described above - I updated the solutions and scripts, which led to the pipelines failing. I have tried to do everything that you suggest in the above, but I am still left with the error: "The property 'sortOrder' cannot be found on this object. Verify that the property exists and can be set."

My solutions has a single test Flow. Any other suggestions or new findings from you side? I would like to avoid using the old scripts, as that doesn't seem like the preferred approach. 

![image](https://user-images.githubusercontent.com/104207653/182363025-269e2000-3f43-4452-8ea8-7b1e04e6ce74.png)

Thank you so much!

**Comment by mikefactorial** [comment] 2022-08-02 14:24
@kimjensen90 can you try visiting the deployment settings screen for your solution and saving the configuration again? Then export again and try to deploy? It's possible that we introduced an issue on upgrade here where it's expecting a value that wasn't set previously in the deployment settings.

**Comment by kimjensen90** [comment] 2022-08-02 18:08
@mikefactorial - thanks for the quick reply. 

Just tried to do the settings again, but the result is the same: 
![image](https://user-images.githubusercontent.com/104207653/182443828-0d1cdbcd-7449-4a93-bc37-383b63d943b9.png)

Are there any specific updates to this in the August release?

**Comment by kimjensen90** [comment] 2022-08-02 18:59
@mikefactorial just updated the ALM Accelerator solution to the August version - still facing the same error. 

The variables in the pipeline looks like this: 
![image](https://user-images.githubusercontent.com/104207653/182452556-db279225-568a-4d15-b897-6bcf72d6cac8.png)

The values don't seem to be updated.

**Comment by mikefactorial** [comment] 2022-08-02 19:43
Thanks for the screenshot. That gets us a little closer to the answer. Wouldn't expect those to be empty or at the very least would expect activateflow.activate and activateflow.order to have values after running through the various environments in the deployment settings screen and exporting again. 

If you go the last run of the export pipeline and click Run New can you share what you see in the Data parameter? 

![image](https://user-images.githubusercontent.com/42348035/182459759-ec8fb26f-45d7-4159-b21b-4ad777f2c276.png)

![image](https://user-images.githubusercontent.com/42348035/182459957-72a5a350-4c6a-43b4-8a28-97d024d4218f.png)

**Comment by kimjensen90** [comment] 2022-08-02 20:02
@mikefactorial - let's see if we can get to the bottom of this. It looks like this: 
![image](https://user-images.githubusercontent.com/104207653/182462637-ce4d562c-86fc-4ea5-a521-83f060b66d97.png)

It begins with "deploy-test...", but the other builds (validation and prod) are in there too. 

Hope this gives you something. Let me know what else I can share with you.

**Comment by kimjensen90** [comment] 2022-08-02 20:09
...and these are the values for the validation part: 

{"BuildName":"deploy-validation-ThisisMYsolution","DeploymentEnvironmentName":"Validation","DeploymentEnvironmentUrl":"https://demo-dev.crm4.dynamics.com/","EnvironmentUrl":"https://coe-xxxxxgroup.crm4.dynamics.com/","ServiceConnectionName":null,"UserSettings":[{"Name":"connectionreference.xxxxx_DataverseConnection","Value":"74826767735a411682cf3dd095adf70c"},{"Name":"connectionreference.user.xxxxx_DataverseConnection","Value":"65812129-0307-4ab0-bf82-ec5595cc3c7d"},{"Name":"environmentvariable.xxxxx_ThisisMYenvironmentvar","Value":"TEst"},{"Name":"environmentvariable.xxxxx_justavariable","Value":null},{"Name":"environmentvariable.xxxxx_SharepointSite","Value":"https://xxxxxgroup.sharepoint.com/sites/ALMAcceleratorSampleSolution"},{"Name":"environmentvariable.xxxxx_SharepointList","Value":"38d56545-bbf1-40d1-ab44-1989ab519223"},{"Name":"canvasshare.aadGroupId.xxxxx_thisismyapp_71e5f","Value":""},{"Name":"canvasshare.roleName.xxxxx_thisismyapp_71e5f","Value":"CanView"},{"Name":"owner.ownerEmail.Thisisjustaflow.7c422983-f2d1-ec11-a7b5-000d3add24e5","Value":"kim.jensen@xxxxx.com"},{"Name":"flow.sharing.Thisisjustaflow.7c422983-f2d1-ec11-a7b5-000d3add24e5","Value":""},{"Name":"activateflow.activateas.Thisisjustaflow.7c422983-f2d1-ec11-a7b5-000d3add24e5","Value":"kim.jensen@xxxxx.com"},{"Name":"activateflow.order.Thisisjustaflow.7c422983-f2d1-ec11-a7b5-000d3add24e5","Value":"1"},{"Name":"activateflow.activate.Thisisjustaflow.7c422983-f2d1-ec11-a7b5-000d3add24e5","Value":"true"}]}]

**Comment by mikefactorial** [comment] 2022-08-02 20:32
Thanks for the quick response. Couple more questions. I think I might know what's happening but need to try to replicate again on my end

1. Are the values in the screenshot you provided for the deploy-validation-ThisisMYsolution or for another pipeline. If not do you see values in the deploy-validation-ThisisMYsolution pipeline variable?
2. Is the error you're seeing happening on the deploy-validation-ThisisMYsolution pipeline or another pipeline e.g. test or prod?
3. Can you share the customDeploymentSettings.json that's in the branch that you exported to e.g. 
![image](https://user-images.githubusercontent.com/42348035/182467854-19711d0b-c901-4498-8005-62809b7cd7a1.png)

**Comment by mikefactorial** [comment] 2022-08-02 20:51
Just a follow up. I missed your comment before last. I would expect the deploy-test variables to be blank based on the Data you posted. It looks like when you went through the deployment configuration it was only for the Validation environment. The drop down at the top of that screen lets you configure the other environments. 

![image](https://user-images.githubusercontent.com/42348035/182470818-3917c13b-4e2e-4733-9a3d-6a98dff77884.png)

I think we're narrowing in on the issue but could please answer the [questions in my previous post](https://github.com/microsoft/coe-starter-kit/issues/3224#issuecomment-1203185734) to help me to replicate?

**Comment by kimjensen90** [comment] 2022-08-02 21:12
@mikefactorial - my answers below: 

1. The values are from the export-solution-to-git pipeline that ran for the solution called: "ThisisMYsolution". The values of the variables in the deploy-validation-ThisisMYsolution are still empty: ![image](https://user-images.githubusercontent.com/104207653/182472817-1025958e-d36a-42da-a241-eed0c2320e2a.png)
2. For now, I have only seen it on the deploy-validation-ThisisMYsolution pipeline, as I haven't been able to move further than that in the process. I have tested some other "validation" pipelines too and received the same error. 
3. This is the customDeploymentSettings.json in the exported branch: 
![image](https://user-images.githubusercontent.com/104207653/182473806-72f0c203-f9b2-49c8-80cd-66be5a93545f.png)
4. I have done the deployment configurations for all environments - they are not the same, but they have values too. 

Happy to hear that we're narrowing in.

**Comment by mikefactorial** [comment] 2022-08-03 09:26
@kimjensen90 Well those weren't the answers I was expecting...even more confused now :) Can I ask you to do one more thing to help figure out where the specific error is occurring? In your local copy of https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/activate-flows.yml. 

Can you temporarily disable the try/catch as follows and rerun the pipeline? This should make the error message more clear about the specific line in the powershell where the script is failing.

```
    #try {
        Invoke-ActivateFlows '$(CdsBaseConnectionString)' '${{parameters.serviceConnection}}' '$(CoETools_Microsoft_Xrm_Data_PowerShell)' '$(XrmDataPowerShellVersion)' '$(CoETools_Microsoft_PowerApps_Administration_PowerShell)' '$(PowerAppsAdminModuleVersion)' '$(TenantId)' '$(ClientId)' '$(ClientSecret)' '${{parameters.solutionName}}' $(EnvironmentId) '${{parameters.solutionComponentOwnershipConfiguration}}' '${{parameters.connectionReferences}}' '${{parameters.activateFlowConfiguration}}'
    #} catch {
    #   Write-Host "##vso[task.logissue type=warning]Errors occurred while activating flows. Please review the log for specific errors and verify your deployment configuration settings."
    #    Write-Host $_
    #    exit 1;
    #}
```

**Comment by kimjensen90** [comment] 2022-08-03 09:47
@mikefactorial - I'm sorry about that. ;-) Sure, I'm very keen on finding culprit. 

I did as you ask and here is the result: 
##[debug]Entering Invoke-VstsTool.
##[debug] Arguments: '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\f2e7922a-823c-4772-ab62-373a2a097955.ps1'"'
##[debug] FileName: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug] WorkingDirectory: 'D:\a\1\s'
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\f2e7922a-823c-4772-ab62-373a2a097955.ps1'"
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\pa\2.0.148\Microsoft.PowerApps.Administration.PowerShell - 2.0.148
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.AuthModule' include unapproved verbs 
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include 
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the 
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\da\2.8.14\Microsoft.Xrm.Data.PowerShell - 2.8.14
ForEach-Object : The property 'sortOrder' cannot be found on this object. Verify that the property exists and can be 
set.
At D:\a\1\PipelineUtils\PowerShell\activate-flows.ps1:52 char:30
+ ... onConfigs | ForEach-Object { if ($_.sortOrder -match '^\d+$') { $_.so ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound,Microsoft.PowerShell.Commands.ForEachObjectCommand
 
##[debug]Exit code: 1
##[debug]Leaving Invoke-VstsTool.
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed]Error detected
##[debug]Leaving D:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.200.0\powershell.ps1.
Finishing: Activate Flows

And picture: 
![image](https://user-images.githubusercontent.com/104207653/182578601-fb200c5b-b88c-4717-ad44-d09f83fe6975.png)

**Comment by mikefactorial** [comment] 2022-08-03 10:47
@kimjensen90 thanks for that. Helped to determine where the failure is occurring and I can see that you're on the July release, but I'm going to have to ask you for another favor. In your local copy of https://github.com/microsoft/coe-alm-accelerator-templates/blob/CenterofExcellenceALMAccelerator-July2022/PowerShell/activate-flows.ps1.

Can you add the following above line 49 and run again? Thanks again.
```
Write-Host "Activation Config " 
```

e.g. 

```
function Get-ActivationConfigurations($activateFlowConfiguration) {
    Write-Host "Acitivation Config " $activateFlowConfiguration
    $activationConfigs = $null
    if ($activateFlowConfiguration -ne "") {
        $activationConfigs = ConvertFrom-Json $activateFlowConfiguration
        $activationConfigs | ForEach-Object { if ($_.sortOrder -match '^\d+$') { $_.sortOrder = [int]$_.sortOrder } else { $_.sortOrder = [int]::MaxValue } }
    }
    return $activationConfigs
}
```

**Comment by kimjensen90** [comment] 2022-08-03 11:24
@mikefactorial - just did and the result seems quite similar, to me at least: 
![image](https://user-images.githubusercontent.com/104207653/182596305-6859de9b-8c3f-4d35-94df-5c112465c696.png)

##[debug]Entering Invoke-VstsTool.
##[debug] Arguments: '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\af8fd1a6-68bb-43f3-a8c9-00e1e74b7592.ps1'"'
##[debug] FileName: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug] WorkingDirectory: 'D:\a\1\s'
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\af8fd1a6-68bb-43f3-a8c9-00e1e74b7592.ps1'"
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\pa\2.0.148\Microsoft.PowerApps.Administration.PowerShell - 2.0.148
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.AuthModule' include unapproved verbs 
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include 
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the 
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\da\2.8.14\Microsoft.Xrm.Data.PowerShell - 2.8.14
Activation Config   = 
ForEach-Object : The property 'sortOrder' cannot be found on this object. Verify that the property exists and can be 
set.
At D:\a\1\PipelineUtils\PowerShell\activate-flows.ps1:52 char:30
+ ... onConfigs | ForEach-Object { if ($_.sortOrder -match '^\d+$') { $_.so ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound,Microsoft.PowerShell.Commands.ForEachObjectCommand
 
##[debug]Exit code: 1
##[debug]Leaving Invoke-VstsTool.
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed]Error detected
##[debug]Leaving D:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.200.0\powershell.ps1.
Finishing: Activate Flows

**Comment by mikefactorial** [comment] 2022-08-03 12:12
@kimjensen90 can you try what I asked here as well https://github.com/microsoft/coe-starter-kit/issues/3224#issuecomment-1203785883? My assumption is that the value $activateFlowConfiguration parameter is not what that function is expecting it would be good to see what the value actually is.

**Comment by kimjensen90** [comment] 2022-08-03 12:35
@mikefactorial - my bad, I forgot a piece of it. I just copied your example instead. However, it still looks pretty similar to me? 
========================== Starting Command Output ===========================
##[debug]Entering Invoke-VstsTool.
##[debug] Arguments: '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\ee7444be-8f2a-4c93-bc3c-e29d0b4e4fe6.ps1'"'
##[debug] FileName: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug] WorkingDirectory: 'D:\a\1\s'
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\ee7444be-8f2a-4c93-bc3c-e29d0b4e4fe6.ps1'"
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\pa\2.0.148\Microsoft.PowerApps.Administration.PowerShell - 2.0.148
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.AuthModule' include unapproved verbs 
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include 
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the 
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\da\2.8.14\Microsoft.Xrm.Data.PowerShell - 2.8.14
Activation Config   
ForEach-Object : The property 'sortOrder' cannot be found on this object. Verify that the property exists and can be 
set.
At D:\a\1\PipelineUtils\PowerShell\activate-flows.ps1:53 char:30
+ ... onConfigs | ForEach-Object { if ($_.sortOrder -match '^\d+$') { $_.so ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound,Microsoft.PowerShell.Commands.ForEachObjectCommand
 
##[debug]Exit code: 1
##[debug]Leaving Invoke-VstsTool.
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed]Error detected
##[debug]Leaving D:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.200.0\powershell.ps1.
Finishing: Activate Flows


This is my script in activateflows.ps1 line 48 to 56:
`function Get-ActivationConfigurations($activateFlowConfiguration) {
    Write-Host "Activation Config " $activateFlowConfiguration
    $activationConfigs = $null
    if ($activateFlowConfiguration -ne "") {
        $activationConfigs = ConvertFrom-Json $activateFlowConfiguration
        $activationConfigs | ForEach-Object { if ($_.sortOrder -match '^\d+$') { $_.sortOrder = [int]$_.sortOrder } else { $_.sortOrder = [int]::MaxValue } }
    }
    return $activationConfigs
}`

Not sure why it renders like that but it looks like this: 
![image](https://user-images.githubusercontent.com/104207653/182609159-c8486138-6aa5-425d-8a7d-941ee2b757c4.png)

**Comment by mikefactorial** [comment] 2022-08-03 15:17
The plot thickens...wouldn't have expected the parameter to be blank. Can you share with me the log for the step Check if Deployment Settings Exists.
![image](https://user-images.githubusercontent.com/42348035/182643760-edccec7c-06e5-4572-b943-b62ee2055947.png)

Also, if you look at the Artifacts on the pipeline run do you see the following?
![image](https://user-images.githubusercontent.com/42348035/182644613-c4e894b6-edb2-450a-b837-8ed704426993.png)

Finally, in the Replace Tokens: * step do you see the following?

![image](https://user-images.githubusercontent.com/42348035/182644992-c7eb6065-cfe4-4718-bf0f-0baa92d5a449.png)

**Comment by mikefactorial** [comment] 2022-08-03 15:22
@kimjensen90 can you download your pipeline repo and attach it here?
![image](https://user-images.githubusercontent.com/42348035/182646225-674f3358-c283-42c1-bc38-8acf4d78da98.png)

**Comment by kimjensen90** [comment] 2022-08-03 17:01
@mikefactorial - logs including debug: 
![image](https://user-images.githubusercontent.com/104207653/182662607-85231f76-932e-45bf-a5e6-b015c913ed53.png)
![image](https://user-images.githubusercontent.com/104207653/182662733-72c910b5-a8ac-4569-b830-52abf162eff8.png)
![image](https://user-images.githubusercontent.com/104207653/182662813-d71dd1ae-e49e-4940-a5a2-c8d2e60dd10f.png)

This is what I see in the published artifacts - maybe that's what's missing?:
![image](https://user-images.githubusercontent.com/104207653/182665100-f340a35e-1c39-4e94-b64c-6e191bcdb228.png)

Finally, this is the tokens log: 
![image](https://user-images.githubusercontent.com/104207653/182665900-cd91ea47-d337-4a57-bf36-066f32244bad.png)
![image](https://user-images.githubusercontent.com/104207653/182666006-341543a5-ad46-44b6-b4f4-c4c8b4d87f97.png)
![image](https://user-images.githubusercontent.com/104207653/182666086-c3bdc7b6-b37f-4774-9cf8-ee43cafe97da.png)

And here are the zipped templates. 

[ALMAcceleratorTemplates.zip](https://github.com/microsoft/coe-starter-kit/files/9253572/ALMAcceleratorTemplates.zip)

So happy to collaborate on this.

**Comment by mikefactorial** [comment] 2022-08-03 17:50
@kimjensen90 thanks again! Finally had a breakthrough when looking at the logs. The issue is related to the name of the Azure Devops project having spaces in the name. The reason I wasn't able to duplicate it was due to the fact that all of my tests were with projects with no spaces. Looking into a fix for this in our August release which would require you to upgrade to that version once the fix is available. @ShridharDeshpande and @VishChandra wonder if you might be able to verify this is the case on your end as well.

**Closed** 2022-08-04 11:56 UTC
Labels: bug, alm-accelerator

**Comment by mikefactorial** [comment] 2022-08-04 12:02
This should be resolved now with the August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2022 and the latest pipelines in https://github.com/microsoft/coe-alm-accelerator-templates.
