### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI Cloud Flow details App

### ISSUE THREAD

**Issue by sayedpfe** [microsoft/coe-starter-kit#6190] opened 2023-07-28 08:49 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

we have issue with the Cloud Flow Details App, even after publishing the Dashboard and access the page with Drillthrough from Cloud Flows page we still getting the below errors

Office365Users.UserProfile failed: The method 'UserProfile' has an invalid value for parameter 'userId
Office365Users.UserProfileV2 failed: The method 'UserProfileV2' has an invalid value for parameter 'id'

the same app for Power Apps is working fine 

### Expected Behavior

to open the cloud flow details page without these errors, same ass the App for App Details 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin - Access this Flow [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1- access Cloud Flows Dashboard
2- Choose specific Flow 
3- right click then choose Drill Through -> Cloud Flow Details
4- when the Cloud Flow Details loaded we got these error on the app

**Comment by manuelap-msft** [comment] 2023-07-28 09:22
Hello,

this is a duplicate of #6164 and will be fixed with the August release, targeted for next week.

Closing as duplicate. Please follow issue #6164 for status update on when it's fixed.

Thank you
Manuela

**Closed by manuelap-msft** 2023-07-28 09:22 UTC
Labels: bug, coe-starter-kit
