### ISSUE TITLE
Unable to see many visuals for Power Platform Administration Planning Power BI report

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#6253] opened 2023-08-07 03:43 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/1c27f98f-1748-48c5-9f07-90a7dd3b4354)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/868367ca-059e-466c-b950-09d44aa2bce1)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/58b2b4d5-bc7e-4ea6-829a-1dd0e84f4615)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/564e9708-8384-49ce-beea-9f4b0085e8a3)

The columns defined for the visuals are missing in the data model. Please find some of the details missing

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/670cb981-ed17-4cee-87e1-bf59cb83c824)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/efc30d0a-4453-45db-a1d6-8ebc66081b17)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/415e42c7-058e-4fcf-af06-e1c57c2e1465)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/c050c638-3bd1-44e7-82de-c8b935434ae6)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/20c09c01-c961-4cec-99bd-9a7b3d64e402)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/025dc42d-3d48-48c1-832c-a75918c0dea7)

### Expected Behavior

The Administration Planning report should load correctly and get updated with the Aug 2023 release

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Administration Planning Dashboard

### What app or flow are you having the issue with?

Aug 2023 _ Power BI Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the PP Admin Planning pbit file from Aug 2023 setup and Provide environment url without prefix (https://) and postfix (/) details

**Comment by Jenefer-Monroe** [comment] 2023-08-07 11:06
I do repro this. Many visuals cannot find their field. Sending to area owner.


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7596f81f-5845-4308-b71b-c251aa8dbe02)

**Comment by manuelap-msft** [comment] 2023-08-07 15:05
Could you please check to see if this version works for you now:
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Power%20Platform%20Administration%20Planning.pbit

Thank you!

(The issue is due to how the PBI Dataverse connector returns fields for the data mapping. It used to return the unique name of a field, e.g. pcat_admintask, and now returns the display name, e.g. Admin Task. We have updated the PBIT file to point the visuals to the new names.)

**Comment by girishuppal** [comment] 2023-08-07 22:24
Perfect !!!  I tried loading the new PBIT file and published it to my PBI Workspace. It worked perfectly fine. Thanks for the quick turn around. Much appreciated.

**Comment by manuelap-msft** [comment] 2023-08-08 10:28
Wonderful, thanks for confirming that so quickly and alerting us this issue! We didn't test those two dashboard recently as we haven't made any changes in that area, and got caught out by a product change here! Thanks for letting us know about it so we could fix it!

**Comment by manuelap-msft** [comment] 2023-08-09 11:49
Closing out as this is now fixed, and the PBIT file has been updated in the release.

**Closed by manuelap-msft** 2023-08-09 11:49 UTC
Labels: bug, coe-starter-kit, product-gap
