### ISSUE TITLE
[ALM Accelerator - BUG]: Connector Import

### ISSUE THREAD

**Issue by mehakvij** [microsoft/coe-starter-kit#969] opened 2021-08-05 14:58 UTC
### Describe the issue

Hi all,  In the AA4AM, we are facing an issue where connectors aren't being deleted:

We have a source solution with 7 connectors. We imported that into the target environment. We then edit the original source solution and delete 2 connectors (resulting in a total of 5). However, when we import this into the target environment, the connectors aren't getting deleted. I've attached screenshots below to show.

![target](https://user-images.githubusercontent.com/73190679/128371793-1b78256f-f1ac-4718-857a-d37bac894fda.PNG)
![source](https://user-images.githubusercontent.com/73190679/128371797-925b1fab-30aa-4ab6-8e1c-1f05eb6f6225.PNG)

### Expected Behavior

We should result with only 5 connectors in the target environment after re-importing.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

1) Create solution with 7 connectors
2) import into a target env
3) Delete 2 connectors from original source solution
4) re-import into target env

**Comment by devkeydet** [comment] 2021-08-05 16:01
@mehakvij - This is not a bug.  This is how Solutions work natively in the platform.  If you want to have things no longer in the solution deleted from the target environment, you need to perform a solution upgrade.  See:
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/update-solutions

In the accelerator, we have a mechanism to inform the pipeline to perform a solution upgrade.  You can see the logic here:
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/deploy-Solution.yml

You can either label a PR with a label of "solution-upgrade" or you can manually set a variable named TriggerSolutionUpgrade to "true".  That will cause the pipeline to initiate the solution upgrade process.

I am closing this bug since this is how Solutions work and we already have mechanisms in the accelerator to handle this scenario.

HTH

**Closed** 2021-08-05 16:01 UTC
Labels: alm-accelerator

**Comment by mehakvij** [comment] 2021-08-05 16:12
Thank you!
