### ISSUE TITLE
[ALM Accelerator - Feature]: Update App to modern theming and controls

### ISSUE THREAD

**Issue by armanaxf** [microsoft/coe-starter-kit#6809] opened 2023-10-06 13:35 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

With more and more apps being modernised and using modern controls and themes, it would be great to see the ALM Accelerator use the modern controls and further make use of the Creator kit components.

**Comment by mikefactorial** [comment] 2023-10-10 12:29
@armanaxf thanks for the suggestion. We've considered this, however, we're currently not planning on investing heavily on the front end of the ALM Accelerator in favor of leveraging the in-product pipelines user interface and pipeline extensions to fill the gaps in functionality. However, we're always open to contributions if the community decides to take up this feature. Closing as won't implement for now.

**Closed by mikefactorial** 2023-10-10 12:29 UTC
Labels: enhancement, alm-accelerator

**Comment by mikefactorial** [comment] 2023-10-10 13:14
Duplicate of #4116
