### ISSUE TITLE
[CoE Starter Kit - BUG]no UPN(user email) in Audit Log for CoE Starter Kit 

### ISSUE THREAD

**Issue by tinghu2000** [microsoft/coe-starter-kit#3072] opened 2022-06-28 11:49 UTC
### Describe the issue

in CoE Starter Kit  Power BI report Audit Log table there is no email name. see please attachtment

![image](https://user-images.githubusercontent.com/102851701/176170902-8a33208a-9c63-406c-a702-a8ae4bd457e1.png)
[](url)

### Expected Behavior

we should see user email address here 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

power apps dashboard

**Comment by Jenefer-Monroe** [comment] 2022-06-28 13:31
Hello, there was a product change and this was fixed to match the new product behavior. 
You will need to update Core and then Audit Logs. 
Please see https://github.com/microsoft/coe-starter-kit/issues/2665

Marking as duplicate. Thanks for using CoE
Duplicate of #2665

**Closed by Jenefer-Monroe** 2022-06-28 13:31 UTC
Labels: bug, coe-starter-kit
