### ISSUE TITLE
[CoE Starter Kit - BUG] Not upgrading from 4.23 to 4.24 due to connection dependency

### ISSUE THREAD

**Issue by shubham45dg** [microsoft/coe-starter-kit#9147] opened 2024-10-18 09:41 UTC
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I did not upgraded COE starter kit since Feb 2024 and hence I am at version 4.23.
When I try to upgrade from 4.23 to 4.24 getting a dependency error saying that a connection reference is not being deleted due used by 18 flows.
 
I am not able to delete the connection reference or flows associated with it as it is a managed solution.
 
Connection reference name is : CoE Core - Dataverse Legacy. I will not be able to upgrade to latest version until this is resolved.

### Expected Behavior

Version should be upgraded to 4.24

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Connection Reference  CoE Core - Dataverse Legacy

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Import version 4.24 while current version is 4.23

**Comment by Jenefer-Monroe** [comment] 2024-10-21 13:03
Unfortunately it looks like you've hit a product bug around upgrade. A few other people have hit this too. Please see https://github.com/microsoft/coe-starter-kit/issues/8466. 
### The connection
This is likely the legacy Dataverse connection that is at play, why it wont tell you the name I don’t know. 
But this is a connection that we have removed from the kit and that is causing issues in the product’s upgrade code.
### The likely issue
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 
### Find impacted flows
Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8186341-cf26-4710-aa3c-8b3e3bb9f2ea)
### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.
And another user has succeeded with this workaround. See https://github.com/microsoft/coe-starter-kit/issues/8466

**Comment by Jenefer-Monroe** [comment] 2024-10-27 15:30
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-10-27 15:30 UTC
Labels: bug, coe-starter-kit
