### ISSUE TITLE
[CoE Starter Kit - BUG] Dataverse Accelerator Deployment causes failure in HELPER - Maker Check if Core Components version is lower than 4.13 (August release)

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6778] opened 2023-10-03 10:37 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

We are facing this with SYSTEM user account details, which is not available in "User Profile & Azure AD" services. We could see the logic for such accounts are written back as SYSTEM account from the "HELPER - Maker Check" child flow. 

We have one existing SYSTEM account , that is already added to the MAKERS table. But we are not able to find even that id under "User Profile & Azure AD" services. Not sure, how this got added by the COE solution.

Could you please let us know, the ways to add such SYSTEM accounts to the MAKERS table.

![image](https://github.com/microsoft/coe-starter-kit/assets/143060581/62166a5c-3d99-406c-b8db-28e8d56d9345)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1577

**Comment by manuelap-msft** [comment] 2023-10-03 10:42
Have you used the Setup Wizard to initially set up the Core Components? The wizard inserts the SYSTEM user into the Makers table.

**Comment by Rajeshgn053** [comment] 2023-10-03 10:51
Am not sure Manuelap.. Will check with the onsite team & confirm you. As far as my knowledge, they would have used the manual setup approach only. However, will confirm you in sometime.

FYI - Still i could see the logic in "HELPER - Maker Check", will just throw back the user object as SYSTEM, if it can't find the userid in "User Profile & Azure AD" services.  Which might need an correction.
On more thing, we are getting this for the following 2 OOB apps, which is synced on all environments - "Overview & Dataverse Actions page".

**Comment by orauch-a** [comment] 2023-10-03 14:37
For a week we have had the same problem.
And the maker id (SYSTEM) is the same : 00000000-0000-0000-0000-5157eaa02fcd

**Comment by jukkan** [comment] 2023-10-04 06:34
We have seen the exact same issue appear in a customer environment. The GUID of the owner is 00000000-0000-0000-0000-5157eaa02fcd.

This appears to be related to the forced deployment of Dataverse Accelerator App into each and every environment that has a Dataverse database in the tenant. The errors seem to be related to the Custom Pages used by that app, "Dataverse Actions Page" and "Overview". Possibly the global deployment process of this experimental app is using a different "SYSTEM" account and wreaking havoc?

FYI, the very same issue is causing errors also in the non-CoE flow template ["Get a list of new apps, Flows, and Connectors"](https://powerautomate.microsoft.com/en-US/templates/details/0b2ffb0174724ad6b4681728c0f53062/get-a-list-of-new-apps-flows-and-connectors/).

**Comment by manuelap-msft** [comment] 2023-10-04 07:47
@jukkan Thanks you, as always, for your great detective work and figuring out the root cause of this issue! Based on the comments here it looks like the GUID is the same across tenants, but I'll follow up with the Dataverse Accelerator App team to see if they can share some more details on the owner and deployment process so we can update our flows to handle that accordingly. 

We'll analyse the impact a bit more to decide on next steps - I believe the impact may be that the Dataverse Accelerator App can't be inventoried but the rest of the inventory should be working fine. Let me know if my assumption here isn't correct!

We've got our release ready and tested to go out today, so we'll have to discuss internally if we should delay the release because of this and fix it or if this can wait until November. We'll follow back up here!

**Comment by orauch-a** [comment] 2023-10-04 09:32
@manuelap-msft : your assumption is correct.
If you have a suggestion for a fix in this ticket, that would be great.

**Comment by manuelap-msft** [comment] 2023-10-04 09:48
@orauch-a 

I unfortunately don't repo this on my end yet - I believe the Dataverse Accelerator App currently only gets deployed to new Developer environments, so I'm just working on getting a few new Developer environments spun up in our development tenant so I can repo this and then running the inventory so I can check what the required fix is.

In the meantime, here's what you could try (caveat: I have not had a chance to try this myself yet): Add row into the Maker table with 00000000-0000-0000-0000-5157eaa02fcd as the GUID and SYSTEM as display name.

You need to populate
- Display Name: SYSTEM
- Maker (ID): 00000000-0000-0000-0000-5157eaa02fcd
- Record GUID as String: 00000000-0000-0000-0000-5157eaa02fcd

I believe the out of the box table edit experience doesn't allow you to modify the unique ID (Maker field) of the table, so you might have to write a simple flow or app that performs the "Add a row" action on that table and through that you can specify the GUID. I think having this GUID and record in the Maker table should address the issue. 

I'll get this tested on my end as well as soon as I repo it and report back.

**Comment by orauch-a** [comment] 2023-10-04 09:55
The problem is that we will then have 2 SYSTEM users in the table. And in the "HELPER Maker Check" first is used to retrieve the SYSTEM user

**Comment by manuelap-msft** [comment] 2023-10-04 10:58
Hm, I don't repo this in my tenant - @orauch-a  what Core components version are you on? Is it 4.8 as well or a later version?

**Comment by orauch-a** [comment] 2023-10-04 11:14
My version is 4.9

**Comment by Rajeshgn053** [comment] 2023-10-04 11:21
We do applied the same fix suggested by Manuela.. no new issues after that..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by orauch-a** [comment] 2023-10-04 11:32
This seems to be the same GUID on all tenants, wouldn't the following fix be better? This would avoid having 2 system users in the Maker table.
<img width="743" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/34766578/a78da8dc-2ac4-4dcd-a077-e2086ce60e5d">

**Comment by jukkan** [comment] 2023-10-04 13:43
@manuelap-msft This is not limited to Developer environments only. In our own tenant as well as many customer tenants, this is getting deployed to many Production and Sandbox environments as well. If the app creators in Power CAT team really intended this to be only targeted for Developer environments, then please alert them ASAP since at least in Europe the solution is spreading like wildfire.

**Comment by StylezDevops** [comment] 2023-10-04 13:48
To confirm the observations of @jukkan : We only have the starter kit setup on production type environments. Even our CoE Dev environment is a production environment. We have seen this behaviour across customer environments and our own internal CoE environments.

**Comment by manuelap-msft** [comment] 2023-10-04 13:54
@jukkan and @StylezDevops It was just misinformation on my end, it is being rolled out to all environments.

I don't repo the error you are seeing with the Helper - Maker Check flow in my tenant where I have the latest CoE kit version installed, and we did recently make some changes to the logic of that flow to make it more robust (version 4.15 and 4.13 should have the fix). If you could comment with the CoE Core Components version you have installed that you're seeing this issue with, we can determine if this is an error that's still present or if it has been fixed with a recent release already.

**Comment by manuelap-msft** [comment] 2023-10-04 13:59
> This seems to be the same GUID on all tenants, wouldn't the following fix be better? This would avoid having 2 system users in the Maker table. <img alt="image" width="743" src="https://user-images.githubusercontent.com/34766578/272559780-a78da8dc-2ac4-4dcd-a077-e2086ce60e5d.png">

Yes, that should work as well. I tried to make a change that would avoid creating unmanaged layers on the flow, but this change should work as well. Just bear in mind that if you create an unmanaged layer on this flow, it won't receive updates in the future when you upgrade & you'll have to remove the unmanaged layer for the upgrade to take. 

I actually don't repo this issue on my tenant - I've created a few new environments now that have the Dataverse Accelerator App installed and ran a full inventory and no flows failed to run. We did in more recent releases (4.13 and 4.15) make some changes to the Helper - Maker Check to make it more robust so it could be that as a by product of us making the flow more robust this issue is already addressed. I'm still investigating this, so these are just current observations.

**Comment by orauch-a** [comment] 2023-10-04 14:41
> > This seems to be the same GUID on all tenants, wouldn't the following fix be better? This would avoid having 2 system users in the Maker table. <img alt="image" width="743" src="https://user-images.githubusercontent.com/34766578/272559780-a78da8dc-2ac4-4dcd-a077-e2086ce60e5d.png">
> 
> Yes, that should work as well. I tried to make a change that would avoid creating unmanaged layers on the flow, but this change should work as well. Just bear in mind that if you create an unmanaged layer on this flow, it won't receive updates in the future when you upgrade & you'll have to remove the unmanaged layer for the upgrade to take.
> 
> I actually don't repo this issue on my tenant - I've created a few new environments now that have the Dataverse Accelerator App installed and ran a full inventory and no flows failed to run. We did in more recent releases (4.13 and 4.15) make some changes to the Helper - Maker Check to make it more robust so it could be that as a by product of us making the flow more robust this issue is already addressed. I'm still investigating this, so these are just current observations.

Thanks a lot. Yes I know that for unmanaged layers. I already have several flow that I had to correct for small bugs that I found

**Comment by StylezDevops** [comment] 2023-10-04 15:09
There is an API Org Request named RemoveActiveCustomizations @orauch-a 
not related to this thread.. but maybe useful info for you

**Comment by manuelap-msft** [comment] 2023-10-05 12:29
Update after investigation on our side:

It looks like this is an issue with older versions of Core components that was fixed with other work we did to make the Helper - Maker Check flow more robust. 

With the latest version (4.16, released yesterday), this app is correctly identified as SYSTEM owned and is shown in the inventory like other system owned apps - e.g. Solution Health Hub or Package Management View

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/518c42e6-6acb-4837-9504-f9de0a37e22d)

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/2bb11fee-9622-4a4c-bb97-26c0f8a020a3)

There's no flow failures with the latest version.

**Comment by cr0max** [comment] 2023-10-05 12:29
We are running version 4.13 (august) and do not have this issue. Even though we have the Dataverse Accelerator App in several environment Prod, Sandbox and Dev.

**Comment by orauch-a** [comment] 2023-10-06 13:12
For example when an environment is created by the system user, we have (id=SYSTEM and displayname=SYSTEM)
Here in for custom canvas pages, the system user is (id=00000000-0000-0000-0000-5157eaa02fcd and displayname=SYSTEM)
I looked at the contents of your latest version (4.16) and I don't think the problem is fixed in this latest version.

**Comment by manuelap-msft** [comment] 2023-10-06 14:16
Model Driven Apps are retrieved via the appmodule table in the environment. Custom pages are returned by the Get Apps as Admin action of the Power Apps for Admin connector. Although these pages show as SYSTEM in the environment, the connector returns them as being owned by the tenant admin. This is expected behaviour. So they are inventoried correctly. You can call the Get Apps as Admin in a standalone flow to observe that behaviour if you want. 

I've tested the 4.16 release now across three tenants and multiple environments in different regions, and we don't repo any errors. If you do run the inventory and see any errors, let us know.

**Comment by lukas-nC** [comment] 2023-10-11 10:22
> @orauch-a
> 
> I unfortunately don't repo this on my end yet - I believe the Dataverse Accelerator App currently only gets deployed to new Developer environments, so I'm just working on getting a few new Developer environments spun up in our development tenant so I can repo this and then running the inventory so I can check what the required fix is.
> 
> In the meantime, here's what you could try (caveat: I have not had a chance to try this myself yet): Add row into the Maker table with 00000000-0000-0000-0000-5157eaa02fcd as the GUID and SYSTEM as display name.
> 
> You need to populate
> 
> * Display Name: SYSTEM
> * Maker (ID): 00000000-0000-0000-0000-5157eaa02fcd
> * Record GUID as String: 00000000-0000-0000-0000-5157eaa02fcd
> 
> I believe the out of the box table edit experience doesn't allow you to modify the unique ID (Maker field) of the table, so you might have to write a simple flow or app that performs the "Add a row" action on that table and through that you can specify the GUID. I think having this GUID and record in the Maker table should address the issue.
> 
> I'll get this tested on my end as well as soon as I repo it and report back.

How do I modify or add a new row and enter a specific value in the Maker colum?

Having this problem at version 4.11

**Closed** 2024-02-05 14:05 UTC
Labels: question, coe-starter-kit
