### ISSUE TITLE
[CoE Starter Kit - BUG] Error on Admin Command Center

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2379] opened 2022-04-06 11:47 UTC
### Describe the issue

Hello, how can I resolve this error on Command Center? Thanks

![error](https://user-images.githubusercontent.com/101250592/161967722-9bca8034-e791-494b-9544-77789e94436e.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Open Admin - Command Center 
2. Go to Power Platform News

**Comment by manuelap-msft** [comment] 2022-04-06 12:22
Duplicate of #2205, which will be fixed with the April release.

**Closed by manuelap-msft** 2022-04-06 12:22 UTC
Labels: bug, coe-starter-kit
