### ISSUE TITLE
Can you suggest which flows are used for inventory and which for governance, etc

### ISSUE THREAD

**Issue by priyankagolatkargit** [microsoft/coe-starter-kit#8782] opened 2024-08-08 09:09 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Once the COE kit is enabled. It enables multiple flows. Some flows are used for inventory purpose, and some for governance and nurture. Some flows could trigger emails to the users/ or delete orphan flows and apps. Can you suggest which flows are used for inventory and which for governance so that we can turn off the governance flows and start them one at a time incrementally as required,

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment] 2024-08-08 16:22
Hello if you use the Setup Wizard it will walk you through what we call "solution areas". 

This "Initial Setup" will set up the "Inventory" components only and inventory flows only. 
![image](https://github.com/user-attachments/assets/0f8f786c-a94f-4a9b-a5a8-63c7ba5f5646)

You can then select individual setup of individual solution areas for set up after that on the "More features" screen. Shown here for example if you wanted to setup Inactivity Processes, you would select that and it would walk you through setup. 
![image](https://github.com/user-attachments/assets/b187a460-b25c-4c4f-9b42-68b14deb5555)

You can also view flows by solution area in the CoE Admin Command Center on the CoE Flows page. Shown here are the flows just for Inventory.
![image](https://github.com/user-attachments/assets/bc2ea35d-bb7b-4f6a-8770-050b6d9443bf)

The same is true for apps, you can view apps by solution area in the CoE Admin Command Center on the Bookmarks page.
![image](https://github.com/user-attachments/assets/501d4613-fdfb-4b0d-92db-ea05a3f66026)

Lastly, you can explore the mails sent from different solution areas in the CoE Admin Command Center on the Customize Emails page along with who the target is. As you can see for Inventory there are only Admin focused mails.
![image](https://github.com/user-attachments/assets/211c997b-7d25-4938-a7ce-df4ac3507667)

**Comment by Jenefer-Monroe** [comment] 2024-08-09 12:31
The three mails you highlighted are not from the inventory solution area, in my screenshot I filtered to the inventory solution area. Thats the only solution area that gets lit up by the Initial setup in the setup wizard
![image](https://github.com/user-attachments/assets/a6c2c45a-89a0-4934-a9a9-36e9774cb66c)

**Comment by Jenefer-Monroe** [comment] 2024-08-09 12:32
For the other apps, you can view this document where we describe [whats in the core components](https://learn.microsoft.com/power-platform/guidance/coe/core-components)

**Comment by priyankagolatkargit** [comment] 2024-08-09 12:55
@Jenefer-Monroe , The screenshot highlighting the email is for reference only. The question is about the target audience here being "Maker" and not "admin". How to disable those.
![image](https://github.com/user-attachments/assets/85256fa9-2f0e-4efd-86e9-94187bfa53d9)

Which governance flow are you highlighting? And is it required to manually turn off?

**Comment by Jenefer-Monroe** [comment] 2024-08-09 12:57
You can use the admin command center to go turn the flows off / ensure they are off, for any of the solution areas you do not want to run. I suggest you please go do that.
![image](https://github.com/user-attachments/assets/f83d6dbc-5b75-497e-a978-2357ca0a9213)

**Comment by Jenefer-Monroe** [comment] 2024-08-09 12:59
The 3 mails you highlighted are from the Environment Request and Compliance solution areas. So if you do not want to run those areas, you would go turn off the flows for those areas.
![image](https://github.com/user-attachments/assets/31f7e644-443f-473f-98bf-59139284206f)

**Comment by priyankagolatkargit** [comment] 2024-08-09 13:14
@Jenefer-Monroe In the initial document its mentioned to create two environments COE Production and COE Testing. Is it required that we upload the package to both?

**Comment by Jenefer-Monroe** [comment] 2024-08-09 13:21
Yes each environment will have you installing the solutions. The only difference between them should be the value you put in the Production Environment environment variable which you will see in the setup wizard. 
You should place this to No for your test environment. It will make all communication go to the admin and prevent things like deletion from occurring.
![image](https://github.com/user-attachments/assets/786baabc-b2e4-41a0-8458-78a45796e5ac)

**Comment by priyankagolatkargit** [comment] 2024-08-12 09:18
@Jenefer-Monroe , Thanks for the update. Do we also have to exclude both the COE Testing  / COE Production environment from the global DLP policy? Or can the environments be a part of the policy

**Comment by Jenefer-Monroe** [comment] 2024-08-12 13:13
That depends on your global DLP setup but likely yes you would need to do that. 
Here is the write up for the DLP requirements for CoE Starter Kit Envts [Validate data loss prevention (DLP) policies](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies)

**Comment by priyankagolatkargit** [comment] 2024-08-12 13:17
The article states to install creator kit first.. 

<img width="452" alt="image" src="https://github.com/user-attachments/assets/7aa8e020-6268-4fd3-892c-c6b93d2c331c">

However it says that the May version has issues. How will I get June 2024 versions...

<img width="618" alt="image" src="https://github.com/user-attachments/assets/894f6b52-e4e9-47ef-8c42-1af633429619">

**Comment by Jenefer-Monroe** [comment] 2024-08-12 14:54
That's strange, that is the version of Creator Kit I am using, and its actually required due to another change. 
I've asked the owners to see what this is referencing. I suspect its just a stale warning that needs cleaned up.

**Comment by Jenefer-Monroe** [comment] 2024-08-13 12:52
Good news, I confirmed with that team that this was a stale warning message. You are good to install the latest Creator Kit build.

**Comment by priyankagolatkargit** [comment] 2024-08-16 10:40
Hello @Jenefer-Monroe ,

I am getting the below error while configuring the wizard. 
<img width="623" alt="image" src="https://github.com/user-attachments/assets/bac99c28-f3b2-4c4c-867b-c8360ea960a2">

I have excluded the testing environment from the Global DLP policy, and add the same to a custom DLP policy where all the required connectors are allowed in business

Please suggest

**Comment by Jenefer-Monroe** [comment] 2024-08-16 11:35
Hello you are correct that its a DLP issue here that needs to be addressed but I"m not sure I can help repair from out here. 

Its likely one of the following : 
- Another DLP policy impacts the envt that you are unaware of, which is blocking. How many DLP policies do you have?
- You have not added all the required connectors to the test envts DLP ([connector list for DLP](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies))
- There is sometimes a time delay between updating DLP and seeing it propagate.

I would suggest:
1. Trying again after you allow time to propagate
2. Double check the connector list
3. Let me know how many total DLP policies exist in the tenant.

**Comment by priyankagolatkargit** [comment] 2024-08-19 12:11
Hi @Jenefer-Monroe 

We have published the dashboard, however the data is showing as blank 
<img width="675" alt="image" src="https://github.com/user-attachments/assets/eb3ff88b-4ac6-487c-bb6c-dc8992aabc8a">

the above is from Production Tenant but Testing powerplatform environment


Also I am seeing less options here in comparison to the screenshots you have shared

<img width="959" alt="image" src="https://github.com/user-attachments/assets/4ec00cac-1e33-4ec5-bf8e-cb4ee5ae201f">

**Comment by Jenefer-Monroe** [comment] 2024-08-20 02:00
Yes you have less options because you have only installed Core. That's expected. 
It looks like your inventory flows did not run. If you go to the Inventory tab on that CoE Flows page, do they all show as on? 
Go to this flow, is it still running? Admin | Sync Template v4 (Driver)

**Comment by priyankagolatkargit** [comment] 2024-08-20 06:21
@Jenefer-Monroe , Yes it shows on and running
<img width="640" alt="image" src="https://github.com/user-attachments/assets/c2b013c4-e995-4a19-8068-a529ae7c95d5">

**Comment by Jenefer-Monroe** [comment] 2024-08-20 14:07
I suggest you turn those 4 flows on, let me know if you get an error or if that works.  That woudl not explain the blank PBI but will prevent you from other functionality. 


Then open the Power Platform Admin View app, see you have data there. 
![image](https://github.com/user-attachments/assets/03f7eec2-fdfb-479b-b9ff-03849445b735)
![image](https://github.com/user-attachments/assets/be0c48fb-7a01-4025-ad39-670f620b4ae1)

**Comment by priyankagolatkargit** [comment] 2024-08-20 15:14
<img width="355" alt="image" src="https://github.com/user-attachments/assets/c52bd519-c159-44bb-8f4e-075b0431fe99">
ALso I am unable to pubslish this report, I have power bi Pro license, and trying to publish it on Power BI Premium Capacity Workspace

**Comment by Jenefer-Monroe** [comment] 2024-08-20 16:00
Sorry I cannot assist with questions bout PBI licensing, you will need to contact product support if your PBI license does not seem to be working.

**Comment by priyankagolatkargit** [comment] 2024-08-21 08:59
Hello @Jenefer-Monroe , I was able to publish the report. And After multiple refreshes get the data as well, It took possibly more than 48 hrs for it to pull all the data....

Also I am looking for Copilot Studio connectors? Or Custom copilot related information. ANy  idea where I can find the same. 
<img width="70" alt="image" src="https://github.com/user-attachments/assets/fa32167f-6ad8-475d-9e4c-db718c768c5d">

**Comment by priyankagolatkargit** [comment] 2024-08-21 14:02
@Jenefer-Monroe , which field are you referring to? The error one or the blank AI Builder credits

**Comment by Jenefer-Monroe** [comment] 2024-08-21 17:37
This one: 
![image](https://github.com/user-attachments/assets/c7841427-9f64-45e5-a36a-76a1e53753f6)

**Comment by priyankagolatkargit** [comment] 2024-08-21 18:41
@Jenefer-Monroe , The AI BUilder Credit usage report is blank? How to fetch that report??

![image](https://github.com/user-attachments/assets/e5d6f39f-f646-450c-b5df-71b02ffb301d)

**Comment by Jenefer-Monroe** [comment] 2024-08-21 18:53
Due to this bug: https://github.com/microsoft/coe-starter-kit/issues/8814
you are going to need to upgrade to the August release in order to see Ai Credit Usage.

As we have gone through many issues together here, and as its becoming hard to track where we are at in the investigation, please do the upgrade to August and then if you have further questions, please open a new issue.

**Comment by Jenefer-Monroe** [comment] 2024-08-28 18:04
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-08-28 18:04 UTC
Labels: question, coe-starter-kit
