### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2223] opened 2022-03-11 08:16 UTC
### Describe the issue

Hello, inside Power Apps section I see three times value "Scheda".
<img width="516" alt="bug" src="https://user-images.githubusercontent.com/101250592/157828536-72cc0bcc-6f37-4bef-bf38-d2bae116dee9.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Run Power Platform Admin View
2. Select an application in Power Apps section

**Comment by manuelap-msft** [comment] 2022-03-11 08:53
Hello,

the cause for this is likely that you do not have the english language pack installed on your CoE environment. The CoE is not available in localized languages but only in english. Please add the english language pack to the environment.

See more: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#supported-languages

**Comment by JackSocini** [comment] 2022-03-15 07:54
Thanks, this solve my problem!

**Comment by JackSocini** [comment] 2022-04-11 09:51
Hello,
after the last update the problem came out again..
How can I solved it?

Thanks

![lingua](https://user-images.githubusercontent.com/101250592/162713496-5c022572-2f02-4618-acfa-188db6a2a23f.jpg)

**Comment by manuelap-msft** [comment] 2022-04-11 10:28
Hello,

I'm not sure, this seems to be a product issue then - we only ship an english version of the CoE starter kit. Please raise a support ticket with Microsoft through official support channels to explore a fix for this: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

Thank you
Manuela

**Closed by manuelap-msft** 2022-04-11 10:28 UTC
Labels: question, coe-starter-kit
