### ISSUE TITLE
[ALM Accelerator - BUG]: ALM with the Flow configuration with its owner and activate user

### ISSUE THREAD

**Issue by will-franca** [microsoft/coe-starter-kit#5723] opened 2023-06-05 14:04 UTC
### Describe the issue

This is the screenshot of ALM with the Flow configuration with its owner and activate user, when run the ALM process to export it from validation to test environment, the owner has not been changed and the flow has not been activated as well.
![flows_active](https://github.com/microsoft/coe-starter-kit/assets/135626493/66e1f3b3-cb74-4e3e-a13d-9dd179c151c0)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 3.23012.17

**Comment by mikefactorial** [comment] 2023-06-06 02:21
@will-franca can you share the steps to reproduce? Did you run the export after making these settings? Any indication in the logs that it is finding these values during the deployment pipeline run? You can also check that the deployment pipeline contains the variable values after exporting.

**Comment by tomjosbin** [comment] 2023-06-06 09:26
@will-franca - Please share the Activate Flows step screenshot / log in the build and deploy job pipeline. Mostly the issue could be related to the owner being not added in the target environment.

**Comment by will-franca** [comment] 2023-06-07 21:17
![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/d2252ceb-0b45-499a-8233-ee3ed9069c50)

I am configuring the owners that I would like to change in the destination environment according to the image, but it is not changing the owner.


Follow the image of flow below in the target environment :

![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/17449128-e48b-4479-86c6-f25f85da1500)

Attach files the logs of pipeline.
[logs_3276.zip](https://github.com/microsoft/coe-starter-kit/files/11682030/logs_3276.zip)

**Comment by tomjosbin** [comment] 2023-06-08 03:09
From the logs it looks like either the Activation User / Owner specified doesn't exist in the target environment. Make sure these users are added to the target enviornment with atleast Basic User role.

**Comment by will-franca** [comment] 2023-06-19 14:41
I check if the user was in the environment, and the user is added and it keeps giving the same error. follow the images

![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/ca6d5ef5-e82a-4db1-aca9-6ec678cf3339)

![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/3f71eca7-14cf-49b5-8490-e34860034836)

**Comment by will-franca** [comment] 2023-06-19 17:20
The user is added.

**Comment by will-franca** [comment] 2023-06-19 17:21
Follow print screen.

**Comment by will-franca** [comment] 2023-06-22 21:27
It has access and continue the same error.

![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/372cbc52-8b39-4a3d-907b-b0367987b614)

[logs_3357.zip](https://github.com/microsoft/coe-starter-kit/files/11840567/logs_3357.zip)

**Comment by mikefactorial** [comment] 2023-06-29 16:31
@will-franca this is strange. Based on the error it is absolutely an issue with the pipelines finding the user specified. However, as you've demonstrated the user does exist and the username specified in the config matches the user's user name in Dataverse. Can I ask again what version of the solution you have installed? In your initial response you said "3.23012.17" but that's not a valid version for the accelerator solution. Would be something like 1.0.20230606.1

**Comment by will-franca** [comment] 2023-07-03 13:03
The version instaled is 1.0.20221206.2.

**Comment by mikefactorial** [comment] 2023-07-05 17:18
@will-franca that's release is pretty out of date at this point as it is from December of last year. Would recommend upgrading to the latest release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2023. We release on a monthly basis so there have been a lot of updates since last December that may resolve your issue.

**Comment by mikefactorial** [comment] 2023-08-02 20:02
@Will-franca Closing this out for now since there's nothing more to do here. Feel free to reopen or open a new issue if there's anything to follow up on.

**Closed by mikefactorial** 2023-08-02 20:02 UTC
Labels: bug, alm-accelerator
