### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) - /powerAppPlanExcluded' to be of type 'String' but is of type 'Boolean'.'

### ISSUE THREAD

**Issue by larhem** [microsoft/coe-starter-kit#3528] opened 2022-08-26 11:16 UTC
### Describe the issue

When running Admin | Sync Template v3 (Flows) and having "fullinventory" to yes we get this error on some of our flows on the "Get flow as admin" action in the section "Only proceed if changed since last updated in CoE or FullInventory".

ResponseSwaggerSchemaValidationFailure. The API 'flowmanagement' returned an invalid response for workflow operation 'Get_Flow_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'AdminGetFlow' requires the property 'body/properties/estimatedSuspensionData/powerAppPlanExcluded' to be of type 'String' but is of type 'Boolean'.'

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment] 2022-08-26 14:47
You have hit some product issue in which the connector expecting the flow to return one type and got another. I happen to know this is a new property as well. 
Can you get an Envt and Flow GUID from your failure repro? If so we can get a simplified repro together.

**Comment by larhem** [comment] 2022-08-27 09:26
Hi,


Two examples:
Flow 1: 
Env: 491828e7-8ac7-49aa-a780-0c97eadc77da
Flow: e052729e-3c36-e4dd-d402-58e36b03f2ee

Flow 2:
Env: c9ee36b0-a69b-41a2-8706-0c0e61a0b24b
Flow: cc8db5ae-6283-479f-8748-e7a14ac7372a

**Comment by Jenefer-Monroe** [comment] 2022-08-27 12:00
Thanks for looking. I suggest you please take note of those locally and delete the comment, just so others dont have your GUIDs.

Can you please create a new flow that just calls this action with these GUIDs? 
Save and run the flow. Do this for both cases. Do you repro? 

![image](https://user-images.githubusercontent.com/89584709/187029066-07198fd8-6dec-4c16-ab29-6d23e24f867f.png)
![image](https://user-images.githubusercontent.com/89584709/187029195-26c523f8-0357-4bbc-8d96-d0bccd3821c3.png)
![image](https://user-images.githubusercontent.com/89584709/187029121-a367921f-7fe8-4959-911b-00f075c28a12.png)
![image](https://user-images.githubusercontent.com/89584709/187029167-c6237498-fd88-464e-8bba-9d56b982833c.png)

**Comment by larhem** [comment] 2022-08-27 12:33
Yes. Same error when creating this simple flow!

**Comment by Jenefer-Monroe** [comment] 2022-08-27 13:56
Thank you for confirming. Can you please create a support ticket for this and bring this simplified flow with you. Let the support person know that the property is new. I will also send this issue to the product team.

**Comment by larhem** [comment] 2022-08-29 05:52
Support ticket created (2208290050000118). 
Thanks for your help.

**Comment by fredrikhr** [comment] 2022-08-30 14:56
I can confirm that our organization has also run into the same issue. I newly deployed CoE last week using the latest (August 2022) release.

**Comment by fredrikhr** [comment] 2022-08-30 14:58
@Jenefer-Monroe should I open a support ticket too, or can we attach information to @larhem's ticket that the issue is **not** isolated to a single tenant?

**Comment by larhem** [comment] 2022-08-30 17:21
MS is still investigating this issue. But it looks like if you do a small change to the flow it gets the error on, like add a note, and then save. The GetFlowAsAdmin then works fine afterwards.

**Comment by fredrikhr** [comment] 2022-08-30 17:45
@larhem :+1: presumably I'll have to do that for all CoE flows that use PowerAutomate Admin Management actions?

**Comment by larhem** [comment] 2022-08-30 18:46
Hopefully they will fix this in the produc, but yes :)

**Comment by Jenefer-Monroe** [comment] 2022-08-30 19:14
yes please post  separate ticket if you can. The more the better!

**Comment by larhem** [comment] 2022-08-30 20:49
> @larhem 👍 presumably I'll have to do that for all CoE flows that use PowerAutomate Admin Management actions?

Its not the flow that is using the management actions that is the problem - its the flow you try to get information about in the «Get flow as admin action» that has the problem :)

**Comment by NPrice99** [comment] 2022-09-02 12:01
I have added a note and I still get the error.  Where do I get the ticket from ? i thought it was portal.azure.com.

**Comment by Jenefer-Monroe** [comment] 2022-09-02 15:09
Here is a link to get product support: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

**Comment by NPrice99** [comment] 2022-09-02 15:33
THanks @Jenefer-Monroe

**Comment by WouterF** [comment] 2022-09-08 07:11
We are having the same issue in our organization. Do you already have more news from Microsoft support?

**Comment by larhem** [comment] 2022-09-08 07:32
We have had multiple screensharing sessions with Microsoft and the ticket is still open. I asked them for a new status earlier today, but i havent received any feedback yet.

**Comment by navalmon** [comment] 2022-09-08 16:43
This bug has been fixed. If you are still experiencing the issue, please go in to the flow editor and resave your flow.

**Comment by larhem** [comment] 2022-09-09 05:44
I can also confirm that bug seems to be fixed. We had to resave the flow using the get flow as admin connector (not a great solution if we need to do that to all flows using the connector).
Microsoft has also confirmed in the support ticket that the issue is mitigated.

**Comment by Jenefer-Monroe** [comment] 2022-09-12 15:47
thank you everyone. I will go ahead and close this out then.

**Closed by Jenefer-Monroe** 2022-09-12 15:47 UTC
Labels: bug, coe-starter-kit
