### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Audit Logs require smaller chunks - already set to 1 second

### ISSUE THREAD

**Issue by dmongell** [microsoft/coe-starter-kit#5382] opened 2023-04-25 21:19 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I get emails once or twice a day with the subject: CoE Audit Logs require smaller chunks

My chunking size interval/unit is already set to the minimum 1 second.

Additionally, is there any info about what could be missed because of this issue? There's nothing obvious missing from the COE Power BI report, but I wouldn't really know for sure.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment] 2023-04-25 22:38
Unfortunately your tenant is just too large for this solution to collect app usage information. 
What you will miss without this is the app usage information meaning which apps are heavily used for example. This will make some of the governance processes less reliable we wont be able to rely on that information. 

Good news is that we are now in preview in which you can use the Data Export feature of the product instead of the office audit logs. You can explore this product feature here: [Set up Microsoft Power Platform self-service analytics to export Power Platform inventory and usage data (preview)](https://docs.microsoft.com/power-platform/admin/self-service-analytics)

And read about the CoE Starter Kits integration with it here: [What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory)

**Comment by DominicMeznik** [comment] 2023-04-27 09:09
@petepuu Yes, that´s how I understood it as well. In that case it could also be truncated if you use Interval 1s and have a count limit < 86.400. Not sure if that would even be possible though, without a per Flow license on the child (or at all :D).

That´s why we opted for "minute" and just selected a count limit that was sufficient. Since any count limit < 1440 would also not work. The config I posted even works in our giant tenant.

**Comment by petepuu** [comment] 2023-04-27 11:02
@DominicMeznik My customer has a large tenant with 120k+ users. They had 5mins before working for long time but just recently started to receive emails about need to reduce the chunk size. They changed to 2mins (CountLimit = 720 and StartTime-Interval = 1 and StartTime-Unit = Day which are default) and seems to work for them now. Thought they are moving to CoE BYODL in prod soon, so will not need audit log component anymore

**Comment by DominicMeznik** [comment] 2023-04-27 11:11
@petepuu That´s about our size, but I went straight to 1 minute, without trying 2 or 5 actually. Has been working for quite some time now. I hope I will never have to set it to seconds interval. but we´ll see

**Comment by PyHatTech** [comment] 2023-04-28 11:21
Same issue. 1 minute not enough, so I'm increasing the TimeSegments-CountLimit to 1500.

Understand that the backend is changing to BYODL, but that is still in preview. There should be an option to get this to work without relying on a preview imo. Have created a ticket with MSFT support and they confirmed that there is no way to get an exception for the API limit.

Here's what I don't get. Why is the flow not designed in a way where it simply changes the size when it's actually needed? It's able to determine when it's too big and you already know how big of an interval it needs to cover. 

Next, I'm kind of disappointed that we can't get an exception for the API calls. A per flow plan (not even sure if that is enough to cover this tbh) is something you get for an entire year. BYODL is probably reaching GA before, so then we have to come up with a use case for an expensive plan.

**Comment by Jenefer-Monroe** [comment] 2023-04-28 13:18
Hello, We are a very small team and so are only funded to create the CoE Starter Kit as an unsupported set of templates. Please see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support 

In this case we were able to add the chunking feature with the env vars about 6 months ago when we had a few hours to spend on the area. Good news is that one of our partners has offered to make this part better soon for us, although it will not help with the API calls or backend throttling, it will help with the complexity of these chunks.

**Comment by Jenefer-Monroe** [comment] 2023-05-01 10:21
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-05-01 10:21 UTC
Labels: question, coe-starter-kit
