### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade Solution Fails for Core version 4.29

### ISSUE THREAD

**Issue by brentellingwoodevr** [microsoft/coe-starter-kit#8064] opened 2024-04-15 14:26 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In our Dev environment we tried to update the CoE SK Core Solution to version 4.29 from 4.22. The Upgrade solution installs correctly but when it comes time to apply the upgrade and get rid of the old version (4.22), we get an error message below

 "The DELETE statement conflicted with the REFERENCE constraint "solution_solutioncomponent". The conflict occurred in database "db_crmcorenam_xxxxxxxxxxxxxxxxx", table "dbo.SolutionComponentBase", column 'SolutionId'. The statement has been terminated."

This same error is thrown when we try to delete the UPGRADE solution manually.

We are seeing this issue with other custom components as well and submitted a MSFT support ticket, and the support rep asked us to reach out here to see if there are any known issues around with the newest version of the SK.

### Expected Behavior

Core Solution upgrades successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Solution Upgrade

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Import Core solution as UPGRADE

### Anything else?

We are seeing this issue with other custom components as well and submitted a MSFT support ticket, and the support rep asked us to reach out here to see if there are any known issues around with the newest version of the SK.

AB#2901

**Comment by Jenefer-Monroe** [comment] 2024-04-15 15:01
Sorry no there are no such known issues. We do reference a product table for solution information in the kit, sounds like you do as well in your custom solutions.
What region and type is your envt?

**Comment by Jenefer-Monroe** [comment] 2024-04-15 15:19
Here is where we call the table, and I've confirmed this still works in 4.29
CLEANUP HELPER - Solution Objects

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c98c2c4a-4adb-498c-afe5-184866ce53fb)

**Comment by Jenefer-Monroe** [comment] 2024-04-15 15:20
We did move this to another flow, can you delete the _upgrade solution if its there, and then look for unmanaged layers on your flows? 

You can see this in the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by brentellingwoodevr** [comment] 2024-04-15 16:01
I tried to delete the Upgrade solution but am getting that same error. There was 1 unmanaged layer on a flow that I was able to remove but the flow didn't touch that solutioncomponents table. Even with product pushed solution upgrades we are getting the same error. 

"The DELETE statement conflicted with the REFERENCE constraint "solution_solutioncomponent". The conflict occurred in database "db_crmcorenam_xxxxxxxxxxxxxx", table "dbo.SolutionComponentBase", column 'SolutionId'. The statement has been terminated."

**Comment by Jenefer-Monroe** [comment] 2024-04-16 12:38
Sorry I'm not sure how to help here. There seems to be something broken in your envt with this system table and its impacting all solution operations so I'm afraid its out of my depth to assist.

**Comment by brentellingwoodevr** [comment] 2024-04-16 12:40
Thank you for assisting anyways. hopefully Microsoft support can help us get it the environment fixed.

**Comment by Jenefer-Monroe** [comment] 2024-04-17 12:38
There appears to be a product regression around solution import. Its complaining about a random app or flow when you try to import. 
It appears to complain about random objects for different people. Some people are getting a random error about a flow and its a different flow each time they try.

Please follow along with and put your notes into https://github.com/microsoft/coe-starter-kit/issues/8076 so that we can more quickly get to resolution with a single issue.

**Comment by Jenefer-Monroe** [comment] 2024-04-18 12:55
Can you please retry today?

**Comment by brentellingwoodevr** [comment] 2024-04-18 14:59
I tried to remove the _Upgrade Solution again and am getting the same error. My ticket with MSFT support is being escalated as they believe it is an issue in this environment specifically. The error is only occurring when trying to remove Model Driven apps from solutions (CoE or Custom).

**Comment by Jenefer-Monroe** [comment] 2024-04-25 15:47
Did you learn anything from support here that might help us?

**Comment by brentellingwoodevr** [comment] 2024-04-25 15:49
Support said they may have found some internal documentation on how we could fix the issue, but they haven't shared the steps with me yet. Once they do and I try it out I can share the results here.

**Comment by Jenefer-Monroe** [comment] 2024-05-03 13:23
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-05-03 13:23 UTC
Labels: bug, coe-starter-kit
