### ISSUE TITLE
Extending the starter kit - issue with child flows

### ISSUE THREAD

**Issue by sandeep-mamidala** [microsoft/coe-starter-kit#1744] opened 2022-01-13 05:55 UTC
Unable to create a copy of the workflows as due to helper Flows are used.So in order to customize the flows in COE which approach will be best.In earlier version of COE we could create copy of flows as they donot use helper flows but in latest version of COE we have this issue.Suggest best approch to customize the workflows so that it will not effect upgrades provide by microsoft in future

**Comment by Jenefer-Monroe** [comment] 2022-01-13 13:47
Hello this would not work for you even without the helper flows due to the use of Environment Variables. 

The recommendation on how to extend the starter kit is outlined here: [Extending the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#extending-the-starter-kit)

**Comment by larhem** [comment] 2022-01-14 08:18
We have the exact same problem. We want to make some changes to some of the componentes in the CoE Core (Welcome email flow) and CoE Governance solutions (Ask for teams env justification flow).  

This can of course be done directly in the managed CoE solutions, but we want to do the changes in an unmanaged solution. 

As far as we can see. the recommendations in [Extending the starter kit](https://docs.microsoft.com/nb-no/power-platform/guidance/coe/after-setup#extending-the-starter-kit) is not valid for all kind of customizations.

For the "Admin | Welcome Email v3" it works fine to "Save as" and add it to a new unmanaged solution, but the same doesnt work for "Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created ".

What is the best ALM approach for this issue?

**Comment by Jenefer-Monroe** [comment] 2022-01-14 17:35
Thanks for clarifying. We have reached out to the product team to see what they recommend.

**Comment by larhem** [comment] 2022-01-19 09:18
Hi :)
Any update on this @Jenefer-Monroe ?

**Comment by Jenefer-Monroe** [comment] 2022-01-21 00:48
No, unfortunately, we have not heard back. I will ping again

**Comment by larhem** [comment] 2022-01-25 09:40
Any idea on when we can expect feedback on this issue?

**Comment by Jenefer-Monroe** [comment] 2022-01-25 14:46
Sorry we dont have a timeline. This is a product limitation, you should post it here to get visibility. 
[MPA Community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity)

The only update for us will be on the documentation once we find out the new recommendations.

**Comment by manuelap-msft** [comment] 2022-02-07 19:21
Hello,

I confirmed this is a product bug, unrelated to the CoE Starter Kit. Closing this issue as our team can't assist further here.

**Closed by manuelap-msft** 2022-02-07 19:21 UTC
Labels: question, coe-starter-kit
