### ISSUE TITLE
[CoE Starter Kit - BUG]: Set Flow/Apps Permissions shows owners withouts apps/flows

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#670] opened 2021-06-22 09:24 UTC
Core 2.1.70
Set Flow Permissions
Set Apps Permissions

Firstly, I am not sure that this is an issue or a expected behaviour.
In this apps, the Owner section shows users that they aren't owner of any apps or flows.

![image](https://user-images.githubusercontent.com/57954993/122899537-31b73e80-d34c-11eb-9cf0-c83030e5fff6.png)

![image](https://user-images.githubusercontent.com/57954993/122899705-57444800-d34c-11eb-9f31-896b22811316.png)

If this is an expect behaviour, I thinks that will be very helpfull that this apps only shows the owners with apps/flows.

**Comment by JeneferM-MSFT** [comment] 2021-06-22 13:49
It was expected behavior (in that we didnt filter it before) but the fix is super easy since we store a calculated column of this in the table. So I am able to fix for July.

**Comment by albertocaa1317** [comment] 2021-06-22 14:35
Great news. I think that is an enchancement very helfull for all lovers of CoE Starter Kit :D

**Comment by JeneferM-MSFT** [comment] 2021-06-22 18:35
you betcha!

**Comment by JeneferM-MSFT** [comment] 2021-07-07 19:43
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by JeneferM-MSFT** 2021-07-07 19:43 UTC
Labels: coe-starter-kit, core-components, enhancement, vnext
