### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by arpagotidot** [microsoft/coe-starter-kit#1147] opened 2021-09-09 22:41 UTC
### Describe the issue

Failure error during the import of Center of Excellence Nurture Components 2.1 version into our GCC tenant. However, the previous imports were successful with no issues (Core, Audit components). 

Below is the log:

Error code: 80040224

Exception Message:
Exception while acquiring token: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details. Original exception: AADSTS700030: Invalid certificate - subject name in certificate is not authorized. SubjectNames/SubjectAlternativeNames (up to 10) in token certificate are: ppdfcrmplugin.pqo.internal.microsoft.us. Trace ID: 869efaef-d58d-4549-b95e-8e0a6c6c2900 Correlation ID: cf54b25f-f0b7-423c-a278-3df48b0498a3 Timestamp: 2021-09-09 19:04:03Z (Fault Detail is equal to Exception details: ErrorCode: 0x8009100C Message: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details. Original exception: AADSTS700030: Invalid certificate - subject name in certificate is not authorized. SubjectNames/SubjectAlternativeNames (up to 10) in token certificate are: ppdfcrmplugin.pqo.internal.microsoft.us. Trace ID: 869efaef-d58d-4549-b95e-8e0a6c6c2900 Correlation ID: cf54b25f-f0b7-423c-a278-3df48b0498a3 Timestamp: 2021-09-09 19:04:03Z TimeStamp: 2021-09-09T19:04:03.0000000Z -- ).

Activity ID: 9ec64388-e999-475e-9c20-812c0dc09af5

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.1

### What app or flow are you having the issue with?

Importing Solution

### Steps To Reproduce

Import the "CenterofExcellenceNurtureComponents_2_1_managed.zip" file into solutions in a GCC Power Platform Environment and history shows the failure message mentioned above.

**Comment by Jenefer-Monroe** [comment] 2021-09-09 22:43
Hello this is a known issue. You will need to use the workaround in #888 . Pasting here for your convenience. 
Duplicate of #888 

### Workaround solution
Hello we have created a workaround solution for you here which is Sept version of Nurture with the data flow removed. 
[CenterofExcellenceNurtureComponents_3_0_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7138428/CenterofExcellenceNurtureComponents_3_0_managed.zip)

### Maker Assessment App

The data flow was used to populate started data for the [Maker Assessment App](https://docs.microsoft.com/power-platform/guidance/coe/nurture-components#maker-assessment). 
If you would like to use that app, without having this data flow, you will need to load the sample data in another way as a result. 

Below is one technique, if it does not work for you then **_you will need to either manually insert the data or wait to use this particular app until the data flow feature works for you before you can use the app._** 

### One technique to Upload Data for Maker Assessment App
Put these 3 files locally on your machine
[assessmentcategories.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138802/assessmentcategories.xlsx)
[assessments.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138803/assessments.xlsx)
[answeroptions.xlsx](https://github.com/microsoft/coe-starter-kit/files/7138804/answeroptions.xlsx)


**Assessment Category**
Browse to the Assessment Category table
![image](https://user-images.githubusercontent.com/89584709/132738548-a260c56a-96ea-46ce-832d-2514e9375a97.png)
Once in the table select Get data > Get data from Excel
![image](https://user-images.githubusercontent.com/89584709/132738779-f369616f-3aa1-4ebc-a013-808417bb25a7.png)
Hit **_upload_**, select assessmentcategories.xlsx, wait till mapping status says **_Mapping was successful_**
![image](https://user-images.githubusercontent.com/89584709/132739201-d5b6342b-763d-4631-84e0-185d00d90cf2.png)
Here is what the mapping should look like if you hit Map Columns
![image](https://user-images.githubusercontent.com/89584709/132750873-5a860f94-3dd8-4fde-bc7a-d4dd0d93aa95.png)
Hit import. You should see 5 items inserted
![image](https://user-images.githubusercontent.com/89584709/132751060-fefc480b-9d93-4395-8fa0-bd3405176fd5.png)

**Assessment Questions**
Do the same steps as above but point to assessments.xlsx
Here is what the mapping will look like, and you should see 22 items inserted
![image](https://user-images.githubusercontent.com/89584709/132751414-9e3fcbc9-5ed4-44c8-8b95-b5619474a2ab.png)

**Answer Options**
Do the same steps as above but point to answeroptions.xlsx
Here is what the mapping will look like, and you should see 65 items inserted
![image](https://user-images.githubusercontent.com/89584709/132752093-4348382c-f24e-4856-a90a-33e8fce84fab.png)

**Closed by Jenefer-Monroe** 2021-09-09 22:43 UTC
Labels: coe-starter-kit

**Comment by arpagotidot** [comment] 2021-09-17 15:50
Hi Jenefer,

It appears that the September version of the COE kit still does not include the new NurtureComponents 3.0, unless I'm downloading from the wrong location.

Release CoE Starter Kit September 2021 * microsoft/coe-starter-kit * GitHub<https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021>

Please advise.

Thanks,
AR Pagoti
SharePoint Architect/Team Lead
Office of the CIO, Infrastructure & Operations
United States Department of Transportation
Room E53-484, 1200 New Jersey Ave, S.E.
Washington, DC 20590
Office - (202) 366-5357 | Mobile - (202) 503-8023
For assistance, please use the following:  SharePoint help tickets<https://remedy.dot.gov/arsys/forms/remedy/SRS:ServiceRequestConsole/?mode=submit&F303900000=4&F303900900=SRGAA5V0GMXWBAPVJDIMPU1KMRWS8P&F303906700=0&F303902000=0&F303902100=0> | MS Teams help<https://remedy.dot.gov/arsys/forms/remedy/SRS:ServiceRequestConsole/?mode=submit&F303900000=4&F303900900=SRGAA5V0GMXWBAPVJD44PU1KS9WS95&F303906700=0&F303902000=0&F303902100=0> | Ticket status<https://remedy.dot.gov/arsys/forms/remedy/SRS%3AServiceRequestConsole/>
Office365/Teams/SharePoint support<https://usdot.sharepoint.com/sites/Office365>

"With Great Power, Comes Great Responsibility"
