### ISSUE TITLE
COE Update or Upgrade to August version does not work

### ISSUE THREAD

**Issue by mduqueBasf** [microsoft/coe-starter-kit#1070] opened 2021-08-24 09:35 UTC
Hi COE Update or Upgrade to August version does not work for CoreComponents The rest of the solutions are OK . Latest Core was June.

My Core Http Azure AD Dependencies are:

![image](https://user-images.githubusercontent.com/64835119/130593856-62af29a5-4c7a-40bd-b684-14e2abb13744.png)

**Comment by JeneferM-MSFT** [comment] 2021-08-24 14:56
Please work with us on this version of the issue 
Duplicate of #1005

**Closed by JeneferM-MSFT** 2021-08-24 14:56 UTC
Labels: coe-starter-kit
