### ISSUE TITLE
[CoE Starter Kit - BUG] The shared_Http connector is not being used in any flow.

### ISSUE THREAD

**Issue by Titoleto** [microsoft/coe-starter-kit#6225] opened 2023-08-03 10:49 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have checked that the shared_Http connector is not being used in any flow, when it is not, we have hundreds of flows that do use this connector.

In the **_admin_flowactiondetail_** table, I have been looking at a particular flow with XrmToolbox tool and I see that the Action Type of type Http does appear.

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/2d087de8-8468-4281-b1ef-9be61c5eb7a6)

When I make a query to the **_admin_flow_** table to the same flow, the **_admin_flowconnections_** field I see that only one connection appears, when this is not the case.
![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/f14ef51b-ac81-4158-95f7-4fa4b87c5fff)

I have reviewed the CoE BYODL Flow Connections Dataflow and one of the steps is to remove the shared_Http connector when this connector is in the file, why is it being removed? By removing it, the connection in the Dataverse we will not be able to know if it is being used or not.

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/1622676e-a282-4d8d-a5fb-e39eb3c07d6e)

In the Power BI report "Cloud flow risk assessment" when I click "Right Click -> Cloud flow detail" on the flow I am verifying and add the Metadata column (as it does not appear by default), I have been able to verify that the Actions that appear are not from the flow I am verifying, what's more, if I open another flow, the Actions that appear are always the same.

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/2debf424-84ae-4f84-8305-704d3a93e665)

This is another different flow, that doesn't use Http and if you look at it, it shows me that it does use it and the Actions are always the same, it's as if it didn't filter well.

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/42c38461-84a9-46ef-8756-32cd575c8cb5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Dataflow - CoE BYODL Flows Connection

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment] 2023-08-04 18:50
hello. putting on the list for the area owner when they are back next week

**Comment by manuelap-msft** [comment] 2023-08-08 17:48
Hello,

from an architecture perspective:

- There is a Power BI Dataflow (PowerPlatformAnalytics-DF) that prepares the Data Export data into Power BI datasets, and the Power BI dashboard is based on that. You will use the BYODL_CoEDashboard file for that
- The Power Platform dataflows (e.g. the one you mentioned CoE BYODL Flow Connections Dataflow) write a small amount of data from Data Export (storage account) to Dataverse for the admin and governance processes of the kit, so the apps/flows. These Power Platform dataflows and Dataverse tables do not power the Power BI dashboard. 
- So for issues with the Power BI Data, you'll have to look at the PowerPlatformAnalytics-DF dataflow in Power BI
- Regarding why it's removed: There's a data quality issue with the data exported from Data Export where all flows show to contain an HTTP action as the first action. It's something to do with Data Export - you an verify this yourself by looking at the data directly in the storage browser and analysing it. We therefore remove the first (starting) HTTP action as it was not accurate. If you found that where we remove it in the first instance is actually incorrect let us know and we can debug those specific cases. But removing them currently is expected behaviour to overcome a known data quality issue with Data Export.

It looks like with this in mind, we have the opposite problem in the Power BI dashboard now. The Power BI Dataflow doesn't filter out the HTTP action, and now all flows show as using the HTTP connector. I've raised this with the product group for investigation as this needs to be fixed at the source (in the Data Export files).

Will comment here once we know more.

**Comment by manuelap-msft** [comment] 2023-08-08 17:51
PS: The HTTP call is an action and not a connector, so I think that even once the Data Export is tidied up, we will not be able to identify HTTP action calls using Data Export method. As this method only returns connections/connectors, not actions.

**Comment by Jenefer-Monroe** [comment] 2023-08-16 15:11
closing out as no further action from starter kit team

**Closed by Jenefer-Monroe** 2023-08-16 15:11 UTC
Labels: question, coe-starter-kit, product-gap
