### ISSUE TITLE
[CoE Starter Kit - BUG] Display Name for orphaned environments is empty

### ISSUE THREAD

**Issue by allanmarsh** [microsoft/coe-starter-kit#2100] opened 2022-02-21 22:27 UTC
### Describe the issue

The Display Name for orphaned environments is not being stored in CDS even though it is being returned by the "Get Environments and some tenant wide properties" task in the Admin | Sync Template v3 flow.  

### Expected Behavior

Expected all environment Display Names to be stored in the Environment entity.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Prerequisite - An orphaned environment.

1. Open the history for a successful run of the Admin | Sync Template v3 flow.
2. Open the "Get Environments and some tenant wide properties" task.
3. Examine the Outputs value in the Get Environments task and find the "displayName" value for the orphaned environment.
4. Compare result of step 3 with the "Display Name" column for that environment in the Environment entity in CDS.

### Anything else?

I'm assuming the problem is tied to the orphaned environments, because we have 6 orphans and it is only those 6 (and all of those 6) that are missing the Display Name in the table.

**Comment by Jenefer-Monroe** [comment] 2022-02-22 13:44
Duplicate of #1658

**Closed by Jenefer-Monroe** 2022-02-22 13:44 UTC
Labels: bug, coe-starter-kit

**Comment by allanmarsh** [comment] 2022-02-23 14:45
Hi. I deployed the latest release of the starter kit and ran the flows again. The problem remains, and it actually removed the names of newly-orphaned environments. Regards, Allan.
________________________________

**Comment by allanmarsh** [comment] 2022-02-23 15:15
You're correct, there is an unmanaged layer on the flows. Thanks,
Allan
________________________________
