### ISSUE TITLE
[Product Bug]: DLP impacting Core but not exposed in Product UX. Cannot turn on flows as a result

### ISSUE THREAD

**Issue by pmatthe1** [microsoft/coe-starter-kit#375] opened 2021-05-18 08:25 UTC
**Describe the bug**
I have updated to the latest version of the Core Components solution ( I have not updated the other solutions).  Following the solution update the following flows have become disabled

Admin | Sync Template V3 (Apps)
Admin | Sync Template V3 (Flows)

As part of the solution upgrade I was asked to create a connection to "HTTP with Azure AD", so the did this and also added the connector to my environment wide DLP policy.  There are no tenant wide DLP policies in place or any other DLP policies associated with this environment.

When I try to turn on the above 2 flows I receive the following

Your flow could not turn on: Admin | Sync Template v3 (Apps). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Admin data policy 'CoE' restricts the use of /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps with /providers/Microsoft.PowerApps/apis/shared_webcontents."}}".

I understand that the connector "shared_webcontents" is referring to "HTTP with Azure AD" and that shared_commondataserviceforapps is referring to  "Microsoft Dataverse" so my DLP policy should work as both those connectors are in my Business Group. (see attached screen shot)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Core
 - Version : 2.1.6
 - App or Flow Admin | Sync Template V3 (Flows) , Admin | Sync Template V3 (Apps)

**Expected behavior**
I would expect as part of the install, once I add the "HTTP with Azure AD" connector to the DLP policy that the flow will begin to work.  I have even deleted the DLP policy and the error still appeared, so I recreated it.

**Screenshots**
I have attached a screen shot showing the HTTP with Azure connector and Dataverse connector in the Business Group of my DLP policy.
![Connectors](https://user-images.githubusercontent.com/83361235/118617870-f2c92280-b7ba-11eb-8e4f-a97fde60b9ea.png)

I have also attached a screen shot of the error.
![Error](https://user-images.githubusercontent.com/83361235/118622485-43427f00-b7bf-11eb-905b-af962ebc33c5.png)

thanks
Paul

**Comment by JeneferM-MSFT** [comment] 2021-05-18 13:37
Hello you must have other DLP policies impacting the environment that you are unaware of. Note that an environment will be impacted by the most restrictive combination of DLP policies that impact it. 
If you use the [DLP Editor app](https://docs.microsoft.com/power-platform/guidance/coe/core-components#dlp-editor-v2) in Core it can help you understand what all DLP policies impact your environment

**Comment by pmatthe1** [comment] 2021-05-18 14:03
Hi, I don't think there are any additional DLP policies impacting this environment.  The app you mention displays 3 DLP Policies, 2 who are environment policies specific to separate environments and one specific to the CoE environment which is the one detailed in this log.  

Could you suggest another way to identify all the DLP policies that are impacting an environment other than opening then up and looking what environments they are associated with as this does seem like a bug to me.

thanks
Paul

**Comment by JeneferM-MSFT** [comment] 2021-05-18 14:14
Hello. Most folks have been able to install correctly and update their DLP, so this is not likely an issue with the toolkit or the product. However there may be something specific about your tenant that will require product support to fix up. 

But again, this is most likely just another DLP policy. 
Can you validate that you are logged in as a member of the power platform admin role such that you will see all DLP policies?

**Comment by pmatthe1** [comment] 2021-05-18 14:54
I understand, however this was all working great until I installed the latest version of the Core components.  the flows were running within the current DLP structure, then as soon as I updated the Core solution they turned off.

Are you aware of a way that I can identify all the policies that are present on an environment.  I will check regarding any higher level policies.

**Comment by JeneferM-MSFT** [comment] 2021-05-18 15:06
We had to add this new connector in order to support service principle installs as without it those would all show as orphaned objects. That's why the new connector is in play.

**Comment by JeneferM-MSFT** [comment] 2021-05-18 15:07
Browse to Azure Portal: https://portal.azure.com/ 
![image](https://user-images.githubusercontent.com/62659043/118676283-80efd980-b7b8-11eb-9688-7cd4c2df93be.png)

Select Users and chose the User you are wanting to investigate 
![image](https://user-images.githubusercontent.com/62659043/118676248-79303500-b7b8-11eb-8bf6-918d8eb2e1df.png)

 

 

Once at your target user select Assigned roles and look for Power platform administrator 
![image](https://user-images.githubusercontent.com/62659043/118676140-64ec3800-b7b8-11eb-97a9-ea2fe77aede1.png)

**Comment by pmatthe1** [comment] 2021-05-18 15:10
thank you, I will double check.  I installed everything successfully using this user  so I think my access is correct but I will double check.

thanks for your help.

**Comment by JeneferM-MSFT** [comment] 2021-05-18 15:17
Once you are able to see all the DLP policies, you can use the app mentioned above, there is a drop down of envts from which you can select your target envt (you may need to browse to a policy in the app and back to populate it, bug in the app)

![image](https://user-images.githubusercontent.com/62659043/118677830-cbbe2100-b7b9-11eb-9b43-50d8f650818d.png)

If this does not expose the problem you will likely have to go through the DLPs one by one in the admin ux.

**Comment by pmatthe1** [comment] 2021-05-18 15:23
thanks, I have used this app, as seen below, and there is only the single DLP policy against it.  I will check my role to ensure that is not the issue.  I hope it is but am am not so sure due to other capabilities that I have within the tenant.

thanks

![DLPApp](https://user-images.githubusercontent.com/83361235/118678660-1d37d180-b7f5-11eb-89a3-ecedbbabb178.png)

**Comment by JeneferM-MSFT** [comment] 2021-05-18 15:33
One last thing to double check is that you hit the update policy button when you made the change to the DLP policy. In the world of auto-save everywhere I sometimes forget to look for such buttons and assume the change I have made was saved. For DLP this isn't the case, you have to remember to get to the final screen and hit Update Policy

![image](https://user-images.githubusercontent.com/62659043/118680501-0628bd80-b7bc-11eb-9c84-076579733e50.png)

**Comment by pmatthe1** [comment] 2021-05-18 15:36
yeah, I have done that previously.  I actually created the DLP from the Admin Center and didn't forget this time.  This is a proper mystery.

**Comment by JeneferM-MSFT** [comment] 2021-05-18 15:40
You may have hit some caching issue with the product's list of DLPs. 
I suggest you create a simple flow outside of the toolkit in that environment. Have it call the HTTP with Azure AD and Dataverse. 
Presumably you will not be able to turn this flow on due to the DLP policy failure. 
With this sample flow you can create a support ticket for the product team to investigate your DLP cache.

**Comment by pmatthe1** [comment] 2021-05-18 16:06
Yeah, I have heard about that.  I will keep that in mind.  I have a quick question if you don't mind, the error that I am getting is 
The bold bit **CoE**, is that referring to a DLP policy name?

Your flow could not turn on: Admin | Sync Template v3 (Apps). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Admin data policy '**CoE'** restricts the use of /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps with /providers/Microsoft.PowerApps/apis/shared_webcontents."}}".

Thanks for your help

**Comment by JeneferM-MSFT** [comment] 2021-05-18 17:36
I believe so

**Comment by pmatthe1** [comment] 2021-05-19 16:05
Hi, I now deleted all DLP policies that are related to the CoE environment.  I have checked my access is correct, and I am still getting the error.  I also did not have a dlp with the name CoE. 

Based on the fact that this issue appeared as soon as I upgraded, I am really struggling to understand how this could not be caused by the upgrade.

**Comment by JeneferM-MSFT** [comment] 2021-05-19 16:11
The upgrade added a connector so it is caused by the upgrade. 
The normal path here, when you have a DLP policy and we add a connector, is to add this new connector in the same bucket as the rest in the DLP

The fact that you are unable to do that, and that there are DLP policies impacting your environment not exposed in the UX, is a product bug. 

I suggest you create a simple flow outside of the toolkit in that environment. Have it call the HTTP with Azure AD and Dataverse.
Presumably you will not be able to turn this flow on due to the same DLP policy failure.

With this sample flow you can create a support ticket for the product team to investigate your DLP cache.

**Comment by JeneferM-MSFT** [comment] 2021-05-19 16:24
One more quick question before you do that, can you validate that you viewed these policies on the product site? 
https://admin.powerplatform.microsoft.com/dlp 

Just in case its a bug in our app which exposes the policies.

**Comment by pmatthe1** [comment] 2021-05-19 16:28
Hi, Yes have have checked in the admin center and the app.  I will create the flow and then create a support ticket if required.

thanks

**Comment by JeneferM-MSFT** [comment] 2021-06-07 12:33
Closing out as no action for toolkit.

**Closed by JeneferM-MSFT** 2021-06-07 12:33 UTC
Labels: coe-starter-kit, core-components, product-bug
