### ISSUE TITLE
[CoE Starter Kit - BUG] Get organization from Develloper Environnments, table organizations

### ISSUE THREAD

**Issue by klemaitreFDJ** [microsoft/coe-starter-kit#5257] opened 2023-04-12 13:55 UTC
### Describe the issue

Flow 'admin sync template V3' - COE startKit xxxxx - Version Dataverse 9.2.23032.00184
Failed (not found) to 'get organisation' from the organization table of a developer environment
Flow is ok on non develloper environnment
In COE Powerapps, cloud flow 'Admin Sync Template v3' : Failure on run process
25 environments, only 4 devellopers envionnements on failure. 21 other environnments OK.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

Config : By default (out of the box)
Run : flow 'Admin - Sync Template v3'
Behavior : 'store environnments in the CoE CDS Entity' - 'Apply to each environnment' - 'Get a PCF value' - 'Get Organization'
Error : organisation not found : only on develloper environnment

**Comment by manuelap-msft** [comment] 2023-04-12 16:39
This is a duplicate of #5246 and we're tracking a fix via #5197 for May.

**Comment by manuelap-msft** [comment] 2023-04-12 16:39
Closing as duplicate. Please follow the other two issues for updates.

**Closed by manuelap-msft** 2023-04-12 16:39 UTC
Labels: bug, duplicate, coe-starter-kit
