### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by v7herman4** [microsoft/coe-starter-kit#1034] opened 2021-08-16 13:33 UTC
### Describe the issue

When installing the following solution: CenterofExcellenceNurtureComponents_1.60.20210708.1_managed

I complete the import steps with the Wizard and the solution starts importing. After a few minutes, an error occurs: Exception while acquiring token: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).    

This occurs whether installing in a brand new environment or when upgrading an existing COE environment. This occurs in both GCC and commercial environments. 

The XML file is attached.
[importlog_CenterofExcellenceNurtureComponents_1_60_20210708_1.zip](https://github.com/microsoft/coe-starter-kit/files/6992681/importlog_CenterofExcellenceNurtureComponents_1_60_20210708_1.zip)

### Expected Behavior

The solution to install successfully. 

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

Nurture Components 1.60.20210708.1

### What app or flow are you having the issue with?

N/A, the error occurs when importing the Nurture solution.

### Steps To Reproduce

1. In this environment: (contact me for environment ID)
2. Install/upgrade all necessary base components to latest COE version (as of 8/16/2021)
3. Install the Nurture solution, complete the import solution steps.
4. Wait and receive error.

**Comment by v7herman4** [comment] 2021-08-16 13:36
Hey Jenefer, apologies just noticed this is an existing issue: https://github.com/microsoft/coe-starter-kit/issues/888

Looks like you might provide an early release to this solution. Please keep me in the loop thank you!

**Comment by JeneferM-MSFT** [comment] 2021-08-16 15:37
Thanks yes I will try to do that, please follow along with #888. 
Duplicate of #888

**Closed by JeneferM-MSFT** 2021-08-16 15:37 UTC
Labels: coe-starter-kit
