### ISSUE TITLE
How to "undelete" flows marked as deleted in ByoDL environment

### ISSUE THREAD

**Issue by shoffma1** [microsoft/coe-starter-kit#7511] opened 2024-01-22 20:11 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

From before the January update, some 2000 of our flows from our main environment have been marked as deleted.  Though they show up in the PowerBI report now, they are not in the default view in the Admin app.
How can we get remove the "marked as deleted"?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Data Export

AB#2105

**Comment by Jenefer-Monroe** [comment] 2024-01-22 22:54
This should happen automatically with the dataflow refreshes. Can you please show a screenshot of the dataflows to see if they are passing? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c78e194f-7b1e-4d01-98ff-1ad108afb8d0)

**Comment by niwrejim21** [comment] 2024-01-24 15:42
Hello @Jenefer-Monroe, we are also getting this issue. Flows, Apps and environments are being marked for deletion and most of the flow are under the "Deleted flows/apps/environment/AI Models" view in the Admin View. I was able to observe that this is happening after the scheduled refresh of dataflows. Once I do a manual refresh of the flow - the flows are again available and are removed from the deleted view. 

Here is an example of our default environment under the "Deleted Environments Review" View.

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/22fa168c-dc89-4c28-9bfe-a22c0330f6db)

**Comment by Jenefer-Monroe** [comment] 2024-01-24 21:53
@niwrejim21 can you please share a screenshot like this?
Also what version of Core are you on?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e67ac5b7-d697-4085-89c4-d50fe4ccf4a0)

**Comment by shoffma1** [comment] 2024-01-25 13:51
<img width="770" alt="Screenshot 2024-01-25 074949" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/c8780370-6b71-42b5-ad9a-a995762986c8">
This is my view ...

**Comment by niwrejim21** [comment] 2024-01-25 14:12
![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/8fc84f84-f213-491b-9be9-9ba55bda1997)

**Comment by Jenefer-Monroe** [comment] 2024-01-25 23:43
I'm not sure how you got into this state, but if you go and delete records in the dataflow history table back to when you saw this issue happen, that should clear it up. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/525b4bcc-dff4-49e7-adfb-7bfd2c459393)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1573ad7f-647a-411f-971a-a1b3e991e8e5)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0349e640-c533-4344-9c36-df9b56e20b52)

**Comment by shoffma1** [comment] 2024-01-26 13:10
> I'm not sure how you got into this state, but if you go and delete records in the dataflow history table back to when you saw this issue happen, that should clear it up. ![image](https://private-user-images.githubusercontent.com/89584709/299839069-525b4bcc-dff4-49e7-adfb-7bfd2c459393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzQ0MjYsIm5iZiI6MTcwNjI3NDEyNiwicGF0aCI6Ii84OTU4NDcwOS8yOTk4MzkwNjktNTI1YjRiY2MtZGZmNC00OWU3LWFkZmItN2JmZDJjNDU5MzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEzMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNzk3NThiZDlkZjU4OTExODNlZjZiNTc1NjFmOTExZGI5OGE0ZjBkY2UyMjM2ZjE5Y2Y3NWFjZjBjNGFmMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SbLDamcQxQCCBLSZX8SrRm9H7qOJKjilEPBGPEZUHbE) ![image](https://private-user-images.githubusercontent.com/89584709/299839352-1573ad7f-647a-411f-971a-a1b3e991e8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzQ0MjYsIm5iZiI6MTcwNjI3NDEyNiwicGF0aCI6Ii84OTU4NDcwOS8yOTk4MzkzNTItMTU3M2FkN2YtNjQ3YS00MTFmLTk3MWEtYTFiM2U5OTFlOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEzMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MWM1ZjM5OGRhMWFiYWUwZTJlNmVmYzg5NTUwMDczMGRmODE1MDJhNGE2OTZkZWM5ZGFhYTU4YzI4ZGEzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9_4JBlV8LwAUMYVkSDyu6oPOSeQwtCWdZJzU4TSsA0) ![image](https://private-user-images.githubusercontent.com/89584709/299839414-0349e640-c533-4344-9c36-df9b56e20b52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzQ0MjYsIm5iZiI6MTcwNjI3NDEyNiwicGF0aCI6Ii84OTU4NDcwOS8yOTk4Mzk0MTQtMDM0OWU2NDAtYzUzMy00MzQ0LTljMzYtZGY5YjU2ZTIwYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEzMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZWMxOTI3ZGFkNGJmZDZlMjk4ZGI2YWE3NDMwMTk5M2NiMzI5NTE2YWUyYjM1MDU2YzA0ZTExMTJiNDM2OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sczFyrkwpcEBqdZwl2fFQVz8Xk9cE81bFQbRuH3EH98)

Thanks for this.  Would there perhaps be a more automated way to delete all rows from this table, as I have no idea when the issue started.

**Comment by niwrejim21** [comment] 2024-01-26 13:25
@Jenefer-Monroe , it happened again today - it seems that this is an intermittent issue. No dataflow failed during the scheduled refresh but some of the resources including our default environment got marked for deletion again. Yesterday, the scheduled refresh worked fine. To be able to fix it, I had to do a refresh of the dataflows again.

**Comment by Jenefer-Monroe** [comment] 2024-01-27 01:24
We did create a more automated way to do this in the Feb release. You'll now see a button which lets you delete back as far as you want
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/82206ef0-54a0-494f-85d8-73461193e854)

**Comment by Jenefer-Monroe** [comment] 2024-01-27 01:25
@niwrejim21 I'm not sure what you mean by marked for deletion. Do you mean they are marked as deleted? 
Please take a sample object that you think should not be marked deleted, and see if it exists in the dataflow file.

**Comment by Jenefer-Monroe** [comment] 2024-01-30 01:58
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)
Then see if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by Jenefer-Monroe** [comment] 2024-01-30 13:11
ok another person posted the question and it pointed me to the issue. Please see https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148 for how to locally resolve. And let me know!

**Comment by shoffma1** [comment] 2024-01-30 14:12
> ok another person posted the question and it pointed me to the issue. Please see [#7562 (comment)](https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148) for how to locally resolve. And let me know!

Not sure this will work for us, as this particular flows is not "On", and gives an error trying to do so.  Sorry, I can't keep straight which flows should be on or off for the ByoDL solution vs the older.

**Comment by Jenefer-Monroe** [comment] 2024-01-30 20:17
No problem. The instructions for the workaround are for a Dataflow. So if you are using DAta Export that one should be on. The issue is in the Dataflow (which brings the default ent back as **_default-abc123_**.... instead of **_Default-abc123_**...). So regardless of if you are using v3 or v4 of the check deleted cloud flow system, you would be impacted.

**Comment by niwrejim21** [comment] 2024-01-31 13:35
@Jenefer-Monroe - confirming that the fix resolved our issue as well. Appreciate all the help!!!

**Comment by shoffma1** [comment] 2024-02-01 13:13
After applying the above code to our dataflow, and activating the Admin sync flow, the general number of flows seems to be correct, however all of the data is now missing in the active flows view, or when clicking into one of the flows from there ...
<img width="339" alt="2024-02-01 07_11_15-Flows Active Flows - Power Apps and 2 more pages -  InPrivate  - Microsoft​ Edge" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/c85780d6-cafa-4d7a-a092-eb3c6ab46a80">

**Comment by Jenefer-Monroe** [comment] 2024-02-01 13:48
What do you mean by this: `and activating the Admin sync flow`

**Comment by shoffma1** [comment] 2024-02-01 14:47
Currently all of our v4 flows are off, … I had thought we needed this one on …

***@***.***

**Comment by shoffma1** [comment] 2024-02-01 15:29
> What do you mean by this: `and activating the Admin sync flow`

Currently all of our v4 Cleanup flows are off.  I had activated this one for a short time: CLEANUP - Admin | Sync Template v4 (Check Deleted)CLEANUP - Admin | Sync Template v4 (Check Deleted)

**Comment by Jenefer-Monroe** [comment] 2024-02-01 17:45
This is written to from another dataflow and mine is working as are the other folks who did the workaround. So I think there may be something unique to your envt. 
- Are all the records blank or just a few?
- Are all the fields blank or just display name? In particular is the envt lookup field filled/

**Comment by shoffma1** [comment] 2024-02-02 13:33
As of this morning, these flows are now not listed at all. Even after removing the "Flow is marked deleted" filter. 
<img width="694" alt="Screenshot 2024-02-02 073039" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/567c3b30-95ce-45d3-9a48-56b9cb5ddcd4">

**Comment by shoffma1** [comment] 2024-02-02 13:36
As of this morning none of these flows are listed at all, even after removing the "Flow Deleted" filter.

<img width="681" alt="2024-02-02 07_33_58-Environments Active Environments - Power Apps" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/ce5b522b-13f9-4166-97ea-0b9077544d91">

**Comment by Jenefer-Monroe** [comment] 2024-02-02 14:45
If you go look at the flow table itself, instead of this roll up number, do you see flows in default?

**Comment by shoffma1** [comment] 2024-02-02 15:22
No, nothing from the default environment.  It almost seems like our "service" account had lost access to that environment, but it does have the "System Administrator" role there, and the "Power Platform Admin" role in Entra, though it is from a group.

**Comment by Jenefer-Monroe** [comment] 2024-02-03 14:57
Can you go see if the file is present in the Data Export storage account? 


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/07c32b4f-be8b-47ed-b350-694546109f96)

**Comment by Jenefer-Monroe** [comment] 2024-02-05 18:36
Great. Please view the dataflows. 
First please confirm that you only have the Next Refresh on Maker (not on any other dataflow)
Then go to the refresh history for the Flows dataflow, is it passing?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ac8c615a-3b29-445f-9e22-a48c75f04147)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/12d25b2a-72c9-48ca-b84d-8a7845939310)

**Comment by shoffma1** [comment] 2024-02-05 18:44
Correct, only the "CoE BYODL Makers" dataflow has a "Next refresh" that is not "N/A".

And the refresh history for "CoE BYODL Flows" is showing success as far back as that goes (12/18/2023).

**Comment by Jenefer-Monroe** [comment] 2024-02-06 16:12
great, now please note the last modified date for the Default-abc... record for flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/64a48ba0-f3dd-4bf4-8462-925c04d350bf)

Delete the records from the DataflowRefreshHistories table back through that date
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/01a76b0b-910b-4d32-9d86-48ca0d977e0d)

Open the flow **_CoE BYODL Flows_** dataflow and see if you find the default envt flows in there, and if the name of the environment has the upper or lower casing for the word default: **_Default-abc..._** or **_default-abc..._**
You may need to filter to just default if they are hard to find like i did here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/757c2dcb-daf4-4dc0-bedc-f07544ec25aa)

**Comment by shoffma1** [comment] 2024-02-06 16:36
Our data export file for our default environment has the current date (6-Feb). I did go ahead and delete today's refresh history items regardless.

Not sure if this is relevant, but we have two dataflows uploaded to powerbi ... one is the january release, which is showing our Default environment, with a capital D.  The older dataflow shows the default environment with a lowercase d.

When I look from the "make.powerapps.com" portal, I'm getting the message, "This table has no rows".

<img width="761" alt="NoRows" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/72c2926b-e4a3-4237-babd-70f84fffa91c">

**Comment by Jenefer-Monroe** [comment] 2024-02-06 16:47
We aren't doing anything with the PBI Dataflows here. The change above is not neeed for them. 
We are only working with the Dataflows in the solution which write to the Dataverse tables. 
Can you confirm we are on the same page?

**Comment by shoffma1** [comment] 2024-02-06 16:55
Yes, confirming I am making changes in our CoE ByoDL environment only.

**Comment by shoffma1** [comment] 2024-02-12 15:25
This should probably be another issue report, but running the upgrade wizard after installing the 4.23 Core components solution, getting this on the first page after the modal windows.

<img width="618" alt="Coe_Upgrade_Error" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/022bb262-bac2-4115-bc42-48bb1a40c08c">

**Comment by shoffma1** [comment] 2024-02-13 16:35
After installing the 4.23 Core components, I was able to delete all the DataFlowRefreshHistory items.  Thank you for that option to delete all!

Now I am getting this error, even after configuring the connections, etc., in the DataFlows ... this is the BYODL Environments dataflow ...

<img width="919" alt="Screenshot 2024-02-13 103240" src="https://github.com/microsoft/coe-starter-kit/assets/54184520/0a21ac94-d805-4299-80b9-19f359dc4097">

**Comment by Jenefer-Monroe** [comment] 2024-02-14 01:30
This means that the maker is not in the inventory. This typically happens when you have set the next reresh on all the dataflows instead of just the maker one. 
Can you confirm that you only have it on for Maker?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc968f0f-9f46-4ede-9a61-574695d83428)

**Comment by shoffma1** [comment] 2024-02-14 13:43
FYI, after our daily refresh(es) completed this morning, we have zero blank flows showing, and the correct number of flows from our default environment.  I think we're good at this point.  Thanks for your help!

**Comment by Jenefer-Monroe** [comment] 2024-02-15 16:35
Wonderful news! I'm still testing a little more and have a few other folks testing as well so ill hold this till early next week and then hopefully close out feeling good about the March release :)

Thanks for your help!

**Comment by Jenefer-Monroe** [comment] 2024-02-19 23:47
ok this is looking good for March release.

**Closed by Jenefer-Monroe** 2024-02-19 23:47 UTC
Labels: question, coe-starter-kit
