### ISSUE TITLE
[ALM Accelerator - BUG]: Connection References are not showing up

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#4179] opened 2022-11-14 17:56 UTC
### Describe the issue

Could not able to see any of the  Connection References under "Configure Deployment Settings" although the solution has 8 Connection References.  Attaching the screenshot for your reference.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/33087528/201731255-3f95eef1-f8d7-44b7-893d-6c858a85e23d.png">

### Expected Behavior

We should see Connection References.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221101.1

### Steps To Reproduce

1. Select any solution in ALM Accelerator Canvas App
2.  Go to Configure Deployment Settings
3.  Look for the Connection References tab

**Comment by challa85** [comment] 2022-11-15 16:28
Thanks for the response Mike. The flow is failing with below error.

{
  "error": {
    "code": 400,
    "source": "flow-apim-unitedstates-002-eastus-01.azure-apim.net",
    "clientRequestId": "782f2b31-c47e-4e43-8a1a-7d9946051561",
    "message": "The response is not in a JSON format.",
    "innerError": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n"
  }
}

**Comment by mikefactorial** [comment] 2022-11-15 16:45
@challa85 thanks for following up. We're aware of this issue and have a plan in place to address it in the upcoming release. Closing as a duplicate of https://github.com/microsoft/coe-starter-kit/issues/4138. When we have implemented the solution for the upcoming release I'll share the details on the existing issue. Thanks again.

**Comment by mikefactorial** [comment] 2022-11-15 16:45
You can see more specifics about the issue on https://github.com/microsoft/coe-starter-kit/issues/4138

**Closed by mikefactorial** 2022-11-15 16:45 UTC
Labels: bug, alm-accelerator

**Comment by challa85** [comment] 2022-11-15 17:05
Thanks, Mike. Will wait for the fix.

**Comment by mikefactorial** [comment] 2022-11-21 16:35
@challa85 here's a link to the prerelease build with the update to the flow for you to validate. Let me know if you have any questions. Will also post it to #4138 if you want to collaborate with the rest of the team on that issue. Thanks
https://mikefactorial-my.sharepoint.com/:u:/p/mike/EUkOwEkTQJtGmU-gEpXP6BUBcDCLk1Ufb3bW7sb4lQL_fg?e=6xcpmH
