### ISSUE TITLE
[CoE Starter Kit - BUG] getting error when Admin | Sync Template v3 (Desktop flows) runs

### ISSUE THREAD

**Issue by NemadeUjwal** [microsoft/coe-starter-kit#3112] opened 2022-07-04 11:59 UTC
### Describe the issue

![DesktopFlowError](https://user-images.githubusercontent.com/99943014/177149651-2b984f1f-ac79-498d-87b9-f0f503c9023b.JPG)

Hi,
In run history of Admin | Sync Template v3 (Desktop flows), I am getting error as below 
Http request failed as there is an error: 'Cannot write more bytes to the    buffer than the configured maximum buffer size: 104857600.'.

Can you please help, In COE table also there is no enteires for Desktop flow and so the BI report is also blank for Desktop Flow tab

### Expected Behavior

Flow should run sucessfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### Steps To Reproduce

Kindly find attached screenshot

**Comment by Jenefer-Monroe** [comment] 2022-07-04 15:25
Hello. I'm afraid you have hit a product limitation which blocks the kit from correctly inventorying your desktop flows
Please see #2102  for details, and track it for updates.
We are awaiting a product change and will fix this once available.

Duplicate of #2102

**Closed by Jenefer-Monroe** 2022-07-04 15:25 UTC
Labels: bug, coe-starter-kit
