### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Detail Request V3 Flow Errors

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1227] opened 2021-09-24 12:50 UTC
### Describe the issue

When I run the flow Admin | Compliance detail request v3, as it iterates through the environments at the "Apply to each envApp" step, on some environments it errors with the message: Request to Azure Resource Manager failed with error: '{"error":{"code":"ActionRepetitionNotFound","message":"The specified repetition '000001-000000' of workflow action 'Get_Assignee_apps' is not found."}}'.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

### Anything else?

![image](https://user-images.githubusercontent.com/17124284/134676931-5c9d0642-7e9d-44b5-9ef1-77a46facfb15.png)

**Comment by Jenefer-Monroe** [comment] 2021-09-24 13:35
You picture doesn't show  which action actually failed. I believe its the Recheck Orphan Status envt app though. Can you confirm? If so this is a duplicate of #1209 , the left side of the conditions got stripped out somehow, and so we arent checking for the value to be null any longer before it gets sent to that action.

**Comment by medicineshow** [comment] 2021-09-27 11:53
You are correct, it is the Recheck Orphan Status envt app. Can you give us the fix for this that will be released in Oct so that we can test this now? Also, is it expected behaviour that it does actually work for some of the environments that it checks?

**Comment by Jenefer-Monroe** [comment] 2021-09-27 13:53
I'm afraid we cannot generate PRs right now as there is some work in progress which results in me not being able to predict what I send you to be functional. 

And I don't understand your last question, can you please clarify? It is, of course, expected to work.

**Comment by medicineshow** [comment] 2021-09-27 15:58
LOL. What I meant is that the flow iterates through each of the environments and gets the list of apps that are then processed and an action applied. If I look at the flow result and step through each of the environments I can see that for some of the environments, it has run without an error at that step.

**Comment by Jenefer-Monroe** [comment] 2021-09-27 16:13
oh i see :)
I dont have expectations for how this will behave today in this broken state. We will be shipping next week and so if you have questions at that time please repost. 
Marking as dupe. Thank you
Duplicate of #1209

**Closed by Jenefer-Monroe** 2021-09-27 16:13 UTC
Labels: coe-starter-kit
