### ISSUE TITLE
[ALM Accelerator - QUESTION] Parameter error on Commit

### ISSUE THREAD

**Issue by bronsonacoutts** [microsoft/coe-starter-kit#3314] opened 2022-07-29 14:43 UTC
### What is your question?

Hi Guys,

I am particularly stuck with this error.  This was occurring prior to upgrading to the August '22 release.  I am certainly no Devops expert and really don't know where to begin troubleshooting this.  If it were a simple exercise to just scrap and re-install from scratch I would, but that is an internally process that requires a Global Admin and so on as I am sure you can appreciate.  Besides, I would really like to understand what is going on under the hood a little better.

Each time I try to Commit a solution, any solution, I am encountering the same Notify() error in the Canvas App in the Advanced Maker Experience.

`Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"Unexpected parameter 'Branch'\nUnexpected parameter 'BranchToCreate'\nUnexpected parameter 'BuildDefinitionId'\nUnexpected parameter 'CommitMessage'\nUnexpected parameter 'Data'\nUnexpected parameter 'Email'\nUnexpected parameter 'EnvironmentName'\nUnexpected parameter 'ImportUnmanaged'\nUnexpected parameter 'PipelineId'\nUnexpected parameter 'Project'","typeName":"Microsoft.Azure.Pipelines....`

Little help?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

August 2022

**Comment by jenschristianschroder** [comment] 2022-08-01 13:02
Hi,

Looks like you have not updated to the latest version of the pipeline templates. The pipeline templates should be upgraded when you upgrade the ALM Accelerator solution.

Here is the docs page on how to upgrade the pipelines: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config#updating-the-pipelines-in-azure-devops

**Comment by bronsonacoutts** [comment] 2022-08-02 01:32
Thanks for that,  I went back and processed the upgrade again and can confirm that there are files in the pipeline templates repo that have dates edited last month.

But I am still getting this error:

`Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"Unexpected parameter 'Branch'\nUnexpected parameter 'BranchToCreate'\nUnexpected parameter 'BuildDefinitionId'\nUnexpected parameter 'CommitMessage'\nUnexpected parameter 'Data'\nUnexpected parameter 'Email'\nUnexpected parameter 'EnvironmentName'\nUnexpected parameter 'ImportUnmanaged'\nUnexpected parameter 'PipelineId'\nUnexpected parameter 'Project'","typeName":"Microsoft.Azure.Pipelines....`

![image](https://user-images.githubusercontent.com/55462373/182272294-7b89d54a-51f3-4698-82c6-e86b072beec3.png)

![image](https://user-images.githubusercontent.com/55462373/182272465-2a83d713-5039-4dad-8bb8-7d58178a32b8.png)

![image](https://user-images.githubusercontent.com/55462373/182272592-b3d22e0b-8f77-48d3-b256-4091d5bf9832.png)

**Comment by PC-BPS** [comment] 2022-08-02 03:20
I have just upgrade our ALM to August (from April) and our Pipeline repo as per documentation. I am experiencing the same/similar error.

This is the first time I have been up to a point where I could commit a solution as our DevOps connector was incorrectly configured.

**Comment by mikefactorial** [comment] 2022-08-02 19:52
@bronsonacoutts and @PC-BPS did you complete the PR and Merge after running the pipeline? The script creates a PR for review but won't update your repo until you review / approve and merge

**Comment by PC-BPS** [comment] 2022-08-02 22:23
Yeah, just double checked and the PR was approved & completed.

**Comment by bronsonacoutts** [comment] 2022-08-03 04:40
I will double check when I'm back in the office a bit later but I would say with 99.5% certainty that it is complete.

**Comment by bronsonacoutts** [comment] 2022-08-03 04:41
Something is making me feel like this could be a Repo permissions thing?  What role does the maker need to have, if any at the Repo level?

**Comment by bronsonacoutts** [comment] 2022-08-03 05:55
> I will double check when I'm back in the office a bit later but I would say with 99.5% certainty that it is complete.

Yes the PR is completed.

**Comment by mikefactorial** [comment] 2022-08-03 08:57
@bronsonacoutts The error message is pretty clear. The issue is that the latest pipelines aren't reflected in the local copy of the pipelines. We moved from using variables to using parameters in our export, import, delete pipelines in the July release and the app was updated to reflect this. You can tell if you have the latest by comparing your local copy of the following pipelines

https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/export-solution-to-git.yml
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/import-unmanaged-to-dev-environment.yml
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/delete-unmanaged-solution-and-components.yml

Assuming your local copy reflects the addition of the parameters at the top of those files the only other possibility would be that your pipelines are pointed at a different repo / branch etc. If not then you may just have to copy over the latest pipelines manually to your repo. Simplest way to do that would probably be to just delete the repo / recreate it and the import from our repo.

**Comment by bronsonacoutts** [comment] 2022-08-03 10:57
Ok, I think I've already done that TBH, I'll do it again to make sure it's right.  Thanks

**Comment by mikefactorial** [comment] 2022-08-03 11:04
May be a good idea to double check what the pipeline is pointing at in that case e.g. Go to the export-solution-to-git pipeline and click edit. You should see the expected parameters. If not it could be pointing to the wrong branch.

![image](https://user-images.githubusercontent.com/42348035/182593177-422895e5-af4b-4eac-8c4a-1576efd4dbb6.png)

**Comment by bronsonacoutts** [comment] 2022-08-05 08:50
You might be on to something there!   Thanks!

So I take it deleting and re-importing the repo wont resolve this?

![image](https://user-images.githubusercontent.com/55462373/183040262-69f39a86-fb0e-4216-a4d7-acbd7e6605ec.png)

**Comment by mikefactorial** [comment] 2022-08-05 22:47
@bronsonacoutts deleting / recreating / reimporting the repo should resolve it. The only thing you have to make sure of is after import you set the default branch of the repo to main. In  the screenshot below it's disabled because main is the default branch but on import AzDO has a tendency to pick whichever branch comes first alphabetically.
![image](https://user-images.githubusercontent.com/42348035/183220726-89db4759-e351-4729-a688-0906936f223e.png)

**Comment by bronsonacoutts** [comment] 2022-08-09 05:19
Thanks a lot for that Mike.  Makes a lot of sense, I think that perhaps the whole issue here may have just been the setting of the default branch. :-/.

I have progress, although now having blown away the repo, re-importing then re-syncing with the pipeline sync & approving the PR, I am getting this:

Is there a specific part of the manual installation documentation you can point me toward that I can follow that might help to resolve this one?

![image](https://user-images.githubusercontent.com/55462373/183570354-3af63e67-148c-4ede-a7a3-3ac8bb58efcc.png)


`Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"Unable to resolve the reference 'refs/heads/main' to a specific version. Verify the reference exists in the source repository.","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}`

**Comment by PC-BPS** [comment] 2022-08-09 05:33
@bronsonacoutts 

I have gotten passed this issue. 

- I wiped the pipeline repo
- recreated it. set the default branch to main (important!)
- deleted the existing deployment yml configs and created new from the samples.
- recreated the export-solution-to-git, import-unmanaged-to-dev-environment and delete-unmanaged-solution-and-component pipelines.

I then had some other issues, I fixed by:
- setting the variables EnvironmentName & ServiceConnection
- setting the deployment settings for all environments (connection refs, permissions, flows etc.)


Thanks @mikefactorial & @jenschristianschroder for your support.

**Comment by bronsonacoutts** [comment] 2022-08-09 07:18
> @bronsonacoutts 
> 
> I have gotten passed this issue. 
> 
> - I wiped the pipeline repo
> - recreated it. set the default branch to main (important!)
> - deleted the existing deployment yml configs and created new from the samples.
> - recreated the export-solution-to-git, import-unmanaged-to-dev-environment and delete-unmanaged-solution-and-component pipelines.
> 
> I then had some other issues, I fixed by:
> - setting the variables EnvironmentName & ServiceConnection
> - setting the deployment settings for all environments (connection refs, permissions, flows etc.)
> 
> 
> Thanks @mikefactorial & @jenschristianschroder for your support.

Awesome thanks for that!  I feel like that might be a winner for me too! I'll give it a go!

Thanks all for your help.

**Comment by mikefactorial** [comment] 2022-09-07 14:46
Closing out as there's nothing more to do on this issue. Thanks for all the feedback and collaboration!

**Closed by mikefactorial** 2022-09-07 14:46 UTC
Labels: question, alm-accelerator

**Comment by bronsonacoutts** [comment] 2022-09-19 00:09
Thanks @mikefactorial finally managed to get the time to get into this and sort it out.   Took a couple of tries following your instructions but I got there.

**Comment by Tamy05** [comment] 2023-11-10 09:24
Hey @mikefactorial getting the same error Error running pipeline: {"$id":"1","innerException":null,"message":"An error occurred while loading the YAML build pipeline. File /Pipelines/export-solution-to-git.yml not found in repository "url"-templates branch refs/heads/main version d38309dd3b25dc5b52b32af85cdb4e858849b5ff.","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException while i click on Comit in the canvas app can you please help me with this ?
