### ISSUE TITLE
[ALM Accelerator - BUG]: Work : The term 'Work' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by HymansTesting** [microsoft/coe-starter-kit#3555] opened 2022-08-31 12:17 UTC
### Describe the issue

The step called "Disable / Enable Solution Flows" from the Deploy Solution feature is erroring with:

"Work : The term 'Work' is not recognized as a name of a cmdlet, function, script file, or executable program."

Deploying the managed solution works without error or issue, however issue still persists even after the manual import.

### Expected Behavior

Deployment of the solution as it does when manually invoked.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

### Steps To Reproduce

Deploy managed solution, whether it exists or not in the environment makes no difference.

### Anything else?

![image](https://user-images.githubusercontent.com/109288908/187675563-d42a4939-b830-4329-811a-e7d97b1fc5d5.png)
![image](https://user-images.githubusercontent.com/109288908/187675608-4b6d4be0-6620-4c9c-b4cf-6e3d8d229397.png)

**Comment by HymansTesting** [comment] 2022-08-31 14:05
Update: Removed the workflows relating to the work entity and they has progressed, however now we see:

![image](https://user-images.githubusercontent.com/109288908/187698126-c35da89c-4fc7-429b-83e7-57c88f160815.png)

Please help! Many thanks again. :)

**Comment by linujohn22** [comment] 2022-08-31 16:43
It seems , a workflow trigger on particular entity in that case that entity also should be  part of the solution . This is not correct , there cases we need to move only workflows . seems it is a bug .

**Comment by mikefactorial** [comment] 2022-08-31 17:09
@HymansTesting same ask here. I believe this and https://github.com/microsoft/coe-starter-kit/issues/3563 are the same root cause. 

> Are there any special characters in the names of the flows included in the solution (e.g. question marks, dollar signs, colons etc.?) I saw that some of the names have parentheses which should be okay, but wanted to know if there's anything else that sticks out. It seems like powershell is misinterpreting the json as truncated by something.

**Comment by mikefactorial** [comment] 2022-09-01 16:18
@HymansTesting closing this out for now as it appears to be a duplicate of https://github.com/microsoft/coe-starter-kit/issues/3563

**Closed by mikefactorial** 2022-09-01 16:18 UTC
Labels: bug, alm-accelerator
