### ISSUE TITLE
[ALM Accelerator - BUG]: Update the Webhook Url value

### ISSUE THREAD

**Issue by alzia-msft** [microsoft/coe-starter-kit#1645] opened 2021-12-17 18:04 UTC
### Describe the issue

Per the documentation we are supposed to copy the webhook Url from the WorkflowCompleted Flow's HTTP action, the value is empty when the flow is opened.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/92477952/146588243-11931c07-63a0-43f7-8b73-47f7686b3ace.png">

### Expected Behavior

A webhook url value that can be pasted into the ALM Accelerator Admin Configuration app.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

1. Open the WorkflowComplete Flow
2. Expand the HTTP action
3. Copy the URL value that appears empty

**Comment by bretthamilton** [comment] 2021-12-17 18:07
Following.

**Comment by mikefactorial** [comment] 2021-12-17 23:23
Likely a duplicate of #1512. @fooshen

**Closed** 2021-12-17 23:25 UTC
Labels: alm-accelerator
