### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot publish Power App theme

### ISSUE THREAD

**Issue by t-irani** [microsoft/coe-starter-kit#887] opened 2021-07-21 22:13 UTC
### Describe the issue

There are two issues I'm experiencing.
1. Following the instructions in the Microsoft document [https://docs.microsoft.com/en-us/power-platform/guidance/coe/theming-components] I'm trying to publish a Power App theme from the CoE Theme Editor. Once the theme colours have been selected, I cannot upload the modified template .msapp files within the Theming app. The ‘Upload File’ sections don’t work. The two 'upload' controls are broken, with the fields constantly displaying ‘Getting your data…’.

2. I don't know if this is by design, but I cannot interact with the Theme Preview controls. I would expect these to behave like they normally would in an app so you can see the colors in the varying states the controls can exist in. Is this by design or a bug. If it's by design, then it's not too helpful!

Thanks 

### Expected Behavior

The Theme Editor app should allow modified .msapp files (containing a reference to the theme in App / OnStart) to be uploaded. It does not.
I believe the Theme Preview controls should be interactive to show the different control states so the effect on color selections can be observed.

### What solution are you experiencing the issue with?

Theming

### What solution version are you using?

1.2

### What app or flow are you having the issue with?

CoE Theme Editor

### Steps To Reproduce

1. Create Theme
2. Edit Theme colours
3. Save
4. Publish - Cannot upload .msapp files

**Comment by carolynle27** [comment] 2021-07-30 04:42
Hey team, is there a workaround for this or an expected ETA for a fix?

**Comment by charrisonfuji** [comment] 2021-08-03 07:51
@t-irani see this workaround https://github.com/microsoft/coe-starter-kit/issues/553#issue-908374101

**Comment by mikefactorial** [comment] 2021-08-03 14:20
Closing this for now duplicate of #402. Will update on that issue

**Closed by mikefactorial** 2021-08-03 14:20 UTC
Labels: theming
