### ISSUE TITLE
[ALM Accelerator - BUG]: Cannot import solution with environment variable

### ISSUE THREAD

**Issue by rajyraman** [microsoft/coe-starter-kit#1395] opened 2021-10-22 01:24 UTC
### Describe the issue

I am raising this under ALM Accelerator, but it seems to be a product issue. When I import the solution and deploymentSettings.json has the value for environment variable solution import still fails with this cryptic error. I have the environment variable in the unpacked solution folder without the value. That value is provided before the solution is imported. I tried `pac solution import -p "SOLUTION_managed.zip" -ap true -f true --settings-file "solution.json"`, but I get the same exception without runtime tenplate string replacements.

`Microsoft.Crm.CrmException: The evaluation of the current component(name=EnvironmentVariableValue, id=97d8df0c-7ab6-ea11-a812-000d3a6aaf3f) in the current operation (Delete) failed during managed property evaluation of condition: Managed Property Name: ismanaged; Component Name: EnvironmentVariableValue;  ---> Microsoft.Crm.CrmException: The evaluation of the current component(name=EnvironmentVariableValue, id=97d8df0c-7ab6-ea11-a812-000d3a6aaf3f) in the current operation (Delete) failed during managed property evaluation of condition: Managed Property Name: ismanaged; Component Name: EnvironmentVariableValue; 
at Microsoft.Crm.BusinessEntities.PropertyEvaluationContainer.EvaluationConditionCollection(ICollection`1 conditions, IEntity entity, OperationType operation, List`1 errors, ExecutionContext context)
at Microsoft.Crm.BusinessEntities.PropertyEvaluationContainer.EvaluateInternal(IEntity entity, OperationType operation, ExecutionContext context)
at Microsoft.Crm.BusinessEntities.ManagedPropertyExtension.PreDeleteHandler(Object sender, ExtensionEventArgs e)
at Microsoft.Crm.BusinessEntities.BusinessProcessObject.PreDeleteEventHandler.Invoke(Object sender, ExtensionEventArgs e)
at Microsoft.Crm.BusinessEntities.BusinessProcessObject.InternalDelete(BusinessEntityMoniker moniker, ExecutionContext context)
at Microsoft.Crm.BusinessEntities.InternalDeleteStrategy.Delete(BusinessProcessObject proc, CascadeRecord record)
at Microsoft.Crm.BusinessEntities.CascadeDeletionHandler.Delete(BusinessProcessObject proc, CascadeRecord record, ExecutionContext context)
at Microsoft.Crm.BusinessEntities.CascadeEngine.<>c__DisplayClass27_0.<CascadeDeleteBulkOM>b__0()
at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
at Microsoft.Crm.BusinessEntities.CascadeEngine.<>c__DisplayClass9_0.<CascadeDeleteDB>b__0()
at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
at Microsoft.Crm.BusinessEntities.CascadeEngine.<>c__DisplayClass94_0.<Delete>b__0()
at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
at Microsoft.Crm.BusinessEntities.BusinessProcessObject.<>c__DisplayClass268_0.<Delete>b__0()
at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
--- End of inner exception stack trace ---
at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
at Microsoft.Crm.Extensibility.Pipeline.<>c__DisplayClass3_0.<RunStep>b__0()`

![image](https://user-images.githubusercontent.com/5035266/138378545-23cd1b93-49f4-4353-9d99-36d46e6274e7.png)

### Expected Behavior

Solution should import with the env variable specified in JSON.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210922.2

**Comment by mikefactorial** [comment] 2021-11-04 18:06
Following up on this. I'm told this is in the backlog to be fixed in PAC CLI. Will continue to follow up with engineering on when the fix is available.

**Comment by mdpc-nnit** [comment] 2022-01-11 15:39
Hi, do you know the status on this one? We encounter a similar error, but only in production.

**Comment by mikefactorial** [comment] 2022-01-11 18:38
@mdpc-nnit Haven't gotten an update. I will reach out again to see when this is expected to be fixed.

**Comment by lavanden** [comment] 2022-01-11 19:50
This happens when you have a current value set on an environment variable. On deployment to a downstream environment, this value will be set as a managed property. When the deployment profile wants to update the value (delete the old one, upload the new one) it will fail.

The following steps will solve the issue: 
- Remove the current value in the development environment
- Import the solution with upgrade in the downstream environment (without deployment profile). This will uninstall the current value on the downstream environment
- Now you should be able to release again with a deployment profile.

**Comment by mdpc-nnit** [comment] 2022-01-12 09:14
@lavanden thanks for providing a workaorund! I have tried to delete values before, but never found out what actually worked

**Comment by mdpc-nnit** [comment] 2022-01-12 11:09
I am trying the workaround as we speak and it doesn't seem to uninstall the current value. I deploy through pipelines and removed the variables

`
    UseDeploymentSettingsFile: $(UseDeploymentSettings)
    DeploymentSettingsFile: $(DeploymentSettingsPath)
`

since I couldn't get it to understand `UseDeploymentSettingsFile: false` but it is still not deleting the current value. Any ideas?

**Comment by lavanden** [comment] 2022-01-12 11:15
> I am trying the workaround as we speak and it doesn't seem to uninstall the current value. I deploy through pipelines and removed the variables
> 
> `UseDeploymentSettingsFile: $(UseDeploymentSettings) DeploymentSettingsFile: $(DeploymentSettingsPath)`
> 
> since I couldn't get it to understand `UseDeploymentSettingsFile: false` but it is still not deleting the current value. Any ideas?

- Did you remove the current value from the source environment?
- Are you applying upgrade (update does not remove values, only upgrade does)
- Does the solution that you are trying to install have a higher version number?

**Comment by mdpc-nnit** [comment] 2022-01-12 11:19
- we are not exporting current values from the dev environment
- I am doing upgrade, yes
- I am making sure the version is always higher (but the contents are the same)

Actually, I have a hard time reproducing the error in a test environment, because there I can delete the current value no problem. Do you know what exactly triggers whether you can delete a current value from a managed solution?

**Comment by lavanden** [comment] 2022-01-12 11:54
> * we are not exporting current values from the dev environment
> * I am doing upgrade, yes
> * I am making sure the version is always higher (but the contents are the same)
> 
> Actually, I have a hard time reproducing the error in a test environment, because there I can delete the current value no problem. Do you know what exactly triggers whether you can delete a current value from a managed solution?

If the value can be deleted, the value was installed with the deployment profile. The deployment profile just inserts a record. So on this particular environment, the deployment should work with deployment profiles. 

Following trick can be used to verify whether the value was installed by a solution or not:
- Navigate to the environment variable
- in the values subgrid, try to delete the current value (be careful on production instances, this might impact your end users)

If the above throws an error, that means the value is part of a managed solution and the resolution I have mentioned above should be applied (the current value has to be uninstalled by an upgrade and no deployment profile should be used). When it does not throw an error, the PAC CLI should be able to remove the current value and install the new one from the deployment profile.

**Comment by mdpc-nnit** [comment] 2022-01-12 12:17
Thanks for your patience with me. 

Can you clarify under what circumstances it will be locked as a managed property?

**Comment by lavanden** [comment] 2022-01-12 12:30
> Thanks for your patience with me.
> 
> Can you clarify under what circumstances it will be locked as a managed property?

No problem. Happy to help.

If the 'current value' is set in the source environment and you export it as managed, the value will be part of the managed solution (and locked after an installation of the solution in the target env)

**Comment by mdpc-nnit** [comment] 2022-01-12 12:56
Ahhh. Great, now I both know how to reproduce AND I was able to verify the workaround! Many thanks

**Comment by mikefactorial** [comment] 2022-02-09 15:53
I'm having trouble replicating this now. Trying to create a small repro for the product team responsible for PAC (attached).

I've tried using latest version of PAC and version 1.10.14 based on the last comment from @mdpc-nnit 28 days ago. Doesn't seem to fail anymore with either.

The PS does the following. ([EVRepro.zip](https://github.com/microsoft/coe-starter-kit/files/8034047/EVRepro.zip))
1. Deletes solution if it exists
2. Imports solution (including an existing environment variable value) - Result is solution imports without error and current value is what is included in the solution.
3. Imports solution with deployment configuration json that includes a new value - Result is solution imports without error and current value is what is included in the config json.

@rajyraman, @lavanden, @mdpc-nnit is there a scenario I'm missing here? If not, this may have been fixed already. Thanks for the assistance in advance.[](url)

**Comment by mikefactorial** [comment] 2022-02-15 23:36
@rajyraman, @lavanden, @mdpc-nnit I've attempted to reproduce this for the product team, but it doesn't seem to be reproducible anymore. Closing out this issue. Feel free to follow up with a specific repro if you have one, but at this point this no longer seems to be an issue in the platform.

**Closed by mikefactorial** 2022-02-15 23:36 UTC
Labels: alm-accelerator, vnext
