### ISSUE TITLE
[ALM Accelerator - BUG]: Validation Pipeline not being triggered

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#6707] opened 2023-09-25 17:56 UTC
### Describe the issue

The Validation pipeline is not getting triggered in the first deployment. A pull request is being created but when I complete it, the Test pipeline starts directly.

### Expected Behavior

The Validation pipeline should run first without the need of the Pull Request to be completed.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2023

### Steps To Reproduce

1. Open the ALM Accelerator Canvas App
2. Commit the Solution
3. Click on Deploy
4. Set the Target as Test

**Comment by LucX4** [comment] 2023-09-25 19:40
Hey @mikefactorial, hope you are fine!
Could you please help me? It would be great to understand the standard behavior of the branchs at each step of the process: commit, deploy to test and deploy to prod.

**Comment by abhizc** [comment] 2023-09-26 17:12
Can you recheck the branch policies? [Set branch policies for pull request validation](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#set-branch-policies-for-pull-request-validation)

**Comment by LucX4** [comment] 2023-09-26 18:34
> Can you recheck the branch policies? [Set branch policies for pull request validation](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#set-branch-policies-for-pull-request-validation)

Yes, that is what was missing. I think it was because I used the same environment for Validation and Test in the Profile.
I know that we don't need to do this manually in each new repository, so I've created a new project and configured a new Profile using different environments for Validation and Test, and now it's working as expected.

**Comment by mikefactorial** [comment] 2023-09-26 19:26
Thanks @abhizc for pointing out the branch policy 👍 @LucX4 thanks for following up. Will take a look at the scenario you described with the same validation and test environment. Could be a regression since that setup worked previously. Closing this for now.

**Closed by mikefactorial** 2023-09-26 19:26 UTC
Labels: bug, alm-accelerator
