### ISSUE TITLE
[CoE Starter Kit - BUG] PBI Dataverse 202110 Template Issues with Dataverse Core

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1435] opened 2021-11-03 21:53 UTC
When attempting to set up the newer Dataverse-connected PBI dashboard tied to a full Dataverse environment I had just upgraded all the solutions in, but the one I'm assuming is needing attention is core to 3.18, I get an error when trying to load the tables.  The App Connection Reference and Flow Connection Reference tables both throw errors that "A join operation cannot result in a table with duplicate column names ("owningbusinessunitname")."  This also blocks the loading of any other tables into PBI.
![image](https://user-images.githubusercontent.com/41799380/140198019-dee1e782-f768-4d6a-b13e-8381bcaa4b0d.png)

I assume this is an issue with the upgrade of the core solution even though that completed normally and looks OK when looking at columns because I can use this same PBI Template and successfully load data when connecting to my D4T environment that I upgraded to 3.6 today also.

**Comment by bartsneary** [comment] 2021-11-03 22:06
Not sure how I got this opened without the issue template, so sorry it's not tagged or assigned to anyone.  I don't seem to have rights to fix that.

**Comment by Jenefer-Monroe** [comment] 2021-11-04 01:52
Duplicate of #1291
We are not able to repro this locally and hence cannot fix it. But if you look at this bug I've linked, they've given steps to resolve.

**Closed by Jenefer-Monroe** 2021-11-04 01:52 UTC
