### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver). Error: Action 'Get_Maker' failed

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#5979] opened 2023-07-03 06:50 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Admin | Sync Template v3 (Driver) flow generates a bug every time it's running. 

The bug occurs under the following blocks:

> Store environments in the CDS entity
> Apply to each environment
> Check if legacy environment
> If No > Get Maker 

### Expected Behavior

Success flow run with data retrieving the environments in my tenant.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In the CoE environment 
2. Run cloud flow: Admin | Sync Template v3 (Driver)
4. See error: Action 'Get_Maker' failed
5. Block: Store environments in the CDS entity
6. Block: Apply to each environment
7. Block: Check if legacy environment
8. Block: If No > Get Maker 

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/727820ca-fd26-455c-bf91-54537e913d30)

**Comment by manuelap-msft** [comment] 2023-07-03 07:42
This is a duplicate of
https://github.com/microsoft/coe-starter-kit/issues/5613

Please find more details in that thread. It will be fixed with our next release.

**Comment by manuelap-msft** [comment] 2023-09-06 11:43
Closing out as this was fixed

**Closed by manuelap-msft** 2023-09-06 11:43 UTC
Labels: bug, duplicate, coe-starter-kit
