### ISSUE TITLE
[ALM Accelerator - BUG]: Errors after approval of new projects

### ISSUE THREAD

**Issue by ey-drien** [microsoft/coe-starter-kit#1764] opened 2022-01-17 08:03 UTC
### Describe the issue

When creating a new project in ALM Accelerator for Makers, we get always one of the error bellow after the approval of the project request:
Error Details: Error found in action: RunCreateEnvironmentFlow with code: Conflict Error: Error Creating Environment with name SVC-PowerApps-CoE_Projekt 17. Error: Error found in action: Force_Sync_user with code: Conflict Error: {"error":{"code":"UnlinkedEnvironmentForbiddenOperation","message":"The environment '5c45d0c9-89cb-475a-b92e-b1a362a14363' is not linked to a new CDS 2.0 instance. The following operation is forbidden for unlinked environments: 'POST/PROVIDERS/MICROSOFT.BUSINESSAPPPLATFORM/SCOPES/ADMIN/ENVIRONMENTS/ADDUSER'"}}
or
Error Details: Error found in action: Assign_Role with code: BadRequest Error: {"error":{"code":"TriggerInputSchemaMismatch","message":"The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'."}}

### Expected Behavior

No errors and creation of a new project.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

1. Import Solution ALMAcceleratorForMakers_1.0.20210521.1_managed.zip
2. Execute all configuration
3. Access ALM Accelerator for Makers app
4. Request approval for a new project
5. Approve new project
6. Error described above

**Comment by ey-drien** [comment] 2022-01-21 11:10
Anybody had the same issue? Or does anyone have an idea what the problem could be?

**Comment by misskristine94** [comment] 2022-02-03 11:40
Hi @ey-drien, I'm currently having the same unfortunately. I've installed the CoE quite a few times previously and haven't had this error before so trying to get to the bottom of it too. If I manage to find the cause, I'll share it with you. Hopefully the CoE team might be able to give us a hand if it's a common error!

**Comment by mikefactorial** [comment] 2022-02-10 00:04
Does this happen every time or occasionally?

This may be a licensing issue if Dataverse capacity isn't available or possibly related to the timing of the Flow that creates the development environment. The flow that creates environments waits for the environment to finish creating asynchronously and can find the environment before the dataverse database has been provisioned.

**Comment by ey-drien** [comment] 2022-02-11 10:21
The error occurs every time and never finished successfully. However the developer environments are being created, but after that the process crashes. Dataverse capacity should be sufficient.

**Comment by Sudhakarvarma** [comment] 2022-02-11 10:47
Hi All,  when I creating Project in ALM Accelerator for maker ,I get the approval Notification ,when I approved Its getting system error,  
Error Details: Error found in action: RunCreateEnvironmentFlow with code: Conflict Error: Error Creating Environment with name admin_ALM_BRAHMA. Error: Error found in action: Create_Environment with code: Conflict Error: {"error":{"code":"InsufficientCapacity_StorageDriven","message":"This environment can't be created because your org (tenant) needs at least 1 GB of database capacity."}}

Please resolve the issue as soon as possible....

**Comment by ey-drien** [comment] 2022-03-10 23:16
@mikefactorial Any updates on that issue? It seems other people like @misskristine94 seem to have the same problem.

**Comment by Pamps2** [comment] 2022-03-29 15:10
Hello @ey-drien , same error here. 
I also notice that this is happening outside the CoE ALM solution for the Action Create CDS database! 
Even creating manually the environment without Database and then creating a simple Flow to create the CDS to this environment it returns Resource Not Found error but the when I check the environment in admin center, the Database is there. It seems to be an issue with this action of the Power Platform for Admins connector

**Comment by mikefactorial** [comment] 2022-06-28 10:17
We've added some better error handling in app.  Closing this out. Feel free to open an enhancement request that we can

**Closed by mikefactorial** 2022-06-28 10:17 UTC
Labels: bug, alm-accelerator
