### ISSUE TITLE
[CoE Starter Kit - BUG] "Sorry there's been a disconnect" - on install

### ISSUE THREAD

**Issue by APICoaching** [microsoft/coe-starter-kit#7050] opened 2023-11-08 15:18 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since Tuesday 7th November, it is impossible to install the Coe Core Component solution version 4.16, either in the Switzerland or Europe region.

- Click next and...you have a purple screen saying 
"Sorry, there's been a disconnect
We can't get that information right now. Either try again or check our support page to see if there are any known issues."
More details : "We can't get that information right now. Either try again or check our support page to see if there are any known issues.
Session ID: 55783040-7e44-11ee-8f21-a9fdbf732c9c"
![Purple screen - 2023-11-08 16_08_19-Power Apps _ Solutions and 6 more pages - Work 5 - Microsoft​ Edge Beta](https://github.com/microsoft/coe-starter-kit/assets/150267535/ac7f3ad5-4033-4a44-b288-ed580c9f2dee)

### Expected Behavior

The system should present me all the Environment variables after clicking Next.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

The Solution

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

- From a production environment either from in Switzerland or Europe Region
- Create all connections - done
- Import the file CenterofExcellenceCoreComponents_4.16_managed.zip solution - done
- Click next and the system checks the solution - done
- Click next and you are presented with all connections - done
- Click next and...you have a purple screen saying 
"Sorry, there's been a disconnect
We can't get that information right now. Either try again or check our support page to see if there are any known issues."
More details : "We can't get that information right now. Either try again or check our support page to see if there are any known issues.
Session ID: 55783040-7e44-11ee-8f21-a9fdbf732c9c"
![Purple screen - 2023-11-08 16_08_19-Power Apps _ Solutions and 6 more pages - Work 5 - Microsoft​ Edge Beta](https://github.com/microsoft/coe-starter-kit/assets/150267535/ac7f3ad5-4033-4a44-b288-ed580c9f2dee)

### Anything else?

I tried with my client in different tenants, removing and recreating the environment, clearing all browser cache, changing browser, etc... no way.
The only change I see is with the HTTP with Azure Connector.
It changes to HTTP with Entra ID (preauthorized) connector in these regions.
May be the issue comes from the fact that the solution still want to access the HTTP Azure AD connector ? The mapping seems good but I don't know what's  happening  behind the scene.
See this post : https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Error-importing-CoE-Starter-Kit/m-p/2442967/highlight/false#M10532

AB#763

**Comment by Jenefer-Monroe** [comment] 2023-11-08 16:31
Yep looks like a product change in this connector. 

Do you know which of these you selected when you created the connections?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a21a0326-ae5a-49b3-ac74-c24d8c4244fc)

**Comment by tkudya** [comment] 2023-11-08 16:35
I have been seeing the same issue. 

this is the one i am using at the moment
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/14e72b1c-f598-4925-bb1b-435343fa0aa5)

**Comment by jsideserf** [comment] 2023-11-08 16:38
Also having the same issue - tried multiple accounts / environments / tenants / browsers

**Comment by Jenefer-Monroe** [comment] 2023-11-08 16:40
yep this seems to be a product bug. What region are you guys in for your coe envt? 
This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by jsideserf** [comment] 2023-11-08 16:42
Our CoE environment region is in United Kingdom

**Comment by tkudya** [comment] 2023-11-08 16:45
Europe

**Comment by APICoaching** [comment] 2023-11-08 16:45
I've used "HTTP with Microsoft Entra ID (preauthorized)" and my Region is either switzerland or Europe (problem with both)

**Comment by Jenefer-Monroe** [comment] 2023-11-08 16:46
Can you try with this same solution? It only has the http connection and a flow to use it
[justhttp_1_0_0_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/13299239/justhttp_1_0_0_1_managed.zip)

**Comment by APICoaching** [comment] 2023-11-08 16:54
> Can you try with this sample solution? It only has the http connection and a flow to use it [justhttp_1_0_0_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/13299239/justhttp_1_0_0_1_managed.zip)

Yes, done successfully.
![image](https://github.com/microsoft/coe-starter-kit/assets/150267535/2b43d352-a5db-4b2e-aa96-3beee5dd5255)

On my side, I had created a simple workflow with the HTTP with Microsoft Entra ID (preauthorized) connector, just to test if it was a problem from the connector, but it seems not because the workflow worked like a charm.

**Comment by Jenefer-Monroe** [comment] 2023-11-08 16:57
Can you please try the Core solution again? I was just able to import into a Switzerland, perhaps they backed out whatever product issue caused it.

**Comment by tkudya** [comment] 2023-11-08 17:01
I am still not able to import the solution. Do i need to get rid of the old connections?
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/e12340dc-d31f-4d17-8b88-4b72bfee5b7d)

**Comment by APICoaching** [comment] 2023-11-08 17:04
No change so far.
My tenant is in switzerland, my envrionment too.
![image](https://github.com/microsoft/coe-starter-kit/assets/150267535/220c2987-f9fa-4462-971d-fb6baa9388f1)

**Comment by APICoaching** [comment] 2023-11-08 17:27
If I want to be very specific, If the solution has already been installed, installing it again as an "update", it works. 
Otherwise, from a brand new install, it doesn't work.

**Comment by rfarris2000** [comment] 2023-11-08 17:53
For me it appears to be related to this article: https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user

However, the App specified is not in my tenant and I get the following error when executing the PowerShell script:

WARNING: No service principal was found in the current tenant with appId: d2ebd3a9-1ada-4480-8b2d-eac162716601

**Comment by manuelap-msft** [comment] 2023-11-08 19:33
Are you able to raise Microsoft Support tickets with the Session ID you get from the error screen, and let us know here any findings they share?

As the issue is happening before the solution even imports, we're not sure what the root cause is yet. It would be helpful for us if you could bring this to Microsoft Support and get more details from the Session ID. Thank you!

**Comment by APICoaching** [comment] 2023-11-09 03:06
I submitted the case to MS. let's see...

**Comment by APICoaching** [comment] 2023-11-09 03:09
> For me it appears to be related to this article: https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user
> 
> However, the App specified is not in my tenant and I get the following error when executing the PowerShell script:
> 
> WARNING: No service principal was found in the current tenant with appId: d2ebd3a9-1ada-4480-8b2d-eac162716601

I think it's not related to the current issue because the connector works like a charm in an App. Moreover with the preauthorized connector, you don't need to set the authorization, it's already predefined (preauthorized) :)

**Comment by ashes2076** [comment] 2023-11-09 08:56
I was trying to install the CoE starter kit this morning, and I got an issue with the HTTP with Microsoft Entra ID connector, i tried to follow the steps (https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user) but as @rfarris2000 I got the same error. 

So I opted to go for the preauthorized connector instead and I was able to make the connection

**Comment by APICoaching** [comment] 2023-11-09 09:14
> I was trying to install the CoE starter kit this morning, and I got an issue with the HTTP with Microsoft Entra ID connector, i tried to follow the steps (https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user) but as @rfarris2000 I got the same error.
> 
> So I opted to go for the preauthorized connector instead and I was able to make the connection

Have you been able to import the solution ? Because the issue happens when you import, after the screen showing you all the connections : you click Next and...crash...

**Comment by ashes2076** [comment] 2023-11-09 09:17
I was trying to install the CoE starter kit this morning, and I got an issue with the HTTP with Microsoft Entra ID connector, i tried to follow the steps (https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user) but as @rfarris2000 I got the same error. 

So i opted to go for the preauthorized connector instead and I was able to make the connection

> > I was trying to install the CoE starter kit this morning, and I got an issue with the HTTP with Microsoft Entra ID connector, i tried to follow the steps (https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user) but as @rfarris2000 I got the same error.
> > So I opted to go for the preauthorized connector instead and I was able to make the connection
> 
> Have you been able to import the solution ? Because the issue happens when you import, after the screen showing you all the connections : you click Next and...crash...

No also crashes for me

**Comment by APICoaching** [comment] 2023-11-09 11:20
Good News: I've been able to install it, in using the classic UI instead of the Modern UI.
Steps:
- Go to make.powerapps.com
- go to the Solution menu
- click the ... in the menu bar and select "Switch to classic"
![image](https://github.com/microsoft/coe-starter-kit/assets/150267535/6fa6e227-6c3b-4634-be03-e67585deaed8)
- Then find the import menu, follow the steps and be patient.
- At the end the solution is installed with a ton of errors, mainly related to the Wizard (which doesn't work directly)
-
![image](https://github.com/microsoft/coe-starter-kit/assets/150267535/4b187650-684d-42ae-a8e9-9352d15f9ce9)

But you have all the items in the solution, so you can manage to set i up manually.

**Comment by Jenefer-Monroe** [comment] 2023-11-09 13:12
We dont think its an issue with the kit but with the Product Import UX, but we could be wrong. I have not repro'd even once with the same test envts as people who do.
Please do keep giving us your feedback and posting support tickets. We are also pressing.

**Comment by rfarris2000** [comment] 2023-11-09 14:30
I don't see the preauthorized connector in my environment like everyone else.

**Comment by lcimon** [comment] 2023-11-09 14:35
I'm facing the same issue with version 4.13 & 4.16. A workaround is to use PAC CLI to import the solution.

**Comment by petepuu** [comment] 2023-11-09 14:57
Yes as @lcimon mentioned PAC CLI can be used to import the solution as a workaround. Just made these instructions to out team


Install PAC CLI https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-power-platform-cli-for-windows
 
Generate deployment settings file:
_pac solution create-settings -z c:\PATH-TO-COE-PACKAGE\CenterofExcellenceCoreComponents_4.16_managed.zip -s DeploymentSettings.json_
 
Create all CoE connections using service account to CoE environment
![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/85bfc804-175f-4a23-89f6-15b3ecfe2b07)


Update the exported deployment settings file with the connection IDs you can copy from URL of the connection's details page. You can see the connector type in the url as well
 
![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/14f53bed-dcab-4946-a7fe-ebfeb84e95b9)

 
Paste the connection ID to deployment settings file. **NOTE** some connectors like Dataverse have multiple connection references, so you will use the same connection ID for each same type of connectors. Maybe good idea to find correct connectors using the internal connector name from the deployment settings file
<img width="494" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/67c87161-f3ac-40de-b7e8-f4c0b34da24b">

 
Delete all the EnvironmentVariables from the deployment settings file
 
<img width="387" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/4cacca5f-6757-476c-8bc8-f4f33e92a869">

 
Connect to environment using CoE service account
_pac auth create -env ENVIRONMENT_ID_
 
Import the solution using deployment settings file
_pac solution import -p c:\PATH-TO-COE-PACKAGE\CenterofExcellenceCoreComponents_4.16_managed.zip -wt 45 -a -ap --settings-file C:\PATH-TO-DEPLOYMENT-SETTINGS\DeploymentSettings.json_

**Comment by J-C-VanBrussels** [comment] 2023-11-09 15:08
Same issue today (4.16)

**Comment by mateuszwrobel89** [comment] 2023-11-09 15:14
Same issue here. I tried to import in classic mode, but then afterwards there are issue in connection references. Errors are blocking to turn on required flows to push forward installation.

**Comment by APICoaching** [comment] 2023-11-09 15:25
Here is the answer from Microsoft following my ticket :
"Findings:
After having more in-depth investigations and having checked the telemetry with the provided Session ID, I found the following:
This issue has been reported several times throughout the previous 24 hours by several customers. It seems to be a bug with the CoE Kit.
As a mitigation, you can try the manual export/import process from the classic UI, and this should help in avoiding the issue which occurs on the Modern UI (make.powerapps.com).
Following the documentation: [Feedback and support for Center of Excellence (CoE) Starter Kit - Power Platform | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform/guidance/coe/feedback-support), issues with the CoE Kit is GitHub supported. Microsoft Support will be able to help surely in case there is something wrong with the core features.
Make sure to raise the issue here: [New Issue · microsoft/coe-starter-kit (github.com)](https://github.com/microsoft/coe-starter-kit/issues/new?assignees=Jenefer-Monroe&labels=coe-starter-kit%2Cbug&template=1-coe-starter-kit-bug.yml&title=%5BCoE+Starter+Kit+-+BUG%5D+ISSUE+TITLE), since the GitHub support will be able to add your environment details as a sample with the product group, to have a fix implemented as soon as possible. If you’ve raised it already, please make sure to let the GitHub support engineer working on the ticket to have the details of your environment shared with the product group if needed.
In the existing reported issue, I’ll be able to share this existing ticket number to our product group, to raise awareness that the issue is happening on your environment too. Hence, would you be able to share the source and target environment URLs, please?
Kareem Mohamed
Email: [v-kareemm@microsoft.com](mailto:v-kareemm@microsoft.com)
Support Engineer – (D365 Customer Engagement)
Team Manager: [v-ahmedei@microsoft.com](mailto:v-ahmedei@microsoft.com)
Direct Dial in: Toll Free number +448003584020, Extension: 41,957,876
Working Hours: Mon. – Fri. 10:00 – 19:00 (UTC +2)
"

**Comment by APICoaching** [comment] 2023-11-09 15:26
As you can read, Jenefer, MS think it's a bug from the CoE... :)

**Comment by SN-bjss** [comment] 2023-11-09 15:36
+1 on this, exact same message across 3 brand new environments. Went through MS support yesterday but they were unable to resolve.

**Comment by manuelap-msft** [comment] 2023-11-09 16:46
The 4.16 solution has been out for a month, and we have about 1k installs of it from what we can see from our telemetry. We've not changed the solution this week. So whilst it's true that the import issue happens with the CoE kit solution, something on the product side must have changed for it to fail all of a sudden this week when it succeeded last week. 

We're investigating on our side as well.

**Comment by Jenefer-Monroe** [comment] 2023-11-09 16:49
> I don't see the preauthorized connector in my environment like everyone else.

Mine went away. I see the old connector now.

**Comment by APICoaching** [comment] 2023-11-09 17:00
> The 4.16 solution has been out for a month, and we have about 1k installs of it from what we can see from our telemetry. We've not changed the solution this week. So whilst it's true that the import issue happens with the CoE kit solution, something on the product side must have changed for it to fail all of a sudden this week when it succeeded last week.
> 
> We're investigating on our side as well.

That's exactly what I told to MS. They agreed. But maybe because of the change in the Modern UI (I don't know which one), there is something the solution which not supported...

**Comment by albertocastro365** [comment] 2023-11-09 17:56
Hi team!

I have this issue updating to november 2023 release (4.17)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/e6c43daf-10f9-491d-ac94-21695142e345)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/4eff56b1-b1b5-495b-b151-946d1dd8d330)

**Comment by petepuu** [comment] 2023-11-09 17:57
@mateuszwrobel89 So you did configure connections to all connection references in default solution and then completed the configuration using CoE Setup and Upgrade Wizard? I just did import and setup in classic portal and didn't run any issues configuring inventory flows

**Comment by Jenefer-Monroe** [comment] 2023-11-09 20:59
Can someone who wants to help debug here test this for me? I've still never seen a repro myself so I cannot test it myself.

1. Create a new environment for testing install and create all your connection references
2. Try to install this which is the May 2023 version of Core as usual
I assume this will fail as above, let me know one way or another
[CenterofExcellenceCoreComponents_4.8_managed.zip](https://github.com/microsoft/coe-starter-kit/files/13312757/CenterofExcellenceCoreComponents_4.8_managed.zip)

3. If so try to install this which is the April 2023 version of Core
I assume that will succeed
[CenterofExcellenceCoreComponents_4_4_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/13312753/CenterofExcellenceCoreComponents_4_4_2_managed.zip)

**Comment by petepuu** [comment] 2023-11-09 21:17
@Jenefer-Monroe 4.4.2 worked but 4.8 not. Feeling that the changes in the HTTP with AAD connector are causing these issues

**Comment by Jenefer-Monroe** [comment] 2023-11-09 21:30
I think its due to the number of env vars. In some geos the UX is behaving oddly when there are over 50 in a solution.

In april 2023 we had 46 env vars in core
In may 2023 we had 51 env vars in core

Can you try this one for me? Its outside the scope of CoE. 

1. Create a new environment for testing install and create all your connection references

2. Try to install this which has 51 env vars
I assume this will fail as above, let me know one way or another
[toomanyenvvarsforManuela_1_0_0_2_managed 51 env vars.zip](https://github.com/microsoft/coe-starter-kit/files/13312989/toomanyenvvarsforManuela_1_0_0_2_managed.51.env.vars.zip)

3. If so try to install this which is the April 2023 version of Core
I assume that will succeed
[toomanyenvvarsforManuela_1_0_0_1_managed 50 env vars.zip](https://github.com/microsoft/coe-starter-kit/files/13312986/toomanyenvvarsforManuela_1_0_0_1_managed.50.env.vars.zip)

**Comment by APICoaching** [comment] 2023-11-10 04:47
@Jennifer-Monroe, I've successfully installed the 1.0.0.2 solution along with 51 environment variables; therefore, the diagnostic does not point to the solution as the issue.
I attempted another installation with the Core but had no success.
To recall: I successfully installed the Core on Friday, the 3rd, but have been failing to do so since Tuesday, the 7th, within the same GEO environment. The primary difference I've noticed is the HTTP Azure AD connector which has since been updated to an HTTP Entra ID connector.
Could the issue be related to this connector change?
I'm unclear on the technical processes occurring in the UI between the selection of the connections and the display of the environment variables, as the issue arises precisely during this transition phase.
I hope this information is useful.

**Comment by petepuu** [comment] 2023-11-10 05:33
@Jenefer-Monroe I can confirm also that  **toomanyenvvarsforManuela_1_0_0_2_managed 51 env vars.zip** import worked. Colleague said yesterday that November version was working for them in Canada region, so decided to test in Canada env but I was not that lucky

**Comment by mateuszwrobel89** [comment] 2023-11-10 06:57
> @mateuszwrobel89 So you did configure connections to all connection references in default solution and then completed the configuration using CoE Setup and Upgrade Wizard? I just did import and setup in classic portal and didn't run any issues configuring inventory flows

I tried first with modern UI to import solution and at this point i estabilished all connectors, but in next step it was failing due to "Sorry, there's been a disconnect". Afterwards i switched to classic UI and imported it again - this one finished OK, all connectors were already in place authenticated, but when i wanted to start installation wizard app it was not possible to run prerequisities or in next steps other flows. After more checks i found out that some flows were not turned on and when i wanted to do it - it says error that reference connections are missing:

![image](https://github.com/microsoft/coe-starter-kit/assets/150365131/6bbb71a5-a73e-4c30-957b-6d9590cdfc02)

![image](https://github.com/microsoft/coe-starter-kit/assets/150365131/c668520c-868a-4e57-a194-a5aa35b5d212)

**Comment by petepuu** [comment] 2023-11-10 07:08
@mateuszwrobel89 When using classic import it does not set any connection references, so you need to update connections for connection references in Default Solution. After that run CoE Setup and Upgrade Wizard

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/048dfcc1-3ad8-4055-b1c8-9934ab4e8c14)

**Comment by mateuszwrobel89** [comment] 2023-11-10 08:16
> @mateuszwrobel89 When using classic import it does not set any connection references, so you need to update connections for connection references in Default Solution. After that run CoE Setup and Upgrade Wizard
> 
> ![image](https://user-images.githubusercontent.com/8307644/281984447-048dfcc1-3ad8-4055-b1c8-9934ab4e8c14.png)

Thanks. It worked like a charm.

**Comment by sunilmhatugade** [comment] 2023-11-10 10:23
@manuelap-msft ... please let us know you sorted this  issue

**Comment by Jenefer-Monroe** [comment] 2023-11-10 11:39
We have not sorted it yet, but do believe its about the number of items or size of a solution being too much for some of your browsers.
 
We've noticed, for example, that she cannot install a particular solution as testuser@testtenant.onmicrosoft.com but I can install as that user. 

And we've gotten a solution which works for her to not work by just adding enough fake env vars. At which point it no longer worked for her. 

We've posted to the product team and will continue to press for an investigation. 
Pete has a great work around posted above until then.

**Comment by ashes2076** [comment] 2023-11-10 12:24
I imported the solution via the classic designer and as @petepuu suggested updated my connection references in the default solution. And so far, the setup wizard seems to work fine, but I am still in the process of setting up.

**Comment by APICoaching** [comment] 2023-11-10 12:53
> I don't see the option to switch to Classic under solutions: ![image](https://user-images.githubusercontent.com/60694700/282063195-11e4d755-ed3c-4325-a0d2-7b67740baa11.png)

Hi @reneskumlesoerensen, you need to go in one existing solution to see the ... after "Publish all customizations"

**Comment by Jenefer-Monroe** [comment] 2023-11-10 13:08
Can I just say that I love this community. Thank you for helping each other while we chase this bug with the product team!
So grateful for you all!!!

**Comment by petepuu** [comment] 2023-11-10 13:17
If you want to use PAC CLI installation option then here is a script which makes it a bit easier as you do not need to manually modify the deployment settings file. https://github.com/petepuu/PowerShell/blob/main/PowerPlatform/Install-CoECoreUsingPAC.ps1

Script requires CoE environment url and full path to CoE Core solution zip. It will create the deployment settings file to the same folder. Browser parameter is used to define what browser you want to open to create connections, Script will check are all the CoE connections created and if not opens browser tab for each missing connection. Does **not** work now inprivate/incognito mode, so create all required connections with CoE service account before running the script

<img width="483" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/ec156599-6fd7-4312-bb58-6205ea5e93a0">

Let me know if there are issues if you want to test this option 🙂 It is a bit faster way to deploy the solution

**Comment by JanetK12** [comment] 2023-11-10 13:47
> * make.powerapps.com

**Comment by JanetK12** [comment] 2023-11-10 13:49
Hi @APICoaching ! I also cannot find the option to switch to Classic mode. Tried as you said to go in one existing solution to see the "..." but cannot find them.

<img width="679" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/7ac3a5d1-8c40-4008-8549-4a4f80b99527">

**Comment by petepuu** [comment] 2023-11-10 13:54
@JanetK12 UI has changed recently, so another option is to use Advanced Settings

<img width="176" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/59fc6238-4624-42c8-9409-27f48582562a">

**Comment by APICoaching** [comment] 2023-11-10 13:58
> Hi @APICoaching ! I also cannot find the option to switch to the Classic mode. Tried as you said to go in one existing solution to see the "..." but cannot find them.
> 
> <img alt="image" width="679" src="https://user-images.githubusercontent.com/113427788/282076387-7ac3a5d1-8c40-4008-8549-4a4f80b99527.png">

Weird...but you are already in the Core Component solution so you don't need oinstall it again :)

Anyway, there is another way as the one from Pete:
use this URL, replacing what is in square brakets [ ] with the appropriate values
https://[YourEnvironmentURL]/tools/solution/edit.aspx?id=[The ID of the Default Solution]

**Comment by JanetK12** [comment] 2023-11-10 14:00
Thank you @petepuu and @APICoaching !

**Comment by KareemMohamed02** [comment] 2023-11-10 15:17
You can also allow the option again from Power Platform Admin Center:

Environment -> Settings -> Behavior - >Turn the toggle "Show the Switch to classic buttons in Power Apps" on.

**Comment by russrimm** [comment] 2023-11-10 15:23
> Can someone who wants to help debug here test this for me? I've still never seen a repro myself so I cannot test it myself.
> 
> 1. Create a new environment for testing install and create all your connection references
> 2. Try to install this which is the May 2023 version of Core as usual
>    I assume this will fail as above, let me know one way or another
>    [CenterofExcellenceCoreComponents_4.8_managed.zip](https://github.com/microsoft/coe-starter-kit/files/13312757/CenterofExcellenceCoreComponents_4.8_managed.zip)
> 3. If so try to install this which is the April 2023 version of Core
>    I assume that will succeed
>    [CenterofExcellenceCoreComponents_4_4_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/13312753/CenterofExcellenceCoreComponents_4_4_2_managed.zip)

@Jenefer-Monroe One of my customers is stuck on this issue and willing to let you remote in and help and see it first-hand and help resolve it if you'd like?

**Comment by KareemMohamed02** [comment] 2023-11-10 15:44
Hello Everyone,

Would you be able to try adding the below string parameter to the end of the URL from the Modern UI, and try the import process again? Please let me know if the issue still persists or not.

?powerappsConnections.enableShowAllEnvVariablesOnImport=false

**Comment by petepuu** [comment] 2023-11-10 15:50
@KareemMohamed02 based on one test that did the trick!!! Got into the environment variables step!

**Comment by KareemMohamed02** [comment] 2023-11-10 16:22
Hello @petepuu,

I'm the Microsoft Support Engineer working with @APICoaching on the issue 😄

I have been working with the product group all day and we managed to formulate this query string parameter.

The issue is basically with a new feature which was done to show all environment variables on solution import in the solution import panel as well as pipelines.

As a mitigation for now we have two options:

1. Add the below query string parameter to the end of the URL from the Modern UI and try the import process again.

?powerappsConnections.enableShowAllEnvVariablesOnImport=false

2. Import from the classic UI (as I advised @APICoaching yesterday).

Product group will be working on the fix, and they will let me know once they have a confirmed date.

I'll keep you all posted here next week! 😉

Thanks

**Comment by manuelap-msft** [comment] 2023-11-10 16:45
@KareemMohamed02 You're amazing, thank you so much! I can also confirm that I've tested this across two environments now that have previously failed for me, and with the query string the import now works successfully! This is fantastic news - thank you so so much for your work in triaging this issue and supporting our customers!!

**Comment by MartinWGT** [comment] 2023-11-10 16:59
Great news.

Please can you clarify which of these connectors we need to set up? I'm hoping 'preauthorized' will work so that we won't need to get admin involved.

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/9d5ee249-74d8-4e14-8b60-0c6cb148b053)

**Comment by Jenefer-Monroe** [comment] 2023-11-10 17:01
yes its the pre-authorized. its still showing with the old name for some users and the new name for others.
That change isnt related to this issue though it turns out.

**Comment by petepuu** [comment] 2023-11-10 17:01
@KareemMohamed02 ok that explains 😀 I was thinking that this must have come from MS support. Thanks a lot for the help and info about the problem 👍

**Comment by APICoaching** [comment] 2023-11-10 18:02
Thank you, @KareemMohamed02 , for your tenacity and perseverance, for ultimately finding THE solution 👍👍❤️

**Comment by johnravas** [comment] 2023-11-10 19:26
Just tried adding the query string parameter to the end of the URL and got the same error while trying to upgrade the core components to v4.13.  I'll monitor this thread for a solution @KareemMohamed02

**Comment by KareemMohamed02** [comment] 2023-11-10 19:32
Hello @johnravas,

Can you try again and make sure that you're using the correct format? Also, make sure that you run it on Power Apps main page from the modern UI on the target environment.

?powerappsConnections.enableShowAllEnvVariablesOnImport=false

**Comment by MartinWGT** [comment] 2023-11-10 19:48
The same happened for me but, as @KareemMohamed02 mentioned, I was using the Power Automate main page. That explains it. So instead I used the Classic UI and then manually connected the connection references. Running through the wizard now.

**Comment by johnravas** [comment] 2023-11-13 14:21
@KareemMohamed02 - Thanks for responding back.  I ran the process today with the same result.  To be clear, here is my process:
Log into the Power Apps home screen
Clicked on Solutions in the left navigation
The URL looked like this: https://make.powerapps.com/environments/<environmentID removed>/solutions?utm_source=office&utm_medium=app_launcher&utm_campaign=office_referrals
I appended the ?powerappsConnections.enableShowAllEnvVariablesOnImport=false to the URL - the screen refreshed
I initiated the import, selected the import file for version 4.13 of the core components solution and clicked Next
It processed the import file, then came up with the import details panel.  Under Advanced it had upgrade selected.  Clicked Next
This is where the error came up.

Please clarify if there is something I am doing wrong in this process.

**Comment by manuelap-msft** [comment] 2023-11-13 14:23
@johnravas the URL should just be https://make.powerapps.com/environments/solutions?powerappsConnections.enableShowAllEnvVariablesOnImport=false you can remove all the other url parameters that you have there, they are not needed.

**Comment by johnravas** [comment] 2023-11-13 14:44
@manuelap-msft I tried that same thing Friday with no luck, but this morning it is working fine.  Import is working.  Thank you for the support.

**Comment by miroslav-harlas** [comment] 2023-11-13 15:24
I have run into the same issue earlier today when trying to install Core version 4.15 into a new recently created environment in our non-production tenant, environment region = united states.

I used approach to 
1. open this url in browser directly: https://make.powerapps.com/environments/<-environemnt_id->/solutions?powerappsConnections.enableShowAllEnvVariablesOnImport=false
2. then clicked on "import solution" and proceeded trough UI import wizard

Works like a charm. Thank you for posting this workaround here.

**Comment by KareemMohamed02** [comment] 2023-11-13 15:34
I’m glad that it’s working for everyone for now at least, once I have an update from the product group, I’ll let you all know 😄

**Comment by cyclingdaze** [comment] 2023-11-13 16:40
Hi, I still see the following, as my original test environment is now a mess.

Created a new environment and set up.

I added this to the end of the URL: powerappsConnections.enableShowAllEnvVariablesOnImport=false

Imported v4.15 (same as we have on Prod).

Upgraded to 4.17.

I see both of these in the environment:

![image](https://github.com/microsoft/coe-starter-kit/assets/103632200/611168f0-5e40-4d0c-b07a-ef022b4d0cb7)

**Comment by iamjina** [comment] 2023-11-13 21:27
Hi team, 
 
Opening up this issue again. Were we able to find exact solution to this bug? "Sorry, there's been a disconnect" has happened again. Please advise.

**Comment by Jenefer-Monroe** [comment] 2023-11-13 21:30
Here is the workaround: Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240

You need to use the Power Apps ux (not Power Automate) and just append the query parameter as described.

**Comment by josefhagen** [comment] 2023-11-14 08:58
I had this exakt issue yesterday. Today it worked splendidly without appending the string. My region is (West) Europe. Cheers!

**Comment by KareemMohamed02** [comment] 2023-11-14 09:25
Hello @josefhagen,

Thank you so much for sharing this. Basically fixes gets deployed in the weekly updates which takes place either in the weekend (Friday evening to Sunday evening) or Monday after the working hours. 

Maybe the product group has implemented a fix yesterday evening already. I’ll check with them and get back to you.

**Comment by KareemMohamed02** [comment] 2023-11-14 09:33
I’ve reached them out and waiting for their response now, until then, would you be able to check the solution history and let me know if there are any updates that took place since yesterday evening for Microsoft solutions?

if you can provide a screenshot too, this would me much appreciated 😊 @josefhagen

**Comment by APICoaching** [comment] 2023-11-14 09:42
@KareemMohamed02 here is my printscreen og the solution history. I don't see anything directly related to our issue (tenant in Switzerland) since the CoE Core import with the help of your url-
![image](https://github.com/microsoft/coe-starter-kit/assets/150267535/9e8a3d71-9c10-4e47-9dd3-5587a9db98f9)

**Comment by KareemMohamed02** [comment] 2023-11-14 10:06
Hello @APICoaching,

I can see two solutions installed/updated yesterday evening, their name is related to Power Platform (Power Apps included), so maybe the fix was deployed there.

I will be waiting for a confirmation from the product group 😄

**Comment by josefhagen** [comment] 2023-11-14 10:50
<img width="681" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/50071213/5700f158-52d8-49c3-a111-80fd67e531f8">

This is my solution history. Maybe the selected one is a patch related to the issue?

**Comment by KareemMohamed02** [comment] 2023-11-14 18:11
Hello everyone,

I've just received an update from the product group, they've confirmed that they deployed a hotfix, and the issue should be fixed now automatically. They disabled the feature completely for all users (show all environment variables on solution import) without the need of the query string parameter. They will enable the feature again as per their plan with more in-depth tests before deployment.

Hence, I can say that no one should be facing this issue now!

It has been a pleasure dealing with you all.

Thanks 😊

**Comment by manuelap-msft** [comment] 2023-11-14 18:36
@KareemMohamed02 Thank you Kareem! If you want to ping me at mapichle@microsoft.com please do, I'd love to send a note to your manager about the phenomenal support you've provided us with! :)

**Comment by kartrabby** [comment] 2023-11-15 10:22
@manuelap-msft  @Jenefer-Monroe 

Hello Team, after the issue we had as per https://github.com/microsoft/coe-starter-kit/issues/7050 ........

I managed to successfully import the Solution, but now I am facing this issue whenever I open any app that is installed as part of the solution!

Nothing works when I click on **sign-in** !

Can you please provide the resolution for this?
(We can't open any app in the COE Core Components!)

![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/a0d3489d-dba4-4179-8ce3-5c8f78af4c2f)

**Closed** 2023-11-15 22:55 UTC
Labels: bug, coe-starter-kit, officehourTHANKS
