### ISSUE TITLE
CustomAzureDevOps.RunPipeline failed: The method 'RunPipeline' has an invalid value for parameter 'project'

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#4628] opened 2023-01-19 06:45 UTC
### Describe the issue

Receiving the below error when I am using a different project other than what is used while executing the CLI command(coe alm install -f install.json) for setting up ALM accelerator solution. Do I need to run the CLI command for each project? or is there an alternate way where I can use any of the projects in ADO.

CustomAzureDevOps.RunPipeline failed: The method 'RunPipeline' has an invalid value for parameter 'project'

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20221121.1_managed

### Steps To Reproduce

1. I am using Project A while executing the CLI command coe alm install -f install.json
2. Created profile using Project A details and  able to commit the solution successfully to Project A repository using ALM accelerator app
3.  Created profile using Project B but this time it failed with the below error while committing the solution to Project B repository
Error : CustomAzureDevOps.RunPipeline failed: The method 'RunPipeline' has an invalid value for parameter 'project'

**Comment by mikefactorial** [comment] 2023-01-23 13:53
@challa85 the expectation is that the export pipeline exists in the same project that you are planning to source control the solution. You can use the Project Setup wizard to initialize a new project with the appropriate pipelines. You don't, however, need to install the pipeline templates into each project. You can select an existing project for the pipeline templates so you don't have to upgrade each project with the new templates when they are released. Here's a screenshot of the Project Wizard where you can point the project at another project that hosts the pipeline templates.

![image](https://user-images.githubusercontent.com/42348035/214056890-8e10f803-c16e-41fc-9030-5f58a1b15330.png)

**Comment by mikefactorial** [comment] 2023-01-23 13:55
The docs for the setup wizard is here https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview

**Comment by challa85** [comment] 2023-01-23 16:41
Hi Mike,

Thanks for the update. We have a so many solutios for different apps, for that reason we have created project for each solution.

I am receiving the same error "**CustomAzureDevOps.RunPipeline failed: The method 'RunPipeline' has an invalid value for parameter 'project'** "although I have installed ALM pipeline template for those projects.


Thanks

**Comment by challa85** [comment] 2023-01-30 16:19
Hi Team/Mike,

It would be really helpful if you can let me know of any updates on this.

Thanks

**Comment by mikefactorial** [comment] 2023-02-28 15:43
@challa85 it's difficult to tell what the issue is based on the thread. It appears something is configured incorrectly, but I can't tell what specifically without more details. Feel free to setup some time for us to walk through the current setup v-ochsmike(at)microsoftdotcom

**Comment by mikefactorial** [comment] 2023-03-15 12:44
@challa85 based on our call and your call with @RajeevPentyala. This has been resolved. Closing for now.

**Closed by mikefactorial** 2023-03-15 12:44 UTC
Labels: bug, alm-accelerator

**Comment by BrentEllingwood** [comment] 2023-04-28 16:52
@mikefactorial  I am currently having the exact same error message. Do you have any information about what you and challa85 did to fix the issue?

**Comment by mikefactorial** [comment] 2023-04-28 17:06
@BrentEllingwood mind opening a new issue since this is closed with the details?
