### ISSUE TITLE
[ALM Accelerator - Feature]: multi tenant

### ISSUE THREAD

**Issue by SabrinaDiBartolomeo** [microsoft/coe-starter-kit#3161] opened 2022-07-11 12:26 UTC
### Is your feature request related to a problem? Please describe.

We have a customer that doesn't use DevOps, so they asked to use our (Partner) DevOps.
When we tried to set up the ALM accelerator by using the CoE CLI we realized that it works only if everything is under the same tenant.
I'm afraid that for now the only option we have is to set up it manually by using the step-by-step walk-through guide (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform)

### Describe the solution you'd like

Since the use of the CoE CLI the recommended way is, do you think this multi tenant scenario will be supported?

**Comment by mikefactorial** [comment] 2022-07-12 00:50
@SabrinaDiBartolomeo the multi-tenant scenario is not currently supported in the Accelerator. The connectors used in the app assume that the user of the app has access to resources in both Azure DevOps and Dataverse / Powerapps based on the credentials used to authenticate with the app. The custom connector we use for Azure DevOps doesn't support connecting with a user outside of the tenant.

**Comment by mikefactorial** [comment] 2022-07-12 00:52
Reopening and moving to backlog to potentially address in a future release if possible.

**Comment by mikefactorial** [comment] 2022-12-07 16:41
Closing this out as a duplicate of #3946

**Closed by mikefactorial** 2022-12-07 16:41 UTC
Labels: enhancement, alm-accelerator, coe-cli
