### ISSUE TITLE
[CoE Starter Kit - BUG] CommandCenterApp>GetM365ServiceMessages.Run failed "error": 502 - The Server did not receive a response from an upstream server

### ISSUE THREAD

**Issue by segovof** [microsoft/coe-starter-kit#4318] opened 2022-11-30 20:37 UTC
### Describe the issue

Admin Command Center is sending an error Message when it load, it was working fine until Nov-28. Then it start Failing, I check the flow and there is an error on the Parse Response after the List serviceAnnouncements from Graph, the error is "ValidationFailed: The schema validation failed" 

![image](https://user-images.githubusercontent.com/36718713/204900898-93bfd6ae-d697-4eb0-856c-8740a3a89de6.png)

### Expected Behavior

Admin Command Center Get Microsoft Messages with no Error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Get M365 Service Messages

### Steps To Reproduce

Open the Admin Command Center App

**Comment by Jenefer-Monroe** [comment] 2022-11-30 23:33
Thank you for posting! There was a change in the returned schema and we started failing as a result. I have this posted and local fixed via https://github.com/microsoft/coe-starter-kit/issues/4312 
Duplicate of #4312 

We do appreciate you investigating and posting though!

**Comment by manuelap-msft** [comment] 2022-12-22 11:02
This was fixed in December.

**Closed by manuelap-msft** 2022-12-22 11:02 UTC
Labels: bug, coe-starter-kit
