### ISSUE TITLE
[CoE Starter Kit - Feature]: Ease e-mail customization in the "CoE - Governance Components" solution

### ISSUE THREAD

**Issue by JMG74** [microsoft/coe-starter-kit#2804] opened 2022-05-21 10:17 UTC
### Is your feature request related to a problem? Please describe.

Hi team, 
In the "CoE - Governance components" solution, the body of the e-mails sent from the flows are hardcoded.
Customization of those flows is possible but not realistic because even if they are adapted in a custom solution, for each new release of the CoE, we need to inspect the new versions of the flows and possibly reapply our customizations.

### Describe the solution you'd like

Would it be possible to manage the e-mails generated from the Governance flows in the same way as in the "CoE - Core components" solution by storing the e-mails body in the table "Customized Email" ?? as this will greatly facilitate their customization from the “CoE - Admin command center” app while avoiding the risks associated with the customization of flows:
![image](https://user-images.githubusercontent.com/13162921/169646978-6ed7d876-101e-4d39-9340-e9cbcacd7527.png)

Why not implementing the same feature in **all CoE solutions** to have a consistent way of customizing e-mails contents according to our needs ?

Thanks in advance and all the best

**Comment by Jenefer-Monroe** [comment] 2022-05-23 12:58
Hello, yes this is on our backlog via https://github.com/microsoft/coe-starter-kit/issues/1683

Duplicate of #1683 

Thanks for using CoE

**Closed** 2022-05-25 13:14 UTC
Labels: enhancement, coe-starter-kit
