### ISSUE TITLE
[CoE Starter Kit - BUG] App usage section

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#1765] opened 2022-01-17 11:33 UTC
### Describe the issue

I can see there is missing app trends

Here is screen shot:

![image](https://user-images.githubusercontent.com/30046543/149760316-847c1b70-2ad5-466f-b706-a874cfc87ad8.png)

Portal screen shot:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/30046543/149762704-706043b9-c8d1-4279-b51d-520d0affa811.png)

Please help to gather the missing app trends 

**Flow Count difference:** 

We have experienced that for same user flow count appears differently  in different section
 
Cloud Flow maker Insight:

![image](https://user-images.githubusercontent.com/30046543/149761427-73d3649a-e91c-4365-aac0-cd883311edcb.png)

Cloud Flow Connections :

![image](https://user-images.githubusercontent.com/30046543/149761577-87696f51-9c31-4648-a346-0a6e55686a97.png)
 

### Expected Behavior

Count should be same 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Power BI Report

**Comment by sharmajitendralal** [comment] 2022-01-19 03:45
Thanks for quick response..

1. It means now we can not retrieve the missing audit log?
2. I have checked the filter and its seems that filter is ok 

Cloud Flow Connection:

![image](https://user-images.githubusercontent.com/30046543/150060002-ac23d5ce-dc42-49db-bce2-ebf68003f0a1.png)

Cloud Flow Maker Insight:

![image](https://user-images.githubusercontent.com/30046543/150060280-5db20775-6754-4ec8-88b6-ab1b58a702cd.png)

**Comment by Jenefer-Monroe** [comment] 2022-01-19 05:54
Please go trigger the clean up flows, ensure they passed, and then see if the numbers correlate after they complete. Because of the way inventory is collected you can sometimes expect to see small differences like these as flows run at different schedules. 

![image](https://user-images.githubusercontent.com/89584709/150072264-9d0be787-3eee-4296-b85f-85e6de7534b3.png)

**Comment by sharmajitendralal** [comment] 2022-01-24 04:35
2 Flow failed and rest are successfully completed

Here is details: 

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) - **Failed after running 05:49:37 hours**
CLEANUP - Admin | Sync Template v3 (Check Deleted) - **Failed after running 19:23:08 hours** 

Can you suggest how we get the success result ?

**Comment by Jenefer-Monroe** [comment] 2022-01-24 12:46
Please understand that you will need to monitor these flows and know how to debug them in order to have a successful CoE. You may need to seek partner assistance in training for this.

I can guess at the cause here though given the above, to be that you have not enabled the child flows of these flows. Please walk the [setup inventory components](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) documentation to ensure you have done all the steps.

**Comment by Jenefer-Monroe** [comment] 2022-01-31 14:41
Closing out as no further action for starter kit team. 
It is our recommendation that you spend time getting to know and understand the sync flows before continuing to test the PBI, as you need to ensure you have everything running and passing, or your data will not be correct. 
Thanks for using CoE

**Closed by Jenefer-Monroe** 2022-01-31 14:41 UTC
Labels: coe-starter-kit
