### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashboard Embed Apps

### ISSUE THREAD

**Issue by garyfrostncc** [microsoft/coe-starter-kit#4054] opened 2022-10-27 09:49 UTC
### Describe the issue

After following the optional instructions [https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi](url)
Published report and all seems to work fine, but when trying to drill down to an app details or cloud flow details get the following errors (see in attached files)

### Expected Behavior

Admin - Access this app and Admin - access this flow apps working within the Power BI Dashboard

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

CoE dashboard & Admin - Access this app & Admin - access this flow

### Steps To Reproduce

Follow instructions  [https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi](url)
Run BI Report in [[app.powerbi.com](https://app.powerbi.com/)](url)
Select and flow or app
Drill through to App Detail or Cloud Flow Details
App appears with errors

### Anything else?

![dashboard cloud flow drill through](https://user-images.githubusercontent.com/60133999/198252463-1b9519dc-1b06-42f9-908c-837749097f18.JPG)
![dashboard apps drill through](https://user-images.githubusercontent.com/60133999/198252467-3741460a-62d2-4b20-af28-6a0792dfe4ba.JPG)

**Comment by Jenefer-Monroe** [comment] 2022-10-27 13:57
Hello, thanks for posting, this was found via https://github.com/microsoft/coe-starter-kit/issues/3875 and is local fixed for next week's November release. 
I'll close as a dupe of that one.

**Closed by Jenefer-Monroe** 2022-10-27 13:57 UTC
Labels: bug, coe-starter-kit
