### ISSUE TITLE
WorkflowCompleteNotification - Setp up Configuration

### ISSUE THREAD

**Issue by alzia-msft** [microsoft/coe-starter-kit#1644] opened 2021-12-17 17:56 UTC
Per the documentation I am supposed to open the "WorkflowCompleteNotification" flow and copy the URL of the first action i.e. HTTP request action and paste it to the the Webhook Url of the admin app. 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/92477952/146587371-2adbe0f7-486a-448c-bcd6-db8b44db671c.png">

The URL in the Flow is blank, what value needs to be in the Webhook Url of the ALM Accelerator Admin Configuration??

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/92477952/146587609-9bbd8e09-94e9-4201-8e5d-66e4df53d361.png">

**Comment by mikefactorial** [comment] 2021-12-17 23:27
@alzia-msft is this a duplicate of #1645? See #1512 for the workaround.

**Closed by mikefactorial** 2021-12-17 23:27 UTC
