### ISSUE TITLE
[CoE Starter Kit - BUG] View Button in Admin- Environment Request not working (Teams)

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#1498] opened 2021-11-17 14:57 UTC
### Describe the issue

Hello, 

I imported the CoE Starterkit for Teams, added an environemnet request and wanted to view this from the Admin- Environment Request app, but I could´t use the View-button. Nothing happens when clicking it.
In developer mode there are several errors regarding two formulas (see below)
<img width="978" alt="Formula 1" src="https://user-images.githubusercontent.com/62603605/142224150-1f6d3044-6d6a-4877-af6c-2f56db2d09c7.png">
<img width="845" alt="formula 2 screen" src="https://user-images.githubusercontent.com/62603605/142224159-0af01909-81e0-40f0-a006-ee2fc4687848.png">
<img width="743" alt="Formula 2" src="https://user-images.githubusercontent.com/62603605/142224161-10e2f4f6-f8f2-445e-8350-a217ab00e78c.png">

Can someone help with this? This would be greate!

Thanks a lot and all the best
Cathi

### Expected Behavior

Navigation to details page

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Teams_3_6_managed

### What app or flow are you having the issue with?

Admin - Environment Request

**Comment by Jenefer-Monroe** [comment] 2021-11-17 14:59
Denise - we should perhaps re-think using Users table, and just use Maker, especially since you create a Maker later anyway.

**Comment by denisem-msft** [comment] 2021-12-07 21:49
@Cathi029 thanks for reaching out!

Can you please:
1. Share the error message details. Either by sharing the monitor network trace and sharing that file, or by taking a screen capture tool like snip using the 3-second delay feature and hovering over the text.
2. Confirm that at least one security roles assigned to your account has access to the Users table.

I am not able to reproduce this in our master branch which has the same code you shared on the button, so that is why I want to check other permissions levels and the actual error message would be helpful.

**Comment by denisem-msft** [comment] 2021-12-14 16:28
I have removed that line of code that uses the 'Created By'.'Azure AD Object Id' column, so it doesn't reference the Users table Although in this context the User who created the Environment Creation Request item needs to be provisioned in the Users table in order for them to have created the record, we can take it out regardless as it was an unnecessary line of code anyways.

I also took out those references to the Users table in the screenshot you provided, so you should not get any more errors in those screens. Please let me know if you find any more.

**Comment by mikefactorial** [comment] 2022-01-06 21:19
@Cathi029 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Closed by mikefactorial** 2022-01-06 21:19 UTC
Labels: coe-starter-kit, vnext
