### ISSUE TITLE
[CoE Starter Kit - BUG] CoEBYODLPreview - PBI do not show Default environment data

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#5052] opened 2023-03-21 16:47 UTC
### Describe the issue

In Power BI report, i am not able to see the app and flow data for the default environments.
![image](https://user-images.githubusercontent.com/110540273/226681791-9ca7d4f7-35a8-433f-a401-333f2a59e214.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

Power BI Report

**Comment by Jenefer-Monroe** [comment] 2023-03-21 17:08
Hello. Did you set up with the Sync Flow or the BYODL architecture?

**Comment by manuelap-msft** [comment] 2023-03-21 17:10
Thank you for raising this issue and trying out the BYODL feature!

Looks like have an issue when we perform the join (merge) of the Environments table with the App/Flow table. 
- In the Environments table, the Environment ID of the default environment is Default-{GUID}
- In the Apps/Flows table, the Environment ID of the default environment is formatted as just the {GUID} - we filter out the prefix incorrectly here

That's why the merge/join fails for the Default environment and thus your Default- apps and flows aren't showing up.

I'm just working on updating the queries for you to try to fix this!

**Comment by manuelap-msft** [comment] 2023-03-21 17:24
Can you:
1. Navigate to app.powerbi.com
2. Edit the PowerPlatformAdminAnalytics-DF dataflow > Edit tables
3. Select the **Apps** table under Queries
4. Open Advanced Editor
5. Replace what's there at the moment with:

`let
    Source = AzureStorage.DataLake(DatalakeURL & "/powerapps/Applications"),
    excludehiddenfiles = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    excludezerolengthfiles = Table.SelectRows(excludehiddenfiles, each [Attributes]?[Size]? > 0),
    excludestalefiles = Table.SelectRows(excludezerolengthfiles, each not Text.EndsWith([Name], "canvas.json") or not Text.EndsWith([Name], "model.json")),
  #"Replaced value" = Table.ReplaceValue(excludestalefiles, "canvas.json", "", Replacer.ReplaceText, {"Name"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", "model.json", "", Replacer.ReplaceText, {"Name"}),
  #"Renamed columns" = Table.RenameColumns(#"Replaced value 1", {{"Name", "EnvironmentNameFromTable"}}),
  #"Lowercased text" = Table.TransformColumns(#"Renamed columns", {{"EnvironmentNameFromTable", each Text.Lower(_), type nullable text}}),
    #"Removed columns" = Table.RemoveColumns(#"Lowercased text", {"Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path"}),
    // Only keep apps where the environment still exists
    #"Merged with environments" = Table.NestedJoin(#"Removed columns", {"EnvironmentNameFromTable"}, Environments, {"environmentId"}, "Environments", JoinKind.Inner),
    #"Get content from json file" = Table.AddColumn(#"Merged with environments", "Invoked custom function", each #"Transform file"([Content])),
    #"Expand file" = Table.ExpandListColumn(#"Get content from json file", "Invoked custom function"),
    #"Expanded file to columns" = Table.ExpandRecordColumn(#"Expand file", "Invoked custom function", {"resourceId", "environmentId", "subType", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups"}, {"appId", "environmentId", "subType", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups"}),
    #"Replace errors" = Table.ReplaceErrorValues(#"Expanded file to columns", {{"appId", null}, {"environmentId", null}, {"subType", null}, {"name", null}, {"description", null}, {"uri", null}, {"tenantId", null}, {"lifecycleState", null}, {"owner", null}, {"createdTime", null}, {"createdPrincipalId", null}, {"lastModifiedTime", null}, {"lastModifiedPrincipalId", null}, {"lastEnabledTime", null}, {"lastEnabledPrincipalId", null}, {"sharedUsers", null}, {"sharedGroups", null}}),
    #"Add Power Apps Type" = Table.TransformColumnTypes(Table.AddColumn(#"Replace errors", "PowerApps Type", each if [subType] = "AppModule" then "Model Driven" else if [subType] = "CustomCanvasPage" then "Custom Page" else if [subType] = "ClassicCanvasApp" then "Canvas" else if [subType] = "CanvasApp" then "Component Library" else null), {{"PowerApps Type", type text}}),
    #"Removed unneeded columns" = Table.RemoveColumns(#"Add Power Apps Type", {"Content", "EnvironmentNameFromTable", "Environments", "subType"}),
    #"Changed column type" = Table.TransformColumnTypes(#"Removed unneeded columns", {{"appId", type text}, {"environmentId", type text}, {"name", type text}, {"description", type text}, {"uri", type text}, {"tenantId", type text}, {"lifecycleState", type text}, {"owner", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type datetime}, {"lastModifiedPrincipalId", type text}, {"lastEnabledTime", type datetime}, {"lastEnabledPrincipalId", type text}, {"sharedUsers", Int64.Type}, {"sharedGroups", Int64.Type}, {"PowerApps Type", type text}}),
    #"Removed duplicates" = Table.Distinct(#"Changed column type", {"appId"})
in
    #"Removed duplicates"`

**Comment by manuelap-msft** [comment] 2023-03-21 17:25
For Flows, I don't repo this in my tenant. It looks like we only had this issue for Apps. Can you confirm you're not seeing Flows either?

**Comment by AkashPatel136** [comment] 2023-03-21 17:30
@manuelap-msft  I do not see the Default environment option to select in cloud flow
![image](https://user-images.githubusercontent.com/110540273/226693216-c1221d1a-a3c1-4626-9db2-822787883531.png)

**Comment by manuelap-msft** [comment] 2023-03-21 17:34
@AkashPatel136 You're right, I repo this too now. Will investigate and get back to you!

**Comment by AkashPatel136** [comment] 2023-03-21 17:35
Thank You @manuelap-msft , will update you about the app data

**Comment by manuelap-msft** [comment] 2023-03-21 17:39
Ok, looks like the issue was that in the Flows table, the Environment ID was Default- and in the Environments table the ID was default- (lowercase) so the merge there failed as well. 

Can you open the **Advanced Editor** of the **Flows** query and replace what's there with:
let
    Source = AzureStorage.DataLake(DatalakeURL & "/powerautomate/Flows"),
    excludehiddenfiles = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    excludezerolengthfiles = Table.SelectRows(excludehiddenfiles, each [Attributes]?[Size]? > 0),
    #"Extract Environment ID from file name" = Table.AddColumn(excludezerolengthfiles, "EnvironmentName", each Text.BeforeDelimiter([Name], "."), type text),
  #"Lowercased text" = Table.TransformColumns(#"Extract Environment ID from file name", {{"EnvironmentName", each Text.Lower(_), type text}}),
    #"Removed unneeded columns" = Table.RemoveColumns(#"Lowercased text", {"Folder Path", "Attributes", "Date created", "Date modified", "Date accessed", "Extension", "Name"}),
    // Only keep flows where the environment still exists in the tenant
    #"Merged with environments" = Table.NestedJoin(#"Removed unneeded columns", {"EnvironmentName"}, Environments, {"environmentId"}, "Environments", JoinKind.Inner),
    #"Get content from json file" = Table.AddColumn(#"Merged with environments", "Transform file", each #"Transform file (6)"([Content])),
    // If transformation fails, assume file is corrupt
    #"Removed errors" = Table.RemoveRowsWithErrors(#"Get content from json file", {"Transform file"}),
    #"Expanded file to columns" = Table.ExpandTableColumn(#"Removed errors", "Transform file", {"resourceId", "name", "tenantId", "environmentId", "lifecycleState", "events_created_timestamp", "events_created_principalId", "events_modified_timestamp", "customExtensions"}, {"flowId", "name", "tenantId", "environmentId", "lifecycleState", "createdOn", "createdBy", "lastModifiedOn", "customExtensions"}),
    #"Expanded customExtensions" = Table.ExpandRecordColumn(#"Expanded file to columns", "customExtensions", {"events_created_usertype", "sharingType", "flowTriggerUri", "triggerKind", "flowSuspensionTime", "flowSuspensionReason"}, {"events_created_usertype", "sharingType", "flowTriggerUri", "triggerKind", "flowSuspensionTime", "flowSuspensionReason"}),
    #"Removed columns" = Table.RemoveColumns(#"Expanded customExtensions", {"Content", "EnvironmentName", "Environments"}),
    #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {{"flowId", type text}, {"name", type text}, {"tenantId", type text}, {"environmentId", type text}, {"lifecycleState", type text}, {"createdOn", type datetime}, {"createdBy", type text}, {"lastModifiedOn", type datetime}, {"events_created_usertype", type any}, {"sharingType", type any}, {"flowTriggerUri", type any}, {"triggerKind", type any}, {"flowSuspensionTime", type any}, {"flowSuspensionReason", type any}}),
    #"Transform columns" = Table.TransformColumnTypes(#"Changed column type", {{"events_created_usertype", type text}, {"sharingType", type text}, {"flowTriggerUri", type text}, {"triggerKind", type text}, {"flowSuspensionTime", type text}, {"flowSuspensionReason", type text}}),
    #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"events_created_usertype", null}, {"sharingType", null}, {"flowTriggerUri", null}, {"triggerKind", null}, {"flowSuspensionTime", null}, {"flowSuspensionReason", null}})
in
    #"Replace errors"

**Comment by manuelap-msft** [comment] 2023-03-21 17:39
I've tested both updated queries in the Dataflow only so far - they seem to there return default- data now. My dataflow refresh is still running so not confirmed if this then works in Power BI dashboard too but hopefully it should.

**Comment by AkashPatel136** [comment] 2023-03-21 17:56
@manuelap-msft I am able to see data for apps and flows in Power BI.

**Comment by manuelap-msft** [comment] 2023-03-21 17:57
YAY! That's wonderful, thanks for helping us triage this. I'll re-open the issue just so we can track to make this update in the public version for the April release, but glad you're unblocked now.

**Comment by albertocastro365** [comment] 2023-03-23 17:26
@manuelap-msft  tested by my side the new version of the dataflow and Default env is showed in apps and cloud flows 💪

**Comment by manuelap-msft** [comment] 2023-03-23 17:28
@albertocastro365 Wohoo, thanks for confirming - so glad it works now!

The reason we missed this is because our Default environment in our development tenant is very sparse so we didn't notice large mismatch in numbers :(
![image](https://user-images.githubusercontent.com/55705669/227288058-4e09a397-f45e-45ca-ae4c-0ef7be47fa96.png)

Sorry about the inconvenience, but super glad you all helped us get to the root of the issue so fast and were helpful in helping us test the fix!

**Closed** 2023-04-05 12:55 UTC
Labels: bug, coe-starter-kit, coe-byodl
