### ISSUE TITLE
[CoE Starter Kit - BUG] CoE not inventoring flows

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8836] opened 2024-08-20 14:44 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Team, 

CoE is not inventorying flows properly. At the moment we have validated that we are having issues with the inventory of two environments but haven't validated the rest. 

Current State: 
An environment has 3 disabled flows. 

Coe does not show the disabled flows nor any trace of them. 

![image](https://github.com/user-attachments/assets/bec0ac0e-ce7b-4277-ba4b-dd1b1265b904)
![image](https://github.com/user-attachments/assets/2f1e2077-554d-47ac-a60b-32241a6a6ebd)
![image](https://github.com/user-attachments/assets/68e42f15-691f-46ea-af10-9ac82e68dad8)
![image](https://github.com/user-attachments/assets/60d2392f-b2ee-43a6-affa-f5ec89b0b791)

We have also validated that CoE account is a sys admin and Power Platform admin. 

### Expected Behavior

CoE Inventory should be accurate

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment] 2024-08-20 14:59
Flows that are unpublished are not gathered by the kit. 
Please see our limitations: [Flows that don't get activated](https://learn.microsoft.com/power-platform/guidance/coe/limitations#flows-that-dont-get-activated)

It sounds like that is what you are seeing. Can you please clarify? Are you seeing something else?

**Comment by nasilvae** [comment] 2024-08-20 17:00
> Flows that are unpublished are not gathered by the kit. Please see our limitations: [Flows that don't get activated](https://learn.microsoft.com/power-platform/guidance/coe/limitations#flows-that-dont-get-activated)
> 
> It sounds like that is what you are seeing. Can you please clarify? Are you seeing something else?

Hi Jenefer these flows were published but they are currently disabled. Would that use case fall into this limitation?

**Comment by Jenefer-Monroe** [comment] 2024-08-20 17:28
Please find the most recent run of **_Admin | Sync Template v4 (Flows)_** for that environment in question and open it
![image](https://github.com/user-attachments/assets/c6c15e55-1470-4a70-be14-5095f6944100)

Are the desired flows returned from List Flows as Admin (V2)?
Are they returned form Filter out unpublished flows?

![image](https://github.com/user-attachments/assets/223d0107-7552-4fdb-bc59-aa03ac06b54e)

**Comment by stanmh** [comment] 2024-08-26 14:20
Are the desired flows returned from List Flows as Admin (V2)?
    1. No, they are not returned from the "List Flows as Admin (V2)" activity.
    2. For the environment with 9 flows these are the only ones returned:
        "displayName": "Search Dynamics 365 knowledge article flow",
        "displayName": "SLAInstanceMonitoringWarningAndExpiryFlow",
        "displayName": "SLAInstanceMonitoringWarningAndExpiryFlow",

Are they returned form Filter out unpublished flows?
    1. N/A since they were not returned from first activity

**Comment by Jenefer-Monroe** [comment] 2024-08-26 14:54
Please go validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by nasilvae** [comment] 2024-08-27 14:16
> Please go validate the user running the flow has direct and permanent assignment to the Power Platform Admin role. ![image](https://private-user-images.githubusercontent.com/89584709/280251600-66096cf4-67ad-41c9-9900-0b3e46de0cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Njc1MDMsIm5iZiI6MTcyNDc2NzIwMywicGF0aCI6Ii84OTU4NDcwOS8yODAyNTE2MDAtNjYwOTZjZjQtNjdhZC00MWM5LTk5MDAtMGIzZTQ2ZGUwY2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE0MDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzY2RmNDM0ZThjYzYzOTkzNWExMjAyNjgxMWE3MjllM2IwOTYxOWUxODRhM2M0OTk4MDIzYmU1MjUyYmU2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RTBFZ65FQp4IYzu47ycTGCAktWFl5STKw7hRod0MJc)

Yes, this has been assigned permanently. We also ran the workaround for sys admin.

**Comment by Jenefer-Monroe** [comment] 2024-08-27 14:29
Unfortunately I dont think I casn assist then. 
This is a product connector and if calling **_List Flows_** does not return the flows then that is a product bug, unless permissions are incorrect which we just confirmed. 
You will need to contact product support.

**Comment by Jenefer-Monroe** [comment] 2024-09-02 22:27
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-09-02 22:27 UTC
Labels: bug, coe-starter-kit
