### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cross- tenant connections tab on Governance and compliance dashboard

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#6216] opened 2023-08-02 17:18 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

My understanding about cross-tenant connections tab is that it flags the admin about how many cross tenant connections are getting used and after analysing they can block it in power platform admin centre by creating some cross tenant policies.

Have questions:  what does this cross-tenant connections tab does. Why it is flagging for an admin?
Looked into our standard CoE documentation https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-compliance, but couldn't find answers to my questions.

For my customer, it is reflecting almost 3000 Cross-tenant connections. When we drill through, we observed that all the accounts are actual users of that tenant and no one is from outside , however, after doing a bit more investigation we got the column admin_connctionReference column in the report. We observed for some accounts it was displaying a different tenant, however , for some accounts its the same organization tenant. 

Confusion here is , if the user is an internal user why it is shown under cross-tenant tab and also why it is showing up with different address on admin_connectionReference column
In below screen shot both the users are internal but they are showing up under cross- tenant tab
<img width="991" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/202fa4cd-9e27-4962-811f-6b1de31855aa">

To add to this, they have Enabled Cross tenant on their tenant with no tenants white listed , so understanding is that then it should restrict all these connections.

From Microsoft learn : 
<img width="574" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/071dbc8f-0d08-4bbe-ba66-52e78b86cbee">

Please help and guide here. Its confusing.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

July

### What app or flow are you having the issue with?

Governance solution

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment] 2023-08-04 16:21
We determine if the identity is cross tenant or not based on the admin email used. 
Please go to the most recent run of **_Admin | Sync Template v3 (Connection Identities)_** for the default environment.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0be635a1-d2e9-49c3-89a3-531ea19e1b93)

And see what is derived here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9e356810-7b7c-4448-9cf2-2c7b01685bee)

**Comment by PPMini** [comment] 2023-08-09 10:55
We checked this and we understood this Tenant String have our company primary domain name. However, we observed that in cross tenant drill through we have connections appearing with this domain as well and we understood that no connections with primary domain should get displayed. 

Secondly, many organizations have multiple domains. Can we do something to whitelist those domains as well via CoE?

**Comment by Jenefer-Monroe** [comment] 2023-08-09 15:32
We do have someone working on making what's a cross tenant connection configurable, please see this issue: https://github.com/microsoft/coe-starter-kit/issues/3506

Hopefully we casn ship that in a month or two. 
Hope that helps!

**Comment by Jenefer-Monroe** [comment] 2023-08-10 02:21
Wonderful, I'll go ahead and close this as a duplicate of #3506 then, you can track that for a fix.

**Closed by Jenefer-Monroe** 2023-08-10 02:21 UTC
Labels: question, coe-starter-kit
