### ISSUE TITLE
[CoE Starter Kit - BUG] Power Apps MAU column does not roll up

### ISSUE THREAD

**Issue by shriyamal** [microsoft/coe-starter-kit#2879] opened 2022-05-31 17:37 UTC
### Describe the issue

The Power Apps MAU over time suddenly dropped to 1 when there should be 8k MAU.

After the update was completed, I made the same changes as were on the CoE Kit before, with regards to StartTime-Interval, StartTime-Unit, TimeInterval-Unit, TimeInterval-Interval and TimeSegment-CountLimit. I turned off the Flows before the change, and then turned them on again after the change. I can see a noticeable change on the duration of Admin | Sync Audit Logs and (Child) Admin | Sync Logs. 

The Admin | Sync Logs has gone from a duration of several hours and sometimes days to just seconds, after the update the longest run has been on 11 seconds.
The (Child) Admin | Sync logs has gone from multiple runs a day, to just 1 run. 

### Expected Behavior

The Power Apps MAU should reflect the telemetry of 8k MAU

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment] 2022-05-31 17:53
There was a product change around the beginning of May that made the user UPN not show up. We had to reship May's audit log solution as 2.9 to fix. 

Please see https://github.com/microsoft/coe-starter-kit/issues/2665
![image](https://user-images.githubusercontent.com/89584709/171252757-b1f02152-1181-4ae4-9103-18d829c04071.png)

This is likely what you are facing, please let us know.

**Comment by shriyamal** [comment] 2022-06-01 13:34
@Jenefer-Monroe  I already have the 2.9 version of the Audit Logs components and I still have the NoUPN as well. Do you have any other suggestions to fix these problems.

**Comment by Jenefer-Monroe** [comment] 2022-06-01 14:24
You probably have unmanaged layers on the flow preventing you from seeing the updates to the flow. 
Please be sure to check for unmanaged layers on upgrade as described in [Installing upgrades](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

**Comment by Jenefer-Monroe** [comment] 2022-06-01 14:41
Manuela, is this another bug in the PBI?

**Comment by shriyamal** [comment] 2022-06-02 09:47
@Jenefer-Monroe 
![image](https://user-images.githubusercontent.com/91137553/171603540-17736cc7-0e8f-4bcf-b383-9a3d56e726c5.png)

And for the unmanaged layer, there is an unmanaged layer on the Audit Log flow. I will delete this and let you know if this has fixed it

**Comment by Jenefer-Monroe** [comment] 2022-06-07 13:52
This is a column that as far as I can tell has never worked. Moving to be a feature for us to investigate.

**Comment by shriyamal** [comment] 2022-06-10 13:35
@Jenefer-Monroe Do you mind summarizing what we have decided to do here as it's been sometime as I was away? Are you saying that the answer to my initial question/bug whereby the MAU dropped to 1k is that the rollup is not working and hence its been addressed as a feature?

**Comment by manuelap-msft** [comment] 2022-10-19 17:09
Duplicate of #2878. Closing as duplicate. This is still on our backlog for investigation.

**Closed by manuelap-msft** 2022-10-19 17:09 UTC
Labels: bug, coe-starter-kit
