### ISSUE TITLE
[CoE Starter Kit - BUG] SharePoint Form Apps listed as Canvas

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#5995] opened 2023-07-04 12:13 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Sharepoint form apps appears to be Canvas apps even after we upgrade to June CoE kit.

### Expected Behavior

Sharepoint forms listed as sharepoint forms

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

PowerBI Dashboard

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/016b20fa-f81f-4c34-8ba5-3354dfabdacd)

AB#2206

**Comment by manuelap-msft** [comment] 2023-07-04 12:58
This is a limitation of the Data Export product feature, which returns SharePoint Form Apps as Canvas App. If you look directly at the Data Export file for your environment that hosts SharePoint form apps, you'll see the type is listed as Canvas. 

There's unfortunately nothing we can do in the CoE kit as that's just how it's returned by the product.

**Comment by lcimon** [comment] 2023-08-08 13:44
Hi,

I have the same issue. 

I've observed that when an app is marked for update again (using the 'InventoryMe' field in the Power Platform Admin View), the App Type is corrected for the SharePoint Form App.

During my investigation, it appears that the flow 'SYNC HELPER - Apps' possesses the correct logic to set the AppType appropriately. I'm still looking into why the initial AppType is incorrect.

Have you already addressed this issue?

Note: I'm using version 4.13 of CoreSolution.

**Comment by Jenefer-Monroe** [comment] 2023-08-08 13:56
Hello. The issue is specific to Data Export, the information for this does exist in the connectors, just not in the Datalake. So when you specifically say "Inventory Me" that goes through the sync flow connectors. We do not do this for all apps as it defeats the purpose of the faster iteration / less API calls of the Data Export feature.

**Comment by lcimon** [comment] 2023-08-08 14:41
Thank you for the clarification. It's an excellent point to consider reducing the number of API calls.

From my understanding, within the 'CoE BYODL - When App dataflow refresh is complete' flow, missing fields for new apps are collected using the 'Get App as Admin' action, such as the 'SharePoint Form URL'.

Given this, it seems feasible to update the AppType without making additional queries. This would ensure accurate data while aligning with the goals of faster iteration and fewer API calls as part of the Data Export feature.

Is there something I might be overlooking that would render this unfeasible?

![image](https://github.com/microsoft/coe-starter-kit/assets/22662809/0d9917eb-e134-4958-8f2c-06980c5b98ac)

**Comment by Jenefer-Monroe** [comment] 2023-08-08 14:54
We can consider that, we are also pressing for the product fix to Data Export to track that correctly so will first continue that avenue and reconsider a fix up on our side if needed.

**Comment by lcimon** [comment] 2023-08-08 15:00
That make sense. Thanks for your answers!

**Comment by Jenefer-Monroe** [comment] 2024-12-17 15:21
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today

**Closed by Jenefer-Monroe** 2024-12-17 15:21 UTC
Labels: question, coe-starter-kit, product-gap
