### ISSUE TITLE
Power BI Center of Excellence Dashboard - Connector Usage Validation Issue

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#640] opened 2021-06-16 13:39 UTC
**Describe the bug**
We are experiencing issues where we are unable to see certain connector analytical usage in the Power BI Center of Excellence dashboard (www.app.powerbi.com). 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [2.1.70]

**To Reproduce**
1. Go to Power BI (app.powerbi.com) and select Center of Excellence dashboard
2. Click on Connections tab
3. Scroll down to specified environment, and view the different connectors
4. Unable to see analytical data on connectors based on what users mentioned/demo

**Expected behavior**
We expect to see the data under the Power BI AFS CoE dashboard

**Screenshots**
Here is an example of Power BI AFS CoE Dashboard > Connections > Connections Trend > Focus Mode > Unable to see certain connectors in data, for example Microsoft Forms & Azure AD

![image](https://user-images.githubusercontent.com/83036044/122228651-0cc35700-ce86-11eb-8719-c3ec224c287c.png)

**Additional context**
Most users are building things out through Power Apps, that's the main hub they're working out of. That being said, is the Connections tab of the Power BI dashboard where we should see this data? If so, any idea why we are unable to see certain connector data?

**Comment by manuelap-msft** [comment] 2021-06-16 19:35
Hello,
we will need a bit more detail to help you. 
1. Do you have a scheduled refresh set up for the Power BI Data or did you refresh it manually? 
2. I would recommend running a FullInventory by setting the FullInventory environment variable to Yes, and waiting until the next day and until all the Sync Flows have finished running, and then refreshishing the dashboard. 
3. Are you a Power Platform Service Admin? 
4. Is it specific environments this information is missing for? 
5. Are you able to find the app itself, and are just the connections that are missing?

**Comment by yearwoodm15** [comment] 2021-06-16 19:58
Hi Manuela, I can definitely help provide more information.

1. Yes I have a scheduled refresh, last one was last Thursday but I also performed a manual refresh.
2. I performed a FullInventory last week in a suggestion in issue #536 which unfortunately did not resolve my issue. I am happy to run another if a fresher run is required.
3. Yes, I am a Power Platform Service Admin.
4. We have only heard from it in regards to one environment, which happens to be the (Default) production environment that our users go to. 
5. I can't see anything the users have mentioned, one of the users mentioned a flow. I looked it up through Power BI dashboard under Flows and there is no information on it, and there is no information about the connector that user utilized. 
5a. The other user has an app, but I have not heard back from them yet to gather additional information.

**Comment by manuelap-msft** [comment] 2021-06-16 21:29
Hello,

it looks like the Sync Flows that are syncing the Default environment are maybe failing - have you set up the Sync Flow Errors to run and are you receiving notifications about flow failures? 

Thank you
Manuela

**Comment by yearwoodm15** [comment] 2021-06-17 13:58
Hi Manuela, 

Looks like the Sync Flow Error was turned off. Should I turn it on and run another step to see if I can produce error notifications?

**Comment by JeneferM-MSFT** [comment] 2021-06-17 15:47
Pease do turn that flow on (and all other flows in Core). 
But you wont need to wait to see about failure for another run. 

Can you please
1) Tell us if you use PIM for the identity running the flows? 
1) Browse to the details page for the Apps and Flows flow. Are they turned on? And when did they last run?
1) Click All runs and then filter to failed runs (see below). Did they fail in the last run?
1) Can you please create a new app with the connectors you are concerned about not showing? Then wait for a run of the sync flows, refresh the PBI, and see they are present. 

To Do #3 
![image](https://user-images.githubusercontent.com/62659043/122430385-ca1a8100-cf50-11eb-872b-5416cf31d6ca.png)
![image](https://user-images.githubusercontent.com/62659043/122430492-e4545f00-cf50-11eb-9aec-195d7c666d52.png)

**Comment by yearwoodm15** [comment] 2021-06-17 19:48
Hi Jenefer! Please see below for answers:

1. No, I do not use PIM for IDing the running of flows.
2. Yes, they are turned on. For Sync Template v3 (Apps) the last time it was run was today at 11:07am (EST). For Sync Template v3 (Flows) the last time was today at 11:07am (EST).
3. For Sync Template v3 (Apps) there were no failed runs today. For Sync Template v3 (Flows) there was a failed run at 11:05am (EST) today.
4. I will try this one later today and report back.

**Comment by JeneferM-MSFT** [comment] 2021-06-17 19:55
Can you please also go see if these are showing up in the **Power Platform Admin View**? Its a model driven app in Core. 
Go to the Connectors report and click on Azure AD or Microsoft Forms to see if the apps and flows are showing there
![image](https://user-images.githubusercontent.com/62659043/122464022-91d86a00-cf73-11eb-93d5-c34405d9c67e.png)
![image](https://user-images.githubusercontent.com/62659043/122464110-b03e6580-cf73-11eb-86ce-9e85edb7268e.png)

**Comment by yearwoodm15** [comment] 2021-06-17 20:31
For the CoE Environment I built out, this info is not showing up. The environment in question does not have the Power Platform Admin View associated to it. But now I have a question (and apologies I'm still learning as I go) - should I have applied the CoE Core Components to the environment in question having this issue? Is that the reason why it is not showing up?

**Comment by JeneferM-MSFT** [comment] 2021-06-17 21:07
The CoE Core Components only need to be installed in your CoE environment. 
And then the user that installs the Core components in your CoE environment needs to have the Power Platform Admin role. 

Let's take a step back. Can you please confirm all of the below?
 
1. You setup the Core Components, you have PPAdmin role, and you do not use PIM in your organization.
2. The Power Platform Admin View (pictures above) do not show any apps or flows for the Azure AD connector. Can you plesae share a picture so I know we are talking about the same spot? 
3. You know for sure that canvas apps connected to Azure AD exist in your Default environment. Can you please share a screenshot of the app so we can understand that? 
4. You validated that the (apps) sync flow is on and passed for all environments today

Next you will
1. Create your own app connected to Azure AD in default envt
2. Wait for sync flows to run
3. Look in the **Power Platform Admin View** model driven app to see if it shows up

**Comment by yearwoodm15** [comment] 2021-06-21 13:43
Hey Jenefer, sure please see below:

1. That's correct.
2. I may have been looking in the wrong part before, but I do see some data there for the flow. My mistake!
3. I'm not see any apps associated to the connector, just flows.
4. That's correct, for that day all worked.

I will work on the other parts today and will provide more information when it's ready.

**Comment by yearwoodm15** [comment] 2021-06-23 19:09
Hi Jenefer,

Just wanted to give an update that I created an app today with Azure AD. The Sync Flow will not occur until tomorrow morning (EST) so I will verify once it has run and report back.

**Comment by yearwoodm15** [comment] 2021-06-24 18:14
Hi Jenefer,

I was able to successfully create an app associated to the Azure AD connector and see the Azure AD App behind the Power Apps Power Platform Admin View.

**Comment by JeneferM-MSFT** [comment] 2021-06-24 18:53
ok good, so things are "working" :)

I wonder if the problem is that the full inventory runs werent actually full inventory. We've had some issues with the env variables lately. Can you see if this might be the problem? 

Can you please 
1) Open default solution, filter to environment variables, and find the full inventory environment variable
![image](https://user-images.githubusercontent.com/62659043/123307385-aa9acf80-d4df-11eb-9e67-489105b5e25d.png)
1) Edit the env variable to see what value is there. I presume you set that to Yes when you did the full inventory runs mentioned above. 
![image](https://user-images.githubusercontent.com/62659043/123307575-e2a21280-d4df-11eb-8e00-54a38e12acb0.png)
1) If that was set correctly, you may have had solution layers on the env variable. 
Back on the list of env vars, chose to view the Solution layers for the env var
![image](https://user-images.githubusercontent.com/62659043/123307691-082f1c00-d4e0-11eb-8a7a-50212ff10d17.png)
1) If you see an unmanaged layer you will need to remove it. Its a product bug that it was added. Please let us know.
![image](https://user-images.githubusercontent.com/62659043/123308203-9f946f00-d4e0-11eb-99ac-f3645f06583d.png)

**Comment by yearwoodm15** [comment] 2021-06-24 19:08
Hi Jenefer,

Thank you for this. Looks like my value went back to No, should I switch it over to Yes? As for number 4 of your last post, I do have an active unmanaged layer. Should I switch value to Yes first and then remove unmanaged layer?

**Comment by JeneferM-MSFT** [comment] 2021-06-24 19:20
Its a product bug so I'm not exactly sure how to get into a good state, but I think what you should do is
1) Add a current value of **Yes** (not default)
1) Remove the unmanaged layer
1) Go check to see if the current value is still there. I think it will be.

**Comment by yearwoodm15** [comment] 2021-06-24 19:35
I ran the above steps and can confirm that the Current Value is still showing as Yes.

**Comment by JeneferM-MSFT** [comment] 2021-06-24 20:14
ok great. Please do a full inventory now then and see if it fixes the issue for you.

**Comment by JeneferM-MSFT** [comment] 2021-06-25 15:02
We just found that there is a product bug which requires you re-activate a flow before it will pick up an env variable change. 
So you may need to also turn off and then turn back on the flow in order for it to pick up the new value.

**Comment by yearwoodm15** [comment] 2021-06-25 16:24
Hi Jenefer, can you send me the steps to do that, which flow? I ran the full inventory and did a data refresh but now I have significantly less environments and data in my CoE dashboard. For example, I previously have 120 environments and now it's only showing 30. Could what you mentioned in the last post be related as well with what's happening with the missing environments, etc?

**Comment by JeneferM-MSFT** [comment] 2021-06-27 23:08
Turn off and back on the all flows in core. You can do this on their details page
![image](https://user-images.githubusercontent.com/62659043/123562165-1f813a00-d76a-11eb-8c26-3cfd8fe24e80.png)

Please go to admin.powerapps.com and see how many environments you have there.

**Comment by yearwoodm15** [comment] 2021-06-28 20:09
Hi Jenefer, I turned off my flows in the core and turned them back on. I also refreshed my data in CoE dashboard but it still shows 31 environments. When I checked Power Platform admin it shows +100 environments. Should I give it some time?

**Comment by yearwoodm15** [comment] 2021-06-28 21:20
Hey Jenefer,

Sounds good, I can do that. Didn't mean to go off track there. But, back to this inquiry yes I was able to verify that my test app is showing up through the Power BI CoE dashboard now through the Connections tab. I however still cannot see the flow that my user mentioned via Power BI CoE even though we were able to verify its existence behind Power Apps Admin View > Connections > for Azure AD. Should I try to attempt another full inventory?

**Comment by JeneferM-MSFT** [comment] 2021-06-29 13:56
At this point I think you should wait for the July release (next week) where we've tried to sort out some messiness with env vars. 
But if you have time and want to try another thing, creating a new environment and setting up the CoE there would be useful to ensure the problem really is with us not updating the apps/flows. 
Basically for new installs, you will always get full inventory.

**Comment by yearwoodm15** [comment] 2021-06-30 21:07
Hey Jenefer! No worries, I can wait until the release next week and then try to check everything out then. I appreciate your continued help!

**Comment by yearwoodm15** [comment] 2021-07-07 14:00
Hi Jenefer/Manuela, just wanted to check to see if the new release has been implemented. I took a look at #720 but couldn't tell if anything had been completed.

**Comment by manuelap-msft** [comment] 2021-07-08 08:57
This is fixed with the latest released version from yesterday! You should be able to just download the CoEStarterKit.zip file from here https://github.com/microsoft/coe-starter-kit/releases and use the Power BI Dashboard in there, no need to upgrade the solution itself.

**Closed by manuelap-msft** 2021-07-08 08:57 UTC
Labels: coe-starter-kit
