### ISSUE TITLE
Maker Environment Request App - Policy doesnt load

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3188] opened 2022-07-13 22:48 UTC
### Describe the issue

Issue 1: The policies doesnt load even though it has been present in the backend

Issue 2: The 'i' information icon listed against the Policy field behaves wierdly
When you click on 'i' it shows a modal window for searching DLP policies, however the section below shows 'Search connector' and lists connector. Is this the normal behavior

POLICY PRESENT IN BACKEND

![image](https://user-images.githubusercontent.com/17232756/178849421-5a54998b-032e-4045-9045-15d3a6d8b59d.png)

DOESN'T POPULATE POLICEIS
![image](https://user-images.githubusercontent.com/17232756/178849625-39ffdf00-74a0-44f7-9512-a92f8b5747c1.png)

WIERD BEHAVIOR ON SEARCHING POLCIES
![image](https://user-images.githubusercontent.com/17232756/178849662-f4533247-d487-49f7-a307-9833833ca411.png)

### Expected Behavior

Must populate Data policies, if it exists in backend

Also, the 'i' information on click pust provide a screen to search for policies (and not connectors)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Maker - Environment Request

### Steps To Reproduce

Navigate to 'Maker - Environment Request' app

On the left menu Click on 'Data Policy Change Requests'

Click on 'New' (for creating New DLP Policy Pending Change Request)

**Comment by manuelap-msft** [comment] 2022-07-14 08:24
1. That is expected behaviour. You have to make the policies visible first via the Admin - Environment Request app, steps are explained here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#sync-shared-policies The reason for this is that you may have policies that you don't want makers to be able to request. 
2. Once you have made policies visible, the modal pop up should behave as expected and allow you to see what connectors are allowed in which policy.

**Comment by Jenefer-Monroe** [comment] 2022-07-23 21:09
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-07-23 21:09 UTC
Labels: question, coe-starter-kit
