### ISSUE TITLE
[CoE Starter Kit - BUG] Verifying "Asignee" in the Audit Flows for "ProductionEnvironment" variable as "No"

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#825] opened 2021-07-12 08:43 UTC
### Describe the issue

In the latest version of CoE Starter Kit 2.1.7 Core and Audit Components 1.61, the Audit Flows contain following condition to check if environment is production or not:

![image](https://user-images.githubusercontent.com/13658386/125256802-cc12fe00-e2ca-11eb-9d41-c26be2c3f8ef.png)

However, the "isProd" Environment Variable value will be "False" and not "no", therefore it will always return false value even if we set "IsProd" as "No" as follows in the environment variable:

![image](https://user-images.githubusercontent.com/13658386/125257920-dda8d580-e2cb-11eb-8567-14bede5e48cd.png)

Should not it be as follows as high lighted? so that in Dev/Tes environment, Var asignee value be as Admin value instead of app/flow owner?

![image](https://user-images.githubusercontent.com/13658386/125260640-8821f800-e2ce-11eb-8db0-7396efadf873.png)

Can you please help me clarifying, how do we satisfy the condition if environment is not production?

### Expected Behavior

Get Asignee condition should satisfy as "True" as "IsProd" = "No" in case if "ProductionEnvironment" value == No

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows)

### Steps To Reproduce

1. Run the flow under environment where "Production Environment" variable value == "No"
2. Verify if "Get Asignee" conditions are satisfying

**Comment by JeneferM-MSFT** [comment] 2021-07-12 12:53
Hello this is fixed in the latest version of core and gov via #682 
Duplicate of #682

**Closed by JeneferM-MSFT** 2021-07-12 12:53 UTC
Labels: coe-starter-kit
