### ISSUE TITLE
[CoE Starter Kit - BUG] Users UPN not showing in PowerBI Production after setting up CoE Starter Kit

### ISSUE THREAD

**Issue by alosadai** [microsoft/coe-starter-kit#2811] opened 2022-05-23 13:48 UTC
### Describe the issue

After installing CoE and setting it all up, when opening the Production PowerBI and checking for app details the information that appears it seems not to be complete.
In a Power App detail information of launches, most of users appear as NoUPN, but all of them have an UPN configured in the Azure Active Directory.

The table that brings this detail is the AuditLog table.

### Expected Behavior

When seeing the App Detail in the PowerBI, it should appear the user UPN in the App Launches graph.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Production PowerBI

### Anything else?

![image](https://user-images.githubusercontent.com/59823492/169833032-68723801-6ad6-4123-9ff6-ca5cad4182a3.png)

**Comment by Jenefer-Monroe** [comment] 2022-05-23 16:47
Hello there was a change in the data source for our audit logs and so we had to shift the field we used. You will need to upgrade to the last version of the kit to get this working again.

**Comment by Jenefer-Monroe** [comment] 2022-05-23 16:52
Duplicate of #2665

**Closed by Jenefer-Monroe** 2022-05-23 16:52 UTC
Labels: bug, coe-starter-kit
