### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there any possibility to exclude specific environments to be audited?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#988] opened 2021-08-10 08:26 UTC
### Describe the issue

I wonder whether the Audit process can be excluded from the specific environment. I believe this could be possible via Environment Variable configuration, however, I'm curious if there is such a possibility already exist/is planned?

Thanks and Regards,
Dipti

### Expected Behavior

List of environments should be excluded from the Audit Process

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Archive and Clean Up (Start Approval for Apps/Flows)

**Comment by manuelap-msft** [comment] 2021-08-10 12:25
There is not, however this is a - currently unfunded - item in our backlog, see #714. 

You can upvote backlog items by liking and commenting on them, which helps us decide what to work on next.

Thank you,
Manuela

(closing out as duplicate of existing backlog item)

**Closed by manuelap-msft** 2021-08-10 12:25 UTC
Labels: coe-starter-kit
