### ISSUE TITLE
CoE Audit Logs require smaller chunks

### ISSUE THREAD

**Issue by DzCoE** [microsoft/coe-starter-kit#1754] opened 2022-01-14 14:11 UTC
### Describe the issue

We are getting constantly the error message that the Center of Excellence Starter Kit requires smaller chunks and that the current chunking size is set to 1 Hour. However, we have already changed the chunking size to 1 Minute. 
![CoE_Error](https://user-images.githubusercontent.com/97743569/149528435-a36abae5-417d-48a4-a440-ab96d2276ab0.png)

Here is the error message we are getting every day:

Your audit logs were collected but some were missed do to truncated results in this run . 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 1 Hour 
See CoE documentation for more details. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

TimeInterval - Unit

**Comment by Jenefer-Monroe** [comment] 2022-01-14 14:20
Please see step 11 in this section of our setup documentation [setup the power automate flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)

**Comment by devchoplife** [comment] 2022-01-14 14:20
> ### Describe the issue
> We are getting constantly the error message that the Center of Excellence Starter Kit requires smaller chunks and that the current chunking size is set to 1 Hour. However, we have already changed the chunking size to 1 Minute. ![CoE_Error](https://user-images.githubusercontent.com/97743569/149528435-a36abae5-417d-48a4-a440-ab96d2276ab0.png)
> 
> Here is the error message we are getting every day:
> 
> Your audit logs were collected but some were missed do to truncated results in this run . You will need to use a smaller interval to gather all logs. Current chunking size: 1 Hour See CoE documentation for more details.
> 
> ### Expected Behavior
> _No response_
> 
> ### What solution are you experiencing the issue with?
> Audit Log
> 
> ### What solution version are you using?
> 1.70
> 
> ### What app or flow are you having the issue with?
> TimeInterval - Unit
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Anything else?
> _No response_

While working on this using the COE documentation, all requirements have been satisfied and this error keeps showing up everyday.

**Comment by Jenefer-Monroe** [comment] 2022-01-14 14:22
Likely the issue is that you did not update the env variable correctly. Please note that env vars are cached. Flows cache these such that you need to turn them off and on again in order to see the values in the flow. 
Please see [update environment variables](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by Jenefer-Monroe** [comment] 2022-01-14 15:49
Did you turn the flows off and back on? Per the above, env variables are cached in flows and you need to turn them off and back on in order to see the values change in flows that reference them

**Comment by DzCoE** [comment] 2022-01-17 13:19
Hello Jenefer, thank you for your feedback! I turned the flows off and back on, and still did get the same message again regarding the chunking size. Do you have any other ideas, what I could do else?

Von: Jenefer Monroe ***@***.***>
Gesendet: Freitag, 14. Januar 2022 16:49
An: microsoft/coe-starter-kit ***@***.***>
Cc: Subasic Dzana ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/coe-starter-kit] CoE Audit Logs require smaller chunks (Issue #1754)


Did you turn the flows off and back on? Per the above, env variables are cached in flows and you need to turn them off and back on in order to see the values change in flows that reference them

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F1754%23issuecomment-1013240638&data=04%7C01%7Cdzana.subasic%40amag.ch%7C94e9200ddeaa41ec997508d9d7756b2a%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637777721571852589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Pr10qqBvaPaeINiJFeH7hO5%2F7KKmXvkbKck7DaoGGbY%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXJXFULIHUBZNEWFW6YWCQ3UWBAXVANCNFSM5L64ZRIQ&data=04%7C01%7Cdzana.subasic%40amag.ch%7C94e9200ddeaa41ec997508d9d7756b2a%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637777721571852589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FW49AXlGtisrhxDVSvoNQr%2F%2BZ7qimvBbtgL1IQojpZU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdzana.subasic%40amag.ch%7C94e9200ddeaa41ec997508d9d7756b2a%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637777721571852589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BKfSJ%2Ff3N2MWY6dJUG%2F9eO6uyE5fL1yVYfixXGtlSBE%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdzana.subasic%40amag.ch%7C94e9200ddeaa41ec997508d9d7756b2a%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637777721571852589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Rm0EPuVQ5rMhJbYPuQ0ImIknLeQKKgwcyNKwtjt2Dqg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

_________________________________________________________________________________________
Diese Mitteilung ist vertraulich. Wenn Sie nicht der vorgesehene Empf?nger sind, bitten wir Sie, diese E-Mail
zu l?schen und uns umgehend zu benachrichtigen. Danke. Ce message est confidentiel. Si vous n'?tes pas le
destinataire, nous vous prions d'effacer cet e-mail et de nous en informer imm?diatement. Merci. Questo
messaggio contiene delle informazioni di natura confidenziale. Qualora non foste il destinatario corretto, La
preghiamo di comunicarlo immediatamente al mittente e di distruggere il presente messaggio. Grazie. This
message is confidential. If you are not the intended recipient, please delete the e-mail and contact us immediately.
Thank you.

**Comment by Jenefer-Monroe** [comment] 2022-01-17 14:13
Please open the latest flow run of **Admin | Sync Audit Logs** and show what came through for the **_CONFIGURE :: Time interval_** action. Here shows the example of running with 5 minute chunks:
![image](https://user-images.githubusercontent.com/89584709/149784558-392680d3-ad5c-4d5d-b395-e542b6dbfdf7.png)

Then please open that flow for edit and show you are using the correct flow, you should see the environment variables there in that action as shown here
![image](https://user-images.githubusercontent.com/89584709/149785545-390a8ce0-300d-427f-a8b5-c30b1c2c61dc.png)

**Comment by DzCoE** [comment] 2022-01-19 07:54
Thank you very much for your help!
It worked - the chunking size has been set to 1 Minute!
However the CoE Audit Logs still require smaller chunks.
Is "Second" a valid chunking size or do we have other possibilities? What would you recommend here?

Here's the notification we get:


CoE Audit Logs require smaller chunks

Your audit logs were collected but some were missed do to truncated results in this run <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Femea.flow.microsoft.com%2F4b35726b-2a63-403c-8638-fdaf068b79a7%2Fflows%2Fff499f16-d1c9-2af1-8b07-4e8f30219b73%2Fruns%2F08585591027904272488544965868CU15&data=04%7C01%7Cdigitalworkplace%40amag.ch%7Cc8aa35a62de6492eb4c908d9da72d691%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637781009014656641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U3gWLQ21L0c%2Fcxzld1o50vIqe%2F4q1cknzBFaWB1Dvk0%3D&reserved=0> .
You will need to use a smaller interval to gather all logs.
Current chunking size: 1 Minute
See CoE documentation <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpower-platform%2Fguidance%2Fcoe%2Fsetup-auditlog%23set-up-the-power-automate-flow&data=04%7C01%7Cdigitalworkplace%40amag.ch%7Cc8aa35a62de6492eb4c908d9da72d691%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637781009014656641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JiguFSYNskt0BAPXvW6Hq3fHLKQ2d6F6E4Adjk3%2B9Ng%3D&reserved=0> for more details.


Von: Jenefer Monroe ***@***.***>
Gesendet: Montag, 17. Januar 2022 15:14
An: microsoft/coe-starter-kit ***@***.***>
Cc: Subasic Dzana ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/coe-starter-kit] CoE Audit Logs require smaller chunks (Issue #1754)


Please open the latest flow run of Admin | Sync Audit Logs and show what came through for the CONFIGURE :: Time interval action. Here shows the example of running with 5 minute chunks:
[Das Bild wurde vom Absender entfernt. image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F149784558-392680d3-ad5c-4d5d-b395-e542b6dbfdf7.png&data=04%7C01%7Cdzana.subasic%40amag.ch%7C1a5d364805554bfb7c6a08d9d9c39e02%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637780256456336369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=46wxkRBQoe2WLjz4uBxIAA8KRRDK3DNBx2j9VKgwbbU%3D&reserved=0>

Then please open that flow for edit and show you are using the correct flow, you should see the environment variables there in that action as shown here
[Das Bild wurde vom Absender entfernt. image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F149785545-390a8ce0-300d-427f-a8b5-c30b1c2c61dc.png&data=04%7C01%7Cdzana.subasic%40amag.ch%7C1a5d364805554bfb7c6a08d9d9c39e02%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637780256456336369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zJ%2FiZG1xJ1G4KxniJUGhQK1HTAK4GMDD9EjYG6qvtgI%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F1754%23issuecomment-1014589295&data=04%7C01%7Cdzana.subasic%40amag.ch%7C1a5d364805554bfb7c6a08d9d9c39e02%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637780256456336369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LaJRDjQuplShcxL4CeFRZE9fUcMPmOX75%2FMJSg%2F%2FNlM%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXJXFUI4VB33SDPYWMPQZSTUWQP2VANCNFSM5L64ZRIQ&data=04%7C01%7Cdzana.subasic%40amag.ch%7C1a5d364805554bfb7c6a08d9d9c39e02%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637780256456336369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZtlBf6zfWbEKjvs9hh%2Fh6Wdp0cE32fuRnahfVDau0cM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdzana.subasic%40amag.ch%7C1a5d364805554bfb7c6a08d9d9c39e02%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637780256456336369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rV54vqR%2F1nCNf%2FEZjGp07%2FTnm3sgtyt0k7qOKdqd9MY%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdzana.subasic%40amag.ch%7C1a5d364805554bfb7c6a08d9d9c39e02%7Cb4a264fc0bfd40569d486c9a934de35b%7C0%7C0%7C637780256456336369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hxc4vxKHeb4IeIr8D1ufnlwJgY%2BsL1DmcrlBqoPl7Ac%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

_________________________________________________________________________________________
Diese Mitteilung ist vertraulich. Wenn Sie nicht der vorgesehene Empf?nger sind, bitten wir Sie, diese E-Mail
zu l?schen und uns umgehend zu benachrichtigen. Danke. Ce message est confidentiel. Si vous n'?tes pas le
destinataire, nous vous prions d'effacer cet e-mail et de nous en informer imm?diatement. Merci. Questo
messaggio contiene delle informazioni di natura confidenziale. Qualora non foste il destinatario corretto, La
preghiamo di comunicarlo immediatamente al mittente e di distruggere il presente messaggio. Grazie. This
message is confidential. If you are not the intended recipient, please delete the e-mail and contact us immediately.
Thank you.

**Comment by devchoplife** [comment] 2022-01-19 08:55
Thanks for your help @Jenefer-Monroe

**Comment by DzCoE** [comment] 2022-01-20 13:39
@Jenefer-Monroe 
Thank you very much for your help!
Turning off and on the flows helped. However the Chunking size of 1 Minute is also still to small. We are still getting the error message "You will need to use a smaller interval to gather all logs. / Current chunking size: 1 Minute" each day.

Do you have a recommendation. Is Second a valid chunking size?
Thank you very much in advance!

**Comment by Jenefer-Monroe** [comment] 2022-01-21 16:37
Perhaps you are using an old version of the solution. 
Here are the env variables we ship with, and the one of interest highlighted. 
![image](https://user-images.githubusercontent.com/89584709/150564612-b0e9d2df-4c1f-4278-9209-8ef84c9e670a.png)

You can manually adjust this in the flow but note that it will create an unmanaged layer that you will need to remove in order to receive updates in the future. 
![image](https://user-images.githubusercontent.com/89584709/150565081-f5943b85-716f-464a-8ac7-865b2eb232ea.png)

**Comment by Jenefer-Monroe** [comment] 2022-01-25 14:47
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-01-25 14:47 UTC
Labels: question, coe-starter-kit
