### ISSUE TITLE
CoE-Starter-kit Flows

### ISSUE THREAD

**Issue by JMMora** [microsoft/coe-starter-kit#1234] opened 2021-09-24 19:45 UTC
Hi,

I am looking to understand the welcome email and end user business justification & approval flows
seems to not work.

**Comment by Jenefer-Monroe** [comment] 2021-09-27 13:49
Hi there. Our flows are documented here [Flows in Core](https://docs.microsoft.com/power-platform/guidance/coe/core-components#flows). And pasted below the description of the welcome mail. Please clarify what questions you might have:
![image](https://user-images.githubusercontent.com/89584709/134921264-7774df5a-e6ef-4e20-a841-4f47682803a5.png)

That flow being broken is a dupe of #1209

**Comment by JMMora** [comment] 2021-09-27 19:30
Thank you very much, I was able to find what I was looking for.

my final question is regarding the flow Env Request | Cleanup expired environments 
for the solution: Center of Excellence - Core Components for Teams

**Comment by manuelap-msft** [comment] 2021-09-28 13:44
Hello,

are you looking for information of what that flow does or do you have an error with it? All our flows are covered in our [documentation here](https://docs.microsoft.com/power-platform/guidance/coe/core-components#flows), see:

| Env Request \| Cleanup expired environments | Schedule | Daily | Cleans up environments with expiration dates identified or sends weekly warning email notifications every Monday if the expiration date is coming up within the month. |

Let us know if you have any further questions

**Closed** 2021-10-04 13:25 UTC
Labels: coe-starter-kit
