### ISSUE TITLE
[CoE Starter Kit - BUG] Error code 8004F036 - Governance Components

### ISSUE THREAD

**Issue by ajeyng** [microsoft/coe-starter-kit#8948] opened 2024-09-09 20:50 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to deploy the "CenterofExcellenceAuditComponents_3_25_managed" solution. I keep running into the below error message:

**Error Code**
8004F036

**Exception message**
The dependent component Workflow (Id=6fda1b2d-3904-ec11-94ef-00224826a4d2) does not exist. Failure trying to associate it with CanvasApp (Id=bf4b58de-9ee3-4faf-9d34-efb189dfe499) as a dependency. Missing dependency lookup type = PrimaryKeyLookup.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

CenterofExcellenceAuditComponents_3_25_managed

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Selected the desired environment.
Imported the solution (CenterofExcellenceAuditComponents_3_25_managed)
Confirm all connections are using the correct account
Updated environment variables and started deploying the solution.
After a few minutes it errors out.

**Comment by Jenefer-Monroe** [comment] 2024-09-09 22:20
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by ajeyng** [comment] 2024-09-10 13:43
Thank you, Jenefer for looking into this. Here is the screen shot of the installed solutions
![image](https://github.com/user-attachments/assets/d89c68ef-8d71-4458-a013-a28909ccfae3)

**Comment by Jenefer-Monroe** [comment] 2024-09-10 14:18
OK looks like you have some customizations, I wonder if thats where the issue is. 
Can you plesae go see if you find the canvas app its referencing in the error? 
![image](https://github.com/user-attachments/assets/c3a8d163-95e1-424a-9287-5dfa8ad45967)

**Comment by Jenefer-Monroe** [comment] 2024-09-17 00:04
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-09-17 00:04 UTC
Labels: bug, coe-starter-kit
