### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to edit the default choices in column "Maker Requirement - Data Classification" in D4T environment

### ISSUE THREAD

**Issue by HMJ-Somerset** [microsoft/coe-starter-kit#2979] opened 2022-06-13 09:06 UTC
### Describe the issue

Unable to edit the default choices in column "Maker Requirement - Data Classification", in the "PowerApps App" table, when installed in a Teams environment.

The CoE is installed in a Teams environment, and I want to change the data classification values in the Developer Compliance Centre to match our protective marking labels.  However, when I try and edit the the PowerApps App table to change the default values in the Maker Requirement - Data Classification column I get the error: 
There was a problem creating or updating your column 'Maker Requirement - Data Classification'. Please try again.

This error persists with all columns that I try to edit.
I have tried editing the table in the PowerApps Teams app,  and the main maker web app.
I have tried creating a new solution and importing the PowerApps App table.  In this case I can add a new column but still get the same error when trying to edit the Maker Requirement - Data Classification column.
I am a PowerPlatform Admin and in the admins group for the environment and solution.

### Expected Behavior

Edit or replace the default column choices with my data classification values

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19.1

### What app or flow are you having the issue with?

Developer Compliance Center (Teams Version)

### Steps To Reproduce

1. From either Teams PowerApps or maker.PowerApps 
2. Select table PowerApps app, click Edit
3. Go to the choice column Maker Requirement - Data Classification, 
4. select edit choices 
5. remove the current entries and add new values (or enter new values in current fields)
6. click save
7. get error message:  There was a problem creating or updating your column 'Maker Requirement - Data Classification'. Please try again.

### Anything else?

![HMJ_Somerset_0-1654530308138](https://user-images.githubusercontent.com/106976858/173318715-3559444d-0f6f-42e5-bc86-11e88eb80971.png)

**Comment by HMJ-Somerset** [comment] 2022-06-13 12:17
Please could you explain more about the product error?  This is not an error I have with any other solution.  Just the CoE Starter kit tables.  It applies to all columns.
Thanks, Hazel

**Comment by manuelap-msft** [comment] 2022-06-13 12:19
It could be do with the CoE Starter Kit being a managed solution. Are you not seeing the same issue with other managed solutions?

Unfortunately we can not help with product errors here, as our team only looks after the CoE starter kit and not the product itself. You'll have to raise a support ticket through formal channels to understand that error further: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

**Comment by manuelap-msft** [comment] 2022-06-13 12:40
It may be a limitation of Teams environments. We have tested the above steps for changing choices and they worked for us: https://github.com/microsoft/coe-starter-kit/issues/2923#issuecomment-1147651699 so hopefully you are successful too following those steps.

We can only help with what's within the scope of the CoE starter kit, but can not control product behaviour.

**Comment by Jenefer-Monroe** [comment] 2022-06-13 13:17
Duplicate of #2923

**Closed by Jenefer-Monroe** 2022-06-13 13:17 UTC
Labels: bug, coe-starter-kit
