### ISSUE TITLE
[CoE Starter Kit - QUESTION] DLP Error when turning on flows

### ISSUE THREAD

**Issue by FolkestadNett** [microsoft/coe-starter-kit#4683] opened 2023-01-30 10:32 UTC
### What is your question?

Not able to activate deactivated flows in the flow section, receive error messages

Center of Excellence - Core Components:

Aktivering mislyktes. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ApiPolicyEndpointViolation","message":"Administratordatapolicyen CoE Power begrenser tilgang til endepunktet @{parameters('Graph URL Environment Variable (admin_GraphURLEnvironmentVariable)')}v1.0/servicePrincipals/@{triggerBody()['text']} for koblingen /providers/Microsoft.PowerApps/apis/shared_webcontents.","extendedData":{"violation":{"policyId":"/providers/Microsoft.BusinessAppPlatform/scopes/service/apiPolicies/6a3a6ac6-6886-4933-af6d-e8b86a5d81e0","policyDisplayName":"CoE Power","type":"BlockedEndpoint","parameters":["/providers/Microsoft.PowerApps/apis/shared_webcontents","@{parameters('Graph URL Environment Variable (admin_GraphURLEnvironmentVariable)')}v1.0/servicePrincipals/@{triggerBody()['text']}"]},"additionalInfo":{}}}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

all the deactivated flows that need to be activated

**Comment by manuelap-msft** [comment] 2023-01-30 10:54
Hello,

thanks for reaching out! Actually, this error is not related to the CoE kit but to the DLP policy you have applied to your environment - the issue is related to a known limitation of granular controls for DLP. 

Basically, granular controls don't evaluate dynamic content that comes from an environment variable - only static endpoints are evaluated. That's why you don't see the error when you add the URL directly, but you do see it when it's populated via an environment variable
![image](https://user-images.githubusercontent.com/55705669/214884977-41688dd2-34f9-476c-a965-f38b0ca20f10.png)

Here's the documentation https://learn.microsoft.com/en-us/power-platform/admin/dlp-granular-controls#known-limitations

You will have to remove the endpoint filtering on the HTTP with Azure AD action in your "CoE Power" DLP Policy.

**Comment by folkestad96** [comment] 2023-01-31 09:27
Thank you for the fast reply!

I have now removed the endpoint filtering on the HTTP with Azure AD action in your "CoE Power" DLP Policy.
And moved the HTTP with Azure AS to non business connection.
I still get an error message but it seems to be smaller.
what else do I need to change?
![image](https://user-images.githubusercontent.com/95488334/215720885-b340b349-31af-481e-b86a-007b122f8f6f.png)

**Comment by manuelap-msft** [comment] 2023-01-31 10:31
Hello,

I think if I translated the message correctly, it sounds like either the Microsoft Dataverse or Microsoft Dataverse (Legacy) connector are in a different DLP category then the HTTP with Azure AD connector. These connectors have to be in the same category (business category) as the CoE Starter Kit uses them together in flows and apps. Here's a list of all the connectors that the CoE kit uses, and they all have to be in the same "business" category: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by FolkestadNett** [comment] 2023-01-31 10:39
![image](https://user-images.githubusercontent.com/123945365/215737710-ac9105e9-a6f9-4f44-b88b-17475b8436b0.png)
Should everything be in Business?

**Comment by manuelap-msft** [comment] 2023-01-31 10:48
All the connectors listed here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies need to be in the same category - can be either business or non-business as long as all of them are in the same group. The category is just a "label", it's the grouping itself that matters.

**Comment by Jenefer-Monroe** [comment] 2023-02-05 14:56
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-02-05 14:56 UTC
Labels: question, coe-starter-kit

**Comment by FolkestadNett** [comment] 2023-02-15 11:19
sorry for late reply, now all the connectors are listed in the same category business but when I try to activate a flow i receieve this error message

Activation failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"MissingAdequateQuotaPolicy","message":"User eda5ea5e-428c-466c-9616-f3550e00d522 does not have a service plan sufficient for the non-default Microsoft Dataverse connection. https://go.microsoft.com/fwlink/?linkid=2123710","extendedData":{}}}".

I have also tried to set myself as a power platform administrator in the azure AD but nothing changed

**Comment by manuelap-msft** [comment] 2023-02-15 11:26
This indicates that you do not have sufficient licenses to turn on the flow. Please review the pre-requisites here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with

The flows use premium connectors, and as such a premium (Power Automate Per User) license is required.

**Comment by FolkestadNett** [comment] 2023-02-22 14:26
I have now access to all these licenses, and I still get the error and is sent to this page.
https://learn.microsoft.com/nb-NO/troubleshoot/power-platform/power-automate/user-does-not-have-a-service-plan-error
what am I missing?
![image](https://user-images.githubusercontent.com/123945365/220650464-6ec3a01a-27b6-4c37-a513-479b5b480fac.png)
