### ISSUE TITLE
[CoE Starter Kit - BUG] Center of Excellence - Core Components" failed to import

### ISSUE THREAD

**Issue by sdadageico** [microsoft/coe-starter-kit#7962] opened 2024-04-01 19:07 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade

### Expected Behavior

Solution imported successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Whole solution

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1.Login to https://make.powerapps.com
2. Look for coe-premium-dvo02
3. Import latest coe core components managed solution 
4. error displays

### Anything else?

I am not able to delete the holding solution which is preventign me from importing the upgrade

AB#2699

**Comment by sdadageico** [comment] 2024-04-02 14:10
I am unable to delete this upgrade because of multiple dependencies. The more dependencies I remove the more they pop-up Its like peeling an onion. The dependencies never ending. I was not sure if this what we need to do for every upgrade. Was this issue reported elsewhere

**Comment by Jenefer-Monroe** [comment] 2024-04-02 15:23
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by sdadageico** [comment] 2024-04-02 15:37
Attached is the screenshot with lis tof solutions installed

**Comment by sdadageico** [comment] 2024-04-02 15:41
![Uploading Screenshot.png…]()

**Comment by Jenefer-Monroe** [comment] 2024-04-02 15:51
Sorry the screenshot did not come through. Note that you will need to be logged in to GitHub to share it. 
Here is what I see: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/acd2bc4a-921d-4ab3-9e9f-1cc40b12d752)

**Comment by sdadageico** [comment] 2024-04-02 16:21
Im logged in but the attachment does not shown up and pasting it does not work. Is there another way to do this ? I put it in a word but still does not show up

**Comment by sdadageico** [comment] 2024-04-02 17:25
+mahesh



Sensitivity: Company-Internal

**Comment by sdadageico** [comment] 2024-04-02 19:14
Can you please let me know how i can ship this image ?

**Comment by Jenefer-Monroe** [comment] 2024-04-02 19:50
I'm afraid I',m not a GitHub expert. Perhaps if you clear your cache?

**Comment by Jenefer-Monroe** [comment] 2024-04-03 11:21
If you are upgrading from long ago (~July 2023 or earlier) then likely the cause is due to the presence of the deprecated Audit Logs solution. 

You can walk the steps here to resolve: https://github.com/microsoft/coe-starter-kit/issues/6018. 
In short they are

- Delete _upgrade
- Delete Audit Logs solution and any other dependencies
- Try your upgrade of Core again
- Setup new Audit Logs collection technique

**Comment by sdadageico** [comment] 2024-04-03 14:50
This issue occurs when I try to delete the _upgrade solution

**Comment by Jenefer-Monroe** [comment] 2024-04-03 14:52
ok you likely ended up with some dependencies local to your install then. You will need to look through the list to clean them up.

**Comment by Jenefer-Monroe** [comment] 2024-04-09 12:06
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-04-09 12:06 UTC
Labels: bug, coe-starter-kit
