### ISSUE TITLE
Failures with Admin | Sync Template v3 (PVA)

### ISSUE THREAD

**Issue by kbirstein** [microsoft/coe-starter-kit#2608] opened 2022-04-29 14:05 UTC
### What is your question?

I'm getting notifications every morning that "Some of the Sync Flows in the CoE Starter Kit have failed" for "Admin | Sync Template v3 (PVA)" flow. They are only the PVA Sync flows and only in 5 of my 18 environments. Only four of my environments are Teams environments so it's not an issue of Teams environments vs. standard environments. And as far as I know I have no PVA at all (Virtual Agent Detail page in Power BI template is blank). When I investigate the error in the failed flows I see "'botid' cannot be selected'". Any idea why I am getting these errors?
![GetBotID](https://user-images.githubusercontent.com/13750516/165960250-d4b7b511-069d-4f65-8459-4445f9024e69.jpg)
![FailedPVAEnvironments](https://user-images.githubusercontent.com/13750516/165960285-29570f5b-3e59-4fc3-a372-763446434176.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2022

**Comment by Jenefer-Monroe** [comment] 2022-04-29 14:16
Hello, known and fixed for May via https://github.com/microsoft/coe-starter-kit/issues/2402
Thanks for using CoE

Duplicate of #2402

**Closed by Jenefer-Monroe** 2022-04-29 14:16 UTC
Labels: question, coe-starter-kit

**Comment by kbirstein** [comment] 2022-04-29 15:25
Ok, Thanks
