### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1160] opened 2021-09-13 10:28 UTC
### Describe the issue

Hi
Whenever I deploy a new version of the CoE I lose the Office 365 Management API Application Registration and have to get the Azure ad people recreate it.  So the Audit Logs part of the Coe Does not work as you cannot loginto the custom connector because the app registration.

### Expected Behavior

I should be able to update the CoE with the latest update without losing the app registration.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

Office 365 Management API connector

### Steps To Reproduce

Floow the instruction to deploy the new version of the core components and the audit logs.

Notice that the Audit logs section stopped working.  Look further and find the app registration has disappeared.

### Anything else?

Azure AD are now refusing to keep recreating the APP Registration so now have no access to the audit log info.

**Comment by manuelap-msft** [comment] 2021-09-13 11:36
This is a known product issue, and nothing to do with the CoE Starter Kit. You will have to reconfigure the custom connector - https://github.com/microsoft/coe-starter-kit/issues/1146#issuecomment-916499947

We will add a note to our documentation to call that out as well. 

Closing as duplicate of #1146

**Closed by manuelap-msft** 2021-09-13 11:36 UTC
Labels: coe-starter-kit

**Comment by NPrice99** [comment] 2021-09-13 11:38
Hi @MAnuela - can you give me more details as I have been asked to reaise an incident

**Comment by manuelap-msft** [comment] 2021-09-13 11:44
What details are you looking for?

It is a known and understood product limitation that custom connectors will loose their connection configuration (= where you set up the client id / secret) on Upgrade, and that this has to be reconfigured. You will not have to re-create a new App Registration, but will have to re-enter the Client ID and Secret that you previously set up.

**Comment by NPrice99** [comment] 2021-09-13 11:46
My problem is that the App Registration actually disappears !

**Comment by manuelap-msft** [comment] 2021-09-13 11:47
The CoE Starter Kit has no functionality to either create or delete app registrations. So this is also a product issue.

**Comment by NPrice99** [comment] 2021-09-13 11:49
Have raised an incident with our Microsoft Incident Management Team
