### ISSUE TITLE
[CoE Starter Kit - QUESTION] Apps entered without their information (environment / name / etc)

### ISSUE THREAD

**Issue by Dlutchy** [microsoft/coe-starter-kit#4657] opened 2023-01-24 01:31 UTC
### What is your question?

In the Admin View App in the PowerApps App view why do I see some rows that are blank? How do I stop these blank rows from being populated?
![image](https://user-images.githubusercontent.com/67881320/214194511-64ba46c8-0a0b-4d0c-b7c9-69a0ba525dc4.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment] 2023-01-24 10:25
I dont know how these got populated. Can you please see if there is data in any of the other columns? 

### Here is one way to explore the full data in the table:
Chose Export to Excel > Dynamic Worksheet
![image](https://user-images.githubusercontent.com/89584709/214265787-06838507-68ea-4b8b-b45f-402765fe7af2.png)

Select all the columns (Record Types) offered > Export
![image](https://user-images.githubusercontent.com/89584709/214266213-37c634d8-2444-4659-8ac8-5a272f4049c4.png)

Open the downloaded file > click Enable Editing then Enable Content in the top yellow bar if asked
Select the top left cell in the spreedsheet (mine was D1) and control-T to make a table
Make sure "My table has headers" is checked and hit ok
![image](https://user-images.githubusercontent.com/89584709/214267295-5f503fab-f112-47de-9a48-d63635f8b14f.png)

Say yes to the prompt, we are just looking at the data
![image](https://user-images.githubusercontent.com/89584709/214267414-2bcc80fe-f09e-4787-8320-7a9e523f9e07.png)

Now filter to App Environment blank and see, what columns contain data?

**Comment by Dlutchy** [comment] 2023-01-24 23:00
Firstly, thank you for the very clear instructions.
Secondly, the results of the blank rows show very little data.
[Link to Spreadsheet](https://365assist.sharepoint.com/:x:/s/365Assist/EQ1VMknuuFFKkzJJaTKXgdoBV9sg4PXboL5Qvw_H7Jzugg?e=8jII51)

Can you tell me which Flow creates these records then I can investigate the flow results.

**Comment by Jenefer-Monroe** [comment] 2023-01-25 01:14
I with I knew how these blank ones got created. We fill the table in the following flow: **_Admin | Sync Template v3 (Apps)_**

As far as I can tell, its not what is creating these blanks but you taking a look would be great. 

I would also be curious, if you delete all these blank rows, will they come back on the next inventory run? As is, they wont be useful to you.

**Comment by Jenefer-Monroe** [comment] 2023-01-25 01:15
I with I knew how these blank ones got created. We fill the table in the following flow: **_Admin | Sync Template v3 (Apps)_**

As far as I can tell, its not what is creating these blanks but you taking a look would be great. 

I would also be curious, if you delete all these blank rows, will they come back on the next inventory run? As is, they wont be useful to you.

**Comment by Jenefer-Monroe** [comment] 2023-01-25 12:46
Another user posted something similar and we were able to deduce cause. Please see https://github.com/microsoft/coe-starter-kit/issues/4608. 
Will fix for Feb release.

**Comment by Dlutchy** [comment] 2023-01-25 22:20
Thanks for that. Looking forward to the fix.
BTW - As suggested I deleted the empty rows and they returned the next day when the flow ran again.

**Comment by Jenefer-Monroe** [comment] 2023-01-30 17:30
closing out as a Duplicate of #4608 
Thanks for posting!

**Closed by Jenefer-Monroe** 2023-01-30 17:30 UTC
Labels: question, coe-starter-kit
