### ISSUE TITLE
[CoE Starter Kit - BUG] Error when trying to upgrade to Nov Core Components

### ISSUE THREAD

**Issue by lsheltonSTO** [microsoft/coe-starter-kit#7084] opened 2023-11-13 17:07 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have version 4.16 installed in my dev COE environment.  I downloaded the new CoreComponents update for November and went to my dev COE environment to install it (4.17).

I get to the Import a solution screen, but when I click next is when I have problems:
<img width="536" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/76535800/0c5f81fe-5ef9-40cd-997d-68d8857564f9">

Both at home and at work, with a several day waiting period between the two, I get this error screen upon clicking "Next":
<img width="742" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/76535800/63a6fdad-104d-4f55-bff1-f4b798ef8abd">
The "more details" pane:  We can't get that information right now. Either try again or check our support page to see if there are any known issues.
Session ID: 74ffb220-8246-11ee-836a-590790fa0955

There's not been issues on the support page listed either of the times I've sat down to do this.

### Expected Behavior

The solution prompts me for new environment variables and then installs the upgrade.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Not a specific one

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1.  In my "dev COE" environment
2. Download the 4.17 managed Core Component solution update for November
3. Go to make.powerapps.com and Solutions
4. Click Import solution
5. Select the 4.17 Core Component file
6. Click Next on the right-tab pop up window

AB#834

**Comment by manuelap-msft** [comment] 2023-11-13 17:12
This is a product bug related to processing environment variables. Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240 - the workaround is to use this URL  https://make.powerapps.com/environments/solutions?powerappsConnections.enableShowAllEnvVariablesOnImport=false with the URL parameter and import the solution from there. 

Closing as this is a duplicate of #7050. If you continue to see issues, please comment on #7050.

**Closed by manuelap-msft** 2023-11-13 17:12 UTC
Labels: bug, coe-starter-kit
