### ISSUE TITLE
[CoE Starter Kit - QUESTION] Desktop Flow dashboard empty - payload size too large for legacy Dataverse connector

### ISSUE THREAD

**Issue by Shinji-Suzuki** [microsoft/coe-starter-kit#2102] opened 2022-02-22 01:46 UTC
### What is your question?

I use translation software to make inquiries.
I may not speak correct English.

We have introduced the CoE Starter Kit, but I don't see all the graphs related to desktop flow.
Graphs other than desktop flow are displayed without any problem.
![Desktop flows](https://user-images.githubusercontent.com/100173189/155045860-0f14c886-c761-432e-b79f-50f3a79d8e11.jpg)

When I contacted Microsoft about this issue, I received the following contact:

------------------------------------Answer from Microsoft--------------------------------------
The cause was that the following error occurred when getting the information of the default environment where the desktop flow is stored.

"HTTP request failed:'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'"

We believe that an error occurred in the action because it violated the message size limit of the cloud flow.
https://docs.microsoft.com/ja-jp/power-automate/limits-and-config#message-size

In cloud flow, there is an upper limit to the message size that can be exchanged with one HTTP request.
An error will occur if you try to input or output a size that exceeds the upper limit.

Since this restriction is a restriction as a product, it is not possible to expand the buffer size at this time.
Therefore, it is possible to limit the size of data acquisition to less than the limit.
In that case, it may be necessary to take measures such as modifying the tools of the CoE starter kit.

The CoE Starter Kit tool itself is not supported.
We apologize for the inconvenience, but could you please contact us using the link below for information on how to resolve this error?
https://aka.ms/coe-starter-kit-issues
----------------------------------------------------------------------------------------------------------
As mentioned above, Microsoft did not get an answer, so we contacted you.
Sorry to trouble you, but could you please teach me how to deal with this matter?

The following attachment is a file that summarizes the emails with Microsoft.
The content of the attached file is the original Japanese text, so please refer to it if necessary.
[The contents of the e-mail.xlsx](https://github.com/microsoft/coe-starter-kit/files/8112889/The.contents.of.the.e-mail.xlsx)

Thank you.

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

AB#1260

**Comment by manuelap-msft** [comment] 2022-02-22 09:15
Hello,

thank you for using translation software to reach out to us - I hope you can translate my response back to Japanese but please let me know if you have any further questions!

Let's first check if you have Desktop Flow inventory correctly in the CoE Starter Kit, so we can work out if the issue is in the Power BI dashboard or the inventory.

1. Please go to make.powerapps.com > Select the environment you have the CoE installed
2. Open the Power Platform Admin View (model driven app)
3. Select UI Flows 
![image](https://user-images.githubusercontent.com/55705669/155100373-32f569a5-9733-49d7-b3bc-61da2d5f0907.png)

Do you see information there?

Then, let's check your desktop flow usage
1. Please go to make.powerapps.com > Select the environment you have the CoE installed
2. Select Solutions > Center of Excellence core components
3. Select Tables > RPA Sessions
4. Select the Data tab
5. Does it show data there?
![image](https://user-images.githubusercontent.com/55705669/155100563-55f443c8-0b49-4fb0-b6ac-16312bfb394b.png)

Thank you
Manuela

**Comment by Shinji-Suzuki** [comment] 2022-02-22 09:55
Thank you for contacting me.
The easy-to-understand content is very helpful.
A user who has the authority to open "UI Flows" has returned home, so I will contact you the day after tomorrow.
* Japan is a holiday tomorrow, so I will contact you the day after tomorrow.

thank you.
Shinji Suzuki

**Comment by Shinji-Suzuki** [comment] 2022-02-24 08:44
I checked both, but neither was displayed correctly.
![Screen1](https://user-images.githubusercontent.com/100173189/155488884-e7a987f3-0495-4507-a1dd-da9c98c6ff80.png)
![Screen2](https://user-images.githubusercontent.com/100173189/155488929-742f28c1-f855-483a-b8a4-546a4f27b2f2.png)

**Comment by Shinji-Suzuki** [comment] 2022-02-28 09:06
Has my reply reached you?
I would appreciate it if you could tell me the current situation.

**Comment by manuelap-msft** [comment] 2022-02-28 11:39
Hello,

apologies for the delay! It looks like Desktop flow inventory is not collected correctly, hence why the reports are showing empty.

Can you please check the cloud flows that collect this inventory?

- Please go to make.powerapps.com > Select the environment you have the CoE installed
- Select Solutions > Center of Excellence core components
- Select Admin | Sync Template v3 (Desktop Flows) to open the details page
- Check if this flow is on - Status should say On 
![image](https://user-images.githubusercontent.com/55705669/155977164-92aff45f-5e78-4955-9dee-aa69b1082e59.png)
- Check if there are any run errors
![image](https://user-images.githubusercontent.com/55705669/155977182-3f518271-2ae4-4370-95e1-df2b5973cbdf.png)
- If there are run errors, please open the failed run and find the action that failed and share that back with us.

Follow the same steps for the Admin | Sync Template v3 (Desktop Flows - Runs) flow.

Both of these flows are using child flows, so if they are turned off at the moment you may see an error turning them on if the child flows are not on as well - here's a list of everything that needs to be turned on: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

Thank you
Manuela

**Comment by Shinji-Suzuki** [comment] 2022-03-01 01:23
Thank you for your reply.
I checked the flow and both were valid.
![Screen1](https://user-images.githubusercontent.com/100173189/156086227-12d51b5f-830e-49a6-ad83-1afcb399950b.png)

![Screen2](https://user-images.githubusercontent.com/100173189/156086235-39381e33-694f-4e8d-ad87-ebce9ee8632c.png)

![Screen3](https://user-images.githubusercontent.com/100173189/156086242-62c9244d-02df-4494-a16b-8f6f68082f6a.png)
Please confirm.

I hope that the content of the response from Microsoft that I posted first can also be used as a reference for investigating the cause.

thank you.
Shinji Suzuki

**Comment by Jenefer-Monroe** [comment] 2022-03-01 14:37
I believe you have hit a product bug around payload size and the legacy connector. 

First, please create a new flow, in your CoE environment
Insert the List Rows action of the legacy dataverse connector:
![image](https://user-images.githubusercontent.com/89584709/156187277-7691cc59-37ef-4188-b95e-34b5410ff63b.png)
![image](https://user-images.githubusercontent.com/89584709/156187413-edf66727-100f-4f49-ba2e-5a3bc9cc8c30.png)

Select the environment where you expect to see a bunch of desktop flows from the first dropdown. Then select the Processes table
![image](https://user-images.githubusercontent.com/89584709/156188428-5efe941f-8856-4a75-b6a9-99a1c1291b80.png)

Save and run the flow. Does it return the expected Desktop Flows?

**Comment by Jenefer-Monroe** [comment] 2022-03-02 21:40
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role? You need this role in order to see all objects in the tenant. Without it you only see the environments and objects to which you have access.

Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

Please see our [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) for this and the other requirements needed to successfully run the starter kit.

**Comment by Shinji-Suzuki** [comment] 2022-03-04 09:38
Sorry for the late contact.
My ID has the role of Power Platform administrator.
![Screen](https://user-images.githubusercontent.com/100173189/156738214-5a8cbc0d-6b87-42f8-8004-21b2cfd9931b.png)
Please teach me how to deal with it.

Thank you.
Shinji Suzuki

**Comment by Jenefer-Monroe** [comment] 2022-03-04 14:21
Do you have the English language pack installed? Note that this is needed in order to use the starter kit [Supported Languages](https://docs.microsoft.com/power-platform/guidance/coe/limitations#supported-languages)

For this issue, if you scroll to the bottom of the list of tables you should see something like Enter custom value, and you can paste the word **_workflows_**. Does that return records? 
![image](https://user-images.githubusercontent.com/89584709/156779599-7ecdee01-4317-4b4f-bb79-0339fdda85fb.png)
![image](https://user-images.githubusercontent.com/89584709/156779756-8a45f65b-5e60-420d-bb3b-2c3ccb1d7533.png)

**Comment by Shinji-Suzuki** [comment] 2022-03-07 02:09
Thank you for your reply.
The English pack was not checked.
After confirming within the organization, I would like to switch to the English pack.

I chose Enter Custom Value and entered Workflow, but no records were returned.
![Screen](https://user-images.githubusercontent.com/100173189/156955845-aef870b3-53d5-484d-a397-3fd2fd6895c7.png)

**Comment by Shinji-Suzuki** [comment] 2022-03-08 01:07
There is a desktop flow in the environment.
Probably 249?
![Screen2](https://user-images.githubusercontent.com/100173189/157145334-ba868f50-fd97-47e1-af65-4617dc983bfa.png)

It was running every day.
![Screen](https://user-images.githubusercontent.com/100173189/157145451-7a14e7a7-35c1-479a-abdb-a376dce72e48.png)

**Comment by Jenefer-Monroe** [comment] 2022-03-08 12:33
Alright, I'm afraid you have hit a product bug. We've seen this now with a couple of people and you have confirmed its generality. 

Basically:

- We have some objects (Desktop Flows, Model Driven Apps, ... ) which do not have a proper connector for them
- In these cases we use the Dataverse tables for inventory
- But because the modern Dataverse connector does not yet let you select non-current envt we have to use the legacy Dataverse connector to fetch these tables. 
- Unfortunately the legacy Dataverse connector does not let you select which column to return and so brings backs the entire filtered table. 
- This can lead to payload size limitations, even with our pagination settings.

**Comment by Jenefer-Monroe** [comment] 2022-03-08 12:35
I've marked the bug as waiting for product. I'm afraid there is nothing more we can do at this time. It is just a product limitation until the connector work is done, estimate is H2 of 2022

**Comment by manuelap-msft** [comment] 2022-06-07 08:32
@[LizethRegules](https://github.com/LizethRegules) at the moment, using the Dataverse connector it's not possible to reduce the columns returned.

**Comment by S0URCEC0D3** [comment] 2023-07-28 16:48
Has this been fixed? I'm having the same issue and I'm using the July 2023 CoE kit

**Comment by Jenefer-Monroe** [comment] 2023-07-28 21:23
No we are still blocked, the feature is in development but not yet released to us to use.

**Comment by DevonAleshireMSFT** [comment] 2023-08-22 23:42
Good Afternoon, I have hit the same issue with a DoD customer and have upvoted the issue. Thank you!

**Comment by henriquesmoco** [comment] 2023-10-17 21:43
I have the same issue. I can see the error in the Flow Run of **Admin | Sync Template v3 (Desktop flows)**, but it says succeeded in the final status.

![image](https://github.com/microsoft/coe-starter-kit/assets/8483398/43b96db2-d2e8-4672-924f-bf28c66fcf1e)

**Comment by manuelap-msft** [comment] 2023-12-19 12:02
This has been fixed with the latest release if you use the v4 Desktop Flow sync flow instead. This new flow is using the modern Dataverse connector. Closing out. Please raise a new issue if you continue to experience issues here.

**Closed by manuelap-msft** 2023-12-19 12:01 UTC
Labels: question, coe-starter-kit, product-gap
