### ISSUE TITLE
[BUG]: Set Flow Permissions app issue with link to flow

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#719] opened 2021-07-01 09:29 UTC
**Describe the bug**
When viewing the Flow Details Screen of the Set Flow Permission app and the Flow Settings button is clicked a new tab is opened in the browser to open the flow but the URL is wrong.  This is because the Flow Maker URL column on the COE Settings table is empty and this column is not on the form and is not editable.

Very similar to this issue https://github.com/microsoft/coe-starter-kit/issues/333#issue-890866765 

**Component (please tell us which flow or app you are experiencing issues with):**
Canvas App - Set Flow Permission

**To Reproduce**
1. Open Set Flow Permission app
2. Click on a flow to open the flow details screen
3. Click Flow Settings

![image](https://user-images.githubusercontent.com/41050216/124100107-47e29e80-dab2-11eb-82b7-a0354e8805f9.png)

![image](https://user-images.githubusercontent.com/41050216/124101321-567d8580-dab3-11eb-8e9c-cbd625c08b86.png)

**Expected behavior**
I think the app needs to be updated so that it pulls the beginning of the URL from the Environment Variables instead of the COR Settings table

**Screenshots**
![image](https://user-images.githubusercontent.com/41050216/124099814-00f4a900-dab2-11eb-9dfd-545e3a86efac.png)

**Comment by manuelap-msft** [comment] 2021-07-01 12:28
Duplicate of #614 and fixed for the July release, which will go out next week.

**Closed by manuelap-msft** 2021-07-01 12:28 UTC
Labels: coe-starter-kit
