### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by vgk001** [microsoft/coe-starter-kit#2245] opened 2022-03-15 13:10 UTC
### What is your question?

Developer Compliance Center is not launching properly. It is always throwing error as

_This app stopped working. Try refreshing your browser._

Session ID: 9dd269a5-3b7d-45c4-b5f7-3cbfed433961

**From the Edge browser console**

Failed to load resource: the server responded with a status of 404 ()
es6.player.js:13 
        
       No previously cached ECS telemetry config exists - fallback to sending event
(anonymous) @ es6.player.js:13
es6.player.js:13 ECS - Config fetch complete
es6.player.js:13 
        
       No previously cached ECS telemetry config exists - fallback to sending event
(anonymous) @ es6.player.js:13
es6.player.js:13 ECS - Config fetch complete
9The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
es6.player.js:29 AppLoadedEvent Timeout Expired ... Flushing Telemetry

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment] 2022-03-15 13:51
Please see #2218 
What version of the player are you using?

**Comment by vgk001** [comment] 2022-03-16 07:40
the player version was .23 & I changed it to .31 via account setting in create.powerapps.com -- still the same

Even tried to turn on the latest updates for the environment - still no luck

type is "Production" & region is "unitedkingdom". 

Tried to update the app player version - however it is not getting update to .31. Kindly help to get this issue addressed

![image](https://user-images.githubusercontent.com/2571730/158540275-1796f413-97bb-4c4c-942c-f2066ccdf1ab.png)

![image](https://user-images.githubusercontent.com/2571730/158539191-ce76224d-24fa-401e-bb03-91a0fc3e29c2.png)

![image](https://user-images.githubusercontent.com/2571730/158539261-7e1c7354-e7f7-41f4-83bf-d08f491e7f0c.png)

**Comment by Jenefer-Monroe** [comment] 2022-03-16 14:25
Do you mean these two versions? 
3.22022.**23**
3.220**31**.21

**Comment by Jenefer-Monroe** [comment] 2022-03-16 15:55
Can you please clarify:
- is this also not working in the maker? Other people that repro can view the apps in the maker
- Please provide the full build number from the player (not the maker preview)

**Comment by Jenefer-Monroe** [comment] 2022-03-16 16:04
We will track all these via #2218 
Duplicate of #2218 
closign this one as dupe so that we will track all the information in one place

**Closed by Jenefer-Monroe** 2022-03-16 16:04 UTC
Labels: question, coe-starter-kit

**Comment by manuelap-msft** [comment] 2022-03-17 09:35
Hello, we have confirmation from the Power Apps Player team that this got fixed now, can you re-try to see if you're still experiencing the issue? Thank you!

PS: Thank you for sharing your Session ID with us, this was critical in the team finding the issue!

**Comment by manuelap-msft** [comment] 2022-03-18 12:03
Great, thanks for confirming!

in Dev CC, the default filter is to only show apps where compliance details have been requested through the compliance process - if you are not using those flows yet, you will have to change the filter by clicking on the filter icon > change filter from requested to all (it's a toggle) to see all apps.
