### ISSUE TITLE
[CoE Starter Kit - BUG] May 2023 SYNC HELPER - Cloud Flows not working for Default Env

### ISSUE THREAD

**Issue by JoeyOakley** [microsoft/coe-starter-kit#5622] opened 2023-05-24 15:22 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

During the **Get Flow as Admin** step, under the **Inventory this flow** scope, it looks if you pass the _envid_ variable for the Default environment you will run into access issues because the default environment is actually looking for "Default-_envid_".

All other environments seem to work just fine as they do not need the "Default-" prefix, but the default environment hits some auth errors.

Failed Flow for Default Env
![image](https://github.com/microsoft/coe-starter-kit/assets/134522506/f9544bad-053e-48a9-979b-99dafb7123df)
![image](https://github.com/microsoft/coe-starter-kit/assets/134522506/73bd9167-6fdf-4aba-95e8-935bc65ea15e)

I took a look at the Admin | Sync Template v4 (Flows) to verify how the data was being passed and saw the "Default-" prefix did exist there: 

![image](https://github.com/microsoft/coe-starter-kit/assets/134522506/7ae932d5-3170-4d7f-bdff-9600fb4d9989)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment] 2023-05-24 17:17
Hello, this is a duplicate of [#5595](https://github.com/microsoft/coe-starter-kit/issues/5595) for which a hot fix was released. 
View hotfix:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2023-HF1
Download hotfix:
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-May2023-HF1/CenterofExcellenceCoreComponents_4.8_managed.zip

**Closed** 2023-05-25 10:00 UTC
Labels: bug, duplicate, coe-starter-kit
