### ISSUE TITLE
[ALM Accelerator - BUG]: Custom Connector, GetIdentities unable to resolve schema

### ISSUE THREAD

**Issue by js9331** [microsoft/coe-starter-kit#954] opened 2021-08-03 15:29 UTC
### Describe the issue

The GetIdenties action on Azure DevOps custom connector is showing error "Unable to resolve schema" in Definitions tab. When trying to use ALM Accelerator for Advanced Makers, app shows error "CustomAzureDevOps.GetIdentities failed: The method 'GetIdentities' has an invalid value for parameter 'organization'" 

### Expected Behavior

No validation error on action in custom connector definition, and app lets me select from Azure DevOps organizations rather than erroring out.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20210757.1

### Steps To Reproduce

Using your install and setup steps - didn't do anything unique or custom yet - these errors all showed up after initial installation and configuration per the setup guides in github.

**Comment by mikefactorial** [comment] 2021-08-03 15:35
@js9331 thanks for bringing this to our attention. Let me see if I can reproduce this. Can you verify that you have selected an organization / project / repo in the settings of the app?

**Comment by mikefactorial** [comment] 2021-08-03 15:38
Also, can you try verifying the GetIdentities call from the Test tab of the Custom Connector e.g.

![image](https://user-images.githubusercontent.com/42348035/128044588-fd80de55-f890-481b-8712-325fc11aa53f.png)

**Comment by mikefactorial** [comment] 2021-08-03 15:43
One more thing that might assist in tracking down this issue is if you can start a monitoring session to capture the request to the GetIdentities call. e.g. 
![image](https://user-images.githubusercontent.com/42348035/128045313-74090392-76d9-44d5-a1a7-eece24648bff.png)

**Comment by js9331** [comment] 2021-08-03 17:15
@mikefactorial getting back to this: regarding whether or not I selected an org/project/repo, the error actually occurs when I launch the ALM Accelerator app - and the azure devops organization list does not populate. Howver, when I test GetOrganizations on the connector, I do get a 200 response. Here's some screenshots:

at launch, error banner and org list does not populate:
![image](https://user-images.githubusercontent.com/35241782/128057688-27b01eb7-ca08-4ba0-84da-3b800b9e0b9e.png)

running test on GetOrganizations succeeds:
![image](https://user-images.githubusercontent.com/35241782/128057880-75abf74f-4368-45a4-a7ca-867154fb016d.png)

I will go start a monitoring session now and report back on a separate message those results.

**Comment by js9331** [comment] 2021-08-03 17:16
@mikefactorial addendum to the above: the GetOrganizations test both succeeds, and I see all the Azure DevOps organizations I should see in the returned list, including the organization where we set up the AA4AM sample projects, pipeline templates, etc.

**Comment by mikefactorial** [comment] 2021-08-03 17:27
@js9331 the GetOrganizations screenshot of the response got cut off can you verify that there are results coming back in the response?

**Comment by js9331** [comment] 2021-08-03 17:29
@mikefactorial I just tried running Monitor multiple times, and I do not see any discrete events getting generated for the GetIdentites or GetOrganization actions in the monitor logs (like I see in your screenshot). I my monitor logs, those actions seem to be hidden inside a function called "ClearConnect": 
![image](https://user-images.githubusercontent.com/35241782/128059801-9521516c-21c3-454f-8705-14172fc87276.png)

**Comment by js9331** [comment] 2021-08-03 17:34
@mikefactorial here's an updated screenshot of GetOrganizations showing at  least the first item returned:
![image](https://user-images.githubusercontent.com/35241782/128060534-11dc2b8b-4bc5-466b-911c-44b9f3fc1641.png)

**Comment by js9331** [comment] 2021-08-03 17:58
@mikefactorial one last note: our Power Platform environments are GCC but connected to an Azure Commercial tenant - not sure if that makes any difference to the custom connector or not?

**Comment by mikefactorial** [comment] 2021-08-03 19:25
@js9331 interesting. I assume you are using the same connection for the app that you are using when testing the GetOrganizations operation in the custom connector in which case I'm not sure why there are different results in the app vs your test. Also, odd that the specific call to GetOrganizations / GetIdentities isn't showing in your trace results. Can you share the PowerAppsTraceEvents.json? If not here maybe put it in a private repo and add me as a collaborator?

**Comment by js9331** [comment] 2021-08-04 13:49
@mikefactorial just checking with some of my internal folks before sending that trace over to you (I'm with a local government and need to make sure my sec team is okay with me sharing out a trace log with you). I'm considering installing the prior version of the AA4AM app to see if that works - would you advise against that for any reason? (e.g. would I need to go back and replace all the pipeline templates devops configurations with older versions?)

**Comment by js9331** [comment] 2021-08-04 18:48
@mikefactorial I have been discussing with both our internal teams and our Microsoft reps, and Microsoft has advised that we open a support ticket with them on this issue, and transfer the trace log to Microsoft on the support ticket rather than adding to github. I'm communicating with sasing@microsoft.com currently on this if you want to check with him. Let me know if you want me to provide you any additional info on this bug thread, otherwise I will just switch over to a Microsoft support ticket instead.

**Comment by devkeydet** [comment] 2021-08-04 20:49
If an issue is related to something we need to fix in the CoE Starter Kit code, then support won't be able to help because this is an open-source project and everything in the CoE Starter Kit is a reference implementation.  We explain this here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support
However, if the root cause is something in the platform, support will and can help.  If it's a combination of collaboration with our team and support to figure it out, we'll collaborate to figure it out together.

@mikefactorial - Please connect offline to see how we can find the path of least resistance to help here.
@js9331  - As a general ask, please consider not sharing a person's email address in a public forum.  It often results in that person getting an overload of email because people will email them directly (including spam).

**Comment by devkeydet** [comment] 2021-08-04 20:51
@js9331  - I have deleted your comment due to sharing of a person's email address.  Feel free to submit a new comment.  I have also shared the details with @mikefactorial as a screenshot.

**Comment by js9331** [comment] 2021-08-04 21:41
@devkeydet thank you for correcting my mistake, and I am so sorry to both your project and the person who's email I posted (I've contacted them separately to apologize as well). Just to explain - I'm a government worker and my email is public info, and I was not being cognizant that things are different for folks in the private sphere. That said, Microsoft did request that I spin up a service ticket with them - I'm not sure how they intended to work with the project team on this, but they did advise me that I should not post the trace log on github and that they wanted me to transfer that to MS via the support ticket. They said they'd be able to reach out and connect with your team. I'll continue to monitor both this bug thread, and my Microsoft ticket - let me know if there's anything else I can do to reduce some of this friction and get back on a better path with your team.

**Comment by devkeydet** [comment] 2021-08-04 23:25
No worries.  These things happen.  That's why we can delete a post in case these things happen.  Thanks for your understanding.  We often hear from customers that their Microsoft contact advised them to submit support requests for the CoE Starter Kit.  Feel free to ask them to contact me, but they should be following the guidance here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support

Our relationship with support is unique due to disclaimer in the guidance above.  Generally, support engineers know to reach out to us, but sometimes we still run into situations where "Microsoft" tells a customer so submit a support request and support says, "we don't support the CoE Starter Kit."  We try not to ask customers to submit support requests until we've concluded the root cause of the issue submitted on GitHub is for us to fix or a platform team to fix.  Because if it is for us to fix, support would just send you right back to us.  For future reference and for anyone else reading this, if we haven't concluded that the root cause is for support to look at, but we need to exchange data that you aren't comfortable sharing on GitHub, we completely understand and will work with you to figure out taking what we can "offline" while honoring the spirit of open source and working out in the open for the benefit of others.  That could be as simple as "ping me on twitter, I'll give you my email address" to "let's spin up a private repo, you can drop the file(s) there, once we have them, we'll delete the private repo" or anything in between that meets your needs as a customer.  We just generally ask that you communicate as much as you *can* through GitHub.  You might not believe this, but once people get our email addresses they sometimes email us directly or IM (sometimes multiple times a day) for "personal support" which is not scalable or sustainable for us as a team.

We realize this "When to do I talk to support?  When do I talk to the CoE Starter Kit team?" isn't always easy to figure out.  We realize it makes for a less than ideal customer experience.  We've been working to have better collaboration with support.  We all want the same thing.  To help you resolve your issue in the quickest way possible.

When in doubt, follow the guidance here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support

We commit to letting you know when we think the issue requires you submitting a support request.  Thanks for using the ALM Accelerator for Advanced Makers.  Thanks for helping us make it better.  To this this statement: "and get back on a better path with your team".  You never left the path.  I am sorry if I left you with that impression.  We value and appreciate your contributions and helping us figure out why you are experiencing this issue.  We'll talk to the support engineer and figure out the right path forward for you.

**Comment by js9331** [comment] 2021-08-05 14:38
@devkeydet Thank you so much! And I am hearing you about this being a reference implementation. That being said, I've downloaded the latest unmanaged version of AA4AM and will be trying to get a working implementation myself from there as well. If I discover more details about the bug I encountered, or a fix for it, I'll post back here my findings.

**Comment by js9331** [comment] 2021-08-05 22:04
@devkeydet @mikefactorial  I found some things that confused me, so I thought I would just report them 😄 

- On the Definition screen, the custom connector shows that GetIdentities has an error
- The error is that it is unable to resolve the response schema
- When I test GetIdentities in the Swagger editor it returns a 404 error
- When I test GetIdentities on the Test tab of the connector, with the same values I used on the Swagger editor test, it returns a 200 and the payload that is expected

**Comment by mikefactorial** [comment] 2021-08-05 22:40
@js9331 Can you send the error you are getting in the Swagger Editor?
There is an issue with the response schema that I looked into as part of this thread. It's a side effect of the schema generation based on a given json response from what I can tell. The specific offending YAML in the custom connector which needs to be removed looks like the following.

                        http://schemas.microsoft.com/identity/claims/objectidentifier:
                          description: http://schemas.microsoft.com/identity/claims/objectidentifier
                          properties:
                            type: {description: type, type: string}
                            value: {description: value, type: string}
                          type: object
                          
It will be resolved in the next release, but if you want to try removing it to get rid of the schema warning give it a try. I'm reasonably certain it's a red herring though since your calls from the test tab are working.

**Comment by dylanhaskins** [comment] 2021-08-06 01:24
Hey Team,

I ran into the same problem, it would appear the issue is that the Policies in the Custom Connector lost their bindings to the Operations they should apply to. From what I can tell the "vssps" policy should only apply to GetIdentities and the "app" policy should only apply to GetOrganizations. By default they were both applying to everything, which causes the API calls to fail.

![image](https://user-images.githubusercontent.com/14045980/128441618-27a1ab35-0ed6-497b-b745-271235b99c6e.png)

**Comment by devkeydet** [comment] 2021-08-06 11:53
Thanks @dylanhaskins.  That should *not* be happening.  You say in the bug report you are using version 1.0.20210757.1.  That wouldn't make sense since we use YYYYMMDD in our builds and there is not 57th day in July.  Can you confirm that you meant 1.0.20210727.1?  That's the latest preview release?

Looking at this file:
https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorForAdvancedMakers/SolutionPackage/Connectors/cat_5Fcustomazuredevops_policytemplateinstances.json

It looks correct.  I also downloaded the release file:
https://github.com/microsoft/coe-starter-kit/releases/download/ALMAcceleratorForAdvancedMakers-July2021/ALMAcceleratorForAdvancedMakers_1.0.20210727.1_managed.zip

I unzipped the file and looked at cat_5Fcustomazuredevops_policytemplateinstances.json in the release.  It looks correct too.  I also doubled checked that things are working in our internal Test/Prod environments.  So, I don't understand how this is happening.  

@mikefactorial - Are you able to repro what @dylanhaskins is reporting in a clean environment?  What about in the update situation?  If we can't reproduce or find an obvious root cause, we may need to gather the activity id of the solution import and ask the Connectors team to investigate.

**Comment by devkeydet** [comment] 2021-08-06 11:56
The good news is that this should go away as we get rid of the custom connector since we are contributing back to the official Azure DevOps connector:
https://github.com/microsoft/coe-starter-kit/issues/696

The bad news is that it's going to be another release or two before those changes will happen.

**Comment by js9331** [comment] 2021-08-06 13:53
> @js9331 Can you send the error you are getting in the Swagger Editor?

@mikefactorial responding to this request from above - apologies if a couple steps behind from last night - catching up now...

Swagger editor error (when using parameter values that work in Test tab):

404 error

Body:
Page not found.

Response headers:
 activityid: **[redacted]** 
 cache-control: no-cacheno-storemust-revalidate 
 content-length: 15 
 content-type: text/plain; charset=utf-8 
 expires: -1 
 pragma: no-cache 
 request-context: appId=cid-v1:**[redacted]** 
 x-tfs-session: **[redacted]** 

Responses:
{
  "count": 0,
  "value": [
    {
      "descriptor": "string",
      "id": "string",
      "isActive": true,
      "memberIds": [
        null
      ],
      "memberOf": [
        null
      ],
      "members": [
        null
      ],
      "metaTypeId": 0,
      "properties": {
        "Account": {
          "type": "string",
          "value": "string"
        },
        "ComplianceValidated": {
          "type": "string",
          "value": "string"
        },
        "DN": {
          "type": "string",
          "value": "string"
        },
        "Description": {
          "type": "string",
          "value": "string"
        },
        "DirectoryAlias": {
          "type": "string",
          "value": "string"
        },
        "Domain": {
          "type": "string",
          "value": "string"
        },
        "Mail": {
          "type": "string",
          "value": "string"
        },
        "PUID": {
          "type": "string",
          "value": "string"
        },
        "SchemaClassName": {
          "type": "string",
          "value": "string"
        },
        "SpecialType": {
          "type": "string",
          "value": "string"
        },
        "http://schemas.microsoft.com/identity/claims/objectidentifier": {
          "type": "string",
          "value": "string"
        }
      },
      "providerDisplayName": "string",
      "resourceVersion": 0,
      "subjectDescriptor": "string"
    }
  ]
}

**Comment by js9331** [comment] 2021-08-06 14:00
> The specific offending YAML in the custom connector which needs to be removed looks like the following
...
> It will be resolved in the next release, but if you want to try removing it to get rid of the schema warning give it a try. I'm reasonably certain it's a red herring though since your calls from the test tab are working.

@mikefactorial confirming your thinking that it was a red herring - applying the fix to the definition did fix the validation error in the custom connector definition screen, but still getting the same error in app 😄

**Comment by js9331** [comment] 2021-08-06 17:24
@devkeydet I was able to review the policies on the custom connector in my installation - mine did not have the problem reported by @dylanhaskins above in his installation (also, validated against the Azure DevOps API documentation, and looks like correct urls configured for each method). However, I did try to go look at the coding inside the Canvas app since the connector is testing/validating succesfully - and I get this error when I try to open the app for edit:
first I am prompted to connect to the connector again (even though a connection already exists):
![image](https://user-images.githubusercontent.com/35241782/128548679-f46258f9-0de3-490b-939a-7c0e21d08180.png)

After clicking the sign in button (in same user context as already created connection) I get the following error:
![image](https://user-images.githubusercontent.com/35241782/128548834-e2177438-f731-4497-b70c-dbf5464be870.png)

I'm going to report this on my Microsoft ticket as well in case this is somehow more platform related or something.

**Comment by mikefactorial** [comment] 2021-09-22 14:59
@js9331 This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.

**Closed by mikefactorial** 2021-09-22 14:59 UTC
Labels: alm-accelerator, vnext
