### ISSUE TITLE
[CoE Starter Kit - BUG] Audit log 2.4 Won't Uninstall

### ISSUE THREAD

**Issue by lwarebmw** [microsoft/coe-starter-kit#2499] opened 2022-04-18 20:52 UTC
### Describe the issue

When I attempted to update my COE audit log component from 2.4 to 2.6 it failed the upgrade. I am unable to delete the 2.4 version due to connection references. I deleted the references but it still will not allow me to delete this component to complete the upgrade.

### Expected Behavior

Expected deletion of old compenent upon upgrade

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

Child Admin | Sync Logs

### Steps To Reproduce

1. In my COE environment
2. Attempt to delete or upgrade the component

**Comment by Jenefer-Monroe** [comment] 2022-04-20 09:34
I'm afraid we cannot assist with upgrade problems of this age. We recommend upgrading at least every 3 months, see https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades
 
However I do have two thoughts for you that I hope help. First of all, do you have a more current version of Core on place? Upgrades should always begin with Core. 

If so, then an overwrite install might help if the issue is just Audit Logs

Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by Jenefer-Monroe** [comment] 2022-04-25 20:04
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-04-25 20:04 UTC
Labels: bug, coe-starter-kit
