### ISSUE TITLE
[ALM Accelerator - Feature]: Setup new Solution Branches / Overview from Azure DevOps Projects - Preview

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#3866] opened 2022-10-05 19:09 UTC
### Is your feature request related to a problem? Please describe.

I want to see and setup new solution branches for my solution repository in Azure DevOps Projects - Preview.

![image](https://user-images.githubusercontent.com/15800069/194142344-f0818243-c075-4f60-9150-1a9745293dcc.png)

### Describe the solution you'd like

1) Repository Solutions are show in Azure DevOps Projects - Preview
1) Setup of a new Solution Branch including the pipelines is possible from Azure DevOps Projects - Preview

**Comment by mikefactorial** [comment] 2022-10-05 19:23
I'm going to defer to @jenschristianschroder on this one.

**Comment by jenschristianschroder** [comment] 2022-10-07 12:42
Hi @megel, Thanks for your feedback!

On this one I think what you suggest would be a duplicate of the functionality we have on first commit of a solution into a project. 
That process will automatically create the solution branch and deployment pipelines. 

Would you rather have that functionality from the admin app or do you see a need for it in both admin app and canvas app?

**Comment by megel** [comment] 2022-10-07 13:22
@jenschristianschroder: You mean, the first commit from AA4PP canvas app creates automatically the solution branch and add the pipelines? I didn't know that this is possible 🤯 - I have everytime used the CoE CLI to setup the branch.... let me check...

**Comment by jenschristianschroder** [comment] 2022-10-07 14:45
Let us know how it goes :)

**Comment by megel** [comment] 2022-10-07 20:27
WOW didn't know about this amazing feature! Extremely cool - worked without any problems:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/15800069/194647297-439f08c5-5977-481f-a9e8-69bc4e3cba54.png">

@jenschristianschroder U are the hero and I'm...
![IAmNotWorthyRespectGIF](https://user-images.githubusercontent.com/15800069/194646997-e6f668d5-a305-446b-a461-c97c6326163c.gif)

**Closed** 2022-10-07 20:27 UTC
Labels: enhancement, alm-accelerator
