### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Check Deleted (Custom Connectors) and Sync Template v3 (custom connectors) failing invalid response from API 'powerappsforappmakers'

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#5615] opened 2023-05-24 10:06 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have recently started to receive an error from the flow runs across nearly all environments for the CLEANUP HELPER - Check Deleted (Custom Connectors) and Sync Template v3 (custom connectors) flow. The issue happens at the 'Get Custom Connectors and store them in CoE CDS Entity' scope at the 'Get Connectors' action. The error below is received:

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/93/properties/connectionParameters/username/uiDefinition/constraints/clearText' to be of type 'Boolean' but is of type 'String'.'

<img width="292" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/78e95564-6961-4205-bac5-bcf017f7355e">

### Expected Behavior

Get connectors for the environment within the filter query

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment] 2023-05-24 10:54
It looks like you've raised this twice (also #5616), but it's also a duplicate of #5580. I'll close this as duplicate, and you can add further comments to  #5580 so we can track this in one place.

**Closed by manuelap-msft** 2023-05-24 10:54 UTC
Labels: bug, coe-starter-kit
