### ISSUE TITLE
Can I use the CoE Starter Kit to delete or quarantine apps using the UI?

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8863] opened 2024-08-27 06:09 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have three questions.

①Can the content here be the same in a CoE Power BI dashboard?
[Process description](https://learn.microsoft.com/en-us/power-platform/guidance/coe/example-processes#process-description)

②Can the content here do the same in the UI?
[Process description](https://learn.microsoft.com/en-us/power-platform/guidance/coe/example-processes#process-description)

③I'm sorry if it's mentioned in the documentation.
Do I need a paid license to use the CoE Power BI dashboard?
Can I use just a free license?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Tomozo-No1** [comment] 2024-08-27 06:43
I have an additional question
Can I use the UI to do the following?

・ Is it possible to perform an audit of the application on a specified date / under specified conditions?

・ Is it possible to notify the app owner by e-mail for an app that has been audited?

・ Can the app owner check the relevant app at the link in the email and request rule application or exemption?

・ Apps that have become regular conditions or apps that have been requested to be excluded from the audit due to the response of the app owner

・ As a result of the audit, the application that is judged to be unnecessary will be deleted and the owner will be notified of the result.

・ Whether the processing status and processing results can be confirmed

**Comment by Jenefer-Monroe** [comment] 2024-08-27 13:03
Hello I'm a little lost in what UX you are referencing. 

Today the quarantine happens automatically if they ignore the compliance requests via this system: [Set up app quarantine components](https://learn.microsoft.com/power-platform/guidance/coe/setup-quarantine-components)

Then in the UX you can also force an app into quarantine using the Power Platform Admin View: 
![image](https://github.com/user-attachments/assets/272d1d6d-d6ef-4ea0-b2a8-632b43507d96)

**Comment by Jenefer-Monroe** [comment] 2024-08-27 13:08
For your other questions

## Is it possible to perform an audit of the application on a specified date / under specified conditions?
No we do not have any app specific settings here other than excusing them.

## Is it possible to notify the app owner by e-mail for an app that has been audited?
If by audited, you mean you have requested they enter the information in the app, then yes that is one of the flows you see in the setup.

## Can the app owner check the relevant app at the link in the email and request rule application or exemption?
Yes that is what they will need to do is follow that link and fill out the details. You as the admin can read their response and decide if you want to mark the app as ok. 

## Apps that have become regular conditions or apps that have been requested to be excluded from the audit due to the response of the app owner

## As a result of the audit, the application that is judged to be unnecessary will be deleted and the owner will be notified of the result.
No we do not have any delete operation in conjunction to this work. 
You as an admin can approve their response or reject. If you reject you can quarantine it as shown above or delete it if you want in that same UX (just to the left of quarantine) but we do not delete it in our processes

## Whether the processing status and processing results can be confirmed
I'm not sure what you mean by this.

**Comment by Jenefer-Monroe** [comment] 2024-09-02 22:26
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-09-02 22:26 UTC
Labels: question, coe-starter-kit
