### ISSUE TITLE
Delete-unmanaged pipeline fails but still deletes solution

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#289] opened 2021-05-05 13:52 UTC
**Describe the bug**
When deleting a solution via the delete-unmanaged pipeline, if a user has a canvas app in said solution open for edit, the pipeline fails on import of managed version of solution.
Result is that solution "container" is deleted but assets remain in environment

**To Reproduce**
1. Open canvas app in solution for edit
2. Click delete solution in AA4AM app for the specific solution
3. The delete-unmanaged pipeline will fail
4. Solution "container" is deleted from environment but all assets remain in environment

**Expected behavior**
Pipeline will fail and solution and all assets remain in environment

**Screenshots**
![image](https://user-images.githubusercontent.com/24893229/117151738-a690e200-adb9-11eb-824a-06c0589f73bf.png)

**Comment by devkeydet** [comment] 2021-05-06 10:22
It's not possible to achieve the expected behavior.  To convert unmanaged components to managed, we must delete the unmanaged solution container.  This will leave the environment in a state where the unmanaged solution components are still there, but the unmanaged container is not.  Recreating the state of the unmanaged solution would be complex.  One way would be to export the unmanaged solution as well, then try to re-import on error.  We can't re-import the unmanaged solution because you would get the same error.  Another would be to get a list of all the components in the solution using the Dataverse API, then programmatically creating a new unmanaged solution with the same name, then programmatically adding the solution components back.  I don't think that's the way to go.  Instead, I think we should introduce a manual intervention step to the pipeline:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml
https://blog.johnfolberth.com/manual-intervention-task-azure-devops-yaml-pipelines/  
By doing so, the user can address what caused the import to fail (locked canvas in your case), then the pipeline can try again.

**Comment by devkeydet** [comment] 2021-05-06 16:16
Manual intervention task wasn't the way to go either.  Moving to an approach where we split the pipeline across two stages/jobs.  The second stage will start with import.  If import fails, user can address what's causing the failure, then rerun the second stage.

**Closed** 2021-05-06 17:25 UTC
Labels: alm-accelerator, bug
