### ISSUE TITLE
[CoE Starter Kit - BUG] Frequent failures on Admin | Sync Template v3 (PVA)

### ISSUE THREAD

**Issue by yingying96** [microsoft/coe-starter-kit#2585] opened 2022-04-28 07:04 UTC
### Describe the issue

We are seeing some frequent failures on our admin sync template v3 for PVA flow.

![image](https://user-images.githubusercontent.com/19566726/165695718-4efebcbb-af87-4d8d-b073-556610d05a6a.png)

![image](https://user-images.githubusercontent.com/19566726/165696045-24fcf294-5fd2-45d3-9e74-ba6daafef984.png)

### Expected Behavior

Flow completed successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

Turn on the core components - Admin | Sync Template v3 (PVA)

**Comment by Jenefer-Monroe** [comment] 2022-04-28 12:25
This one is known and fixed for May. https://github.com/microsoft/coe-starter-kit/issues/2402

Duplicate of #2402

**Closed by Jenefer-Monroe** 2022-04-28 12:25 UTC
Labels: bug, coe-starter-kit
