### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION

### ISSUE THREAD

**Issue by fosttj** [microsoft/coe-starter-kit#5774] opened 2023-06-09 18:23 UTC
### What is your question?

I am using the ALM Accelerator for Power Platform canvas app in Azure GCC and I select my dev environment and then select Open Solution to edit my solution the URL defaults to the Commercial URL (https://make.powerapps.com/environments) and not the GCC URL (https://make.gov.powerapps.us/environments).  Is there a location where I can change this value to default to the GCC path?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230517.1

**Comment by mikefactorial** [comment] 2023-06-09 18:29
@fosttj this is a known issue. You would need to edit the canvas app to change the url. Closing as duplicate of #5370

**Closed by mikefactorial** 2023-06-09 18:29 UTC
Labels: question, alm-accelerator

**Comment by fosttj** [comment] 2023-06-09 18:33
Could you please provide the location in the canvas app to change the url?
