### ISSUE TITLE
[CoE Starter Kit - BUG] August version for Power BI report error: column 'admin_recordinguidasstring' contains blank values

### ISSUE THREAD

**Issue by KiraXie2** [microsoft/coe-starter-kit#3335] opened 2022-08-02 10:54 UTC
### Describe the issue

When trying to install the August version for "Production_CoEDashboard_August2022" pbit, receiving the error below:
![image](https://user-images.githubusercontent.com/108067225/182356257-6de7fba8-0fac-4dff-8391-fdccb3dac203.png)

### Expected Behavior

Successfully get the "Production_CoEDashboard_August2022" pbit file published to PBI online.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Not app or flow; only PBIT file

### Steps To Reproduce

1. Open PBI Desktop
2. File > Import > Power BI template > Production_CoEDashboard_August2022
3. OrgUrl: *********
4. sign in with the correct user account multiple times
5. error occurs

July version for this report has been published and refreshed successfully multiple times. But today I received an error notification email as below:
![image](https://user-images.githubusercontent.com/108067225/182357733-43bb97c1-c031-4bbe-9843-650ff08b1d9b.png)

**Comment by Jenefer-Monroe** [comment] 2022-08-02 13:48
Thanks for posting, we are re-shipping the PBI to remove this alt key. Details in #3318 
Here they are ahead of releasing them, in case you would like an early copy: [August PBITs with alt key removed.zip](https://github.com/microsoft/coe-starter-kit/files/9242700/August.PBITs.with.alt.key.removed.zip)

I'll close this as a dupe of that.

**Closed by Jenefer-Monroe** 2022-08-02 13:48 UTC
Labels: bug, coe-starter-kit

**Comment by manuelap-msft** [comment] 2022-08-03 08:39
We have re-released the PBIT files to address #3322 and #3318. They're available when you re-download https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-August2022/CoEStarterKit.zip
