### ISSUE TITLE
[CoE Starter Kit - BUG] Fail to update derived owner to creator when creator not in maker table. - Admin | Sync Template v3 (Flows)

### ISSUE THREAD

**Issue by poi-radvine** [microsoft/coe-starter-kit#4648] opened 2023-01-23 08:57 UTC
### Describe the issue

We set up our CoE newly because of previous errors that could not be resolved (System tables were missing).
Upon reinitialization of the flow/app/maker tables we encountered many (45) errors always on the app or flows with orphaned owners.
The Flow Admin | Sync Template v3 is crashing and cannot continue hence the derived owner cannot be found/set.

I found a copy of this error already in March 22, but it was closed hence nobody followed up to it and provided error details.

### Expected Behavior

The inventory components should also list the abandoned/orphaned flows, even if the original or derived owner cannot be found.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Get a flow with a already disabled AND deleted owner and try to runt he Sync Flow, that has this flow not yet in the inventory.

**Comment by poi-radvine** [comment] 2023-01-23 09:08
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/88713407/214001841-f1b46744-8ce8-4304-8fc8-718388899f5a.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/88713407/214001938-f77a393d-aabe-45e4-8cd4-8b718b8f67ef.png">

`{
  "error": {
    "code": "0x80040217",
    "message": "admin_Maker With Id = 75591fc4-154e-4b6d-a820-77a55e29170a Does Not Exist",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_Maker With Id = 75591fc4-154e-4b6d-a820-77a55e29170a Does Not Exist"
  }
}`

**Comment by poi-radvine** [comment] 2023-01-23 09:10
`FlowName         : 09594847-90b4-d48f-c5d0-da3d32f80f22
Enabled          : False
DisplayName      : CloudFlow_RecordatorioEvaluacion
UserType         : Owner
CreatedTime      : 2022-02-14T20:47:23Z
CreatedBy        : @{tenantId=0f6f68be-4ef2-465a-986b-eb9a250d9789; objectId=75591fc4-154e-4b6d-a820-77a55e29170a;
                   userId=75591fc4-154e-4b6d-a820-77a55e29170a; userType=ActiveDirectory}
LastModifiedTime : 2023-01-17T16:33:36Z
EnvironmentName  : Default-0f6f68be-4ef2-465a-986b-eb9a250d9789
Internal         : @{name=09594847-90b4-d48f-c5d0-da3d32f80f22; id=/providers/Microsoft.ProcessSimple/environments/Defa
                   ult-0f6f68be-4ef2-465a-986b-eb9a250d9789/flows/09594847-90b4-d48f-c5d0-da3d32f80f22;
                   type=Microsoft.ProcessSimple/environments/flows; properties=}
`

The Flow cannot be found neither through Admin Center -> Environments -> Resources, nor the CoE tables.

**Comment by Jenefer-Monroe** [comment] 2023-01-23 11:03
Duplicate of https://github.com/microsoft/coe-starter-kit/issues/4502, fixed for Feb. Thank you for posting.

**Closed by Jenefer-Monroe** 2023-01-23 11:03 UTC
Labels: bug, coe-starter-kit

**Comment by poi-radvine** [comment] 2023-01-23 11:43
Sorry, but this is the lastest version, now Solution Layers, newly installed in a new environment.
<img width="942" alt="image" src="https://user-images.githubusercontent.com/88713407/214031387-c25d0ebe-6ce8-470b-bea3-22ac62324594.png">

![image](https://user-images.githubusercontent.com/88713407/214031411-d74fc8e3-a96a-433d-bcbe-204116db9da4.png)


And the value is set to True, not to the parameter true

**Comment by Jenefer-Monroe** [comment] 2023-01-23 11:46
Correct, this is local fixed for the next release in Feb. 
Please see https://github.com/microsoft/coe-starter-kit/issues/4502#issuecomment-1367659327 for how to local fix while you await release.
