### ISSUE TITLE
[CoE Starter Kit - BUG] Center of Excellence deletes and recreates records

### ISSUE THREAD

**Issue by mrlksae** [microsoft/coe-starter-kit#3526] opened 2022-08-26 08:50 UTC
### Describe the issue

Hello everyone,

We use the Center of Excellence mainly for governance purposes. The main app we use is the Developer Compliance App. We made a copy and adjusted it a little to make it fit to our needs. 

However, after some time a user complained that his entries were deleted also the attachments of the records.

An investigation showed that the records of his flows were deleted and newly created in the Flow table. They were probably deleted by the flow CLEANUP HELPER - Check Deleted (Cloud Flows). 

What we did so far:

- Investigation of several flows to check which one is the deleting flow

- Change the environment variable to prevent the flow to delete the records from the Flow table -> worked

- Search for similarities of deleted and still existing flow records -> Found none yet (The records of the previous mentioned user are still there) 

Do you have any idea?

Best regards,

Matthias

### Expected Behavior

Records that were already crawled and are not deleted should stay in the dataverse tables.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Cloud Flows) and Developer Compliance Center

### Steps To Reproduce

CoE flows crawled through all environments and added the data of the flows to the flows table.
We made a copy of the  Developer Compliance Center app and adjusted it.
Users entered data in Developer Compliance Center app for his flows.
CLEANUP HELPER - Check Deleted (Cloud Flows) ran and deleted flow records in flows table despite the flows being still there and active. 
The crawler flow created new records for the same flows that were previously deleted. Therefore, it looks like that the data the user entered were deleted but new records were created. During this time the flows weren't changed.

**Comment by Jenefer-Monroe** [comment] 2022-08-26 14:09
Can you please tell me if the account you have set up and running the flows in the CoE kit are given their licenses and roles via PIM?

**Comment by mrlksae** [comment] 2022-08-29 12:10
Thanks for your reply!

No, we did not use PIM. 
We use a service user who got his roles and licences via an AAD Security Group. His AAD role is Power Platform Administrator. His environment role is System Administrator.

**Comment by Jenefer-Monroe** [comment] 2022-08-29 14:21
Since I dont repro, we will need you to walk through to find the cause here. 

1. Get the flow of interests ID and Environment, and make sure the flow is not marked as Deleted
- find the flow in the new table UX as shown here and make sure its not marked as deleted
![image](https://user-images.githubusercontent.com/89584709/187219605-d0f3b08d-4724-4f7c-bda3-2b9ddc485457.png)
- find the enviornment of the flow in the same way and get its GUID and Name. Note for most enviroments these are the same value
![image](https://user-images.githubusercontent.com/89584709/187220665-4a360c1c-fc81-4130-9c75-5f6917a372c6.png)

2. Now go run the **_CLEANUP HELPER - Check Deleted (Cloud Flows)_** flow as shown here. Be sure to have **_CheckIfDeleted_** to true and **_DeleteFromCoE_** as false.
![image](https://user-images.githubusercontent.com/89584709/187221428-f7ef8690-5c1b-4137-ba99-17baca189f89.png)

3. When the flow is complete, find the flow of interest being returned here, and note its index (ex is it the 3rd in the list). Then go to that iteration and see if its returned.
![image](https://user-images.githubusercontent.com/89584709/187222478-0dfd6fcb-5202-44b2-952a-a78ecf5e9942.png)
![image](https://user-images.githubusercontent.com/89584709/187223245-acbade1e-1de9-4eec-9d74-3f6fdf4f61d9.png)

**Comment by Jenefer-Monroe** [comment] 2022-09-06 12:40
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-09-06 12:40 UTC
Labels: bug, coe-starter-kit
