### ISSUE TITLE
Upgrade issue from Core Components 2.1.7 to 2.2.20210707.3

### ISSUE THREAD

**Issue by jefmeyer** [microsoft/coe-starter-kit#885] opened 2021-07-21 12:24 UTC
### Describe the issue

We're upgrading from 2.1.7 (June) to 2.2.20210707.3 (July) of the CoE and the Core Components are failing to uninstall the 2.1.7 with the following error:

Solution dependencies exist, cannot uninstall. DependencyCount : 9 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: 49b91242-d737-471d-bbcb-394d5ecf0e8a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Start Approval for Flows), Id: 7e68d839-0556-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: 49b91242-d737-471d-bbcb-394d5ecf0e8a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Clean Up and Delete), Id: 78466552-7e56-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEAuditConnection, Id: bbced732-7ae8-4bbf-ad8a-406cf1bd982d, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEAuditConnection, Id: f45bc61b-395f-459a-954b-799fc127c647, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: 935ce54a-edc0-439a-be18-944ec3115adb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: 935ce54a-edc0-439a-be18-944ec3115adb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Check Approval), Id: 6c0522f0-6256-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEv3SyncTemplatesUsers, Id: ed4bd1e7-7551-4dec-bffb-a90f7fedc36c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Start Approval for Flows), Id: 7e68d839-0556-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 5c0e9e81-4e42-45e4-977a-bf064e8bbef4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Start Approval for Apps), Id: d740e841-7057-eb11-a812-000d3a9964a5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 5c0e9e81-4e42-45e4-977a-bf064e8bbef4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Clean Up and Delete), Id: 78466552-7e56-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

### Expected Behavior

2.1.7 should uninstall

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Core Components

### Steps To Reproduce

1. Upgraded May CoE version to June release
2. Attempt to upgrade June release to July release, issue occurs while applying the Core update

**Comment by medicineshow** [comment] 2021-07-21 12:32
I have experienced similar issues where it states it cannot uninstall because of dependencies.

**Comment by jefmeyer** [comment] 2021-07-21 12:38
Were you able to find a workaround?  Right now I have 2.1.70 and 2.2.20210707.3 of the Core Components installed.

**Comment by JeneferM-MSFT** [comment] 2021-07-21 13:02
Duplicate of #779 

Hello, as discussed in issue #779 , please use **Update** instead of Upgrade during the Import. This should resolve the dependency issues. 

Thank you

**Closed by JeneferM-MSFT** 2021-07-21 13:02 UTC
Labels: coe-starter-kit

**Comment by jefmeyer** [comment] 2021-07-21 13:08
Thanks Jenefer.  Do I need to delete the 2.2.20210707.3 version of the Core before performing the Update?

**Comment by JeneferM-MSFT** [comment] 2021-07-21 13:11
You should not need to delete anything.

**Comment by medicineshow** [comment] 2021-07-22 15:23
Just to note that in the documentation here:
https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup.md#installing-updates

it still says to use Upgrade. This should be updated.

**Comment by JeneferM-MSFT** [comment] 2021-07-22 15:26
correct. upgrade is the normal path. there was a bug that made us force via update

**Comment by medicineshow** [comment] 2021-07-23 07:59
Thanks for that. I am currently documenting how to upgrade the CoE for our IT department. Is there somewhere where i can reference this information so that in future they can check to see if this bug is fixed and which path to actually use?
