### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why can't I export a table of PowerAppsApps

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8755] opened 2024-08-05 04:39 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello
I would like to know why I can't export tables in PowerAppsAppsn.
The error details are as shown in the attached file.
Please let me know if you understand.
<img width="813" alt="Appsデータエクスポート" src="https://github.com/user-attachments/assets/51421beb-53cf-4925-a3f7-fae956df94ac">

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/6

### What method are you using to get inventory and telemetry?

None

**Comment by ValiPrk** [comment] 2024-08-05 06:52
Hello,

I have the same issue, I cannot export to excel the PowerApps Apps section, the Flow section works fine, I also checked with the developer tools and I saw the "400" code when trying to reach the API.
@Tomozo-No1, sorry that I reply on your open topic, but I did not want to open a separate one for the same issue.
@ Microsoft team -> thank you for your reply on this matter.

Valentin

**Comment by Jenefer-Monroe** [comment] 2024-08-05 12:47
Hello. I'm afraid this is a product support question and not a question for the kit. 
Here is an article on how to [open table data in Excel](https://learn.microsoft.com/power-apps/maker/data-platform/data-platform-excel-addin)

Here are the [troubleshooting tips](https://learn.microsoft.com/power-apps/maker/data-platform/data-platform-excel-addin#troubleshooting) from that article.

**Comment by ValiPrk** [comment] 2024-08-05 12:59
Hi, I'm talking about the fact that when going to the "PowerApps Apps" section of the PowerPlatform Admin view and trying to export to Excel, it won't work.
<img width="1169" alt="Export to excel" src="https://github.com/user-attachments/assets/d769d9e9-ad80-43cc-bb56-21c966c2730a">
<img width="277" alt="Error" src="https://github.com/user-attachments/assets/88d7808f-4f73-41fa-a543-8ccd6f484c5d">

**Comment by ValiPrk** [comment] 2024-08-06 06:32
Hello,

I tried also the Dynamic Export and I have the same issue, see attached screenshot. From what I see, the API seems to cause the issue. In this case should I open a ticket to Microsoft or you can offer support here? 
![Uploading Dynamic export.png…]()

**Comment by ValiPrk** [comment] 2024-08-06 06:38
I also saw that Microsoft has some issues with the "Microsoft Graph API" that they are working on, can they maybe cause this? MO848126 -> in the health center

**Comment by Jenefer-Monroe** [comment] 2024-08-06 12:36
Sorry I'm just not sure. I tried to do a little searching for this and I'm not finding what could be the cause. 
You can try doing this on some other non-CoE tables and in other environments. See if you repro there too. 
Or you can try the [Excel add in](https://learn.microsoft.com/power-apps/maker/data-platform/data-platform-excel-addin)

**Comment by ValiPrk** [comment] 2024-08-08 05:11
Hi, I further investigated and it seems to be only for a particular view, the other ones are working fine (I tried it with the "All Apps" view and could download it without any problems) and can be downloaded, it seems very odd
Also, I tried to select only one column "App ID" when exporting to Dynamic worksheet and still doesn't work...
Do you have any other ideas?

**Comment by Jenefer-Monroe** [comment] 2024-08-08 16:52
This does work for me so I dont think the view is corrupt. And PACatalogList is not one of our views as far as I casn tell. The "App Catalog Apps" view does work for me as well. 
![image](https://github.com/user-attachments/assets/55008b0e-eccb-419f-abf5-9d582cf8a55e)

**Comment by ValiPrk** [comment] 2024-08-09 06:21
Hello,

These also work for me, is there any chance that I can create a new view with the same settings? Do you have some guidance for this type of action?
Thank you very much for your reply!

**Comment by fannazephyr** [comment] 2024-08-13 11:50
i used it in Play mode instead then i was able to export

**Comment by Jenefer-Monroe** [comment] 2024-08-14 13:15
Closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-08-14 13:15 UTC
Labels: question, coe-starter-kit
