### ISSUE TITLE
Error updating the CoE

### ISSUE THREAD

**Issue by send2mark** [microsoft/coe-starter-kit#7079] opened 2023-11-13 02:33 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Every time I try to update the CoE kit I get the following error.

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: {"error":{"code":"CannotDeleteApiDueToExistingConnections","message":"The custom connector admin-5foffice-20365-20management-20api-5fb280e9a44edb5141 cannot be deleted because there are connections associated with this api."}}.

When I looked into the history logs this is what I get.
{"error":{"code":"CannotDeleteApiDueToExistingConnections","message":"The custom connector admin-5foffice-20365-20management-20api-5fb280e9a44edb5141 cannot be deleted because there are connections associated with this api."}}

I have tried deleting it, but it says that it is shared with another connector. I can't seem to find what that would be.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#828

**Comment by A-Demir-ilx** [comment] 2023-11-13 07:01
@Jenefer-Monroe I can't import the core solution via make.powerapps.com. I am getting the error below. This error appears once I select the solution in the import view and then click on next. Normally, the environment variables needs to be appear.

![afbeelding](https://github.com/microsoft/coe-starter-kit/assets/96475793/67302fcf-0e22-4260-add5-2ff042da6c02)

**Comment by Titoleto** [comment] 2023-11-13 07:56
> @Jenefer-Monroe I can't import the core solution via make.powerapps.com. I am getting the error below. This error appears once I select the solution in the import view and then click on next. Normally, the environment variables needs to be appear.
> 
> ![afbeelding](https://user-images.githubusercontent.com/96475793/282385603-67302fcf-0e22-4260-add5-2ff042da6c02.png)

We are getting the same error. @Jenefer-Monroe  In case it has something to do with it, the environment where we have installed the CoE Starter Kit is a European environment.

**Comment by ashes2076** [comment] 2023-11-13 08:21
> @Jenefer-Monroe I can't import the core solution via make.powerapps.com. I am getting the error below. This error appears once I select the solution in the import view and then click on next. Normally, the environment variables needs to be appear.
> 
> ![afbeelding](https://user-images.githubusercontent.com/96475793/282385603-67302fcf-0e22-4260-add5-2ff042da6c02.png)



> > @Jenefer-Monroe I can't import the core solution via make.powerapps.com. I am getting the error below. This error appears once I select the solution in the import view and then click on next. Normally, the environment variables needs to be appear.
> > ![afbeelding](https://user-images.githubusercontent.com/96475793/282385603-67302fcf-0e22-4260-add5-2ff042da6c02.png)
> 
> We are getting the same error. @Jenefer-Monroe In case it has something to do with it, the environment where we have installed the CoE Starter Kit is a European environment where we already have version 4.16 installed.

Hi guys, this issue as addressed last week to the CoE Team, and they did come up with a temporary solution...

Please refer here : [https://github.com/microsoft/coe-starter-kit/issues/7050]

**Comment by cyclingdaze** [comment] 2023-11-13 09:17
I also get the Disconnect message, been trying to update since Friday.  This message now all comes up if I try with the October install of core components, and also when adding the July one to a new test environment.

**Comment by Titoleto** [comment] 2023-11-13 09:25
> I also get the Disconnect message, been trying to update since Friday. This message now all comes up if I try with the October install of core components, and also when adding the July one to a new test environment.

I was able to install from the Classic UI. From make.powerapps.com click on the top right on Settings - Advance Settings, in the new window that opens, click on the top (to the right of Settings to open the drop-down) and in the Customization section, select the Solutions option.

**Comment by cyclingdaze** [comment] 2023-11-13 10:44
Hi @Titoleto  - that works, though it's left my environment in a bit of a funny state, with:

Centre of Excellence - Core Components (name: CentreOfExcellenceCoreComponents_Upgrade) v4.27 AND
Centre of Excellence - Core Components (name: CentreOfExcellenceCoreComponents) v4.8

Both now in the same environment.  I guess that's not right.

I can't remove 4.8, or apply upgrade.

**Comment by Jenefer-Monroe** [comment] 2023-11-13 12:24
For the disconnect issue:
Hello, this is a dupe of https://github.com/microsoft/coe-starter-kit/issues/7050 which is a product bug that impacts some subset of people. 
Product support was able to find a workaround which is explained here: Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240
I'll go ahead and close out as a dupe.

**Comment by Jenefer-Monroe** [comment] 2023-11-13 12:29
### For Original Poster and the Audit Logs upgrade failure:

Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018

We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 

If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use  powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by send2mark** [comment] 2023-11-13 22:38
I have tried running this (https://make.powerapps.com/environments/solutions?powerappsConnections.enableShowAllEnvVariablesOnImport=false), but when I go to import the solution I get "Sorry, there's been a disconnect." 
I am on 4.9 and have tried with 4.11.

**Comment by Jenefer-Monroe** [comment] 2023-11-13 23:23
I'm afraid this is a workaround given to us by product support and a product bug. If their workaround doesnt work you may need to contact them. 
You can also post this note directly in the https://github.com/microsoft/coe-starter-kit/issues/7050 and see if the support engineer is able to assist you there. I believe they may still be monitoring.

**Comment by send2mark** [comment] 2023-11-14 05:17
I rebooted my computer and it worked. I am good to go. Now I just need to figure out how to us a non-admin account due to PIM.

**Closed** 2023-11-20 11:20 UTC
Labels: duplicate, question, coe-starter-kit
