### ISSUE TITLE
 Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created is running from past 3 days

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#749] opened 2021-07-07 13:54 UTC
Hi Team,

'Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created' flow from CoE Governance Components solution is running from past 3 days. On the day of setup, it ran for 4 hrs and completed successfully but from the next day onwards it's been in running status and never completed.

Attached the screenshot for your reference.

Center of Excellence - Governance Components version  1.61
Center of Excellence - Core Components version 2.1.70

Thanks

![image](https://user-images.githubusercontent.com/33087528/124771090-7cde6d80-df58-11eb-98c0-f1504196b321.png)

**Comment by manuelap-msft** [comment] 2021-07-07 17:15
Hello,

when you raise issues, can you please make sure to use the CoE Starter Kit Bug Report template - this makes sure that the issue is labelled and assigned correctly, and you will get a faster response!
![image](https://user-images.githubusercontent.com/55705669/124801850-3afcf980-df4f-11eb-9a91-817c1f5fd100.png)

Thank you,
Manuela

**Comment by JeneferM-MSFT** [comment] 2021-07-07 18:51
Hello it is expected to run and wait for the person to respond. After 6 days of waiting if the person doesn't respond, the flow will end gracefully (aka not fail). 

So I think this is the expected behavior.

**Comment by challa85** [comment] 2021-07-08 06:47
Thanks for the update Jenefer. So ideally the flow will run every day and completes successfully if there are no justifications that need to submit and in case the justification is not provided the flow will run till the person submits justification or the flow will run for 6 days whichever is less. Could you please clarify if my understanding is correct?

**Comment by JeneferM-MSFT** [comment] 2021-07-08 13:32
This flow is triggered by an event not a timer, meaning its not a scheduled daily run.

This flow runs when a new teams environment is added to the inventory. So if 5 new teams environments were added that day, it will run 5 times. If none were added it will not run at all.
![image](https://user-images.githubusercontent.com/62659043/124929877-13914580-dfbe-11eb-893d-974ce3669ff7.png)

This is why it can wait for response, because each new teams environment has its own run. So if **_Jon Doe_** created a teams environment **_Junk Envt_**, it will get its own run of this flow when **_Junk Envt_** is added to the inventory. 

If **_Jon Doe_** responds to the teams card within 6 days, the flow will add his response to the Dataverse and complete 
If **_Jon Doe_** ignores the teams card complete, then after 6 days the flow will complete and the envt will be deleted later by another flow. 

Hope that makes sense.

**Comment by challa85** [comment] 2021-07-08 18:07
Thanks, Jenefer. Now it's clear but a final query. Does this flow trigger immediately whenever an environment is created or it will take some time to trigger? as we noticed that the flow got triggered almost an hour after we created the environment.

**Comment by JeneferM-MSFT** [comment] 2021-07-08 18:14
The trigger is when the environment is put into your CoE inventory not when they are created. 

Power Platform does not have triggers on its object so we cannot listen for environments actually being created. Instead we listed for them to be recorded into the CoE inventory. 

This recording into the inventory happens for enviroments via the **_Admin | Sync Template v3_** flow which runs daily by default.

**Comment by JeneferM-MSFT** [comment] 2021-07-12 18:10
closing out, no further action for toolkit

**Closed by JeneferM-MSFT** 2021-07-12 18:10 UTC
Labels: coe-starter-kit, governance-components, question
