### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template Sync v3 (PVA) failes repeatedly

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#2661] opened 2022-05-09 08:31 UTC
### Describe the issue

Hello, 

some of my customers flows fail repeatedlywith the same error multiple times a day. Sometimes the flow runs perfectly fine because it skips earlier in the flow. But most of the times the flow fails.

There are two bots in specific environments for testing purposes. But most environments don´t have a bot installed. Here are some of the messages of that flow.

![image](https://user-images.githubusercontent.com/87785803/167367794-bfd8f9a0-111e-4363-8b3d-38788b11b9d3.png)

![image](https://user-images.githubusercontent.com/87785803/167367745-28555be6-e4c9-4a16-9c18-6eecddaf28dd.png)

![image](https://user-images.githubusercontent.com/87785803/167368001-94a77d2e-879c-4116-b971-0b1f55601d7a.png)

![image](https://user-images.githubusercontent.com/87785803/167368444-bd2fc7ed-3e43-4146-81a2-dac1cd9857c0.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template Sync v3 (PVA)

**Comment by Jenefer-Monroe** [comment] 2022-05-09 08:46
Hello this was a regression caused by a product change. Fixed in the May release via https://github.com/microsoft/coe-starter-kit/issues/2402

Duplicate of #2402 

Thanks for using CoE

**Closed by Jenefer-Monroe** 2022-05-09 08:46 UTC
Labels: bug, coe-starter-kit
