### ISSUE TITLE
Fail to deploy Center of Excellence - Core Components - error note on a random object

### ISSUE THREAD

**Issue by vcontes** [microsoft/coe-starter-kit#8076] opened 2024-04-16 18:18 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am currently trying to upgrade the  Center of Excellence - Core Components version 4.17 tp version 4.29.
There is no unmanaged layer / customization.
I got the following message while installing : 
Import failed: Model-Driven App is missing required components uniquename : admin_PowerPlatformAdminView. Please include the App with required components.

### Expected Behavior

 Center of Excellence - Core Components version 4.29 installed 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

admin_PowerPlatformAdminView

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Import a Solution CenterofExcellenceCoreComponents_4.29_managed.zip
2. Click on next 
3. 
![image](https://github.com/microsoft/coe-starter-kit/assets/154508730/97e09c50-979b-4397-99af-6efa7750ca33)

4. Connections screen. Not need to re-establish them, clicking on Next
5. No update of environment variables
6. Finally click on import
7. Wait a long time and got the error

### Anything else?

--

AB#2914

**Comment by Jenefer-Monroe** [comment] 2024-04-16 20:37
Hello. That app is still in the solution. And we did test from that build. 

- Have you already re-tried? 
- Is the current install also managed?

Here is the app in the April build
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/56a82eaa-c927-4430-9242-06fb07638b1b)

**Comment by vcontes** [comment] 2024-04-16 20:53
CONFIDENTIAL & RESTRICTED

Yes the installed  solution is managed and I retried several times with the samedi error ...

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-04-16 21:05
I'm not sure what to say. That app is installed. 
There may be some intermittent import issue at play as I've seen a few other very strange error messages hitting people.
Perhaps try to upgrade to a 4.18 and see if you see the same error. Or upgrade another solution (ex creator kit) and see if that suceeds.

**Comment by vcontes** [comment] 2024-04-17 11:04
I just tried to install an earlier version and same issue. 
In that case, what could we do ? Do I have to delete and install the solution from scratch ?

**Comment by Jenefer-Monroe** [comment] 2024-04-17 12:34
Thank you for trying with an old build, that helps prove this as a product regression we need to chase. 
I dont think there is anything you can do right now besides help me debug. 
It appears to complain about random objects for different people. Some people are getting a random error about a flow and its a different flow each time they try. 
We'll use this as the main issue for getting to the bottom of this so I'll point others here for adding their notes.

Unfortunately I'm on vacation so just adding these notes before my family awakens, so need to find someone to own this in the team.

**Comment by Jenefer-Monroe** [comment] 2024-04-17 13:15
OK I just failed to upgrade as well, my error was a server time out error. Which I see sometimes on the uninstall and it goes away on its own, but this time it was on the import so it wont self repair 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a8abd288-4e2d-4eba-8036-b5cad113d65c)

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Code: InternalServerError Content: {"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: ''. Please see details.","details":[{"code":"ServerTimeout","message":"The request timed out. The tracking Id is 'ada2105e-5411-49d7-9508-ed5b4cc07251'."},{"code":"ServerTimeout","message":"The request timed out. The tracking Id is 'ada2105e-5411-49d7-9508-ed5b4cc07251'."}]}}

**Comment by Grant-Archibald-MS** [comment] 2024-04-17 21:50
Following up on thread. I was unable to reproduce the problem with the following:
1. Created environment of type Developer in Region United States
1. Install of release 4.17 in a new environment. Successful install
2. Upgrade from 4.17 to 4.19. Success upgrade

![image](https://github.com/microsoft/coe-starter-kit/assets/31553604/d74745b4-2e43-45cb-970d-cab18891a4f4)

**Comment by Grant-Archibald-MS** [comment] 2024-04-18 03:06
Adding to @Jenefer-Monroe comment. If others could confirm that this issues is occurring I was able to upgrade sucessfully

**Comment by Jenefer-Monroe** [comment] 2024-04-18 14:04
confirmed in my repro envt as well, this appears to be resolved now HURRAH

**Comment by bilodeauju** [comment] 2024-04-22 20:49
Hello, since Friday I am experiencing a somewhat similar error trying to upgrade from 4.22 to 4.29 (both managed solutions). There is no unmanaged layer / customization that I can see. I retried twice today, every time I get the following failure in the history : 

Error code 8004F01F
Exception message: Workflow uninstall: FAILURE, workflow id 04b5f2be-08f7-ec11-bb3d-000d3a10bc1d category ModernFlow name CLEANUP HELPER - Check Deleted (Solutions)

![CoEFailedUpgradeError](https://github.com/microsoft/coe-starter-kit/assets/81716086/3d1e792c-2150-47f3-9a4b-9e1736541ab8)

The log contains the following:
![CoEFailedUpgradeErrorlog](https://github.com/microsoft/coe-starter-kit/assets/81716086/a5ec407b-7e94-47b2-a50e-5710303e8692)

This seem to be the dependency it is referring to:
![CoEFailedUpgrade](https://github.com/microsoft/coe-starter-kit/assets/81716086/077ab158-a753-4a40-9d5b-30645544e58f)

I was able to upgrade from 4.22 to 4.29 in a sandbox environment on April 11th without any issues, so I'm not sure why it would be failing in this production environment. I will try to upgrade this environment to 4.23 instead and see if that goes through.

**Comment by Jenefer-Monroe** [comment] 2024-04-24 14:23
ok this new issue appears to be a separate one. And is covered by https://github.com/microsoft/coe-starter-kit/issues/8130
So I'll go ahead and close this one now as resolved.

**Closed by Jenefer-Monroe** 2024-04-24 14:23 UTC
Labels: bug, coe-starter-kit
