### ISSUE TITLE
Pull Request Set EnvironmentId failed

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#332] opened 2021-05-11 16:24 UTC
**Describe the bug**
When we create a pull request from the working branch to the v-next branch it fails at Set EnvironmentId. The pull request runs for validation.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/117850937-ca3da780-b253-11eb-88f4-8d313df762d2.png)

**Additional context**

**Comment by AkashPatel136** [comment] 2021-05-11 20:15
Hi @mikefactorial 

I have make sure all 4 things and are correct.

**Comment by devkeydet** [comment] 2021-05-12 10:50
At this point, it doesn't seem related to anything we can control, other than providing troubleshooting suggestions.  I agree with @mikefactorial that the most likely root cause is one of the things he's stated.  The best thing I can recommend to diagnose is to run Add-PowerAppsAccount from a PowerShell window on your desktop, using the values you have supplied for the variables.

Add-PowerAppsAccount -TenantID "use-your-tenant-id-value-here" -ApplicationId "use-your-client-id-value-here" -ClientSecret "use-your-secret-value-here"

If you get the same error, and you've validated everything @mikefactorial has suggested, then your best bet is to contact support through: https://admin.powerplatform.microsoft.com/support.  

If you don't get an error, then the most likely root cause is a typo in the values you've supplied for your variables.

**Comment by AkashPatel136** [comment] 2021-05-12 14:53
@mikefactorial 

Below is the API permission we have granted. 
![image](https://user-images.githubusercontent.com/75992078/117995745-9031db80-b30f-11eb-974e-dc4930584d4a.png)

We also tried what @devkeydet asked and we run the PowerShell command and for application id, we provided our canvas app id and it did throw the error message but it is different than what we saw in DevOps. 

![image](https://user-images.githubusercontent.com/75992078/117996612-4990b100-b310-11eb-9f14-994f1a5e8d8a.png)

**Comment by AkashPatel136** [comment] 2021-05-12 16:44
Hi @mikefactorial 

Just want to give an update is that I had to delete the ClientSecret and recreate the client secret and it worked perfectly fine. But 
now it throws another error message. 

![image](https://user-images.githubusercontent.com/75992078/118013146-cd9e6500-b31f-11eb-99a8-7b93697ceb54.png)

**Comment by mikefactorial** [comment] 2021-05-12 17:24
Hey @AkashPatel136 when you have a chance let's do a screenshare on Teams

**Comment by AkashPatel136** [comment] 2021-05-12 17:25
Hi @mikefactorial i am available now if you are available

**Comment by mikefactorial** [comment] 2021-05-12 18:02
Closing this issue. Environment was reset and needed to setup connections and app user again.

**Closed by mikefactorial** 2021-05-12 18:02 UTC
