### ISSUE TITLE
Export to Git failing

### ISSUE THREAD

**Issue by JakeStratton** [microsoft/coe-starter-kit#4021] opened 2022-10-21 20:50 UTC
suddenly we are getting the following error when running the "export_solution_to_git" pipeline on the "pac - Clone or Sync Solution" task:

Error: Cannot find required file 'D:\a\1\s\slp_LabSci\slp_LabSci\SolutionPackage\Other\Customizations.xml'.

any ideas on how to resolve this?

**Comment by sdhsynsci** [comment] 2022-10-24 16:21
We solved this my deleting the solution branch from AzDo and making a new commit from environment.

**Comment by mikefactorial** [comment] 2022-10-24 16:23
@JakeStratton this is due to a regression in PAC CLI introduced in 1.19.4. We released a hotfix for our pipelines to work around this issue here https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/CenterofExcellenceALMAccelerator-October2022-HF1

**Comment by dmcweeney** [comment] 2022-11-02 10:59
Got caught with this also! Thanks for the fix...

**Comment by trepaxrm** [comment] 2022-11-03 18:02
Hi i have got the same Error, but all my pipeline and COE ALM is update to november Release. is the hotFix present in the November release? if not what is the fix to apply, Thanks!

**Comment by mikefactorial** [comment] 2022-12-07 17:53
@trepaxrm the fix is in the November release and the December release that was released today. Closing this issue out as there's no more action required.

**Closed by mikefactorial** 2022-12-07 17:53 UTC
Labels: alm-accelerator
