### ISSUE TITLE
[CoE Starter Kit - BUG]: now data in shared with

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#569] opened 2021-06-03 18:03 UTC
Seems like we dont collect users that apps has been shared with. We have been running for some time but all apps are empty:

![image](https://user-images.githubusercontent.com/43033640/120691387-aeba6b00-c4a6-11eb-9dad-859185f394d6.png)

How can we troubleshoot this?

**Comment by manuelap-msft** [comment] 2021-06-03 19:14
Hello,

can you confirm the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) flow is turned on, and running without failures?

Thank you
Manuela

**Comment by tsegato** [comment] 2021-06-03 19:34
Are we talking core components? 
![image](https://user-images.githubusercontent.com/43033640/120701713-7d946780-c4b3-11eb-81dd-7372296b053c.png)

**Comment by manuelap-msft** [comment] 2021-06-03 19:37
Yes we are

**Comment by tsegato** [comment] 2021-06-03 19:38
I dont see that flow. See screenshot. Is it a version 9 feature?

**Comment by tsegato** [comment] 2021-06-03 19:39
Sorry foun dit. Looks like this is the problem. 
![image](https://user-images.githubusercontent.com/43033640/120702320-3a86c400-c4b4-11eb-8592-ee091322ec3a.png)

**Comment by tsegato** [comment] 2021-06-03 19:41
I get this error: Your flow could not turn on: CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With). Error: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_Environments_as_Admin' of type 'OpenApiConnection' at line '1' and column '1494' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

**Comment by manuelap-msft** [comment] 2021-06-03 19:50
Hello, 

all the flows have this pagination policy. This error indicates that you are using an insufficient license.
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

See here for the license types: https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles
And here for pagination limits: https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits

And hence our requirements for licenses. [What licenses do I need to run this solution?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-licenses-do-i-need-to-run-this-solution)

Duplicate of #476

**Closed by manuelap-msft** 2021-06-03 19:50 UTC
Labels: coe-starter-kit
