### ISSUE TITLE
[CoE Starter Kit - BUG] Error in Import

### ISSUE THREAD

**Issue by e110323** [microsoft/coe-starter-kit#9382] opened 2024-12-09 17:19 UTC
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I followed the update step by step until the step of importing the new solution, I tried to import the CoE Starter KIT directly, but this error ocurred:
 
**The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.**  
 
To try to get past this error, I unzipped the folder and tried to import one file at a time, and these were the results:
 
 
 
Admintaskanalyses: **Sucess**
 
Business_value_core: **Sucess**
 
BV-sample-data: Error - **The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.**  
 
CenterofExcellenceAuditComponents: **Sucess**
 
CenterofExcellenceCoreComponents: **Error - Falha na importação da solução "Center of Excellence - Core Components": ImportAsHolding failed with exception :The connectionreference(02934c32-46c2-4765-8da9-0752388feffc) component cannot be deleted because it is referenced by 16 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest.**
 
 
CenterofExcellenceInnovationBacklog: **Sucess**
 
CenterofExcellenceNurtureComponents: **Error - Need to update CenterofExcellenceCoreComponents beforehand**
 
Toollcons: **Error - The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.**
 
 

Best regards,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Starter Kit

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment] 2024-12-09 18:56
Hello you are correct, the download from here is a zip file containing many things including individual solution files. 
This is why one of the first things you need to do is extract the components. 
See [Import the core components solution](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#import-the-core-components-solution)
![Image](https://github.com/user-attachments/assets/c783f505-cc9c-426d-9a46-fd82dc572522)

Not everything in the zip file is a solution file though. BV-sample-data and Toollcons are not solution files. 
As you walk through all the setup instructions you will see reference to them. 
For example: [Set up Innovation Backlog component](https://learn.microsoft.com/power-platform/guidance/coe/setup-innovationbacklog)
![Image](https://github.com/user-attachments/assets/6843befd-5dc2-4c40-a193-8a10262b3653)

**Comment by Jenefer-Monroe** [comment] 2024-12-09 18:57
For your failure to upgrade Core, unfortunately you've hit a known product bug. I've paseted information about that below. 

## Product bug around connection reference upgrade
Unfortunately it looks like you've hit a product bug around upgrade. A few other people have hit this too. Please see https://github.com/microsoft/coe-starter-kit/issues/8466. 
### The connection
This is likely the legacy Dataverse connection that is at play, why it wont tell you the name I don’t know. 
But this is a connection that we have removed from the kit and that is causing issues in the product’s upgrade code.
### The likely issue
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 
### Find impacted flows
Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8186341-cf26-4710-aa3c-8b3e3bb9f2ea)
### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.
And another user has succeeded with this workaround. See https://github.com/microsoft/coe-starter-kit/issues/8466

**Comment by Jenefer-Monroe** [comment] 2024-12-17 13:12
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-12-17 13:12 UTC
Labels: bug, coe-starter-kit
