### ISSUE TITLE
[CoE Starter Kit - BUG]: issue title

### ISSUE THREAD

**Issue by dtsoden** [microsoft/coe-starter-kit#701] opened 2021-06-28 17:10 UTC
![error](https://user-images.githubusercontent.com/36846872/123676294-c10f9680-d811-11eb-82f8-8469175d5981.png)
**Describe the bug**
After making a theme and saving it, I can not publish it. The publish screen shows NO upload control, just getting your data as seen in the screenshot attached.

**Component (please tell us which flow or app you are experiencing issues with):**
Theming_1_2_managed.zip

**To Reproduce**
1. Make a theme
2. Save a Theme
3. Try to publish a theme
4. See missing controls to upload the phone and tablet files

**Expected behavior**
expect to see upload controls 

**Screenshots**
see attached

**Comment by dtsoden** [comment] 2021-06-28 17:11
Works the same in two environments, so not environmental as best as I can tell

**Comment by SPB21** [comment] 2021-07-28 12:25
@dtsoden please see a fix from @charrisonfuj - https://github.com/microsoft/coe-starter-kit/issues/553

**Comment by mikefactorial** [comment] 2021-08-03 14:20
Closing this for now duplicate of #402. Will update on that issue

**Closed as completed by mikefactorial** 2021-08-03 14:20 UTC
Labels: theming
