### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrading core resulted in dependencies on Audit Logs solution

### ISSUE THREAD

**Issue by welpculmsee** [microsoft/coe-starter-kit#803] opened 2021-07-09 05:47 UTC
### Describe the issue

Applied upgrade from July build and it fails with dependency issues. A dependency check shows connection refs required by the audit log solution. Not sure why a solution upgrade would result in this...

![image](https://user-images.githubusercontent.com/85979622/125029359-183c2380-e0bc-11eb-9022-d573b4f22b08.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.50.20210708.1

### What app or flow are you having the issue with?

NA

### Steps To Reproduce

Open solutions. 
Import new core solution.
Wait :-)

**Comment by welpculmsee** [comment] 2021-07-09 05:50
For reference the audit log solution has not been touched yet and is 1.3.6

**Comment by CarstenGrowth** [comment] 2021-07-09 06:30
I tried starting with the upgrade process on Audit-Log solution first, but failed with error message as well: https://github.com/microsoft/coe-starter-kit/issues/779
Seems there´s now a dependency on a dependency build-in that needs to be fixed regarding the connection references

**Comment by manuelap-msft** [comment] 2021-07-09 07:53
Hello,

as discussed offline, please try using **Update** instead of Upgrade during the Import. This should resolve the dependency issues. 

(Commenting here in case others experience the same issue)

Thank you
Manuela

**Comment by CarstenGrowth** [comment] 2021-07-09 09:21
When using Update - ensure to fix the connection on Office 365 Management API connector afterwards in your Audit Log solution

(Commenting here in case others follow the Update approach)

**Comment by HamishSheild** [comment] 2021-07-10 01:37
Hi team, I have also come across this issue.  I imported both the Core and Audit solutions via the make.powerapps.com UI and it imported the solutions as an update successfully but failed to upgrade.  It looks like the reason for this is because some of the connection references have changed in both the Core and Audit solutions and so when the solutions are trying to be upgraded the old solution cannot be removed because there are connection references in the old solution, that don't exist in the new solutions, that are currently being referenced by some of the flows.  I had to manually update the connection references in the affected flows (**[Child] Admin | Sync Logs** and **Admin | Sync Audit Logs**) to point to the new connection references in the July release solutions.  Then I was able to upgrade both solutions.

One thing that I have also noticed is that the Admin | Sync Audit Logs flow from the Audit solution references a legacy Dataverse connection reference in the Core solution - ideally the Audit solution would have its own connection reference for legacy Dataverse right?

Also, for reference, here are the error messages that I received....
```
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 
RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEAuditConnection, Id: fe376bdc-5656-45f0-a529-9046232f0bb5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 
RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEAuditConnection, Id: 0f394cfb-edf1-4dc1-834d-b945eea64c6e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 
RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: 6c3c36a3-edff-4dfa-89d5-fdc24ce37ef8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 
```


```
Solution "Center of Excellence - Audit Logs" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 
RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_faecd, Id: 0f207907-2efa-49b4-a21d-0992c66eecf0, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .
```

**Comment by manuelap-msft** [comment] 2021-07-12 08:22
Thanks for the detailed error analysis!

Part of the issue is unfortunately old (previous version) solutions, and not the new ones.

- In the previous version, we had cross-dependency of connection references, so a connection reference in Core was used in Audit Log and vice versa.
- With this version, we went to clean up all our connection references and created new ones that are just used in one solution
- An **Upgrade** tries to delete components removed from the solution during Import, which leads to the import issue. It can't delete the connection reference because it's used in another solution. 
- An **Update** does not delete components removed from the solution, so the Import succeeds with the old connection references left alone. If you update all solutions, it should clean up all connection references.
- We are just looking through this again to make sure it's all good and will likely re-ship today or tomorrow so might be worth waiting for that release. But you will still have to use Update instead of Upgrade if you are on an older version of the CoE Starter Kit.

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment] 2021-08-13 18:07
closing out now that we've moved on to August

**Closed by JeneferM-MSFT** 2021-08-13 18:07 UTC
Labels: coe-starter-kit
