### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#974] opened 2021-08-06 13:58 UTC
### Describe the issue

Starting around July 21 st the [Child] Admin | Sync Logs
Details flow is failing with error message Parse_JSON failed.

### Expected Behavior

Successful flow run

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.3.6

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs Details

### Anything else?

![image](https://user-images.githubusercontent.com/77410660/128521523-b8d7fc69-b771-4398-8ccb-bb699c10373a.png)

**Comment by JeneferM-MSFT** [comment] 2021-08-06 15:39
In the future please structure issues you post like #959 to which I will be duping your bug. 
Note that they provided a title and the error message received. 

That said, I believe you are experiencing the same issue, and the product changed what it sends in some situations slightly. 
Duplicate of #959 

Fixed for August. 
Thanks for using CoE

**Closed by JeneferM-MSFT** 2021-08-06 15:39 UTC
Labels: coe-starter-kit

**Comment by keharrin** [comment] 2021-08-06 15:50
Thanks Jenefer.  I will mark #959 as an example for future issues.  The resolution appears to have resolved this for us as well.
