### ISSUE TITLE
[CoE Starter Kit - BUG] Impossible installation of governance component in teams environment

### ISSUE THREAD

**Issue by tmycgn** [microsoft/coe-starter-kit#1018] opened 2021-08-12 13:51 UTC
### Describe the issue

When installing the CoE in a Team Environment, the installation of the Governance component does not work. According to documentation https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components the solution **CenterOfExcellenceAuditComponents_x_x_xx_managed.zip** should be imported. But when this is done, it expects an installed **CenterofExcellenceCoreComponents_x_x_xx_managed.zip** solution. For Team Environments, however, according to the documentation, the CenterofExcellenceCoreComponents**Teams**_x_x_xx_managed.zip solution should be installed in advance. Therefore an adapted solution CenterOfExcellenceAuditComponents**Teams**_x_x_xx_managed.zip seems to be missing. Also the screencaptures on the page show only the way over an own productive environment, but it is mentioned in the text that this works for productive and teams environment. What am I doing wrong?

### Expected Behavior

Expected according to documentation would be that the installation will work.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_2_1_managed.zip

### What app or flow are you having the issue with?

CenterofExcellenceAuditComponents_2_0_managed.zip

### Steps To Reproduce

Perform installation according to instructions within Teams Environment until attempting to install audit components.

### Anything else?

Log:
`[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceAuditComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required type=\"1\" schemaName=\"admin_archiveapproval\" displayName=\"Archive Approval \" solution=\"CenterofExcellenceCoreComponents (2.74)\" /><Dependent type=\"1\" schemaName=\"admin_archiveapproval\" displayName=\"Archive Approval \" /></MissingDependency><MissingDependency><Required type=\"9\" schemaName=\"admin_admin_archiveapproval_complete\" displayName=\"Local Enumeration\" solution=\"CenterofExcellenceCoreComponents (2.74)\" /><Dependent type=\"9\" schemaName=\"admin_admin_archiveapproval_complete\" displayName=\"Local Enumeration\" /></MissingDependency><MissingDependency><Required type=\"9\" schemaName=\"admin_archiveapproval_statecode\" displayName=\"Status\" solution=\"CenterofExcellenceCoreComponents (2.74)\" /><Dependent type=\"9\" schemaName=\"admin_archiveapproval_statecode\" displayName=\"Status\" /></MissingDependency><MissingDependency><Required type=\"9\" schemaName=\"admin_archiveapproval_statuscode\" displayName=\"Status Reason\" solution=\"CenterofExcellenceCoreComponents (2.74)\" /><Dependent type=\"9\" schemaName=\"admin_archiveapproval_statuscode\" displayName=\"Status Reason\" /></MissingDependency><MissingDependency><Required type=\"9\" schemaName=\"cr5d5_archivalitemtype\" displayName=\"Archival Item Type Options\" solution=\"CenterofExcellenceCoreComponents (2.74)\" /><Dependent type=\"2\" schemaName=\"cr5d5_archivalitemtype\" displayName=\"Archival Item Type\" parentSchemaName=\"admin_archiveapproval\" parentDisplayName=\"Archive Approval \" /></MissingDependency><MissingDependency><Required type=\"9\" schemaName=\"cr5d5_archivalitemtype\" displayName=\"Archival Item Type Options\" solution=\"CenterofExcellenceCoreComponents (2.74)\" /><Dependent type=\"9\" schemaName=\"cr5d5_archivalitemtype\" displayName=\"Archival Item Type Options\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]`

**Comment by manuelap-msft** [comment] 2021-08-12 14:02
Duplicate of #1012. We just fixed this and published a new release, you will have to download the latest version published today and re-install Core.

**Closed by manuelap-msft** 2021-08-12 14:02 UTC
Labels: coe-starter-kit
