### ISSUE TITLE
[ALM Accelerator - QUESTION] Conditional Access Policy

### ISSUE THREAD

**Issue by DazzHa** [microsoft/coe-starter-kit#6694] opened 2023-09-22 16:18 UTC
### What is your question?

Hi,

I have installed and configured the ALM Accelerator but I am having problems using the ALM Accelerator for Power Platform Administration App.

The first problem is every time I open the App it requests permission to use the CustomAzureDevOps connection.

The second problem is when selecting Projects the GetProjects and HasPermissions API's fail. I have gone into the custom connector to the Test page and tested the connector.
GetOrganizations and GetCurrentUserProfile work fine and return OK (200).
When I test GetProjects I get The requested operation is not allowed. (403). the body returned is:
{
  "$id": "1",
  "innerException": null,
  "message": "VS403463: The conditional access policy defined by your Azure Active Directory administrator has failed.",
  "typeName": "Microsoft.VisualStudio.Services.Common.VssServiceException, Microsoft.VisualStudio.Services.Common",
  "typeKey": "VssServiceException",
  "errorCode": 0,
  "eventId": 3000
}

We have tried to identify what policy is causing this without any success. I have successfully used the DevOps connector in other flows and can access DevOps without any problems.

I am hoping that you can provide some guidance or point us in the right direction to try and resolve this.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20230906.1

AB#574

**Comment by mikefactorial** [comment] 2023-10-05 19:08
@DazzHa it's difficult to know specifically what the issue is here without knowing what Azure Policies are in place. The only thing that stands out to me is that the specific Operations you mentioned as working, **GetOrganizations and GetCurrentUserProfile**, are associated with a Custom Connector policy that redirects the connector host to app.vssps.visualstdio.com rather than the default host of dev.azure.com. Is it possible that there's a policy in Azure that is blocking dev.azure.com specifically?


![Image](https://github.com/microsoft/coe-starter-kit/assets/42348035/150e2194-61bb-4f2d-8996-1c13bf5e0f09)

**Comment by RajeevPentyala** [comment] 2023-11-01 08:54
@dazzha Did you get a chance to check Mike's comment?

**Comment by DazzHa** [comment] 2023-11-02 09:55
@RajeevPentyala , @mikefactorial Our systems and networks people are doing some further investigation based on your feedback.  Currently they are looking into if a conditional forwarder is required. I will feedback any findings so that anyone encountering a similar issue can benefit.

**Comment by mikefactorial** [comment] 2023-11-13 12:59
@DazzHa any update here? Were you able to track down the issue?

**Comment by RajeevPentyala** [comment] 2023-11-20 12:18
@DazzHa Closing this for now. Please feel free to reach out if you need further assistance.

**Closed by RajeevPentyala** 2023-11-20 12:18 UTC
Labels: question, alm-accelerator

**Comment by DazzHa** [comment] 2023-12-14 19:39
@RajeevPentyala ,@mikefactorial We finally got to the bottom of the problem. We have a Conditional Access Policy to Block access from non-compliant devices and applies to all cloud apps and all users with some locations excluded. Adding my account to the exclusion list fixed the problem and few other issues I had with other Azure and M365 services.
I can now configure ALM Accelerator. 
Thanks.
