### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashboard - Apps Report

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2117] opened 2022-02-23 13:54 UTC
### Describe the issue

Hello Team,

After updating the data refresh with latest time by today, I see the Apps statistics in the Power BI Dashboard report is not aligned with the "PowerApps Apps" table.

For example, I get the following statistics from the PowerApps App table:

Total Apps = 2097

Undeleted apps = 1812 (admin_appdeleted = False)

Canvas Apps = 624

Model Driven Apps - 76

SP Apps - 1112

 

Now, if I look at Power BI Dashboard, I see below results:

Total No of Apps = 331

Canvas Apps = 113

Model Driven Apps = 27

 How can I identify that the PowerApps dahsboard Apps report is displaying correct data as per the PowerApps App CoE Table? Or what are the test cases to verify the same?

Looking forward!

Thanks,

### Expected Behavior

Power BI Dashboard - apps report should show statistics as per the CoE Table data called "Power Apps App"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest Power BI report

### What app or flow are you having the issue with?

Apps Report in Power BI Report

**Comment by Jenefer-Monroe** [comment] 2022-02-23 14:02
Please share a picture of the PBI page you are referencing. This will help us see if there appears to be filters in place, and if you seem to have a current version of the report.

**Comment by Jenefer-Monroe** [comment] 2022-02-23 15:14
That is certainly a likely culprit. I'm afraid your version is too old for us to assist with any bugs that might exist in the filters etc. 
But again, it does appear that the data is just not refreshed, and so that is likely the cause.

**Comment by tomsinsight** [comment] 2022-02-23 15:24
Silly me - That's true - It was an issue with the dataset refresh - would you please help me with two things as follows:

1) Which report should I use at latest?
2) How can I add the additional filter such as "Show - admin_appdeleted=False" same for the flows
3) what is the best way to schedule the refresh dataset?

Thanks,

**Comment by Jenefer-Monroe** [comment] 2022-03-07 13:59
closing out as no further action for the starter kit team.

**Closed by Jenefer-Monroe** 2022-03-07 13:59 UTC
Labels: question, coe-starter-kit
