### ISSUE TITLE
[ALM Accelerator - BUG]: Folder is created in Pipelines 

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1878] opened 2022-01-28 21:40 UTC
### Describe the issue

When I run the export-to-git pipeline, it creates a folder in the pipelines folder with the same name as our solution v-next branch and it contains the solution and deployment pipelines. but if you try to open the yaml code, they all error.

![image](https://user-images.githubusercontent.com/17124284/151625195-3eeb973e-6463-46b6-b737-6eeea3e72852.png)
the error is:

An error occurred while fetching the YAML file '/ALMAcceleratorSampleSolution/deploy-prod-ALMAcceleratorSampleSolution.yml' in the repository's default branch and latest build branches: ALMAcceleratorSampleSolution. Error on last attempt: File /ALMAcceleratorSampleSolution/deploy-prod-ALMAcceleratorSampleSolution.yml not found in repository alm-sandbox at version/branch ALMAcceleratorSampleSolution.

![image](https://user-images.githubusercontent.com/17124284/151625256-e0d422ef-2477-473e-87bf-7534a08af16f.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220114.1

**Comment by mikefactorial** [comment] 2022-01-28 22:37
This is a new one to me @medicineshow. The folder structure for the pipelines is expected. Can you take a look at the settings for the pipeline and make sure that the specified yaml file exists in the Solution Branch?

![image](https://user-images.githubusercontent.com/42348035/151630999-4fcf0f61-154d-42e5-85a3-2376cd205594.png)

![image](https://user-images.githubusercontent.com/42348035/151630925-67293f98-512f-4093-9c61-0456cc2c4ee8.png)

**Comment by medicineshow** [comment] 2022-01-29 13:01
If I look in the Repo solution folder it has the Yaml files:
![image](https://user-images.githubusercontent.com/17124284/151661950-8d6713ad-705a-420e-b5de-650fff7cdb08.png)
 
and if I open in the Pipeline folder I see this:

![image](https://user-images.githubusercontent.com/17124284/151661986-8f3a5016-9998-4a69-8a58-718df02b2bca.png)

**Comment by medicineshow** [comment] 2022-01-31 10:05
To add (and possibly confuse also) it adds a Build Validation policy to the version branch during the initial commit.
We have created a version (v-next) branch - AlbertsOwnSolution and applied a Branch policy - PR Build Validation.
When Albert runs the Commit Solution from the app which runs the export-to-git pipeline it creates Alberts own working branch (which is named by the pipeline albert.hoffman@hs2test.org.uk-AlbertsOwnSolution) but adds a Build Validation policy to the v-next branch - Build Validation
![image](https://user-images.githubusercontent.com/17124284/151774179-b9207b1c-472b-4f76-8a19-f98a62a74bd3.png)

**Comment by medicineshow** [comment] 2022-01-31 13:19
It's happening during the Update Deployment Setting step in the Export-to-Git pipeline run. The pipeline folder is created without yaml 

![image](https://user-images.githubusercontent.com/17124284/151799833-f9daceac-a850-4086-a272-f7aea71f6a47.png)

also the branch policy is being created and set on our version branch but within that branch policy it points to the newly created pipeline that has no Yaml.


![image](https://user-images.githubusercontent.com/17124284/151800081-bdb8995b-600e-4c8a-b55f-2a47228eac51.png)

**Comment by mikefactorial** [comment] 2022-01-31 14:10
@medicineshow the export pipeline will attempt to validate that the deployment pipelines exist. If they don't it runs the coe-cli branch command which checks for a v-next branch for the solution. If it exists it will not create it, but if it doesn't it goes ahead and creates the branch and will also attempt to create the deployment pipelines. Currently, there's no check to see if the policy exists in the coe-cli which is why you're seeing duplicates get created. However, also just noticed that the pipeline yaml is named build-deploy-environment-SolutionName.yml in the repo. I have a feeling that the coe-cli is expecting the name to be deploy-environment-SolutionName.yml which is why the pipelines can't find the correct files. The naming conventions are fairly rigid right now, but if you were to use the coe-cli (or allow the export pipelines) to wire up the branches / pipelines automatically it would help alleviate some of the manual setup and possible errors related to how things are named. 

Try deleting the existing pipelines and associated yaml files, removing the branch policies and running a new export of the solution from the app to get everything synced up appropriately.

**Comment by medicineshow** [comment] 2022-01-31 14:33
Oh that is a good spot. Perhaps there should be a highlighted "Important" note in the documentation to say that the naming convention is essential? I will reset and re-run and let you know. Thanks.

**Comment by mikefactorial** [comment] 2022-01-31 16:58
@medicineshow I was able to replicate the specific error you were having previously. Hopefully, it goes away with the reset, but the fix in my case was to Edit the pipeline and go to Triggers. Then under the YAML tab -> Get Sources verify that the settings are correctly pointing to your v-next branch. This shouldn't be necessary if the pipelines are generated by the coe-cli, but in case I'm missing something. That fixed it for me.  In my case it was an expected behavior due to working in a mixed environment between GitHub and AzDO repos, but since the error message was the same I thought I'd share.


![image](https://user-images.githubusercontent.com/42348035/151837791-f0967048-60b8-49b6-b1c9-9297af773cab.png)

![image](https://user-images.githubusercontent.com/42348035/151838080-0e505637-8f4f-48d3-ac66-5e9f05f1df77.png)

**Comment by mikefactorial** [comment] 2022-01-31 17:48
@medicineshow I've added a callout to the manual setup docs as you suggested. This will be updated in the February release of the CoE Starter Kit. Thanks again for all the input and assistance working through this issue. It's great having such an active community of contributors. Closing this issue for now. Feel free to open another as you continue to test.

![image](https://user-images.githubusercontent.com/42348035/151845927-995eaa0e-9860-47ab-ae94-83f9d7e3e91f.png)

**Closed by mikefactorial** 2022-01-31 17:48 UTC
Labels: alm-accelerator
