### ISSUE TITLE
[ALM Accelerator - BUG]: Commit / Export-solution-to-git

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#3667] opened 2022-09-14 06:32 UTC
### Describe the issue

The Canvas app sends InstanceUrl in both ServiceConnectionUrl and ServiceConnectionName paramters when running export-solution-to-git pipeline. This prevents the use of friendly names in service connection configuration as the pipeline will look for service connections named with the instanceUrl

### Expected Behavior

The Canvas app will send environment name (friendly name) in the ServiceConnectionName parameter so we can use friendly names for service connections.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

20220831.2

### Steps To Reproduce

1. create service connection for maker environment with friendly name
2. commit solution from maker environment
3. export pipeline fails as it cannot find the specified service connection.

**Comment by mikefactorial** [comment] 2022-10-10 18:27
Closed as duplicate of #3743

**Closed by mikefactorial** 2022-10-10 18:27 UTC
Labels: bug, alm-accelerator
