### ISSUE TITLE
[CoE Starter Kit - BUG] The imported solution and the existing solution must both be managed for upgrade

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#5685] opened 2023-05-30 21:51 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

While I'm trying to upgrade the CoE Starter Kit in our production environment from version 3.34 to 4.8 and I received this error message: 

`The imported solution and the existing solution must both be managed for upgrade`

After looking at the logs I found the following error message: 

`Import of ap module(s) failed: Power Platform Admin View app cannot be associated to more than one component library. Already exists component library count 1. In Solution Import, please remove library either from source or Target and try again.`

Keep in mind, this solution is in production and it hasn't been modified so no unmanaged layers would be there, though I double-checked. Also because it is a managed solution I am not able to delete the component library to get passed this.

### Expected Behavior

Upgrade to 4.8

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View app

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Downloaded the latest version from GitHub repository
2. Started the Import
3. Received error message
4. Tried both of these solutions but did not work: 
>  https://github.com/microsoft/coe-starter-kit/issues/4375
> https://github.com/microsoft/coe-starter-kit/issues/3798

**Comment by Jenefer-Monroe** [comment] 2023-05-30 22:20
I'm afraid this is some product bug outside the context of the kit having something to do with your environment. We have not been able to reproduce it or resolve on our side. Perhaps if you respond to those issues, the members of the community there can help.

**Comment by S0URCEC0D3** [comment] 2023-05-30 22:28
Would deleting the previous solution and importing this new version work?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jenefer-Monroe** [comment] 2023-05-31 04:50
I'm really not sure. But if you can delete the solution my suggestion woudl be to just start with a fresh envt.

**Comment by S0URCEC0D3** [comment] 2023-05-31 15:57
Would upgrading it once version at a time fix the issue?

**Comment by Jenefer-Monroe** [comment] 2023-05-31 16:36
I'm afraid I dont know how to resolve this.

**Comment by Jenefer-Monroe** [comment] 2023-06-03 13:50
closing out as  no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-06-03 13:50 UTC
Labels: duplicate, question, coe-starter-kit

**Comment by Jenefer-Monroe** [comment] 2023-06-16 11:22
thank you so much for posting your findings! We've decided to fund a little test pass around this to see if we can harden our documentation. Appreciate you!

**Comment by perssonkasia** [comment] 2023-06-28 12:19
I run in the same issue. I was able to solve it by adding "Key Vault Reader" and "Key Vault Secrets User" permission in Azure to my service user. (the user I use to run CoE)

**Comment by andrewgaskins** [comment] 2023-07-15 23:45
Similar situation where I had KV value incorrect. It is an odd error since it is very misleading. Fix or remove the KV value and the solution upgrades without issue.
