### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jojobodybeat** [microsoft/coe-starter-kit#3099] opened 2022-06-30 15:25 UTC
### Describe the issue

Admin | Sync Template v3 (PVA) flow got failed each time when it comes to GetBotID action.
In the scope called Update Components for Changed Bots each time when the List BotComponents action ISN'T empty we receive an error in the GetBotID compose action.

On the screenshots you can see that the List BotComponents action isn't empty and the error we receive in the action after that.
I was a post with the same issue in the link below:
https://github.com/microsoft/coe-starter-kit/issues/2434 

![ca580db6-7c65-4edf-8e2c-bb48510b36fd](https://user-images.githubusercontent.com/108478900/176714312-108bb342-d417-4a41-a71d-6bf9e1141ee6.png)
![ca580db6-7c65-4edf-8e2c-bb48510b36fd](https://user-images.githubusercontent.com/108478900/176714513-81912ad7-7e2a-43e9-83b2-684d7791e25d.png)

### Expected Behavior

Successful run of the Get Parent Bot ID scope and actions inside it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

Actually, each time when the List BotComponents action isn't empty you can see that GetBotID compose action got failed. We didn't find any successful runs when the List BotComponents action isn't empty.

### Anything else?

![ca580db6-7c65-4edf-8e2c-bb48510b36fd](https://user-images.githubusercontent.com/108478900/176715988-fcafb9a2-c7ae-40ab-98cb-689e7c998b3e.png)
![2022_06_29_10h18_31](https://user-images.githubusercontent.com/108478900/176715996-2b13a0ca-5534-41e1-b085-b8155bb06d04.png)

**Comment by Jenefer-Monroe** [comment] 2022-06-30 17:41
Hello, this was fixed in the May version of the kit with https://github.com/microsoft/coe-starter-kit/issues/2402

Please [update the kit](https://docs.microsoft.com/power-platform/guidance/coe/after-setup) to see the change.

Duplicate of #2402

**Closed by Jenefer-Monroe** 2022-06-30 17:41 UTC
Labels: bug, coe-starter-kit
