### ISSUE TITLE
[CoE Starter Kit - BUG]: Unable to update the Center of Excellence Audit Components version 1.6.1 from the June release CoEToolkit

### ISSUE THREAD

**Issue by gsknbabu** [microsoft/coe-starter-kit#623] opened 2021-06-15 08:53 UTC
**Describe the bug**
Unable to update the Center of Excellence Audit Components from the June release CoEToolkit

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : CenterofExcellenceAuditComponents
 - Version: 1.61

**To Reproduce**

1. - Download the latest CoEStarterKit from https://aka.ms/coestarterkitdownload
2. - Unzip the CoEStarterKit zip file
3. - Navigate to the Solutions
4. - Click on Import
5. - Browse and Select CenterofExcellenceAuditComponents_1_61_managed.zip
6. - Click on Next
7. - Error There are missing dependencies. Install the following solutions before installing this one: "Active".

**Expected behavior**
Solution should display the Connection References and Environment Variables and proceed to update the selected solution to the environment

**Screenshots**
![image](https://user-images.githubusercontent.com/2226547/122023431-295b8280-cde5-11eb-8acd-6d2584093158.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-06-15 13:13
Hello, in the future you need to get us the details in order to debug these. "Active" is just a placeholder. 
However for this one, it is already known. The solution relies on new fields in Core and so you need to update Core before using Gov. 
Duplicate of #601
Thanks for using CoE

**Closed by JeneferM-MSFT** 2021-06-15 13:13 UTC
Labels: coe-starter-kit, duplicate
