### ISSUE TITLE
[CoE Starter Kit - BUG] Nov month release not working 

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#7067] opened 2023-11-10 04:18 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team 

We are getting error while importing Nov 2023 package. PFB snap for referance..

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/76b0b6fa-327b-4a1f-91bd-afabb4b1cd9d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Kit

### What method are you using to get inventory and telemetry?

None

AB#809

**Comment by manuelap-msft** [comment] 2023-11-10 10:14
Duplicate of https://github.com/microsoft/coe-starter-kit/issues/7050. Please follow along there.

Closing as duplicate.

**Closed by manuelap-msft** 2023-11-10 10:14 UTC
Labels: bug, coe-starter-kit

**Comment by Jenefer-Monroe** [comment] 2023-11-10 16:50
Work around has been posted in https://github.com/microsoft/coe-starter-kit/issues/7050
Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240
