### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permissions App unable to find all the environments of teams type

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#4153] opened 2022-11-10 15:56 UTC
### Describe the issue

We have installed the COE in Core 
We have an issue that the "Set flow Permissions" are not pulling the data from some environments which are of team's type.
Wanted to know why it's not complete environments irrespective of environment type.
![image](https://user-images.githubusercontent.com/111575586/201142410-7b1010ee-e5ad-4b30-9c8a-8b31c0dfeb27.png)

![image](https://user-images.githubusercontent.com/111575586/201143132-0e46fdbc-ebc1-4180-976a-73510679440f.png)

I have totally 8 environments of such type and as my admin account is not a member of those it gives the error and my Admin - Sync (Flows) are failing with different Id's.
So, I wanted to check this in Set Flow Permission app and get the access across those flows. But when I try to check am unable to find either environments or the flows with owner ID in this app.

So wanted to know why it's not fetching the data of all environments. 

### Expected Behavior

It should get all the environments irrespective of the environment type is.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Set Flow Permissions App

### Steps To Reproduce

Goto core solutions:
Select the Set app permission app
select the environment list
Unable to find the environment of Teams type.

**Comment by Jenefer-Monroe** [comment] 2022-11-10 17:12
Hello, please note that the identity running the flows needs to be [Microsoft Power Platform service admin](https://learn.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant#power-platform-administrator), global tenant admin, or Dynamics 365 service admin. And this role must be permanently assigned (not PIM). 

That is by far the most reason that not all environments are pulled for people. Can you please check? 
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

See also [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Neel1KNK** [comment] 2022-11-11 14:18
Hello Jenefer,
Thanks for your response.
As you said I have the required permission which is permanent.
![image](https://user-images.githubusercontent.com/111575586/201358651-93b05760-e75d-49c4-998e-3092b10bf61b.png)

We are running just core solution itself but facing this issue.
Kindly help

**Comment by Neel1KNK** [comment] 2022-11-11 17:04
Am unable to see the flows here as well.
I tried to go filters and search as per environments which are not visible and here as well am unable to find them.
![image](https://user-images.githubusercontent.com/111575586/201391975-0e24b63f-8e43-4721-94af-fa9affad4f10.png)

![image](https://user-images.githubusercontent.com/111575586/201392017-e5e43b18-9564-496a-b802-8cf57e649c74.png)

Unable to see any flows

**Comment by Jenefer-Monroe** [comment] 2022-11-11 17:14
ok sounds like the sync flow is not fetching them then. 
Can you plesae go to https://flow.microsoft.com/ > your CoE envt > Core solution > Flows > Admin | Sync Template v3 (Flows)

Once on the details page, please add the environmentid column and find one of these environments (you may need to go to All Runs to find it)
When you find it, click on the timestamp to open the run
![image](https://user-images.githubusercontent.com/89584709/201393694-10428df3-82d1-4273-8b7e-d7e58843fb10.png)

Once in the run, find the List Flows as Admin call. Do you see flows returned here? 
![image](https://user-images.githubusercontent.com/89584709/201393914-2ace8ef7-af04-49ee-9fc4-666d2d307420.png)

**Comment by Neel1KNK** [comment] 2022-11-11 17:35
Yes, I can find them.

![image](https://user-images.githubusercontent.com/111575586/201397098-3a2a9b5a-1517-4b06-8bea-1f03f0586d63.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-11 17:55
great, lets move down the flow then. 
the next thing to see is, are they still present after the next step, the filter? 
![image](https://user-images.githubusercontent.com/89584709/201400317-d48b1e0e-32e5-4529-88f3-c0575abe493a.png)

**Comment by Neel1KNK** [comment] 2022-11-11 18:07
Yes, they are.
![image](https://user-images.githubusercontent.com/111575586/201401834-e91e9f06-cd9d-4ea6-9754-65ef9c6c045f.png)

They are failing here:
![image](https://user-images.githubusercontent.com/111575586/201401981-97c40e61-4bd6-4593-b031-a677ca345bea.png)
![image](https://user-images.githubusercontent.com/111575586/201402046-c9306938-1d29-40ae-90aa-63d5a85ee209.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-11 18:13
Is it failing for this flow in the same way listed in your other bug? https://github.com/microsoft/coe-starter-kit/issues/4142

**Comment by Jenefer-Monroe** [comment] 2022-11-11 18:15
And can you validate that the flow exist, if you go to https://admin.powerplatform.microsoft.com/environments > Find your envt > click flows
![image](https://user-images.githubusercontent.com/89584709/201403176-302c5d0d-85c8-4f81-9936-ee265b567e03.png)

**Comment by Neel1KNK** [comment] 2022-11-11 18:19
Yes, I have crosschecked there previously and confirming you.

![image](https://user-images.githubusercontent.com/111575586/201403615-a4ade65d-e040-42b9-99c2-cab84f4f2b90.png)

**Comment by Jenefer-Monroe** [comment] 2022-11-11 18:54
ok, find this flow in the return from here. Get its index number (it should be index 1 of a total of 1 flows but please confirm)
![image](https://user-images.githubusercontent.com/89584709/201403891-beb31e03-4b43-4d1a-b0cf-4fba4e90dc37.png)

Then follow into the Apply to each, it should look like this
![image](https://user-images.githubusercontent.com/89584709/201410948-a57ee6e2-b634-4b28-bd5c-8e76bd8a6f1d.png)

Does this action fail?
![image](https://user-images.githubusercontent.com/89584709/201410990-31e54dc3-1009-4420-a333-adb8796157a8.png)

**Comment by Neel1KNK** [comment] 2022-11-14 17:59
Hello,

Yes the flow is failing at the action: "Get New Flow As Admin"

![image](https://user-images.githubusercontent.com/111575586/201732610-e2c3a9a2-c0f4-48c9-be64-0cdd6cf661d2.png)

![image](https://user-images.githubusercontent.com/111575586/201732221-62d41092-9a5f-4ac2-93e7-f8dd25027e89.png)

I see it has correct inputs and outputs, not sure about index.

**Comment by Jenefer-Monroe** [comment] 2022-11-21 13:39
alright this is the same issue then as the other one we are working on together and the product is incorrectly failing to retrieve the  flow that exists. I will dupe this to that bug and we will track there., 
Dupe of https://github.com/microsoft/coe-starter-kit/issues/4142

**Closed by Jenefer-Monroe** 2022-11-21 13:39 UTC
Labels: bug, coe-starter-kit
