### ISSUE TITLE
[CoE Starter Kit - BUG] Environments on Power BI Dashboard Count not matching

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7158] opened 2023-11-20 14:54 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

IT says I have a 11 but I know I only have 10, I believe it is counting the Blank item even though there is none found.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/d3f39785-8474-497d-be24-3938cc411fff)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/29d41ad2-7e8c-4753-8e43-0e146606a549)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

None

AB#1460

**Comment by Jenefer-Monroe** [comment] 2023-11-20 22:25
It does count blank you are correct. I think this is by design, and you can filter it out if you'd like.

**Comment by Jenefer-Monroe** [comment] 2023-11-26 15:03
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-11-26 15:03 UTC
Labels: bug, coe-starter-kit
