### ISSUE TITLE
[CoE Starter Kit - BUG] Error message when importing the solution core components

### ISSUE THREAD

**Issue by mikarepos** [microsoft/coe-starter-kit#7083] opened 2023-11-13 15:38 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I want to configure Center of Excellence (tenant) for the Power Platform for the first time as this is the new implementation
and I tried several times  to import the CenterofExcellenceCoreComponents_4.16_managed.zip and also new version CenterofExcellenceCoreComponents_4.17_managed.zip solution into Power Automate but when I click on the buton "Next" on the step of establishing of the connection with the connections, I get every time the same error message as below . 
I tried in browsers like Google Chrome, Edge and also in inprivate mode and I enabled the third part cookies within the browser but still I got the same issue and cannot import the solution CenterofExcellenceCoreComponents_4.17_managed.zip into the Power Platform in order to further continue the configuration of the coe-starter-kit.
I have contacted as well the support Microsoft Power Platform to investigate the issue but after some investigations and checking the network traces when recreating the issue, Microsoft Power Platform support agent told that based on their checks, as Coe tool is supported by Github, and hence it is out of scope from their end.
The Center of Excellence (CoE) Starter Kit is not supported by the Power Platform product team. For issue related to the 'CoE Starter Kit' product, Microsoft Power Platform support requested me to report the issue to https://github.com/microsoft/coe-starter-kit/
I have done the search but I did not find the same issue reported earlier on Github.
 
Could you investigate and help resolve this issue.
 
Sorry... The connection was interrupted
We cannot obtain this information at this time. Try again or check our support page to see if there are any known issues.
ID of the session: 94e7bef0-8234-11ee-afb9-8b1fbdf33a21
![error message coe kit1](https://github.com/microsoft/coe-starter-kit/assets/68370075/7b871ea1-424c-4450-ae3c-4d4ea1aeea3b)
![error message coe kit](https://github.com/microsoft/coe-starter-kit/assets/68370075/4b27c954-2411-497c-9deb-c4dc3838a020)
![error message coe kit4](https://github.com/microsoft/coe-starter-kit/assets/68370075/1dfaa41d-e809-473f-8af4-956f79819d12)
![error message coe kit3](https://github.com/microsoft/coe-starter-kit/assets/68370075/b12b45e4-e16c-44ee-8f60-13ddf75ae0a6)
![error message coe kit2](https://github.com/microsoft/coe-starter-kit/assets/68370075/2a988451-7de8-4165-a758-edb035cd27a2)
![error message coe kit5](https://github.com/microsoft/coe-starter-kit/assets/68370075/9066ba40-b5fb-46bb-a016-04737dd0e10b)

### Expected Behavior

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.17

### What app or flow are you having the issue with?

I want to import the solution core components for the first time

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

![error message coe kit2](https://github.com/microsoft/coe-starter-kit/assets/68370075/0519f26b-1897-48ab-a685-f01dcd475bd7)
![error message coe kit3](https://github.com/microsoft/coe-starter-kit/assets/68370075/83a6875e-31b4-4b0b-824f-48adb774a842)
![error message coe kit4](https://github.com/microsoft/coe-starter-kit/assets/68370075/2de4a958-8108-4f66-8cd6-3bf24804a3a4)
![error message coe kit](https://github.com/microsoft/coe-starter-kit/assets/68370075/b8f81550-5592-40ee-b82b-6a35180d39c2)
![error message coe kit1](https://github.com/microsoft/coe-starter-kit/assets/68370075/d1c6a817-d34a-41dd-a06c-ba2e991dc5af)
![error message coe kit5](https://github.com/microsoft/coe-starter-kit/assets/68370075/7ccf9363-3ff7-449c-b5ef-88bab4d6c558)

### Anything else?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup

AB#833

**Comment by manuelap-msft** [comment] 2023-11-13 17:13
This is a product bug related to processing environment variables. Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240 - the workaround is to use this URL  https://make.powerapps.com/environments/solutions?powerappsConnections.enableShowAllEnvVariablesOnImport=false with the URL parameter and import the solution from there. 

Closing as this is a duplicate of #7050. If you continue to see issues, please comment on #7050.

**Closed by manuelap-msft** 2023-11-13 17:13 UTC
Labels: bug, coe-starter-kit

**Comment by mikarepos** [comment] 2023-11-13 19:47
Great, I just tried this workaround and it is working.
