### ISSUE TITLE
[CoE Starter Kit - BUG] Error in Admin | Sync Template v3 (Connection Identities) flow

### ISSUE THREAD

**Issue by kruthihegde11** [microsoft/coe-starter-kit#3558] opened 2022-08-31 13:33 UTC
### Describe the issue

when flow is trying to remove deleted connection reference identities from the inventory, following error message is seen:
"message":"Syntax error at position 147 in '_admin_environment_value eq ed0d6cba-3f74-4db6-b039-0223f043fb5a and admin_name eq 'shared_commondataservice' and admin_accountname eq 'Kathryn.O'Neil@mycompany.com' and (admin_connectionreferencecreatordisplayname eq null or admin_connectionreferencecreatordisplayname eq 'Kathryn.O'Neil@mycompany.com')'

Looks like the special character (apostrophe) in the account name Kathryn.O'Neil@mycompany.com is the cause.
More information on the steps causing issue in the screenshots attached.
![Capture1](https://user-images.githubusercontent.com/112558856/187689970-0b2e51c7-925e-4d4f-9806-e5a8ff2c5a1d.PNG)
![Capture2](https://user-images.githubusercontent.com/112558856/187689987-29d6c27a-f722-4348-816b-347247ffb127.PNG)

### Expected Behavior

the query should process the special characters. The flow is failing only for the records with account name containing special character (').

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities) flow

**Comment by manuelap-msft** [comment] 2022-08-31 15:52
Duplicate of #3201 and on our roadmap. Closing as duplicate.

**Closed by manuelap-msft** 2022-08-31 15:52 UTC
Labels: bug, coe-starter-kit

**Comment by Jenefer-Monroe** [comment] 2022-08-31 22:58
this one is local fixed for Sept via https://github.com/microsoft/coe-starter-kit/issues/3201
