### ISSUE TITLE
[CoE Starter Kit - Feature]: Solution Inventory

### ISSUE THREAD

**Issue by bronsonacoutts** [microsoft/coe-starter-kit#3254] opened 2022-07-22 00:59 UTC
### Is your feature request related to a problem? Please describe.

Inventory of Solutions across all environments into the CoE Dataverse Tables.

### Describe the solution you'd like

**Should Have**
- Solutions from all Tenant environments would be sync'd as part of the Core Inventory flows into a 'Solutions' table.
- The solutions should be related in both directions of the hierarchy (i.e. up to Environments and down to components such as apps, flows etc).
- Ability for developers or administrators to provide solution information and/or links to the reference documentation for a support user/future developer/architecture audience.

**Nice to Have**
Additional inventory of things like Security Roles & Option Sets for the purpose of good Data Architecture & Governance.

### Additional context?

I am looking to build a couple of CoE Extensions that will require an inventory (similar to all of the other inventories in the CoE) but for Solutions (that are related to Environments, Apps, Flow's etc).

Quick Summary of the use cases as I see them:

- Developers would be able to provide additional context and info that gets tagged to the solution. 
- This would allow for the ability to generate somewhat of a solution manifest/solution documentation to aid compliance, support users and future developers.
- This would allow for Administrators to build extensions such as the one that I intend to build that when a user is granted access to a security role that requires a premium license, to record all of the instances/solutions/solution objects that require premium licensing against the user.  _(The actual Licensing Management tool doesn't/shouldn't be a direct feature because the requirement's for each organisation would be too bespoke, but having the solution inventory would aid people like me to develop such things)_
- Having the Solution to Environment to Solution Object relationship would assist Data Architects with requirements such as:  maintaining consistency and reduce redundant duplication of or the non-refreshed persistence of data that has it's source of truth elsewhere.

I am sure there are many more benefits too.  Keen to hear thoughts, perhaps there is something that I am missing?

**Comment by manuelap-msft** [comment] 2022-07-22 11:55
Hello,

solution inventory will be part of our next release in August, estimated to go live first week of August - see here for some preview screenshots of what we've done:
https://github.com/microsoft/coe-starter-kit/issues/968#issuecomment-1167675889

**Comment by manuelap-msft** [comment] 2022-07-22 11:56
I'm closing this as duplicate, as I think the August release addresses your ask but if once that's available and you've tested it out you feel we missed a scenario or could improve how something works, please feel free to create another feature ask for us!

**Comment by manuelap-msft** [comment] 2022-07-22 11:57
Duplicate of #968, closing.

**Closed by manuelap-msft** 2022-07-22 11:56 UTC
Labels: enhancement, coe-starter-kit
