### ISSUE TITLE
[CoE Starter Kit - BUG] Invalid pagination

### ISSUE THREAD

**Issue by KezHalls** [microsoft/coe-starter-kit#3067] opened 2022-06-27 20:26 UTC
### Describe the issue

Flow: Admin | Sync Template v3 (Connectors)
I have exceeded what I believe to be the required licences but still get the error below.
Licences I have. 
- Power Automate per user plan 
- Power BI Pro
- Power Apps per user plan
Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Connectors' of type 'OpenApiConnection' at line '1' and column '5166' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}". Code: 0x80060467 InnerError: '.

### Expected Behavior

Flow runs successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Go back to previous page Admin | Sync Template v3 (Connectors)

### Steps To Reproduce

Edit Flow --> Turn on
Error occurs

**Comment by Jenefer-Monroe** [comment] 2022-06-27 22:28
Hello, you are likely using a trial license which we cannot support for purposes of the pagination requirements. 
Please see this notice in [Turn on inventory flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

![image](https://user-images.githubusercontent.com/89584709/176046554-0a15f9ca-bbe9-4f4c-b4d2-4a373c65c33b.png)

**Comment by KezHalls** [comment] 2022-06-28 22:55
I understand that.  Hence why I listed the licences that I had.  I am trying to understand what licence I dont' have.

**Comment by KezHalls** [comment] 2022-06-28 22:56
I may have put in wrong area.  not a but but certainly documentation is not clear as I believe I have fulfilled licence expecations.

**Comment by Jenefer-Monroe** [comment] 2022-06-29 00:03
Here is the full [license requirement list](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with). Every person we have seen hit this has been due to them having a trial version of their per user license, so I am certain that the issue is that you are using a trial license for that, which we do not support. 
![image](https://user-images.githubusercontent.com/89584709/176323712-0a67b2d3-ab7f-43dd-9455-16c538d84549.png)

You may be able to check this by going to Azure and looking at your licenses
![image](https://user-images.githubusercontent.com/89584709/176323973-50b9614b-59fa-4371-9c63-311de8f13887.png)

**Comment by KezHalls** [comment] 2022-06-29 02:17
As I said. I don't have trial licences. Even went as far as getting an individual power automat licence... instead of relying on the one that comes a part of power apps.  I listed the licences I have above (which was the exact wording on them.  
[ms licences.pdf](https://github.com/microsoft/coe-starter-kit/files/9006721/ms.licences.pdf)
)

**Comment by KezHalls** [comment] 2022-06-29 02:20
heres via the porta
<img width="449" alt="mslicence via portal" src="https://user-images.githubusercontent.com/29215309/176337245-f95ac7fa-10a1-4962-a0fe-a0123b03f689.png">

**Comment by Jenefer-Monroe** [comment] 2022-06-29 13:24
Is the identity used to install the kit, the identity used for the connection, and the idenity you checked there all the same identity? 
If you have multiple admins, or if you use service accounts, you can sometimes end up with a mix, like shown here
![image](https://user-images.githubusercontent.com/89584709/176447078-3d12bbca-597b-4104-a2fd-9d3de6d0bfd6.png)


Its the Connection references in use that are used for the license / pagination.

**Comment by Jenefer-Monroe** [comment] 2022-07-05 20:01
Closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-07-05 20:01 UTC
Labels: bug, coe-starter-kit
