### ISSUE TITLE
@Samuel-Dittmann thanks for reporting this issue. Will look into a fix for this and validating Dataflows in general as we've not spent a lot of time in this area, but need to get this working.

### ISSUE THREAD

**Issue by SAEED2ALAHMARI** [microsoft/coe-starter-kit#6068] opened 2023-07-13 11:02 UTC
@Samuel-Dittmann thanks for reporting this issue. Will look into a fix for this and validating Dataflows in general as we've not spent a lot of time in this area, but need to get this working.

_Originally posted by @mikefactorial in https://github.com/microsoft/coe-starter-kit/issues/3705#issuecomment-1251295740_

**Comment by mikefactorial** [comment] 2023-07-14 03:25
This looks to be a duplicate of #3705 or an accidental response. Closing for now. Please feel free to add more information to the original issue.

**Closed by mikefactorial** 2023-07-14 03:25 UTC
Labels: alm-accelerator

**Comment by SAEED2ALAHMARI** [comment] 2023-07-18 09:18
*Is the problem solved?*
* What is the cause of this problem?*

* How do I avoid that?*

*Thank you for contacting me*


‫في الجمعة، 14 يوليو 2023 في 6:25 ص تمت كتابة ما يلي بواسطة ‪Mike!‬‏ <‪
***@***.***‬‏>:‬
