### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template v3 PVA fails on GetBotID

### ISSUE THREAD

**Issue by LoRosset** [microsoft/coe-starter-kit#2546] opened 2022-04-25 10:50 UTC
### Describe the issue

The flow "Admin | Sync Template v3 (PVA)" fails on GetBotID with the following mistake:

InvalidTemplate. Unable to process template language expressions in action 'GetBotID' inputs at line '0' and column '0': 'The template language expression 'first(body('List_bot_for_a_botcomponent')?['value'])['botid']' cannot be evaluated because property 'botid' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.

![image](https://user-images.githubusercontent.com/25909766/165074677-8f8ad6b1-4b5d-4cad-919c-6bd176b8ede5.png)

### Expected Behavior

No failure

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

1. Launch Admin Sync Template v3 (PVA)
2. On all environment the flow fails with the error mentionned

**Comment by medicineshow** [comment] 2022-04-25 11:08
We are experiencing exactly the same error.

**Comment by NPrice99** [comment] 2022-04-25 11:16
Hi
I am also experiencing the same issue.

The issue is cause by previous step  "List bot for a bot component" returning an empty array.  
![image](https://user-images.githubusercontent.com/8484048/165078476-a7807988-635c-4a82-a91f-09d6925a99f0.png)

So should just need a condition before GetBotID to check for an empty array returned by "List bot for a botcomponent".

Regards

Nigel

**Comment by NPrice99** [comment] 2022-04-25 11:50
This worked for me -
![image](https://user-images.githubusercontent.com/8484048/165083218-5e13f924-3796-4aea-bdd0-222d42ea1d8b.png)

Where Condition is -
![image](https://user-images.githubusercontent.com/8484048/165083358-af5247c0-c0c9-413a-b77e-52725d27c78f.png)

Regards

Nigel

**Comment by Jenefer-Monroe** [comment] 2022-04-25 12:17
Fixed by #2402 for May. It seems the issue is that a new solution was added to many environments by the product team which contained subcomponents of the object type without the object itself. An error state we hadn’t anticipated. 

There is no impact on inventory by this failure, so there is no need to worry local fixing it, the failures are annoying as they imply something is wrong, but will go away when they upgrade. 

Thanks for using CoE

**Comment by Jenefer-Monroe** [comment] 2022-04-25 12:17
closing out as a dupe.

**Closed by Jenefer-Monroe** 2022-04-25 12:17 UTC
Labels: bug, coe-starter-kit
