### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance App is missing in Core Components solution

### ISSUE THREAD

**Issue by thotavinod590** [microsoft/coe-starter-kit#7949] opened 2024-03-27 07:03 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,
We have installed Core Components Solution version 4.23; the Developer Compliance App is not available in the Core Components Solution. Previously, this app was available in the Governance Solution. But in the latest version, there is no governance solution. Can you please advise us on setting up the developer compliance app?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

 Developer Compliance App

### What method are you using to get inventory and telemetry?

None

AB#2680

**Comment by RahulBojji** [comment] 2024-03-27 07:40
@thotavinod590 You will find the Developer Compliance App in the Audit Components Solution. Here is the release [URL](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-February2024) for the same
<img width="875" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/da2519b4-b0d2-45d2-a180-3a10f099afdb">

**Comment by thotavinod590** [comment] 2024-03-28 08:20
Hi @RahulBojji 
Thanks for the your response. Can you please help us understand the below points.

In Developer Compliance App, 
 1. How to extract the reports Of List of app and flow  are compliance
 2. As Admin account , how to see all apps and flow details 
 3. On what basis apps/Flows are Non- Compliant, Missing details , Flagged as in active

**Comment by RahulBojji** [comment] 2024-03-28 11:29
@thotavinod590 
1. How to extract the reports Of List of app and flow are compliance  - In the power platform admin view model driven app there is a dedicated view on the PowerApps Apps and Flows table

<img width="801" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/ac161b51-2191-467d-ac58-96e7aa0c14e0">

There is a similar view on the Flows table as well. You can use that view for your reports

2. As Admin account , how to see all apps and flow details - If your question is about where to find the information about all the apps and flows, "Power Platform Admin View" Model Driven is where you see all the information. 

<img width="909" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/5bfbff27-7f48-4a8d-9a5f-03b39945be69">

3. On what basis apps/Flows are Non- Compliant, Missing details , Flagged as in active - In compliance there are some flows which does this. Please see [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#compliance-processes) for more information. For example, if an app is non- compliant, it indicates that the resource is currently noncompliant with existing DLP or billing policies; often this means that the resource can't be used until the problem is resolved.

Hope this answers your question

**Comment by RahulBojji** [comment] 2024-04-01 13:38
Hello. We are a very small team and note the CoE Starter Kit is an [unsupported set of templates](https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support). As a result we are not staffed to meet with our GitHub users.

**Comment by thotavinod590** [comment] 2024-04-02 15:04
Hi @RahulBojji 

We are not clear with your answers. Here is a brief description for your better understanding. 

1. Power Platform Administrator/Global Admin able to see only apps created by user as compliance?
2. In our COE Toolkit, please describe the flows and Data verse table related to the Developer Compliance App.
3. We are planning only developer compliance. Only for sending out email and not providing access to the user due to a license constraint, hope will trigger an email to the user  with a custom email.

**Comment by Jenefer-Monroe** [comment] 2024-04-02 17:10
Hello our customization capabilities will likely not meet these needs. The solution we have created depends on the user accessing the app to fill in the details. 
That said, the starter kit is open source and so you can take the ideas and make them your own as needed.

**Comment by Jenefer-Monroe** [comment] 2024-04-08 12:39
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-04-08 12:39 UTC
Labels: bug, coe-starter-kit
