### ISSUE TITLE
COE core component update with september release is getting failed

### ISSUE THREAD

**Issue by PoojaBaniya** [microsoft/coe-starter-kit#9347] opened 2024-12-02 13:17 UTC
COE core component update with september release is getting failed with error "Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :The connectionreference(2d3ab564-af95-40df-ba1b-9450c6a0f25d) component cannot be deleted because it is referenced by 17 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest."

**Comment by Jenefer-Monroe** [comment] 2024-12-02 13:37
Unfortunately it looks like you've hit a product bug around upgrade. A few other people have hit this too. Please see https://github.com/microsoft/coe-starter-kit/issues/8466. 
### The connection
This is likely the legacy Dataverse connection that is at play, why it wont tell you the name I don’t know. 
But this is a connection that we have removed from the kit and that is causing issues in the product’s upgrade code.
### The likely issue
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 
### Find impacted flows
Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8186341-cf26-4710-aa3c-8b3e3bb9f2ea)
### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.
And another user has succeeded with this workaround. See https://github.com/microsoft/coe-starter-kit/issues/8466

**Comment by PoojaBaniya** [comment] 2024-12-03 12:46
Hello Jenefer,

I have performed suggested workaround now it is giving me new error, let me know what needs to be done.
Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Import failed: The DELETE statement conflicted with the REFERENCE constraint "connector_connectionreference". The conflict occurred in database "db_crmcorenam_20220817_12521167_8461", table "dbo.connectionreferenceBase", column 'CustomConnectorId'. The statement has been terminated.

Regards,
Pooja Baniya

**Comment by Jenefer-Monroe** [comment] 2024-12-09 14:28
Unfortunately I'm just not sure then. You are in an unknown state at this point. 
You can try a classic upgrade, hopefully that resolves. 

### How to do an overwrite upgrade in the classic UX:
 
Switch to classic
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/690cafcb-ade8-4571-81d5-df70f97f6266)

Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/433cd2d8-7e2a-4d35-a86e-cf569b7777f2)

Select Core > Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f232f4b5-783d-4d8c-af94-21fb6dfd91bf)

Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/39c84d9b-7ccf-4aff-8861-6c70ed7cb237)

Overwrite customizations > Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b23463c-2361-4135-81a8-363a96ca23d5)

**Comment by PoojaBaniya** [comment] 2024-12-11 11:45
This didn't work, what are consequence if we update instead of upgrade?

Regards,
Pooja Baniya

**Comment by Jenefer-Monroe** [comment] 2024-12-11 13:55
As you are in an unknown state, I'm just not sure. But it sounds like you are low on options so you may as well try.

**Comment by Jenefer-Monroe** [comment] 2024-12-17 13:11
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-12-17 13:11 UTC
