### ISSUE TITLE
The connectionreference(GUID) component cannot be deleted because it is referenced by 17 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest.

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8561] opened 2024-06-27 14:57 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

error when upgrading Core Component solution from 4.17 to 4.32.2

### Expected Behavior

Upgrade success

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2024

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

Error Code
[8004F01F](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004F01F&de=online)
Exception Message
The connectionreference(1992b487-9933-4983-945b-72d1597a9a24) component cannot be deleted because it is referenced by 17 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest.

Total Duration
1 h 26 m 55 s
Correctif logiciel
Non
Géré
Oui
Remplacer les personnalisations
Non
ID d'activité
40a66b4b-2ba0-4d3e-a168-8f18742121aa

AB#3698

**Comment by Jenefer-Monroe** [comment] 2024-06-27 19:53
Unfortunately it looks like you've hit a product bug around upgrade. A few other people have hit this too. Please see https://github.com/microsoft/coe-starter-kit/issues/8466. 
### The connection
This is likely the legacy Dataverse connection that is at play, why it wont tell you the name I don’t know. 
But this is a connection that we have removed from the kit and that is causing issues in the product’s upgrade code.
### The likely issue
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 
### Find impacted flows
Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8186341-cf26-4710-aa3c-8b3e3bb9f2ea)
### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.
And another user has succeeded with this workaround. See https://github.com/microsoft/coe-starter-kit/issues/8466

**Comment by gghaleb** [comment] 2024-06-28 14:18
it worked, thanks!

**Comment by Jenefer-Monroe** [comment] 2024-06-28 14:59
Wonderful news, thanks so much for responding to let me know! 
I'll go ahead and close this out then but please feel free to reach out with new issues in the future

**Closed by Jenefer-Monroe** 2024-06-28 14:59 UTC
Labels: bug, duplicate, coe-starter-kit
