### ISSUE TITLE
[CoE Starter Kit - BUG] Custom Connector Record does not get updated

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#1247] opened 2021-09-28 02:38 UTC
### Describe the issue

I deleted the custom connector using Remove-AdminPowerAppConnector PowerShell cmd and after that, I run Admin | Sync Template v3 (Custom Connector) to make sure if the record is removed or marked as inactive but it did not. As you can see below images. 

After that, I created a test cloud flow that will bring all custom connectors from that environment where the connector was deleted and it did not pass any value. 

![image](https://user-images.githubusercontent.com/75992078/135012843-bc27eb4f-606a-401a-b017-2dd017b10d1a.png)

![image](https://user-images.githubusercontent.com/75992078/135012906-49600254-c5a2-45aa-b3f2-430f68f57fcf.png)

Based on the Power Platform Admin View Model-Driven app there should be 2 custom connectors in the environment but based on the cloud flow which i run there is no custom connector in the environment. 
Power Platform Admin View App
![image](https://user-images.githubusercontent.com/75992078/135012987-138193db-59ee-4fe2-978b-6aaba6345629.png)

Test Cloud flow
![image](https://user-images.githubusercontent.com/75992078/135013097-5f1bb3d1-800d-4331-8ce6-ec37fdd3269d.png)

Also, I want to list another problem is that when a cloud flow or app uses a custom connector they do not show up inside the custom connector section where you can see apps and flows which use a custom connector. 

![image](https://user-images.githubusercontent.com/75992078/135013393-6b0c25b7-1969-4259-b51d-599f45759fd1.png)

### Expected Behavior

To mark records as inactive when they do not exist. records

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connector)

**Comment by manuelap-msft** [comment] 2021-09-28 13:52
Duplicate of #1218 and has been fixed for the October release.

**Closed by manuelap-msft** 2021-09-28 13:52 UTC
Labels: duplicate, coe-starter-kit
