### ISSUE TITLE
CoE Dashboard showing inconsistent numbers

### ISSUE THREAD

**Issue by DaisyZ6166** [microsoft/coe-starter-kit#7270] opened 2023-12-11 21:30 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have CoE starter kit installed in two test environments, both are running the November release. However, the CoE dashboard in two environments has different numbers of apps, flows, makers, teams environments, solutions. We have not excluded any environments from inventory. We need assistance to investigate and fix the issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1750

**Comment by v-bjaiswal** [comment] 2023-12-13 07:08
Hi, 
Please check if below flow ran on both the environment and last ran should be latest on both of them.

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/563861ce-ed06-4067-a753-8106234f586d)

If the flow is fine and you are using Power BI Desktop then please ensure that you have synced the latest data from organization by using the "Refresh" ribbon button.

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/c371fe64-1fc1-4758-af1d-0b682a7bb6c5)

**Comment by DaisyZ6166** [comment] 2023-12-13 22:40
Hi Bhavendra,
Thanks for your advice.

The flows in two environments NZTA-Power-Platform-Test-CoE and NZTA_Power-Platform-TestCoE all ran successfully at similar time. Screen shots as attached.
[Screenshots for Inconsistent Numbers in Two Environments.docx](https://github.com/microsoft/coe-starter-kit/files/13666411/Screenshots.for.Inconsistent.Numbers.in.Two.Environments.docx)
The two reports were last refreshed at similar time. Screenshot is also included in the attached file.

Thanks!
Regards,

**Comment by v-bjaiswal** [comment] 2023-12-15 10:53
Hi, could you tell where exactly the count is different? If it's different everywhere then please attach the snip of it.

Since this is not fully reproducible at our end and all the inventory data of Apps, flows and environment came from its individual flows so it might be helpful for us to further look into it.

Thanks

**Comment by DaisyZ6166** [comment] 2023-12-17 22:37
Hi Bhavendra,

I have added some screenshots to the attached file of the inconsistent numbers from two environments.

Thanks!
Regards,
Daisy
[Screenshots for Inconsistent Numbers in Two Environments.docx](https://github.com/microsoft/coe-starter-kit/files/13698004/Screenshots.for.Inconsistent.Numbers.in.Two.Environments.docx)

**Comment by Jenefer-Monroe** [comment] 2023-12-18 14:43
Hello. You can expect small differences in numbers between environments as the inventory is always a snapshot in time. 

From looking at your screenshots, I dont think there is a problem here, I think its just a snapshot issue. 
However if you would like to investigate further. Please look to find a specific object (ex an app) that is in one inventory but not the other. Then see if if normalizes the next day.

**Comment by Jenefer-Monroe** [comment] 2024-01-03 17:15
Closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-01-03 17:15 UTC
Labels: question, coe-starter-kit
