### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by satyak64** [microsoft/coe-starter-kit#5593] opened 2023-05-22 11:53 UTC
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Reports are not having complete data after recently upgraded to 4.4.1 version of Core Components. Actual count of the Flows in our environment is not showing in the COE reports.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment] 2023-05-22 12:05
Hello. This is a duplicate of https://github.com/microsoft/coe-starter-kit/issues/5331 for which we shipped a hotfix for April release. You will need to upgrade to the May release to resolve.

**Comment by Jenefer-Monroe** [comment] 2023-05-23 13:27
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2023-05-23 13:27 UTC
Labels: duplicate, question, coe-starter-kit
