### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to commit solution

### ISSUE THREAD

**Issue by UvVij99** [microsoft/coe-starter-kit#7745] opened 2024-02-28 10:51 UTC
### Describe the issue

Unable to commit solution in ALM Accelerator.

### Expected Behavior

It should commit solution changes to DevOps.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

### Steps To Reproduce

Open ALM Accelerator App
Commit Solution

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/54388217/7b78991f-3362-4795-9ee8-37ffc5045d46)

AB#2404

**Comment by RajeevPentyala** [comment] 2024-03-01 05:43
@UvVij99 Looks like the issue is with 'ALM Accelerator' configuration. To get the detailed error, can you please click on the chevron, which takes you to the 'Request History' screen as shown below?
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/0d6d2a5d-ba57-4598-bcba-949a4edce466)

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/5f142ea6-b3d0-4052-978b-d7d625c36772)

**Comment by UvVij99** [comment] 2024-03-05 09:58
@RajeevPentyala Can you confirm what needs to be done here?
I cannot see any error message here.
![image](https://github.com/microsoft/coe-starter-kit/assets/54388217/78bc4a2d-7679-4e6a-9349-78c6145af555)

**Comment by v-bjaiswal** [comment] 2024-03-18 11:57
Hi @UvVij99 , 

Could you please verify if you encounter any errors during the "export-solution-to-git" pipeline in your Azure DevOps project? If there are any errors, could you let us know at which step they occur? Identifying these errors will help us pinpoint the root cause and address the issue effectively.

Thank you for your assistance.

**Comment by UvVij99** [comment] 2024-03-20 17:12
I Cannot see any export-solution-to-git triggered.

**Comment by v-bjaiswal** [comment] 2024-03-21 05:31
Can you Validate if in you Azure Devops projects all these pipelines created?
![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/b6c524cf-6cf4-460e-bc59-e238a5382b7b)

the folder names should be like "Project name - Solution name"

Also ensure all the service connections are created as per below:
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#create-service-connections-for-azure-devops-to-access-power-platform

**Comment by UvVij99** [comment] 2024-03-28 13:03
@v-bjaiswal

I can confirm the Pipelines exists and i can see them on Devops but they are not working, and we have service connections already created onto DevOps and all accesses are provided. But the pipelines are not getting triggered automatically as they should be once we trigger commands from ALM Accelerator App.

![image](https://github.com/microsoft/coe-starter-kit/assets/54388217/937182e8-f239-4f68-ab64-9e46c820f89a)

**Comment by RajeevPentyala** [comment] 2024-05-08 10:10
@UvVij99 Please let us know if you are still facing the issue.

**Comment by UvVij99** [comment] 2024-05-08 10:18
@RajeevPentyala Yes I am still facing issue. It is not yet resolved.

**Comment by RajeevPentyala** [comment] 2024-05-21 05:09
@UvVij99 I suspect the issue is with 'Custom Connector' configuration. Can you open the 'CustomAzureDevOps' custom connector and manually test the 'RunPipeline' method?
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/e7444f2d-a4b6-4017-be07-c49c7b0c0d6f)

**Comment by UvVij99** [comment] 2024-05-30 11:34
@RajeevPentyala  I have checked and found that custom connector is working fine as it is giving me 200 ok response when tested as mentioned on Official document we should be getting 200Ok response for connector to be working.

**Comment by RajeevPentyala** [comment] 2024-06-10 06:31
@UvVij99 Closing this issue as we had a sync-up, and it turned out to be a configuration problem.

**Closed by RajeevPentyala** 2024-06-10 06:31 UTC
Labels: bug, alm-accelerator

**Comment by UvVij99** [comment] 2024-06-12 20:42
@RajeevPentyala  I verified, and configurations for Admin app are done but still it is not working, please re-open this case and assist me what else we can do?

**Comment by RajeevPentyala** [comment] 2024-06-13 08:42
@UvVij99 The original commit issue was addressed in our call; it was due to incorrect pipeline configurations and a missing variable group. Please log a new ticket with the details of the issue you are facing.
