### ISSUE TITLE
[ALM Accelerator - BUG]: pac - Clone or Sync Solution failed

### ISSUE THREAD

**Issue by Yocomd** [microsoft/coe-starter-kit#4014] opened 2022-10-21 00:01 UTC
### Describe the issue

The export_solution_to_git pipeline suddenly started failing during the "pac - Clone or Sync Solution" task.  There was a successful this afternoon, but two hours later, it is consistently failing at this step.  The only changes I am aware of were changes to a flow and fields within the solution.

### Expected Behavior

Continue past this tas

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20221004.2

### Steps To Reproduce

1. In an environment/solution that has already been setup for ALM Accerlator, make some changes to the unmanaged solution and publish changes.
2. In the ALM Accelerator, click the COMMIT button.
3. Error occurs during the "pac - Clone or Sync Solution" task in export_solution_to_git pipeline.

**Comment by thetla** [comment] 2022-10-21 08:11
Same issue with many solutions in our company. This morning it worked and after a little change this error message came again. I hope you can look into this case. It's given us many problems with commits and deployments :) 
![image](https://user-images.githubusercontent.com/114479358/197146632-979b7e1d-31cb-4012-be73-da14d4450407.png)

**Comment by RajeevPentyala** [comment] 2022-10-21 09:05
@Yocomd and @thetla Can you please share the "Power Platform Build Tools" version in your Azure Devops Organization?
![image](https://user-images.githubusercontent.com/104883923/197157370-6c565086-c366-443c-8cac-69d41fc16e90.png)

**Steps to check the Power Platform Build Tools version:**

- Sign in to your organization (https://dev.azure.com/{yourorganization}).
- Select the shopping bag icon, and then select 'Manage extensions'.
- Open the "Power Platform Build Tools" extension.
-

**Comment by thetla** [comment] 2022-10-21 09:48
![image](https://user-images.githubusercontent.com/114479358/197167306-69cb0e68-54ad-442c-8320-2b1280f790ab.png)

**Comment by J3ffr0y3d** [comment] 2022-10-21 11:23
we are having the same issue, just tried to commit a solution and getting the same error

**Comment by RajeevPentyala** [comment] 2022-10-21 12:21
@thetla and @J3ffr0y3d. This error is due to pac cli regression, which got introduced in Power Platform tools (2.0.8) version. We are working with the pac team on priority for the fix. Till pac team release a fix, we will implement a short-term workaround and release a hotfix for 'ALM Accelerator'.

But, If you feel that you are blocked, please perform following steps:
- Go to the Azure DevOps repository with 'ALM Accelerator' build.
![image](https://user-images.githubusercontent.com/104883923/197192340-35b1266a-aa45-457a-99a6-d09c8f9d7ce4.png)

- Open PowerShell/code-first-functions.ps1 file.
- Go to "clone-or-sync-solution" function (Line number 185)
- Replace Line 211 to 218 which is the following code
        _# If .cds project file exists (i.e., Clone performed already) trigger Sync
        if(Test-Path "$cdsProjPath")
        {
            Write-Host "Cloned solution available; Triggering Solution Sync"
            $syncCommand = "solution sync -pca true -f ""$cdsProjFolderPath"" -p Both"
            Write-Host "Triggering Sync - $syncCommand"
            Invoke-Expression -Command "$pacexepath $syncCommand"
        }_
- With this new code
        _# If .cds project file exists (i.e., Clone performed already) trigger Sync
        if(Test-Path "$cdsProjPath")
        {
            Write-Host "Cloned solution available; Triggering Solution Sync"
            $cdsProjfolderPath = [System.IO.Path]::GetDirectoryName("$cdsProjPath")              
            Write-Host "Pointing to cdsproj folder path - " $cdsProjfolderPath
            Set-Location -Path $cdsProjfolderPath
            $syncCommand = "solution sync -pca true -p Both"
            Write-Host "Triggering Sync - $syncCommand"
            Invoke-Expression -Command "$pacexepath $syncCommand"
        }_

- Save the file and retrigger the commit.
- As I mentioned, we are making this change in our build and releasing a hotfix. Please make above change if you are blocked.

**Comment by mikefactorial** [comment] 2022-10-21 15:20
We've released a Hotfix for this issue. 

[11:16 AM] Michael Ochs, MVP (Guest)
Wrong link https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/CenterofExcellenceALMAccelerator-October2022-HF1

You can update your pipelines to take advantage of the fix by following upgrade procedures documented below. The Hotfix release tag is CenterofExcellenceALMAccelerator-October2022-HF1

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config#updating-the-pipelines-in-azure-devops

**Comment by Yocomd** [comment] 2022-10-25 16:25
I just updated to the hotfix and it seems to be working now.  Thanks!

**Comment by mikefactorial** [comment] 2022-10-26 22:18
Closing this out for now. We've merged the hotfix into the November release.

**Closed by mikefactorial** 2022-10-26 22:18 UTC
Labels: bug, alm-accelerator

**Comment by Yocomd** [comment] 2022-11-02 15:17
yes, I was able to install the hotfix and it worked.  Thank you.
