### ISSUE TITLE
error getting while creating a project in ALM accelerator for makers canvas app

### ISSUE THREAD

**Issue by AnubhavPatnaik** [microsoft/coe-starter-kit#1124] opened 2021-09-08 10:53 UTC
### Describe the issue

we are using the same solution - ALM Accelerator for Makers and following the same steps which is mentioned in the msft doc(Set up ALM Accelerator for Makers components - Power Platform | Microsoft Docs).

The error which we are getting while creating a project in ALM accelerator for makers canvas app(The Project Test SOlution creation has failed due to system error) , PFA error screenshot for the same.

Regards,
Anubhav

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

<img width="473" alt="email" src="https://user-images.githubusercontent.com/90198494/132496931-049901e2-c5c9-40ba-9219-0977f249e9e6.PNG">
<img width="760" alt="canvaserror1" src="https://user-images.githubusercontent.com/90198494/132496972-bc942082-de3f-4bdf-8e4a-58cd6ac25ed3.PNG">

**Comment by mikefactorial** [comment] 2021-09-08 12:35
Hi @AnubhavPatnaik,
The easiest way to troubleshoot the issue is to look at the Flow runs that run behind the canvas app. Specifically the CreateProject flow and it's child flows. If you can track down the specific step that fails and the error message associated with the failure that would help to figure out the root cause.

![image](https://user-images.githubusercontent.com/42348035/132509938-9e98c534-d8bb-40d9-b367-119bd4b7096a.png)

**Comment by AnubhavPatnaik** [comment] 2021-09-09 06:17
![image](https://user-images.githubusercontent.com/90198494/132633041-38f20f06-9a22-43e2-832d-5c79882a26a2.png)

getting this error.

**Comment by AnubhavPatnaik** [comment] 2021-09-09 06:18
![image](https://user-images.githubusercontent.com/90198494/132633235-0935e8e2-81e7-4eb2-b715-fb12b55784c6.png)

**Comment by AnubhavPatnaik** [comment] 2021-09-09 06:45
![image](https://user-images.githubusercontent.com/90198494/132636279-990cf50d-4b10-40c5-bbdd-375da6f30ce4.png)

**Comment by AnubhavPatnaik** [comment] 2021-09-09 06:52
i have updated the stageowneremail in the admin alm app
![image](https://user-images.githubusercontent.com/90198494/132637088-9410dd1a-7e16-4d32-b0ed-b171013e7303.png)

but getting assigned is missing

**Comment by AnubhavPatnaik** [comment] 2021-09-09 06:52
@mikefactorial

**Comment by mikefactorial** [comment] 2021-09-09 13:02
@AnubhavPatnaik thanks for the call this morning. Adding notes here for others in case they have similar issues.
1. In order for the project to be provisioned the Owner. User and Password need to be filled out in the Admin app.
2. In new environments where approvals have not been used previously there is an additional step to initialize the Flow approval tables documented here, we'll need to add this to the ALM Accelerator docs since this issue has come up before. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment

**Comment by AnubhavPatnaik** [comment] 2021-09-09 13:14
Thank you so much @mikefactorial for your help :)

Regards,
Anubhav

**Comment by AnubhavPatnaik** [comment] 2021-09-09 13:15
Thanks for the information

**Comment by mikefactorial** [comment] 2021-11-04 17:57
@AnubhavPatnaik closing this issue. Feel free to open another issue if more assistance is required

**Closed by mikefactorial** 2021-11-04 17:57 UTC
Labels: alm-accelerator
