### ISSUE TITLE
[CoE Starter Kit - BUG] - Teams Environment Not getting deleted after successful run of "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" Flow 

### ISSUE THREAD

**Issue by abhishekmaru** [microsoft/coe-starter-kit#726] opened 2021-07-02 11:45 UTC
### Describe the issue

Describe the issue:
We have installed the Governance Component of the COE toolkit, the workflow - "**Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments**" has successful runs however the environments of Types of Microsoft Teams are still not deleted from our Power Platform tenant.

If we go and see the Environments details at COE toolkit, it says deleted on xyz dates but doesn't delete them from tenant. Attached are few screenshots.

### Expected Behavior

The flow should delete the Team environments created 7 days ago and have no business justification, or the business justification has been rejected by the admin. In our case Teams Environments are more than 90 days old with no justification, they should get deleted.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

### Steps To Reproduce

Install the Governance Components.
Wait for the flow Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments to trigger automatically or trigger it manually.

### Anything else?

<img width="565" alt="WF Run" src="https://user-images.githubusercontent.com/82568150/124269688-d7db2380-db58-11eb-9179-37b845f4ed7f.PNG">
<img width="486" alt="Env 1 at Tenant" src="https://user-images.githubusercontent.com/82568150/124269720-e3c6e580-db58-11eb-9c7b-e61f8163d883.PNG">
<img width="644" alt="Env 1- rejected" src="https://user-images.githubusercontent.com/82568150/124269722-e4f81280-db58-11eb-8ec5-ffa6e7fe9198.PNG">
<img width="432" alt="ENV 1" src="https://user-images.githubusercontent.com/82568150/124269725-e590a900-db58-11eb-97fa-d79c47f9fe03.PNG">
<img width="615" alt="Env 2 - deleted" src="https://user-images.githubusercontent.com/82568150/124269726-e6293f80-db58-11eb-8a57-e57533b829e3.PNG">
<img width="433" alt="Env 2" src="https://user-images.githubusercontent.com/82568150/124269728-e6c1d600-db58-11eb-8bf6-9a86afcf952a.PNG">
<img width="482" alt="Team Env details" src="https://user-images.githubusercontent.com/82568150/124269732-e75a6c80-db58-11eb-99ca-bb45c864b05e.PNG">

**Comment by JeneferM-MSFT** [comment] 2021-07-02 13:02
Hello. I do not repro. From the sound of it, you are trying to back-apply this policy on environments made before you turned on these flows. Is that accurate? That will not work, by design, with the flow as is. 

We have a time stamp upon which we rely that isnt created time, its when we asked for the business justification. The reason we do this is so that a bunch of pre-existing environments wont get deleted just by turning on the flows, as in this case the user never got asked to supply business justification.

If you are trying to bulk delete old teams environments intentionally you will need to mark up that date in order to have them enter the flow. 

Hope that makes sense. And thanks for using CoE

![image](https://user-images.githubusercontent.com/62659043/124277742-a20b5000-db02-11eb-8522-6e35d653f800.png)
![image](https://user-images.githubusercontent.com/62659043/124277899-cd8e3a80-db02-11eb-8702-d3e705c862c1.png)

**Comment by JeneferM-MSFT** [comment] 2021-07-08 14:17
closing out as no further action for CoE team.

**Closed by JeneferM-MSFT** 2021-07-08 14:17 UTC
Labels: coe-starter-kit
