### ISSUE TITLE
[ALM Accelerator - QUESTION] About Deployment Settings

### ISSUE THREAD

**Issue by J3ffr0y3d** [microsoft/coe-starter-kit#3948] opened 2022-10-13 12:46 UTC
### What is your question?

Hi, Im wondering, which deployment settings does ALM use for deployment? as its sets variables to the deploy pipelines, but in the latest release now it also has under the branch folders validation/test/prod with customDeploymentSettings.json & deploymentSettings.json. 
i ask as when i recently committed a solution and then tried to deploy to validate it failed at activate flows got the error
`Cannot convert value "hq" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).` which presume was looking at the customDeploymentSettings.json
![image](https://user-images.githubusercontent.com/95473533/195599835-d5fd18ac-fe21-4ca5-b151-b1bddf414f64.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

October 2022 release

**Comment by mikefactorial** [comment] 2022-10-17 14:30
@J3ffr0y3d the pipelines use customDeploymentSettings.json and deploymentSettings.json for deployment. The variables on the pipelines are used to replace the tokens in these files (e.g. #{somevariablethathasavalueonthepipeline}). I'm going to close out this issue since the error in question is a duplicate of #3947.

**Closed by mikefactorial** 2022-10-17 14:30 UTC
Labels: question, alm-accelerator
