### ISSUE TITLE
[ALM Accelerator - Feature]: Remove impersonation workaround for turning off flows

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#3014] opened 2022-06-20 13:03 UTC
### Describe the solution you'd like

Once this capability is rolled out globally, we need to clean up our impersonation workaround.
https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/ownership-supported-service-principals

The guidance will be for the individual user who created the connection to share the connection with an SPN.  We should consider some UI convenience in the canvas app to make it easier to share the connections with the correct SPN in the target environment (perhaps via querying app users).

**Comment by devkeydet** [comment] 2022-06-20 13:34
For this one, if we remove our workarounds and customers HAVE NOT shared their connections with the SPN that imports the solution, the flow will still not turn on after import.  So, to help guide customers down the happy path, we should consider whatever we can do to ensure everything is in a working state after import.  That probably means proactively checking if the connections are shared with the SPN before we attempt to initiate a pipeline that does a solution import.  Also, helping the maker using the canvas app to get to a healthy state prior to any solution import.

**Comment by mikefactorial** [comment] 2022-11-29 16:58
Duplicate of #[#3306](https://github.com/microsoft/coe-starter-kit/issues/3306)

**Closed by mikefactorial** 2022-11-29 16:58 UTC
Labels: enhancement, alm-accelerator
