### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (PVA) - GetBotID failed

### ISSUE THREAD

**Issue by Samuel-Dittmann** [microsoft/coe-starter-kit#2637] opened 2022-05-05 09:57 UTC
### Describe the issue

The problem happens in the "Get Parent Bot ID" scope when the Action "List bot for a botcomponent" action returns an empty array. The following action then fails. 

### Expected Behavior

The Flow should not fail.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Anything else?

InvalidTemplate. Unable to process template language expressions in action 'GetBotID' inputs at line '0' and column '0': 'The template language expression 'first(body('List_bot_for_a_botcomponent')?['value'])['botid']' cannot be evaluated because property 'botid' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.

botcomponentid eq 97593d44-a7a8-448e-b1f4-08d8473efc19, c764cd74-47eb-47aa-9a1f-0a44b315d4dd and 10 more (out of 46)

**Comment by Jenefer-Monroe** [comment] 2022-05-05 12:14
Hello, this is known and fixed in the May release https://github.com/microsoft/coe-starter-kit/issues/2585
The product team installed a solution in environments which had bot components but no bot, this violated assumptions we had made in the flow. Addressed now in the latest version of Core.  
Duplicate of #2585

**Closed by Jenefer-Monroe** 2022-05-05 12:14 UTC
Labels: bug, coe-starter-kit
