### ISSUE TITLE
[CoE Starter Kit - BUG] Are Power BI Reports only available to analyze/view on the production type environment and not sandbox?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2936] opened 2022-06-07 22:26 UTC
### Describe the issue

Hi Team,

I am currently working on the latest CoE kit in the sandbox environment. However, the Power BI dashboard setup link https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi  says that it can be only viewed on the production environment.

Would you please share if I can review the Power BI dashboard on the sandbox type environment? If not, what needs to be changed or it's not at all possible?

Looking forward to hearing from you!

Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power BI Reports

**Comment by Jenefer-Monroe** [comment] 2022-06-07 22:31
Hello. The language is confusing, apologies. 

By production here we mean, as apposed to in a Dataverse for Team environment. The way that PBI can connect to these envt types is different, so:

- Production_CoEDashboard_May2022 ==> For production, sandbox, or trial type environments
- Teams_CoEDashboard_May2022 ==> For D4T type environments

Hope that helps!

**Comment by tomsinsight** [comment] 2022-06-07 23:23
Great, thank you very much to clarify with the prompt response! 

I also see that the latest CoE Reports asks to install latest Power BI dashboard as well, when I do that, I am unable to login as it keeps bringing following screen after signing in + click on "Connect" without any error:

![image](https://user-images.githubusercontent.com/98403757/172499489-6ddfce4b-025f-4742-b52d-ff3e074dccf2.png)

could this be due to 'sandbox' environment? or specific settings needs to be done for the latest CoE report? as the previous CoE reports are opening without any issues. Any clue?

Note: I have tried opening run as admin and without admin - both have the same issue as described above

**Comment by Jenefer-Monroe** [comment] 2022-06-08 13:53
I have seen some customers hit this, the issue is in Power Bi itself. You will see it if you boot Power Bi and just try to add a Dataverse data source.  I'm afraid you will need to create a support ticket.

**Comment by Jenefer-Monroe** [comment] 2022-06-15 21:54
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-06-15 21:54 UTC
Labels: bug, coe-starter-kit
