### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by GemmaBrownImpellam** [microsoft/coe-starter-kit#9257] opened 2024-11-14 07:33 UTC
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I have upgraded our CoE kit to the latest version, following the steps to import the Center of Excellence Core Components zip file from the latest release. I did this on 05/11/2024. The import does says success, however when I review the CoE Admin Command Center it suggests that the CoE kit solution was installed in April 2024. Further to this when I click into the Power Platform Admin View (model-driven app) I cannot see the environments we have set up back in May time. Additionally, the DLP Impact Analysis isn't running correctly, I know the DLP I am applying against an environment will have impacted Flows/Apps but the App it returns 0 issues. 

### Expected Behavior

Expected behaviour, the install should be installed correctly and not presenting an error message in the CoE Admin Command Center to say it's not been installed since April 2024. The Power Platform Admin View should be up to date including any new additions (environments etc.) The DLP impact analysis should be highlighting impacted flows/apps and not returning a 0 value. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Data Policy Impact Analysis; CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In environment 'IMPELLAM_COE_PROD'
2. In Apps > Data Policy Impact Analysis > Play
3. Select A DLP from the list
4. Edit and run the Steps select the environment to check Impact against
5. The results instantly return 'Impacted Apps (0) Impacted Flow (0) as thought nothing has run to check

1. In environment 'IMPELLAM_COE_PROD'
2. In Apps > CoE Admin Command Center > Play
3. Error message is presented on the banner 
4. Select 'Power Platform Admin View'
5. Active Environments do not appear that are active

**Comment by GemmaBrownImpellam** [comment] 2024-11-18 15:53
Impellam - Public

Hi

1. Understood
2. Security roles are being checked. How do I check that the inventory run has completed?
3. Understood, to be investigated after point 1 & 2

Best regards,
Gemma



Impellam - Public

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-11-18 16:45
The inventory run will be complete (for environments) when the Driver flow completes: Admin | Sync Template v4 (Driver)

**Comment by GemmaBrownImpellam** [comment] 2024-11-19 11:10
Impellam - Public

Hi

I've just kicked it back off again,

Also, I checked the history and this has run successfully on previous days.

[cid:a62de652-8c09-4c97-9758-2d46f4275316][cid:700ad5a1-d2bb-4590-891e-df041de76b30]


I've checked the Power Platform Admin View, the new environment created earlier this year still are not appearing in this view.


[cid:3f087c57-4ee0-4375-b84d-f07ec5529631]

Best regards,

Gemma



Impellam - Public

________________________________

**Comment by GemmaBrownImpellam** [comment] 2024-11-19 11:45
Impellam - Public

Also, the Power Platform admin account running the flow is set to Direct and Permanent.

The DLP still isn't running.

What are the next steps please?

Best regards,
Gemma



Impellam - Public

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-11-19 12:51
Is your inventory up to date now? Previously you said that it was not gathering environments.

**Comment by GemmaBrownImpellam** [comment] 2024-11-19 15:05
Impellam - Public

I can not all the environments in 'Power Plaform Admin View' the active environments do not contain the new ones we created early this year. Power Platform Admin View<https://org9b179d82.crm11.dynamics.com/main.aspx?appid=00335d0b-fce5-ee11-904d-002248425de8&pagetype=dashboard&id=cf839870-ff70-e911-a833-000d3a375590&type=system&_canOverride=true#>



Impellam - Public

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-11-19 19:04
Go to the most recent run of **_Admin | Sync Template v4 (Driver)_**
Are all environments returned here?

![Image](https://github.com/user-attachments/assets/b92b58f6-c330-42b8-b025-d5435e3205a4)

**Comment by Jenefer-Monroe** [comment] 2024-11-25 13:30
Hello, my latest question is above, I've repasted for your ease of reading

Great, please note the position of the missing envts in the output array (ex record 6 of 11)

Then find the envt in this array, you can make sure you found it by checking whats returned in the **_Get Environment as Admin - see if it still exists_** call

Does it pass through and do an update?
![Image](https://github.com/user-attachments/assets/b9a44a08-42bc-4c71-99b1-22209bc7d945)

**Comment by GemmaBrownImpellam** [comment] 2024-11-27 10:48
Impellam - Public

Hi Jenifer,

I followed your instructions, and I have pasted my screen shot. It doesn't appear the same as yours. Is it worth us doing a screen share, I'm conscious this ticket has been on-going for some weeks now. Are you free for a team call/screen share?

[cid:bddb39ad-cc64-48e8-af8e-ad55bb61e899]

[cid:06cd0618-3318-40b2-84f1-07a541d95098]

Best regards,
Gemma


Impellam - Public

________________________________

**Comment by GemmaBrownImpellam** [comment] 2024-11-27 13:40
Hi Jenifer, 

I followed your instructions, and I have pasted my screen shot. It doesn't appear the same as yours. Please advise next steps


[Admin Syn Template v4 (Driver).docx](https://github.com/user-attachments/files/17935142/Admin.Syn.Template.v4.Driver.docx)

**Comment by GemmaBrownImpellam** [comment] 2024-11-27 14:18
Impellam - Public


I've responded through the GitHub, so hopefully the images will show.

Thanks
Gemma



Impellam - Public

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-11-27 19:58
thanks I did get your attachement. 

My ask was for you to see if your missing envts are returned from this call. Have you validated that? 
![Image](https://github.com/user-attachments/assets/764d6b6c-9436-4d21-ada3-69225a110501)

**Comment by GemmaBrownImpellam** [comment] 2024-11-28 11:14
Hi Jennifer, please see my steps and comments. 

[Screen shots for CoE kit.docx](https://github.com/user-attachments/files/17947173/Screen.shots.for.CoE.kit.docx)

Please advise next steps

Thanks
Gemma

**Comment by GemmaBrownImpellam** [comment] 2024-11-28 11:39
Impellam - Public

I've replied in GitHub with screen shots and comments.

Best regards,
Gemma



Impellam - Public

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-11-30 14:25
That dashboard does not show all environments. Can you please see if your environments are in the list of environments? 

![Image](https://github.com/user-attachments/assets/cbd01e87-f441-4a44-9fe4-5c84db516b29)

**Comment by GemmaBrownImpellam** [comment] 2024-12-01 13:52
[Step one.docx](https://github.com/user-attachments/files/17969115/Step.one.docx)

Yes, I see the environments in there. Please can you advise why the DLP policy isn't running over an environment, this was another query I had in the CoE Kit. I've created a DLP but when I run the DLP against an environment it doesn't pick up that there's any flows or apps impacted but I know there are ones that will be impacted. 

Please see screenshots attached of steps taken. 

Best regards, 
Gemma

**Comment by Jenefer-Monroe** [comment] 2024-12-02 13:29
OK it sounds like your inventory issue is resolved. 

My concern would be that it resolved while we were working together only, which means the issue is likely the following. So I'll put that back here and allow you to go validate:

## Permissions
Please validate that the inventory run has completed (Driver flow completed successfully) 
Please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently.
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by GemmaBrownImpellam** [comment] 2024-12-03 07:01
Impellam - Public

That worked, thank you, it is returning affected apps and flows now.

Is our CoE kit upgraded now, do we need to do anything else with it?


Best regards,
Gemma


Impellam - Public

________________________________

**Comment by Jenefer-Monroe** [comment] 2024-12-03 13:06
YEAH! Glad we persisted and got you unblocked. 
It seems like you are good now. Please do feel free to return with other questions in the future though.

**Comment by GemmaBrownImpellam** [comment] 2024-12-03 13:22
Hi Jenefer, 

Why don't my active environments show in my visual?

Please see attached screen shot. 

Best regards, 
Gemma[Active environments visual.docx](https://github.com/user-attachments/files/17993495/Active.environments.visual.docx)

**Comment by Jenefer-Monroe** [comment] 2024-12-09 14:16
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-12-09 14:16 UTC
Labels: bug, coe-starter-kit
