### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Solution Fails but Duplicates Power Apps in CoE Solution

### ISSUE THREAD

**Issue by dragunwing** [microsoft/coe-starter-kit#1983] opened 2022-02-08 16:44 UTC
### Describe the issue

I've tried installing the Nurture Components several times, receiving an error that it "fails to import."  As I was reviewing the Apps section of the CoE environment, I noticed that there are duplicated Power Apps that have time stamps appended to the names referring to each time I tried re-installing the Nurture Components. The duplicated apps are:

- Power Platform Training Management
- Template Catalog
- Power Platform Training Registration
- Maker Assessment
- Maker Assessment Admin App

My questions are:

1.  How do I get the Nurture Components to install correctly?
2.  Should the duplicated apps be removed?  If so, how is the best way to do so, without affecting the first installation of the apps bulleted above?

### Expected Behavior

I expect the Nurture Components to install correctly _and_ that the Power Apps not get duplicated.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

CenterofExcellenceNurtureComponents_2.6_managed.zip

### Steps To Reproduce

I am repeatedly getting the same error, regardless of signing out of the Power Apps Admin portal and clearing my cache & browsing history.

### Anything else?

![NurtureInstallErrorMessage](https://user-images.githubusercontent.com/11412139/153033786-760fc758-7f72-4ca2-a093-9fbb857e531d.png)

![NurtureInstallDuplicationError](https://user-images.githubusercontent.com/11412139/153034048-cd8d6688-3b9b-4ea1-a103-c6eb4e257e85.png)

**Comment by Jenefer-Monroe** [comment] 2022-02-11 13:36
Hello, I'm afraid that I cannot assist here, you are in an unknown state. What features are you already using within Nurture? This will help me know if I can advice a clean install.

**Comment by dragunwing** [comment] 2022-02-11 14:16
I have not been using any Nurture Components yet.  This was from my first attempts at installing those components.

When you mention "clean install," does that refer to just the Nurture Components or the entire CoE components?

If I delete the following apps (including the duplicated versions of these), should that be enough to clear out the Nurture Components that did get installed but never finished (Essentially, are these items just part of the Nurture Components and can be removed without affecting the Core Components or Governance Components)?

- Power Platform Training Management
- Template Catalog
- Power Platform Training Registration
- Maker Assessment
- Maker Assessment Admin App

**Comment by Jenefer-Monroe** [comment] 2022-02-11 14:18
Yes I just mean Nurture. I would suggest deleting the Nurture solution to get us back to a clean state. No need to touch Gov/Core.

**Comment by dragunwing** [comment] 2022-02-11 14:19
I'm commercial only.

**Comment by Jenefer-Monroe** [comment] 2022-02-11 14:23
Thanks, asking as there were some issues with those tenant types and this solution. 
I would suggest deleting Nurture completely here since you havent started using it. Then trying to install again. If it still fails, I would suggested deleting again and then waiting until March release. 
Note that we are removing the component that has been causing install issues in the March release (see #1889)

**Comment by Jenefer-Monroe** [comment] 2022-02-11 16:22
Wow you are in a strange state. 
Yes please just delete all the Nurture apps, both the duplicates and the original, manually. 
And then do the same for the flows (you may have to look in the Default Solution for these)
You can find the list of all the apps and flows from Nurture here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/nurture-components

**Comment by Jenefer-Monroe** [comment] 2022-02-17 13:26
I'm going to close this one out as a dupe to #1889 as taht is the cause of all these install issues with Nurture. 
If you still struggle with the install please wait for March release and try then. 
Duplicate of #1889

**Closed by Jenefer-Monroe** 2022-02-17 13:26 UTC
Labels: coe-starter-kit
