### ISSUE TITLE
[ALM Accelerator - BUG]: Overwriting readonly variable 'TriggerSolutionUpgrade' is not permitted

### ISSUE THREAD

**Issue by alanrroberts** [microsoft/coe-starter-kit#3256] opened 2022-07-22 13:53 UTC
### Describe the issue

When setting a TriggerSolutionUpgrade variable to try and perform an upgrade I receive the following error in the "Set TriggerSolutionUpgrade Variable" step

```
##[error]Unable to process command '##vso[task.setvariable variable=TriggerSolutionUpgrade;isOutput=true]false' successfully.
##[error]Overwriting readonly variable 'TriggerSolutionUpgrade' is not permitted.
```

As I understand it pipeline variables are immutable so the powershell script that tries to set this variable errors as it already exists.

### Expected Behavior

An upgrade of the solution to run

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2022

**Comment by mikefactorial** [comment] 2022-07-22 14:17
@alanrroberts making sure I understand the issue here. You are setting the TriggerSolutionUpgrade variable on the pipeline and the issue is when the pipeline tries to set it correct? We should be handling that situation and will look into fixing this assuming I understand the issue correctly.

**Comment by alanrroberts** [comment] 2022-07-22 14:33
Hi @mikefactorial, I've just been playing a bit more and it may be an issue with my understanding of where to configure the variable.  I was initially setting the variable for an individual run of the pipeline, rather than for the pipeline as a whole.  I have it running new that I have set it on the pipeline which gave me the option of allowing the variable to be overwritten.  This option wasn't there for a run only variable.

Cheers

Alan

**Comment by mikefactorial** [comment] 2022-07-25 14:50
Thanks for reporting back @alanrroberts. Closing this out for for now. We have an existing backlog item to expose this as part of the deployment process in the app which would make it easier for makers to decide when an upgrade should happen, but it's good that it can be overridden at the pipeline level.

**Closed by mikefactorial** 2022-07-25 14:50 UTC
Labels: bug, alm-accelerator
