### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to view "Individual Admin" environment variable in the Core componenets

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2973] opened 2022-06-10 14:33 UTC
### Describe the issue

Hi Team,

I have just upgraded the Core components solution 3.39, however I do not see the variable "Individual Admin" as a part of the solution as described in the Microsoft docs - is that ok?

Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Individual Admin

**Comment by tomsinsight** [comment] 2022-06-10 16:07
I have just started all the flows of Core components; however I do not see more option than these at the moment in command centre app, probably it would take some time to appear?
![image](https://user-images.githubusercontent.com/98403757/173106638-c79c8221-234e-4147-b87e-955487e52f7b.png)

Maybe I need to wait some more time to verify your steps?

**Comment by tomsinsight** [comment] 2022-06-10 16:39
Sorry my bad, I was looking into the MCA instead of ACA!

With respect to the question, no I do not see the variable there too as indicated in the following screen in the ACA:
![image](https://user-images.githubusercontent.com/98403757/173112248-508a5656-48ae-4f48-8e34-58fa463637f8.png)

any clue?

**Comment by Jenefer-Monroe** [comment] 2022-06-10 17:33
Do you have unmanaged layers on that app?

**Comment by tomsinsight** [comment] 2022-06-13 13:19
No, This app has been deployed very first time, so there is no unmanaged layer. Also, the "Individual Admin" environment variable is not available in the default solution too - just for the info.

**Comment by Jenefer-Monroe** [comment] 2022-06-13 16:27
Can you please share a picture of these three things for me? 
1. You solution list such that I can see the Core solution as shown like this
![image](https://user-images.githubusercontent.com/89584709/173399674-a5f4edf8-5c4a-4314-83e4-65952bbfca4b.png)
2. Solution layers for the app
![image](https://user-images.githubusercontent.com/89584709/173399870-c875af88-2a51-427b-a810-d8da75d3d7d2.png)
![image](https://user-images.githubusercontent.com/89584709/173399948-67fed4b7-f99b-40a9-bb8f-951b7ce43e09.png)
3. Solution layers on this environment variable? Look for admin_ApprovalAdmin (The old name)
![image](https://user-images.githubusercontent.com/89584709/173400326-d177a441-3187-4399-961b-2047e3665ab3.png)
![image](https://user-images.githubusercontent.com/89584709/173400457-465ecd87-b733-408d-8134-df313663b5a5.png)

**Comment by tomsinsight** [comment] 2022-06-14 18:07
Sure, please find them as follows:

**Screenshot 1:**
![image](https://user-images.githubusercontent.com/98403757/173658350-5eb8a605-b906-4e18-95c4-5183d8391d03.png)

**Screenshot 2:**
![image](https://user-images.githubusercontent.com/98403757/173658582-9cc365cf-165e-454f-8361-9175215bec23.png)


**Screenshot 3 (When I type admin in the searchbox):**
![image](https://user-images.githubusercontent.com/98403757/173658951-f6162dc7-d57a-4dab-8bf5-3abec0a61333.png)

There is no individual Admin environment variable exist at the moment, therefore I could not share the suggested screenshot - in fact, that;s the issue for me at the moment that why it's not visible or it's renamed?

**Comment by tomsinsight** [comment] 2022-06-14 18:19
It seems like that the "Approval Admin" is an "Individual Admin" based on the internal name and the screenshot from your end. Probably the display name has not been changed as it's mentioned in the document?

**Comment by Jenefer-Monroe** [comment] 2022-06-14 20:36
Yes I think the issue is that you have an unmanaged layer on this env variable. Its the display name that has changed. 
![image](https://user-images.githubusercontent.com/89584709/173683944-775d0c92-e46b-4644-a8d7-9855a57e1966.png)

**Comment by tomsinsight** [comment] 2022-06-14 23:06
yes, that's correct, I had an unmanaged layer on this environment variable, however as per the documentation, I assumed that only canvas apps and flows unmanaged layer to be removed - therefore I did not consider strongly to remove the unmanaged layer for the environment variables.

I was wondering if "removing unmanaged layer" to be considered for "All" the components of the solution only "Canvas apps and flows" ?

Also, since I have not removed the unmanaged layer for this variable, I did not get the latest update, what should I do in this case in order to update the environment variable with "Individual Admin"?

Thank you very much for your time in advance!

**Comment by Jenefer-Monroe** [comment] 2022-06-15 13:36
Yes the topic is very confusing and the product team is working on making it more clear. 

You can remove the unmanaged layer, that way you will see the new display name. 
Then you can reapply your value to the env variable and then you will have the new display name and your current value. See [updating environment variables](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables) for a reminder on how to do that.

**Comment by tomsinsight** [comment] 2022-06-15 16:26
Perfect!! Appreciate your help, patience and understanding!

**Comment by Jenefer-Monroe** [comment] 2022-06-15 18:27
You are so welcome, thank you for using CoE!

**Comment by Jenefer-Monroe** [comment] 2022-06-15 21:55
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2022-06-15 21:55 UTC
Labels: bug, coe-starter-kit
