### ISSUE TITLE
[CoE Starter Kit - QUESTION] Problem with Admin Command

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2240] opened 2022-03-14 16:57 UTC
### What is your question?

Hello, I was changing some parameter inside the app anche the left menu disappear.. How I can fix it?

<img width="592" alt="command-center" src="https://user-images.githubusercontent.com/101250592/158221092-dde22ebb-9bcd-43e7-9146-dc680bf6e295.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment] 2022-03-14 17:00
hello, what do you mean by this? 

> I was changing some parameter inside the app

Were you editing the app in the Maker?

**Comment by JackSocini** [comment] 2022-03-14 17:09
I ahve the italian version installed on my tenant and I was change some variable that gives error with the maker. When I came back to the available oldest version of the app the app crash completly..

<img width="959" alt="error" src="https://user-images.githubusercontent.com/101250592/158224190-8edf5184-d57d-41a0-abfe-29a96b5cb135.png">

**Comment by JackSocini** [comment] 2022-03-15 07:51
I have already add english pack. But the app doesn't fix language problem automatically..

<img width="617" alt="LANGUAGE" src="https://user-images.githubusercontent.com/101250592/158330947-65b31f42-58b3-42fd-86eb-b4d2c78e17f9.png">

**Comment by Jenefer-Monroe** [comment] 2022-03-15 13:48
I'm afraid I cannot help you understand your current state as you are trying to edit the app and make it behave in a customized way. But if you return to the state in which we shipped, you can share here what doesnt work out of the box for you, and I can try to see what we need to change.

**Comment by javiermga-inditex** [comment] 2022-03-16 12:25
Hi @Jenefer-Monroe,

I'm getting exactly the same error in a fresh, clean (not customized), CoE Starter Kit setup in English.

All other applications run without any problem, but `Admin - Command Center` throws this error when any user try to play it.

![AdminCommandCenter_Error](https://user-images.githubusercontent.com/101564333/158589276-69db1772-d5c0-4304-9a03-647393b47ea8.png)

**Comment by JackSocini** [comment] 2022-03-16 14:22
I came back to the first version with comment "update metdata".

My version is: Power Apps 3.22031.21

**Comment by Jenefer-Monroe** [comment] 2022-03-16 16:03
We will track all these via #2218 
Duplicate of #2218 
closign this one as dupe so that we will track all the information in one place

**Closed by Jenefer-Monroe** 2022-03-16 16:03 UTC
Labels: question, coe-starter-kit

**Comment by manuelap-msft** [comment] 2022-03-17 09:35
Hello, we have confirmation from the Power Apps Player team that this got fixed now, can you re-try to see if you're still experiencing the issue? Thank you!
