### ISSUE TITLE
[CoE Starter Kit - BUG] Solution dependencies exist, cannot uninstall - ObjectName: admin_CoECoreDataverseLegacy

### ISSUE THREAD

**Issue by BB-BITS** [microsoft/coe-starter-kit#8435] opened 2024-06-06 20:45 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Trying to install version 4.31 of Core Components, I am getting this error message:  Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoECoreDataverseLegacy, Id: 42bc24da-56ac-40ba-a62b-068bd256d7bf, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CloudFlowOperations, Id: 6093b58a-4fea-eb11-bacb-000d3a578f6c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published .

I tried to delete the workflow HELPER - CloudFlowOperations. but received an error saying I could not delete from a managed solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Upgrading Core Components

### What method are you using to get inventory and telemetry?

None

AB#3508

**Comment by Jenefer-Monroe** [comment] 2024-06-07 15:58
This is a connector we removed from the kit. Likely you have attached yourself to it in your own flows accidently. 

Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)

The 17 shown here will be cleaned up for you from the install. You must have others there that are local to your environment
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b5e8e64-e32f-43d6-a6de-ce45a04b5925)

**Comment by BB-BITS** [comment] 2024-06-07 19:01
You are correct.  There is one called CLEANUP HELPER - Check Deleted (Solutions).

 How do I get rid of this dependency?

[cid:024768c7-566b-475d-b7c9-a666cf899ed7]

[cid:aa4bbf6a-e9a4-4d45-ad4f-675ba44d75c0]

[cid:11c1bef0-ab41-4d62-9367-4316974b9051]
Bryan
________________________________

**Comment by Jenefer-Monroe** [comment] 2024-06-07 19:23
ok thank you for exploring. That is one of our flows, and it seems you've hit a strange product issue we've seen a few others hit around upgrades:
-----------

Please see https://github.com/microsoft/coe-starter-kit/issues/8130

There is a product bug around deleting a parent and child flow at the same time which is hitting some envts. 
This is due to us cleaning up all the old v3 inventory flows. 

A workaround has been tested and is described here: https://github.com/microsoft/coe-starter-kit/issues/8130#issuecomment-2101226902

--------------

Can you please try that workaround and then try again?

**Comment by BB-BITS** [comment] 2024-06-12 18:10
I was able to install the new version, thank you.  The previous version, 4.17, will not delete however.  The error indicates a dependency exists, which it shows as:

[cid:050d05ab-5f44-4351-b0de-068bfba6a317]
Bryan
________________________________

**Comment by Jenefer-Monroe** [comment] 2024-06-12 20:11
The picture did not come through. Note that the install did not work if the old one was not un-installed, so you will need to resolve this yet. 

Unfortunately you've hit a product bug around upgrade. 
The issue is around dependency ordering. 
Flow X uses Connection Y
Both Flow X and Connection Y are deleted as part of the upgrade
The product is attempting to delete Connection Y before Flow X, which is cannot do. 

As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again

Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)


The product team is aware of this issue but the fix has not yet come out.

**Comment by Jenefer-Monroe** [comment] 2024-06-18 11:37
closing out as no further action for starter kit team

**Closed by Jenefer-Monroe** 2024-06-18 11:37 UTC
Labels: bug, coe-starter-kit
