### ISSUE TITLE
[CoE Starter Kit - BUG]: Publish Theme

### ISSUE THREAD

**Issue by wimbervoetsjtbc** [microsoft/coe-starter-kit#588] opened 2021-06-08 14:34 UTC
**Describe the bug**
I have a problem publishing a newly created theme. When I click the publish button the app navigates to the "Publish Screen" but only the static text is displayed. I don't get a text line to copy and there is no posibility to upload a file.

**Component:**
 - Theming
 -  1.2
 - App

**To Reproduce**
1. Download and import solution in PowerApps (https://aka.ms/coestarterkitdownload)
2. Play "CoE Theme Editor"
3. Create a new theme
4. Save and publish 

**Expected behavior**
A "publish screen" with a line of code to copy and the possibility to upload 2 msapp files

**Screenshots**
![image](https://user-images.githubusercontent.com/85567727/121202504-a2069000-c875-11eb-8a26-07e99111d146.png)
![image](https://user-images.githubusercontent.com/85567727/121202666-c19db880-c875-11eb-91df-342a12291823.png)
![image](https://user-images.githubusercontent.com/85567727/121202961-0164a000-c876-11eb-95cd-5af0e15ece8e.png)
![image](https://user-images.githubusercontent.com/85567727/121203085-1d684180-c876-11eb-97f5-e0b7c33ca5d3.png)

**Additional context**
- PrimaryColor4Value seems to change every time I reopen the app.
- AppChecker displays 13 formula errors
- The "CoE Theme Gallery" app doesn't display the created theme

**Comment by wimbervoetsjtbc** [comment] 2021-06-21 09:34
Any idea on when I can expect an update on this issue?

**Comment by charrisonfuji** [comment] 2021-08-03 07:50
@wimbervoetsjtbc  try my workaround here this has worked for me and other people  https://github.com/microsoft/coe-starter-kit/issues/553#issue-908374101

**Comment by mikefactorial** [comment] 2021-08-03 14:21
Closing this for now duplicate of #402. Will update on that issue

**Closed by mikefactorial** 2021-08-03 14:21 UTC
Labels: theming
