### ISSUE TITLE
Timeout when loading solution import experience

### ISSUE THREAD

**Issue by tewatkin** [microsoft/coe-starter-kit#5324] opened 2023-04-18 23:06 UTC
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Microsoft Support guided me to this page.  The end customer is Armstrong Group of Companies.  I am their CSAM reporting the issue on their behalf.  
As part of a CSA-e led session, we followed pre-requisite steps to deploy COE found here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup?source=recommendations

When installing "CenterofExcellenceCoreComponents_x.xx_managed.zip", the attached error is observed when importing the solution. 
Issue is reproduced in multiple environments and 2 separate accounts.
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/131213373/232922468-58cf8bc2-4531-4f06-a858-ac0856ae6749.png)

### Expected Behavior

COE installs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CoE Starter Kit April 2023

### What app or flow are you having the issue with?

COE

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Customer tried in 2 enviroments but unable to import solution.  Microsoft Engineer tried in her developer environment and was able to install.  Error code does not indicate exactly what the issue is.

### Anything else?

Microsoft was helping customer with their install of COE and ran into error.   Since not supported its hard to trouble shoot the issue for the customer so CSAM not sure where to get help.

**Comment by manuelap-msft** [comment] 2023-04-19 07:39
This error seems to happen before the CoE kit even imports, so I'm not sure how the error can be related to the CoE Starter Kit. This is just the default solution import experience - are you able to try importing another solution with connection references and check if you get the same issue there? 

Sorry we wouldn't be able to help further here as the issue is not with the capability of the kit, but with core platform capability of importing solutions.

**Comment by manuelap-msft** [comment] 2023-04-19 14:56
Thank you - yes, unfortunately we've seen a few times that as soon as you mention CoE kit, you get re-directed to us; sorry you experienced this as well! 

Hopefully it was only a temporary issue and is resolved now; we've not seen this before and I wasn't able to repo it in our tenant either!

**Comment by tewatkin** [comment] 2023-04-19 15:04
The issues was resolved.  It was related to the environment being new and provisioning / permissions were still working through the systems.

Thank you again for your response and assistance.


Teri Watkins
Sr. Customer Success Account Manager (CSAM)
***@***.******@***.***>
Phone: 469-775-1093 | Mobile : 469-585-8550
Premier Support: 1-800-936-3100  | Premier Support: https://serviceshub.microsoft.com<https://serviceshub.microsoft.com/>
My business hours are M-F 8:00-5:00 CST
[Microsoft]

Feedback? Contact my Manager, Andrea ***@***.***>

**Comment by manuelap-msft** [comment] 2023-04-19 15:06
Wonderful, thanks for letting us know what the issue was as well - we'll keep that in our mental wiki if it comes up again!

**Comment by manuelap-msft** [comment] 2023-04-19 15:11
I'll close this issue but please let us know if you have further issues with the setup!

**Closed by manuelap-msft** 2023-04-19 15:11 UTC
Labels: question, coe-starter-kit
